### PR TITLE
ABcDeFx - Volumes & Fees

### PR DESCRIPTION
**Pull request by ftm1337**

### CODE REVIEW

**Comment by llamatester** [comment]
The abcdefx adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    dexs/abcdefx/index.ts(83,49): error TS2552: Cannot find name 'Chain'. Did you mean 'CHAIN'?
    
    Done in 2.95s.

**Comment by llamatester** [comment]
The abcdefx adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    dexs/abcdefx/index.ts(89,14): error TS2304: Cannot find name 'kava'.
    dexs/abcdefx/index.ts(112,18): error TS2304: Cannot find name 'kava'.
    dexs/abcdefx/index.ts(127,14): error TS2304: Cannot find name 'kava'.
    
    Done in 3.56s.

**Comment by llamatester** [comment]
The abcdefx adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    dexs/abcdefx/index.ts(89,14): error TS2304: Cannot find name 'kava'.
    dexs/abcdefx/index.ts(112,18): error TS2304: Cannot find name 'kava'.
    dexs/abcdefx/index.ts(127,14): error TS2304: Cannot find name 'kava'.
    
    Done in 3.81s.

**Comment by llamatester** [comment]
The abcdefx adapter exports: 
        
 
 _______________________________________
    Dexs for 16/6/2023
    _______________________________________
    
    KAVA 👇
    Backfill start time: 29/1/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 1461.24277950808
    Timestamp: 1686959998
    
    
    
    
    Done in 23.93s.

**Comment by llamatester** [comment]
The abcdefx adapter exports: 
        
 
 _______________________________________
    Dexs for 16/6/2023
    _______________________________________
    
    KAVA 👇
    Backfill start time: 29/1/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 1461.24277950808
    Timestamp: 1686959998
    
    
    
    
    Done in 23.80s.

**Comment by ftm1337** [comment]
thats right ser llamatester.  o7

**Comment by llamatester** [comment]
The abcdefx adapter exports: 
        
 
 _______________________________________
    Dexs for 16/6/2023
    _______________________________________
    
    KAVA 👇
    Backfill start time: 29/1/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 1461.24277950808
    Timestamp: 1686959998
    
    
    
    
    Done in 24.52s.

**Comment by llamatester** [comment]
The abcdefx.ts adapter exports: 
        
 
 _______________________________________
    Fees for 16/6/2023
    _______________________________________
    
    KAVA 👇
    Backfill start time: 29/1/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 0.29252409195000006
    Daily revenue: 0.29252409195000006
    Daily holders revenue: 0.29252409195000006
    Timestamp: 1686959998
    
    
    
    
    Done in 23.46s.

**Comment by ftm1337** [comment]
fees is correct as well :+1:

**Comment by ftm1337** [comment]
a lot of dexes use the same codebase for fee and volume.. maybe convert it in to a util / sdk function?
inputs could be 
getGenericVolumes( chainName, factoryAddress,  swapEventTopic )
getGenericFees( chainName, factoryAddress,  feeEventTopic )

**Comment by dtmkeng** [comment]
thank you for PR and suggests , I'll try do it 🙏

**Pull request merged**
