### PR TITLE
Add pear volume

### PR DESCRIPTION
**Pull request by literallymarvellous**

### CODE REVIEW

**Comment by llamatester** [comment]
The pear-protocol adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs pear-protocol
    
    🦙 Running PEAR-PROTOCOL adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 12 Sep 2024 00:00:00 GMT
    End Date:	Fri, 13 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1726185599 (2024-09-12T23:59:59.000Z)

**Comment by llamatester** [comment]
The pear-protocol adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees pear-protocol
    
    🦙 Running PEAR-PROTOCOL adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 12 Sep 2024 00:00:00 GMT
    End Date:	Fri, 13 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1726185599 (2024-09-12T23:59:59.000Z)

**Comment by llamatester** [comment]
The pear-protocol adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs pear-protocol
    
    🦙 Running PEAR-PROTOCOL adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 14 Sep 2024 00:00:00 GMT
    End Date:	Sun, 15 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1726358399 (2024-09-14T23:59:59.000Z)

**Comment by llamatester** [comment]
The pear-protocol adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees pear-protocol
    
    🦙 Running PEAR-PROTOCOL adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 14 Sep 2024 00:00:00 GMT
    End Date:	Sun, 15 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1726358399 (2024-09-14T23:59:59.000Z)

**Comment by dtmkeng** [comment]
SEEM. your api don't have field daily value could you check

**Comment by dtmkeng** [comment]
```json
{
"message": "fetched all trade details successfully",
"payload": {
"totalV1TradesInUsd": 253448.888055709,
"totalV1PearOpenTrades": 489,
"totalV1PearUsers": 112,
"totalV2TradesInUsd": 12934591.5756047,
"totalV2PearOpenTrades": 1214,
"totalV2PearUsers": 427,
"totalTradesInUsd": 13188040.463660408,
"totalPearOpenTrades": 1703,
"totalPearUsers": 539
},
"statusCode": 200
}
```

**Comment by llamatester** [comment]
The pear-protocol adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs pear-protocol
    
    🦙 Running PEAR-PROTOCOL adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 14 Sep 2024 00:00:00 GMT
    End Date:	Sun, 15 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1726358399 (2024-09-14T23:59:59.000Z)

**Comment by llamatester** [comment]
The pear-protocol adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees pear-protocol
    
    🦙 Running PEAR-PROTOCOL adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 14 Sep 2024 00:00:00 GMT
    End Date:	Sun, 15 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1726358399 (2024-09-14T23:59:59.000Z)

**Comment by literallymarvellous** [comment]
> ```json
> {
> "message": "fetched all trade details successfully",
> "payload": {
> "totalV1TradesInUsd": 253448.888055709,
> "totalV1PearOpenTrades": 489,
> "totalV1PearUsers": 112,
> "totalV2TradesInUsd": 12934591.5756047,
> "totalV2PearOpenTrades": 1214,
> "totalV2PearUsers": 427,
> "totalTradesInUsd": 13188040.463660408,
> "totalPearOpenTrades": 1703,
> "totalPearUsers": 539
> },
> "statusCode": 200
> }
> ```

sorry, updated.

**Comment by llamatester** [comment]
The pear-protocol adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs pear-protocol
    
    🦙 Running PEAR-PROTOCOL adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 14 Sep 2024 00:00:00 GMT
    End Date:	Sun, 15 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1726358399 (2024-09-14T23:59:59.000Z)

**Comment by llamatester** [comment]
The pear-protocol adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees pear-protocol
    
    🦙 Running PEAR-PROTOCOL adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 14 Sep 2024 00:00:00 GMT
    End Date:	Sun, 15 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1726358399 (2024-09-14T23:59:59.000Z)

**Comment by llamatester** [comment]
The pear-protocol adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs pear-protocol
    
    🦙 Running PEAR-PROTOCOL adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 14 Sep 2024 00:00:00 GMT
    End Date:	Sun, 15 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 81.98 M
    Daily volume: 1.49 M
    End timestamp: 1726358399 (2024-09-14T23:59:59.000Z)

**Comment by llamatester** [comment]
The pear-protocol adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees pear-protocol
    
    🦙 Running PEAR-PROTOCOL adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 14 Sep 2024 00:00:00 GMT
    End Date:	Sun, 15 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 3.08 k
    Total fees: 196.31 k
    Daily revenue: 3.08 k
    Total revenue: 196.31 k
    End timestamp: 1726358399 (2024-09-14T23:59:59.000Z)

**Comment by dtmkeng** [comment]
is there details for list website x and description ?

**Comment by literallymarvellous** [comment]
yeah, where do I add the details

**Comment by dtmkeng** [comment]
you can drop add this commend

**Comment by literallymarvellous** [comment]
Website: pear.garden
X: pear_protocol
Description: The home of one-click decentralized pairs trading. Trade the latest narratives by choosing one token to long and one to short with leverage.

**Pull request merged**
