### PR TITLE
Add Helix Markets DEX dailyVolume

### PR DESCRIPTION
**Pull request by BitGonzi**
Adding an adapter for Helix Markets (https://www.helixmarkets.io/) a DEX on the ICP for daily volume

### CODE REVIEW

**Comment by llamatester** [comment]
The helix-markets adapter exports: 
        
 
 _______________________________________
    fatal: Not a valid object name master
    Error: Command failed: git ls-tree --name-only -r master
    fatal: Not a valid object name master
    
        at checkExecSyncError (node:child_process:890:11)
        at execSync (node:child_process:962:15)
        at checkIfFileExistsInMasterBranch (/home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:12:23)
        at /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:53:5
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      status: 128,
      signal: null,
      output: [
        null,
        <Buffer >,
        <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 76 61 6c 69 64 20 6f 62 6a 65 63 74 20 6e 61 6d 65 20 6d 61 73 74 65 72 0a>
      ],
      pid: 1831,
      stdout: <Buffer >,
      stderr: <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 76 61 6c 69 64 20 6f 62 6a 65 63 74 20 6e 61 6d 65 20 6d 61 73 74 65 72 0a>
    }
    Done in 1.35s.

**Comment by llamatester** [comment]
The helix-markets adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The helix-markets adapter exports: 
        
 
 _______________________________________
    Dexs for 25/4/2024
    _______________________________________
    
    ICP 👇
    Backfill start time: 23/4/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 228.48 k
    Timestamp: 1714044185 (2024-04-25T11:23:05.000Z)

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Comment by llamatester** [comment]
The helix-markets adapter exports: 
        
 
 _______________________________________
    Dexs for 25/4/2024
    _______________________________________
    
    ICP 👇
    Backfill start time: 23/4/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 227.55 k
    Timestamp: 1714044472 (2024-04-25T11:27:52.000Z)

**Comment by BitGonzi** [comment]
> is there tvl adapter ?

Yes, we'll have it ready in the next day or two, we have TVL on our WS, converting it to REST, then publishing the TVL adapter as well

**Comment by dtmkeng** [comment]
okay will wait tvl merge

**Pull request merged**
