### PR TITLE
Add dForce swap.

### PR DESCRIPTION
**Pull request by Skyge**

### CODE REVIEW

**Comment by llamatester** [comment]
The dForce-swap adapter exports: 
        
 
 _______________________________________
    Dexs for 18/3/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 1/1/1970
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1679097600
    
    
    POLYGON 👇
    Backfill start time: 1/1/1970
    NO METHODOLOGY SPECIFIED
    Daily volume: 5496.098910000001
    Timestamp: 1679097600
    
    
    ARBITRUM 👇
    Backfill start time: 1/1/1970
    NO METHODOLOGY SPECIFIED
    Daily volume: 1379168.1750577954
    Timestamp: 1679097600
    
    
    OPTIMISM 👇
    Backfill start time: 1/1/1970
    NO METHODOLOGY SPECIFIED
    Daily volume: 88446.48139935738
    Timestamp: 1679097600
    
    
    BSC 👇
    Backfill start time: 1/1/1970
    NO METHODOLOGY SPECIFIED
    Daily volume: 16486.85075782207
    Timestamp: 1679097600
    
    
    
    
    Done in 5.06s.

**Comment by dtmkeng** [comment]
seem tx not direct to dForce LP, i can not merge this pr because is double count on some protocol, should open under folder `aggregators` type

**Comment by Skyge** [comment]
Okay, I will update it

**Comment by Skyge** [comment]
@dtmkeng Have moved it under `aggregators` type, how about now?

**Comment by Skyge** [comment]
@dtmkeng Hi, this is PR has been merged yesterday, but sorry, I do not find the link to access to it, there is not an option named `aggregator` on the page, could you please share me with the link, thanks a lot!

**Comment by dtmkeng** [comment]
@Skyge  oh sorry let me check

**Comment by dtmkeng** [comment]
https://defillama.com/aggregators/dforce

**Pull request merged**
