### PR TITLE
Add Zerion Wallet Fees Adapter

### PR DESCRIPTION
**Pull request by rockfridrich**
This adapter is designed to compute and allocate payouts to treasury multi-signature wallets

### CODE REVIEW

**Comment by llamatester** [comment]
The zerion-wallet.ts adapter exports: 
        
 
 _______________________________________
    Fees for 18/1/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705622398
    Daily fees: 2.69 k
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 2.69 k
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 2.69 k
    
    
    OPTIMISM 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705622398
    Daily fees: 51.86 k
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 51.86 k
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 51.86 k
    
    
    ARBITRUM 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705622398
    Daily fees: 251.26544042302822
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 251.26544042302822
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 251.26544042302822
    
    
    BASE 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705622398
    Daily fees: 22.135085980058715
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 22.135085980058715
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 22.135085980058715
    
    
    POLYGON 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705622398
    Daily fees: 52.34442814073586
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 52.34442814073586
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 52.34442814073586
    
    
    BSC 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705622398
    Daily fees: 34.30157288860949
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 34.30157288860949
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 34.30157288860949
    
    
    
    
    Done in 9.83s.

**Comment by dtmkeng** [comment]
is there details for list (x, website, and some desc)

**Comment by rockfridrich** [comment]
Sure! 

Zerion (https://zerion.io/) — a crypto wallet for everything onchain

**Comment by llamatester** [comment]
The zerion-wallet.ts adapter exports: 
        
 
 _______________________________________
    Fees for 19/1/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705708798
    Daily fees: 1.40 k
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 1.40 k
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 1.40 k
    
    
    OPTIMISM 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705708798
    Daily fees: 140.5608369206302
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 140.5608369206302
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 140.5608369206302
    
    
    ARBITRUM 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705708798
    Daily fees: 293.8721197451272
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 293.8721197451272
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 293.8721197451272
    
    
    BASE 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705708798
    Daily fees: 20.33789623686251
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 20.33789623686251
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 20.33789623686251
    
    
    POLYGON 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705708798
    Daily fees: 77.77565595460472
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 77.77565595460472
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 77.77565595460472
    
    
    BSC 👇
    Backfill start time: 1/1/2023
    Timestamp: 1705708798
    Daily fees: 196.2186706592529
    └─ Methodology: Take 0.5% from trading volume
    Daily revenue: 196.2186706592529
    └─ Methodology: Take 0.5% from trading volume
    Daily protocol revenue: 196.2186706592529
    
    
    
    
    Done in 11.05s.

**Pull request merged**
