### PR TITLE
Add mango-v4 to dexs + fees

### PR DESCRIPTION
**Pull request by Lou-Kamades**

### CODE REVIEW

**Comment by llamatester** [comment]
The mango-v4 adapter exports: 
        
 
 _______________________________________
    Dexs for 17/9/2023
    _______________________________________
    
    Version -> SPOT
    ---------
    SOLANA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 9595.777067149606
    Total volume: 39235288.70862898
    Timestamp: 1694995199
    
    
    Version -> PERP
    ---------
    SOLANA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 92807.45146400481
    Total volume: 35047709.39461801
    Timestamp: 1694995199
    
    
    Done in 4.31s.

**Comment by llamatester** [comment]
The mango-v4.ts adapter exports: 
        
 
 _______________________________________
    Fees for 17/9/2023
    _______________________________________
    
    Version -> SPOT
    ---------
    SOLANA 👇
    Backfill start time not defined
    Daily fees: 140.37957061479392
    └─ Methodology: Swap fees are 0.1%, with a fee of 0.2% for stop-loss swaps. CLOB maker/taker fees are -0.02%/0.04%.
    Total fees: 25879.61285809088
    └─ Methodology: Swap fees are 0.1%, with a fee of 0.2% for stop-loss swaps. CLOB maker/taker fees are -0.02%/0.04%.
    Timestamp: 1694995199
    
    
    Version -> PERP
    ---------
    SOLANA 👇
    Backfill start time not defined
    Daily fees: 140.37957061479392
    └─ Methodology: Maker/taker fees are -0.03%/0.1%. Stop-loss orders have a fee of 0.2%
    Total fees: 25879.61285809088
    └─ Methodology: Maker/taker fees are -0.03%/0.1%. Stop-loss orders have a fee of 0.2%
    Timestamp: 1694995199
    
    
    Done in 3.95s.

**Comment by dtmkeng** [comment]
hey fees we can split breakdown, we can split like current  your  protocol  split
could you group value for fees adapter ?
image

**Comment by llamatester** [comment]
The mango-v4 adapter exports: 
        
 
 _______________________________________
    Dexs for 17/9/2023
    _______________________________________
    
    Version -> SPOT
    ---------
    SOLANA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 11136.524887252539
    Total volume: 39236348.25721829
    Timestamp: 1694995199
    
    
    Version -> PERP
    ---------
    SOLANA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 277226.2733940035
    Total volume: 35237813.660048015
    Timestamp: 1694995199
    
    
    Done in 4.02s.

**Comment by llamatester** [comment]
The mango-v4.ts adapter exports: 
        
 
 _______________________________________
    Fees for 17/9/2023
    _______________________________________
    
    Version -> SPOT
    ---------
    SOLANA 👇
    Backfill start time not defined
    Daily fees: 578.4869212898484
    └─ Methodology: Swap fees are 0.1%, with a fee of 0.2% for stop-loss swaps. CLOB maker/taker fees are -0.02%/0.04%.
    Total fees: 21036.63792429542
    └─ Methodology: Swap fees are 0.1%, with a fee of 0.2% for stop-loss swaps. CLOB maker/taker fees are -0.02%/0.04%.
    Timestamp: 1694995199
    
    
    Version -> PERP
    ---------
    SOLANA 👇
    Backfill start time not defined
    Daily fees: 86.06665147057174
    └─ Methodology: Maker/taker fees are -0.03%/0.1%. Stop-loss orders have a fee of 0.2%
    Total fees: 5540.21063345233
    └─ Methodology: Maker/taker fees are -0.03%/0.1%. Stop-loss orders have a fee of 0.2%
    Timestamp: 1694995199
    
    
    Version -> TOTAL
    ---------
    SOLANA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily fees: 664.553572760422
    Total fees: 26576.84855774775
    Timestamp: 1694995199
    
    
    Done in 3.91s.

**Comment by Lou-Kamades** [comment]
I am not sure what you want me to do? I've added a total section for fees. 

I do not know what you mean by "hey fees we can split breakdown, we can split like current your protocol split"

**Comment by dtmkeng** [comment]
> I am not sure what you want me to do? I've added a total section for fees.
> 
> I do not know what you mean by "hey fees we can split breakdown, we can split like current your protocol split"

just return fees adapter like this 
https://github.com/DefiLlama/dimension-adapters/blob/master/fees/bmx.ts#L59

**Comment by llamatester** [comment]
The mango-v4 adapter exports: 
        
 
 _______________________________________
    Dexs for 17/9/2023
    _______________________________________
    
    Version -> SPOT
    ---------
    SOLANA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 11136.524887252539
    Total volume: 39243277.41642628
    Timestamp: 1694995199
    
    
    Version -> PERP
    ---------
    SOLANA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 297571.74696400017
    Total volume: 35262350.099018015
    Timestamp: 1694995199
    
    
    Done in 4.20s.

**Comment by llamatester** [comment]
The mango-v4.ts adapter exports: 
        
 
 _______________________________________
    Fees for 17/9/2023
    _______________________________________
    
    SOLANA 👇
    Backfill start time not defined
    Timestamp: 1694995198
    Daily fees: 789.4828543510921
    └─ Methodology: CLOB maker/taker fees are -0.02%/0.04%. Swap fees are 0.1%, with a fee of 0.2% for stop-loss swaps. Perp maker/taker fees are -0.03%/0.1%. Stop-loss orders have a fee of 0.2%. Borrows have an origination fee of 0.05%-0.2%, based on token liquidity. Liquidations have fees ranging from 5-20%.
    Total fees: 26663.025080332325
    └─ Methodology: CLOB maker/taker fees are -0.02%/0.04%. Swap fees are 0.1%, with a fee of 0.2% for stop-loss swaps. Perp maker/taker fees are -0.03%/0.1%. Stop-loss orders have a fee of 0.2%. Borrows have an origination fee of 0.05%-0.2%, based on token liquidity. Liquidations have fees ranging from 5-20%.
    Daily protocol revenue: 789.4828543510921
    Total protocol revenue: 26663.025080332325
    
    
    
    
    Done in 3.91s.

**Pull request merged**
