### PR TITLE
update apx finance daily trading volume.

### PR DESCRIPTION
**Pull request by AQVYmeCkJsFTFWpMAHmA**

### CODE REVIEW

**Comment by llamatester** [comment]
The apollox adapter exports: 
        
 
 _______________________________________
    Dexs for 24/1/2024
    _______________________________________
    
    BSC 👇
    Backfill start time: 21/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 54.68 M
    Timestamp: 1706140798
    
    
    ARBITRUM 👇
    Backfill start time: 21/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 3.12 M
    Timestamp: 1706140798
    
    
    
    
    Done in 3.47s.

**Comment by DrunkCzz** [comment]
Current trading volume, not counting APX V1 and dumb trading volume

**Comment by dtmkeng** [comment]
that api return 24h value  ?

**Comment by dtmkeng** [comment]
it exclude volume pancake perp ?

**Comment by dtmkeng** [comment]
https://github.com/DefiLlama/dimension-adapters/pull/877/files i think duplicate with this pr

**Pull request closed without merging**
