### PR TITLE
satori fee add xlayer

### PR DESCRIPTION
**Pull request by miler012**
here is satori prep , we add the fee from xlayer

### CODE REVIEW

**Comment by llamatester** [comment]
The satori adapter exports: 
        
 
 _______________________________________
    Dexs for 29/5/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://base.satori.finance/api/data-center/pub/overview/integration',
      method: 'POST',
      axiosError: 'Forbidden',
      chain: 'base'
    }

**Comment by dtmkeng** [comment]
could you check errror at `https://base.satori.finance/api/data-center/pub/overview/integration`

**Comment by llamatester** [comment]
The satori adapter exports: 
        
 
 _______________________________________
    Dexs for 31/5/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://base.satori.finance/api/data-center/pub/overview/integration',
      method: 'POST',
      axiosError: 'Forbidden',
      chain: 'base'
    }

**Comment by llamatester** [comment]
The satori adapter exports: 
        
 
 _______________________________________
    Dexs for 3/6/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://base.satori.finance/api/data-center/pub/overview/integration',
      method: 'POST',
      axiosError: 'Forbidden',
      chain: 'base'
    }

**Comment by llamatester** [comment]
The satori adapter exports: 
        
 
 _______________________________________
    Dexs for 18/6/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://base.satori.finance/api/data-center/pub/overview/integration',
      method: 'POST',
      axiosError: 'Forbidden',
      chain: 'base'
    }

**Comment by dtmkeng** [comment]
@miler012 could you check new endpoint seem error 403 ?

**Comment by miler012** [comment]
> @miler012 could you check new endpoint seem error 403 ?
still ,anything wrong?

**Comment by llamatester** [comment]
The satori adapter exports: 
        
 
 _______________________________________
    Dexs for 27/6/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://base.satori.finance/api/data-center/pub/overview/integration',
      method: 'POST',
      axiosError: 'Forbidden',
      chain: 'base'
    }

**Comment by dtmkeng** [comment]
@miler012 yes

**Comment by miler012** [comment]
we test it is ok .
is there have some request time limit for the index execute.
we have 6 api request

**Comment by llamatester** [comment]
The satori adapter exports: 
        
 
 _______________________________________
    Dexs for 28/6/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://xlayer.satori.finance/api/data-center/pub/overview/integration',
      method: 'POST',
      axiosError: 'Forbidden',
      chain: 'xlayer'
    }

**Comment by dtmkeng** [comment]
no we just call one time per day if you set `runAtCurrTime: true`

**Comment by miler012** [comment]
const ZKEVM_URL = 'https://zkevm.satori.finance/api/data-center/pub/overview/integration'
const ZkSYNC_URL = 'https://zksync.satori.finance/api/data-center/pub/overview/integration'
const SCROLL_URL = 'https://scroll.satori.finance/api/data-center/pub/overview/integration'
const LINEA_URL = 'https://linea.satori.finance/api/data-center/pub/overview/integration'
const BASE_URL = 'https://base.satori.finance/api/data-center/pub/overview/integration'
const XLAYER_URL = 'https://xlayer.satori.finance/api/data-center/pub/overview/integration'

it is so strange.
the same api and have 6 call,the before 4 is ok , just occuer error at last two.
and we test is all good.

**Comment by dtmkeng** [comment]
can't merge if it error on ci, i guess it block from  your side

**Comment by miler012** [comment]
can you offer your ip?

**Comment by dtmkeng** [comment]
can't we use cloud, there is not ip for you

**Pull request closed without merging**
