### PR TITLE
ZivoeAdaperFees

### PR DESCRIPTION
**Pull request by pseudonaut**

### CODE REVIEW

**Comment by llamabutler** [comment]
The zivoe adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees zivoe
    
    🦙 Running ZIVOE adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 22 Dec 2024 15:33:00 GMT
    End Date:	Mon, 23 Dec 2024 15:33:00 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 10/10/2024
    Daily fees: 0
    └─ Methodology: Interest earned from borrowers + fees generated by deploying idle capital into DeFi.
    Daily revenue: 0
    └─ Methodology: Portion of fees retained by the protocol.
    End timestamp: 1734967979 (2024-12-23T15:32:59.000Z)

**Comment by pseudonaut** [comment]
For metadata related to project (we've already been approved) - see https://github.com/DefiLlama/DefiLlama-Adapters/pull/12792

**Comment by g1nt0ki** [comment]
thanks for the PR, merged it with a minor fix, but is the api returning the correct data? I am getting empty array as response.

if you share event logs structure for the fees, we can compute it on chain.

**Comment by alexsserban** [comment]
@g1nt0ki We currently have fees for 2 days. You can check `npm test fees zivoe` for `1732320000` and `1734739200`. Let me know if we are missing something.

**Pull request closed without merging**
