### PR TITLE
Updated bluefin volume adaptor to consider start and end time

### PR DESCRIPTION
**Pull request by burhanuddin03**
- Updated bluefin volume adaptor to consider start and end time

### CODE REVIEW

**Comment by burhanuddin03** [comment]
How to update the adaptor to backfill old data based on this?

**Comment by llamatester** [comment]
The bluefin adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs bluefin
    
    🦙 Running BLUEFIN adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 05 Dec 2024 00:00:00 GMT
    End Date:	Fri, 06 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Version -> DERIVATIVES
    ---------
    SUI 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 140.02 M
    End timestamp: 1733443199 (2024-12-05T23:59:59.000Z)

**Comment by llamatester** [comment]
The bluefin adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs bluefin
    
    🦙 Running BLUEFIN adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 05 Dec 2024 13:07:35 GMT
    End Date:	Fri, 06 Dec 2024 13:07:35 GMT
    ---------------------------------------------------
    
    Version -> DERIVATIVES
    ---------
    SUI 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 111.01 M
    End timestamp: 1733490454 (2024-12-06T13:07:34.000Z)

**Comment by g1nt0ki** [comment]
thanks for the PR, we will refill

**Pull request merged**
