### PR TITLE
add fees adapter, volume adapter for Allbridge Classic

### PR DESCRIPTION
**Pull request by m-cote**
* Add fees adapter for Allbridge Classic
* Add volume adapter for Allbridge Classic

### CODE REVIEW

**Comment by llamatester** [comment]
The allbridge-classic adapter exports: 
        
 
 _______________________________________
    Dexs for 4/1/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 13/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 22.90 k
    
    
    BSC 👇
    Backfill start time: 13/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 28.33 k
    
    
    TERRA 👇
    Backfill start time: 9/12/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    AURORA 👇
    Backfill start time: 14/12/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 2.71 k
    
    
    POLYGON 👇
    Backfill start time: 10/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 16.68 k
    
    
    HECO 👇
    Backfill start time: 13/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 365.3221504474
    
    
    CELO 👇
    Backfill start time: 13/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 2.16 k
    
    
    AVAX 👇
    Backfill start time: 13/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 20.13 k
    
    
    FANTOM 👇
    Backfill start time: 21/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 1.35 k
    
    
    FUSE 👇
    Backfill start time: 1/1/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    SOLANA 👇
    Backfill start time: 10/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 76.98 k
    
    
    NEAR 👇
    Backfill start time: 1/2/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    HARMONY 👇
    Backfill start time: 1/1/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    TEZOS 👇
    Backfill start time: 5/6/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    KLAYTN 👇
    Backfill start time: 15/8/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    WAVES 👇
    Backfill start time: 15/9/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    STELLAR 👇
    Backfill start time: 30/12/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 2.52 k
    
    
    STACKS 👇
    Backfill start time: 27/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    
    
    Done in 5.67s.

**Comment by llamatester** [comment]
The allbridge-classic.ts adapter exports: 
        
 
 _______________________________________
    Fees for 4/1/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 13/11/2021
    Timestamp: 1704412798
    Daily fees: 13.572470000000001
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 2.714494
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 10.857976
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    BSC 👇
    Backfill start time: 13/11/2021
    Timestamp: 1704412798
    Daily fees: 44.98739639800001
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 8.997479279600002
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 35.98991711840001
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    TERRA 👇
    Backfill start time: 9/12/2021
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    AURORA 👇
    Backfill start time: 14/12/2021
    Timestamp: 1704412798
    Daily fees: 10.79981
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 2.159962
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 8.639848
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    POLYGON 👇
    Backfill start time: 10/11/2021
    Timestamp: 1704412798
    Daily fees: 47.049875748400005
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 9.409975149680001
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 37.639900598720004
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    HECO 👇
    Backfill start time: 13/11/2021
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    CELO 👇
    Backfill start time: 13/11/2021
    Timestamp: 1704412798
    Daily fees: 11.803568
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 2.3607136
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 9.4428544
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    AVAX 👇
    Backfill start time: 13/11/2021
    Timestamp: 1704412798
    Daily fees: 18.709639307099998
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 3.74192786142
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 14.96771144568
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    FANTOM 👇
    Backfill start time: 21/11/2021
    Timestamp: 1704412798
    Daily fees: 11.005982000000001
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 2.2011964
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 8.8047856
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    FUSE 👇
    Backfill start time: 1/1/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    SOLANA 👇
    Backfill start time: 10/11/2021
    Timestamp: 1704412798
    Daily fees: 297.3401152686
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 59.46802305372
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 237.87209221488
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    NEAR 👇
    Backfill start time: 1/2/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    HARMONY 👇
    Backfill start time: 1/1/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    TEZOS 👇
    Backfill start time: 5/6/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    KLAYTN 👇
    Backfill start time: 15/8/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    WAVES 👇
    Backfill start time: 15/9/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    STELLAR 👇
    Backfill start time: 30/12/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    STACKS 👇
    Backfill start time: 27/7/2023
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    
    
    Done in 2.69s.

**Comment by llamatester** [comment]
The allbridge-classic adapter exports: 
        
 
 _______________________________________
    Dexs for 4/1/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 13/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 22.90 k
    
    
    BSC 👇
    Backfill start time: 13/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 28.33 k
    
    
    TERRA 👇
    Backfill start time: 9/12/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    AURORA 👇
    Backfill start time: 14/12/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 2.71 k
    
    
    POLYGON 👇
    Backfill start time: 10/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 16.68 k
    
    
    HECO 👇
    Backfill start time: 13/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 365.3221504474
    
    
    CELO 👇
    Backfill start time: 13/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 2.16 k
    
    
    AVAX 👇
    Backfill start time: 13/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 20.13 k
    
    
    FANTOM 👇
    Backfill start time: 21/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 1.35 k
    
    
    FUSE 👇
    Backfill start time: 1/1/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    SOLANA 👇
    Backfill start time: 10/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 76.98 k
    
    
    NEAR 👇
    Backfill start time: 1/2/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    HARMONY 👇
    Backfill start time: 1/1/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    TEZOS 👇
    Backfill start time: 5/6/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    KLAYTN 👇
    Backfill start time: 15/8/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    WAVES 👇
    Backfill start time: 15/9/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    STELLAR 👇
    Backfill start time: 30/12/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: 2.52 k
    
    
    STACKS 👇
    Backfill start time: 27/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704412798
    Daily volume: NaN
    
    
    
    
    Done in 3.06s.

**Comment by llamatester** [comment]
The allbridge-classic.ts adapter exports: 
        
 
 _______________________________________
    Fees for 4/1/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 13/11/2021
    Timestamp: 1704412798
    Daily fees: 13.57247
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 2.714494
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 10.857976
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    BSC 👇
    Backfill start time: 13/11/2021
    Timestamp: 1704412798
    Daily fees: 44.987396398
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 8.9974792796
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 35.9899171184
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    TERRA 👇
    Backfill start time: 9/12/2021
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    AURORA 👇
    Backfill start time: 14/12/2021
    Timestamp: 1704412798
    Daily fees: 10.79981
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 2.159962
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 8.639848
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    POLYGON 👇
    Backfill start time: 10/11/2021
    Timestamp: 1704412798
    Daily fees: 47.0498757484
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 9.40997514968
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 37.63990059872
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    HECO 👇
    Backfill start time: 13/11/2021
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    CELO 👇
    Backfill start time: 13/11/2021
    Timestamp: 1704412798
    Daily fees: 11.803568
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 2.3607136
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 9.4428544
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    AVAX 👇
    Backfill start time: 13/11/2021
    Timestamp: 1704412798
    Daily fees: 18.709639307099998
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 3.74192786142
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 14.96771144568
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    FANTOM 👇
    Backfill start time: 21/11/2021
    Timestamp: 1704412798
    Daily fees: 11.005982000000001
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 2.2011964
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 8.8047856
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    FUSE 👇
    Backfill start time: 1/1/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    SOLANA 👇
    Backfill start time: 10/11/2021
    Timestamp: 1704412798
    Daily fees: 297.3401152686001
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: 59.46802305372002
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: 237.87209221488007
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    NEAR 👇
    Backfill start time: 1/2/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    HARMONY 👇
    Backfill start time: 1/1/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    TEZOS 👇
    Backfill start time: 5/6/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    KLAYTN 👇
    Backfill start time: 15/8/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    WAVES 👇
    Backfill start time: 15/9/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    STELLAR 👇
    Backfill start time: 30/12/2022
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    STACKS 👇
    Backfill start time: 27/7/2023
    Timestamp: 1704412798
    Daily fees: NaN
    └─ Methodology: Users pay bridge fee for each transfer on the source chain.
    Daily protocol revenue: NaN
    └─ Methodology: Protocol receives 20% of the collected bridge fee.
    Daily supply side revenue: NaN
    └─ Methodology: 80% of the collected bridge fee is used for rewards to the stakers
    
    
    
    
    Done in 2.69s.

**Comment by dtmkeng** [comment]
what is volume type (swap)`dexs`, `aggregators`  ?

**Comment by m-cote** [comment]
> what is volume type (swap)`dexs`, `aggregators` ?

This is volume of swaps on the Allbridge Classic bridge

**Comment by dtmkeng** [comment]
@m-cote  could you check api it error 502 when i run backfill data

**Comment by m-cote** [comment]
@dtmkeng Could you try running backfill again, please?

**Pull request merged**
