### PR TITLE
nexter volume data

### PR DESCRIPTION
**Pull request by manti**
```
🦙 Running NEXTER adapter 🦙

POLYGON 👇
Backfill start time: 23/12/2021
NO METHODOLOGY SPECIFIED
Timestamp: 1708300798 (2024-02-18T23:59:58.000Z)
Total premium volume: 56.38 M
Daily premium volume: 4.50 k


ARBITRUM 👇
Backfill start time: 23/12/2021
NO METHODOLOGY SPECIFIED
Timestamp: 1708300798 (2024-02-18T23:59:58.000Z)
Total premium volume: 16.96 M
Daily premium volume: 0


POLYGON_ZKEVM 👇
Backfill start time: 23/12/2021
NO METHODOLOGY SPECIFIED
Timestamp: 1708300798 (2024-02-18T23:59:58.000Z)
Total premium volume: 5.95 M
Daily premium volume: 0


MANTLE 👇
Backfill start time: 23/12/2021
NO METHODOLOGY SPECIFIED
Timestamp: 1708300798 (2024-02-18T23:59:58.000Z)
Total premium volume: 8.01 M
Daily premium volume: 0


TELOS 👇
Backfill start time: 23/12/2021
NO METHODOLOGY SPECIFIED
Timestamp: 1708300798 (2024-02-18T23:59:58.000Z)
Total premium volume: 23.80 M
Daily premium volume: 0


```

### CODE REVIEW

**Comment by llamatester** [comment]
The nexter adapter exports: 
        
 
 _______________________________________
    Options for 18/2/2024
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 23/12/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1708300798 (2024-02-18T23:59:58.000Z)
    Total premium volume: 56.38 M
    Daily premium volume: 4.50 k
    
    
    ARBITRUM 👇
    Backfill start time: 23/12/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1708300798 (2024-02-18T23:59:58.000Z)
    Total premium volume: 16.96 M
    Daily premium volume: 0
    
    
    POLYGON_ZKEVM 👇
    Backfill start time: 23/12/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1708300798 (2024-02-18T23:59:58.000Z)
    Total premium volume: 5.95 M
    Daily premium volume: 0
    
    
    MANTLE 👇
    Backfill start time: 23/12/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1708300798 (2024-02-18T23:59:58.000Z)
    Total premium volume: 8.01 M
    Daily premium volume: 0
    
    
    TELOS 👇
    Backfill start time: 23/12/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1708300798 (2024-02-18T23:59:58.000Z)
    Total premium volume: 23.80 M
    Daily premium volume: 0
    
    
    
    
    Done in 63.75s.

**Comment by manti** [comment]
@llamatester Can you please merge this

**Comment by dtmkeng** [comment]
@manti  we can't list bet volume

**Comment by manti** [comment]
@dtmkeng This works similarly to binary options, and it is important to stress that the funds involved are actual deposits from users into the contract. 

It seems that swapping on a DEX, paying a premium in options trading, and engaging in binary options all share similarities in their execution. We're having difficulty determining how this particular activity differs from the volume in the DEX. Could you please provide further clarification on this matter?

I'm happy to jump on a call and explain things better.
FYI- We are not a casino model; all of our predictions are player versus player, thus volume in the prediction market is same as option trading premium. It's not something different.

**Comment by 0xngmi** [comment]
in your website you mention that this is a prediction market where one can trade sports events, real world events... but in app there only seems to be binary options on crypto, is the other stuff not getting included here?

**Comment by manti** [comment]
@0xngmi At the moment, our app does not feature sports and other prediction markets. Nevertheless, we closely monitor user feedback and market demands. However, our main focus currently lies in binary options trading for crypto assets. Additionally, we are transitioning our narrative to L3 chain, specializing in binary options using staked assets. Consequently, our priority doesn't lean towards incorporating sports and other prediction data, except for monitoring volumes related to binary options.

**Comment by manti** [comment]
@dtmkeng @0xngmi Can you merge this PR ?

**Comment by manti** [comment]
@dtmkeng @0xngmi any update here ?

**Comment by manti** [comment]
@dtmkeng @0xngmi  Do you need anything to merge this PR? It's been about two weeks!

**Comment by 0xngmi** [comment]
After discussing it we're not gonna list this project as options, because it's main usecase is gambling and:
- Users checking the options dashboard want to get info on the adoption of option trades vs other instruments like perps, adding this would mix up option and gambling volume and wouldnt be useful to our users
- Comparing gambling like this to option marketplaces is not apples to apples, they're very different

**Pull request closed without merging**
