### PR TITLE
show daily Jupiter Perpetual volume.

### PR DESCRIPTION
**Pull request by siong1987**
this PR adds Jupiter Perpetual Exchange volume: https://jup.ag/perps

### CODE REVIEW

**Comment by llamatester** [comment]
The jupiter-perpetual adapter exports: 
        
 
 _______________________________________
    Dexs for 27/1/2024
    _______________________________________
    
    there is no more api key
    Version -> DERIVATIVES
    ---------
    SOLANA 👇
    Backfill start time: 22/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1706313600
    
    
    TypeError: Cannot read properties of undefined (reading 'bail')
        at onError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/async-retry/lib/index.js:26:15)
        at catchIt (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/async-retry/lib/index.js:51:11)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
    Done in 2.92s.

**Comment by dtmkeng** [comment]
Jupiter is own of lp for perp volume ?

**Comment by siong1987** [comment]
the error above is caused by an invalid Dune API key. i tested with my own Dune API key and it works.

**Comment by siong1987** [comment]
> Jupiter is own of lp for perp volume ?

yup. it is a perpetual product that comes with the LP pool. you can check out the JLP pool here: https://jup.ag/perps-earn/buy/SOL

**Comment by dtmkeng** [comment]
> > Jupiter is own of lp for perp volume ?
> 
> yup. it is a perpetual product that comes with an LP pool. you can check out the JLP pool here: https://jup.ag/perps-earn/buy/SOL

is there txs direct to other perp protocol ?

**Comment by siong1987** [comment]
> > > Jupiter is own of lp for perp volume ?
> > 
> > 
> > yup. it is a perpetual product that comes with an LP pool. you can check out the JLP pool here: https://jup.ag/perps-earn/buy/SOL
> 
> is there txs direct to other perp protocol ?

nope. it trades directly with the JLP pool, not an aggregator.

> Jupiter perpetual exchange is LP-to-trader perpetual exchange based on oracle prices.
> 
> Our pool consists of 5 tokens, SOL, ETH, WBTC, USDC, and USDT. Liquidity providers deposit one of the pool tokens into the pool in exchange for LP tokens representing their share of the pool.
> 
> A trader may open a leveraged position by putting up collateral and borrowing the rest of the position from the pool.

You can read more about it here: https://station.jup.ag/labs/perpetual-exchange/how-it-works

**Comment by siong1987** [comment]
> > > > > Jupiter is own of lp for perp volume ?
> > > > 
> > > > 
> > > > yup. it is a perpetual product that comes with an LP pool. you can check out the JLP pool here: https://jup.ag/perps-earn/buy/SOL
> > > 
> > > 
> > > is there txs direct to other perp protocol ?
> > 
> > 
> > nope. it trades directly with the JLP pool, not an aggregator.
> > > Jupiter perpetual exchange is LP-to-trader perpetual exchange based on oracle prices.
> > > Our pool consists of 5 tokens, SOL, ETH, WBTC, USDC, and USDT. Liquidity providers deposit one of the pool tokens into the pool in exchange for LP tokens representing their share of the pool.
> > > A trader may open a leveraged position by putting up collateral and borrowing the rest of the position from the pool.
> > 
> > 
> > You can read more about it here: https://station.jup.ag/labs/perpetual-exchange/how-it-works
> 
> is there tvl adapter ?

yes. we do have a lot of data here: https://dune.com/ilemi/jupiter-perps

**Comment by dtmkeng** [comment]
> > > > > > Jupiter is own of lp for perp volume ?
> > > > > 
> > > > > 
> > > > > yup. it is a perpetual product that comes with an LP pool. you can check out the JLP pool here: https://jup.ag/perps-earn/buy/SOL
> > > > 
> > > > 
> > > > is there txs direct to other perp protocol ?
> > > 
> > > 
> > > nope. it trades directly with the JLP pool, not an aggregator.
> > > > Jupiter perpetual exchange is LP-to-trader perpetual exchange based on oracle prices.
> > > > Our pool consists of 5 tokens, SOL, ETH, WBTC, USDC, and USDT. Liquidity providers deposit one of the pool tokens into the pool in exchange for LP tokens representing their share of the pool.
> > > > A trader may open a leveraged position by putting up collateral and borrowing the rest of the position from the pool.
> > > 
> > > 
> > > You can read more about it here: https://station.jup.ag/labs/perpetual-exchange/how-it-works
> > 
> > 
> > is there tvl adapter ?
> 
> yes. we do have a lot of data here: https://dune.com/ilemi/jupiter-perps

could you create tvl adapter ?

**Comment by siong1987** [comment]
> > > > > > > Jupiter is own of lp for perp volume ?
> > > > > > 
> > > > > > 
> > > > > > yup. it is a perpetual product that comes with an LP pool. you can check out the JLP pool here: https://jup.ag/perps-earn/buy/SOL
> > > > > 
> > > > > 
> > > > > is there txs direct to other perp protocol ?
> > > > 
> > > > 
> > > > nope. it trades directly with the JLP pool, not an aggregator.
> > > > > Jupiter perpetual exchange is LP-to-trader perpetual exchange based on oracle prices.
> > > > > Our pool consists of 5 tokens, SOL, ETH, WBTC, USDC, and USDT. Liquidity providers deposit one of the pool tokens into the pool in exchange for LP tokens representing their share of the pool.
> > > > > A trader may open a leveraged position by putting up collateral and borrowing the rest of the position from the pool.
> > > > 
> > > > 
> > > > You can read more about it here: https://station.jup.ag/labs/perpetual-exchange/how-it-works
> > > 
> > > 
> > > is there tvl adapter ?
> > 
> > 
> > yes. we do have a lot of data here: https://dune.com/ilemi/jupiter-perps
> 
> could you create tvl adapter ?

added it here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8787

**Pull request merged**
