### PR TITLE
Add Gambit dex, fee and revenue

### PR DESCRIPTION
**Pull request by ALPHADA**
https://defillama.com/protocol/gambit-trade

### CODE REVIEW

**Comment by llamatester** [comment]
The gambit adapter exports: 
        
 
 _______________________________________
    Dexs for 11/10/2023
    _______________________________________
    
    ERA 👇
    Backfill start time: 17/5/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 38675.4746
    Timestamp: 1697068798
    
    
    
    
    Done in 4.45s.

**Comment by llamatester** [comment]
The gambit.ts adapter exports: 
        
 
 _______________________________________
    Fees for 11/10/2023
    _______________________________________
    
    ERA 👇
    Backfill start time: 17/5/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1697068798
    Daily fees: 17.327474
    Daily revenue: 6.855542
    Daily holders revenue: 6.855542
    
    
    
    
    Done in 5.57s.

**Comment by dtmkeng** [comment]
is it DERIVATIVES volume ?

**Comment by ALPHADA** [comment]
yes

**Pull request merged**
