### PR TITLE
Add EYWA to dexs

### PR DESCRIPTION
**Pull request by spiehdid**

### CODE REVIEW

**Comment by llamatester** [comment]
The eywa adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs eywa
    
    🦙 Running EYWA adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 20 Aug 2024 16:27:58 GMT
    End Date:	Wed, 21 Aug 2024 16:27:58 GMT
    ---------------------------------------------------
    
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4003938/execute',
      method: 'POST',
      axiosError: 'invalid API Key'
    }
    Version -> V1
    ---------
    ETHEREUM 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    AVAX 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    FANTOM 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    POLYGON 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    BSC 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    Version -> V1.5
    ---------
    ETHEREUM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    AVAX 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    FANTOM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    POLYGON 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    BSC 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    Version -> V2
    ---------
    ETHEREUM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    AVAX 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    FANTOM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    POLYGON 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    BSC 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    BASE 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)
    
    
    XDAI 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724257677 (2024-08-21T16:27:57.000Z)

**Comment by spiehdid** [comment]
@llamatester An api key is needed to complete the request on the dune

**Comment by dtmkeng** [comment]
could you make dune return all chain and all break down one time is good to save cost dune credit

**Comment by spiehdid** [comment]
> could you make dune return all chain and all break down one time is good to save cost dune credit

That's a good point. Will do

**Comment by llamatester** [comment]
The eywa adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs eywa
    
    🦙 Running EYWA adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 21 Aug 2024 17:32:44 GMT
    End Date:	Thu, 22 Aug 2024 17:32:44 GMT
    ---------------------------------------------------
    
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4009605/results',
      method: 'GET',
      axiosError: 'invalid API Key'
    }
    Version -> V1
    ---------
    ETHEREUM 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    AVAX 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    FANTOM 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    POLYGON 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    BSC 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 6/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    Version -> V1.5
    ---------
    ETHEREUM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    AVAX 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    FANTOM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    POLYGON 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    BSC 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    Version -> V2
    ---------
    ETHEREUM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    AVAX 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    FANTOM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    POLYGON 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    BSC 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    BASE 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)
    
    
    XDAI 👇
    Backfill start time: 10/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1724347963 (2024-08-22T17:32:43.000Z)

**Comment by spiehdid** [comment]
> could you make dune return all chain and all break down one time is good to save cost dune credit

Check out the new version. I will set up a data update for every day in dune

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Comment by spiehdid** [comment]
> is there tvl adapter ?

This is an adapter for daily and total swap volume

**Comment by dtmkeng** [comment]
is there example txs that your count for swap volume not sure seem it deposit i think i can't count deposit for volume

**Comment by spiehdid** [comment]
> is there example txs that your count for swap volume not sure seem it deposit i think i can't count deposit for volume
Swap USDC/DAI https://explorer.eywa.fi/?search=0x26cb046180e4dcee5d68e1b793d4ed0aa0cbb0ae621c5cdae5e27e05a9cb1036&p=1

**Comment by spiehdid** [comment]
@dtmkeng

**Comment by spiehdid** [comment]
> seem not swap volume

@dtmkeng This is a cross-chain swap

**Comment by spiehdid** [comment]
@dtmkeng Describe the problem in more detail. How do I calculate the cross-chain swap volume if the current implementation is not correct?

**Comment by dtmkeng** [comment]
will ask team is it can list  cross-chain swap  at dexs

**Comment by 0xngmi** [comment]
Our definition of DEXs are dexs where the tx happens on a chain, not crosschain, sorry about that but instead this should be listed as a bridge

**Comment by spiehdid** [comment]
> Our definition of DEXs are dexs where the tx happens on a chain, not crosschain, sorry about that but instead this should be listed as a bridge

How can we get into the dexes?

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi, thanks for the PR. All of these are evm chains, can you update the adapter to compute data on chain using event logs? I could help with the adapter if you share contract and event details

**Pull request closed without merging**
