### PR TITLE
update subgraph

### PR DESCRIPTION
**Pull request by 0xBluePingu**
we've updated our subgraph and its logic (multi-asset data separation). We've also changed our logo with our rebranding, which we put online today. I've attached the logo, but perhaps I should PR the Defillama-Adapters repo to request the logo change?
Icon_P1-s

### CODE REVIEW

**Comment by llamabutler** [comment]
The pingu adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs pingu
    
    🦙 Running PINGU adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 17 Dec 2024 00:00:00 GMT
    End Date:	Wed, 18 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 10/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 3.20 M
    End timestamp: 1734393600 (2024-12-17T00:00:00.000Z)

**Comment by llamabutler** [comment]
The pingu adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees pingu
    
    🦙 Running PINGU adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 17 Dec 2024 00:00:00 GMT
    End Date:	Wed, 18 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 10/1/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 1.66 k
    End timestamp: 1734393600 (2024-12-17T00:00:00.000Z)

**Comment by g1nt0ki** [comment]
hi @0xBluePingu I tried computing the volume & fees using event logs and I am getting very different result, can you take a look ? 

https://github.com/DefiLlama/dimension-adapters/pull/2238

No need for PR in adapter repo, we will update the logo

**Comment by Lxnchy** [comment]
yesterday we have deployed a new positions contract that issues Increase and Decrease Position events. The subgraph uses these events to calculate volume and fees, so some of yesterday's data is missing from the old version of the subgraph

**Comment by 0xBluePingu** [comment]
yesterday we have deployed a new positions contract that issues Increase and Decrease Position events. The subgraph uses these events to calculate volume and fees, so some of yesterday's data is missing from the old version of the subgraph

**Comment by 0xBluePingu** [comment]
if you run the script with the old subgraph for yesterday (19/12 - 20/12) you will see that there is only the volume of liquidations (which depend on another contract that we have not changed) and 0 of fees

**Comment by llamabutler** [comment]
The pingu adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs pingu
    
    🦙 Running PINGU adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 22 Dec 2024 00:00:00 GMT
    End Date:	Mon, 23 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 10/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 247.43 k
    End timestamp: 1734825600 (2024-12-22T00:00:00.000Z)

**Comment by llamabutler** [comment]
The pingu adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees pingu
    
    🦙 Running PINGU adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 22 Dec 2024 00:00:00 GMT
    End Date:	Mon, 23 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 10/1/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 176
    End timestamp: 1734825600 (2024-12-22T00:00:00.000Z)

**Pull request merged**
