### PR TITLE
add Orderly EVM volume

### PR DESCRIPTION
**Pull request by Slava-g1**

### CODE REVIEW

**Comment by llamatester** [comment]
The orderly-network adapter exports: 
        
 
 _______________________________________
    Dexs for 10/1/2024
    _______________________________________
    
    NEAR 👇
    Backfill start time: 14/9/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704844800
    Daily volume: 5.67 M
    
    
    EVM 👇
    Backfill start time: 26/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704844800
    Daily volume: 13.83 M
    
    
    
    
    Done in 3.21s.

**Comment by Slava-g1** [comment]
we need to switch over to derivates. All the volume on EVM is perps and most of the volume on near is perps as well

**Comment by dtmkeng** [comment]
> we need to switch over to derivates. All the volume on EVM is perps and most of the volume on near is perps as well

you should create new adapter for derivates volume, and should spacifi chain i don't chain name `evm`

**Comment by Slava-g1** [comment]
Will create a separate adapter. Re splitting the chains, the volume cannot be split between chains as our orderbook is offchain and all orders come into the same book.

**Comment by dtmkeng** [comment]
> Will create a separate adapter. Re splitting the chains, the volume cannot be split between chains as our orderbook is offchain and all orders come into the same book.

if you can't specifi chain you should choose one chain like dydx choose eth, apex too

**Comment by Slava-g1** [comment]
where should I create a new adapter?

**Comment by llamatester** [comment]
The orderly-network adapter exports: 
        
 
 _______________________________________
    Dexs for 18/1/2024
    _______________________________________
    
    Failed to get start time for undefined undefined near
    Version -> SPOT
    ---------
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 26/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1705536000
    Daily volume: 15.70 M
    
    
    Done in 2.70s.

**Comment by Slava-g1** [comment]
separated the spot and derivates, spot is on NEAR only, derivatives I assigned all under arbitrum. Not sure why near spot check failed (was successful build on local env)

**Comment by llamatester** [comment]
The orderly-network adapter exports: 
        
 
 _______________________________________
    Dexs for 19/1/2024
    _______________________________________
    
    NEAR 👇
    Backfill start time: 14/9/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1705622400
    Daily volume: 2.30 M
    
    
    
    
    Done in 3.44s.

**Comment by llamatester** [comment]
The orderly-network-derivatives adapter exports: 
        
 
 _______________________________________
    Dexs for 19/1/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 26/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1705622400
    Daily volume: 27.83 M
    
    
    
    
    Done in 2.94s.

**Pull request merged**
