### PR TITLE
add options aevo

### PR DESCRIPTION
**Pull request by timongll**

### CODE REVIEW

**Comment by llamatester** [comment]
The aevo adapter exports: 
        
 
 _______________________________________
    Options for 27/7/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690416000
    Daily notional volume: 2166450.92
    Daily premium volume: 44411.86
    Total notional volume: 204186830.68
    Total premium volume: 2172848.70
    
    
    
    
    Done in 3.97s.

**Comment by llamatester** [comment]
The aevo adapter exports: 
        
 
 _______________________________________
    Dexs for 27/7/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690416000
    Daily notional volume: 2166915.45
    Daily premium volume: 44407.09
    Total notional volume: 204191325.46
    Total premium volume: 2172848.70
    
    
    
    
    Done in 4.14s.

**Comment by llamatester** [comment]
The aevo adapter exports: 
        
 
 _______________________________________
    Options for 27/7/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690416000
    Daily notional volume: 2166915.45
    Daily premium volume: 44407.09
    Total notional volume: 204191325.46
    Total premium volume: 2172848.70
    
    
    
    
    Done in 4.03s.

**Comment by dtmkeng** [comment]
hi, you want to list `dexs` (swap volume ) or `options` ?

**Comment by timongll** [comment]
`options` and `derivatives`

**Comment by dtmkeng** [comment]
> 

okay could you edit `dexs` adapter return field `dailyVolume` and totalVolume (optional)

**Comment by llamatester** [comment]
The aevo adapter exports: 
        
 
 _______________________________________
    Dexs for 27/7/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690416000
    Daily volume: 2177410.94
    Total volume: 204203263.53
    
    
    
    
    Done in 4.58s.

**Comment by llamatester** [comment]
The aevo adapter exports: 
        
 
 _______________________________________
    Options for 27/7/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690416000
    Daily notional volume: 2177410.94
    Daily premium volume: 44407.67
    Total notional volume: 204203263.53
    Total premium volume: 2172852.03
    
    
    
    
    Done in 4.30s.

**Comment by timongll** [comment]
done!

**Comment by timongll** [comment]
@dtmkeng updated files https://github.com/DefiLlama/dimension-adapters/pull/679

**Comment by dtmkeng** [comment]
seem we count aevo perp volume as options volume could you check dexs adapter  ?

**Comment by timongll** [comment]
sorry could you clarify, so /options counts perp volume but /dexs doesn't?

**Comment by dtmkeng** [comment]
no mean derivatives use option volume
https://defillama.com/derivatives

**Comment by timongll** [comment]
so derivatives will only count option volume, not perp volume?

**Comment by dtmkeng** [comment]
> so derivatives will only count option volume, not perp volume?

not sure about your API just have complaint ` counting aevo perp volume as options volume`

**Comment by dtmkeng** [comment]
we will hide aevo on derivatives and show only option, sorry about that

**Pull request merged**
