### PR TITLE
Amphor - Add PTezETH vault, PTrsETH vault, PTweETH vault

### PR DESCRIPTION
**Pull request by blablalf**

### CODE REVIEW

**Comment by llamatester** [comment]
The amphor adapter exports: 
        
 
 _______________________________________
    Fees for 18/3/2024
    _______________________________________
    
    TypeError: Cannot read properties of undefined (reading 'id')
        at data (/home/runner/work/dimension-adapters/dimension-adapters/fees/amphor/index.ts:97:31)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:29:18)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:59:21 {
      chain: 'ethereum'
    }
    Done in 8.47s.

**Comment by blablalf** [comment]
Ups, I'm going to fix this asap

**Comment by llamatester** [comment]
The amphor adapter exports: 
        
 
 _______________________________________
    Fees for 20/3/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 6/10/2023
    Timestamp: 1710979199 (2024-03-20T23:59:59.000Z)
    Total fees: 122.65 k
    └─ Methodology: Includes all treasury revenue.
    Total revenue: -895592
    └─ Methodology: Sum of protocol revenue.
    Total protocol revenue: 122.65 k
    └─ Methodology: Share of revenue going to Amphor treasury.
    Total user fees: 122.65 k
    └─ Methodology: Include performance fees.
    Daily fees: 0
    └─ Methodology: Includes all treasury revenue.
    Daily protocol revenue: 0
    └─ Methodology: Share of revenue going to Amphor treasury.
    Daily revenue: 0
    └─ Methodology: Sum of protocol revenue.
    
    
    
    
    Done in 48.50s.

**Comment by llamatester** [comment]
The amphor adapter exports: 
        
 
 _______________________________________
    Fees for 20/3/2024
    _______________________________________
    
    {
      llamaRPCError: true,
      errors: [
        { host: 'https://cloudflare-eth.com', error: [AxiosError] },
        { host: 'https://singapore.rpc.blxrbdn.com', error: [Object] },
        { host: 'https://virginia.rpc.blxrbdn.com', error: [Object] }
      ],
      chain: 'ethereum'
    }
    Done in 101.95s.

**Comment by llamatester** [comment]
The amphor adapter exports: 
        
 
 _______________________________________
    Fees for 20/3/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 6/10/2023
    Timestamp: 1710979199 (2024-03-20T23:59:59.000Z)
    Total fees: 122.65 k
    └─ Methodology: Includes all treasury revenue.
    Total protocol revenue: 122.65 k
    └─ Methodology: Share of revenue going to Amphor treasury.
    Total user fees: 122.65 k
    └─ Methodology: Include performance fees.
    Daily fees: 0
    └─ Methodology: Includes all treasury revenue.
    Daily protocol revenue: 0
    └─ Methodology: Share of revenue going to Amphor treasury.
    
    
    
    
    Done in 345.19s.

**Comment by blablalf** [comment]
It is okay to me ✅

**Pull request merged**
