### PR TITLE
Add Bitoro adapter

### PR DESCRIPTION
**Pull request by bluestars1233**
Integrate Bitoro Adapter into DefiLlama's aggregator-derivatives which returns daily and total volumes.

### CODE REVIEW

**Comment by bluestars1233** [comment]
Hi DefiLlama team!
I'm curious about the timeline for reviewing and potentially merging this PR.
Thank you!

**Comment by bluestars1233** [comment]
Hi @dtmkeng, just checking in again on the status of this PR.
I understand you might be busy, but any update on the estimated timeline for review would be greatly appreciated.
Thanks!

**Comment by bluestars1233** [comment]
Hey @dtmkeng 
Thanks for merging my pr!
I'm wondering if you need Bitoro logo to display alongside our data on your DefiLlama. If so, please let me know the preferred format and dimensions, and I'll provide it right away.
Thanks again for your work and support!

**Comment by opensea0508** [comment]
Hi @dtmkeng 
Can we change logo and name? from `Bitoro` to `Bitoro Network`?
This would be new logo. Much appreciated!
btoro

**Pull request merged**
