### PR TITLE
new data fetch for upgrade

### PR DESCRIPTION
**Pull request by algtm**
please backfill data since 1732233600

### CODE REVIEW

**Comment by llamatester** [comment]
The udex-agg adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators udex-agg
    
    🦙 Running UDEX-AGG adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 26 Nov 2024 07:21:10 GMT
    End Date:	Wed, 27 Nov 2024 07:21:10 GMT
    ---------------------------------------------------
    
    https://public.udex.one/bsc/indexer/56/udex/daliyVolume?from_timestamp=1732605669&to_timestamp=1732692069
    https://public.udex.one/bsc/indexer/56/udex/daliyVolume?from_timestamp=1732605669&to_timestamp=1732692069
    data { code: 200, msg: 'success', data: '22035471.42' }
    https://public.udex.one/bsc/indexer/56/udex/daliyVolume?from_timestamp=1732605669&to_timestamp=1732692069
    https://public.udex.one/bsc/indexer/56/udex/daliyVolume?from_timestamp=1732605669&to_timestamp=1732692069
    https://public.udex.one/bsc/indexer/56/udex/daliyVolume?from_timestamp=1732605669&to_timestamp=1732692069
    BSC 👇
    Backfill start time: 29/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 22.04 M
    End timestamp: 1732692069 (2024-11-27T07:21:09.000Z)
    
    
    POLYGON 👇
    Backfill start time: 29/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1732692069 (2024-11-27T07:21:09.000Z)
    
    
    ETHEREUM 👇
    Backfill start time: 29/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1732692069 (2024-11-27T07:21:09.000Z)
    
    
    BASE 👇
    Backfill start time: 29/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1732692069 (2024-11-27T07:21:09.000Z)
    
    
    OP_BNB 👇
    Backfill start time: 29/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 819.98 k
    End timestamp: 1732692069 (2024-11-27T07:21:09.000Z)

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
hi, can you explain why you using your own api instead of event logs, I am seeing a big difference, 2.7M -> 22M

**Comment by algtm** [comment]
> hi, can you explain why you using your own api instead of event logs, I am seeing a big difference, 2.7M -> 22M↳

Sorry, there was a calculation error in the backend, but it has been corrected. The switch to api is mainly to meet regulatory compliance requirements, such as filtering certain transactions.

**Comment by g1nt0ki** [comment]
@algtm sorry, I am rejecting this PR, we prefer relying on event logs, it is transparent and one less dependency to worry about compared to relying on your api.

**Pull request closed without merging**
