### PR TITLE
Add SubstanceX trade volume

### PR DESCRIPTION
**Pull request by 0scallion**

### CODE REVIEW

**Comment by llamatester** [comment]
The SubstanceX adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    dexs/SubstanceX/index.ts(107,7): error TS2322: Type '{}' is not assignable to type 'Adapter'.
    dexs/SubstanceX/index.ts(108,1): error TS1005: '}' expected.
    
    Done in 2.53s.

**Comment by 0scallion** [comment]
I have completed the changes to the file.  I would appreciate it if you could merge it. Thank you！

**Comment by llamatester** [comment]
The SubstanceX adapter exports: 
        
 
 _______________________________________
    Dexs for 27/11/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 18/11/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1701129598
    Total volume: 6633492562002
    Daily volume: 789806086317
    
    
    
    
    Done in 3.21s.

**Comment by dtmkeng** [comment]
i guess value should div some value, could you check ?

**Comment by llamatester** [comment]
The SubstanceX adapter exports: 
        
 
 _______________________________________
    Dexs for 27/11/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 18/11/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1701129598
    Total volume: 6633492.562002
    Daily volume: 789806.086317
    
    
    
    
    Done in 3.24s.

**Pull request merged**
