### PR TITLE
Update GMX V2 Volume and Swaps Tracking 

### PR DESCRIPTION
**Pull request by K-Lascar**
The main source for the discrepancy was the lack of swaps tracking, more efficient than tracking event logs.
Swap event logs is more complex compared to the volumes.

- Added Volume V2 Tracking
- Added Swaps V2 Tracking

### CODE REVIEW

**Comment by llamatester** [comment]
The gmx-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs gmx-v2
    
    🦙 Running GMX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 05 Aug 2024 04:36:40 GMT
    End Date:	Tue, 06 Aug 2024 04:36:40 GMT
    ---------------------------------------------------
    
    TypeError: Cannot read properties of undefined (reading 'length')
        at /home/runner/work/dimension-adapters/dimension-adapters/dexs/gmx-v2/index.ts:50:29
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:46:18)
        at async Promise.all (index 1)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:26:20)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:82:24 {
      chain: 'avax'
    }

**Comment by llamatester** [comment]
The gmx-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs gmx-v2
    
    🦙 Running GMX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 05 Aug 2024 04:45:53 GMT
    End Date:	Tue, 06 Aug 2024 04:45:53 GMT
    ---------------------------------------------------
    
    TypeError: Cannot read properties of undefined (reading 'length')
        at /home/runner/work/dimension-adapters/dimension-adapters/dexs/gmx-v2/index.ts:50:29
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:46:18)
        at async Promise.all (index 1)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:26:20)
        at async Promise.all (index 1)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:82:24 {
      chain: 'avax'
    }

**Comment by llamatester** [comment]
The gmx-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs gmx-v2
    
    🦙 Running GMX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 05 Aug 2024 04:49:53 GMT
    End Date:	Tue, 06 Aug 2024 04:49:53 GMT
    ---------------------------------------------------
    
    TypeError: Cannot read properties of undefined (reading 'length')
        at /home/runner/work/dimension-adapters/dimension-adapters/dexs/gmx-v2/index.ts:50:29
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:46:18)
        at async Promise.all (index 0)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:26:20)
        at async Promise.all (index 1)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:82:24 {
      chain: 'arbitrum'
    }

**Comment by llamatester** [comment]
The gmx-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs gmx-v2
    
    🦙 Running GMX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 05 Aug 2024 04:51:25 GMT
    End Date:	Tue, 06 Aug 2024 04:51:25 GMT
    ---------------------------------------------------
    
    Version -> SWAP
    ---------
    ARBITRUM 👇
    Backfill start time: 31/8/2021
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722919884 (2024-08-06T04:51:24.000Z)
    Total volume: 1.92 B
    
    
    AVAX 👇
    Backfill start time: 22/12/2021
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722919884 (2024-08-06T04:51:24.000Z)
    Total volume: 147.86 M
    
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 31/8/2021
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722919884 (2024-08-06T04:51:24.000Z)
    Total volume: 48.48 B
    
    
    AVAX 👇
    Backfill start time: 22/12/2021
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722919884 (2024-08-06T04:51:24.000Z)
    Total volume: 1.36 B

**Comment by K-Lascar** [comment]
Added in V2 Volume and Swaps for GMX.
Removed old directory for tracking volumes.

**Comment by llamatester** [comment]
The gmx-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs gmx-v2
    
    🦙 Running GMX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 05 Aug 2024 05:07:19 GMT
    End Date:	Tue, 06 Aug 2024 05:07:19 GMT
    ---------------------------------------------------
    
    Version -> SWAP
    ---------
    ARBITRUM 👇
    Backfill start time: 31/8/2021
    End timestamp: 1722920838 (2024-08-06T05:07:18.000Z)
    Total volume: 1.92 B
    
    
    AVAX 👇
    Backfill start time: 22/12/2021
    End timestamp: 1722920838 (2024-08-06T05:07:18.000Z)
    Total volume: 147.86 M
    
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 31/8/2021
    End timestamp: 1722920838 (2024-08-06T05:07:18.000Z)
    Total volume: 48.48 B
    
    
    AVAX 👇
    Backfill start time: 22/12/2021
    End timestamp: 1722920838 (2024-08-06T05:07:18.000Z)
    Total volume: 1.36 B

**Comment by llamatester** [comment]
The gmx-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs gmx-v2
    
    🦙 Running GMX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 05 Aug 2024 07:47:01 GMT
    End Date:	Tue, 06 Aug 2024 07:47:01 GMT
    ---------------------------------------------------
    
    Version -> SWAP
    ---------
    ARBITRUM 👇
    Backfill start time: 31/8/2021
    End timestamp: 1722930420 (2024-08-06T07:47:00.000Z)
    Total volume: 1.92 B
    
    
    AVAX 👇
    Backfill start time: 22/12/2021
    End timestamp: 1722930420 (2024-08-06T07:47:00.000Z)
    Total volume: 147.90 M
    
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 31/8/2021
    End timestamp: 1722930420 (2024-08-06T07:47:00.000Z)
    Total volume: 48.49 B
    
    
    AVAX 👇
    Backfill start time: 22/12/2021
    End timestamp: 1722930420 (2024-08-06T07:47:00.000Z)
    Total volume: 1.36 B

**Comment by llamatester** [comment]
The radiant.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees radiant.ts
    
    🦙 Running RADIANT.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 05 Aug 2024 00:00:00 GMT
    End Date:	Tue, 06 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 18/3/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 7.51 k
    Daily supply side revenue: 1.88 k
    Daily holders revenue: 4.50 k
    Daily protocol revenue: 1.13 k
    Daily revenue: 5.63 k
    End timestamp: 1722902399 (2024-08-05T23:59:59.000Z)
    
    
    BSC 👇
    Backfill start time: 26/3/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 2.99 k
    Daily supply side revenue: 748
    Daily holders revenue: 1.79 k
    Daily protocol revenue: 449
    Daily revenue: 2.24 k
    End timestamp: 1722902399 (2024-08-05T23:59:59.000Z)
    
    
    ETHEREUM 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 2.71 k
    Daily supply side revenue: 678
    Daily holders revenue: 1.63 k
    Daily protocol revenue: 407
    Daily revenue: 2.03 k
    End timestamp: 1722902399 (2024-08-05T23:59:59.000Z)
    
    
    BASE 👇
    Backfill start time: 28/6/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 1.81 k
    Daily supply side revenue: 452
    Daily holders revenue: 1.08 k
    Daily protocol revenue: 271
    Daily revenue: 1.36 k
    End timestamp: 1722902399 (2024-08-05T23:59:59.000Z)

**Pull request merged**
