### PR TITLE
OptionBlitz

### PR DESCRIPTION
**Pull request by web3dev00**

### CODE REVIEW

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Fees for 27/3/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    Daily fees: 0
    └─ Methodology: Trade collateral collected.
    Total fees: 0
    └─ Methodology: Trade collateral collected.
    Timestamp: 1711584000000 (+056207-12-10T00:00:00.000Z)
    
    
    
    
    Done in 3.43s.

**Comment by dtmkeng** [comment]
it seem you adapter return total volume  at field `dailyVolume` could you check ?

**Comment by dtmkeng** [comment]
if need list options volume could move to under `options` folder and return 
```
    dailyNotionalVolume,
    dailyPremiumVolume,
    totalNotionalVolume,
    totalPremiumVolume,
```

**Comment by web3dev00** [comment]
> it seem you adapter return total volume at field `dailyVolume` could you check ?

I checked it and run it on my system to check the results and it seems to work fine. Here is the result image I shared.
image

**Comment by optionblitz** [comment]
> it seem you adapter return total volume at field `dailyVolume` could you check ?

It is because we set the first day to start counting data as that date which explains why daily and total is the same. Please proceed with the merge

**Comment by dtmkeng** [comment]
> if need list options volume could move to under `options` folder and return
> 
> ```
>     dailyNotionalVolume,
>     dailyPremiumVolume,
>     totalNotionalVolume,
>     totalPremiumVolume,
> ```

options volume should return field like this

**Comment by optionblitz** [comment]
> > if need list options volume could move to under `options` folder and return
> > ```
> >     dailyNotionalVolume,
> >     dailyPremiumVolume,
> >     totalNotionalVolume,
> >     totalPremiumVolume,
> > ```
> 
> options volume should return field like this

we can only return 

> >     dailyPremiumVolume,
> >     totalPremiumVolume,

and this is the same data as

dailyvolume
totalvolume

**Comment by dtmkeng** [comment]
> > > if need list options volume could move to under `options` folder and return
> > > ```
> > >     dailyNotionalVolume,
> > >     dailyPremiumVolume,
> > >     totalNotionalVolume,
> > >     totalPremiumVolume,
> > > ```
> > 
> > 
> > options volume should return field like this
> 
> we can only return
> 
> > > ```
> > > dailyPremiumVolume,
> > > totalPremiumVolume,
> > > ```
> 
> and this is the same data as
> 
> dailyvolume totalvolume

yes can you fix ?

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Dexs for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    NO METHODOLOGY SPECIFIED
    Daily premium volume: 65.95 k
    Total premium volume: 3.57 M
    Timestamp: 1712102400000 (+056224-05-14T00:00:00.000Z)
    
    
    
    
    Done in 60.36s.

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Fees for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    Daily fees: -16
    └─ Methodology: Trade collateral collected.
    Total fees: 69
    └─ Methodology: Trade collateral collected.
    Timestamp: 1712102400000 (+056224-05-14T00:00:00.000Z)
    
    
    
    
    Done in 6.41s.

**Comment by optionblitz** [comment]
@dtmkeng is that ok now?

**Comment by dtmkeng** [comment]
is there `dailyNotionalVolume` volume ? 
and could you revert change at yarn lock ?

**Comment by optionblitz** [comment]
> is there `dailyNotionalVolume` volume ? and could you revert change at yarn lock ?

no there is no `dailyNotionalVolume` volume 

yes, will instruct dev to revert change at yarn lock

**Comment by dtmkeng** [comment]
hmm not sure if list it should 0 it is okay ? 
why options product does not have trade volume ?

**Comment by optionblitz** [comment]
> hmm not sure if list it should 0 it is okay ? why options product does not have trade volume ?

Yes its ok or just duplicate premium volume, notional volume is not available because these types of options do not count the notional.

**Comment by dtmkeng** [comment]
> > hmm not sure if list it should 0 it is okay ? why options product does not have trade volume ?
> 
> Yes its ok or just duplicate premium volume, notional volume is not available because these types of options do not count the notional.

why premium is equal notional volume ?

**Comment by dtmkeng** [comment]
> > > > hmm not sure if list it should 0 it is okay ? why options product does not have trade volume ?
> > > 
> > > 
> > > Yes its ok or just duplicate premium volume, notional volume is not available because these types of options do not count the notional.
> > 
> > 
> > why premium is equal notional volume ?
> 
> to avoid it just being 0

premium ?

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Dexs for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    NO METHODOLOGY SPECIFIED
    Daily volume: 65.97 k
    Total volume: 3.57 M
    Timestamp: 1712102400000 (+056224-05-14T00:00:00.000Z)
    
    
    
    
    Done in 8.88s.

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Fees for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    Daily fees: -16
    └─ Methodology: Trade collateral collected.
    Total fees: 69
    └─ Methodology: Trade collateral collected.
    Timestamp: 1712102400000 (+056224-05-14T00:00:00.000Z)
    
    
    
    
    Done in 6.11s.

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Dexs for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    NO METHODOLOGY SPECIFIED
    Daily premium volume: 65.97 k
    Total premium volume: 3.57 M
    Timestamp: 1712102400000 (+056224-05-14T00:00:00.000Z)
    
    
    
    
    Done in 6.18s.

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Dexs for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    NO METHODOLOGY SPECIFIED
    Daily premium volume: 65.88 k
    Total premium volume: 3.56 M
    Timestamp: 1712102400000 (+056224-05-14T00:00:00.000Z)
    
    
    
    
    Done in 7.97s.

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Fees for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    Daily fees: -16
    └─ Methodology: Trade collateral collected.
    Total fees: 69
    └─ Methodology: Trade collateral collected.
    Timestamp: 1712102400000 (+056224-05-14T00:00:00.000Z)
    
    
    
    
    Done in 37.01s.

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Fees for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    Daily fees: -16
    └─ Methodology: Trade collateral collected.
    Total fees: 68
    └─ Methodology: Trade collateral collected.
    Timestamp: 1712102400000 (+056224-05-14T00:00:00.000Z)
    
    
    
    
    Done in 4.52s.

**Comment by optionblitz** [comment]
> > > > > hmm not sure if list it should 0 it is okay ? why options product does not have trade volume ?
> > > > 
> > > > 
> > > > Yes its ok or just duplicate premium volume, notional volume is not available because these types of options do not count the notional.
> > > 
> > > 
> > > why premium is equal notional volume ?
> > 
> > 
> > to avoid it just being 0
> 
> premium ?

? what do you mean here

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Fees for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    Daily fees: -16
    └─ Methodology: Trade collateral collected.
    Total fees: 68
    └─ Methodology: Trade collateral collected.
    Timestamp: 1712102400000 (+056224-05-14T00:00:00.000Z)
    
    
    
    
    Done in 5.74s.

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Options for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    NO METHODOLOGY SPECIFIED
    Timestamp: 1712102400000 (+056224-05-14T00:00:00.000Z)
    Daily notional volume: 65.83 k
    Daily premium volume: 0
    Total notional volume: 3.56 M
    Total premium volume: 0
    
    
    
    
    Done in 8.73s.

**Comment by dtmkeng** [comment]
is it correct ?

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Fees for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    Daily fees: 29
    └─ Methodology: Trade collateral collected.
    Total fees: 69
    └─ Methodology: Trade collateral collected.
    Timestamp: 1712016000 (2024-04-02T00:00:00.000Z)
    
    
    
    
    Done in 40.70s.

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Options for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    NO METHODOLOGY SPECIFIED
    Timestamp: 1712016000 (2024-04-02T00:00:00.000Z)
    Daily notional volume: 473.37 k
    Daily premium volume: 0
    Total notional volume: 3.57 M
    Total premium volume: 0
    
    
    
    
    Done in 20.80s.

**Comment by optionblitz** [comment]
> is it correct ?

yes

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Options for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    NO METHODOLOGY SPECIFIED
    Timestamp: 1712016000 (2024-04-02T00:00:00.000Z)
    Daily notional volume: 473.37 k
    Daily premium volume: 0
    Total notional volume: 3.57 M
    Total premium volume: 0
    
    
    
    
    Done in 7.71s.

**Comment by optionblitz** [comment]
> Daily notional volume: 473.37 k
> Daily premium volume: 0
> Total notional volume: 3.57 M
> Total premium volume: 0

should be


Daily notional volume: 0
Daily premium volume: 473.37 k
Total notional volume: 0
Total premium volume: 3.57 M

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Fees for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    Daily fees: 29
    └─ Methodology: Trade collateral collected.
    Total fees: 69
    └─ Methodology: Trade collateral collected.
    Timestamp: 1712016000 (2024-04-02T00:00:00.000Z)
    
    
    
    
    Done in 8.16s.

**Comment by llamatester** [comment]
The optionBlitz adapter exports: 
        
 
 _______________________________________
    Options for 2/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/1976
    NO METHODOLOGY SPECIFIED
    Timestamp: 1712016000 (2024-04-02T00:00:00.000Z)
    Daily notional volume: 0
    Daily premium volume: 472.89 k
    Total notional volume: 0
    Total premium volume: 3.57 M
    
    
    
    
    Done in 7.11s.

**Comment by optionblitz** [comment]
> The optionBlitz adapter exports:
> 
> ```
> Options for 2/4/2024
> _______________________________________
> 
> ARBITRUM 👇
> Backfill start time: 4/3/1976
> NO METHODOLOGY SPECIFIED
> Timestamp: 1712016000 (2024-04-02T00:00:00.000Z)
> Daily notional volume: 0
> Daily premium volume: 472.89 k
> Total notional volume: 0
> Total premium volume: 3.57 M
> 
> 
> 
> 
> Done in 7.11s.
> ```

perfect

**Comment by dtmkeng** [comment]
could you check your value ppl compliant it is fake value ?

**Comment by optionblitz** [comment]
> could you check your value ppl compliant it is fake value ?

I think there is too many 000s

**Comment by optionblitz** [comment]
> could you check your value ppl compliant it is fake value ?

can you just divide the values by 1000 to get correct value

**Pull request merged**
