### PR TITLE
add staking and usd vault revenue ether.fi

### PR DESCRIPTION
**Pull request by vvalecha519**

### CODE REVIEW

**Comment by llamatester** [comment]
The ether-fi adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees ether-fi
    
    🦙 Running ETHER-FI adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 05 Nov 2024 16:06:31 GMT
    End Date:	Wed, 06 Nov 2024 16:06:31 GMT
    ---------------------------------------------------
    
    TypeError: Cannot mix BigInt and other types, use explicit conversions
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/ether-fi/index.ts:59:27)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:51:18)
        at async Promise.all (index 0)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:27:20)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:84:21 {
      chain: 'ethereum'
    }

**Comment by llamatester** [comment]
The ether-fi adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees ether-fi
    
    🦙 Running ETHER-FI adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 05 Nov 2024 16:07:41 GMT
    End Date:	Wed, 06 Nov 2024 16:07:41 GMT
    ---------------------------------------------------
    
    TypeError: Cannot mix BigInt and other types, use explicit conversions
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/ether-fi/index.ts:59:27)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:51:18)
        at async Promise.all (index 0)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:27:20)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:84:21 {
      chain: 'ethereum'
    }

**Comment by llamatester** [comment]
The ether-fi adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees ether-fi
    
    🦙 Running ETHER-FI adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 05 Nov 2024 16:14:28 GMT
    End Date:	Wed, 06 Nov 2024 16:14:28 GMT
    ---------------------------------------------------
    
    TypeError: Cannot mix BigInt and other types, use explicit conversions
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/ether-fi/index.ts:56:27)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:51:18)
        at async Promise.all (index 0)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:27:20)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:84:21 {
      chain: 'ethereum'
    }

**Comment by llamatester** [comment]
The ether-fi adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees ether-fi
    
    🦙 Running ETHER-FI adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 05 Nov 2024 19:26:58 GMT
    End Date:	Wed, 06 Nov 2024 19:26:58 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 12/3/2024
    Daily fees: 56.15 k
    End timestamp: 1730921217 (2024-11-06T19:26:57.000Z)

**Comment by dtmkeng** [comment]
should i refill data ?, is there range your prefer ?

**Pull request merged**
