### PR TITLE
Add Quickswap Perps, Quickswap Hydra, LineHub V2 and LineHub V3 adapters

### PR DESCRIPTION
**Pull request by 0xrmvdao**

### CODE REVIEW

**Comment by llamatester** [comment]
The linehub-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs linehub-v2
    
    🦙 Running LINEHUB-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 16 Oct 2024 04:54:46 GMT
    End Date:	Thu, 17 Oct 2024 04:54:46 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 17/10/2024
    NO METHODOLOGY SPECIFIED
    Block: 10.85 M
    Total volume: 1.32 k
    Daily volume: 1
    End timestamp: 1729140885 (2024-10-17T04:54:45.000Z)

**Comment by llamatester** [comment]
The quickswap-perps adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs quickswap-perps
    
    🦙 Running QUICKSWAP-PERPS adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 16 Oct 2024 04:56:16 GMT
    End Date:	Thu, 17 Oct 2024 04:56:16 GMT
    ---------------------------------------------------
    
    POLYGON_ZKEVM 👇
    Backfill start time: 1/1/2024
    Daily volume: 18.92 k
    Total volume: 151.05 M
    End timestamp: 1729140975 (2024-10-17T04:56:15.000Z)

**Comment by llamatester** [comment]
The linehub-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees linehub-v2
    
    🦙 Running LINEHUB-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 16 Oct 2024 00:00:00 GMT
    End Date:	Thu, 17 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 1/3/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1729036800 (2024-10-16T00:00:00.000Z)
    Daily fees: 0
    Total fees: 4

**Comment by llamatester** [comment]
The linehub-v3 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees linehub-v3
    
    🦙 Running LINEHUB-V3 adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 16 Oct 2024 00:00:00 GMT
    End Date:	Thu, 17 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 1/3/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1729036800 (2024-10-16T00:00:00.000Z)
    Daily fees: 10
    Total fees: 2.91 k

**Comment by llamatester** [comment]
The quickswap-hydra adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees quickswap-hydra
    
    🦙 Running QUICKSWAP-HYDRA adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 16 Oct 2024 00:00:00 GMT
    End Date:	Thu, 17 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    POLYGON_ZKEVM 👇
    Backfill start time: 1/1/2024
    Methodology: All treasuryFee, poolFee and keeperFee are collected
    End timestamp: 1729036800 (2024-10-16T00:00:00.000Z)
    Daily fees: 0
    Total fees: 1.96 k
    
    
    MANTA 👇
    Backfill start time: 1/1/2024
    Methodology: All treasuryFee, poolFee and keeperFee are collected
    End timestamp: 1729036800 (2024-10-16T00:00:00.000Z)
    Daily fees: 12
    Total fees: 223

**Comment by llamatester** [comment]
The quickswap-perps adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees quickswap-perps
    
    🦙 Running QUICKSWAP-PERPS adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 16 Oct 2024 00:00:00 GMT
    End Date:	Thu, 17 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    POLYGON_ZKEVM 👇
    Backfill start time: 1/3/2024
    Methodology: All treasuryFee, poolFee and keeperFee are collected
    End timestamp: 1729036800 (2024-10-16T00:00:00.000Z)
    Daily fees: 41
    Total fees: 394.76 k

**Comment by g1nt0ki** [comment]
thanks, merged with a minor fix here: https://github.com/DefiLlama/dimension-adapters/pull/2014

**Pull request closed without merging**
