### PR TITLE
Add dexs, fee for Gambit arbitrum 

### PR DESCRIPTION
**Pull request by ALPHADA**
#### Link : https://defillama.com/protocol/gambit-trade

### CODE REVIEW

**Comment by llamatester** [comment]
The gambit adapter exports: 
        
 
 _______________________________________
    Dexs for 5/11/2023
    _______________________________________
    
    Version -> V1
    ---------
    ERA 👇
    Backfill start time: 31/7/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1699228799
    
    
    Version -> V2
    ---------
    ERA 👇
    Backfill start time: 2/11/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1699228799
    
    
    ARBITRUM 👇
    Backfill start time: 2/11/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1699228799
    
    
    Done in 4.73s.

**Comment by llamatester** [comment]
The gambit.ts adapter exports: 
        
 
 _______________________________________
    Fees for 5/11/2023
    _______________________________________
    
    Version -> V1
    ---------
    ERA 👇
    Backfill start time: 31/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699228799
    Daily fees: 0
    Daily revenue: 0
    Daily holders revenue: 0
    
    
    Version -> V2
    ---------
    ERA 👇
    Backfill start time: 2/11/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699228799
    Daily fees: 0
    Daily revenue: 0
    Daily holders revenue: 0
    
    
    ARBITRUM 👇
    Backfill start time: 2/11/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699228799
    Daily fees: 0
    Daily revenue: 0
    Daily holders revenue: 0
    
    
    Done in 4.47s.

**Comment by ALPHADA** [comment]
Is it possible to view different contract addresses separately based on a specific time instead of separating them into v1 and v2?
v1 is completely replaced by v2.

**Comment by dtmkeng** [comment]
> Is it possible to set contract addresses separately based on a specific time, instead of separating them into v1 and v2? v1 is completely replaced by v2.
yeah i can if you split tvl adapter version v1,v2 i will split fees n volume

**Comment by ALPHADA** [comment]
I don't want to split it into v1 and v2.
Is it possible to divide two contract addresses in one network, like the code below?
```
const adapter: SimpleAdapter = {
  adapter: {
    [CHAIN.ERA]: {
      fetch: fetch(CHAIN.ERA, contract_address_v1[CHAIN.ERA], 0),
      start: async () => 1690761600, // 2023/07/31 00:00:00
    },
    [CHAIN.ERA]: {
      fetch: fetch(CHAIN.ERA),
      start: async () => 1698883200, // 2023/11/02 00:00:00
    },
    [CHAIN.ARBITRUM]: {
      fetch: fetch(CHAIN.ARBITRUM),
      start: async () => 1698883200, // 2023/11/02 00:00:00
    }
  }
};
```

**Comment by dtmkeng** [comment]
if you don't need split adapter you should sum two contract volume on same chain 
example era volume => volume from contract v1 + contract v2

**Comment by llamatester** [comment]
The gambit adapter exports: 
        
 
 _______________________________________
    Dexs for 6/11/2023
    _______________________________________
    
    Version -> V1
    ---------
    ERA 👇
    Backfill start time: 31/7/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1699315199
    
    
    Version -> V2
    ---------
    ERA 👇
    Backfill start time: 2/11/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 36360.310752000005
    Timestamp: 1699315199
    
    
    ARBITRUM 👇
    Backfill start time: 2/11/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 31280
    Timestamp: 1699315199
    
    
    Done in 5.75s.

**Comment by llamatester** [comment]
The gambit.ts adapter exports: 
        
 
 _______________________________________
    Fees for 6/11/2023
    _______________________________________
    
    ERA 👇
    Backfill start time: 1/8/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699315198
    Daily fees: 5.272184
    Daily revenue: 0
    Daily holders revenue: 0
    
    
    ARBITRUM 👇
    Backfill start time: 2/11/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699315198
    Daily fees: 7.2012
    Daily revenue: 4.428408
    Daily holders revenue: 4.428408
    
    
    
    
    Done in 6.10s.

**Comment by llamatester** [comment]
The gambit adapter exports: 
        
 
 _______________________________________
    Dexs for 6/11/2023
    _______________________________________
    
    ERA 👇
    Backfill start time: 1/8/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 23023.403096000002
    Timestamp: 1699315198
    
    
    ARBITRUM 👇
    Backfill start time: 2/11/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 12809.4
    Timestamp: 1699315198
    
    
    
    
    Done in 5.19s.

**Comment by llamatester** [comment]
The gambit.ts adapter exports: 
        
 
 _______________________________________
    Fees for 6/11/2023
    _______________________________________
    
    ERA 👇
    Backfill start time: 1/8/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699315198
    Daily fees: 5.272184
    Daily revenue: 0
    Daily holders revenue: 0
    
    
    ARBITRUM 👇
    Backfill start time: 2/11/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699315198
    Daily fees: 7.2012
    Daily revenue: 4.428408
    Daily holders revenue: 4.428408
    
    
    
    
    Done in 4.93s.

**Comment by ALPHADA** [comment]
@dtmkeng 
The code has been modified.
Please check and merge.

**Pull request merged**
