### PR TITLE
kriya clmm volume

### PR DESCRIPTION
**Pull request by Knight-101**
Hi team,

This is Kriya's Defillama space: https://defillama.com/protocol/kriya#information

We recently added a sub-category 'Kriya CLMM' (related PR: https://defillama.com/protocol/kriya#information)

I am raising this PR to add Kriya CLMM's Volume to Defilamma. The volume adapter for Kriya AMM will stay as it is and Kriya's volume = Kriya AMM volume + Kriya CLMM Volume

Folder wise mapping:-
kriya-dex -> Kriya AMM
kriya-clmm -> Kriya CLMM

Let me know if this PR works for the same

Thanks

### CODE REVIEW

**Comment by llamatester** [comment]
The kriya-clmm adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs kriya-clmm
    
    🦙 Running KRIYA-CLMM adapter 🦙
    ---------------------------------------------------
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The kriya-clmm adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs kriya-clmm
    
    🦙 Running KRIYA-CLMM adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 23 Jul 2024 07:59:27 GMT
    End Date:	Wed, 24 Jul 2024 07:59:27 GMT
    ---------------------------------------------------
    
    [Error: Request failed with status code 400] {
      url: 'https://tkmw8dmcp8.execute-api.ap-southeast-1.amazonaws.com/prod/volume/clmm[object Object]',
      method: 'GET',
      axiosError: 'Bad Request',
      chain: 'sui'
    }

**Comment by llamatester** [comment]
The kriya-clmm adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs kriya-clmm
    
    🦙 Running KRIYA-CLMM adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 23 Jul 2024 08:01:00 GMT
    End Date:	Wed, 24 Jul 2024 08:01:00 GMT
    ---------------------------------------------------
    
    [Error: Request failed with status code 400] {
      url: 'https://tkmw8dmcp8.execute-api.ap-southeast-1.amazonaws.com/prod/volume/clmm/[object Object]',
      method: 'GET',
      axiosError: 'Bad Request',
      chain: 'sui'
    }

**Comment by llamatester** [comment]
The kriya-clmm adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs kriya-clmm
    
    🦙 Running KRIYA-CLMM adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 23 Jul 2024 08:15:17 GMT
    End Date:	Wed, 24 Jul 2024 08:15:17 GMT
    ---------------------------------------------------
    
    SUI 👇
    Backfill start time: 9/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 13.72 M
    Daily volume: 2.76 M
    End timestamp: 1721808916 (2024-07-24T08:15:16.000Z)

**Comment by dtmkeng** [comment]
could you check api it error 500

**Comment by dtmkeng** [comment]
hmm seem it can backfill sine  Jul 20 2024

**Pull request merged**
