### PR TITLE
[levana] - Add neutron stats

### PR DESCRIPTION
**Pull request by lvn-talented-dragon**
A small update to add neutron mainnet to the adapter.

### CODE REVIEW

**Comment by llamatester** [comment]
The levana adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs levana
    
    🦙 Running LEVANA adapter 🦙
    ---------------------------------------------------
    dexs/levana/fetch.ts(13,5): error TS1005: ',' expected.

**Comment by llamatester** [comment]
The levana adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs levana
    
    🦙 Running LEVANA adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 02 Sep 2024 00:00:00 GMT
    End Date:	Tue, 03 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 95079999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 95079999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    OSMOSIS 👇
    Backfill start time: 6/7/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1725321599 (2024-09-02T23:59:59.000Z)
    Daily volume: 1.80 M
    Total volume: 2.91 B
    
    
    SEI 👇
    Backfill start time: 6/8/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1725321599 (2024-09-02T23:59:59.000Z)
    Daily volume: 0
    Total volume: 41.03 M
    
    
    INJECTIVE 👇
    Backfill start time: 26/9/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1725321599 (2024-09-02T23:59:59.000Z)
    Daily volume: 17.21 k
    Total volume: 177.39 M
    
    
    NEUTRON 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1725321599 (2024-09-02T23:59:59.000Z)
    Daily volume: 7.65 k
    Total volume: 944.06 k

**Comment by lvn-talented-dragon** [comment]
> The levana adapter exports:
> 
> ```
> ...
> error fetching block [Error: Llama RPC error! methos: undefined 
> - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 95079999)] {
>   _underlyingError: '[object Object]',
>   _isCustomError: true
> }
> error fetching block [Error: Llama RPC error! methos: undefined 
> - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 95079999)] {
>   _underlyingError: '[object Object]',
>   _isCustomError: true
> }
> ...
> ```
Hi Team, Could you give me an advice on how to proceed with this issue?
The error shows that there're some issues on Sei but I was not able to find any data gap on DefiLlama page for Levana.

**Comment by dtmkeng** [comment]
> > The levana adapter exports:
> > ```
> > ...
> > error fetching block [Error: Llama RPC error! methos: undefined 
> > - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 95079999)] {
> >   _underlyingError: '[object Object]',
> >   _isCustomError: true
> > }
> > error fetching block [Error: Llama RPC error! methos: undefined 
> > - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 95079999)] {
> >   _underlyingError: '[object Object]',
> >   _isCustomError: true
> > }
> > ...
> > ```
> 
> Hi Team, Could you give me an advice on how to proceed with this issue, please? The error shows that there're some issues on Sei but I was not able to find any data gap on DefiLlama page for Levana.

sei rpc cant get block, value is correct ?

**Comment by lvn-talented-dragon** [comment]
> sei rpc cant get block, value is correct ?
We only added neutron network to the adapters list.
The config values for Sei does not changes for this PR.

**Pull request merged**
