### PR TITLE
Add arbitrum subgraphs

### PR DESCRIPTION
**Pull request by paulvaden**

### CODE REVIEW

**Comment by llamatester** [comment]
The lyra adapter exports: 
        
 
 _______________________________________
    Options for 22/1/2023
    _______________________________________
    
    OPTIMISM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1674431998
    Total premium volume: 18778200
    Total notional volume: 447741934
    Daily premium volume: 19553
    Daily notional volume: 1016079
    
    
    ARBITRUM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1674431998
    Total premium volume: 0
    Total notional volume: 0
    Daily premium volume: 0
    Daily notional volume: 0
    
    
    
    
    Done in 7.97s.

**Comment by dtmkeng** [comment]
hi, I run test on my local, but fee/Options do not have value could you check ARBITRUM endpoint

**Comment by paulvaden** [comment]
> hi, I run test on my local, but fee/Options do not have value could you check ARBITRUM endpoint ?

Hi, this is expected, there are no expiries listed yet so there is no volume/fees.  Expiries will be listed tomorrow, and at that point volume/fees should start showing up.

**Comment by dtmkeng** [comment]
> > hi, I run test on my local, but fee/Options do not have value could you check ARBITRUM endpoint ?
> 
> Hi, this is expected, there are no expiries listed yet so there is no volume/fees. Expiries will be listed tomorrow, and at that point volume/fees should start showing up.

oke let me run check again tomorrow

**Comment by llamatester** [comment]
The lyra.ts adapter exports: 
        
 
 _______________________________________
    Fees for 30/1/2023
    _______________________________________
    
    OPTIMISM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1675123198
    Daily fees: 3123
    
    
    
    
    Done in 5.59s.

**Comment by llamatester** [comment]
The lyra adapter exports: 
        
 
 _______________________________________
    Options for 30/1/2023
    _______________________________________
    
    OPTIMISM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1675123198
    Total premium volume: 18951358
    Total notional volume: 455750617
    Daily premium volume: 44747
    Daily notional volume: 1808508
    
    
    ARBITRUM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1675123198
    Total premium volume: 13810
    Total notional volume: 568542
    Daily premium volume: 11
    Daily notional volume: 1611
    
    
    
    
    Done in 12.67s.

**Pull request merged**
