### PR TITLE
chore: fix some typos in comment

### PR DESCRIPTION
**Pull request by ianlv**

### CODE REVIEW

**Comment by dtmkeng** [comment]
useless sorry

**Comment by llamatester** [comment]
The impermax-finance.ts adapter exports: 
        
 
 _______________________________________
    Fees for 3/5/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 23/10/2023
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees are calculated as 90% of the borrowing fees for qualified pools, paid by the borrowers to the lenders.
    Daily revenue: 0
    └─ Methodology: Revenue is the remaining 10% of all collected borrowing fees and go to the protocol.
    
    
    POLYGON 👇
    Backfill start time: 23/10/2023
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees are calculated as 90% of the borrowing fees for qualified pools, paid by the borrowers to the lenders.
    Daily revenue: 0
    └─ Methodology: Revenue is the remaining 10% of all collected borrowing fees and go to the protocol.
    
    
    ARBITRUM 👇
    Backfill start time: 23/10/2023
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees are calculated as 90% of the borrowing fees for qualified pools, paid by the borrowers to the lenders.
    Daily revenue: 0
    └─ Methodology: Revenue is the remaining 10% of all collected borrowing fees and go to the protocol.
    
    
    AVAX 👇
    Backfill start time: 23/10/2023
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees are calculated as 90% of the borrowing fees for qualified pools, paid by the borrowers to the lenders.
    Daily revenue: 0
    └─ Methodology: Revenue is the remaining 10% of all collected borrowing fees and go to the protocol.
    
    
    ERA 👇
    Backfill start time: 23/10/2023
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees are calculated as 90% of the borrowing fees for qualified pools, paid by the borrowers to the lenders.
    Daily revenue: 0
    └─ Methodology: Revenue is the remaining 10% of all collected borrowing fees and go to the protocol.
    
    
    FANTOM 👇
    Backfill start time: 23/10/2023
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees are calculated as 90% of the borrowing fees for qualified pools, paid by the borrowers to the lenders.
    Daily revenue: 0
    └─ Methodology: Revenue is the remaining 10% of all collected borrowing fees and go to the protocol.

**Comment by llamatester** [comment]
The kyberswap.ts adapter exports: 
        
 
 _______________________________________
    Fees for 3/5/2024
    _______________________________________
    
    Version -> CLASSIC
    ---------
    AURORA 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 0
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    OPTIMISM 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 0
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    ARBITRUM 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    
    
    FANTOM 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 0
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    AVAX 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 1
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 1
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 1
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    BSC 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 0
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    POLYGON 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 164
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 164
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 26
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 26
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 138
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    ETHEREUM 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 449
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 449
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 72
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 72
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 377
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    CRONOS 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 0
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    ERA 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 15
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 15
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 2
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 2
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 13
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    LINEA 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 2
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 2
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 2
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    POLYGON_ZKEVM 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 0
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    BITTORRENT 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 0
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    SCROLL 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 3
    └─ Methodology: Users pay a dynamic fee based on market conditions
    Daily fees: 3
    └─ Methodology: Kyberswap Classic collects a dynamic fee that increases with market volatility and decreases with stable market conditions
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 2
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    Version -> ELASTIC
    ---------
    OPTIMISM 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 43.40 k
    └─ Methodology: Users pay trading fees based pool fee setting: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily fees: 43.40 k
    └─ Methodology: Each pool can have different fees set from the following tires: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily revenue: 6.94 k
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 6.94 k
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 36.46 k
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    ARBITRUM 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 2
    └─ Methodology: Users pay trading fees based pool fee setting: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily fees: 2
    └─ Methodology: Each pool can have different fees set from the following tires: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 1
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    FANTOM 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay trading fees based pool fee setting: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily fees: 0
    └─ Methodology: Each pool can have different fees set from the following tires: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    AVAX 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay trading fees based pool fee setting: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily fees: 0
    └─ Methodology: Each pool can have different fees set from the following tires: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    BSC 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay trading fees based pool fee setting: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily fees: 0
    └─ Methodology: Each pool can have different fees set from the following tires: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    POLYGON 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 1
    └─ Methodology: Users pay trading fees based pool fee setting: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily fees: 1
    └─ Methodology: Each pool can have different fees set from the following tires: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    ETHEREUM 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay trading fees based pool fee setting: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily fees: 0
    └─ Methodology: Each pool can have different fees set from the following tires: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    LINEA 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 4
    └─ Methodology: Users pay trading fees based pool fee setting: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily fees: 4
    └─ Methodology: Each pool can have different fees set from the following tires: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily revenue: 1
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 1
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 3
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    BITTORRENT 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay trading fees based pool fee setting: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily fees: 0
    └─ Methodology: Each pool can have different fees set from the following tires: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    BASE 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 0
    └─ Methodology: Users pay trading fees based pool fee setting: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily fees: 0
    └─ Methodology: Each pool can have different fees set from the following tires: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily revenue: 0
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 0
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range
    
    
    SCROLL 👇
    Backfill start time: 4/5/2024
    Timestamp: 1714780799 (2024-05-03T23:59:59.000Z)
    Daily user fees: 5
    └─ Methodology: Users pay trading fees based pool fee setting: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily fees: 5
    └─ Methodology: Each pool can have different fees set from the following tires: 0.008%, 0.01%, 0.04%, 0.3% and 1%
    Daily revenue: 1
    └─ Methodology: Currently 100% of the dao rewards (10% of the collected fees) goes to all voters (KNC stakers)
    Daily protocol revenue: 0
    └─ Methodology: Treasury have no revenue
    Daily holders revenue: 1
    └─ Methodology: Holders who stake and participate in the KyberDAO get their share of the fees designated for rewards, currently set at 10% of trading fees
    Daily supply side revenue: 4
    └─ Methodology: Liquidity providers earn 90% fees of trading routed through their pool and selected price range

**Comment by llamatester** [comment]
The predy-finance adapter exports: 
        
 
 _______________________________________
    Fees for 3/5/2024
    _______________________________________
    
    [Error: Error: Missing ABI parameter!] {
      _underlyingError: 'Error: Missing ABI parameter!',
      _isCustomError: true,
      chain: 'arbitrum'
    }

**Pull request closed without merging**
