### PR TITLE
XY Finance: list XY Finance on the aggregators page

### PR DESCRIPTION
**Pull request by coolryanc**
Hi DL team @g1nt0ki @dtmkeng, this is XY Finance, we'd like to list us on https://defillama.com/aggregators, here is the PR could you please help review. 🙏 

Quick question, other than submitting the PR here, do we also need to submit PR to https://github.com/DefiLlama/defillama-server? Please let us know, thanks. 🙇 

llama server PR: https://github.com/DefiLlama/defillama-server/pull/8150

### Evidence
```bash
yarn test aggregators xy-finance
```

volume

### CODE REVIEW

**Comment by dtmkeng** [comment]
could you revert change package.json and `package-lock.json` ?

**Comment by llamatester** [comment]
The xy-finance adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators xy-finance
    
    🦙 Running XY-FINANCE adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 19 Sep 2024 00:00:00 GMT
    End Date:	Fri, 20 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    error fetching block TypeError: Cannot read properties of null (reading 'getBlock')
        at _getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:84:59)
        at getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:76:22)
        at _lookupBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:204:44)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:155:26
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:31
        at run (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:43)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:45:20
        at runNextTicks (node:internal/process/task_queues:60:5)
        at listOnTimeout (node:internal/timers:538:9)
        at processTimers (node:internal/timers:512:7)
    error fetching block TypeError: Cannot read properties of null (reading 'getBlock')
        at _getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:84:59)
        at getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:76:22)
        at _lookupBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:204:44)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:155:26
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:31
        at run (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:43)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:45:20
        at runNextTicks (node:internal/process/task_queues:60:5)
        at listOnTimeout (node:internal/timers:538:9)
        at processTimers (node:internal/timers:512:7)
    error fetching block TypeError: Cannot read properties of null (reading 'getBlock')
        at _getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:84:59)
        at getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:76:22)
        at _lookupBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:204:44)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:155:26
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:31
        at run (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:43)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:45:20
        at runNextTicks (node:internal/process/task_queues:60:5)
        at listOnTimeout (node:internal/timers:538:9)
        at processTimers (node:internal/timers:512:7)
    XY Finance fetch chain zksync error: {}
    XY Finance fetch chain numbers error: {}
    ETHEREUM 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 36.09 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    SCROLL 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 232.57 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    MANTLE 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 49.66 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    LINEA 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 12.22 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    BASE 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 70.58 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 572.93 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    ZKSYNC 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 0
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    BSC 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 89.20 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    POLYGON 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 32.85 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    KLAYTN 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 0
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    POLYGON_ZKEVM 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 1.16 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    AVAX 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 8.22 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 123.35 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    CRONOS 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 38.33 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    FANTOM 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 0
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    ASTAR 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 0
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    KCC 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 0
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    MOONRIVER 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 0
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    THUNDERCORE 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 0
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    NUMBERS 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 0
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    WEMIX 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 0
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    BLAST 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 4.30 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    XLAYER 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 40
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    TAIKO 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 51.30 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)
    
    
    CRONOS_ZKEVM 👇
    Backfill start time: 10/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bridge volume: 1.06 k
    End timestamp: 1726790399 (2024-09-19T23:59:59.000Z)

**Comment by dtmkeng** [comment]
i think should move under `https://github.com/DefiLlama/dimension-adapters/tree/master/bridge-aggregator`   is it bridge-aggregator

**Review by Reallyfe — APPROVED** [review]

**Review by Reallyfe — APPROVED** [review]

**Review by Reallyfe — APPROVED** [review]

**Review by Reallyfe — APPROVED** [review]

**Review by Rezacb0413 — APPROVED** [review]

**Comment by dtmkeng** [comment]
i can merge but config for show bridge agg it not ready yet

**Pull request merged**
