### PR TITLE
feat: rabbitx starknet dex

### PR DESCRIPTION
**Pull request by kshilov**

### CODE REVIEW

**Comment by llamatester** [comment]
The rabbitx adapter exports: 
        
 
 _______________________________________
    Dexs for 14/11/2023
    _______________________________________
    
    STARKNET 👇
    Backfill start time: 1/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: undefined
    Timestamp: 1700006398
    
    
    
    
    Done in 4.07s.

**Comment by llamatester** [comment]
The rabbitx adapter exports: 
        
 
 _______________________________________
    Dexs for 14/11/2023
    _______________________________________
    
    STARKNET 👇
    Backfill start time: 1/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: undefined
    Timestamp: 1700006398
    
    
    
    
    Done in 4.29s.

**Comment by dtmkeng** [comment]
could you check  why daily volume is undefined if this does not have volume should set 0 instead undefined

**Comment by dtmkeng** [comment]
okay let me know if ready for merge

**Pull request closed without merging**
