### PR TITLE
palmswap sdk dapter - not finished

### PR DESCRIPTION
**Pull request by erocoder01**

### CODE REVIEW

**Comment by llamatester** [comment]
The ellipsis adapter exports: 
        
 
 _______________________________________
    Dexs for 20/7/2023
    _______________________________________
    
    Wrong value [object Object] with key dailyVolume
    BSC 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Total volume: 29756380456
    Timestamp: 1689958109
    
    
    
    
    Done in 3.50s.

**Comment by llamatester** [comment]
The synfutures adapter exports: 
        
 
 _______________________________________
    Dexs for 20/7/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 5/8/2021
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 0
    Timestamp: 1689811200
    
    
    ARBITRUM 👇
    Backfill start time: 6/8/2022
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 0
    Timestamp: 1689811200
    
    
    ETHEREUM 👇
    Backfill start time: 5/8/2021
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 0
    Timestamp: 1689811200
    
    
    BSC 👇
    Backfill start time: 5/8/2021
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 0
    Timestamp: 1689811200
    
    
    
    
    Done in 3.26s.

**Comment by llamatester** [comment]
The palmswap adapter exports: 
        
 
 _______________________________________
    Dexs for 20/7/2023
    _______________________________________
    
    
    
    Done in 2.92s.

**Comment by dtmkeng** [comment]
could you remove change on synfutures,ellipsis, yarn lock and package lock ?

**Comment by dtmkeng** [comment]
and can modify adapter like this https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/gmx/index.ts for split dexs volume and derivative volume

**Pull request closed without merging**
