### PR TITLE
fix(ggr): dailyFees=dailyRevenue and methodology updated

### PR DESCRIPTION
**Pull request by cowboybebop-r**

### CODE REVIEW

**Comment by llamatester** [comment]
The azuro adapter exports: 
        
 
 _______________________________________
    Fees for 16/5/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 14/7/2022
    Timestamp: 1684281598
    Daily fees: -1837.6659678729338
    └─ Methodology: Total pools profits (equals total bets amount minus total won bets amount)
    Daily revenue: -1837.6659678729338
    └─ Methodology: Total pools profits (equals total bets amount minus total won bets amount)
    
    
    XDAI 👇
    Backfill start time: 14/7/2022
    Timestamp: 1684281598
    Daily fees: 1465.5646192437125
    └─ Methodology: Total pools profits (equals total bets amount minus total won bets amount)
    Daily revenue: 1465.5646192437125
    └─ Methodology: Total pools profits (equals total bets amount minus total won bets amount)
    
    
    
    
    Done in 4.99s.

**Comment by dtmkeng** [comment]
hi , ty for PR, could you explain about your change metrology?

**Comment by dtmkeng** [comment]
hmm seem current meta
fees = all money that users spent taking bets (so regardless of whether they win or lose)
revenue = how much money pool makes, including wins and losses
is it incorrect ?

**Comment by cowboybebop-r** [comment]
@dtmkeng, yes, it is incorrect.
Here is the correct definition:
Fees: Total pools profits (equals total bets amount minus total won bets amount)
Revenue: Total pools profits (equals total bets amount minus total won bets amount)

**Pull request merged**
