### PR TITLE
add Paal-AI fees

### PR DESCRIPTION
**Pull request by jscrui**
This PR is to add paal-ai -> paalecosystemfund.eth fees to the platform

### CODE REVIEW

**Comment by llamatester** [comment]
The paal-ai adapter exports: 
        
 
 _______________________________________
    Fees for 28/10/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 6/10/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698537598
    Total fees: 32246970051238224140
    
    
    
    
    Done in 4.71s.

**Comment by dtmkeng** [comment]
if you use balance for track fees should  get `today balance` - `yesterday balance` 
and div by `1e18` and  mulipy by ethPrice 
and could you remove change on package lock and yarn lock ?

**Comment by llamatester** [comment]
The paal-ai adapter exports: 
        
 
 _______________________________________
    Fees for 29/10/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 6/10/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698623998
    Total fees: 38428451813507598276
    
    
    
    
    Done in 5.04s.

**Comment by llamatester** [comment]
The paal-ai adapter exports: 
        
 
 _______________________________________
    Fees for 29/10/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 6/10/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698623998
    Total fees: 38428451813507598276
    
    
    
    
    Done in 5.23s.

**Comment by llamatester** [comment]
The paal-ai adapter exports: 
        
 
 _______________________________________
    Fees for 29/10/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 6/10/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698623998
    Total fees: 5455062812084257000
    Total fees usd: 9801.275006356147
    
    
    
    
    Done in 5.79s.

**Comment by dtmkeng** [comment]
you delete file lock ?
i mean un commit lock on this pr

**Pull request closed without merging**
