### PR TITLE
Fix stakewise fees

### PR DESCRIPTION
**Pull request by tsudmi**

### CODE REVIEW

**Comment by llamatester** [comment]
The stakewise.ts adapter exports: 
        
 
 _______________________________________
    Fees for 21/12/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 4/1/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 12.72 k
    Daily revenue: 0.42778892516819367
    Daily supply side revenue: 5.258646637417865
    Timestamp: 1703203198
    
    
    
    
    Done in 8.33s.

**Comment by dtmkeng** [comment]
why rev is a bit ?, it is protocol rev ?

**Comment by llamatester** [comment]
The stakewise.ts adapter exports: 
        
 
 _______________________________________
    Fees for 21/12/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 4/1/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 12.72 k
    Daily revenue: 957.2632778488669
    Daily supply side revenue: 11.77 k
    Timestamp: 1703203198
    
    
    
    
    Done in 4.89s.

**Comment by tsudmi** [comment]
@dtmkeng fixed

**Pull request merged**
