### PR TITLE
add ithaca protocol

### PR DESCRIPTION
**Pull request by chaitanyasjoshi**

### CODE REVIEW

**Comment by llamatester** [comment]
The ithaca adapter exports: 
        
 
 _______________________________________
    Options for 16/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 15/4/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1713311999 (2024-04-16T23:59:59.000Z)
    Daily fees: 0
    Total fees: 5
    Daily premium volume: 0
    Total premium volume: 411
    Daily notional volume: 0
    Total notional volume: 211.73 k
    
    
    
    
    Done in 70.60s.

**Comment by dtmkeng** [comment]
@chaitanyasjoshi hi seem value 28th and 29th got spike could you check data 
is it correct? 
image

**Comment by chaitanyasjoshi** [comment]
> @chaitanyasjoshi hi seem value 28th and 29th got spike could you check data is it correct? image

checking with the team. will update you soon

**Comment by chaitanyasjoshi** [comment]
@dtmkeng sorry for the delay. Checked with the team, data is indeed correct

**Pull request merged**
