### PR TITLE
Add Koi Finance V3 

### PR DESCRIPTION
**Pull request by mattt21**

### CODE REVIEW

**Comment by llamatester** [comment]
The koi-finance adapter exports: 
        
 
 _______________________________________
    Fees for 24/5/2024
    _______________________________________
    
    ZKSYNC 👇
    Backfill start time: 23/2/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 10.60 k
    Daily revenue: 2.12 k
    Timestamp: 1716595199 (2024-05-24T23:59:59.000Z)

**Comment by llamatester** [comment]
The mute.io-v3 adapter exports: 
        
 
 _______________________________________
    Dexs for 25/5/2024
    _______________________________________
    
    ERA 👇
    Backfill start time: 23/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1716677484 (2024-05-25T22:51:24.000Z)
    Block: 34.92 M
    Total volume: 18.04 k
    Daily volume: 3.45 k

**Comment by dtmkeng** [comment]
will list v3 call Koi Finance CL

**Comment by dtmkeng** [comment]
https://github.com/DefiLlama/dimension-adapters/pull/1879

**Pull request closed without merging**
