### PR TITLE
Add volume for Econia on Aptos

### PR DESCRIPTION
**Pull request by CRBl69**
This PR adds volume information from Econia.

### CODE REVIEW

**Comment by llamatester** [comment]
The econia adapter exports: 
        
 
 _______________________________________
    Dexs for 6/2/2024
    _______________________________________
    
    APTOS 👇
    Backfill start time: 23/11/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 30.63 M
    Daily volume: 412.98 k
    Timestamp: 1707177600
    
    
    
    
    Done in 2.87s.

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Comment by CRBl69** [comment]
From the docs I see [here](https://docs.llama.fi/list-your-project/how-to-write-a-fetch-adapter), it seems that fetch adapters are not supported anymore and only SDK adapters are.

If I understand correctly, fetch adapters get data from an API, and SDK adapters get their data from chain directly.

Due to the structure of our contract, we cannot get TVL data from chain. But we can get it from the REST API (that we also use to get volume here). I can add a fetch adapter for it if that is still possible.

**Comment by dtmkeng** [comment]
@CRBl69  okay is there detail for list (website,x and details) ?

**Comment by alnoki** [comment]
> @CRBl69 okay is there detail for list (website,x and details) ?

@dtmkeng Is this what you are looking for?

1. econialabs.com
2. @econialabs
3. "Econia is a fully on-chain order book that offers both permissionless market making and atomic matching"

**Pull request merged**
