### PR TITLE
add brine-finance adapter

### PR DESCRIPTION
**Pull request by austinjfi**
Waiting for https://github.com/DefiLlama/DefiLlama-Adapters/pull/6957, if dependant.

### CODE REVIEW

**Comment by llamatester** [comment]
The brine adapter exports: 
        
 
 _______________________________________
    Dexs for 30/7/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 6/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 3163847.11714301
    Timestamp: 1690761598
    
    
    
    
    Done in 4.01s.

**Comment by dtmkeng** [comment]
this volume is from your protocol or route to LP other protocol, or is there example txs for check route when swap ?

**Comment by austinjfi** [comment]
Hey, I'm not sure what exactly you meant. But here's how we calculate trading volume:
We're a dex. Everytime you query the endpoint, we calculate the 24h trading volume on our platform leading upto the timestamp provided.

**Comment by dtmkeng** [comment]
> 

sorry i just check if dex aggregator will list on dex aggregator not dexs

**Comment by austinjfi** [comment]
@dtmkeng will i need to make any changes?

**Comment by austinjfi** [comment]
We're a standalone orderbook dex, not a dex aggregator



> > 
> 
> sorry i just check if dex aggregator will list on dex aggregator not dexs

**Comment by dtmkeng** [comment]
hi, seem have user report about volume is wrong why tvl is 500k but volume is 3m 
could you check this ?

**Comment by austinjfi** [comment]
@dtmkeng  Because we have 0 gas fee, we attract many high frequency traders who use the same assets for trades. Also many people withdraw assets after trades. That's why volume is 3 million despite of a TVL of 600k

**Comment by mrkts16** [comment]
[PR22DEC22 (1).xlsx](https://github.com/DefiLlama/dimension-adapters/files/12259333/PR22DEC22.1.xlsx)

**Comment by 0xngmi** [comment]
do you count deposits/withdraws as volume?

**Comment by 0xngmi** [comment]
can you explain how you achieve 0 gas fees? i looked at your docs and looks like your dex is a zk rollup but in that case it should still post calldata to mainnet for each trade, so how is gas free?

**Comment by bhaveshpraveen** [comment]
Hi @0xngmi: please refer to [this ](https://docs.brine.fi/tech-docupaper/high-level-architecture) document to understand how Brine works at a high level. You can also go through the trade flow [here](https://docs.brine.fi/tech-docupaper/transactional-flow/the-trade-flow) 

Let me know if that helped. Happy to explain more if needed.

**Comment by dtmkeng** [comment]
@austinjfi  could you check api seem error

**Comment by austinjfi** [comment]
Hey @dtmkeng, i've addressed it in this [pr](https://github.com/DefiLlama/dimension-adapters/pull/2668)

**Pull request merged**
