### PR TITLE
Add moby options volume data

### PR DESCRIPTION
**Pull request by mobydev01**

### CODE REVIEW

**Comment by llamatester** [comment]
The moby adapter exports: 
        
 
 _______________________________________
    Options for 4/4/2024
    _______________________________________
    
    
    
    Done in 1.34s.

**Comment by llamatester** [comment]
The moby adapter exports: 
        
 
 _______________________________________
    Options for 4/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 27/3/1976
    NO METHODOLOGY SPECIFIED
    Timestamp: 1712275199 (2024-04-04T23:59:59.000Z)
    Daily notional volume: 37.83 M
    Daily premium volume: 20.12 k
    Total notional volume: 44.19 M
    Total premium volume: 32.21 k
    
    
    
    
    Done in 12.39s.

**Comment by mobydev01** [comment]
Hi @dtmkeng could you merge it?

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Comment by moby-dev02** [comment]
@dtmkeng we don't track tvl

**Comment by dtmkeng** [comment]
i think i can't  options without tvl

**Comment by moby-dev02** [comment]
You mean we need to add TVL adapter first?

**Comment by moby-dev02** [comment]
@dtmkeng you mean do we need to add tvl adapter first? by forking defillama-adapters?

**Comment by dtmkeng** [comment]
yes some ppl will complaint example why ... protocol does not have tvl but volume if high ...

**Comment by moby-dev02** [comment]
@dtmkeng ok, after tracking tvl, I will let you know!

**Comment by mobydev01** [comment]
@dtmkeng PR for TVL https://github.com/DefiLlama/DefiLlama-Adapters/pull/9734

**Comment by dtmkeng** [comment]
good wait tvl megre
how do you calcaute notional volume and premium volume ?

**Comment by llamatester** [comment]
The moby adapter exports: 
        
 
 _______________________________________
    Options for 7/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 27/3/1976
    NO METHODOLOGY SPECIFIED
    Timestamp: 1712534399 (2024-04-07T23:59:59.000Z)
    Daily notional volume: 8.44 M
    Daily premium volume: 16.80 k
    Total notional volume: 82.68 M
    Total premium volume: 98.58 k
    
    
    
    
    Done in 9.82s.

**Comment by moby-dev02** [comment]
@dtmkeng 
TVL pr merged! https://github.com/DefiLlama/DefiLlama-Adapters/pull/9734

**Comment by moby-dev02** [comment]
> good wait tvl megre how do you calcaute notional volume and premium volume ?

@dtmkeng We are calculating notional volume through events below:

```
    event OpenBuyPosition(
        address indexed account,
        uint256 requestIndex,
        uint16 indexed underlyingAssetIndex,
        uint40 indexed expiry,
        uint256 optionTokenId,
        uint256 size,

        address quoteToken,
        uint256 amountPaid,
        uint256 executionPrice,
        uint256 spotPrice
    );

    event OpenSellPosition(
        address indexed account,
        uint256 requestIndex,
        uint16 indexed underlyingAssetIndex,
        uint40 indexed expiry,
        uint256 optionTokenId,
        uint256 size,

        address quoteToken,
        uint256 amountReceived,
        address collateralToken,
        uint256 collateralAmount,
        uint256 executionPrice,
        uint256 spotPrice
    );

    event CloseBuyPosition(
        address indexed account,
        uint256 requestIndex,
        uint16 indexed underlyingAssetIndex,
        uint40 indexed expiry,
        uint256 optionTokenId,
        uint256 size,

        address quoteToken,
        uint256 amountReceived,
        uint256 executionPrice,
        uint256 spotPrice
    );

    event CloseSellPosition(
        address indexed account,
        uint256 requestIndex,
        uint16 indexed underlyingAssetIndex,
        uint40 indexed expiry,
        uint256 optionTokenId,
        uint256 size,

        address quoteToken,
        uint256 amountPaid,
        address collateralToken,
        uint256 collateralAmount,
        uint256 executionPrice,
        uint256 spotPrice
    );
```

And this events are emitted through these contracts in arbitrum
```
"S_VAULT": "0xd4D23332E6256B751E2Da0B9C0b3a70CFe9180C0",
"M_VAULT": "0x9e34F79E39AddB64f4874203066fFDdD6Ab63a41",
"L_VAULT": "0x3B22F749f082bC33Af33751cBD53d21215FC71d1",
```


`notional volume = size / (10 ** underlying_asset_decimal) * spotPrice / 10 ** 30`
`premium volume = size / (10 ** underlying_asset_decimal) * executionPrice / 10 ** 30`

**Comment by moby-dev02** [comment]
@dtmkeng Thanks for merge!
When can we see our app in this page?
https://defillama.com/options

**Pull request merged**
