### PR TITLE
add bitget wallet volume

### PR DESCRIPTION
**Pull request by bitkeep-tech**
add-bitgetwall-volume

### CODE REVIEW

**Comment by llamatester** [comment]
The bitgetwallet adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators bitgetwallet
    
    🦙 Running BITGETWALLET adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 30 Oct 2024 00:00:00 GMT
    End Date:	Thu, 31 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 16.96 B
    Daily volume: 4.51 M
    End timestamp: 1730246400 (2024-10-30T00:00:00.000Z)
    
    
    POLYGON 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 500028.20 B
    Daily volume: 569.13 k
    End timestamp: 1730246400 (2024-10-30T00:00:00.000Z)
    
    
    SOLANA 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 0
    End timestamp: 1730246400 (2024-10-30T00:00:00.000Z)
    
    
    BSC 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 16380.91 B
    Daily volume: 943.47 k
    End timestamp: 1730246400 (2024-10-30T00:00:00.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 6.34 B
    Daily volume: 4.45 k
    End timestamp: 1730246400 (2024-10-30T00:00:00.000Z)
    
    
    BASE 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 0
    End timestamp: 1730246400 (2024-10-30T00:00:00.000Z)
    
    
    TON 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 0
    End timestamp: 1730246400 (2024-10-30T00:00:00.000Z)
    
    
    TRON 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 0
    End timestamp: 1730246400 (2024-10-30T00:00:00.000Z)
    
    
    BITCOIN 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 0
    End timestamp: 1730246400 (2024-10-30T00:00:00.000Z)

**Comment by g1nt0ki** [comment]
hi @bitkeep-tech thanks for the PR, can we compute this on chain using event logs? Also, the total volume looks bit high

**Comment by bitkeep-tech** [comment]
> hi @bitkeep-tech thanks for the PR, can we compute this on chain using event logs? Also, the total volume looks bit high

Yes, some of the data is incorrect. After a detailed search, the incorrect data is mainly concentrated before April 2024.
We will fix this part of the data. After the data is repaired, please approve it.

**Comment by bitkeep-tech** [comment]
@g1nt0ki hello. we have fixed data issue. The value of the token is not in the event logs. We can't add this in the short term.
please approve the mr.

**Comment by g1nt0ki** [comment]
@bitkeep-tech we can price the tokens ourselves, even the amount of tokens are not present in event log? Also, how does this work in the background, you have aggregator contract deployed in various chains and interact with it? can you share a transaction as example?

We prefer event logs as it removes dependency on your api, also more transparent/verifiable by our users.

**Comment by bitkeep-tech** [comment]
> @bitkeep-tech we can price the tokens ourselves, even the amount of tokens are not present in event log? Also, how does this work in the background, you have aggregator contract deployed in various chains and interact with it? can you share a transaction as example?
> 
> We prefer event logs as it removes dependency on your api, also more transparent/verifiable by our users.
@g1nt0ki 
We have routers for the following chains,
eth: 0xDe44500b5d1479DF5C003bf48915b3E24Df3e8dD
bsc: 0xDe44500b5d1479DF5C003bf48915b3E24Df3e8dD
polygon: 0xDe44500b5d1479DF5C003bf48915b3E24Df3e8dD
base:  0xDe44500b5d1479DF5C003bf48915b3E24Df3e8dD
We don’t have routers for some other chains, such as btc ton, cross swaps too . So we provide the api to return data.

example: https://etherscan.io/tx/0xd8aa85cf261b98c08694798f6d76e6de5d4b40968cfd927dcafc6a5b0b41778b

**Comment by g1nt0ki** [comment]
sorry for the late response, can you share the abi for the swap event
image

**Comment by bitkeep-tech** [comment]
@g1nt0ki 
we have two routers. 
There are abi files.
[BKSwapRouter.json](https://github.com/user-attachments/files/17713814/BKSwapRouter.json) 
0xD1ca1F4dBB645710f5D5a9917AA984a47524f49A
[BKSwap.json](https://github.com/user-attachments/files/17713816/BKSwap.json)  0xDe44500b5d1479DF5C003bf48915b3E24Df3e8dD

**Comment by bitkeep-tech** [comment]
@g1nt0ki Hi, Is there any progress on this?

**Comment by bitkeep-tech** [comment]
@g1nt0ki  I'm sorry to ask, how is the situation going?

**Comment by bitkeep-tech** [comment]
@g1nt0ki could you approve the pr first. When parse event log complete switch to new way?

**Comment by llamatester** [comment]
The bitgetwallet adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators bitgetwallet
    
    🦙 Running BITGETWALLET adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 20 Nov 2024 00:00:00 GMT
    End Date:	Thu, 21 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 1.63 B
    Daily volume: 3.56 M
    End timestamp: 1732060800 (2024-11-20T00:00:00.000Z)
    
    
    POLYGON 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 873.40 M
    Daily volume: 955.05 k
    End timestamp: 1732060800 (2024-11-20T00:00:00.000Z)
    
    
    SOLANA 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 0
    End timestamp: 1732060800 (2024-11-20T00:00:00.000Z)
    
    
    BSC 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 2.05 B
    Daily volume: 1.77 M
    End timestamp: 1732060800 (2024-11-20T00:00:00.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 68.99 M
    Daily volume: 167.61 k
    End timestamp: 1732060800 (2024-11-20T00:00:00.000Z)
    
    
    BASE 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 0
    End timestamp: 1732060800 (2024-11-20T00:00:00.000Z)
    
    
    TON 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 0
    End timestamp: 1732060800 (2024-11-20T00:00:00.000Z)
    
    
    TRON 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 0
    End timestamp: 1732060800 (2024-11-20T00:00:00.000Z)
    
    
    BITCOIN 👇
    Backfill start time: 31/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 0
    End timestamp: 1732060800 (2024-11-20T00:00:00.000Z)

**Comment by g1nt0ki** [comment]
@bitkeep-tech sorry for the delay

**Comment by bitkeep-tech** [comment]
> @bitkeep-tech sorry for the delay

no problem.

**Pull request merged**
