### PR TITLE
Fluid: fix magnifier fees revenues

### PR DESCRIPTION
**Pull request by bergben**
Fixes an issue for fetching fees & revenues when some fees from magnifier use are active. We need to backfill starting from Nov22 please, which is when we executed IGP53 https://beta.atlas.instadapp.io/proposals/53

Before (ETH fees wrong): 
image

After:  
image

### CODE REVIEW

**Comment by llamatester** [comment]
The fluid adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees fluid
    
    🦙 Running FLUID adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 01 Dec 2024 14:00:21 GMT
    End Date:	Mon, 02 Dec 2024 14:00:21 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 18/2/2024
    Daily fees: 79.24 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 18.91 k
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1733148020 (2024-12-02T14:00:20.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 3/7/2024
    Daily fees: 3.33 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 334
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1733148020 (2024-12-02T14:00:20.000Z)
    
    
    BASE 👇
    Backfill start time: 12/8/2024
    Daily fees: 3.58 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 358
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1733148020 (2024-12-02T14:00:20.000Z)

**Comment by bergben** [comment]
Also, fetching logs on Base fails when running `yarn test fees fluid 1733011200`. Any ideas what could be causing this?

image

I added setting fees to 0 in that case, before it ended up giving very wrong values: 
image

**Comment by 0xpeluche** [comment]
#2183  Hello @bergben , sorry it took me a bit of time. The changes are relevant, but I took the liberty of significantly refactoring the code, as it was becoming quite monstrous with over 700 lines. You can check the changes in this PR and cross-check if you'd like

**Comment by bergben** [comment]
Closing in favor of #2183 . Ty for the refactoring

**Pull request closed without merging**
