### PR TITLE
update to V-2

### PR DESCRIPTION
**Pull request by TerrenceAddison**
Update to use V2 adapter

### CODE REVIEW

**Comment by TerrenceAddison** [comment]
@dtmkeng please review and update any fixes if any, lmk if you need any assistance from me, thanks!

**Comment by dtmkeng** [comment]
could you fix conflicts ?

**Comment by TerrenceAddison** [comment]
> could you fix conflicts ?

I think you were the one who updated the code so I'm not too sure how to resolve it 🙏

**Comment by g1nt0ki** [comment]
@TerrenceAddison I have fixed it

**Comment by TerrenceAddison** [comment]
@g1nt0ki thanks and much appreciated!

**Pull request closed without merging**
