### PR TITLE
Add idliemine revenue

### PR DESCRIPTION
**Pull request by abhinavabhi1218**
I am adding my project to DefiLlama in fees and revenues

### CODE REVIEW

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by abhinavabhi1218** [comment]
> The idlemine adapter exports:
> 
> ```
> ERROR: Use Adapter v2 format for new adapters
> ```

🦙 Running IDLEMINE adapter 🦙
_______________________________________
Fees for 14/5/2024
_______________________________________

BSC 👇
Backfill start time: 1/3/2024
Methodology: idlemine revenue from idlemine thumb game and idlemine battle games
Timestamp: 1715731199 (2024-05-14T23:59:59.000Z)
Daily revenue: 3.26 M

im getting this from my repository
make sure add "git ls-tree --name-only -r master" for idlemine adaptor

**Comment by dtmkeng** [comment]
could you remove change at `package` and lock 
cold you explain how you cal revenue  ?

**Comment by abhinavabhi1218** [comment]
> could you remove change at `package` and lock cold you explain how you cal revenue ?

By calling my API which response all the data regarding game revenue , deposits and more.

**Comment by dtmkeng** [comment]
> > could you remove change at `package` and lock cold you explain how you cal revenue ?
> 
> By calling my API which response all the data regarding game revenue , deposits and more.

al;l deposits go to team ?, revenue is protocol revenue

**Comment by abhinavabhi1218** [comment]
> > > could you remove change at `package` and lock cold you explain how you cal revenue ?
> > 
> > 
> > By calling my API which response all the data regarding game revenue , deposits and more.
> 
> al;l deposits go to team ?, revenue is protocol revenue

I didn't understand can you explain it briefly

**Comment by dtmkeng** [comment]
revenue should from fees or reward protocol earn which rev your count from is there example txs

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by abhinavabhi1218** [comment]
> The idlemine adapter exports:
> 
> ```
> ERROR: Use Adapter v2 format for new adapters
> ```

🦙 Running IDLEMINE adapter 🦙
_______________________________________
Fees for 19/5/2024
_______________________________________

BSC 👇
Backfill start time: 1/3/2024
Methodology: idlemine revenue from idlemine thumb game and idlemine battle games
Timestamp: 1716163199 (2024-05-19T23:59:59.000Z)
 total revenue: 3.06 M
 total fee: 383.94 k

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by AbhinavString** [comment]
> The idlemine adapter exports:
> 
> ```
> ERROR: Use Adapter v2 format for new adapters
> ```


merge branch  DfiLlama:master  itno master

**Comment by AbhinavString** [comment]
image

**Comment by dtmkeng** [comment]
add `version: 2`  add above `adapter`
and field about fees 
```
totalFees
dailyFees
dailyUserFees
totalRevenue
dailyRevenue
dailyProtocolRevenue
dailyHoldersRevenue
dailySupplySideRevenue
totalProtocolRevenue
totalSupplySideRevenue
totalUserFees
dailyBribesRevenue
dailyTokenTaxes
```

**Comment by dtmkeng** [comment]
and plz revert change `package-lock` and `package`

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    Fees for 21/5/2024
    _______________________________________
    
    TypeError: Cannot read properties of undefined (reading 'createBalances')
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/idlemine/index.ts:38:32)
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:25)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'bsc'
    }

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    Fees for 21/5/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://api.idlemine.io/api/admin/user/revenue',
      method: 'GET',
      axiosError: 'Forbidden',
      chain: 'bsc'
    }

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    Fees for 21/5/2024
    _______________________________________

**Comment by dtmkeng** [comment]
still got error api 403 could you check ?

**Comment by AbhinavString** [comment]
> still got error api 403 could you check ?

we are restricted my APIs for some unwanted not stop requests  from some IP's

will you provide your network address we will whitelist it

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    Fees for 22/5/2024
    _______________________________________
    
    BSC 👇
    Backfill start time: 1/3/2024
    Methodology: Calculates revenue from specific blockchain games using transaction data.
    Timestamp: 1716373381 (2024-05-22T10:23:01.000Z)
    Total revenue: 1.87 M

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    Fees for 22/5/2024
    _______________________________________
    
    BSC 👇
    Backfill start time: 1/3/2024
    Methodology: Calculates revenue from specific blockchain games using transaction data.
    Timestamp: 1716375132 (2024-05-22T10:52:12.000Z)
    Total revenue: 11.61 M

**Comment by abhinavabhi1218** [comment]
> The idlemine adapter exports:
> 
> ```
> Fees for 22/5/2024
> _______________________________________
> 
> BSC 👇
> Backfill start time: 1/3/2024
> Methodology: Calculates revenue from specific blockchain games using transaction data.
> Timestamp: 1716375132 (2024-05-22T10:52:12.000Z)
> Total revenue: 11.61 M
> ```

why it is in still Open ??

**Comment by dtmkeng** [comment]
> add `version: 2` add above `adapter` and field about fees
> 
> ```
> totalFees
> dailyFees
> dailyUserFees
> totalRevenue
> dailyRevenue
> dailyProtocolRevenue
> dailyHoldersRevenue
> dailySupplySideRevenue
> totalProtocolRevenue
> totalSupplySideRevenue
> totalUserFees
> dailyBribesRevenue
> dailyTokenTaxes
> ```

@abhinavabhi1218

**Comment by dtmkeng** [comment]
> and plz revert change `package-lock` and `package`

@abhinavabhi1218

**Comment by dtmkeng** [comment]
> revenue should from fees or reward like lido cut reward % for their rev which rev your count from is there example txs

@abhinavabhi1218

**Comment by dtmkeng** [comment]
> > add `version: 2` add above `adapter` and field about fees
> > ```
> > totalFees
> > dailyFees
> > dailyUserFees
> > totalRevenue
> > dailyRevenue
> > dailyProtocolRevenue
> > dailyHoldersRevenue
> > dailySupplySideRevenue
> > totalProtocolRevenue
> > totalSupplySideRevenue
> > totalUserFees
> > dailyBribesRevenue
> > dailyTokenTaxes
> > ```
> 
> @abhinavabhi1218

it require daily field

**Comment by dtmkeng** [comment]
> > > add `version: 2` add above `adapter` and field about fees
> > > ```
> > > totalFees
> > > dailyFees
> > > dailyUserFees
> > > totalRevenue
> > > dailyRevenue
> > > dailyProtocolRevenue
> > > dailyHoldersRevenue
> > > dailySupplySideRevenue
> > > totalProtocolRevenue
> > > totalSupplySideRevenue
> > > totalUserFees
> > > dailyBribesRevenue
> > > dailyTokenTaxes
> > > ```
> > 
> > 
> > @abhinavabhi1218
> 
> it require daily field and add version 2

**Comment by dtmkeng** [comment]
> > revenue should from fees or reward like lido cut reward % for their rev which rev your count from is there example txs
> 
> @abhinavabhi1218

is there example txs for calculate  rev ?

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    Fees for 23/5/2024
    _______________________________________
    
    Failed to fetch daily stats: [Error: Request failed with status code 403] {
      url: 'https://api.idlemine.io/api/admin/user/revenue',
      method: 'GET',
      axiosError: 'Forbidden'
    }
    Error: Error fetching daily stats
        at fetchDailyStats (/home/runner/work/dimension-adapters/dimension-adapters/fees/idlemine/index.ts:31:11)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:18)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'bsc'
    }

**Comment by abhinavabhi1218** [comment]
recheck it

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    Fees for 23/5/2024
    _______________________________________
    
    Failed to fetch daily stats: [Error: Request failed with status code 403] {
      url: 'https://api.idlemine.io/api/admin/user/revenue',
      method: 'GET',
      axiosError: 'Forbidden'
    }
    Error: Error fetching daily stats
        at fetchDailyStats (/home/runner/work/dimension-adapters/dimension-adapters/fees/idlemine/index.ts:31:11)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:18)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'bsc'
    }

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    Fees for 24/5/2024
    _______________________________________
    
    {
      Totalrevenue: 3166715.8509379732,
      Fee: 405933.1539999976,
      dailyfees: 4646,
      dailyrevenue: 18000.255
    } 
    BSC 👇
    Backfill start time: 1/3/2024
    Methodology: Calculates revenues and fees from IdleMine thumb game and IdleMine battle games.
    Timestamp: 1716541428 (2024-05-24T09:03:48.000Z)
    Daily revenue: 18.00 k
    Daily fees: 4.65 k
    Total revenue: 3.17 M
    Total fees: 405.93 k

**Comment by llamatester** [comment]
The idlemine adapter exports: 
        
 
 _______________________________________
    Fees for 24/5/2024
    _______________________________________
    
    BSC 👇
    Backfill start time: 1/3/2024
    Methodology: Calculates revenues and fees from IdleMine thumb game and IdleMine battle games.
    Timestamp: 1716541489 (2024-05-24T09:04:49.000Z)
    Daily revenue: 18.00 k
    Daily fees: 4.65 k
    Total revenue: 3.17 M
    Total fees: 405.93 k

**Comment by dtmkeng** [comment]
i think should count only withdrawal charge 
seem you  count  user deposit  right ?

**Comment by abhinavabhi1218** [comment]
> i think should count only withdrawal charge seem you count user deposit right ?


No, we only count deposits as revenue. When a user withdraws their amount, we charge a fee of 5-10% based on their withdrawals. If a user earned from free games, we charge 10%; otherwise, it’s 5%. So, the revenue is primarily from the withdrawal charges rather than the initial deposits.

**Comment by dtmkeng** [comment]
why rev more than fees ?

**Comment by abhinavabhi1218** [comment]
> why rev more than fees ?

coz  game investment(deposits) is higher than withdrawal fee then revenue is high

**Comment by dtmkeng** [comment]
all deposit it go to team and token holder ?

**Comment by abhinavabhi1218** [comment]
> all deposit it go to team and token holder ?

No, it's a gaming platform, so deposits go to an organization.

**Comment by abhinavabhi1218** [comment]
> > > all deposit it go to team and token holder ?
> > 
> > 
> > No, it's a gaming platform, so deposits go to an organization.
> 
> hmm can't count to rev rev mean money go to team or token holder

can you explain team and token holders ?
we are using All BEP20 tokens to play idlemine games , we we are not using my OWN tokens to play idlemine games
so there is no token holders im idlemine rev means investment /deposits  these count go to idlemine team

**Comment by dtmkeng** [comment]
> > > > all deposit it go to team and token holder ?
> > > 
> > > 
> > > No, it's a gaming platform, so deposits go to an organization.
> > 
> > 
> > hmm can't count to rev rev mean money go to team or token holder
> 
> can you explain team and token holders ? we are using All BEP20 tokens to play idlemine games , we we are not using my OWN tokens to play idlemine games so there is no token holders im idlemine rev means investment /deposits these count go to idlemine team

like gov token or vTOKEN like velodreom holder have profit from fees when stake or burn 
no i can' t count rev from deposits sorry

**Comment by abhinavabhi1218** [comment]
> > > > > all deposit it go to team and token holder ?
> > > > 
> > > > 
> > > > No, it's a gaming platform, so deposits go to an organization.
> > > 
> > > 
> > > hmm can't count to rev rev mean money go to team or token holder
> > 
> > 
> > can you explain team and token holders ? we are using All BEP20 tokens to play idlemine games , we we are not using my OWN tokens to play idlemine games so there is no token holders im idlemine rev means investment /deposits these count go to idlemine team
> 
> like gov token or vTOKEN like velodreom holder have profit from fees when stake or burn no i can' t count rev from deposits sorry

How does [YoloGames ](https://yologames.io/)count its revenue and fees? It doesn't have its own token or holders. Users deposit funds or invest in games to play. [IdleMine ](https://idlemine.io/)operates similarly to YoloGames, yet you accept YoloGames but not IdleMine. Why is that?

**Comment by g1nt0ki** [comment]
closing this PR as stale

**Pull request closed without merging**
