### PR TITLE
Create D5 Exchange

### PR DESCRIPTION
**Pull request by qwertyuioppkgkf**
D5 is the first aggregator combining the power of Order Books and AMMs, providing a revolutionary on-chain trading experience.

### CODE REVIEW

**Comment by dtmkeng** [comment]
hi seem your pr does not have code for get your data, could you check ?

**Comment by qwertyuioppkgkf** [comment]
const sdk = require('@defillama/sdk');
const MINT_TOKEN_CONTRACT = 0x2F27118E3D2332aFb7d165140Cf1bB127eA6975d
const GDX__CONTRACT = '0x2F27118E3D2332aFb7d165140Cf1bB127eA6975d';

async function tvl(_, _1, _2, { api }) {
  const balances = {};

  const collateralBalance = await [api.call](http://api.call/)({
    abi: 'erc20:balanceOf',
    target: GDX_TOKEN_CONTRACT,
    params: GDXT__CONTRACT],
  });

  await sdk.util.sumSingleBalance(balances, MINT_TOKEN_CONTRACT, collateralBalance, api.chain)

  return balances;
}

module.exports = {
  timetravel: true,
  misrepresentedTokens: false,
  methodology: 'counts the number of MINT tokens in the Club Bonding contract.',
  start: 1000235,
  bsc: {
    tvl,
  }
};

**Comment by qwertyuioppkgkf** [comment]
> hi seem your pr does not have code for get your data, could you check ?

So i want to list d5 exchange or the token on it now( GDX)

**Comment by dtmkeng** [comment]
@qwertyuioppkgkf  you can drop detail on defillama discord about tvl of d5 https://discord.defillama.com/

**Pull request closed without merging**
