### PR TITLE
added fees and volume for kyotoswap

### PR DESCRIPTION
**Pull request by miguelangelrm**
Added fees and volume for KyotoSwap. Uniswap V2 Fork

### CODE REVIEW

**Comment by llamatester** [comment]
The kyotoswap.ts adapter exports: 
        
 
 _______________________________________
    Fees for 28/3/2023
    _______________________________________
    
    Version -> V2
    ---------
    BSC 👇
    Backfill start time: 4/12/2022
    Timestamp: 1680047999
    Block: 26870334
    Total volume: 3761937.6138592656
    Daily volume: 29911.72973028194254853270321271476
    Daily fees: 74.7793243257048563713317580317869
    └─ Methodology: All fees comes from the user.
    Total fees: 9404.844034648164
    └─ Methodology: All fees comes from the user.
    Daily protocol revenue: 23.929383784225554038826162570171808
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 3009.55009108741248
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily user fees: 74.7793243257048563713317580317869
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 9404.844034648164
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 50.849940541479305323678568489809346853270321271476
    └─ Methodology: LPs receive 0.17% of the fees.
    Total supply side revenue: 6395.29394356075189619376138592656
    └─ Methodology: LPs receive 0.17% of the fees.
    Daily revenue: 6.730139189313437073419858222860821
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 846.43596311833476
    └─ Methodology: All revenue generated comes from user fees.
    
    
    Done in 4.79s.

**Comment by dtmkeng** [comment]
hmmm, why dexs does not have breakdown (v2) like fees ?

**Comment by miguelangelrm** [comment]
> hmmm, why dexs does not have breakdown (v2) like fees ?

It's because I based them off of different projects, if it's an issue I could alter them.

**Comment by dtmkeng** [comment]
ok thank you

**Pull request merged**
