### PR TITLE
Add Lyra Chain and Lyra perps

### PR DESCRIPTION
**Pull request by paulvaden**

### CODE REVIEW

**Comment by llamatester** [comment]
The lyra-v2 adapter exports: 
        
 
 _______________________________________
    Options for 16/4/2024
    _______________________________________
    
    LYRA 👇
    Backfill start time: 15/12/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1713311999 (2024-04-16T23:59:59.000Z)
    Daily notional volume: 12.11 M
    Daily premium volume: 531.24 k
    Total notional volume: 872.79 M
    Total premium volume: 16.21 M
    
    
    
    
    Done in 8.69s.

**Comment by llamatester** [comment]
The lyra adapter exports: 
        
 
 _______________________________________
    Dexs for 16/4/2024
    _______________________________________
    
    LYRA 👇
    Backfill start time: 15/12/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1713311999 (2024-04-16T23:59:59.000Z)
    Daily volume: 10.05 M
    Total volume: 516.67 M
    
    
    
    
    Done in 10.35s.

**Comment by dtmkeng** [comment]
how to old value at eth ?

**Comment by dtmkeng** [comment]
i mean prev options data is on eth, how it still on eth ?

**Comment by paulvaden** [comment]
Sorry not sure I fully understand the question. 

Lyra V1 was on Optimism/Arbitrum.  Lyra V2 options was listed a few months ago, but was incorrectly listed as being on Ethereum (Its on Lyra Chain).  If possible it would be great if we could instead show that volume under Lyra Chain.

Is that something I would need to update in my PR?

thanks!

**Comment by Define101** [comment]
Good to merge. We added lyra chain on the server

**Pull request merged**
