### PR TITLE
trying to fix the volume data issue 

### PR DESCRIPTION
**Pull request by ayabelarbi**

### CODE REVIEW

**Comment by ayabelarbi** [comment]
as i don't have write access, i cannot fix the conflicts

**Comment by dtmkeng** [comment]
i fixed support historical data already

**Comment by ayabelarbi** [comment]
yes but, it's a different code. i've remove 24h to the time in order to make my volume api code works

**Comment by dtmkeng** [comment]
we collect data every hour for current data when your data your update, i think some your data is misstake when we collect data

**Comment by dtmkeng** [comment]
i refilled your data will okay next 2-3 hour

**Pull request closed without merging**
