### PR TITLE
fix in calculation

### PR DESCRIPTION
**Pull request by bufferfinance**

### CODE REVIEW

**Comment by llamatester** [comment]
The buffer adapter exports: 
        
 
 _______________________________________
    Fees for 22/2/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 29/1/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1677110398
    Daily fees: 8807.019625
    Daily revenue: 8807.019625
    
    
    
    
    Done in 5.44s.

**Comment by bufferfinance** [comment]
Let me know if this is proper. This number will be displayed in itself in the code right?

**Comment by dtmkeng** [comment]
Why do not do supplySide and HolderRev calculations?

**Comment by bufferfinance** [comment]
Because that is confusing the users. Plus what is reflected on the platform is different from my local output.
I have explained the issue here https://github.com/DefiLlama/dimension-adapters/pull/247#issuecomment-1441567714

**Pull request merged**
