### PR TITLE
add kyex

### PR DESCRIPTION
**Pull request by rellyxx**

### CODE REVIEW

**Comment by llamatester** [comment]
The kyex adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs kyex
    
    🦙 Running KYEX adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 28 Oct 2024 00:00:00 GMT
    End Date:	Tue, 29 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    1729988072 10915184801204574258726
    1729993982 10919185801204574258726
    1729998471 10922015779889299418976
    1730001335 10923285779889299418976
    1730001341 10924356679889299418976
    1730001448 10925845679889299418976
    1730001448 10925845679889299418976
    1730002036 10926177679889299418976
    1730004740 10927152679889299418976
    1730006283 10927768679889299418976
    1730006746 10929434679889299418976
    1730006746 10929434679889299418976
    1730006746 10929434679889299418976
    1730006752 10929846979889299418976
    1730006794 10930354279889299418976
    1730006794 10930354279889299418976
    1730006800 10930666379889299418976
    1730010325 10931286379889299418976
    1730010331 10931846979889299418976
    1730010331 10931846979889299418976
    1730010337 10932773379889299418976
    1730010385 10933532379889299418976
    1730010385 10933532379889299418976
    1730012199 10933755379889299418976
    1730019894 10952045136310234724052
    1730020138 10954045136310234724052
    1730027528 11022004613337806909711
    1730028656 11090004613337806909711
    1730028829 11157626803368226401643
    1730042890 11161527238668148972100
    1730046100 11168534220601267700769
    1730046118 11169034220601267700769
    ZETA 👇
    Backfill start time: 9/9/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 254
    Total volume: 11.28 k
    End timestamp: 1730159999 (2024-10-28T23:59:59.000Z)

**Comment by llamatester** [comment]
The kyex adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs kyex
    
    🦙 Running KYEX adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 29 Oct 2024 11:09:52 GMT
    End Date:	Wed, 30 Oct 2024 11:09:52 GMT
    ---------------------------------------------------
    
    ZETA 👇
    Backfill start time: 9/9/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 77
    End timestamp: 1730286591 (2024-10-30T11:09:51.000Z)

**Comment by dtmkeng** [comment]
@rellyxx  hi do you have details for list ? 
website x, or some descriptions

**Comment by rellyxx** [comment]
> @rellyxx hi do you have details for list ? website x, or some descriptions

[pull_request_template.md](https://github.com/user-attachments/files/17581319/pull_request_template.md)

**Pull request merged**
