### PR TITLE
[Dont merge] abcdefx - add fantom

### PR DESCRIPTION
**Pull request by ftm1337**

### CODE REVIEW

**Comment by llamatester** [comment]
The abcdefx.ts adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    fees/abcdefx.ts(172,27): error TS6133: 'CHAIN' is declared but its value is never read.
    fees/abcdefx.ts(172,32): error TS2418: Type of computed property's value is '{ fetch(CHAIN: number): never; "": any; start: () => Promise<number>; }', which is not assignable to type '{ start: IStartTimestamp; fetch: Fetch; runAtCurrTime?: boolean | undefined; customBackfill?: Fetch | undefined; meta?: { methodology?: string | IJSON<string> | undefined; hallmarks?: [...][] | undefined; } | undefined; }'.
      Object literal may only specify known properties, and '(Missing)' does not exist in type '{ start: IStartTimestamp; fetch: Fetch; runAtCurrTime?: boolean | undefined; customBackfill?: Fetch | undefined; meta?: { methodology?: string | IJSON<string> | undefined; hallmarks?: [...][] | undefined; } | undefined; }'.
    fees/abcdefx.ts(173,29): error TS6133: 'CHAIN' is declared but its value is never read.
    fees/abcdefx.ts(173,34): error TS2418: Type of computed property's value is '{ fetch(CHAIN: number): never; "": any; start: () => Promise<number>; }', which is not assignable to type '{ start: IStartTimestamp; fetch: Fetch; runAtCurrTime?: boolean | undefined; customBackfill?: Fetch | undefined; meta?: { methodology?: string | IJSON<string> | undefined; hallmarks?: [...][] | undefined; } | undefined; }'.
      Object literal may only specify known properties, and '(Missing)' does not exist in type '{ start: IStartTimestamp; fetch: Fetch; runAtCurrTime?: boolean | undefined; customBackfill?: Fetch | undefined; meta?: { methodology?: string | IJSON<string> | undefined; hallmarks?: [...][] | undefined; } | undefined; }'.
    fees/abcdefx.ts(172,32): error TS1005: ',' expected.
    fees/abcdefx.ts(172,37): error TS1005: ',' expected.
    fees/abcdefx.ts(172,38): error TS1136: Property assignment expected.
    fees/abcdefx.ts(173,34): error TS1005: ',' expected.
    fees/abcdefx.ts(173,41): error TS1005: ',' expected.
    fees/abcdefx.ts(173,42): error TS1136: Property assignment expected.
    
    Done in 3.19s.

**Comment by llamatester** [comment]
The abcdefx.ts adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    fees/abcdefx.ts(173,14): error TS2304: Cannot find name 'graph'.
    fees/abcdefx.ts(177,14): error TS2304: Cannot find name 'graph'.
    
    Done in 2.96s.

**Comment by llamatester** [comment]
The abcdefx.ts adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    fees/abcdefx.ts(173,14): error TS2304: Cannot find name 'graph'.
    fees/abcdefx.ts(177,14): error TS2304: Cannot find name 'graph'.
    
    Done in 3.07s.

**Comment by llamatester** [comment]
The abcdefx.ts adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    fees/abcdefx.ts(173,7): error TS2322: Type 'Promise<FetchResultFees>' is not assignable to type 'Fetch'.
      Type 'Promise<FetchResultFees>' provides no match for the signature '(timestamp: number, chainBlocks: { [chain: string]: number; }): Promise<FetchResult>'.
    fees/abcdefx.ts(173,14): error TS2554: Expected 2 arguments, but got 1.
    fees/abcdefx.ts(177,7): error TS2322: Type 'Promise<FetchResultFees>' is not assignable to type 'Fetch'.
    fees/abcdefx.ts(177,14): error TS2554: Expected 2 arguments, but got 1.
    
    Done in 2.98s.

**Comment by llamatester** [comment]
The abcdefx.ts adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    fees/abcdefx.ts(173,7): error TS2322: Type 'Promise<FetchResultFees>' is not assignable to type 'Fetch'.
      Type 'Promise<FetchResultFees>' provides no match for the signature '(timestamp: number, chainBlocks: { [chain: string]: number; }): Promise<FetchResult>'.
    fees/abcdefx.ts(173,14): error TS2554: Expected 2 arguments, but got 1.
    fees/abcdefx.ts(177,7): error TS2322: Type 'Promise<FetchResultFees>' is not assignable to type 'Fetch'.
    fees/abcdefx.ts(177,14): error TS2554: Expected 2 arguments, but got 1.
    
    Done in 3.11s.

**Comment by ftm1337** [comment]
Covered by https://github.com/DefiLlama/dimension-adapters/pull/582

**Pull request closed without merging**
