### PR TITLE
Add IPOR Protocol to dimension-adapters

### PR DESCRIPTION
**Pull request by amydlarz**

### CODE REVIEW

**Comment by llamatester** [comment]
The ipor adapter exports: 
        
 
 _______________________________________
    Dexs for 5/2/2024
    _______________________________________
    
    Version -> DERIVATIVES
    ---------
    ETHEREUM 👇
    Backfill start time: 16/8/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1707177599
    Daily volume: 250.00 k
    Total volume: 4.29 B
    
    
    Done in 139.66s.

**Comment by g1nt0ki** [comment]
hi @amydlarz I am changing the code style a bit, so I have the adapter here, can you have a look? https://github.com/DefiLlama/dimension-adapters/pull/1181/commits/b802b5d273b94b9658e8167f344393ea846ce721

**Comment by llamatester** [comment]
The ipor adapter exports: 
        
 
 _______________________________________
    Dexs for 6/2/2024
    _______________________________________
    
    Version -> DERIVATIVES
    ---------
    ETHEREUM 👇
    Backfill start time: 16/8/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1707263999
    Daily volume: 400.00 k
    Total volume: 4.29 B
    
    
    Done in 280.46s.

**Comment by dtmkeng** [comment]
@amydlarz is it only `DERIVATIVES` not include `options` volume  right ?

**Comment by amydlarz** [comment]
> @amydlarz is it only `DERIVATIVES` not include `options` volume right ?

@dtmkeng yes it is only `DERIVATIVES`

**Comment by amydlarz** [comment]
One more question. When I extend to the second arbitrum chain and run
`yarn test dexs ipor`
then I see only Ethereum without arbitrum. How can I test Arbitrum?

**Comment by dtmkeng** [comment]
> One more question. When I extend to the second arbitrum chain and run `yarn test dexs ipor` then I see only Ethereum without arbitrum. How can I test Arbitrum?

if start time equal yesterday it not return anything

**Comment by g1nt0ki** [comment]
> > hi @amydlarz I am changing the code style a bit, so I have the adapter here, can you have a look? [b802b5d](https://github.com/DefiLlama/dimension-adapters/commit/b802b5d273b94b9658e8167f344393ea846ce721)
> 
> @g1nt0ki Should I apply your changes here?

no, wait a bit, I will merge my branch in the next 24 hours, then you can fork it and add arbitrum data?

**Pull request closed without merging**
