### PR TITLE
Add vanilla swap v3 and v2

### PR DESCRIPTION
**Pull request by rogi-sh**

### CODE REVIEW

**Comment by llamatester** [comment]
The vanillaswap-v2.ts adapter exports: 
        
 
 _______________________________________
    Protocols for 6/6/2024
    _______________________________________
    
    DEFICHAIN_EVM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Daily fees: 0
    Timestamp: 1717698767 (2024-06-06T18:32:47.000Z)

**Comment by llamatester** [comment]
The vanillaswap-v3.ts adapter exports: 
        
 
 _______________________________________
    Protocols for 6/6/2024
    _______________________________________
    
    DEFICHAIN_EVM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Daily fees: 0
    Timestamp: 1717698775 (2024-06-06T18:32:55.000Z)

**Comment by llamatester** [comment]
The vanillaswap-v2.ts adapter exports: 
        
 
 _______________________________________
    Protocols for 10/6/2024
    _______________________________________
    
    DEFICHAIN_EVM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Daily fees: 0
    Timestamp: 1717999506 (2024-06-10T06:05:06.000Z)

**Comment by llamatester** [comment]
The vanillaswap-v3.ts adapter exports: 
        
 
 _______________________________________
    Protocols for 10/6/2024
    _______________________________________
    
    DEFICHAIN_EVM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Daily fees: 0
    Timestamp: 1717999515 (2024-06-10T06:05:15.000Z)

**Comment by rogi-sh** [comment]
Yeah the biggest are:
DUSD: 0xFf0000000000000000000000000000000000000F
JAV: 0x66F3Cf265D2D146A0348F6fC67E3Da0835e0968E
WDFI: 0x49febbF9626B2D39aBa11C01d83Ef59b3D56d2A4
VAN: 0x870c765f8aF9b189C324BE88B99884e5bAe4514b
MUSD: 0x80b6897Ba629d6C42584eC162CCA29F1E34783bE
USDT: 0xFF00000000000000000000000000000000000003
USDC: 0xFF0000000000000000000000000000000000000d

**Comment by llamatester** [comment]
The vanillaswap-v2.ts adapter exports: 
        
 
 _______________________________________
    Protocols for 12/6/2024
    _______________________________________
    
    DEFICHAIN_EVM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Daily fees: 0
    Timestamp: 1718188584 (2024-06-12T10:36:24.000Z)

**Comment by llamatester** [comment]
The vanillaswap-v3.ts adapter exports: 
        
 
 _______________________________________
    Protocols for 12/6/2024
    _______________________________________
    
    DEFICHAIN_EVM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Daily fees: 0
    Timestamp: 1718188596 (2024-06-12T10:36:36.000Z)

**Comment by rogi-sh** [comment]
Here are the pools: 
https://www.geckoterminal.com/defimetachain/vanillaswap-v3-defimetachain/pools
https://www.geckoterminal.com/defimetachain/vanillaswap-v2-defimetachain/pools

**Comment by llamatester** [comment]
The vanillaswap-v2.ts adapter exports: 
        
 
 _______________________________________
    Protocols for 13/6/2024
    _______________________________________
    
    DEFICHAIN_EVM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 63.53 k
    Daily fees: 191
    Timestamp: 1718291231 (2024-06-13T15:07:11.000Z)

**Comment by llamatester** [comment]
The vanillaswap-v3.ts adapter exports: 
        
 
 _______________________________________
    Protocols for 13/6/2024
    _______________________________________
    
    DEFICHAIN_EVM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 43.18 k
    Daily fees: 130
    Timestamp: 1718291249 (2024-06-13T15:07:29.000Z)

**Pull request merged**
