### PR TITLE
Added EETH on Arbitrum to PENDLE fees and revenues

### PR DESCRIPTION
**Pull request by ngfam**

### CODE REVIEW

**Comment by llamatester** [comment]
The pendle.ts adapter exports: 
        
 
 _______________________________________
    TypeError: Cannot read properties of undefined (reading 'Interface')
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/pendle.ts:69:43)
        at Module._compile (node:internal/modules/cjs/loader:1356:14)
        at Module.m._compile (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1618:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
        at Object.require.extensions.<computed> [as .ts] (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1621:12)
        at Module.load (node:internal/modules/cjs/loader:1197:32)
        at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
        at Module.require (node:internal/modules/cjs/loader:1225:19)
        at require (node:internal/modules/helpers:177:18)
        at /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:29:49
    Done in 1.38s.

**Comment by llamatester** [comment]
The pendle.ts adapter exports: 
        
 
 _______________________________________
    Fees for 8/2/2024
    _______________________________________
    
    {
      llamaRPCError: true,
      errors: [
        { host: 'https://bsc-dataseed.binance.org', error: [Object] },
        { host: 'https://bsc-dataseed3.defibit.io', error: [Object] },
        { host: 'https://bsc-dataseed2.ninicoin.io', error: [Object] }
      ],
      chain: 'bsc'
    }
    Done in 20.83s.

**Comment by dtmkeng** [comment]
@ngfam could you resolve `Conflicting` ?

**Comment by llamatester** [comment]
The pendle.ts adapter exports: 
        
 
 _______________________________________
    Fees for 13/2/2024
    _______________________________________
    
    {
      'arbitrum:0x82af49447d8a07e3bd95bd0d56f35241523fbab1': '28754487145791216',
      'arbitrum:0x912ce59144191c1204e64559fe8253a0e49e6548': '37388930852817330000',
      'arbitrum:0x3d9907f9a368ad0a51be60f7da3b97cf940982d8': '372037922616414',
      'arbitrum:0x0c880f6761f1af8d9aa9c466984b80dab9a8c9e8': '858016240166866200',
      'arbitrum:0x2ac2b254bc18cd4999f64773a966e4f4869c34ee': '2471486350345259500',
      'arbitrum:0xff970a61a04b1ca14834a43f5de4533ebddb5cc8': '6313861',
      'arbitrum:0xb6cfcf89a7b22988bfc96632ac2a9d6dab60d641': '52652',
      'arbitrum:0x1addd80e6039594ee970e5872d247bf0414c8903': '5664000694310779000',
      'arbitrum:0xa6c5c7d189fa4eb5af8ba34e63dcdd3a635d433f': '1020713258887364',
      'arbitrum:0x7cbaf5a14d953ff896e5b3312031515c858737c8': '2400867091494287400',
      'arbitrum:0x724dc807b04555b71ed48a6896b6f41593b8c637': '56027721',
      'arbitrum:0xb688ba096b7bb75d7841e47163cd12d18b36a5bf': '80532119293096360000',
      'arbitrum:0x55ade3b74abef55bf379ff6ae61cb77a405eb4a8': '501662650',
      'ethereum:0xae7ab96520de3a18e5e111b5eaab095312d7fe84': '293957757325497400',
      'ethereum:0x35fa164735182de50811e8e2e824cfb9b6118ac2': '1123033596426277200',
      'arbitrum:0xd85e038593d7a098614721eae955ec2022b9b91b': '293736122124907580000',
      'arbitrum:0xec70dcb4a1efa46b8f2d97c310c9c4790ba5ffa8': '26412400249571412',
      'arbitrum:0xc25cef6061cf5de5eb761b50e4743c1f5d7e5407': '42914752647810250',
      'arbitrum:0xbfca4230115de8341f3a3d5e8845ffb3337b2be3': '37627744834914640',
      'arbitrum:0xc9da32c3b444f15412f7feac6104d1e258d23b1b': '47222095508412936',
      'arbitrum:0x4307fbdcd9ec7aea5a1c2958decaa6f316952bab': '338574849785066800'
    }
    {
      'ethereum:0xae7ab96520de3a18e5e111b5eaab095312d7fe84': '3349146077815',
      'optimism:0x9bcef72be871e61ed4fbbc7630889bee758eb81d': '3284130007166965'
    }
    {
      'bsc:0x52f24a5e03aee338da5fd9df68d2b6fae1178827': '7095094056307416',
      'bsc:0xa2e3356610840701bdf5611a53974510ae27e2e1': '44047528533311'
    }
    [Error: Promise pool failed! 
     PromisePoolError: Llama RPC error! methos: undefined 
    - host: https://cloudflare-eth.com error: out of gas
    - host: https://eth.llamarpc.com error: out of gas: gas required exceeds allowance: 0x0000000000000000000000000000000000000000000000000000000002faf080_U256
    - host: https://gateway.tenderly.co/public/mainnet error: Request failed with status code 408
    - host: https://openapi.bitstack.com/v1/wNFxbiJyQsSeLrX8RRCHi7NpRxrlErZk/DjShIqLishPCTB9HiMkPHXjUM9CNM9Na/ETH/mainnet error: out of gas
    - host: https://mainnet.gateway.tenderly.co error: Request failed with status code 408
    - host: https://eth.drpc.org error: out of gas
    - host: https://endpoints.omniatech.io/v1/eth/mainnet/public error: missing trie node 0f469f707ba0fd21a4689370c9c573718dd96163bccb42de6ce6c03aaa58145d (path ) <nil>] {
      _isCustomError: true,
      chain: 'ethereum'
    }
    Done in 20.91s.

**Comment by llamatester** [comment]
The pendle.ts adapter exports: 
        
 
 _______________________________________
    Fees for 13/2/2024
    _______________________________________
    
    [Error: Promise pool failed! 
     PromisePoolError: Failed to call: function tryAggregate(bool requireSuccess, tuple(address target, bytes callData)[] calls) payable returns (tuple(bool success, bytes returnData)[] returnData) target: 0xca11bde05977b3631167028862be2a173976ca11 params: false, 0x58732f1c1243a0d5876a601fb8d1ee508b21580d,0xc4f59f9b,0x96f77f24b3d17166fcaf3a9e3b8330ff38b966f9,0xc4f59f9b,0xf86dda825885674f85c54200... on chain: [bsc] rpc: https://bsc-dataseed.binance.org, https://bsc-dataseed1.defibit.io, https://bsc-dataseed1.ninicoin.io, https://bsc-dataseed2.defibit.io, https://bsc-dataseed2.ninicoin.io, https://binance.llamarpc.com, https://bsc-dataseed.bnbchain.org, https://bsc-dataseed3.defibit.io, https://bsc-dataseed4.defibit.io, https://bsc-dataseed3.ninicoin.io, https://bsc-dataseed4.ninicoin.io, https://bsc-dataseed1.bnbchain.org, https://bsc-dataseed2.bnbchain.org, https://bsc-dataseed3.bnbchain.org, https://bsc-dataseed4.bnbchain.org, https://rpc-bsc.48.club, https://koge-rpc-bsc.48.club, https://endpoints.omniatech.io/v1/bsc/mainnet/public, https://bsc-pokt.nodies.app, https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3, https://rpc.ankr.com/bsc, https://bscrpc.com, https://binance.nodereal.io, https://bsc-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf, https://1rpc.io/bnb, https://bsc.rpc.blxrbdn.com, https://bsc.blockpi.network/v1/rpc/public, https://bnb.api.onfinality.io/public, https://bsc.publicnode.com, https://bsc-mainnet.public.blastapi.io, https://bsc.meowrpc.com, https://bsc.drpc.org, https://rpc.tornadoeth.cash/bsc  call reverted, reason: fragment.format is not a function   ] {
      _isCustomError: true,
      chain: 'bsc'
    }
    Done in 20.42s.

**Comment by llamatester** [comment]
The pendle.ts adapter exports: 
        
 
 _______________________________________
    Fees for 13/2/2024
    _______________________________________
    
    [Error: Promise pool failed! 
     PromisePoolError: Failed to call: function tryAggregate(bool requireSuccess, tuple(address target, bytes callData)[] calls) payable returns (tuple(bool success, bytes returnData)[] returnData) target: 0xca11bde05977b3631167028862be2a173976ca11 params: false, 0x58732f1c1243a0d5876a601fb8d1ee508b21580d,0xc4f59f9b,0x96f77f24b3d17166fcaf3a9e3b8330ff38b966f9,0xc4f59f9b,0xf86dda825885674f85c54200... on chain: [bsc] rpc: https://bsc-dataseed.binance.org, https://bsc-dataseed1.defibit.io, https://bsc-dataseed1.ninicoin.io, https://bsc-dataseed2.defibit.io, https://bsc-dataseed2.ninicoin.io, https://binance.llamarpc.com, https://bsc-dataseed.bnbchain.org, https://bsc-dataseed3.defibit.io, https://bsc-dataseed4.defibit.io, https://bsc-dataseed3.ninicoin.io, https://bsc-dataseed4.ninicoin.io, https://bsc-dataseed1.bnbchain.org, https://bsc-dataseed2.bnbchain.org, https://bsc-dataseed3.bnbchain.org, https://bsc-dataseed4.bnbchain.org, https://rpc-bsc.48.club, https://koge-rpc-bsc.48.club, https://endpoints.omniatech.io/v1/bsc/mainnet/public, https://bsc-pokt.nodies.app, https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3, https://rpc.ankr.com/bsc, https://bscrpc.com, https://binance.nodereal.io, https://bsc-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf, https://1rpc.io/bnb, https://bsc.rpc.blxrbdn.com, https://bsc.blockpi.network/v1/rpc/public, https://bnb.api.onfinality.io/public, https://bsc.publicnode.com, https://bsc-mainnet.public.blastapi.io, https://bsc.meowrpc.com, https://bsc.drpc.org, https://rpc.polysplit.cloud/v1/chain/56, https://rpc.tornadoeth.cash/bsc  call reverted, reason: fragment.format is not a function   ] {
      _isCustomError: true,
      chain: 'bsc'
    }
    Done in 15.40s.

**Comment by ngfam** [comment]
> @ngfam could you resolve `Conflicting` ?

I have adapted the PR with the updated codebase. Could you also help to rerun the new code for the last 7 days on Pendle fees so that defillama UI shows accurate datas?

**Comment by dtmkeng** [comment]
> > @ngfam could you resolve `Conflicting` ?
> 
> @dtmkeng I have adapted the PR with the updated codebase. Could you also help to rerun the new code for the last 7 days on Pendle fees so that defillama UI shows accurate datas?

yes will refill data last 7 day for pendle fees

**Pull request merged**
