### PR TITLE
fees and revenues

### PR DESCRIPTION
**Pull request by whichghost**

### CODE REVIEW

**Comment by llamatester** [comment]
The polter adapter exports: 
        
 
 _______________________________________
    Fees for 19/5/2024
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 16/5/1972
    NO METHODOLOGY SPECIFIED
    Daily fees: 6.53 k
    Daily revenue: 18.36 k
    Timestamp: 1716135781 (2024-05-19T16:23:01.000Z)

**Comment by llamatester** [comment]
The polter adapter exports: 
        
 
 _______________________________________
    Fees for 21/5/2024
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 29/1/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 1.48 k
    Daily revenue: 3.90 k
    Timestamp: 1716259593 (2024-05-21T02:46:33.000Z)

**Comment by dtmkeng** [comment]
why fees less than rev ? i guess fees is = all reward and how many % rev example holder rev and protocol rev

**Comment by dtmkeng** [comment]
https://github.com/DefiLlama/dimension-adapters/pull/1506 i change fees = rev if you have detail about reward paid go to team and token holder let me know about how to calculate

**Pull request merged**
