### PR TITLE
Add fees from fee distributor for Thruster

### PR DESCRIPTION
**Pull request by jooleseth**
Ran with test command `npm test fees thruster 1733806031`

Parses the token amount of USDB to return as string directly instead of adding to object

Open to suggestions

### CODE REVIEW

**Comment by llamatester** [comment]
The thruster adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees thruster
    
    🦙 Running THRUSTER adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 05:07:08 GMT
    End Date:	Wed, 11 Dec 2024 05:07:08 GMT
    ---------------------------------------------------
    
    BLAST 👇
    Backfill start time: 17/4/1970
    Daily fees: 0
    └─ Methodology: The USDB distributed to veTHRUST stakers.
    End timestamp: 1733893627 (2024-12-11T05:07:07.000Z)

**Comment by llamatester** [comment]
The thruster adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees thruster
    
    🦙 Running THRUSTER adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 05:16:15 GMT
    End Date:	Wed, 11 Dec 2024 05:16:15 GMT
    ---------------------------------------------------
    
    BLAST 👇
    Backfill start time: 17/4/1970
    Daily fees: 0
    └─ Methodology: The USDB distributed to veTHRUST stakers.
    End timestamp: 1733894174 (2024-12-11T05:16:14.000Z)

**Comment by llamatester** [comment]
The thruster-v3.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts protocols thruster-v3.ts
    
    🦙 Running THRUSTER-V3.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 07:37:27 GMT
    End Date:	Wed, 11 Dec 2024 07:37:27 GMT
    ---------------------------------------------------
    
    BLAST 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 26.97 M
    Daily fees: 27.56 k
    End timestamp: 1733902646 (2024-12-11T07:37:26.000Z)

**Comment by g1nt0ki** [comment]
hi @jooleseth thanks for the PR, included it in current listing

**Pull request closed without merging**
