### PR TITLE
IntentX Fees and Volume integration

### PR DESCRIPTION
**Pull request by lemonpac**
**Project Description**
IntentX is a perpetuals platform based on intent technology

**Resources**
https://twitter.com/IntentX_
https://intentx.io

### CODE REVIEW

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    dexs/intent-x/index.tsx(2,23): error TS2307: Cannot find module '../helpers/chains' or its corresponding type declarations.
    dexs/intent-x/index.tsx(4,46): error TS2307: Cannot find module '../helpers/getUniSubgraphVolume' or its corresponding type declarations.
    dexs/intent-x/index.tsx(5,48): error TS2307: Cannot find module '../adapters/types' or its corresponding type declarations.
    
    Done in 3.56s.

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Dexs for 1/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 6/8/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796800
    Daily fees: undefined
    Total fees: 0.19725174
    Daily user fees: undefined
    Daily revenue: undefined
    Daily protocol revenue: 0
    Daily holders revenue: undefined
    Daily supply side revenue: 0
    Total user fees: 0.19725174
    Total revenue: 0.19725174
    Total protocol revenue: 0
    Total supply side revenue: 0
    
    
    
    
    Done in 3.94s.

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Fees for 1/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 6/8/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796800
    Daily fees: undefined
    Total fees: 0.19725174
    Daily user fees: undefined
    Daily revenue: undefined
    Daily protocol revenue: 0
    Daily holders revenue: undefined
    Daily supply side revenue: 0
    Total user fees: 0.19725174
    Total revenue: 0.19725174
    Total protocol revenue: 0
    Total supply side revenue: 0
    
    
    
    
    Done in 3.62s.

**Comment by dtmkeng** [comment]
hi dexs adapter require file `dailyVolume` could you fix
and could you check daily fees why undefined if that day does not have data plz set it 0

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Dexs for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily volume: 13635343.892694459
    Total volume: undefined
    
    
    
    
    Done in 5.60s.

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Fees for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily fees: 4.33843694
    Total fees: 7.391044412
    Daily user fees: 4.33843694
    Daily revenue: 4.33843694
    Daily protocol revenue: 0
    Daily holders revenue: 4.33843694
    Daily supply side revenue: 0
    Total user fees: 7.391044412
    Total revenue: 7.391044412
    Total protocol revenue: 0
    Total supply side revenue: 0
    
    
    
    
    Done in 2.81s.

**Comment by lemonpac** [comment]
Fees undefined values and Dexs files :)

**Comment by dtmkeng** [comment]
why `accountSource` is not same account 🤔

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Dexs for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily volume: undefined
    Total volume: undefined
    
    
    
    
    Done in 4.48s.

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Fees for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily fees: 4.33843694
    Total fees: 13.376719292
    Daily user fees: 4.33843694
    Daily revenue: 4.33843694
    Daily protocol revenue: 0
    Daily holders revenue: 4.33843694
    Daily supply side revenue: 0
    Total user fees: 13.376719292
    Total revenue: 13.376719292
    Total protocol revenue: 0
    Total supply side revenue: 0
    
    
    
    
    Done in 5.51s.

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Dexs for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily volume: undefined
    Total volume: undefined
    
    
    
    
    Done in 6.17s.

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Fees for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily fees: 4.33843694
    Total fees: 13.376719292
    Daily user fees: 4.33843694
    Daily revenue: 4.33843694
    Daily protocol revenue: 0
    Daily holders revenue: 4.33843694
    Daily supply side revenue: 0
    Total user fees: 13.376719292
    Total revenue: 13.376719292
    Total protocol revenue: 0
    Total supply side revenue: 0
    
    
    
    
    Done in 4.17s.

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Dexs for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily volume: 13635343.892694459
    Total volume: undefined
    
    
    
    
    Done in 2.87s.

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Fees for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily fees: 4.33843694
    Total fees: 13.376719292
    Daily user fees: 4.33843694
    Daily revenue: 4.33843694
    Daily protocol revenue: 0
    Daily holders revenue: 4.33843694
    Daily supply side revenue: 0
    Total user fees: 13.376719292
    Total revenue: 13.376719292
    Total protocol revenue: 0
    Total supply side revenue: 0
    
    
    
    
    Done in 2.65s.

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Dexs for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily volume: undefined
    Total volume: undefined
    
    
    
    
    Done in 2.71s.

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Fees for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily fees: 4.33843694
    Total fees: 13.376719292
    Daily user fees: 4.33843694
    Daily revenue: 4.33843694
    Daily protocol revenue: 0
    Daily holders revenue: 4.33843694
    Daily supply side revenue: 0
    Total user fees: 13.376719292
    Total revenue: 13.376719292
    Total protocol revenue: 0
    Total supply side revenue: 0
    
    
    
    
    Done in 2.56s.

**Comment by lemonpac** [comment]
Fixed accountSource difference 🤔

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Dexs for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily volume: 0
    Total volume: 0
    
    
    
    
    Done in 2.79s.

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Fees for 5/11/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699142400
    Daily fees: 4.33843694
    Total fees: 13.376719292
    Daily user fees: 4.33843694
    Daily revenue: 4.33843694
    Daily protocol revenue: 0
    Daily holders revenue: 4.33843694
    Daily supply side revenue: 0
    Total user fees: 13.376719292
    Total revenue: 13.376719292
    Total protocol revenue: 0
    Total supply side revenue: 0
    
    
    
    
    Done in 2.63s.

**Comment by lemonpac** [comment]
Now is using timestamps at the beginning of our platform data origin
Also replaced the subgraph to use our custom one

**Pull request merged**
