### PR TITLE
better fiat stables

### PR DESCRIPTION
**Pull request by 0xngmi**
Change code for tether and circle to be based partially on on-chain data

could be improved by using an api to get treasury rate at a point in time but i couldnt find any

### CODE REVIEW

**Comment by llamatester** [comment]
The circle.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees circle.ts
    
    🦙 Running CIRCLE.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 23 Nov 2024 15:17:08 GMT
    End Date:	Sun, 24 Nov 2024 15:17:08 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily fees: 3.48 M
    Daily revenue: 3.48 M
    End timestamp: 1732461427 (2024-11-24T15:17:07.000Z)

**Comment by llamatester** [comment]
The tether adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees tether
    
    🦙 Running TETHER adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 23 Nov 2024 15:17:19 GMT
    End Date:	Sun, 24 Nov 2024 15:17:19 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily fees: 8.65 M
    Daily revenue: 8.65 M
    End timestamp: 1732461438 (2024-11-24T15:17:18.000Z)

**Comment by llamatester** [comment]
The circle.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees circle.ts
    
    🦙 Running CIRCLE.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 23 Nov 2024 15:58:11 GMT
    End Date:	Sun, 24 Nov 2024 15:58:11 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily fees: 4.77 M
    Daily revenue: 4.77 M
    End timestamp: 1732463890 (2024-11-24T15:58:10.000Z)

**Comment by g1nt0ki** [comment]
maybe chainlink/pyth has an oracle from which we can pull treasury rate on chain?

**Pull request merged**
