### PR TITLE
GEODNET Fees/Revenue/Holders Revenue

### PR DESCRIPTION
**Pull request by 0xnirmal**
There's no TVL for this project, so was hoping to do something like Metamask, with just the Fees/Revenue/Holders Revenue: https://defillama.com/protocol/metamask

Description of methodology can be found here: https://insidegnss.com/developing-a-truly-global-rtk-network/

Dune Dashboard: https://dune.com/geodnet_console/geod-console

---
##### Name (to be shown on DefiLlama):
Geodnet

##### Twitter Link:
`https://twitter.com/GEODNET_`

##### Website Link:
https://geodnet.com/

##### Logo (High resolution, will be shown with rounded borders):
https://assets.coingecko.com/coins/images/31608/standard/Circular_White.png?1696530424

##### Current TVL:
N/A

##### Treasury Addresses (if the protocol has treasury)
N/A

##### Chain:
Polygon

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
geodnet

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
20969

##### Short Description (to be shown on DefiLlama):
GEODNET is a web3.0 blockchain-based highly-reliable RTK Network using #DePIN principles.

RTK (Real-Time Kinematics) enables a 100x improvement in position accuracy as compared to standalone GPS. GEODNET's global RTK Network naturally complements on-device sensors such as Cameras, LiDAR, and IMU's to power AI-based Autonomous Systems.

##### Token address and ticker if any:
0xac0f66379a6d7801d7726d5a943356a172549adb
GEOD

##### Category (full list at https://defillama.com/categories) *Please choose only one:
N/A (DePin if possible)

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
N/A
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
N/A
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology (what is being counted as tvl, how is tvl being calculated):
N/A

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/geodnet

### CODE REVIEW

**Comment by llamatester** [comment]
The geodnet.ts adapter exports: 
        
 
 _______________________________________
    Fees for 11/3/2024
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 10/9/2023
    Daily fees: 0
    └─ Methodology: GEODNET receives fees for station access to their RTK network.
    Daily revenue: 0
    └─ Methodology: When GEODNET receives fees for station access, 80% of the fees are used to repurchase GEOD tokens from the open market and remove them from circulation. The remaining 20% supports the foundation's organizational costs.
    Daily holders revenue: 0
    └─ Methodology: 80% of the fees are used to repurchase GEOD tokens from the open market and remove them from circulation.
    Timestamp: 1710201598 (2024-03-11T23:59:58.000Z)
    
    
    
    
    Done in 10.79s.

**Comment by llamatester** [comment]
The geodnet.ts adapter exports: 
        
 
 _______________________________________
    Fees for 11/3/2024
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 10/9/2023
    Daily fees: 0
    └─ Methodology: GEODNET receives fees for station access to their RTK network.
    Daily revenue: 0
    └─ Methodology: When GEODNET receives fees for station access, 80% of the fees are used to repurchase GEOD tokens from the open market and remove them from circulation. The remaining 20% supports the foundation's organizational costs.
    Daily holders revenue: 0
    └─ Methodology: 80% of the fees are used to repurchase GEOD tokens from the open market and remove them from circulation.
    Timestamp: 1710201598 (2024-03-11T23:59:58.000Z)
    
    
    
    
    Done in 10.78s.

**Comment by llamatester** [comment]
The geodnet.ts adapter exports: 
        
 
 _______________________________________
    Fees for 14/3/2024
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 10/9/2023
    Daily fees: 4.07 k
    └─ Methodology: GEODNET receives fees for station access to their RTK network.
    Daily revenue: 4.07 k
    └─ Methodology: When GEODNET receives fees for station access, 80% of the fees are used to repurchase GEOD tokens from the open market and remove them from circulation. The remaining 20% supports the foundation's organizational costs.
    Daily holders revenue: 3.25 k
    └─ Methodology: 80% of the fees are used to repurchase GEOD tokens from the open market and remove them from circulation.
    Timestamp: 1710460798 (2024-03-14T23:59:58.000Z)
    
    
    
    
    Done in 27.70s.

**Comment by 0xnirmal** [comment]
@dtmkeng - can I get a backfill on this? Looks like UI only has new data points: https://defillama.com/protocol/geodnet?fees=true

Many thanks!

**Pull request merged**
