### PR TITLE
Add aggregators plexus tatal volume

### PR DESCRIPTION
**Pull request by Plexus-Olivia**
Hello DeFiLlama is using the plexus fee API, so I kept it and added a trading volume API. Is it possible to update?

### CODE REVIEW

**Comment by dtmkeng** [comment]
yesh
```
_______________________________________
Aggregators for 26/4/2023
_______________________________________

ETHEREUM 👇
Backfill start time: 1/2/2023
NO METHODOLOGY SPECIFIED
Daily volume: 59.861669312
Timestamp: 1682553598


BSC 👇
Backfill start time: 1/2/2023
NO METHODOLOGY SPECIFIED
Daily volume: 2116.740406128761
Timestamp: 1682553598


POLYGON 👇
Backfill start time: 1/2/2023
NO METHODOLOGY SPECIFIED
Daily volume: 9485.171786899537
Timestamp: 1682553598


FANTOM 👇
Backfill start time: 1/2/2023
NO METHODOLOGY SPECIFIED
Daily volume: 0
Timestamp: 1682553598


KAVA 👇
Backfill start time: 1/2/2023
NO METHODOLOGY SPECIFIED
Daily volume: 47442.70316798316
Timestamp: 1682553598


ARBITRUM 👇
Backfill start time: 1/2/2023
NO METHODOLOGY SPECIFIED
Daily volume: 60.98688325198795
Timestamp: 1682553598


AVAX 👇
Backfill start time: 1/2/2023
NO METHODOLOGY SPECIFIED
Daily volume: 0
Timestamp: 1682553598


OPTIMISM 👇
Backfill start time: 1/2/2023
NO METHODOLOGY SPECIFIED
Daily volume: 0
Timestamp: 1682553598


KLAYTN 👇
Backfill start time: 1/2/2023
NO METHODOLOGY SPECIFIED
Daily volume: 0
Timestamp: 1682553598


AURORA 👇
Backfill start time: 1/2/2023
NO METHODOLOGY SPECIFIED
Daily volume: 0
Timestamp: 1682553598
```
this result are you ok ?

**Comment by Plexus-Olivia** [comment]
That's right. Thank you

**Comment by HIprotocoltony** [comment]
Thank you @dtmkeng  Is PLEXUS being added here? https://defillama.com/dexs/chains/kava

**Comment by dtmkeng** [comment]
> Thank you @dtmkeng Is PLEXUS being added here? https://defillama.com/dexs/chains/kava

think no, at this  https://defillama.com/aggregators

**Comment by HIprotocoltony** [comment]
I see, will the kava chain be added as well?

**Comment by dtmkeng** [comment]
i guess will show on thi https://defillama.com/aggregators/chains

**Pull request merged**
