### PR TITLE
Create Omax-swap

### PR DESCRIPTION
**Pull request by OMAXCHAIN**
Volume for DEX- Omax Swap

### CODE REVIEW

**Comment by OMAXCHAIN** [comment]
Adding the volume for Omax swap

**Comment by dtmkeng** [comment]
could you move file to under dexs folder ?

**Comment by OMAXCHAIN** [comment]
@dtmkeng its not letting me to upload or move.

**Comment by dtmkeng** [comment]
1. create folder `Omax-swap` under dexs folder 
2. create file `index.ts` under folder `Omax-swap`
3. move code to `index.ts`
4. remove `Omax-swap`

**Comment by OMAXCHAIN** [comment]
@dtmkeng is it okay now?

**Comment by dtmkeng** [comment]
> @dtmkeng is it okay now?

no. you should fix by step above plzzzzz

**Pull request closed without merging**
