### PR TITLE
add base fees

### PR DESCRIPTION
**Pull request by dtmkeng**

### CODE REVIEW

**Comment by llamatester** [comment]
The base.ts adapter exports: 
        
 
 _______________________________________
    Fees for 24/7/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/8/2020
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690243198
    Daily fees: 3.657203906373521263
    
    
    
    
    Done in 4.23s.

**Comment by llamatester** [comment]
The base.ts adapter exports: 
        
 
 _______________________________________
    Fees for 25/7/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 29/8/2020
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690329598
    Daily fees: 3.573916082559635161
    
    
    
    
    Done in 4.22s.

**Comment by llamatester** [comment]
The base.ts adapter exports: 
        
 
 _______________________________________
    Fees for 25/7/2023
    _______________________________________
    
    Error: connect ECONNREFUSED ::1:5432
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
        at cachedError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/query.js:171:23)
        at new Query (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/query.js:36:24)
        at sql (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/index.js:111:11)
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/base.ts:71:33)
    Failed to get value on base: Error: connect ECONNREFUSED ::1:5432
    BASE 👇
    Timestamp attempted: 24/7/2023
    Error: connect ECONNREFUSED ::1:5432
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
        at cachedError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/query.js:171:23)
        at new Query (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/query.js:36:24)
        at sql (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/index.js:111:11)
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/base.ts:71:33)
    
    
    
    
    Done in 4.39s.

**Review by mrkts16 — APPROVED** [review]

**Review by mrkts16 — COMMENTED** [review]
BASE 👇
Backfill start time: 29/8/2020
NO METHODOLOGY SPECIFIED
Timestamp: 1690243198
Daily fees: 3.657203906373521263

**Review by mrkts16 — APPROVED** [review]

**Pull request merged**
