### PR TITLE
Add aark digital

### PR DESCRIPTION
**Pull request by sp-aark**

### CODE REVIEW

**Comment by llamatester** [comment]
The aark adapter exports: 
        
 
 _______________________________________
    Dexs for 13/8/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 12/8/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 25911191.979656085
    Daily volume: 12665347.644950835
    Timestamp: 1691884800
    
    
    
    
    Done in 3.35s.

**Comment by dtmkeng** [comment]
could you remove change yarn lock ?

**Review by mrkts16 — APPROVED** [review]

**Review by mrkts16 — APPROVED** [review]

**Comment by llamatester** [comment]
The aark adapter exports: 
        
 
 _______________________________________
    Dexs for 14/8/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 12/8/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 44766524.492077336
    Daily volume: 15287266.920749586
    Timestamp: 1691971200
    
    
    
    
    Done in 4.82s.

**Comment by sp-aark** [comment]
did it

**Pull request merged**
