### PR TITLE
update Demex Exchange's historical volume endpoint

### PR DESCRIPTION
**Pull request by victorlaiyeeteng**
Updated the 'historicalVolumeEndpoint' of Demex exchange. 
It was previously displaying the pool volume, but the correct volume to be displayed should be the market volume.

### CODE REVIEW

**Comment by llamatester** [comment]
The demex adapter exports: 
        
 
 _______________________________________
    Dexs for 15/5/2023
    _______________________________________
    
    CARBON 👇
    Backfill start time: 1/8/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 84462045.0200000000
    Daily volume: 75722.5200000000
    Timestamp: 1684108800
    
    
    
    
    Done in 6.53s.

**Comment by dtmkeng** [comment]
> s previously displaying the pool volume, but the correct volume to be displayed should be the market volume.

could you explain, how different between market volume and pool volume?

**Comment by victorlaiyeeteng** [comment]
@dtmkeng 
In Carbon, carbon pools are not linked 1-to-1 like typical AMM pools. Pool volume only consist of the total volume traded with our liquidity pools (to do AMM) in Demex exchange, but this only contributes to part of Demex’s market volume. 
However, to correctly reflect Demex’s total volume, market volume should be used as it comprises of both the pool volume and the volume from non-AMM trades from users and market makers. Market volume reflects accurately the total amount traded for a token pair.

**Comment by dtmkeng** [comment]
ty 🙏

**Pull request merged**
