### PR TITLE
Add trading volume and fees for Trado Perpetual

### PR DESCRIPTION
**Pull request by flowdex**

### CODE REVIEW

**Comment by llamatester** [comment]
The trado adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs trado
    
    🦙 Running TRADO adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 03 Oct 2024 00:00:00 GMT
    End Date:	Fri, 04 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    FLOW 👇
    Backfill start time: 17/1/1970
    NO METHODOLOGY SPECIFIED
    End timestamp: 1727999999 (2024-10-03T23:59:59.000Z)
    Total volume: 423.19 k
    Daily volume: 798

**Comment by llamatester** [comment]
The trado adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees trado
    
    🦙 Running TRADO adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 03 Oct 2024 15:13:20 GMT
    End Date:	Fri, 04 Oct 2024 15:13:20 GMT
    ---------------------------------------------------
    
    FLOW 👇
    Backfill start time: 17/1/1970
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Total fees: 282
    End timestamp: 1728054799 (2024-10-04T15:13:19.000Z)

**Review by Rezacb0413 — APPROVED** [review]

**Review by Rezacb0413 — APPROVED** [review]

**Review by Rezacb0413 — APPROVED** [review]

**Comment by llamatester** [comment]
The trado adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs trado
    
    🦙 Running TRADO adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 06 Oct 2024 10:43:38 GMT
    End Date:	Mon, 07 Oct 2024 10:43:38 GMT
    ---------------------------------------------------
    
    FLOW 👇
    Backfill start time: 17/1/1970
    NO METHODOLOGY SPECIFIED
    Total volume: 438.78 k
    Daily volume: 11.65 k
    End timestamp: 1728297817 (2024-10-07T10:43:37.000Z)

**Comment by llamatester** [comment]
The trado adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees trado
    
    🦙 Running TRADO adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 06 Oct 2024 10:43:43 GMT
    End Date:	Mon, 07 Oct 2024 10:43:43 GMT
    ---------------------------------------------------
    
    FLOW 👇
    Backfill start time: 17/1/1970
    NO METHODOLOGY SPECIFIED
    Total fees: 291
    Daily fees: 8
    End timestamp: 1728297822 (2024-10-07T10:43:42.000Z)

**Pull request merged**
