### PR TITLE
feat: using premium field for revenue

### PR DESCRIPTION
**Pull request by KngZhi**

### CODE REVIEW

**Comment by llamatester** [comment]
The premia.ts adapter exports: 
        
 
 _______________________________________
    Fees for 12/1/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 1237.60
    Timestamp: 1673567998
    
    
    ETHEREUM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 727.13
    Timestamp: 1673567998
    
    
    FANTOM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 2034.34
    Timestamp: 1673567998
    
    
    OPTIMISM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 451.25
    Timestamp: 1673567998
    
    
    
    
    Done in 6.69s.

**Comment by llamatester** [comment]
The premia.ts adapter exports: 
        
 
 _______________________________________
    Fees for 14/1/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 2606.43
    Daily revenue: 78.15
    Timestamp: 1673740798
    Total fees: 6433006.83
    Total revenue: 214125.63
    
    
    ETHEREUM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 499.58
    Daily revenue: 14.99
    Timestamp: 1673740798
    Total fees: 2499804.65
    Total revenue: 78255.92
    
    
    FANTOM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 1790.24
    Daily revenue: 53.71
    Timestamp: 1673740798
    Total fees: 1568677.04
    Total revenue: 47160.42
    
    
    OPTIMISM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 942.85
    Daily revenue: 28.56
    Timestamp: 1673740798
    Total fees: 681559.75
    Total revenue: 20655.63
    
    
    
    
    Done in 7.76s.

**Comment by llamatester** [comment]
The premia adapter exports: 
        
 
 _______________________________________
    Options for 14/1/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1673740798
    Total notional volume: 48868921.27110325
    Daily notional volume: 14498.94701000303
    Total premium volume: 2499804.646267921
    Daily premium volume: 499.5785349709913
    
    
    ARBITRUM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1673740798
    Total notional volume: 160196157.98300368
    Daily notional volume: 194360.4647859037
    Total premium volume: 6433006.829597451
    Daily premium volume: 2606.427910624072
    
    
    FANTOM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1673740798
    Total notional volume: 33849803.25576832
    Daily notional volume: 134946.54315459356
    Total premium volume: 1568677.036782028
    Daily premium volume: 1790.2381260681432
    
    
    OPTIMISM 👇
    Backfill start time: 25/6/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1673740798
    Total notional volume: 15144455.100936847
    Daily notional volume: 38474.47809558362
    Total premium volume: 681559.7517466191
    Daily premium volume: 942.8542415084084
    
    
    
    
    Done in 7.04s.

**Comment by KngZhi** [comment]
@0xngmi mind to take a look?

**Pull request merged**
