### PR TITLE
Create koi-finance Fees 

### PR DESCRIPTION
**Pull request by mattt21**

### CODE REVIEW

**Comment by llamatester** [comment]
The mute.io adapter exports: 
        
 
 _______________________________________
    Dexs for 2/4/2024
    _______________________________________
    
    ERA 👇
    Backfill start time: 23/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1712018218 (2024-04-02T00:36:58.000Z)
    Block: 30.45 M
    Total volume: 1.23 B
    Daily volume: 300.93 k
    
    
    
    
    Done in 10.99s.

**Comment by llamatester** [comment]
The koi-finance adapter exports: 
        
 
 _______________________________________
    Fees for 1/4/2024
    _______________________________________
    
    ZKSYNC 👇
    Backfill start time: 23/2/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 9.86 k
    Daily revenue: 1.97 k
    Timestamp: 1712015999 (2024-04-01T23:59:59.000Z)
    
    
    
    
    Done in 5.36s.

**Comment by mattt21** [comment]
@dtmkeng how long till this shows up on our page?

**Comment by dtmkeng** [comment]
around 2-3 hour

**Pull request merged**
