### PR TITLE
feat: add fees and dexs zeno

### PR DESCRIPTION
**Pull request by GalenSofiadis**

### CODE REVIEW

**Comment by llamatester** [comment]
The zeno adapter exports: 
        
 
 _______________________________________
    Dexs for 9/5/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 25/6/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1715237142 (2024-05-09T06:45:42.000Z)
    Total volume: 8.82 M
    Daily volume: 0

**Comment by llamatester** [comment]
The zeno.ts adapter exports: 
        
 
 _______________________________________
    Fees for 9/5/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 25/6/1970
    NO METHODOLOGY SPECIFIED
    Daily fees: 22
    Daily user fees: 20
    Daily revenue: 10
    Daily protocol revenue: 1
    Daily holders revenue: 9
    Daily supply side revenue: 12
    Total fees: 3.07 k
    Total user fees: 2.81 k
    Timestamp: 1715237152 (2024-05-09T06:45:52.000Z)

**Comment by llamatester** [comment]
The zeno.ts adapter exports: 
        
 
 _______________________________________
    Fees for 10/5/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 25/6/1970
    NO METHODOLOGY SPECIFIED
    Daily fees: 48
    Daily user fees: 48
    Daily revenue: 14
    Daily protocol revenue: 2
    Daily holders revenue: 12
    Daily supply side revenue: 17
    Total fees: 3.12 k
    Total user fees: 2.85 k
    Timestamp: 1715345121 (2024-05-10T12:45:21.000Z)

**Comment by llamatester** [comment]
The zeno adapter exports: 
        
 
 _______________________________________
    Dexs for 16/5/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 13/3/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1715831346 (2024-05-16T03:49:06.000Z)
    Total volume: 8.95 M
    Daily volume: 5.00 k

**Comment by llamatester** [comment]
The zeno.ts adapter exports: 
        
 
 _______________________________________
    Fees for 16/5/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 13/3/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 1
    Daily user fees: 1
    Daily revenue: 0
    Daily protocol revenue: 0
    Daily holders revenue: 0
    Daily supply side revenue: 1
    Total fees: 3.17 k
    Total user fees: 2.90 k
    Timestamp: 1715831354 (2024-05-16T03:49:14.000Z)

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Pull request merged**
