### PR TITLE
add nlx protocol...

### PR DESCRIPTION
**Pull request by nlx-morpheus**

### CODE REVIEW

**Comment by llamatester** [comment]
The nlx adapter exports: 
        
 
 _______________________________________
    Dexs for 4/5/2024
    _______________________________________
    
    Version -> NLX-SWAP
    ---------
    CORE 👇
    Backfill start time: 24/4/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 14
    Timestamp: 1714788764 (2024-05-04T02:12:44.000Z)
    
    
    Version -> NLX-TRADE
    ---------
    CORE 👇
    Backfill start time: 24/4/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 6.60 k
    Timestamp: 1714788764 (2024-05-04T02:12:44.000Z)

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Comment by nlx-morpheus** [comment]
Yes... made a PR for it Too

https://github.com/DefiLlama/DefiLlama-Adapters/pull/10091

**Comment by dtmkeng** [comment]
how different trade and swap ? trade is it perp ? like gmx ?

**Pull request merged**
