### PR TITLE
Add Kinetix and Metavault dexs and fees adapters.

### PR DESCRIPTION
**Pull request by 0xrmvdao**
Dexs
------
kinetix-v2
metavault-amm-v2

Fees
-----
kinetix-v2
kinetix-v3
metavault-amm-v2
metavault-v3

### CODE REVIEW

**Comment by llamatester** [comment]
The kinetix-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs kinetix-v2
    
    🦙 Running KINETIX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 23 Oct 2024 05:13:17 GMT
    End Date:	Thu, 24 Oct 2024 05:13:17 GMT
    ---------------------------------------------------
    
    KAVA 👇
    Backfill start time: 24/10/2024
    NO METHODOLOGY SPECIFIED
    Block: 12.32 M
    Total volume: 10.25 k
    Daily volume: 11
    End timestamp: 1729746796 (2024-10-24T05:13:16.000Z)
    
    
    BASE 👇
    Backfill start time: 24/10/2024
    NO METHODOLOGY SPECIFIED
    Block: 21.48 M
    Total volume: 0
    Daily volume: 0
    End timestamp: 1729746796 (2024-10-24T05:13:16.000Z)

**Comment by llamatester** [comment]
The metavault-amm-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs metavault-amm-v2
    
    🦙 Running METAVAULT-AMM-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 23 Oct 2024 05:13:27 GMT
    End Date:	Thu, 24 Oct 2024 05:13:27 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 24/10/2024
    NO METHODOLOGY SPECIFIED
    Block: 11.14 M
    Total volume: 1.86 k
    Daily volume: 5
    End timestamp: 1729746806 (2024-10-24T05:13:26.000Z)
    
    
    SCROLL 👇
    Backfill start time: 24/10/2024
    NO METHODOLOGY SPECIFIED
    Block: 10.48 M
    Total volume: 54.13 k
    Daily volume: 0
    End timestamp: 1729746806 (2024-10-24T05:13:26.000Z)

**Comment by llamatester** [comment]
The kinetix-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees kinetix-v2
    
    🦙 Running KINETIX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 23 Oct 2024 00:00:00 GMT
    End Date:	Thu, 24 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    KAVA 👇
    Backfill start time: 22/8/2023
    Methodology: Fees collected from user trading fees
    End timestamp: 1729641600 (2024-10-23T00:00:00.000Z)
    Daily fees: 0
    Total fees: 30
    
    
    BASE 👇
    Backfill start time: 8/5/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1729641600 (2024-10-23T00:00:00.000Z)
    Daily fees: 0
    Total fees: 0

**Comment by llamatester** [comment]
The kinetix-v3 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees kinetix-v3
    
    🦙 Running KINETIX-V3 adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 23 Oct 2024 00:00:00 GMT
    End Date:	Thu, 24 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    KAVA 👇
    Backfill start time: 15/8/2023
    Methodology: Fees collected from user trading fees
    End timestamp: 1729641600 (2024-10-23T00:00:00.000Z)
    Daily fees: 65
    Total fees: 75.17 k
    
    
    BASE 👇
    Backfill start time: 8/5/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1729641600 (2024-10-23T00:00:00.000Z)
    Daily fees: 0
    Total fees: 181

**Comment by llamatester** [comment]
The metavault-v3 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees metavault-v3
    
    🦙 Running METAVAULT-V3 adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 23 Oct 2024 00:00:00 GMT
    End Date:	Thu, 24 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 1/3/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1729641600 (2024-10-23T00:00:00.000Z)
    Daily fees: 3
    Total fees: 102.25 k
    
    
    SCROLL 👇
    Backfill start time: 1/3/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1729641600 (2024-10-23T00:00:00.000Z)
    Daily fees: 2
    Total fees: 43.94 k

**Comment by g1nt0ki** [comment]
looks good, thanks for the PR

**Pull request merged**
