### PR TITLE
feat: update apx daily trading volume exclude cake volume

### PR DESCRIPTION
**Pull request by AQVYmeCkJsFTFWpMAHmA**

### CODE REVIEW

**Comment by llamatester** [comment]
The apollox adapter exports: 
        
 
 _______________________________________
    Dexs for 29/1/2024
    _______________________________________
    
    BSC 👇
    Backfill start time: 21/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 15.33 M
    Timestamp: 1706572798
    
    
    ARBITRUM 👇
    Backfill start time: 21/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 454.22 k
    Timestamp: 1706572798
    
    
    
    
    Done in 3.45s.

**Comment by dtmkeng** [comment]
duplicate https://github.com/DefiLlama/dimension-adapters/pull/877

**Comment by DrunkCzz** [comment]
> 重复#877
This Interface data excludes PANCAKE!

**Comment by DrunkCzz** [comment]
full-volume data：
https://www.apollox.finance/bapi/future/v1/public/future/apx/pair?chain=bsc

exclude cake date
https://www.apollox.finance/bapi/future/v1/public/future/apx/pair?chain=bsc&excludeCake=true

It's different

> duplicate #877

**Comment by llamatester** [comment]
The apollox adapter exports: 
        
 
 _______________________________________
    Dexs for 29/1/2024
    _______________________________________
    
    BSC 👇
    Backfill start time: 21/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 15.33 M
    Timestamp: 1706572798
    
    
    ARBITRUM 👇
    Backfill start time: 21/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 580.10 k
    Timestamp: 1706572798
    
    
    
    
    Done in 3.84s.

**Comment by dtmkeng** [comment]
merged sorry i missunderstand

**Pull request merged**
