### PR TITLE
Add C3 Exchange Volumes

### PR DESCRIPTION
**Pull request by MatHermida**

### CODE REVIEW

**Comment by llamatester** [comment]
The c3-exchange adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs c3-exchange
    
    🦙 Running C3-EXCHANGE adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 01 Aug 2024 17:20:04 GMT
    End Date:	Fri, 02 Aug 2024 17:20:04 GMT
    ---------------------------------------------------
    
    ALGORAND 👇
    Backfill start time: 1/7/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 525
    End timestamp: 1722619203 (2024-08-02T17:20:03.000Z)
    
    
    AVAX 👇
    Backfill start time: 1/7/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 23.60 k
    End timestamp: 1722619203 (2024-08-02T17:20:03.000Z)
    
    
    BITCOIN 👇
    Backfill start time: 1/7/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 35.13 k
    End timestamp: 1722619203 (2024-08-02T17:20:03.000Z)
    
    
    ETHEREUM 👇
    Backfill start time: 1/7/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 22.62 k
    End timestamp: 1722619203 (2024-08-02T17:20:03.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 1/7/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 30.52 k
    End timestamp: 1722619203 (2024-08-02T17:20:03.000Z)
    
    
    BSC 👇
    Backfill start time: 1/7/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1722619203 (2024-08-02T17:20:03.000Z)
    
    
    SOLANA 👇
    Backfill start time: 1/7/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 12.74 k
    End timestamp: 1722619203 (2024-08-02T17:20:03.000Z)

**Comment by dtmkeng** [comment]
is it swap volume ?

**Comment by MatHermida** [comment]
> is it swap volume ?

Yes, it's the swap volume for each trading pair in our protocol, grouped by the corresponding chains of the assets in the pairs.

**Comment by dtmkeng** [comment]
is there example txs ?

**Comment by llamatester** [comment]
The c3-exchange adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs c3-exchange
    
    🦙 Running C3-EXCHANGE adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 04 Aug 2024 15:12:33 GMT
    End Date:	Mon, 05 Aug 2024 15:12:33 GMT
    ---------------------------------------------------
    
    ALGORAND 👇
    Backfill start time: 1/7/2023
    Daily volume: 2.54 k
    End timestamp: 1722870752 (2024-08-05T15:12:32.000Z)
    
    
    AVAX 👇
    Backfill start time: 1/7/2023
    Daily volume: 19.99 k
    End timestamp: 1722870752 (2024-08-05T15:12:32.000Z)
    
    
    BITCOIN 👇
    Backfill start time: 1/7/2023
    Daily volume: 74.95 k
    End timestamp: 1722870752 (2024-08-05T15:12:32.000Z)
    
    
    ETHEREUM 👇
    Backfill start time: 1/7/2023
    Daily volume: 82.25 k
    End timestamp: 1722870752 (2024-08-05T15:12:32.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 1/7/2023
    Daily volume: 474.93 k
    End timestamp: 1722870752 (2024-08-05T15:12:32.000Z)
    
    
    BSC 👇
    Backfill start time: 1/7/2023
    Daily volume: 0
    End timestamp: 1722870752 (2024-08-05T15:12:32.000Z)
    
    
    SOLANA 👇
    Backfill start time: 1/7/2023
    Daily volume: 6.60 k
    End timestamp: 1722870752 (2024-08-05T15:12:32.000Z)

**Comment by MatHermida** [comment]
Could you please clarify what you mean by "example Txs"? 
Are you referring to blockchain transactions of our trades, or are you asking for a method to verify the authenticity of the volume values? Or something else?

**Comment by dtmkeng** [comment]
> Could you please clarify what you mean by "example Txs"? Are you referring to blockchain transactions of our trades, or are you asking for a method to verify the authenticity of the volume values? Or something else?

on chain txs ?

**Comment by dtmkeng** [comment]
swap volume your count for volume

**Comment by MatHermida** [comment]
In our setup, we aggregate and serve the on-chain transactions information data through our API, as pulling the data directly from the transactions would be quite complex.
All the operations are settled as on-chain transactions on the Algorand blockchain. Our system information can be accessed via this API endpoint: https://api.c3.io/v1/system-info, specially our settlement Algorand contract ("ceOnchain") ID is 1257259627. All related transactions can be viewed on the Pera Wallet Explorer here: https://explorer.perawallet.app/application/1257259627/.
Additionally, each market volume is displayed on the graphs of our trading app, such as on this page: https://c3.io/trade/ETH-USDC.
Please let me know I understood properly your requests or if any further clarification is needed.

**Comment by dtmkeng** [comment]
is it like spot trade ?

**Comment by MatHermida** [comment]
Yes

**Comment by MatHermida** [comment]
Are there any changes I need to make because it's spot trade?

**Comment by dtmkeng** [comment]
seem api it error 504

**Pull request merged**
