### PR TITLE
Listing D2Finance

### PR DESCRIPTION
**Pull request by dunglv-smartosc**

### CODE REVIEW

**Comment by llamatester** [comment]
The d2finance adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees d2finance
    
    🦙 Running D2FINANCE adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 14 Jul 2024 05:22:14 GMT
    End Date:	Mon, 15 Jul 2024 05:22:14 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 20/1/2024
    NO METHODOLOGY SPECIFIED
    Total protocol revenue: 24.83 k
    Total revenue: 24.83 k
    Total fees: 24.83 k
    End timestamp: 1721020933 (2024-07-15T05:22:13.000Z)

**Comment by dtmkeng** [comment]
could you add daily value ?

**Comment by dunglv-smartosc** [comment]
> could you add daily value ?

Our fees are collected at the conclusion of each of our trading epochs. With our model, we don’t collect fees on a daily basis

**Comment by dtmkeng** [comment]
can't list if can't return daily vale

**Comment by llamatester** [comment]
The d2finance adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees d2finance
    
    🦙 Running D2FINANCE adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 18 Jul 2024 06:33:37 GMT
    End Date:	Fri, 19 Jul 2024 06:33:37 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 20/1/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 44
    Daily revenue: 44
    Daily protocol revenue: 44
    Total fees: 25.23 k
    Total revenue: 25.23 k
    Total protocol revenue: 25.23 k
    End timestamp: 1721370816 (2024-07-19T06:33:36.000Z)

**Comment by dunglv-smartosc** [comment]
> can't list if can't return daily vale

I've updated the PR. Pls check it again

**Pull request merged**
