### PR TITLE
feat: Add seiyan-fun dex volume adapter

### PR DESCRIPTION
**Pull request by raspLarry**
- Add Seiyanfun dailyVolume on dex dashboard

### CODE REVIEW

**Comment by llamatester** [comment]
The seiyan-fun adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs seiyan-fun
    
    🦙 Running SEIYAN-FUN adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 15 Aug 2024 00:00:00 GMT
    End Date:	Fri, 16 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 80711999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 80711999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    [Error: Request failed with status code 429] {
      url: 'https://seiyan.fun/api/public/v1/trading-volume?caipChainID=cosmos:sei-pacific-1&startAt=1723680000&endAt=1723766400',
      method: 'GET',
      axiosError: 'Too Many Requests',
      chain: 'sei'
    }

**Comment by raspLarry** [comment]
Our current API rate limit is 2 calls per 10 seconds. Could you please advise on what the appropriate rate limit should be?

**Comment by llamatester** [comment]
The seiyan-fun adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs seiyan-fun
    
    🦙 Running SEIYAN-FUN adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 15 Aug 2024 00:00:00 GMT
    End Date:	Fri, 16 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 80711999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 80711999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    SEI 👇
    Backfill start time: 1/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 1626073513098.36 B
    End timestamp: 1723766399 (2024-08-15T23:59:59.000Z)

**Comment by dtmkeng** [comment]
could you check value seem it not correct ?

**Comment by llamatester** [comment]
The seiyan-fun adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs seiyan-fun
    
    🦙 Running SEIYAN-FUN adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 18 Aug 2024 00:00:00 GMT
    End Date:	Mon, 19 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 95079999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 95079999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    SEI 👇
    Backfill start time: 1/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 796
    End timestamp: 1724025599 (2024-08-18T23:59:59.000Z)

**Comment by raspLarry** [comment]
@dtmkeng 
I’ve fixed the issue! could you check this again?

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Comment by raspLarry** [comment]
@dtmkeng 
no there isnt't.. is it necessary?

**Comment by dtmkeng** [comment]
> @dtmkeng no there isnt't.. is it necessary?

hmm volume is from https://seiyan.fun not from other dexs ?

**Comment by raspLarry** [comment]
@dtmkeng 
yes it's from seiyan.fun

**Pull request merged**
