### PR TITLE
ramses-exchange

### PR DESCRIPTION
**Pull request by 0xShad0w**
Adding V2 here

### CODE REVIEW

**Comment by dtmkeng** [comment]
could you remove `yarn` file  ?

**Comment by llamatester** [comment]
The ramses-exchange.ts adapter exports: 
        
 
 _______________________________________
    Fees for 15/6/2023
    _______________________________________
    
    Version -> V1
    ---------
    ARBITRUM 👇
    Backfill start time: 15/3/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 1432.366800784922
    Daily revenue: 1432.366800784922
    Daily holders revenue: 1432.366800784922
    Timestamp: 1686873599
    
    
    Version -> V2
    ---------
    ARBITRUM 👇
    Backfill start time: 31/5/2023
    Timestamp: 1686873599
    Block: 101576904
    Total volume: 11543719.967509728
    Daily volume: 1445326.484978058077633179674136622
    Daily fees: 1376.342470813592699625606562358793
    Total fees: 13750.226297264266
    Daily holders revenue: 1376.342470813592699625606562358793
    └─ Methodology: User fees are distributed among holders.
    Total holders revenue: 13750.226297264266
    └─ Methodology: User fees are distributed among holders.
    Daily user fees: 1376.342470813592699625606562358793
    └─ Methodology: User pays 0.05%, 0.30%, or 1% on each swap.
    Total user fees: 13750.226297264266
    └─ Methodology: User pays 0.05%, 0.30%, or 1% on each swap.
    Daily revenue: 1376.342470813592699625606562358793
    Total revenue: 13750.226297264266
    
    
    Done in 6.05s.

**Comment by dtmkeng** [comment]
ohh could split file fees/ramses-exchange.ts -> for v1
and fees/ramses-exchange-v2.ts for v2
like https://github.com/DefiLlama/dimension-adapters/blob/master/fees/camelot-v3.ts  ?
because it easy for backfill data

**Comment by llamatester** [comment]
The ramses-exchange.ts adapter exports: 
        
 
 _______________________________________
    Fees for 15/6/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 15/3/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 1432.366800784922
    Daily revenue: 1432.366800784922
    Daily holders revenue: 1432.366800784922
    Timestamp: 1686873598
    
    
    
    
    Done in 10.07s.

**Comment by llamatester** [comment]
The ramses-exchange-v2.ts adapter exports: 
        
 
 _______________________________________
    Fees for 15/6/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 31/5/2023
    Timestamp: 1686873598
    Block: 101576904
    Total volume: 11543719.967509728
    Daily volume: 1445326.484978058077633179674136622
    Daily fees: 1376.342470813592699625606562358793
    Total fees: 13759.723649140298
    Daily holders revenue: 1376.342470813592699625606562358793
    └─ Methodology: User fees are distributed among holders.
    Total holders revenue: 13759.723649140298
    └─ Methodology: User fees are distributed among holders.
    Daily user fees: 1376.342470813592699625606562358793
    └─ Methodology: User pays 0.05%, 0.30%, or 1% on each swap.
    Total user fees: 13759.723649140298
    └─ Methodology: User pays 0.05%, 0.30%, or 1% on each swap.
    Daily revenue: 1376.342470813592699625606562358793
    Total revenue: 13759.723649140298
    
    
    
    
    Done in 4.33s.

**Comment by 0xShad0w** [comment]
Thanks ser @dtmkeng 

Should I take the same approach when doing dexs/ramses-exchange too?

**Comment by dtmkeng** [comment]
> Thanks ser @dtmkeng
> 
> Should I take the same approach when doing dexs/ramses-exchange too?

yeah thank you

**Comment by llamatester** [comment]
The ramses-exchange.ts adapter exports: 
        
 
 _______________________________________
    Fees for 15/6/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 15/3/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 1432.366800784922
    Daily revenue: 1432.366800784922
    Daily holders revenue: 1432.366800784922
    Timestamp: 1686873598
    
    
    
    
    Done in 9.53s.

**Comment by llamatester** [comment]
The ramses-exchange-v2 adapter exports: 
        
 
 _______________________________________
    Dexs for 15/6/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 31/5/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1686873598
    Block: 101576904
    Total volume: 11543719.967509728
    Daily volume: 1445326.484978058077633179674136622
    
    
    
    
    Done in 3.17s.

**Comment by llamatester** [comment]
The ramses-exchange-v2.ts adapter exports: 
        
 
 _______________________________________
    Fees for 15/6/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 31/5/2023
    Timestamp: 1686873598
    Block: 101576904
    Total volume: 11543719.967509728
    Daily volume: 1445326.484978058077633179674136622
    Daily fees: 1376.342470813592699625606562358793
    Total fees: 13837.759333907405
    Daily holders revenue: 1376.342470813592699625606562358793
    └─ Methodology: User fees are distributed among holders.
    Total holders revenue: 13837.759333907405
    └─ Methodology: User fees are distributed among holders.
    Daily user fees: 1376.342470813592699625606562358793
    └─ Methodology: User pays 0.05%, 0.30%, or 1% on each swap.
    Total user fees: 13837.759333907405
    └─ Methodology: User pays 0.05%, 0.30%, or 1% on each swap.
    Daily revenue: 1376.342470813592699625606562358793
    Total revenue: 13837.759333907405
    
    
    
    
    Done in 4.00s.

**Comment by dtmkeng** [comment]
LG thank you

**Pull request merged**
