### PR TITLE
Taker volume correction

### PR DESCRIPTION
**Pull request by lemonpac**

### CODE REVIEW

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    dexs/intent-x/index.tsx(254,3): error TS1005: ',' expected.

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 31 Jul 2024 00:00:00 GMT
    End Date:	Thu, 01 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722384000 (2024-07-31T00:00:00.000Z)
    Daily volume: 1692370306506584.00 B
    Total volume: 3435677162502156800.00 B
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722384000 (2024-07-31T00:00:00.000Z)
    Daily volume: 191479555552000.00 B
    Total volume: 503803936238378624.00 B
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722384000 (2024-07-31T00:00:00.000Z)
    Daily volume: 10672667717065878.00 B
    Total volume: 4433700985517030400.00 B

**Comment by lemonpac** [comment]
IntentX taker volume adjustements to be adjusted to SYMMIO protocol standard

**Comment by dtmkeng** [comment]
value is look sus

**Comment by lemonpac** [comment]
What does it mean?
We are now taking into account maker + taker volume as part of the protocol

**Comment by dtmkeng** [comment]
test result seem value is wrong

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 02 Aug 2024 00:00:00 GMT
    End Date:	Sat, 03 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    TypeError: toString(...).dividedBy is not a function
        at fetchVolumeBlast (/home/runner/work/dimension-adapters/dimension-adapters/dexs/intent-x/index.tsx:214:74)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:44:18)
        at async Promise.all (index 1)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:26:20)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'blast'
    }

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 02 Aug 2024 00:00:00 GMT
    End Date:	Sat, 03 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722556800 (2024-08-02T00:00:00.000Z)
    Daily volume: 1.83 M
    Total volume: 3.44 B
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722556800 (2024-08-02T00:00:00.000Z)
    Daily volume: 14.68 k
    Total volume: 504.00 M
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722556800 (2024-08-02T00:00:00.000Z)
    Daily volume: 13.34 M
    Total volume: 4.46 B

**Comment by lemonpac** [comment]
Decimals addressed! @dtmkeng

**Comment by dtmkeng** [comment]
sorry can't merge i volume should calculate only one side

**Pull request closed without merging**
