### PR TITLE
add sharpe perp, sharpe bridge. sharpe-dex

### PR DESCRIPTION
**Pull request by Anirudha619**
## Sharpe Perp DEX (add this project in perp aggregator)
Sharpe Perp is an omnichain decentralized orderbook perpetual DEX built on Orderly that aims to provide a high-performance, low-latency trading app for traders looking to trade perpetual futures.

Sharpe Perp is a hybrid orderbook model that combines the best features of centralized and decentralized exchanges, allowing Sharpe Perp to offer centralized exchange performance with low latency and concentrated liquidity while providing full transparency of decentralized exchanges and full self-custody of funds.

## Sharpe DEX (add this project in DEXs volume)
Sharpe DEX is a leading decentralized exchange aggregator that leverages the liquidity of various decentralized exchanges and DEX aggregators, such as Paraswap, OpenOcean, 1inch, Uniswap and more.

## Sharpe Bridge  (add this project in Bridge )
Sharpe Cross-chain Swap provides a seamless platform for swapping and bridging crypto across multiple blockchains and protocols. It combines various decentralized exchanges, DEX aggregators and bridges into one interface, offering best price execution for any swap or bridge. Whether you are a seasoned crypto enthusiast or a newcomer, Sharpe Cross-chain Swap simplifies the process of trading across different chains.

### CODE REVIEW

**Comment by llamatester** [comment]
The sharpe-perp adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregator-derivatives sharpe-perp
    
    🦙 Running SHARPE-PERP adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 09 Jul 2024 12:49:51 GMT
    End Date:	Wed, 10 Jul 2024 12:49:51 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 213.81 M
    End timestamp: 1720615790 (2024-07-10T12:49:50.000Z)

**Comment by llamatester** [comment]
The sharpe-dex adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs sharpe-dex
    
    🦙 Running SHARPE-DEX adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 09 Jul 2024 12:50:59 GMT
    End Date:	Wed, 10 Jul 2024 12:50:59 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 67.46 k
    End timestamp: 1720615858 (2024-07-10T12:50:58.000Z)

**Comment by dtmkeng** [comment]
could you add dailyVolume ?

**Comment by Anirudha619** [comment]
> could you add dailyVolume ?

only dailyVolume or total volume is required, right? 

so i think we can simply push it

**Review by dtmkeng — CHANGES_REQUESTED** [review]
it require dailyVolume

**Comment by llamatester** [comment]
The sharpe-perp adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregator-derivatives sharpe-perp
    
    🦙 Running SHARPE-PERP adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 25 Jul 2024 17:52:43 GMT
    End Date:	Fri, 26 Jul 2024 17:52:43 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 279.32 M
    End timestamp: 1722016362 (2024-07-26T17:52:42.000Z)

**Comment by Anirudha619** [comment]
Added the daily volume.

Please also sunset the sharpe magnum product on defillama

**Comment by llamatester** [comment]
The sharpe-perp adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregator-derivatives sharpe-perp
    
    🦙 Running SHARPE-PERP adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 25 Jul 2024 17:53:46 GMT
    End Date:	Fri, 26 Jul 2024 17:53:46 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 279.32 M
    Daily volume: 1.61 M
    End timestamp: 1722016425 (2024-07-26T17:53:45.000Z)

**Comment by llamatester** [comment]
The sharpe-dex adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs sharpe-dex
    
    🦙 Running SHARPE-DEX adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 25 Jul 2024 17:53:48 GMT
    End Date:	Fri, 26 Jul 2024 17:53:48 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 2.64 M
    End timestamp: 1722016427 (2024-07-26T17:53:47.000Z)

**Comment by llamatester** [comment]
The sharpe-dex adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs sharpe-dex
    
    🦙 Running SHARPE-DEX adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 25 Jul 2024 17:54:53 GMT
    End Date:	Fri, 26 Jul 2024 17:54:53 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 2.64 M
    Daily volume: 1.90 M
    End timestamp: 1722016492 (2024-07-26T17:54:52.000Z)

**Comment by dtmkeng** [comment]
is there web site and logo ?

**Comment by Anirudha619** [comment]
> is there web site and logo ?

The main project which is sharpe.ai is already added in defillama.

We just have to update the above  information and Remove the Magnum which is currently live on defillama.

**Comment by Anirudha619** [comment]
Any update on this??

**Comment by realdealshaman** [comment]
Hey @Anirudha619, thanks for the PRs! We've added the new listing for the perp aggregator. However, we don't delist sunsetted projects—we keep them to maintain a historical record of all the projects that have existed

**Pull request merged**
