### PR TITLE
Integration of core markets & IntentX blast

### PR DESCRIPTION
**Pull request by lemonpac**

### CODE REVIEW

**Comment by llamatester** [comment]
The intent-x adapter exports: 
        
 
 _______________________________________
    Dexs for 14/3/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1710374400 (2024-03-14T00:00:00.000Z)
    Daily volume: 50.69 M
    Total volume: 1.11 B
    
    
    
    
    Done in 6.49s.

**Comment by llamatester** [comment]
The core-markets adapter exports: 
        
 
 _______________________________________
    Dexs for 14/3/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 15/3/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1710374400 (2024-03-14T00:00:00.000Z)
    Daily volume: 818.61 k
    Total volume: 2.98 M
    
    
    
    
    Done in 5.16s.

**Comment by llamatester** [comment]
The core-markets adapter exports: 
        
 
 _______________________________________
    Fees for 14/3/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 15/3/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1710374400 (2024-03-14T00:00:00.000Z)
    Daily fees: 253
    Total fees: 926
    Daily user fees: 253
    Daily revenue: 253
    Daily protocol revenue: 0
    Daily holders revenue: 253
    Daily supply side revenue: 0
    Total user fees: 926
    Total revenue: 926
    Total protocol revenue: 0
    Total supply side revenue: 0
    
    
    
    
    Done in 5.57s.

**Comment by dtmkeng** [comment]
@lemonpac  is there detail for list `core-markets` ?

**Pull request merged**
