### PR TITLE
EⅢ : Add Base

### PR DESCRIPTION
**Pull request by ftm1337**

### CODE REVIEW

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    Dexs for 9/8/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 186.62390464952432
    Timestamp: 1691625598
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 69.63636565424352
    Timestamp: 1691625598
    
    
    
    
    Done in 11.43s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 9/8/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    Daily fees: 0.2821473337626009
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 0.2821473337626009
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 0.28210417101717505
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 0.28210417101717505
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 0.28210417101717505
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.00004316274542587317
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1691625598
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    Daily fees: 0.039743609467222454
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 0.039743609467222454
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 0.013825226596598333
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 0.013825226596598333
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 0.013825226596598333
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.02591838287062412
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1691625598
    
    
    
    
    Done in 10.24s.

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    Dexs for 10/8/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 9911.586837817178
    Timestamp: 1691711998
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 14.907826288385097
    Timestamp: 1691711998
    
    
    
    
    Done in 10.06s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 10/8/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    Daily fees: 13.7351665301855
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 13.7351665301855
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 13.579419131749644
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 13.579419131749644
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 13.579419131749644
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.1557473984358566
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1691711998
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    Daily fees: 0.006055687608374712
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 0.006055687608374712
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 0.0012228953031701822
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 0.0012228953031701822
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 0.0012228953031701822
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.00483279230520453
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1691711998
    
    
    
    
    Done in 10.12s.

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    Dexs for 10/8/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 9911.586837817178
    Timestamp: 1691711998
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 14.907826288385097
    Timestamp: 1691711998
    
    
    BASE 👇
    Backfill start time: 9/8/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 11.680989319999998
    Timestamp: 1691711998
    
    
    
    
    Done in 10.07s.

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    Dexs for 10/8/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 9911.586837817178
    Timestamp: 1691711998
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 14.907826288385097
    Timestamp: 1691711998
    
    
    BASE 👇
    Backfill start time: 9/8/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 11.680989319999998
    Timestamp: 1691711998
    
    
    
    
    Done in 13.19s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 10/8/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    Daily fees: 13.7351665301855
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 13.7351665301855
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 13.579419131749644
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 13.579419131749644
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 13.579419131749644
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.1557473984358566
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1691711998
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    Daily fees: 0.006055687608374712
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 0.006055687608374712
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 0.0012228953031701822
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 0.0012228953031701822
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 0.0012228953031701822
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.00483279230520453
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1691711998
    
    
    BASE 👇
    Backfill start time: 9/8/2023
    Daily fees: 0.004687682999999999
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 0.004687682999999999
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 0.004684679999999999
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 0.004684679999999999
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 0.004684679999999999
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.0000030029999999996865
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1691711998
    
    
    
    
    Done in 10.84s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 10/8/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    Daily fees: 13.7351665301855
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 13.7351665301855
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 13.579419131749644
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 13.579419131749644
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 13.579419131749644
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.1557473984358566
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1691711998
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    Daily fees: 0.006055687608374712
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 0.006055687608374712
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 0.0012228953031701822
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 0.0012228953031701822
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 0.0012228953031701822
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.00483279230520453
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1691711998
    
    
    BASE 👇
    Backfill start time: 9/8/2023
    Daily fees: 0.004687682999999999
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 0.004687682999999999
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 0.004684679999999999
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 0.004684679999999999
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 0.004684679999999999
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.0000030029999999996865
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1691711998
    
    
    
    
    Done in 12.79s.

**Comment by ftm1337** [comment]
looks good :+1:

**Pull request merged**
