### PR TITLE
blex add volume and derivatives volume

### PR DESCRIPTION
**Pull request by dalveytech-zero**

### CODE REVIEW

**Comment by llamatester** [comment]
The blex adapter exports: 
        
 
 _______________________________________
    Dexs for 9/10/2023
    _______________________________________
    
    Version -> VOLUME
    ---------
    ARBITRUM 👇
    Backfill start time: 5/8/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1696809600
    Daily volume: 3.1115616965925934e+24
    Total volume: 1.5752974990341515e+26
    
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 5/8/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1696809600
    Daily volume: 3.111561696592593e+24
    Total volume: 1.5752974990341e+26
    
    
    Done in 5.03s.

**Comment by dtmkeng** [comment]
value it should div by .. ?

**Comment by dalveytech-zero** [comment]
yes, I'll modify it

**Comment by dalveytech-zero** [comment]
Please check it

**Comment by dtmkeng** [comment]
value it is okay seem less ?

**Comment by dalveytech-zero** [comment]
If you check it, I seem to be correct. If there are any mistakes, please point them out for me. I will be very grateful.

**Comment by dtmkeng** [comment]
> If you check it, I seem to be correct. If there are any mistakes, please point them out for me. I will be very grateful.

look good
it for this protocol https://defillama.com/protocol/blex ?

**Comment by dalveytech-zero** [comment]
Yes, I am a member of the BLEX team

**Pull request merged**
