### PR TITLE
Add daily volume and fees for StormTrade

### PR DESCRIPTION
**Pull request by shuva10v**
Here is volume and fees data for the [StormTrade](https://defillama.com/protocol/storm-trade) project on TON blockchain. Data collected using [re:doubt](https://beta.redoubt.online/) analytical platform, references:
* [Smart-contracts specification](https://github.com/Tsunami-Exchange/storm-contracts-specs/tree/main)
* [Data parsers](https://github.com/re-doubt/ton-indexer/pull/28/files)
* [Live dashboard](https://tonalytica.redoubt.online/public/dashboards/yLrq2MRoaaPfhoaI9eJngVGcc9HBPiOcSBqSrE7H?org_slug=default) with the current metrics

### CODE REVIEW

**Comment by llamatester** [comment]
The stormtrade adapter exports: 
        
 
 _______________________________________
    Dexs for 4/12/2023
    _______________________________________
    
    TON 👇
    Backfill start time: 14/11/2023
    Daily volume: {
      "tether": 331129.73
    }
    Timestamp: 1701756300
    
    
    
    
    Done in 2.65s.

**Comment by llamatester** [comment]
The stormtrade adapter exports: 
        
 
 _______________________________________
    Fees for 4/12/2023
    _______________________________________
    
    TON 👇
    Backfill start time: 14/11/2023
    Daily user fees: {
      "tether": 397.72
    }
    Timestamp: 1701756300
    
    
    
    
    Done in 2.49s.

**Comment by dtmkeng** [comment]
if use token breakdown response should use `chain:token_address` or if token price if alivable on llama endpoint you can return unit of usd `dailyFees`: '10' , `dailyVolume`: '100'
and could you fix fees  should set dailyFees is equal dailyUserFees 
thx

**Comment by llamatester** [comment]
The stormtrade adapter exports: 
        
 
 _______________________________________
    Dexs for 4/12/2023
    _______________________________________
    
    TON 👇
    Backfill start time: 14/11/2023
    Daily volume: 339313.74
    Timestamp: 1701767100
    
    
    
    
    Done in 2.99s.

**Comment by llamatester** [comment]
The stormtrade adapter exports: 
        
 
 _______________________________________
    Fees for 4/12/2023
    _______________________________________
    
    TON 👇
    Backfill start time: 14/11/2023
    Daily user fees: 407.54
    Daily fees: 407.54
    └─ Methodology: Traders pay opening and closing fees
    Timestamp: 1701767100
    
    
    
    
    Done in 2.74s.

**Comment by shuva10v** [comment]
@dtmkeng Fixed!

**Pull request merged**
