### PR TITLE
feat: hercules data

### PR DESCRIPTION
**Pull request by waliair**

### CODE REVIEW

**Comment by llamatester** [comment]
The hercules-v3 adapter exports: 
        
 
 _______________________________________
    Dexs for 24/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 3/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1713982592 (2024-04-24T18:16:32.000Z)
    Block: 16.78 M
    Total volume: 66.74 M
    Daily volume: 1.58 M
    
    
    
    
    Done in 7.78s.

**Comment by llamatester** [comment]
The hercules adapter exports: 
        
 
 _______________________________________
    Dexs for 24/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 23/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1713982600 (2024-04-24T18:16:40.000Z)
    Block: 16.78 M
    Total volume: 403.41 k
    Daily volume: 12.43 k
    
    
    
    
    Done in 7.06s.

**Comment by llamatester** [comment]
The hercules-v2.ts adapter exports: 
        
 
 _______________________________________
    Fees for 23/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 23/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1713916799 (2024-04-23T23:59:59.000Z)
    Daily fees: 26
    Daily user fees: 26
    Daily revenue: 10
    Daily protocol revenue: 1
    Daily holders revenue: 9
    Daily supply side revenue: 16
    
    
    
    
    Done in 6.42s.

**Comment by llamatester** [comment]
The hercules-v3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 23/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 3/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1713916799 (2024-04-23T23:59:59.000Z)
    Daily fees: 6.32 k
    Daily user fees: 6.32 k
    Daily revenue: 948
    Daily protocol revenue: 190
    Daily holders revenue: 758
    Daily supply side revenue: 5.37 k
    
    
    
    
    Done in 5.38s.

**Comment by llamatester** [comment]
The hercules-v3 adapter exports: 
        
 
 _______________________________________
    Dexs for 24/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 3/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1713983101 (2024-04-24T18:25:01.000Z)
    Block: 16.78 M
    Total volume: 66.74 M
    Daily volume: 1.58 M
    
    
    
    
    Done in 6.82s.

**Comment by llamatester** [comment]
The hercules adapter exports: 
        
 
 _______________________________________
    Dexs for 24/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 23/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1713983108 (2024-04-24T18:25:08.000Z)
    Block: 16.78 M
    Total volume: 403.41 k
    Daily volume: 12.43 k
    
    
    
    
    Done in 5.18s.

**Comment by llamatester** [comment]
The hercules-v2.ts adapter exports: 
        
 
 _______________________________________
    Fees for 23/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 23/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1713916799 (2024-04-23T23:59:59.000Z)
    Daily fees: 26
    Daily user fees: 26
    Daily revenue: 10
    Daily protocol revenue: 1
    Daily holders revenue: 9
    Daily supply side revenue: 16
    
    
    
    
    Done in 5.71s.

**Comment by llamatester** [comment]
The hercules-v3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 23/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 3/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1713916799 (2024-04-23T23:59:59.000Z)
    Daily fees: 6.32 k
    Daily user fees: 6.32 k
    Daily revenue: 948
    Daily protocol revenue: 190
    Daily holders revenue: 758
    Daily supply side revenue: 5.37 k
    
    
    
    
    Done in 3.91s.

**Comment by waliair** [comment]
for now: we need to update our list, so closed, it will be re-open soon.

**Pull request closed without merging**
