### PR TITLE
Add hydradex

### PR DESCRIPTION
**Pull request by ipetrov22**

### CODE REVIEW

**Comment by llamatester** [comment]
The hydradex adapter exports: 
        
 
 _______________________________________
    Dexs for 23/4/2023
    _______________________________________
    
    Version -> V2
    ---------
    HYDRA 👇
    Backfill start time: 4/8/2021
    Timestamp: 1682294399
    Block: 960723
    Total volume: 15945940.937826226
    Daily volume: 590.773179202763219546
    Daily fees: 1.772319537608289658638
    Total fees: 47837.822813478678
    Daily user fees: 1.772319537608289658638
    └─ Methodology: User pays 0.3% fees on each swap.
    Total user fees: 47837.822813478678
    └─ Methodology: User pays 0.3% fees on each swap.
    Daily protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Total protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Daily supply side revenue: 1.772319537608289658638
    └─ Methodology: All user fees are distributed among LPs.
    Total supply side revenue: 47837.822813478678
    └─ Methodology: All user fees are distributed among LPs.
    Daily holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Total holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Daily revenue: 0
    Total revenue: 0
    
    
    Version -> V3
    ---------
    HYDRA 👇
    Backfill start time: 21/3/2023
    Timestamp: 1682294399
    Block: 960725
    Total volume: 1360329.9193031243
    Daily volume: 30112.53596774746962631679386442589
    Daily fees: 90.33760790324240887895038159327761
    Total fees: 3686.4808179302277
    Daily protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Total protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Daily holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Total holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Daily user fees: 90.33760790324240887895038159327761
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Total user fees: 3686.4808179302277
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Daily supply side revenue: 90.33760790324240887895038159327761
    └─ Methodology: All user fees are distributed among LPs.
    Total supply side revenue: 3686.4808179302277
    └─ Methodology: All user fees are distributed among LPs.
    Daily revenue: 0
    Total revenue: 0
    
    
    Done in 5.13s.

**Comment by dtmkeng** [comment]
hi, thx for pr have question why you not use function `getGraphDimensions` at helpers/getUniSubgraph instead you create new function

**Comment by ipetrov22** [comment]
@dtmkeng Hi! There was a small difference in one of the queries and I didn't want to put custom logic in the `getUniSubgraph` helper, so instead I recreated it for our needs. Also this way we are sure that if there are eventually  changes to the `getUniSubgraph` we won't be affected.

**Comment by ipetrov22** [comment]
> > @dtmkeng Hi! There was a small difference in one of the queries and I didn't want to put custom logic in the `getUniSubgraph` helper, so instead I recreated it for our needs. Also this way we are sure that if there are eventually changes to the `getUniSubgraph` we won't be affected.
> 
> could you explain which point it difference?

In this query the V2 graph is set to use `Float!` type for the block number for some reason and I added a check to change that type

```shell 
// Queries
// check if it's v2 graph and change the block number type
const totalVolumeQuery = gql`
query total_volume ($block: ${graphFieldsTotalVolume.factory.includes('hydraswap') ? 'Float!' : 'Int'}) {
  ${graphFieldsTotalVolume.factory}(block: { number: $block }) {
    ${graphFieldsTotalVolume.field}
  }
}`;
```

**Comment by llamatester** [comment]
The hydradex adapter exports: 
        
 
 _______________________________________
    Dexs for 23/4/2023
    _______________________________________
    
    Version -> V2
    ---------
    HYDRA 👇
    Backfill start time: 4/8/2021
    Timestamp: 1682294399
    Block: 961446
    Total volume: 15947362.44184701
    Daily volume: 590.773179202763219546
    Daily fees: 1.772319537608289658638
    Total fees: 47842.08732554103
    Daily user fees: 1.772319537608289658638
    └─ Methodology: User pays 0.3% fees on each swap.
    Total user fees: 47842.08732554103
    └─ Methodology: User pays 0.3% fees on each swap.
    Daily protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Total protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Daily supply side revenue: 1.772319537608289658638
    └─ Methodology: All user fees are distributed among LPs.
    Total supply side revenue: 47842.08732554103
    └─ Methodology: All user fees are distributed among LPs.
    Daily holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Total holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Daily revenue: 0
    Total revenue: 0
    
    
    Version -> V3
    ---------
    HYDRA 👇
    Backfill start time: 21/3/2023
    Timestamp: 1682294399
    Block: 960729
    Total volume: 1360329.9193031243
    Daily volume: 30112.53596774746962631679386442589
    Daily fees: 90.33760790324240887895038159327761
    Total fees: 3686.4808179302277
    Daily protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Total protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Daily holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Total holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Daily user fees: 90.33760790324240887895038159327761
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Total user fees: 3686.4808179302277
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Daily supply side revenue: 90.33760790324240887895038159327761
    └─ Methodology: All user fees are distributed among LPs.
    Total supply side revenue: 3686.4808179302277
    └─ Methodology: All user fees are distributed among LPs.
    Daily revenue: 0
    Total revenue: 0
    
    
    Done in 5.78s.

**Comment by 0xtawa** [comment]
Hi @ipetrov22, Ive added a commit adding some parameters to customize the type on the query, in the end 99% of the code is shared and all uni-like dexes rely on that helper so we take care of maintaining it and making sure no changes affect the adapters using it. Also using the helper will have the benefit of instant updates in case we start tracking other parameters in the subgraph or if any fix is needed.

Adapter looks good only thing needed is to use the parameter `timestamp` in the get custom block functions. This way we can do an accurate backfill of data.

`getCustomBlock: ((timestamp: number) => Promise<number>)`.

After that change will proceed to list 🚀

**Comment by llamatester** [comment]
The hydradex adapter exports: 
        
 
 _______________________________________
    Dexs for 23/4/2023
    _______________________________________
    
    Version -> V2
    ---------
    HYDRA 👇
    Backfill start time: 4/8/2021
    Timestamp: 1682294399
    Block: 959530
    Total volume: 15947362.44184701
    Daily volume: 590.773179202763219546
    Daily fees: 1.772319537608289658638
    Total fees: 47842.08732554103
    Daily user fees: 1.772319537608289658638
    └─ Methodology: User pays 0.3% fees on each swap.
    Total user fees: 47842.08732554103
    └─ Methodology: User pays 0.3% fees on each swap.
    Daily protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Total protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Daily supply side revenue: 1.772319537608289658638
    └─ Methodology: All user fees are distributed among LPs.
    Total supply side revenue: 47842.08732554103
    └─ Methodology: All user fees are distributed among LPs.
    Daily holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Total holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Daily revenue: 0
    Total revenue: 0
    
    
    Version -> V3
    ---------
    HYDRA 👇
    Backfill start time: 21/3/2023
    Timestamp: 1682294399
    Block: 959530
    Total volume: 1354159.6115206643
    Daily volume: 30112.53596774746962631679386442589
    Daily fees: 90.33760790324240887895038159327761
    Total fees: 3688.16625696462
    Daily protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Total protocol revenue: 0
    └─ Methodology: Protocol have no revenue.
    Daily holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Total holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Daily user fees: 90.33760790324240887895038159327761
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Total user fees: 3688.16625696462
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Daily supply side revenue: 90.33760790324240887895038159327761
    └─ Methodology: All user fees are distributed among LPs.
    Total supply side revenue: 3688.16625696462
    └─ Methodology: All user fees are distributed among LPs.
    Daily revenue: 0
    Total revenue: 0
    
    
    Done in 6.55s.

**Comment by ipetrov22** [comment]
@0xtawa Thank you for the feedback and assistance! I've added the `timestamp` option. Let me know if there is anything else that needs to be done.

**Pull request merged**
