### PR TITLE
Add Marinade fees adapter

### PR DESCRIPTION
**Pull request by martinkrecek**

### CODE REVIEW

**Comment by llamatester** [comment]
The marinade adapter exports: 
        
 
 _______________________________________
    Fees for 18/2/2024
    _______________________________________
    
    SOLANA 👇
    Backfill start time: 12/7/2023
    Timestamp: 1708345427.696 (2024-02-19T12:23:47.696Z)
    Total fees: 22.65 M
    └─ Methodology: Staking rewards
    Daily fees: 208.29 k
    └─ Methodology: Staking rewards
    Daily user fees: 7.51 k
    └─ Methodology: Marinade management fee 6% on staking rewards
    Total revenue: 855.36 k
    └─ Methodology:  = ProtocolRevenue
    Daily revenue: 7.51 k
    └─ Methodology:  = ProtocolRevenue
    Daily protocol revenue: 7.51 k
    └─ Methodology:  = UserFees
    Daily supply side revenue: 200.78 k
    └─ Methodology: Stakers revenue = Fees - UserFees
    Total protocol revenue: 855.36 k
    └─ Methodology:  = UserFees
    Total supply side revenue: 21.80 M
    └─ Methodology: Stakers revenue = Fees - UserFees
    Total user fees: 855.36 k
    └─ Methodology: Marinade management fee 6% on staking rewards
    
    
    
    
    Done in 7.88s.

**Comment by martinkrecek** [comment]
> @martinkrecek value above is for `marinade-liquid-staking` or `native` ?

It's for both, summed together.

**Comment by dtmkeng** [comment]
> > @martinkrecek value above is for `marinade-liquid-staking` or `native` ?
> 
> It's for both, summed together.

we. can't list both from 1 adapter if you need list for both should create 2 adapter and filter value type

**Comment by martinkrecek** [comment]
> > > @martinkrecek value above is for `marinade-liquid-staking` or `native` ?
> > 
> > 
> > It's for both, summed together.
> 
> we. can't list both from 1 adapter if you need list for both should create 2 adapter and filter value type

That's exactly what I was trying to clarify [on Discord](https://discord.com/channels/823822164956151810/823885412425793587/1205539325157310505) before submitting this, so could you please confirm whether there are any other requirements for this?

Do the slugs really not matter, or is that not the case and they should match? How are you then linking the fees (or other dimensions) to the if not by the slug, purely manually, based on some internal identifiers? Is there any other update needed in the implementation than splitting it into two parts?

To avoid going back and forth, I'm optimistically adding a list of steps which I'll take unless I learn about some additional requirement or limitation, please confirm or correct me on these.
- Remove the current implementation from `fees/marinade/index.ts`.
- Add a similar implementation to `fees/marinade-liquid-staking/index.ts` (slugs might not need to match, but doesn't matter actually), but returning numbers for our *liquid product only*.
- Add a similar implementation to `fees/marinade-native/index.ts` (slugs might not need to match, but doesn't matter actually), but returning numbers for our *native product only*.

**Comment by dtmkeng** [comment]
> > > > @martinkrecek value above is for `marinade-liquid-staking` or `native` ?
> > > 
> > > 
> > > It's for both, summed together.
> > 
> > 
> > we. can't list both from 1 adapter if you need list for both should create 2 adapter and filter value type
> 
> That's exactly what I was trying to clarify [on Discord](https://discord.com/channels/823822164956151810/823885412425793587/1205539325157310505) before submitting this, so could you please confirm whether there are any other requirements for this?
> 
> Do the slugs really not matter, or is that not the case and they should match? How are you then linking the fees (or other dimensions) to the if not by the slug, purely manually, based on some internal identifiers? Is there any other update needed in the implementation than splitting it into two parts?
> 
> To avoid going back and forth, I'm optimistically adding a list of steps which I'll take unless I learn about some additional requirement or limitation, please confirm or correct me on these.
> 
> * Remove the current implementation from `fees/marinade/index.ts`.
> * Add a similar implementation to `fees/marinade-liquid-staking/index.ts` (slugs might not need to match, but doesn't matter actually), but returning numbers for our _liquid product only_.
> * Add a similar implementation to `fees/marinade-native/index.ts` (slugs might not need to match, but doesn't matter actually), but returning numbers for our _native product only_.

yes it is correct for create `marinade-liquid-staking` and `marinade-native`

**Comment by llamatester** [comment]
The marinade-liquid-staking adapter exports: 
        
 
 _______________________________________
    Fees for 19/2/2024
    _______________________________________
    
    SOLANA 👇
    Backfill start time: 12/7/2023
    Timestamp: 1708436617.878 (2024-02-20T13:43:37.878Z)
    Total fees: 14.26 M
    └─ Methodology: Staking rewards
    Daily fees: 122.99 k
    └─ Methodology: Staking rewards
    Daily user fees: 7.38 k
    └─ Methodology: Marinade management fee 6% on staking rewards
    Total revenue: 855.70 k
    └─ Methodology:  = ProtocolRevenue
    Daily revenue: 7.38 k
    └─ Methodology:  = ProtocolRevenue
    Daily protocol revenue: 7.38 k
    └─ Methodology:  = UserFees
    Daily supply side revenue: 115.61 k
    └─ Methodology: Stakers revenue = Fees - UserFees
    Total protocol revenue: 855.70 k
    └─ Methodology:  = UserFees
    Total supply side revenue: 13.41 M
    └─ Methodology: Stakers revenue = Fees - UserFees
    Total user fees: 855.70 k
    └─ Methodology: Marinade management fee 6% on staking rewards
    
    
    
    
    Done in 6.89s.

**Comment by llamatester** [comment]
The marinade-native adapter exports: 
        
 
 _______________________________________
    Fees for 19/2/2024
    _______________________________________
    
    SOLANA 👇
    Backfill start time: 12/7/2023
    Timestamp: 1708436624.698 (2024-02-20T13:43:44.698Z)
    Total fees: 8.41 M
    └─ Methodology: Staking rewards
    Daily fees: 81.54 k
    └─ Methodology: Staking rewards
    Daily user fees: 0
    └─ Methodology: No Marinade fees in native staking
    Total revenue: 0
    └─ Methodology:  = ProtocolRevenue
    Daily revenue: 0
    └─ Methodology:  = ProtocolRevenue
    Daily protocol revenue: 0
    └─ Methodology:  = UserFees
    Daily supply side revenue: 81.54 k
    └─ Methodology: Stakers revenue = Fees
    Total protocol revenue: 0
    └─ Methodology:  = UserFees
    Total supply side revenue: 8.41 M
    └─ Methodology: Stakers revenue = Fees
    Total user fees: 0
    └─ Methodology: No Marinade fees in native staking
    
    
    
    
    Done in 5.89s.

**Pull request merged**
