### PR TITLE
feat: primex adapter

### PR DESCRIPTION
**Pull request by TbIKoBKa**

### CODE REVIEW

**Comment by llamatester** [comment]
The primex-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 19/10/2023
    _______________________________________
    
    
    
    Done in 3.34s.

**Comment by TbIKoBKa** [comment]
start date is 19/10/2023, but no volume results
if set to 18/10/2023 everything works fine

**Comment by dtmkeng** [comment]
yeah we collect yesterday's data if start time = yesterday's date is not the result

**Comment by TbIKoBKa** [comment]
@dtmkeng so can we merge adapter with yesterday's date or wait until tomorrow?

**Comment by dtmkeng** [comment]
we can merge today if you okay about result data, could you set start time  18/10/2023 for check result data ?

**Comment by llamatester** [comment]
The primex-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 19/10/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 18/10/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 21476.631201253727
    Timestamp: 1697759998
    
    
    
    
    Done in 16.43s.

**Comment by TbIKoBKa** [comment]
@dtmkeng done

**Comment by llamatester** [comment]
The primex-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 19/10/2023
    _______________________________________
    
    
    
    Done in 3.44s.

**Comment by dtmkeng** [comment]
this value `1697587200`

**Comment by llamatester** [comment]
The primex-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 19/10/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 18/10/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 21476.631201253727
    Timestamp: 1697759998
    
    
    
    
    Done in 12.90s.

**Comment by TbIKoBKa** [comment]
@dtmkeng yep, but the final start date should be 19/10/2023

**Pull request merged**
