### PR TITLE
add fwx dexs adapter

### PR DESCRIPTION
**Pull request by idea2409**

### CODE REVIEW

**Comment by llamatester** [comment]
The fwx adapter exports: 
        
 
 _______________________________________
    Fees for 15/1/2024
    _______________________________________
    
    AVAX 👇
    Backfill start time: 7/12/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 0.04926229144
    Daily revenue: 0.0002927644636
    Daily protocol revenue: 0.0002927644636
    Daily holders revenue: 0.0026348801724
    Total fees: 197.10 k
    Timestamp: 1705363198
    
    
    
    
    Done in 3.61s.

**Comment by dtmkeng** [comment]
is it spot volume or derivatives volume ?

**Comment by idea2409** [comment]
Derivatives volume

**Comment by llamatester** [comment]
The fwx adapter exports: 
        
 
 _______________________________________
    Dexs for 16/1/2024
    _______________________________________
    
    AVAX 👇
    Backfill start time: 7/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 484.835508
    Daily open interest: 6.21 k
    Timestamp: 1705449598
    
    
    
    
    Done in 3.92s.

**Pull request merged**
