### PR TITLE
SynFutures V3: Fees

### PR DESCRIPTION
**Pull request by fan3cn**
SynFutures V3: Fees paid by takers on Blast

### CODE REVIEW

**Comment by llamatester** [comment]
The synfutures-v3 adapter exports: 
        
 
 _______________________________________
    Fees for 17/4/2024
    _______________________________________
    
    BLAST 👇
    Backfill start time: 27/2/2024
    Daily fees: 414.94 k
    └─ Methodology: Fees paid by takers
    Total fees: 7.32 M
    └─ Methodology: Fees paid by takers
    Timestamp: 1713332354 (2024-04-17T05:39:14.000Z)
    
    
    
    
    Done in 65.42s.

**Comment by dtmkeng** [comment]
how you cal ` takerFee` and `protocolFee` ?

**Comment by fan3cn** [comment]
> how you cal ` takerFee` and `protocolFee` ?

TakerFee is equal to the trading volume multiplied by the TradeFeeRatio. TradeFeeRatio here is not fixed; for the majority of trades, it is 0.01%. However, for some trades, this value can vary and may be greater than 0.01%. protocolFee is equal to the trading volume multiplied by the ProtocolFeeRatio. The ProtocolFeeRatio for each pair is fixed but may vary between different pairs. For example, for mainstream trading pairs, this value is generally 0.02%, while for some long-tailed tokens, this value may be 0.5%.

**Comment by dtmkeng** [comment]
why value is high ?
is it wash-trade ?

**Comment by fan3cn** [comment]
> why value is high ? is it wash-trade ?

The value is high because of high trading volume, we have campaigns incentivize users to trade to earn Odyssey points.

**Comment by fan3cn** [comment]
> could you cal only taker and maker fees, protocol fees is part from maker and taker fees

Hi, we decided to show more fees: taker/maker fees, LP fees and protocol fees.

**Comment by llamatester** [comment]
The synfutures-v3 adapter exports: 
        
 
 _______________________________________
    Fees for 22/4/2024
    _______________________________________
    
    BLAST 👇
    Backfill start time: 27/2/2024
    Daily fees: 251.50 k
    └─ Methodology: Fees paid by takers
    Total fees: 9.17 M
    └─ Methodology: Fees paid by takers
    Timestamp: 1713754841 (2024-04-22T03:00:41.000Z)
    
    
    
    
    Done in 67.87s.

**Comment by llamatester** [comment]
The synfutures-v3 adapter exports: 
        
 
 _______________________________________
    Fees for 22/4/2024
    _______________________________________
    
    BLAST 👇
    Backfill start time: 27/2/2024
    Daily fees: 253.84 k
    └─ Methodology: Fees paid by takers
    Total fees: 9.25 M
    └─ Methodology: Fees paid by takers
    Timestamp: 1713756182 (2024-04-22T03:23:02.000Z)
    
    
    
    
    Done in 66.07s.

**Comment by fan3cn** [comment]
Hi, the latest PR has been re-submitted: https://github.com/DefiLlama/dimension-adapters/pull/1432

**Pull request closed without merging**
