### PR TITLE
Add stride fees adapter

### PR DESCRIPTION
**Pull request by srph**

### CODE REVIEW

**Comment by llamatester** [comment]
The stride.ts adapter exports: 
        
 
 _______________________________________
    Fees for 17/1/2023
    _______________________________________
    
    COSMOS 👇
    Backfill start time: 1/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1673999998
    Daily fees: 326.9599075963255
    
    
    OSMOSIS 👇
    Backfill start time: 1/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1673999998
    Daily fees: 80.8399039205896
    
    
    JUNO 👇
    Backfill start time: 1/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1673999998
    Daily fees: 13.287373291132173
    
    
    STARGAZE 👇
    Backfill start time: 1/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1673999998
    Daily fees: 17.07626520977568
    
    
    
    
    Done in 3.98s.

**Comment by riley-stride** [comment]
Stride collects a 10% fee on liquid staked asset staking yield. You can read more about that [here](https://stride.zone/blog/stride-tokenomics). This PR measures those fees across Stride's LSD tokens' yields and converts them to USD terms.

**Comment by llamatester** [comment]
The stride.ts adapter exports: 
        
 
 _______________________________________
    Fees for 17/1/2023
    _______________________________________
    
    COSMOS 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 326.9599075963255
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield.
    
    
    OSMOSIS 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 80.8399039205896
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield.
    
    
    JUNO 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 13.287373291132173
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield.
    
    
    STARGAZE 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 17.07626520977568
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield.
    
    
    
    
    Done in 5.24s.

**Comment by llamatester** [comment]
The stride.ts adapter exports: 
        
 
 _______________________________________
    Fees for 17/1/2023
    _______________________________________
    
    COSMOS 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 326.9599075963255
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield. This fee is measured across Stride's LSD tokens' yields and converts them to USD terms.
    
    
    OSMOSIS 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 80.8399039205896
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield. This fee is measured across Stride's LSD tokens' yields and converts them to USD terms.
    
    
    JUNO 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 13.287373291132173
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield. This fee is measured across Stride's LSD tokens' yields and converts them to USD terms.
    
    
    STARGAZE 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 17.07626520977568
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield. This fee is measured across Stride's LSD tokens' yields and converts them to USD terms.
    
    
    
    
    Done in 5.04s.

**Comment by llamatester** [comment]
The stride.ts adapter exports: 
        
 
 _______________________________________
    Fees for 17/1/2023
    _______________________________________
    
    COSMOS 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 326.9599075963255
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield. These fees are measured across Stride's LSD tokens' yields and converts them to USD terms.
    
    
    OSMOSIS 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 80.8399039205896
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield. These fees are measured across Stride's LSD tokens' yields and converts them to USD terms.
    
    
    JUNO 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 13.287373291132173
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield. These fees are measured across Stride's LSD tokens' yields and converts them to USD terms.
    
    
    STARGAZE 👇
    Backfill start time: 1/1/1970
    Timestamp: 1673999998
    Daily fees: 17.07626520977568
    └─ Methodology: Stride collects a 10% fee on liquid staked asset staking yield. These fees are measured across Stride's LSD tokens' yields and converts them to USD terms.
    
    
    
    
    Done in 4.52s.

**Pull request merged**
