### PR TITLE
add totalPremiumVolume

### PR DESCRIPTION
**Pull request by DIO1009**

### CODE REVIEW

**Comment by llamatester** [comment]
The equation adapter exports: 
        
 
 _______________________________________
    Dexs for 13/11/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 20/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699833600
    Daily volume: 9426733.241004
    Total volume: 210506080.537686
    Total premium volume: 210506080.537686
    Total notional volume: 210506080.537686
    Daily premium volume: 9426733.241004
    Daily notional volume: 9426733.241004
    
    
    
    
    Done in 3.74s.

**Comment by dtmkeng** [comment]
it is value of options volume or derivatives volume ?

**Comment by dtmkeng** [comment]
> image
> How can I display the volume on the interface instead of the derivatives volume? I've already written algorithms for dailyVolume and totalVolume in the code, but why are they being recorded under derivatives

your volume is include swap volume ?

**Comment by dtmkeng** [comment]
> > > image
> > > How can I display the volume on the interface instead of the derivatives volume? I've already written algorithms for dailyVolume and totalVolume in the code, but why are they being recorded under derivatives
> > 
> > 
> > your volume is include swap volume ?
> > The transaction volume does not include swap, it is all the transaction volume within the protocol.

yeah volume is for swap volume direct to lp like uniswap

**Comment by dtmkeng** [comment]
> > > > > image
> > > > > How can I display the volume on the interface instead of the derivatives volume? I've already written algorithms for dailyVolume and totalVolume in the code, but why are they being recorded under derivatives
> > > > 
> > > > 
> > > > your volume is include swap volume ?
> > > > The transaction volume does not include swap, it is all the transaction volume within the protocol.
> > 
> > 
> > yeah volume is for swap volume direct to lp like uniswap
> > Do I need to provide the volume data or is there another data source? If I provide it, how should I organize the data?

yeah if you have other volume like swap (direct in your lp) and option you can create adapter for swap volume and options

**Pull request closed without merging**
