### PR TITLE
feat:Adapter, Usual (fees)

### PR DESCRIPTION
**Pull request by 0xpeluche**
> These are data retrieved from Dune, which count the accumulated revenue in Usual's treasury. However, I haven't been able to determine the percentage of fees that the treasury takes as protocol revenue

image

### CODE REVIEW

**Comment by llamatester** [comment]
The usual adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees usual
    
    🦙 Running USUAL adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 26 Aug 2024 00:00:00 GMT
    End Date:	Tue, 27 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/3868036/results',
      method: 'GET',
      axiosError: 'invalid API Key',
      chain: 'ethereum'
    }

**Comment by llamatester** [comment]
The usual adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees usual
    
    🦙 Running USUAL adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 26 Aug 2024 00:00:00 GMT
    End Date:	Tue, 27 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/3868036/results',
      method: 'GET',
      axiosError: 'invalid API Key',
      chain: 'ethereum'
    }

**Comment by llamatester** [comment]
The usual adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees usual
    
    🦙 Running USUAL adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 26 Aug 2024 00:00:00 GMT
    End Date:	Tue, 27 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/3868036/results',
      method: 'GET',
      axiosError: 'invalid API Key',
      chain: 'ethereum'
    }

**Comment by dtmkeng** [comment]
is there dailyFees ?

**Pull request closed without merging**
