### PR TITLE
feat: add scallop aggregator adapter

### PR DESCRIPTION
**Pull request by nicetomeetyou1**

### CODE REVIEW

**Comment by llamatester** [comment]
The scallop adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators scallop
    
    🦙 Running SCALLOP adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 28 Aug 2024 15:01:25 GMT
    End Date:	Thu, 29 Aug 2024 15:01:25 GMT
    ---------------------------------------------------
    
    SUI 👇
    Backfill start time: 5/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 2.28 M
    End timestamp: 1724943684 (2024-08-29T15:01:24.000Z)

**Comment by dtmkeng** [comment]
is there details for list ?

**Comment by nicetomeetyou1** [comment]
Could you elaborate on what kind of list you mean?

**Comment by dtmkeng** [comment]
details for show on our web about scallop aggregator

**Comment by nicetomeetyou1** [comment]
Information: An Aggregator of Aggregators built on Sui
Website: https://scallop.io/
Twitter: https://x.com/Scallop_io

**Comment by nicetomeetyou1** [comment]
@dtmkeng Any updates on this PR?

**Pull request merged**
