### PR TITLE
adding start and end timestamps as suggested from defilama

### PR DESCRIPTION
**Pull request by Dav0808**
API is working now. could you check this pr - that it works properly?

### CODE REVIEW

**Comment by llamatester** [comment]
The hinkal adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs hinkal
    
    🦙 Running HINKAL adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 02 Oct 2024 12:41:25 GMT
    End Date:	Thu, 03 Oct 2024 12:41:25 GMT
    ---------------------------------------------------
    
    {
      options: {
        createBalances: [Function: createBalances],
        getBlock: [AsyncFunction: getBlock],
        toTimestamp: 1727959284,
        fromTimestamp: 1727872884,
        getFromBlock: [AsyncFunction: getFromBlock],
        getToBlock: [AsyncFunction: getToBlock],
        getLogs: [AsyncFunction: getLogs],
        chain: 'ethereum',
        fromApi: <ref *1> ChainApi {
          block: 20877880,
          chain: 'ethereum',
          timestamp: 1727872884,
          provider: [LlamaProvider],
          _balances: [Balances],
          chainId: 1,
          storedKey: undefined,
          api: [Circular *1]
        },
        toApi: <ref *2> ChainApi {
          block: 20885051,
          chain: 'ethereum',
          timestamp: undefined,
          provider: [LlamaProvider],
          _balances: [Balances],
          chainId: 1,
          storedKey: undefined,
          api: [Circular *2]
        },
        api: <ref *2> ChainApi {
          block: 20885051,
          chain: 'ethereum',
          timestamp: undefined,
          provider: [LlamaProvider],
          _balances: [Balances],
          chainId: 1,
          storedKey: undefined,
          api: [Circular *2]
        },
        startOfDay: 1727913600,
        startTimestamp: 1727872884,
        endTimestamp: 1727959285,
        getStartBlock: [AsyncFunction: getFromBlock],
        getEndBlock: [AsyncFunction: getToBlock]
      }
    }
    Error: "timestampStart" is not a supported metric.Supported metrics can be found in adapters/types.ts
        at /home/runner/work/dimension-adapters/dimension-adapters/cli/utils.ts:30:19
        at Array.forEach (<anonymous>)
        at printVolumes (/home/runner/work/dimension-adapters/dimension-adapters/cli/utils.ts:28:10)
        at /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:78:17
        at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by llamatester** [comment]
The hinkal adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs hinkal
    
    🦙 Running HINKAL adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 02 Oct 2024 12:49:31 GMT
    End Date:	Thu, 03 Oct 2024 12:49:31 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1727959770 (2024-10-03T12:49:30.000Z)
    Daily volume: 115.94 M
    
    
    BASE 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1727959770 (2024-10-03T12:49:30.000Z)
    Daily volume: 10.35 M
    
    
    ARBITRUM 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1727959770 (2024-10-03T12:49:30.000Z)
    Daily volume: 8.57 M
    
    
    POLYGON 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1727959770 (2024-10-03T12:49:30.000Z)
    Daily volume: 755.08 k
    
    
    BSC 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1727959770 (2024-10-03T12:49:30.000Z)
    Daily volume: 235.95 k
    
    
    AVAX 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1727959770 (2024-10-03T12:49:30.000Z)
    Daily volume: 129.44 k
    
    
    OPTIMISM 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1727959770 (2024-10-03T12:49:30.000Z)
    Daily volume: 872.25 k
    
    
    BLAST 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1727959770 (2024-10-03T12:49:30.000Z)
    Daily volume: 447.54 k

**Comment by dtmkeng** [comment]
seem value is not change when i change timestamp

**Comment by llamatester** [comment]
The hinkal adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs hinkal
    
    🦙 Running HINKAL adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 03 Oct 2024 02:14:15 GMT
    End Date:	Fri, 04 Oct 2024 02:14:15 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728008054 (2024-10-04T02:14:14.000Z)
    Daily volume: 116.43 M
    
    
    BASE 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728008054 (2024-10-04T02:14:14.000Z)
    Daily volume: 11.80 M
    
    
    ARBITRUM 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728008054 (2024-10-04T02:14:14.000Z)
    Daily volume: 8.58 M
    
    
    POLYGON 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728008054 (2024-10-04T02:14:14.000Z)
    Daily volume: 755.81 k
    
    
    BSC 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728008054 (2024-10-04T02:14:14.000Z)
    Daily volume: 236.36 k
    
    
    AVAX 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728008054 (2024-10-04T02:14:14.000Z)
    Daily volume: 129.16 k
    
    
    OPTIMISM 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728008054 (2024-10-04T02:14:14.000Z)
    Daily volume: 874.19 k
    
    
    BLAST 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728008054 (2024-10-04T02:14:14.000Z)
    Daily volume: 457.90 k

**Comment by Dav0808** [comment]
> seem value is not change when i change timestamp
new API is now working. Can you check this PR - if everything is working? thanks

**Comment by Dav0808** [comment]
> seem value is not change when i change timestamp

any update aboyt this pr?

**Comment by llamatester** [comment]
The hinkal adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs hinkal
    
    🦙 Running HINKAL adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 05 Oct 2024 11:26:36 GMT
    End Date:	Sun, 06 Oct 2024 11:26:36 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728213995 (2024-10-06T11:26:35.000Z)
    Daily volume: 0
    
    
    BASE 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728213995 (2024-10-06T11:26:35.000Z)
    Daily volume: 0
    
    
    ARBITRUM 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728213995 (2024-10-06T11:26:35.000Z)
    Daily volume: 225
    
    
    POLYGON 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728213995 (2024-10-06T11:26:35.000Z)
    Daily volume: 3.02 k
    
    
    BSC 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728213995 (2024-10-06T11:26:35.000Z)
    Daily volume: 62
    
    
    AVAX 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728213995 (2024-10-06T11:26:35.000Z)
    Daily volume: 0
    
    
    OPTIMISM 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728213995 (2024-10-06T11:26:35.000Z)
    Daily volume: 0
    
    
    BLAST 👇
    Backfill start time: 19/4/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1728213995 (2024-10-06T11:26:35.000Z)
    Daily volume: 0

**Review by Rezacb0413 — APPROVED** [review]

**Comment by Dav0808** [comment]
any update about this pr? when will it approx merged? as I understand it takes some time after merge for changes to be visible on defilama?

**Pull request merged**
