### PR TITLE
add YFX V4

### PR DESCRIPTION
**Pull request by yfxcom**

### CODE REVIEW

**Comment by llamatester** [comment]
The yfx-v4.ts adapter exports: 
        
 
 _______________________________________
    Fees for 24/5/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 24/5/2024
    Time: 1.72 B
    Daily fees: 755
    └─ Methodology: Fees from open/close position (0.05%) and remove liquidity fees (0%)
    Daily user fees: 755
    └─ Methodology: Fees from open/close position (0.05%)
    Timestamp: 1716543837 (2024-05-24T09:43:57.000Z)

**Comment by yfxcom** [comment]
> The yfx-v4 adapter exports:
> 
> ```
> Dexs for 24/5/2024
> _______________________________________
> 
> ARBITRUM 👇
> Backfill start time: 24/5/2024
> NO METHODOLOGY SPECIFIED
> Timestamp: 1716543828 (2024-05-24T09:43:48.000Z)
> Daily volume: 2.50 M
> Total volume: 8.16 M
> ```

Correct

**Comment by yfxcom** [comment]
> The yfx-v4.ts adapter exports:
> 
> ```
> Fees for 24/5/2024
> _______________________________________
> 
> ARBITRUM 👇
> Backfill start time: 24/5/2024
> Time: 1.72 B
> Daily fees: 755
> └─ Methodology: Fees from open/close position (0.05%) and remove liquidity fees (0%)
> Daily user fees: 755
> └─ Methodology: Fees from open/close position (0.05%)
> Timestamp: 1716543837 (2024-05-24T09:43:57.000Z)
> ```

Correct

**Comment by yfxcom** [comment]
We still have not seen the dimensional data of YFX v4.0. BTW, could you please migrate the existing YFX V3.0 data with the new submitted YFX V4.0?

**Pull request merged**
