### PR TITLE
Maverick AMM volume and fee adapter

### PR DESCRIPTION
**Pull request by gte620v**

### CODE REVIEW

**Comment by llamatester** [comment]
The maverick adapter exports: 
        
 
 _______________________________________
    Dexs for 3/3/2023
    _______________________________________
    
    Wrong value NaN with key totalFees
    Wrong value NaN with key totalUserFees
    ETHEREUM 👇
    Backfill start time: 1/1/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 25861523.030197863
    Daily volume: 3220130.814900196
    Daily fees: 322.0130814900196
    Daily user fees: 322.0130814900196
    Timestamp: 1677801600
    
    
    
    
    Done in 5.81s.

**Comment by llamatester** [comment]
The maverick adapter exports: 
        
 
 _______________________________________
    Dexs for 3/3/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 1/1/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 25861523.030197863
    Daily volume: 3220130.814900196
    Daily fees: 322.0130814900196
    Total fees: 2710.821691263894
    Daily user fees: 322.0130814900196
    Total user fees: 2710.821691263894
    Timestamp: 1677801600
    
    
    
    
    Done in 5.42s.

**Comment by dtmkeng** [comment]
could you split two adapter `dexs` and `fees` ?

**Comment by gte620v** [comment]
@dtmkeng Can you point me to an example?

**Comment by dtmkeng** [comment]
> @dtmkeng Can you point me to an example? I am not sure what you mean.

if dexs volume should return this type 
```
  timestamp: number,
  dailyVolume?: string
  totalVolume?: string 
```

if fees adapter return this type
```
  totalFees?: string | IJSON<string>;
  dailyFees?: string | IJSON<string>;
  dailyUserFees?: string | IJSON<string>;
  totalRevenue?: string | IJSON<string>;
  dailyRevenue?: string | IJSON<string>;
  dailyProtocolRevenue?: string | IJSON<string>;
  dailyHoldersRevenue?: string | IJSON<string>;
  dailySupplySideRevenue?: string | IJSON<string>;
  totalProtocolRevenue?: string | IJSON<string>;
  totalSupplySideRevenue?: string | IJSON<string>;
  totalUserFees?: string | IJSON<string>;
```
if you want to add two adapter type you should split file under `dexs/...` and `fees/...`

**Comment by llamatester** [comment]
The maverick adapter exports: 
        
 
 _______________________________________
    Dexs for 4/3/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 1/1/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 21245896.102729984
    Daily volume: 289363.9207252556
    Timestamp: 1677888000
    
    
    
    
    Done in 7.96s.

**Comment by llamatester** [comment]
The maverick.ts adapter exports: 
        
 
 _______________________________________
    Fees for 4/3/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 1/1/2023
    Timestamp: 1677974398
    Daily fees: 28.936392072525564
    └─ Methodology: Fees generated on each swap at a rate set by the pool.
    Total fees: 2124.5896102729985
    └─ Methodology: Fees generated on each swap at a rate set by the pool.
    Daily user fees: 28.936392072525564
    └─ Methodology: LPs collect 100% of the fee generated in a pool
    Total user fees: 2124.5896102729985
    └─ Methodology: LPs collect 100% of the fee generated in a pool
    
    
    
    
    Done in 5.52s.

**Comment by gte620v** [comment]
Ok, how about this?

**Comment by llamatester** [comment]
The maverick adapter exports: 
        
 
 _______________________________________
    Dexs for 4/3/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 1/1/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 21245896.102729984
    Daily volume: 289363.9207252556
    Timestamp: 1677888000
    
    
    
    
    Done in 6.33s.

**Comment by llamatester** [comment]
The maverick.ts adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    fees/maverick.ts(17,7): error TS2322: Type '(timestamp: number) => Promise<{ dailyFees: string; totalFees: string; dailyUserFees: string; totalUserFees: string; }>' is not assignable to type 'Fetch'.
      Type 'Promise<{ dailyFees: string; totalFees: string; dailyUserFees: string; totalUserFees: string; }>' is not assignable to type 'Promise<FetchResult>'.
        Type '{ dailyFees: string; totalFees: string; dailyUserFees: string; totalUserFees: string; }' is not assignable to type 'FetchResult'.
          Property 'timestamp' is missing in type '{ dailyFees: string; totalFees: string; dailyUserFees: string; totalUserFees: string; }' but required in type 'FetchResultBase'.
    
    Done in 2.61s.

**Comment by llamatester** [comment]
The maverick adapter exports: 
        
 
 _______________________________________
    Dexs for 4/3/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 1/1/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 21245896.102729984
    Daily volume: 289363.9207252556
    Timestamp: 1677888000
    
    
    
    
    Done in 6.14s.

**Comment by llamatester** [comment]
The maverick.ts adapter exports: 
        
 
 _______________________________________
    Fees for 4/3/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 1/1/2023
    Timestamp: 1677974398
    Daily fees: 28.936392072525564
    └─ Methodology: Fees generated on each swap at a rate set by the pool.
    Total fees: 2124.5896102729985
    └─ Methodology: Fees generated on each swap at a rate set by the pool.
    Daily user fees: 28.936392072525564
    └─ Methodology: LPs collect 100% of the fee generated in a pool
    Total user fees: 2124.5896102729985
    └─ Methodology: LPs collect 100% of the fee generated in a pool
    
    
    
    
    Done in 5.81s.

**Comment by dtmkeng** [comment]
@gte620v oh everything is good, and for list could you drop detail of this protocol tw link or web site ?

**Comment by gte620v** [comment]
I submitted the protocol data at https://github.com/DefiLlama/DefiLlama-Adapters/pull/5525
Does that work?

**Comment by dtmkeng** [comment]
> DefiLlama/DefiLlama-Adapters#5525

oke waiting tvl adapter merge i will merge this adapter

**Comment by gte620v** [comment]
Ok, it is merged now; thanks!

**Pull request merged**
