### PR TITLE
remove fees metrics for thala

### PR DESCRIPTION
**Pull request by LawsonGraham**
removing fees metrics for the time being from thala adapters

### CODE REVIEW

**Comment by llamatester** [comment]
The thalaswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs thalaswap
    
    🦙 Running THALASWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 07 Sep 2024 00:00:00 GMT
    End Date:	Sun, 08 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    APTOS 👇
    Backfill start time: 4/4/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 1.66 B
    Daily volume: 9.14 M
    End timestamp: 1725753599 (2024-09-07T23:59:59.000Z)

**Comment by llamatester** [comment]
The move-dollar.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees move-dollar.ts
    
    🦙 Running MOVE-DOLLAR.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 07 Sep 2024 00:00:00 GMT
    End Date:	Sun, 08 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Invalid adapter
    Error: No compatible adapter found
        at /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:93:16
        at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by llamatester** [comment]
The thalaswap.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees thalaswap.ts
    
    🦙 Running THALASWAP.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 07 Sep 2024 00:00:00 GMT
    End Date:	Sun, 08 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Invalid adapter
    Error: No compatible adapter found
        at /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:93:16
        at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by dtmkeng** [comment]
if you need disable i can disable from my config if you comment code like that is error when run adapter

**Pull request closed without merging**
