### PR TITLE
add swych fees adapter

### PR DESCRIPTION
**Pull request by itsmenikolaos**
This PR adds a new adapter for the Swych Fees Dashboard

### CODE REVIEW

**Comment by llamatester** [comment]
The swych adapter exports: 
        
 
 _______________________________________
    Fees for 14/4/2024
    _______________________________________
    
    BSC 👇
    Backfill start time: 4/12/2023
    Total fees: 22.76 k
    └─ Methodology: Swych collects fees from different transactions done on the Perpetual Exchange.
    
    
    
    
    Done in 23.47s.

**Comment by dtmkeng** [comment]
is there only fees ? 
is there rev or holder rev ?

**Comment by itsmenikolaos** [comment]
I think it is better to show this data as total revenue instead of total fees. Would this be ok?

**Comment by dtmkeng** [comment]
> I think it is better to show this data as total revenue instead of total fees. Would this be ok?

no just ask details about fees distribution

**Comment by dtmkeng** [comment]
could you fix adapter return dailyFees now it have only totalFees

**Pull request merged**
