### PR TITLE
feat: update vertex-protocol adapter to breakdown spots and perps

### PR DESCRIPTION
**Pull request by yruej301**

### CODE REVIEW

**Comment by llamatester** [comment]
The vertex-protocol adapter exports: 
        
 
 _______________________________________
    Dexs for 21/5/2023
    _______________________________________
    
    Failed to get value on arbitrum: TypeError: Cannot read properties of undefined (reading 'map')
    Failed to get value on arbitrum: TypeError: Cannot read properties of undefined (reading 'map')
    Version -> SWAPS
    ---------
    ARBITRUM 👇
    Timestamp attempted: 21/5/2023
    TypeError: Cannot read properties of undefined (reading 'map')
        at fetchProducts (/home/runner/work/dimension-adapters/dimension-adapters/dexs/vertex-protocol/index.ts:23:8)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async fetchSpots (/home/runner/work/dimension-adapters/dimension-adapters/dexs/vertex-protocol/index.ts:67:27)
        at async /home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:32:52
        at async Promise.allSettled (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:61:9
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:60:26
    
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Timestamp attempted: 21/5/2023
    TypeError: Cannot read properties of undefined (reading 'map')
        at fetchProducts (/home/runner/work/dimension-adapters/dimension-adapters/dexs/vertex-protocol/index.ts:23:8)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async fetchPerps (/home/runner/work/dimension-adapters/dimension-adapters/dexs/vertex-protocol/index.ts:72:27)
        at async /home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:32:52
        at async Promise.allSettled (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:61:9
        at async Promise.all (index 1)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:60:26
    
    
    Done in 3.84s.

**Comment by yruej301** [comment]
hey @llamatester, I believe this is because of IP blocking from our API -- this is the output i get -- 

```node
🦙 Running VERTEX-PROTOCOL adapter 🦙
_______________________________________
Dexs for 21/5/2023
_______________________________________

Version -> SWAPS
---------
ARBITRUM 👇
Backfill start time: 8/5/2023
NO METHODOLOGY SPECIFIED
Daily volume: 10272699.736999996
Timestamp: 1684713599


Version -> DERIVATIVES
---------
ARBITRUM 👇
Backfill start time: 8/5/2023
NO METHODOLOGY SPECIFIED
Daily volume: 17318947.228000008
Timestamp: 1684713599


✨  Done in 7.19s.
```
I think last time you guys were able to run the tests from a remote server where there's no IP blocking (non-US).

**Comment by llamatester** [comment]
The vertex-protocol adapter exports: 
        
 
 _______________________________________
    Dexs for 21/5/2023
    _______________________________________
    
    Failed to get value on arbitrum: TypeError: Cannot read properties of undefined (reading 'map')
    Failed to get value on arbitrum: TypeError: Cannot read properties of undefined (reading 'map')
    Version -> SWAPS
    ---------
    ARBITRUM 👇
    Timestamp attempted: 21/5/2023
    TypeError: Cannot read properties of undefined (reading 'map')
        at fetchProducts (/home/runner/work/dimension-adapters/dimension-adapters/dexs/vertex-protocol/index.ts:23:8)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async fetchSpots (/home/runner/work/dimension-adapters/dimension-adapters/dexs/vertex-protocol/index.ts:67:27)
        at async /home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:32:52
        at async Promise.allSettled (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:61:9
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:60:26
    
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Timestamp attempted: 21/5/2023
    TypeError: Cannot read properties of undefined (reading 'map')
        at fetchProducts (/home/runner/work/dimension-adapters/dimension-adapters/dexs/vertex-protocol/index.ts:23:8)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async fetchPerps (/home/runner/work/dimension-adapters/dimension-adapters/dexs/vertex-protocol/index.ts:72:27)
        at async /home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:32:52
        at async Promise.allSettled (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:61:9
        at async Promise.all (index 1)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:60:26
    
    
    Done in 4.26s.

**Comment by yruej301** [comment]
fyi: tests are failing because of IP blocking. should re-run from a non-US server

**Pull request merged**
