### PR TITLE
Velodrome BOB/MODE

### PR DESCRIPTION
**Pull request by ethzoomer**
Volume/swap fees/gauge rewards support for Mode and Bob deployments on Velodrome. BOB chain doesn't yet exist in this repo, not sure if there's something else I need to do for that part

### CODE REVIEW

**Comment by llamatester** [comment]
The velodrome-bob adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The velodrome-mode adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The velodrome-bob adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The velodrome-mode adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The velodrome-mode adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The velodrome-bob adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The velodrome-mode adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by dtmkeng** [comment]
https://github.com/DefiLlama/dimension-adapters/commit/c88506db6ae6ca0244005fab2ebc6b879220cd65 added

**Pull request closed without merging**
