### PR TITLE
[zklite] Add new DEX zklite.io

### PR DESCRIPTION
**Pull request by Khang-NT**
- [x] `yarn run test dexs zklite`

### CODE REVIEW

**Comment by llamatester** [comment]
The zklite adapter exports: 
        
 
 _______________________________________
    Dexs for 23/4/2024
    _______________________________________
    
    
    
    Done in 1.35s.

**Comment by llamatester** [comment]
The zklite adapter exports: 
        
 
 _______________________________________
    Dexs for 23/4/2024
    _______________________________________
    
    ZKSYNC 👇
    Backfill start time: 10/4/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 1.15 k
    Timestamp: 1713830400 (2024-04-23T00:00:00.000Z)
    
    
    
    
    Done in 6.71s.

**Comment by Khang-NT** [comment]
> is there tvl adapter ?

Do you mean tvl adapter on the project `DefiLlama-Adapters`? I just made a draft PR for this: https://github.com/DefiLlama/DefiLlama-Adapters/pull/9967

Please take a look. If it's not what you mean, please give me the docs of tvl adapter.

**Comment by dtmkeng** [comment]
wait tvl merge

**Pull request merged**
