### PR TITLE
Add new Morphex fantom contracts

### PR DESCRIPTION
**Pull request by daedboi**
Added morphex-old in volume and fees, this displays our old Multichain data. "morphex" displays current Fantom data and BSC data.

Could this be grouped together under one tab "Morphex"? Thanks!

### CODE REVIEW

**Comment by llamatester** [comment]
The morphex adapter exports: 
        
 
 _______________________________________
    Dexs for 6/8/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    FANTOM 👇
    Backfill start time: 22/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1691280000
    Daily volume: 103351.57434203965
    Total volume: 1101160.3637221495
    
    
    BSC 👇
    Backfill start time: 14/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1691280000
    Daily volume: 20045.618035858977
    Total volume: 40780778.71610517
    
    
    Version -> DERIVATIVES
    ---------
    FANTOM 👇
    Backfill start time: 22/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1691280000
    Daily volume: 941143.8506140448
    Total volume: 1747276.1809411484
    
    
    BSC 👇
    Backfill start time: 14/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1691280000
    Daily volume: 63331.32178110392
    Total volume: 9752785.769628374
    
    
    Done in 4.04s.

**Comment by llamatester** [comment]
The morphex-old adapter exports: 
        
 
 _______________________________________
    Dexs for 6/8/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    FANTOM 👇
    Backfill start time: 3/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1691280000
    Daily volume: 0
    Total volume: 264566096.23537293
    
    
    Version -> DERIVATIVES
    ---------
    FANTOM 👇
    Backfill start time: 3/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1691280000
    Daily volume: 0
    Total volume: 179084342.71691352
    
    
    Done in 3.83s.

**Comment by llamatester** [comment]
The morphex-old.ts adapter exports: 
        
 
 _______________________________________
    Fees for 6/8/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 3/3/2023
    Timestamp: 1691366398
    Daily fees: 0.6822083080931437
    └─ Methodology: Fees from open/close position (0.1%), liquidations, swap (0.2% to 0.8%), mint and burn (based on tokens balance in the pool) and borrow fee ((assets borrowed)/(total assets in pool)*0.01%)
    Daily user fees: 0
    └─ Methodology: Fees from open/close position (0.1%), swap (0.2% to 0.8%) and borrow fee ((assets borrowed)/(total assets in pool)*0.01%)
    Daily revenue: 0.2046624924279431
    └─ Methodology: Governance revenue is 30% of all collected fees, which are distributed to MPX stakers
    Daily protocol revenue: 0.06822083080931438
    └─ Methodology: 10% of all collected fees are distributed to the treasury
    Daily holders revenue: 0.2046624924279431
    └─ Methodology: 30% of all collected fees are distributed to MPX stakers
    Daily supply side revenue: 0.4093249848558862
    └─ Methodology: 60% of all collected fees are distributed to MLP stakers
    
    
    
    
    Done in 3.70s.

**Comment by dtmkeng** [comment]
is there old version on tvl ?

**Comment by daedboi** [comment]
Isn't TVL in the main adapters repo? Not sure what you mean, apologies

**Comment by dtmkeng** [comment]
> Isn't TVL in the main adapters repo? Not sure what you mean, apologies

yeah

**Comment by daedboi** [comment]
Hi, coming back to this and noticed this wasn't merged, is everything good to go?

**Comment by waynebruce0x** [comment]
@daedboi the bsc subgraph endpoint here isnt returning daily data - is this still maintained? thanks

**Pull request merged**
