### PR TITLE
add concentrator fee and clever fee

### PR DESCRIPTION
**Pull request by 0xFefeEC**

### CODE REVIEW

**Comment by llamatester** [comment]
The clever.ts adapter exports: 
        
 
 _______________________________________
    Fees for 25/10/2023
    _______________________________________
    
    1698192000
    Failed to get value on ethereum: TypeError: Cannot convert undefined or null to object
    ETHEREUM 👇
    Timestamp attempted: 24/10/2023
    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at /home/runner/work/dimension-adapters/dimension-adapters/fees/clever.ts:29:14
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async /home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:32:52
        at async Promise.allSettled (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:52:23
    
    
    
    
    Done in 6.49s.

**Comment by llamatester** [comment]
The concentrator.ts adapter exports: 
        
 
 _______________________________________
    Fees for 25/10/2023
    _______________________________________
    
    1698192000
    Failed to get value on ethereum: TypeError: Cannot convert undefined or null to object
    ETHEREUM 👇
    Timestamp attempted: 24/10/2023
    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at /home/runner/work/dimension-adapters/dimension-adapters/fees/concentrator.ts:28:14
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async /home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:32:52
        at async Promise.allSettled (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:52:23
    
    
    
    
    Done in 4.13s.

**Comment by llamatester** [comment]
The clever.ts adapter exports: 
        
 
 _______________________________________
    Fees for 25/10/2023
    _______________________________________
    
    1698192000
    ETHEREUM 👇
    Backfill start time: 19/4/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698278398
    Daily fees: 0
    Daily revenue: 0
    
    
    
    
    Done in 4.36s.

**Comment by llamatester** [comment]
The concentrator.ts adapter exports: 
        
 
 _______________________________________
    Fees for 25/10/2023
    _______________________________________
    
    1698192000
    ETHEREUM 👇
    Backfill start time: 8/11/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698278398
    Daily fees: 0
    Daily revenue: 0
    
    
    
    
    Done in 4.31s.

**Comment by llamatester** [comment]
The clever.ts adapter exports: 
        
 
 _______________________________________
    Fees for 26/10/2023
    _______________________________________
    
    1698364798 1698278400
    ETHEREUM 👇
    Backfill start time: 19/4/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698364798
    Daily fees: 0
    Daily revenue: 0
    
    
    
    
    Done in 3.73s.

**Comment by llamatester** [comment]
The concentrator.ts adapter exports: 
        
 
 _______________________________________
    Fees for 26/10/2023
    _______________________________________
    
    1698364798 1698278400
    ETHEREUM 👇
    Backfill start time: 8/11/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698364798
    Daily fees: 0
    Daily revenue: 0
    
    
    
    
    Done in 3.62s.

**Comment by dtmkeng** [comment]
hmm value is still 0,

**Comment by 0xFefeEC** [comment]
> hmm value is still 0,

Because yesterday there were just no transactions that generated a fee. There were transactions fees incurred on 10.17

image

image

**Comment by dtmkeng** [comment]
okay thank you

**Pull request merged**
