### PR TITLE
Add Pingu Exchange Fees & Volume

### PR DESCRIPTION
**Pull request by 0xBluePingu**
Hi, I added dexs/pingu and fees/pingu
We are already listed with a tvl dashboard (https://defillama.com/protocol/pingu-exchange)
Do you need other information than what I provided during my tvl PR?

### CODE REVIEW

**Comment by llamatester** [comment]
The pingu adapter exports: 
        
 
 _______________________________________
    Dexs for 6/2/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 10/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 15.83 M
    Total volume: 159.33 M
    Timestamp: 1707177600
    
    
    
    
    Done in 3.83s.

**Comment by llamatester** [comment]
The pingu adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    fees/pingu/index.ts(4,46): error TS2307: Cannot find module '../../helpers/getUniSubgraphfees' or its corresponding type declarations.
    
    Done in 2.26s.

**Comment by 0xBluePingu** [comment]
I fixed the import error

**Comment by llamatester** [comment]
The pingu adapter exports: 
        
 
 _______________________________________
    Dexs for 6/2/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 10/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 15.83 M
    Total volume: 159.33 M
    Timestamp: 1707177600
    
    
    
    
    Done in 2.89s.

**Comment by llamatester** [comment]
The pingu adapter exports: 
        
 
 _______________________________________
    Fees for 6/2/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 10/1/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 10.39 k
    Total fees: 110.49 k
    Timestamp: 1707177600
    
    
    
    
    Done in 2.67s.

**Pull request merged**
