### PR TITLE
Adds volume adapter for Taraswap

### PR DESCRIPTION
**Pull request by DevZi1la**

### CODE REVIEW

**Comment by llamatester** [comment]
The taraswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs taraswap
    
    🦙 Running TARASWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 27 Nov 2024 11:11:14 GMT
    End Date:	Thu, 28 Nov 2024 11:11:14 GMT
    ---------------------------------------------------
    
    []
    []

**Comment by llamatester** [comment]
The taraswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees taraswap
    
    🦙 Running TARASWAP adapter 🦙
    ---------------------------------------------------
    tara
    Start Date:	Wed, 27 Nov 2024 00:00:00 GMT
    End Date:	Thu, 28 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    []
    14319453
    {
        uniswapDayData(id: 20054) {
          feesUSD
          volumeUSD
        }
        factories(first: 1, subgraphError: allow, block: { number: 14319453 }) {
          txCount
          totalVolumeUSD
          totalFeesUSD
          totalValueLockedUSD
        }
      }
      
    [
      {
        chain: 'tara',
        startTimestamp: 1700870400,
        timestamp: 1732751999,
        dailyFees: 1,
        totalFees: 1,
        dailyUserFees: 1,
        totalUserFees: 1
      }
    ]
    TARA 👇
    Backfill start time: 25/11/2023
    End timestamp: 1732751999 (2024-11-27T23:59:59.000Z)
    Daily fees: 1
    └─ Methodology: Fees generated on each swap at a rate set by the pool.
    Total fees: 1
    └─ Methodology: Fees generated on each swap at a rate set by the pool.
    Daily user fees: 1
    └─ Methodology: LPs collect 100% of the fee generated in a pool
    Total user fees: 1
    └─ Methodology: LPs collect 100% of the fee generated in a pool

**Comment by llamatester** [comment]
The taraswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs taraswap
    
    🦙 Running TARASWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 27 Nov 2024 11:14:52 GMT
    End Date:	Thu, 28 Nov 2024 11:14:52 GMT
    ---------------------------------------------------

**Comment by llamatester** [comment]
The taraswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs taraswap
    
    🦙 Running TARASWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 27 Nov 2024 11:17:11 GMT
    End Date:	Thu, 28 Nov 2024 11:17:11 GMT
    ---------------------------------------------------
    
    []
    []

**Comment by llamatester** [comment]
The taraswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees taraswap
    
    🦙 Running TARASWAP adapter 🦙
    ---------------------------------------------------
    tara
    Start Date:	Wed, 27 Nov 2024 00:00:00 GMT
    End Date:	Thu, 28 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    []
    14319453
    {
        uniswapDayData(id: 20054) {
          feesUSD
          volumeUSD
        }
        factories(first: 1, subgraphError: allow, block: { number: 14319453 }) {
          txCount
          totalVolumeUSD
          totalFeesUSD
          totalValueLockedUSD
        }
      }
      
    [
      {
        chain: 'tara',
        startTimestamp: 1700870400,
        timestamp: 1732751999,
        dailyFees: 1,
        totalFees: 1,
        dailyUserFees: 1,
        totalUserFees: 1
      }
    ]
    TARA 👇
    Backfill start time: 25/11/2023
    End timestamp: 1732751999 (2024-11-27T23:59:59.000Z)
    Daily fees: 1
    └─ Methodology: Fees generated on each swap at a rate set by the pool.
    Total fees: 1
    └─ Methodology: Fees generated on each swap at a rate set by the pool.
    Daily user fees: 1
    └─ Methodology: LPs collect 100% of the fee generated in a pool
    Total user fees: 1
    └─ Methodology: LPs collect 100% of the fee generated in a pool

**Comment by llamatester** [comment]
The taraswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs taraswap
    
    🦙 Running TARASWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 27 Nov 2024 11:21:01 GMT
    End Date:	Thu, 28 Nov 2024 11:21:01 GMT
    ---------------------------------------------------

**Comment by llamatester** [comment]
The taraswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees taraswap
    
    🦙 Running TARASWAP adapter 🦙
    ---------------------------------------------------
    tara
    Start Date:	Wed, 27 Nov 2024 00:00:00 GMT
    End Date:	Thu, 28 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    14319453
    {
        uniswapDayData(id: 20054) {
          feesUSD
          volumeUSD
        }
        factories(first: 1, subgraphError: allow, block: { number: 14319453 }) {
          txCount
          totalVolumeUSD
          totalFeesUSD
          totalValueLockedUSD
        }
      }
      
    TARA 👇
    Backfill start time: 25/11/2023
    End timestamp: 1732751999 (2024-11-27T23:59:59.000Z)
    Daily fees: 1
    └─ Methodology: Fees generated on each swap at a rate set by the pool.
    Total fees: 1
    └─ Methodology: Fees generated on each swap at a rate set by the pool.
    Daily user fees: 1
    └─ Methodology: LPs collect 100% of the fee generated in a pool
    Total user fees: 1
    └─ Methodology: LPs collect 100% of the fee generated in a pool

**Comment by g1nt0ki** [comment]
thanks for the PR, refactored and merged here: https://github.com/DefiLlama/dimension-adapters/pull/2153

**Pull request closed without merging**
