### PR TITLE
Add mummy finance on optimism

### PR DESCRIPTION
**Pull request by mummyguy**

### CODE REVIEW

**Comment by llamatester** [comment]
The mummy-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 15/3/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 5/12/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1678838400
    Daily volume: 1741560.6294454709
    Total volume: 166762617.51486176
    
    
    OPTIMISM 👇
    Backfill start time: 28/2/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1678838400
    Daily volume: 1419924.2743747784
    Total volume: 6729376.564154902
    
    
    
    
    Done in 3.81s.

**Comment by llamatester** [comment]
The mummy-finance.ts adapter exports: 
        
 
 _______________________________________
    Fees for 15/3/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 1/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1678838400
    Total fees: 991619.5847055163
    Daily fees: 36726.255954951484
    Total revenue: 49580.97923527582
    Daily revenue: 1836.3127977475742
    
    
    OPTIMISM 👇
    Backfill start time: 1/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1678838400
    Total fees: 35089.56402478626
    Daily fees: 4883.812639121907
    Total revenue: 1754.4782012393132
    Daily revenue: 244.19063195609533
    
    
    
    
    Done in 4.41s.

**Comment by crystalshay2es** [comment]
Was wondering where to make use of it

**Comment by dtmkeng** [comment]
@crystalshay2es  if you want to see result this link https://defillama.com/fees/mummy-finance
and if you want test this adapter just pull this repo and run `npm run test fees  mummy-finance` test result return data from yesterday

**Pull request merged**
