### PR TITLE
Viri fees & volume adapter

### PR DESCRIPTION
**Pull request by GREFintech**

### CODE REVIEW

**Comment by llamatester** [comment]
The Viridian adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The Viridian adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The equilibre adapter exports: 
        
 
 _______________________________________
    TypeError: Cannot read properties of undefined (reading 'Interface')
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/bribes.ts:10:45)
        at Module._compile (node:internal/modules/cjs/loader:1364:14)
        at Module.m._compile (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1618:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
        at Object.require.extensions.<computed> [as .ts] (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1621:12)
        at Module.load (node:internal/modules/cjs/loader:1203:32)
        at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
        at Module.require (node:internal/modules/cjs/loader:1231:19)
        at require (node:internal/modules/helpers:177:18)
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/index.ts:5:1)

**Comment by llamatester** [comment]
The Viridian adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The Viridian adapter exports: 
        
 
 _______________________________________
    Fees for 23/5/2024
    _______________________________________
    
    CORE 👇
    Backfill start time: 31/3/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 54
    Daily holders revenue: 54
    Daily bribes revenue: 0
    Timestamp: 1716502733 (2024-05-23T22:18:53.000Z)

**Comment by llamatester** [comment]
The equilibre adapter exports: 
        
 
 _______________________________________
    TypeError: Cannot read properties of undefined (reading 'Interface')
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/bribes.ts:10:45)
        at Module._compile (node:internal/modules/cjs/loader:1364:14)
        at Module.m._compile (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1618:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
        at Object.require.extensions.<computed> [as .ts] (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1621:12)
        at Module.load (node:internal/modules/cjs/loader:1203:32)
        at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
        at Module.require (node:internal/modules/cjs/loader:1231:19)
        at require (node:internal/modules/helpers:177:18)
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/index.ts:5:1)

**Comment by llamatester** [comment]
The Viridian adapter exports: 
        
 
 _______________________________________
    Dexs for 23/5/2024
    _______________________________________
    
    TypeError: Cannot read properties of undefined (reading 'fromTimestamp')
        at /home/runner/work/dimension-adapters/dimension-adapters/helpers/dexVolumeLogs.ts:93:73
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:25)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'core'
    }

**Comment by llamatester** [comment]
The Viridian adapter exports: 
        
 
 _______________________________________
    Fees for 23/5/2024
    _______________________________________
    
    CORE 👇
    Backfill start time: 31/3/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 54
    Daily holders revenue: 54
    Daily bribes revenue: 0
    Timestamp: 1716502875 (2024-05-23T22:21:15.000Z)

**Comment by llamatester** [comment]
The equilibre adapter exports: 
        
 
 _______________________________________
    TypeError: Cannot read properties of undefined (reading 'Interface')
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/bribes.ts:10:45)
        at Module._compile (node:internal/modules/cjs/loader:1364:14)
        at Module.m._compile (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1618:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
        at Object.require.extensions.<computed> [as .ts] (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1621:12)
        at Module.load (node:internal/modules/cjs/loader:1203:32)
        at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
        at Module.require (node:internal/modules/cjs/loader:1231:19)
        at require (node:internal/modules/helpers:177:18)
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/index.ts:5:1)

**Comment by llamatester** [comment]
The Viridian adapter exports: 
        
 
 _______________________________________
    Dexs for 23/5/2024
    _______________________________________
    
    TypeError: Cannot read properties of undefined (reading 'fromTimestamp')
        at /home/runner/work/dimension-adapters/dimension-adapters/helpers/dexVolumeLogs.ts:93:73
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:25)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'core'
    }

**Comment by llamatester** [comment]
The Viridian adapter exports: 
        
 
 _______________________________________
    Fees for 23/5/2024
    _______________________________________
    
    CORE 👇
    Backfill start time: 17/5/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 54
    Daily holders revenue: 54
    Daily bribes revenue: 0
    Timestamp: 1716503113 (2024-05-23T22:25:13.000Z)

**Comment by llamatester** [comment]
The equilibre adapter exports: 
        
 
 _______________________________________
    TypeError: Cannot read properties of undefined (reading 'Interface')
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/bribes.ts:10:45)
        at Module._compile (node:internal/modules/cjs/loader:1364:14)
        at Module.m._compile (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1618:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
        at Object.require.extensions.<computed> [as .ts] (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1621:12)
        at Module.load (node:internal/modules/cjs/loader:1203:32)
        at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
        at Module.require (node:internal/modules/cjs/loader:1231:19)
        at require (node:internal/modules/helpers:177:18)
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/index.ts:5:1)

**Comment by llamatester** [comment]
The Viridian adapter exports: 
        
 
 _______________________________________
    Dexs for 23/5/2024
    _______________________________________
    
    CORE 👇
    Backfill start time: 17/5/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1716503552 (2024-05-23T22:32:32.000Z)

**Comment by llamatester** [comment]
The Viridian adapter exports: 
        
 
 _______________________________________
    Fees for 23/5/2024
    _______________________________________
    
    CORE 👇
    Backfill start time: 17/5/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 54
    Daily holders revenue: 54
    Daily bribes revenue: 0
    Timestamp: 1716503560 (2024-05-23T22:32:40.000Z)

**Comment by llamatester** [comment]
The equilibre adapter exports: 
        
 
 _______________________________________
    TypeError: Cannot read properties of undefined (reading 'Interface')
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/bribes.ts:10:45)
        at Module._compile (node:internal/modules/cjs/loader:1364:14)
        at Module.m._compile (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1618:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
        at Object.require.extensions.<computed> [as .ts] (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1621:12)
        at Module.load (node:internal/modules/cjs/loader:1203:32)
        at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
        at Module.require (node:internal/modules/cjs/loader:1231:19)
        at require (node:internal/modules/helpers:177:18)
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/index.ts:5:1)

**Comment by dtmkeng** [comment]
we have track equilibre fees already if you need modify plz use this file https://github.com/DefiLlama/dimension-adapters/blob/cbedf6194b2589905e886f36e7e7dc28c4038923/fees/equilibre-exchange.ts

**Comment by llamatester** [comment]
The equilibre-exchange.ts adapter exports: 
        
 
 _______________________________________
    Fees for 23/5/2024
    _______________________________________
    
    KAVA 👇
    Backfill start time: 4/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1716508799 (2024-05-23T23:59:59.000Z)
    Daily fees: 12
    Daily revenue: 12
    Daily holders revenue: 12

**Comment by llamatester** [comment]
The equilibre adapter exports: 
        
 
 _______________________________________
    TypeError: Cannot read properties of undefined (reading 'Interface')
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/bribes.ts:10:45)
        at Module._compile (node:internal/modules/cjs/loader:1364:14)
        at Module.m._compile (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1618:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
        at Object.require.extensions.<computed> [as .ts] (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1621:12)
        at Module.load (node:internal/modules/cjs/loader:1203:32)
        at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
        at Module.require (node:internal/modules/cjs/loader:1231:19)
        at require (node:internal/modules/helpers:177:18)
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/equilibre/index.ts:5:1)

**Pull request closed without merging**
