### PR TITLE
Fix opensea

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The opensea adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees opensea
    
    🦙 Running OPENSEA adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 22 Nov 2024 13:25:34 GMT
    End Date:	Sat, 23 Nov 2024 13:25:34 GMT
    ---------------------------------------------------
    
    Version -> V1
    ---------
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    End timestamp: 1732368333 (2024-11-23T13:25:33.000Z)
    
    
    Version -> V2
    ---------
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    End timestamp: 1732368333 (2024-11-23T13:25:33.000Z)
    
    
    Version -> SEAPORT
    ---------
    ETHEREUM 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 1.39 M
    Daily revenue: 29.82 k
    End timestamp: 1732368333 (2024-11-23T13:25:33.000Z)

**Comment by llamatester** [comment]
The opensea adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees opensea
    
    🦙 Running OPENSEA adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 22 Nov 2024 14:11:33 GMT
    End Date:	Sat, 23 Nov 2024 14:11:33 GMT
    ---------------------------------------------------
    
    Version -> V1
    ---------
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    End timestamp: 1732371092 (2024-11-23T14:11:32.000Z)
    
    
    Version -> V2
    ---------
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    End timestamp: 1732371092 (2024-11-23T14:11:32.000Z)
    
    
    Version -> SEAPORT
    ---------
    ETHEREUM 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 1.39 M
    Daily revenue: 29.04 k
    End timestamp: 1732371092 (2024-11-23T14:11:32.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 7.30 k
    Daily revenue: 2.89 k
    End timestamp: 1732371092 (2024-11-23T14:11:32.000Z)
    
    
    AVAX 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 1.31 k
    Daily revenue: 1.31 k
    End timestamp: 1732371092 (2024-11-23T14:11:32.000Z)
    
    
    BASE 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 5.52 k
    Daily revenue: 4.03 k
    End timestamp: 1732371092 (2024-11-23T14:11:32.000Z)
    
    
    BLAST 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 32
    Daily revenue: 9
    End timestamp: 1732371092 (2024-11-23T14:11:32.000Z)
    
    
    KLAYTN 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 23
    Daily revenue: 0
    End timestamp: 1732371092 (2024-11-23T14:11:32.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 27
    Daily revenue: 18
    End timestamp: 1732371092 (2024-11-23T14:11:32.000Z)
    
    
    POLYGON 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 5.34 k
    Daily revenue: 2.11 k
    End timestamp: 1732371092 (2024-11-23T14:11:32.000Z)
    
    
    ZORA 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 426
    Daily revenue: 283
    End timestamp: 1732371092 (2024-11-23T14:11:32.000Z)

**Comment by llamatester** [comment]
The opensea adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees opensea
    
    🦙 Running OPENSEA adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 22 Nov 2024 14:26:23 GMT
    End Date:	Sat, 23 Nov 2024 14:26:23 GMT
    ---------------------------------------------------
    
    Version -> V1
    ---------
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    End timestamp: 1732371982 (2024-11-23T14:26:22.000Z)
    
    
    Version -> V2
    ---------
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    End timestamp: 1732371982 (2024-11-23T14:26:22.000Z)
    
    
    Version -> SEAPORT
    ---------
    ETHEREUM 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 1.38 M
    Daily revenue: 28.55 k
    End timestamp: 1732371982 (2024-11-23T14:26:22.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 7.21 k
    Daily revenue: 2.83 k
    End timestamp: 1732371982 (2024-11-23T14:26:22.000Z)
    
    
    AVAX 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 1.32 k
    Daily revenue: 1.32 k
    End timestamp: 1732371982 (2024-11-23T14:26:22.000Z)
    
    
    BASE 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 5.20 k
    Daily revenue: 3.83 k
    End timestamp: 1732371982 (2024-11-23T14:26:22.000Z)
    
    
    BLAST 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 29
    Daily revenue: 9
    End timestamp: 1732371982 (2024-11-23T14:26:22.000Z)
    
    
    KLAYTN 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 23
    Daily revenue: 0
    End timestamp: 1732371982 (2024-11-23T14:26:22.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 23
    Daily revenue: 18
    End timestamp: 1732371982 (2024-11-23T14:26:22.000Z)
    
    
    POLYGON 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 3.84 k
    Daily revenue: 2.08 k
    End timestamp: 1732371982 (2024-11-23T14:26:22.000Z)
    
    
    ZORA 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 427
    Daily revenue: 283
    End timestamp: 1732371982 (2024-11-23T14:26:22.000Z)

**Comment by llamatester** [comment]
The opensea adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees opensea
    
    🦙 Running OPENSEA adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 22 Nov 2024 14:41:46 GMT
    End Date:	Sat, 23 Nov 2024 14:41:46 GMT
    ---------------------------------------------------
    
    Version -> V1
    ---------
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    End timestamp: 1732372905 (2024-11-23T14:41:45.000Z)
    
    
    Version -> V2
    ---------
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    End timestamp: 1732372905 (2024-11-23T14:41:45.000Z)
    
    
    Version -> SEAPORT
    ---------
    ETHEREUM 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 67.37 k
    Daily revenue: 28.35 k
    End timestamp: 1732372905 (2024-11-23T14:41:45.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 5.63 k
    Daily revenue: 2.49 k
    End timestamp: 1732372905 (2024-11-23T14:41:45.000Z)
    
    
    AVAX 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 1.30 k
    Daily revenue: 1.30 k
    End timestamp: 1732372905 (2024-11-23T14:41:45.000Z)
    
    
    BASE 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 5.42 k
    Daily revenue: 4.05 k
    End timestamp: 1732372905 (2024-11-23T14:41:45.000Z)
    
    
    BLAST 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 29
    Daily revenue: 9
    End timestamp: 1732372905 (2024-11-23T14:41:45.000Z)
    
    
    KLAYTN 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 27
    Daily revenue: 0
    End timestamp: 1732372905 (2024-11-23T14:41:45.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 26
    Daily revenue: 21
    End timestamp: 1732372905 (2024-11-23T14:41:45.000Z)
    
    
    POLYGON 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 3.93 k
    Daily revenue: 2.13 k
    End timestamp: 1732372905 (2024-11-23T14:41:45.000Z)
    
    
    ZORA 👇
    Backfill start time: 12/6/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 425
    Daily revenue: 282
    End timestamp: 1732372905 (2024-11-23T14:41:45.000Z)

**Review by 0xngmi — APPROVED** [review]

**Pull request merged**
