### PR TITLE
add arrow-markets volume API

### PR DESCRIPTION
**Pull request by TerrenceAddison**

### CODE REVIEW

**Comment by llamatester** [comment]
The arrow-markets adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts options arrow-markets
    
    🦙 Running ARROW-MARKETS adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 21 Aug 2024 00:00:00 GMT
    End Date:	Thu, 22 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    AVAX 👇
    Backfill start time: 15/12/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1724284799 (2024-08-21T23:59:59.000Z)
    Total notional volume: 1.27 M

**Comment by dtmkeng** [comment]
could you add daily notional volume and daily dailyPremiumVolume

**Comment by TerrenceAddison** [comment]
> 1. could you add daily notional volume and daily dailyPremiumVolume
> 2. could you revert change yarn lock

is no.1 a must? we want to keep it simple first and we will add it later down the line

**Comment by llamatester** [comment]
The arrow-markets adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts options arrow-markets
    
    🦙 Running ARROW-MARKETS adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 21 Aug 2024 00:00:00 GMT
    End Date:	Thu, 22 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    AVAX 👇
    Backfill start time: 15/12/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1724284799 (2024-08-21T23:59:59.000Z)
    Total notional volume: 1.27 M

**Comment by TerrenceAddison** [comment]
@dtmkeng is no.1 a must? we want to keep it simple first before adding the rest down the line.

**Comment by dtmkeng** [comment]
> @dtmkeng is no.1 a must? we want to keep it simple first before adding the rest down the line.

 example is all adapter under options folder

**Comment by llamatester** [comment]
The arrow-markets adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts options arrow-markets
    
    🦙 Running ARROW-MARKETS adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 22 Aug 2024 00:00:00 GMT
    End Date:	Fri, 23 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    AVAX 👇
    Backfill start time: 15/12/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1724371199 (2024-08-22T23:59:59.000Z)
    Daily notional volume: 2.67 k
    Daily premium volume: 7
    Total notional volume: 1.27 M

**Comment by TerrenceAddison** [comment]
@dtmkeng updated, please confirm if all is okay thanks 🙏

**Comment by TerrenceAddison** [comment]
@dtmkeng thanks for merging, I checked in our page that the information is still not available. Could you tell me why? I've waited a few hours before asking. Thanks! 🙏

**Comment by dtmkeng** [comment]
> @dtmkeng thanks for merging, I checked in our page that the information is still not available. Could you tell me why? I've waited a few hours before asking. Thanks! 🙏

you api can backfill data  ? seem i run checked is return 0 at daily value

**Comment by dtmkeng** [comment]
AVAX 👇
Backfill start time: 15/12/2023
NO METHODOLOGY SPECIFIED
End timestamp: 1724630399 (2024-08-25T23:59:59.000Z)
Daily notional volume: 0
Daily premium volume: 0
Total notional volume: 1.27 M

**Comment by TerrenceAddison** [comment]
@dtmkeng actually no we can't backfill data, but I expect to see the total notional volume at least which is still not showing till now

**Comment by dtmkeng** [comment]
> @dtmkeng actually no we can't backfill data, but I expect to see the total notional volume at least which is still not showing till now

it still 0

**Comment by TerrenceAddison** [comment]
> > @dtmkeng actually no we can't backfill data, but I expect to see the total notional volume at least which is still not showing till now
> 
> it still 0

what is still 0? if you're talking about daily, it should show 0 if there is no transaction, or are you saying there needs to be some data for daily before the total appears?

**Comment by dtmkeng** [comment]
> what is still 0? if you're talking about daily, it should show 0 if there is no transaction, or are you saying there needs to be some data for daily before the total appears?

your said your api is can't backfill then i can't backfill prev data

**Comment by TerrenceAddison** [comment]
> > what is still 0? if you're talking about daily, it should show 0 if there is no transaction, or are you saying there needs to be some data for daily before the total appears?
> 
> your said your api is can't backfill then i can't backfill prev data

yes but shouldn't I still see the total notional volume?

**Comment by dtmkeng** [comment]
> > > what is still 0? if you're talking about daily, it should show 0 if there is no transaction, or are you saying there needs to be some data for daily before the total appears?
> > 
> > 
> > your said your api is can't backfill then i can't backfill prev data
> 
> yes but shouldn't I still see the total notional volume?

yes i check if all record is still 0

**Comment by TerrenceAddison** [comment]
> AVAX 👇 Backfill start time: 15/12/2023 NO METHODOLOGY SPECIFIED End timestamp: 1724630399 (2024-08-25T23:59:59.000Z) Daily notional volume: 0 Daily premium volume: 0 Total notional volume: 1.27 M

isn't there a total notional volume here?

**Comment by dtmkeng** [comment]
> > AVAX 👇 Backfill start time: 15/12/2023 NO METHODOLOGY SPECIFIED End timestamp: 1724630399 (2024-08-25T23:59:59.000Z) Daily notional volume: 0 Daily premium volume: 0 Total notional volume: 1.27 M
> 
> isn't there a total notional volume here?
> 
> Is there something in the code I need to remove to remove backfill if we don't have backfill?

no backfill is should query by timestamp your api is can query by timestamp ?

**Pull request merged**
