### PR TITLE
feat: add op_bnb chain

### PR DESCRIPTION
**Pull request by ryanfanjc**
feat: add op_bnb chain

### CODE REVIEW

**Comment by llamatester** [comment]
The myx-finance adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees myx-finance
    
    🦙 Running MYX-FINANCE adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 07 Oct 2024 00:00:00 GMT
    End Date:	Tue, 08 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 31/1/2024
    Total fees: 10.86 M
    Daily fees: 13.84 k
    End timestamp: 1728259199 (2024-10-06T23:59:59.000Z)
    
    
    LINEA 👇
    Backfill start time: 21/2/2024
    Total fees: 2.98 M
    Daily fees: 13.37 k
    End timestamp: 1728259199 (2024-10-06T23:59:59.000Z)
    
    
    OP_BNB 👇
    Backfill start time: 27/9/2024
    Total fees: 1.11 k
    Daily fees: 152
    End timestamp: 1728259199 (2024-10-06T23:59:59.000Z)

**Comment by g1nt0ki** [comment]
@ryanfanjc thanks for the PR, can you update the dex adapter as well?

**Comment by llamatester** [comment]
The myx-finance adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs myx-finance
    
    🦙 Running MYX-FINANCE adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 07 Oct 2024 07:52:21 GMT
    End Date:	Tue, 08 Oct 2024 07:52:21 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 31/1/2024
    Daily volume: 40.83 M
    End timestamp: 1728373940 (2024-10-08T07:52:20.000Z)
    
    
    LINEA 👇
    Backfill start time: 21/2/2024
    Daily volume: 29.61 M
    End timestamp: 1728373940 (2024-10-08T07:52:20.000Z)

**Comment by llamatester** [comment]
The myx-finance adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees myx-finance
    
    🦙 Running MYX-FINANCE adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 07 Oct 2024 07:53:28 GMT
    End Date:	Tue, 08 Oct 2024 07:53:28 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 31/1/2024
    Total fees: 10.86 M
    Daily fees: 13.84 k
    End timestamp: 1728374007 (2024-10-08T07:53:27.000Z)
    
    
    LINEA 👇
    Backfill start time: 21/2/2024
    Total fees: 2.98 M
    Daily fees: 13.37 k
    End timestamp: 1728374007 (2024-10-08T07:53:27.000Z)
    
    
    OP_BNB 👇
    Backfill start time: 27/9/2024
    Total fees: 1.13 k
    Daily fees: 169
    End timestamp: 1728374007 (2024-10-08T07:53:27.000Z)

**Comment by g1nt0ki** [comment]
merging this for now, can you put up a new PR with op_bnb dex data endpoint?

**Comment by ryanfanjc** [comment]
> merging this for now, can you put up a new PR with op_bnb dex data endpoint?

Sorry, I just saw your reply. I've already submitted the opbnb DEX.

**Pull request merged**
