### PR TITLE
✨ Elixir volume adapter

### PR DESCRIPTION
**Pull request by cairoeth**
##### Name (to be shown on DefiLlama):
Elixir Protocol

##### Twitter Link:
https://twitter.com/ElixirProtocol

##### List of audit links if any:
https://github.com/trailofbits/publications/blob/master/reviews/2023-09-elixir-securityreview.pdf

##### Website Link:
https://elixir.finance/

##### Logo (High resolution, will be shown with rounded borders):
https://drive.google.com/drive/u/1/folders/1dIqhnpgEXBfphkzyxJnCa8h3zSg_Cg0n

##### Current TVL: 
$8.85m (Nov. 10)

##### Treasury Addresses (if the protocol has treasury):
N/A

##### Chain:
Arbitrum

##### Short Description (to be shown on DefiLlama):

The Elixir Protocol is a high-throughput DPoS consensus network that enables anyone to supply liquidity directly to orderbooks. The protocol is fully composable: enabling orderbook-based DEXs to natively integrate Elixir into their core infrastructure to unlock retail liquidity for algorithmic market making. ​

Elixir has 20+ native integrations into the core infrastructure of leading DEXs, including Vertex, Injective, dYdX, RabbitX, Bluefin, WooFi, and others.

##### Token address and ticker if any:
N/A

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Infrastructure

##### Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
N/A

##### forkedFrom (Does your project originate from another project):
N/A

##### methodology:
N/A

##### Github org/user (Optional, if your code is open source, we can track activity):
N/A

### CODE REVIEW

**Comment by llamatester** [comment]
The elixir adapter exports: 
        
 
 _______________________________________
    Dexs for 9/11/2023
    _______________________________________
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 25/10/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 5579438
    Daily volume: 518488
    Timestamp: 1699574399
    
    
    Done in 9.25s.

**Comment by dtmkeng** [comment]
Are you open PR for tvl already ?

**Comment by cairoeth** [comment]
> Are you open PR for tvl already ?

no, is that necessary for a volume dashboard? i can open it

**Comment by dtmkeng** [comment]
no, just easy for list if tvl already

**Comment by dtmkeng** [comment]
volume is from other protocol ? 
 see explore page should active trade on VERTEX

**Comment by cairoeth** [comment]
this is our volume that we are trading on Vertex. can you specify?

**Comment by dtmkeng** [comment]
yeah, seem the elixir is include on  Vertex volume ?

**Comment by cairoeth** [comment]
yes, our volume is included in the Vertex dashboard because we trade there.

**Comment by dtmkeng** [comment]
i can't list your volume because is duplicate with Vertex on our data

**Comment by dtmkeng** [comment]
if you mean list yield this repo `https://github.com/DefiLlama/yield-server`

**Pull request closed without merging**
