### PR TITLE
update to allow backfill

### PR DESCRIPTION
**Pull request by TerrenceAddison**
Adding timestamp to our query to allow backfill.

### CODE REVIEW

**Comment by llamatester** [comment]
The arrow-markets adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts options arrow-markets
    
    🦙 Running ARROW-MARKETS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Sep 2024 00:00:00 GMT
    End Date:	Wed, 11 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    AVAX 👇
    Backfill start time: 8/2/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1726012799 (2024-09-10T23:59:59.000Z)
    Daily notional volume: 258
    Daily premium volume: 3
    Total notional volume: 1.27 M

**Comment by TerrenceAddison** [comment]
@dtmkeng can I get your eyes on this?

**Comment by TerrenceAddison** [comment]
@dtmkeng I have waited 24h but I don't see the backfill data filling, can you advise me on resolving this?

**Comment by dtmkeng** [comment]
> @dtmkeng I have waited 24h but I don't see the backfill data filling, can you advise me on resolving this?

do you have timestamp example is data is not zero ?

**Comment by TerrenceAddison** [comment]
> > @dtmkeng I have waited 24h but I don't see the backfill data filling, can you advise me on resolving this?
> 
> do you have timestamp example is data is not zero ?

Here are some example:
`1726185600`
`1723680000`
`1722297600`
`1721865600`

**Comment by dtmkeng** [comment]
refilled

**Comment by TerrenceAddison** [comment]
thanks for the help! @dtmkeng

**Pull request merged**
