### PR TITLE
feat: rabbitx starknet dex

### PR DESCRIPTION
**Pull request by kshilov**

### CODE REVIEW

**Comment by llamatester** [comment]
The rabbitx adapter exports: 
        
 
 _______________________________________
    Dexs for 19/11/2023
    _______________________________________
    
    STARKNET 👇
    Backfill start time: 1/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: undefined
    Timestamp: 1700438398
    
    
    
    
    Done in 3.85s.

**Comment by llamatester** [comment]
The rabbitx adapter exports: 
        
 
 _______________________________________
    Dexs for 19/11/2023
    _______________________________________
    
    STARKNET 👇
    Backfill start time: 17/11/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: undefined
    Timestamp: 1700438398
    
    
    
    
    Done in 3.58s.

**Comment by llamatester** [comment]
The rabbitx adapter exports: 
        
 
 _______________________________________
    Dexs for 19/11/2023
    _______________________________________
    
    
    
    Done in 2.53s.

**Comment by dtmkeng** [comment]
if your value is 0 you should use 0 instead`undefined`
and if you need set start time is 17/11 should set `1700179200`

**Comment by llamatester** [comment]
The rabbitx adapter exports: 
        
 
 _______________________________________
    Dexs for 20/11/2023
    _______________________________________
    
    
    
    Done in 2.52s.

**Pull request merged**
