### PR TITLE
Add missing dimension adapters 

### PR DESCRIPTION
**Pull request by 0xrmvdao**

### CODE REVIEW

**Comment by llamatester** [comment]
The kinetix-derivatives-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs kinetix-derivatives-v2
    
    🦙 Running KINETIX-DERIVATIVES-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 27 Sep 2024 00:00:00 GMT
    End Date:	Sat, 28 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    KAVA 👇
    Backfill start time: 28/9/2024
    Daily volume: 1.15 k
    Total volume: 8.28 M
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)

**Comment by llamatester** [comment]
The linehub-perps adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs linehub-perps
    
    🦙 Running LINEHUB-PERPS adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 26 Sep 2024 22:59:25 GMT
    End Date:	Fri, 27 Sep 2024 22:59:25 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 2/7/2024
    Daily volume: 1.43 k
    Total volume: 135.70 k
    End timestamp: 1727477964 (2024-09-27T22:59:24.000Z)

**Comment by llamatester** [comment]
The metavault-derivatives-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs metavault-derivatives-v2
    
    🦙 Running METAVAULT-DERIVATIVES-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 27 Sep 2024 00:00:00 GMT
    End Date:	Sat, 28 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 12/3/2024
    Daily volume: 513
    Total volume: 2.38 M
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    
    
    POLYGON 👇
    Backfill start time: 13/3/2024
    Daily volume: 0
    Total volume: 0
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)

**Comment by llamatester** [comment]
The metavault-v3 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs metavault-v3
    
    🦙 Running METAVAULT-V3 adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 26 Sep 2024 23:01:38 GMT
    End Date:	Fri, 27 Sep 2024 23:01:38 GMT
    ---------------------------------------------------
    
    Version -> V3
    ---------
    LINEA 👇
    Backfill start time: 4/11/2023
    End timestamp: 1727478097 (2024-09-27T23:01:37.000Z)
    Block: 10.03 M
    Total volume: 43.36 M
    Daily volume: 5.73 k
    Daily fees: 13
    └─ Methodology: Each pool charge between 0.01% to 1% fee
    Total fees: 103.11 k
    └─ Methodology: Each pool charge between 0.01% to 1% fee
    Daily protocol revenue: 0
    └─ Methodology: Treasury receives a share of the fees
    Total protocol revenue: 0
    └─ Methodology: Treasury receives a share of the fees
    Daily holders revenue: 0
    └─ Methodology: None
    Total holders revenue: 0
    └─ Methodology: None
    Daily user fees: 13
    └─ Methodology: Users pay between 0.01% to 1% fee
    Total user fees: 103.11 k
    └─ Methodology: Users pay between 0.01% to 1% fee
    Daily supply side revenue: 13
    └─ Methodology: Liquidity providers get most of the fees of all trades in their pools
    Total supply side revenue: 103.11 k
    └─ Methodology: Liquidity providers get most of the fees of all trades in their pools
    Daily revenue: 0
    └─ Methodology: 0 to 1/4 of the fee goes to treasury
    Total revenue: 0
    └─ Methodology: 0 to 1/4 of the fee goes to treasury
    
    
    SCROLL 👇
    Backfill start time: 4/11/2023
    End timestamp: 1727478097 (2024-09-27T23:01:37.000Z)
    Block: 9.67 M
    Total volume: 135.42 M
    Daily volume: 15.73 k
    Daily fees: 42
    └─ Methodology: Each pool charge between 0.01% to 1% fee
    Total fees: 66.36 k
    └─ Methodology: Each pool charge between 0.01% to 1% fee
    Daily protocol revenue: 0
    └─ Methodology: Treasury receives a share of the fees
    Total protocol revenue: 0
    └─ Methodology: Treasury receives a share of the fees
    Daily holders revenue: 0
    └─ Methodology: None
    Total holders revenue: 0
    └─ Methodology: None
    Daily user fees: 42
    └─ Methodology: Users pay between 0.01% to 1% fee
    Total user fees: 66.36 k
    └─ Methodology: Users pay between 0.01% to 1% fee
    Daily supply side revenue: 42
    └─ Methodology: Liquidity providers get most of the fees of all trades in their pools
    Total supply side revenue: 66.36 k
    └─ Methodology: Liquidity providers get most of the fees of all trades in their pools
    Daily revenue: 0
    └─ Methodology: 0 to 1/4 of the fee goes to treasury
    Total revenue: 0
    └─ Methodology: 0 to 1/4 of the fee goes to treasury

**Comment by llamatester** [comment]
The kinetix-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs kinetix-v2
    
    🦙 Running KINETIX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 26 Sep 2024 23:02:45 GMT
    End Date:	Fri, 27 Sep 2024 23:02:45 GMT
    ---------------------------------------------------
    
    KAVA 👇
    Backfill start time: 28/9/2024
    NO METHODOLOGY SPECIFIED
    Block: 11.91 M
    Total volume: 9.83 k
    Daily volume: 12
    End timestamp: 1727478164 (2024-09-27T23:02:44.000Z)
    
    
    BASE 👇
    Backfill start time: 28/9/2024
    NO METHODOLOGY SPECIFIED
    Block: 20.34 M
    Total volume: 0
    Daily volume: 0
    End timestamp: 1727478164 (2024-09-27T23:02:44.000Z)

**Comment by llamatester** [comment]
The linehub-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs linehub-v2
    
    🦙 Running LINEHUB-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 26 Sep 2024 23:02:53 GMT
    End Date:	Fri, 27 Sep 2024 23:02:53 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 28/9/2024
    NO METHODOLOGY SPECIFIED
    Block: 10.03 M
    Total volume: 1.22 k
    Daily volume: 25
    End timestamp: 1727478172 (2024-09-27T23:02:52.000Z)

**Comment by llamatester** [comment]
The metavault-amm-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs metavault-amm-v2
    
    🦙 Running METAVAULT-AMM-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 26 Sep 2024 23:03:59 GMT
    End Date:	Fri, 27 Sep 2024 23:03:59 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 28/9/2024
    NO METHODOLOGY SPECIFIED
    Block: 10.03 M
    Total volume: 1.79 k
    Daily volume: 1
    End timestamp: 1727478238 (2024-09-27T23:03:58.000Z)
    
    
    SCROLL 👇
    Backfill start time: 28/9/2024
    NO METHODOLOGY SPECIFIED
    Block: 9.67 M
    Total volume: 54.13 k
    Daily volume: 0
    End timestamp: 1727478238 (2024-09-27T23:03:58.000Z)

**Comment by llamatester** [comment]
The quickswap-hydra adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs quickswap-hydra
    
    🦙 Running QUICKSWAP-HYDRA adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 26 Sep 2024 23:05:03 GMT
    End Date:	Fri, 27 Sep 2024 23:05:03 GMT
    ---------------------------------------------------
    
    POLYGON_ZKEVM 👇
    Backfill start time: 2/7/2024
    Daily volume: 0
    Total volume: 0
    End timestamp: 1727478302 (2024-09-27T23:05:02.000Z)
    
    
    MANTA 👇
    Backfill start time: 2/7/2024
    Daily volume: 106
    Total volume: 815.06 k
    End timestamp: 1727478302 (2024-09-27T23:05:02.000Z)

**Comment by llamatester** [comment]
The quickswap-perps adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs quickswap-perps
    
    🦙 Running QUICKSWAP-PERPS adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 26 Sep 2024 23:05:28 GMT
    End Date:	Fri, 27 Sep 2024 23:05:28 GMT
    ---------------------------------------------------
    
    POLYGON_ZKEVM 👇
    Backfill start time: 1/1/2024
    Daily volume: 234.58 k
    Total volume: 146.57 M
    End timestamp: 1727478327 (2024-09-27T23:05:27.000Z)

**Comment by llamatester** [comment]
The sparkdex-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs sparkdex-v2
    
    🦙 Running SPARKDEX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 26 Sep 2024 23:05:35 GMT
    End Date:	Fri, 27 Sep 2024 23:05:35 GMT
    ---------------------------------------------------
    
    FLARE 👇
    Backfill start time: 28/9/2024
    NO METHODOLOGY SPECIFIED
    Block: 30.44 M
    Total volume: 24.11 k
    Daily volume: 24
    End timestamp: 1727478334 (2024-09-27T23:05:34.000Z)

**Comment by llamatester** [comment]
The kinetix-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees kinetix-v2
    
    🦙 Running KINETIX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 27 Sep 2024 00:00:00 GMT
    End Date:	Sat, 28 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    KAVA 👇
    Backfill start time: 22/8/2023
    Methodology: Fees collected from user trading fees
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 0
    Total fees: 29
    
    
    BASE 👇
    Backfill start time: 8/5/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 0
    Total fees: 0

**Comment by llamatester** [comment]
The kinetix-v3 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees kinetix-v3
    
    🦙 Running KINETIX-V3 adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 27 Sep 2024 00:00:00 GMT
    End Date:	Sat, 28 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    KAVA 👇
    Backfill start time: 15/8/2023
    Methodology: Fees collected from user trading fees
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 87
    Total fees: 71.11 k
    
    
    BASE 👇
    Backfill start time: 8/5/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 0
    Total fees: 181

**Comment by llamatester** [comment]
The linehub-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees linehub-v2
    
    🦙 Running LINEHUB-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 27 Sep 2024 00:00:00 GMT
    End Date:	Sat, 28 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 1/3/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 0
    Total fees: 4

**Comment by llamatester** [comment]
The linehub-v3 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees linehub-v3
    
    🦙 Running LINEHUB-V3 adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 27 Sep 2024 00:00:00 GMT
    End Date:	Sat, 28 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 1/3/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 21
    Total fees: 2.65 k

**Comment by llamatester** [comment]
The metavault-amm-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees metavault-amm-v2
    
    🦙 Running METAVAULT-AMM-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 27 Sep 2024 00:00:00 GMT
    End Date:	Sat, 28 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 1/3/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 0
    Total fees: 5
    
    
    SCROLL 👇
    Backfill start time: 1/3/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 0
    Total fees: 162

**Review by Rezacb0413 — APPROVED** [review]

**Comment by llamatester** [comment]
The metavault-v3 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees metavault-v3
    
    🦙 Running METAVAULT-V3 adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 27 Sep 2024 00:00:00 GMT
    End Date:	Sat, 28 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    LINEA 👇
    Backfill start time: 1/3/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 13
    Total fees: 102.16 k
    
    
    SCROLL 👇
    Backfill start time: 1/3/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 15
    Total fees: 43.81 k

**Comment by llamatester** [comment]
The quickswap-hydra adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees quickswap-hydra
    
    🦙 Running QUICKSWAP-HYDRA adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 27 Sep 2024 00:00:00 GMT
    End Date:	Sat, 28 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    POLYGON_ZKEVM 👇
    Backfill start time: 1/1/2024
    Methodology: All treasuryFee, poolFee and keeperFee are collected
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 0
    Total fees: 0
    
    
    MANTA 👇
    Backfill start time: 1/1/2024
    Methodology: All treasuryFee, poolFee and keeperFee are collected
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 0
    Total fees: 0

**Comment by llamatester** [comment]
The quickswap-perps adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees quickswap-perps
    
    🦙 Running QUICKSWAP-PERPS adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 27 Sep 2024 00:00:00 GMT
    End Date:	Sat, 28 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    POLYGON_ZKEVM 👇
    Backfill start time: 1/3/2024
    Methodology: All treasuryFee, poolFee and keeperFee are collected
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 782
    Total fees: 379.82 k

**Review by Rezacb0413 — APPROVED** [review]

**Comment by llamatester** [comment]
The sparkdex-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees sparkdex-v2
    
    🦙 Running SPARKDEX-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 27 Sep 2024 00:00:00 GMT
    End Date:	Sat, 28 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    FLARE 👇
    Backfill start time: 1/3/2024
    Methodology: Fees collected from user trading fees
    End timestamp: 1727395200 (2024-09-27T00:00:00.000Z)
    Daily fees: 0
    Total fees: 72

**Review by Rezacb0413 — APPROVED** [review]

**Review by Rezacb0413 — APPROVED** [review]

**Review by Rezacb0413 — APPROVED** [review]

**Pull request closed without merging**
