### PR TITLE
Javsphere: Add volume and fees of dusdstaking product.

### PR DESCRIPTION
**Pull request by rogi-sh**
https://app.javsphere.com/stake-x

We added the fees and volume of our product dusd staking.

### CODE REVIEW

**Comment by llamatester** [comment]
The javsphere adapter exports: 
        
 
 _______________________________________
    Dexs for 2/4/2024
    _______________________________________
    
    DEFICHAIN 👇
    Backfill start time not defined
    Total volume: 74.42 M
    └─ Methodology: User buys and sell RWA tokens. User get in and out of dusdstaking.
    Total fees: 87.89 k
    └─ Methodology: User pays 0.1% fees on each trade. User pays 10% fee of rewards in dusdstaking.
    Daily fees: 636
    └─ Methodology: User pays 0.1% fees on each trade. User pays 10% fee of rewards in dusdstaking.
    Daily volume: 195.16 k
    └─ Methodology: User buys and sell RWA tokens. User get in and out of dusdstaking.
    Timestamp: 1712102399 (2024-04-02T23:59:59.000Z)
    
    
    
    
    Done in 7.20s.

**Comment by dtmkeng** [comment]
> https://app.javsphere.com/stake-x
> 
> We added the fees and volume of our product dusd staking.

stake volume is it volume when user swap on staking product ?

**Comment by rogi-sh** [comment]
> user swap

Yes user invests in the product and based on this invested amount user gets rewards. So enter and leave the product is volume -> how many funds are go in and out of the product. Same like on trade where user swap the funds. Here user enter the product.

**Comment by dtmkeng** [comment]
> > user swap
> 
> Yes user invests in the product and based on this invested amount user gets rewards. So enter and leave the product is volume -> how many funds are go in and out of the product. Same like on trade where user swap the funds. Here user enter the product.

i can't like volume like this, we list only swap like uni or spot trade

**Comment by rogi-sh** [comment]
> > > user swap
> > 
> > 
> > Yes user invests in the product and based on this invested amount user gets rewards. So enter and leave the product is volume -> how many funds are go in and out of the product. Same like on trade where user swap the funds. Here user enter the product.
> 
> i can't like volume like this, we list only swap like uni or spot trade
ok understood, can we leave the fees then? Because the fees are based on the reward?

**Comment by dtmkeng** [comment]
> ok understood, can we leave the fees then? Because the fees are based on the reward?

yes only fees

**Comment by rogi-sh** [comment]
> > ok understood, can we leave the fees then? Because the fees are based on the reward?
> 
> yes only fees

Done

**Comment by llamatester** [comment]
The javsphere adapter exports: 
        
 
 _______________________________________
    Dexs for 2/4/2024
    _______________________________________
    
    DEFICHAIN 👇
    Backfill start time not defined
    Total volume: 1.60 M
    └─ Methodology: User buys and sell RWA tokens.
    Total fees: 87.89 k
    └─ Methodology: User pays 0.1% fees on each trade. User pays 10% fee of rewards in dusdstaking.
    Daily fees: 642
    └─ Methodology: User pays 0.1% fees on each trade. User pays 10% fee of rewards in dusdstaking.
    Daily volume: 81.71 k
    └─ Methodology: User buys and sell RWA tokens.
    Timestamp: 1712102399 (2024-04-02T23:59:59.000Z)
    
    
    
    
    Done in 4.65s.

**Pull request merged**
