### PR TITLE
Update index.ts

### PR DESCRIPTION
**Pull request by LeeRyanj**

### CODE REVIEW

**Comment by llamatester** [comment]
The kiloex adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees kiloex
    
    🦙 Running KILOEX adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 11 Oct 2024 00:00:00 GMT
    End Date:	Sat, 12 Oct 2024 00:00:00 GMT
    ---------------------------------------------------

**Comment by dtmkeng** [comment]
why you comment all chain ?

**Comment by LeeRyanj** [comment]
> why you comment all chain ?

The part about fee will not be disclosed for the time being

**Comment by dtmkeng** [comment]
can't merge

**Pull request closed without merging**
