### PR TITLE
add thorwallet

### PR DESCRIPTION
**Pull request by pawell24**

### CODE REVIEW

**Comment by llamatester** [comment]
The thorwallet adapter exports: 
        
 
 _______________________________________
    Dexs for 8/2/2023
    _______________________________________
    
    THORCHAIN 👇
    Backfill start time: 2/11/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 1934154861.0904448
    Daily volume: 17696890.57635826
    Timestamp: 1675814400
    
    
    
    
    Done in 7.10s.

**Comment by dtmkeng** [comment]
hi, thank you for contributor, thorswap it already existing https://defillama.com/dexs/thorswap
if you have any update can update on https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/thorswap/index.ts

**Comment by pawell24** [comment]
Yes we know it, but thorwallet is also a protocol that works on thorchain network. We use the same API on thorchain so we want to share data with our users. Here is our website: https://app.thorwallet.org/

**Comment by dtmkeng** [comment]
I see
What would you like us to do?

**Comment by pawell24** [comment]
We want to list Thorwallet on the Defillama platform and show the volume to users.

**Comment by dtmkeng** [comment]
> We want to list Thorwallet on the Defillama platform and show the volume to users.

you mean  instead of thorswap with Thorwallet ?

**Comment by pawell24** [comment]
As well as Thorswap, we are initially sharing the same API for some assets but we are diverting already in terms of assets and volume will follow.

**Comment by dtmkeng** [comment]
@pawell24  could you check adapter thorwallet api return 503

**Pull request merged**
