### PR TITLE
add y2k volume adapter

### PR DESCRIPTION
**Pull request by icyage**

### CODE REVIEW

**Comment by dtmkeng** [comment]
hi, volume is alive for dex, and seem you cord is like fees adapter, if you need update fees adapter, just modify 
https://github.com/DefiLlama/dimension-adapters/blob/master/fees/y2k-finance-v2.ts or https://github.com/DefiLlama/dimension-adapters/blob/master/fees/y2k-finance.ts

**Comment by dtmkeng** [comment]
> > > @dtmkeng the code is similar, but it's not for fees adapter. it's to track volumes.
> > 
> > 
> > it is swap volume ?
> 
> I wanted to ask this, that's deposit volume. But I couldn't find any projects under derivatives. Can I create a folder for derivatives dashboard type and put y2k under that?
yeah, can add it under dexs
this code is work ?

**Comment by llamatester** [comment]
The y2k adapter exports: 
        
 
 _______________________________________
    Dexs for 16/7/2023
    _______________________________________
    
    Version -> V1
    ---------
    ARBITRUM 👇
    Backfill start time: 3/2/2023
    Daily volume: 0
    Timestamp: 1689551999
    
    
    Version -> V2
    ---------
    ARBITRUM 👇
    Backfill start time: 30/5/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1689551999
    
    
    Done in 6.42s.

**Comment by icyage** [comment]
yes but using flipside so thinking to migrate it to manual scan

**Comment by icyage** [comment]
Yes, it works

**Comment by dtmkeng** [comment]
> Yes, it works

is it ok for merge ?

**Pull request merged**
