### PR TITLE
feat: Add tracking for historical OI + Freestyle volume for BMX

### PR DESCRIPTION
**Pull request by daedboi**
Fees:
  - Updated our adapter to use newer import
Dexs:
  - Added historical OI tracking for our Classic market (GMX v1 style)
  - Added derivatives volume tracking for our Freestyle product (intent-based trading)

Recently I committed changes to update our subgraph links to new ones that work, but on the DefiLlama website, the period from June 24 - August 16 just duplicates the fees and volume data on the graphs. I tested various timestamps from that period of time locally, and I got correct, non-duplicated values from the adapters. May you please look into this? Thanks!

image

### CODE REVIEW

**Comment by llamatester** [comment]
The bmx adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs bmx
    
    🦙 Running BMX adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 16 Aug 2024 00:00:00 GMT
    End Date:	Sat, 17 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Version -> SWAP
    ---------
    BASE 👇
    Backfill start time: 10/9/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1723766400 (2024-08-16T00:00:00.000Z)
    Daily volume: 127.47 k
    Total volume: 277.69 M
    
    
    MODE 👇
    Backfill start time: 10/7/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1723766400 (2024-08-16T00:00:00.000Z)
    Daily volume: 34.58 k
    Total volume: 1.21 M
    
    
    Version -> DERIVATIVES-CLASSIC
    ---------
    BASE 👇
    Backfill start time: 10/9/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1723766400 (2024-08-16T00:00:00.000Z)
    Daily long open interest: 118.98 k
    Daily short open interest: 60.44 k
    Daily open interest: 179.42 k
    Daily volume: 8.12 k
    Total volume: 50.38 M
    
    
    MODE 👇
    Backfill start time: 10/7/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1723766400 (2024-08-16T00:00:00.000Z)
    Daily long open interest: 22
    Daily short open interest: 2.20 k
    Daily open interest: 2.22 k
    Daily volume: 7.45 k
    Total volume: 140.97 k
    
    
    Version -> DERIVATIVES-FREESTYLE
    ---------
    BASE 👇
    Backfill start time: 2/5/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1723766400 (2024-08-16T00:00:00.000Z)
    Daily volume: 6.17 M
    Total volume: 215.86 M

**Comment by llamatester** [comment]
The bmx.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees bmx.ts
    
    🦙 Running BMX.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 16 Aug 2024 10:14:53 GMT
    End Date:	Sat, 17 Aug 2024 10:14:53 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 10/9/2023
    End timestamp: 1.72 B
    Daily fees: 175
    └─ Methodology: Fees from open/close position (0.1%), liquidations, swap (0.2% to 0.8%), mint and burn (based on tokens balance in the pool) and borrow fee ((assets borrowed)/(total assets in pool)*0.01%)
    Daily user fees: 149
    └─ Methodology: Fees from open/close position (0.1%), swap (0.2% to 0.8%) and borrow fee ((assets borrowed)/(total assets in pool)*0.01%)
    Daily revenue: 70
    └─ Methodology: Revenue is 40% of all collected fees, which are distributed to BMX/wBLT LP stakers and BMX stakers
    Daily holders revenue: 70
    └─ Methodology: 10% of all collected fees are distributed to BMX stakers
    Daily supply side revenue: 105
    └─ Methodology: 60% of all collected fees are distributed to BLT stakers
    End timestamp: 1723889692 (2024-08-17T10:14:52.000Z)
    
    
    MODE 👇
    Backfill start time: 10/7/2024
    End timestamp: 1.72 B
    Daily fees: 128
    └─ Methodology: Fees from open/close position (0.1%), liquidations, swap (0.2% to 0.8%), mint and burn (based on tokens balance in the pool) and borrow fee ((assets borrowed)/(total assets in pool)*0.01%)
    Daily user fees: 113
    └─ Methodology: Fees from open/close position (0.1%), swap (0.2% to 0.8%) and borrow fee ((assets borrowed)/(total assets in pool)*0.01%)
    Daily revenue: 51
    └─ Methodology: Revenue is 40% of all collected fees, which are distributed to BMX/wBLT LP stakers and BMX stakers
    Daily holders revenue: 51
    └─ Methodology: 10% of all collected fees are distributed to BMX stakers
    Daily supply side revenue: 77
    └─ Methodology: 60% of all collected fees are distributed to BLT stakers
    End timestamp: 1723889692 (2024-08-17T10:14:52.000Z)

**Comment by daedboi** [comment]
@dtmkeng Thank you for merging, the fees/revenue data now shows correctly - the volume data is still duplicated though.

Also https://defillama.com/protocol/bmx#derivatives-volume doesn't load at all atm.

image

**Comment by dtmkeng** [comment]
okay will take a look

**Pull request merged**
