### PR TITLE
feat(fees): added azuro to fees dashboard

### PR DESCRIPTION
**Pull request by cowboybebop-r**
added new fees adapter for azuro protocol

### CODE REVIEW

**Comment by llamatester** [comment]
The azuro adapter exports: 
        
 
 _______________________________________
    Fees for 20/3/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 1/1/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1679356798
    Daily fees: -1606.75
    Daily revenue: -1606.75
    
    
    XDAI 👇
    Backfill start time: 1/1/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1679356798
    Daily fees: 807.46
    Daily revenue: 807.46
    
    
    
    
    Done in 4.14s.

**Comment by dtmkeng** [comment]
hi, could you check the result why the fees are negative value.?

**Comment by cowboybebop-r** [comment]
Hi! Its for us having negative fee(Gross Gaming Revenue (GGR)) in short
term period.

**Comment by llamatester** [comment]
The azuro adapter exports: 
        
 
 _______________________________________
    Fees for 21/3/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 1/1/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1679443198
    Daily fees: 711.59
    Daily revenue: 711.59
    
    
    XDAI 👇
    Backfill start time: 1/1/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1679443198
    Daily fees: -52.06
    Daily revenue: -52.06
    
    
    
    
    Done in 5.34s.

**Comment by cowboybebop-r** [comment]
so it is impossible to send negative values, only values >= 0 right?

**Comment by cowboybebop-r** [comment]
the specifics of our project and protocol allow us to have negative GGR values (GGR = fees = revenue). please take into account our specifics and please do not pay attention to negative values, they are correct for us

**Comment by cowboybebop-r** [comment]
@dtmkeng hi! 
when i can get response about negative value issue? are there any updates or decisions?

**Comment by cowboybebop-r** [comment]
@dtmkeng great idea! but can u clarify what exactly should be added to help people understand our fee/rev? should be short descriptions in methodology?

**Comment by dtmkeng** [comment]
> @dtmkeng great idea! but can u clarify what exactly should be added to help people understand our fee/rev? should be short descriptions in methodology?

fees data from ...
revenue data from x % of fees

**Comment by cowboybebop-r** [comment]
Fees:
“Fees” within Azuro refers to the total profits of the Liquidity Pools. I.e. the difference between the total sum of tokens bet by users via front-ends and the total sum of tokens paid out.

Revenue:
Revenue stands for the total amount of profit generated in all of Azuro’s Liquidity Pools. I.e. equals “Fees”.

**Pull request merged**
