### PR TITLE
add volume for DackieSwap on Blast

### PR DESCRIPTION
**Pull request by DackieSwap**

### CODE REVIEW

**Comment by llamatester** [comment]
The dackieswap-v2 adapter exports: 
        
 
 _______________________________________
    Dexs for 5/3/2024
    _______________________________________
    
    Attempting with alternative query...
    Attempting with alternative query...
    BASE 👇
    Backfill start time: 6/3/2024
    Timestamp: 1709683198 (2024-03-05T23:59:58.000Z)
    Block: 11.45 M
    Total volume: 1.76 M
    Daily volume: 4.01 k
    Daily fees: 10
    └─ Methodology: All fees comes from the user.
    Total fees: 4.40 k
    └─ Methodology: All fees comes from the user.
    Daily user fees: 10
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 4.40 k
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 7
    └─ Methodology: LPs receive 0.17% of each swap.
    Total supply side revenue: 2.99 k
    └─ Methodology: LPs receive 0.17% of each swap.
    Daily protocol revenue: 3
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 1.41 k
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily revenue: 10
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 4.40 k
    └─ Methodology: All revenue generated comes from user fees.
    
    
    OPTIMISM 👇
    Backfill start time: 6/3/2024
    Timestamp: 1709683198 (2024-03-05T23:59:58.000Z)
    Block: 117.04 M
    Total volume: 18.42 k
    Daily volume: 582
    Daily fees: 1
    └─ Methodology: All fees comes from the user.
    Total fees: 46
    └─ Methodology: All fees comes from the user.
    Daily user fees: 1
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 46
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 1
    └─ Methodology: LPs receive 0.17% of each swap.
    Total supply side revenue: 31
    └─ Methodology: LPs receive 0.17% of each swap.
    Daily protocol revenue: 0
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 15
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily revenue: 1
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 46
    └─ Methodology: All revenue generated comes from user fees.
    
    
    ARBITRUM 👇
    Backfill start time: 6/3/2024
    Timestamp: 1709683198 (2024-03-05T23:59:58.000Z)
    Block: 187.50 M
    Total volume: 12.23 k
    Daily volume: 888
    Daily fees: 2
    └─ Methodology: All fees comes from the user.
    Total fees: 31
    └─ Methodology: All fees comes from the user.
    Daily user fees: 2
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 31
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 2
    └─ Methodology: LPs receive 0.17% of each swap.
    Total supply side revenue: 21
    └─ Methodology: LPs receive 0.17% of each swap.
    Daily protocol revenue: 1
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 10
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily revenue: 2
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 31
    └─ Methodology: All revenue generated comes from user fees.
    
    
    BLAST 👇
    Backfill start time: 6/3/2024
    Timestamp: 1709683198 (2024-03-05T23:59:58.000Z)
    Block: 436.69 k
    Total volume: 0
    Daily volume: 0
    Daily fees: 0
    └─ Methodology: All fees comes from the user.
    Total fees: 0
    └─ Methodology: All fees comes from the user.
    Daily user fees: 0
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 0
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 0
    └─ Methodology: LPs receive 0.17% of each swap.
    Total supply side revenue: 0
    └─ Methodology: LPs receive 0.17% of each swap.
    Daily protocol revenue: 0
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 0
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily revenue: 0
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 0
    └─ Methodology: All revenue generated comes from user fees.
    
    
    
    
    Done in 11.15s.

**Comment by llamatester** [comment]
The dackieswap adapter exports: 
        
 
 _______________________________________
    Dexs for 5/3/2024
    _______________________________________
    
    Attempting with alternative query...
    BASE 👇
    Backfill start time: 6/3/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1709683198 (2024-03-05T23:59:58.000Z)
    Block: 11.45 M
    Total volume: 454.09 M
    Daily volume: 503.73 k
    Daily fees: 138
    Total fees: 118.56 k
    
    
    OPTIMISM 👇
    Backfill start time: 6/3/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1709683198 (2024-03-05T23:59:58.000Z)
    Block: 117.04 M
    Total volume: 102.09 k
    Daily volume: 19.02 k
    Daily fees: 42
    Total fees: 159
    
    
    ARBITRUM 👇
    Backfill start time: 6/3/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1709683198 (2024-03-05T23:59:58.000Z)
    Block: 187.50 M
    Total volume: 69.97 k
    Daily volume: 9.13 k
    Daily fees: 14
    Total fees: 77
    
    
    BLAST 👇
    Backfill start time: 6/3/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1709683198 (2024-03-05T23:59:58.000Z)
    Block: 436.69 k
    Total volume: 0
    Daily volume: 0
    Total fees: 0
    
    
    
    
    Done in 6.74s.

**Comment by dtmkeng** [comment]
could you resolve conflict ?

**Comment by DackieSwap** [comment]
> could you resolve conflict ?

resolved @dtmkeng 🙏

**Comment by llamatester** [comment]
The dackieswap-v2 adapter exports: 
        
 
 _______________________________________
    Dexs for 6/3/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 24/7/2023
    Timestamp: 1709690369 (2024-03-06T01:59:29.000Z)
    Block: 11.45 M
    Total volume: 1.76 M
    Daily volume: 4.52 k
    Daily fees: 11
    └─ Methodology: All fees comes from the user.
    Total fees: 4.40 k
    └─ Methodology: All fees comes from the user.
    Daily user fees: 11
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 4.40 k
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 8
    └─ Methodology: LPs receive 0.17% of each swap.
    Total supply side revenue: 2.99 k
    └─ Methodology: LPs receive 0.17% of each swap.
    Daily protocol revenue: 4
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 1.41 k
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily revenue: 11
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 4.40 k
    └─ Methodology: All revenue generated comes from user fees.
    
    
    OPTIMISM 👇
    Backfill start time: 23/1/2024
    Timestamp: 1709690369 (2024-03-06T01:59:29.000Z)
    Block: 117.05 M
    Total volume: 18.46 k
    Daily volume: 232
    Daily fees: 1
    └─ Methodology: All fees comes from the user.
    Total fees: 46
    └─ Methodology: All fees comes from the user.
    Daily user fees: 1
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 46
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 0
    └─ Methodology: LPs receive 0.17% of each swap.
    Total supply side revenue: 31
    └─ Methodology: LPs receive 0.17% of each swap.
    Daily protocol revenue: 0
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 15
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily revenue: 1
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 46
    └─ Methodology: All revenue generated comes from user fees.
    
    
    ARBITRUM 👇
    Backfill start time: 14/2/2024
    Timestamp: 1709690369 (2024-03-06T01:59:29.000Z)
    Block: 187.52 M
    Total volume: 12.23 k
    Daily volume: 1.94 k
    Daily fees: 5
    └─ Methodology: All fees comes from the user.
    Total fees: 31
    └─ Methodology: All fees comes from the user.
    Daily user fees: 5
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 31
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 3
    └─ Methodology: LPs receive 0.17% of each swap.
    Total supply side revenue: 21
    └─ Methodology: LPs receive 0.17% of each swap.
    Daily protocol revenue: 2
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 10
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily revenue: 5
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 31
    └─ Methodology: All revenue generated comes from user fees.
    
    
    BLAST 👇
    Backfill start time: 3/1/1970
    Timestamp: 1709690369 (2024-03-06T01:59:29.000Z)
    Block: 440.28 k
    Total volume: 0
    Daily volume: 3
    Daily fees: 0
    └─ Methodology: All fees comes from the user.
    Total fees: 0
    └─ Methodology: All fees comes from the user.
    Daily user fees: 0
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 0
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 0
    └─ Methodology: LPs receive 0.17% of each swap.
    Total supply side revenue: 0
    └─ Methodology: LPs receive 0.17% of each swap.
    Daily protocol revenue: 0
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 0
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily revenue: 0
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 0
    └─ Methodology: All revenue generated comes from user fees.
    
    
    
    
    Done in 10.05s.

**Comment by llamatester** [comment]
The dackieswap adapter exports: 
        
 
 _______________________________________
    Dexs for 6/3/2024
    _______________________________________
    
    TypeError: customBlockFunc is not a function
        at /home/runner/work/dimension-adapters/dimension-adapters/helpers/getUniSubgraph/index.ts:190:16
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:29:25)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 1)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:57:21 {
      chain: 'optimism'
    }
    Done in 7.84s.

**Comment by llamatester** [comment]
The dackieswap-v2 adapter exports: 
        
 
 _______________________________________
    Dexs for 6/3/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 24/7/2023
    Timestamp: 1709690619 (2024-03-06T02:03:39.000Z)
    Block: 11.45 M
    Total volume: 1.76 M
    Daily volume: 4.52 k
    Daily fees: 11
    └─ Methodology: All fees comes from the user.
    Total fees: 4.40 k
    └─ Methodology: All fees comes from the user.
    Daily user fees: 11
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 4.40 k
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 8
    └─ Methodology: LPs receive 0.17% of each swap.
    Total supply side revenue: 2.99 k
    └─ Methodology: LPs receive 0.17% of each swap.
    Daily protocol revenue: 4
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 1.41 k
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily revenue: 11
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 4.40 k
    └─ Methodology: All revenue generated comes from user fees.
    
    
    OPTIMISM 👇
    Backfill start time: 23/1/2024
    Timestamp: 1709690619 (2024-03-06T02:03:39.000Z)
    Block: 117.05 M
    Total volume: 18.46 k
    Daily volume: 232
    Daily fees: 1
    └─ Methodology: All fees comes from the user.
    Total fees: 46
    └─ Methodology: All fees comes from the user.
    Daily user fees: 1
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 46
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 0
    └─ Methodology: LPs receive 0.17% of each swap.
    Total supply side revenue: 31
    └─ Methodology: LPs receive 0.17% of each swap.
    Daily protocol revenue: 0
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 15
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily revenue: 1
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 46
    └─ Methodology: All revenue generated comes from user fees.
    
    
    ARBITRUM 👇
    Backfill start time: 14/2/2024
    Timestamp: 1709690619 (2024-03-06T02:03:39.000Z)
    Block: 187.52 M
    Total volume: 12.23 k
    Daily volume: 1.94 k
    Daily fees: 5
    └─ Methodology: All fees comes from the user.
    Total fees: 31
    └─ Methodology: All fees comes from the user.
    Daily user fees: 5
    └─ Methodology: User pays 0.25% fees on each swap.
    Total user fees: 31
    └─ Methodology: User pays 0.25% fees on each swap.
    Daily supply side revenue: 3
    └─ Methodology: LPs receive 0.17% of each swap.
    Total supply side revenue: 21
    └─ Methodology: LPs receive 0.17% of each swap.
    Daily protocol revenue: 2
    └─ Methodology: Treasury receives 0.08% of each swap.
    Total protocol revenue: 10
    └─ Methodology: Treasury receives 0.08% of each swap.
    Daily revenue: 5
    └─ Methodology: All revenue generated comes from user fees.
    Total revenue: 31
    └─ Methodology: All revenue generated comes from user fees.
    
    
    
    
    Done in 12.75s.

**Comment by llamatester** [comment]
The dackieswap adapter exports: 
        
 
 _______________________________________
    Dexs for 6/3/2024
    _______________________________________
    
    TypeError: customBlockFunc is not a function
        at /home/runner/work/dimension-adapters/dimension-adapters/helpers/getUniSubgraph/index.ts:190:16
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:29:25)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:57:21 {
      chain: 'base'
    }
    Done in 8.40s.

**Pull request merged**
