### PR TITLE
Synthetix: Update fees

### PR DESCRIPTION
**Pull request by Tburm**
Synthetix:
- Adds perps markets
- Removes liquidations from volume

Synthetix V3:
- Adds methodology
- Adds fees from Arbitrum perps

### CODE REVIEW

**Comment by llamatester** [comment]
The synthetix adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs synthetix
    
    🦙 Running SYNTHETIX adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 21 Nov 2024 00:00:00 GMT
    End Date:	Fri, 22 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    OPTIMISM 👇
    Backfill start time: 22/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 166.99 M
    End timestamp: 1732233599 (2024-11-21T23:59:59.000Z)

**Comment by llamatester** [comment]
The synthetix-v3.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees synthetix-v3.ts
    
    🦙 Running SYNTHETIX-V3.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 21 Nov 2024 00:00:00 GMT
    End Date:	Fri, 22 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 13/1/2024
    Daily fees: 7.01 k
    └─ Methodology: Fees generated from trades
    Daily revenue: 2.60 k
    └─ Methodology: Fees paid by users and awarded to LPs
    Daily holders revenue: 2.60 k
    └─ Methodology: Fees are granted proportionally to LPs by tracking the profit and loss of the positions backed by Synthetix V3
    Daily supply side revenue: 2.60 k
    End timestamp: 1732233599 (2024-11-21T23:59:59.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 15/8/2024
    Daily fees: 1.08 k
    └─ Methodology: Fees generated from trades
    Daily revenue: 0
    └─ Methodology: Fees paid by users and awarded to LPs
    Daily holders revenue: 0
    └─ Methodology: Fees are granted proportionally to LPs by tracking the profit and loss of the positions backed by Synthetix V3
    Daily supply side revenue: 574
    End timestamp: 1732233599 (2024-11-21T23:59:59.000Z)

**Comment by llamatester** [comment]
The synthetix-v3.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees synthetix-v3.ts
    
    🦙 Running SYNTHETIX-V3.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 21 Nov 2024 00:00:00 GMT
    End Date:	Fri, 22 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 13/1/2024
    Daily fees: 7.01 k
    └─ Methodology: Fees generated from trades
    Daily revenue: 2.60 k
    └─ Methodology: Fees paid by users and awarded to LPs
    Daily holders revenue: 2.60 k
    └─ Methodology: Fees are granted proportionally to LPs by tracking the profit and loss of the positions backed by Synthetix V3
    Daily supply side revenue: 2.60 k
    End timestamp: 1732233599 (2024-11-21T23:59:59.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 15/8/2024
    Daily fees: 1.08 k
    └─ Methodology: Fees generated from trades
    Daily revenue: 0
    └─ Methodology: Fees paid by users and awarded to LPs
    Daily holders revenue: 0
    └─ Methodology: Fees are granted proportionally to LPs by tracking the profit and loss of the positions backed by Synthetix V3
    Daily supply side revenue: 574
    End timestamp: 1732233599 (2024-11-21T23:59:59.000Z)

**Comment by g1nt0ki** [comment]
@Tburm looks good, thanks for the PR

**Pull request merged**
