### PR TITLE
Add catton volume adapter

### PR DESCRIPTION
**Pull request by Cattontech**

### CODE REVIEW

**Comment by llamatester** [comment]
The catton adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs catton
    
    🦙 Running CATTON adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 21 Nov 2024 22:19:53 GMT
    End Date:	Fri, 22 Nov 2024 22:19:53 GMT
    ---------------------------------------------------

**Comment by llamatester** [comment]
The catton adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs catton
    
    🦙 Running CATTON adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 21 Nov 2024 22:27:47 GMT
    End Date:	Fri, 22 Nov 2024 22:27:47 GMT
    ---------------------------------------------------
    
    TON 👇
    Backfill start time: 21/11/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 75.41 k
    Total volume: 101.23 k
    End timestamp: 1732314466 (2024-11-22T22:27:46.000Z)

**Comment by llamatester** [comment]
The catton adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs catton
    
    🦙 Running CATTON adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 23 Nov 2024 11:07:41 GMT
    End Date:	Sun, 24 Nov 2024 11:07:41 GMT
    ---------------------------------------------------
    
    TON 👇
    Backfill start time: 21/11/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 133.93 k
    Total volume: 372.91 k
    End timestamp: 1732446460 (2024-11-24T11:07:40.000Z)

**Comment by g1nt0ki** [comment]
thanks for the PR

**Pull request merged**
