### PR TITLE
add lighter v2

### PR DESCRIPTION
**Pull request by ahmetavc**
Lighter v2 contracts are deployed and we started having volume there

tests are passing; yarn test dexs lighter

### CODE REVIEW

**Comment by llamatester** [comment]
The lighter adapter exports: 
        
 
 _______________________________________
    Dexs for 27/11/2023
    _______________________________________
    
    Version -> V1
    ---------
    ARBITRUM 👇
    Backfill start time: 4/3/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 3499443884.1145983
    Daily volume: 6963635.773170001
    Timestamp: 1701043200
    
    
    Version -> V2
    ---------
    ARBITRUM 👇
    Backfill start time: 12/10/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 31290202.46022705
    Daily volume: 250321.180426
    Timestamp: 1701043200
    
    
    Done in 3.09s.

**Comment by dtmkeng** [comment]
could you create new file for v2 ?

**Comment by ahmetavc** [comment]
> could you create new file for v2 ?

where should I place BreakdownAdapter then? or use two different simple adapter?

**Comment by ahmetavc** [comment]
> > > could you create new file for v2 ?
> > 
> > 
> > where should I place BreakdownAdapter then? or use two different simple adapter?
> 
> just create folder `lighter-v2` under `dexs` and file `index.ts` under `lighter-v2`

Screen Shot 2023-11-28 at 3 34 15 PM

will it be shown like this with two different folders?

**Comment by dtmkeng** [comment]
yeah we can group with our config

**Comment by ahmetavc** [comment]
> yeah we can group with our config

thanks, done

**Comment by llamatester** [comment]
The lighter adapter exports: 
        
 
 _______________________________________
    Dexs for 27/11/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 4/3/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 3499443884.11463
    Daily volume: 6963635.773170001
    Timestamp: 1701043200
    
    
    
    
    Done in 3.09s.

**Comment by llamatester** [comment]
The lighterv2 adapter exports: 
        
 
 _______________________________________
    Dexs for 27/11/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 12/10/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 31290202.460227054
    Daily volume: 250321.180426
    Timestamp: 1701043200
    
    
    
    
    Done in 2.59s.

**Comment by dtmkeng** [comment]
is there tvl adapter for v2 ?

**Comment by ahmetavc** [comment]
> is there tvl adapter for v2 ?

no, since lighter is an orderbook based exchange.

i am checking the defillama website and its seems like our volume is pretty low right now, did you merge both versions? we need v1 too since most of the volume is still there

**Comment by dtmkeng** [comment]
we create adapter for v2 and tvl is 0, is it okay ?

**Comment by ahmetavc** [comment]
> we create adapter for v2 and tvl is 0, is it okay ?

i see tvl value on the website, I am not sure where do you get this for v1

**Comment by ahmetavc** [comment]
> > we create adapter for v2 and tvl is 0, is it okay ?
> 
> i see tvl value on the website, I am not sure where do you get this for v1

i believe you guys are handl

> > > we create adapter for v2 and tvl is 0, is it okay ?
> > 
> > 
> > i see tvl value on the website, I am not sure where do you get this for v1
> 
> https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/lighter/index.js

hmm, i didnt wrote this piece of code

**Comment by dtmkeng** [comment]
> > > we create adapter for v2 and tvl is 0, is it okay ?
> > 
> > 
> > i see tvl value on the website, I am not sure where do you get this for v1
> 
> i believe you guys are handl
> 
> > > > we create adapter for v2 and tvl is 0, is it okay ?
> > > 
> > > 
> > > i see tvl value on the website, I am not sure where do you get this for v1
> > 
> > 
> > https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/lighter/index.js
> 
> hmm, i didnt wrote this piece of code

idk, you can open pr for update tvl

**Comment by ahmetavc** [comment]
> > > > we create adapter for v2 and tvl is 0, is it okay ?
> > > 
> > > 
> > > i see tvl value on the website, I am not sure where do you get this for v1
> > 
> > 
> > i believe you guys are handl
> > > > > we create adapter for v2 and tvl is 0, is it okay ?
> > > > 
> > > > 
> > > > i see tvl value on the website, I am not sure where do you get this for v1
> > > 
> > > 
> > > https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/lighter/index.js
> > 
> > 
> > hmm, i didnt wrote this piece of code
> 
> idk, you can open pr for update tvl

ok, its not important for now

**Comment by dtmkeng** [comment]
which name do you need for v2 ?

**Comment by ahmetavc** [comment]
> which name do you need for v2 ?

lighter v2

**Comment by ahmetavc** [comment]
hey @dtmkeng i am able to see lighter v2 on the website but they seem as separated apps, can you merge them under the lighter name as v1 and v2 like uniswap?

**Pull request merged**
