### PR TITLE
add astroport dex dailyVolume

### PR DESCRIPTION
**Pull request by miclondev**

### CODE REVIEW

**Comment by llamatester** [comment]
The astroport adapter exports: 
        
 
 _______________________________________
    Dexs for 5/7/2023
    _______________________________________
    
    TERRA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1688515200
    Daily volume: 279561.9885
    
    
    INJECTIVE 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1688515200
    Daily volume: 139529.7445
    
    
    NEUTRON 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1688515200
    Daily volume: 830454.8587
    
    
    
    
    Done in 3.64s.

**Comment by dtmkeng** [comment]
wow, is there old data from backfill sine May ?

**Comment by miclondev** [comment]
> wow, is there old data from backfill sine May 2022?

The data is there, just need to add some aggregation queries, will put up another PR once the endpoint can handle historical data.

**Comment by dtmkeng** [comment]
> > wow, is there old data from backfill sine May 2022?
> 
> The data is there, just need to add some aggregation queries, will put up another PR once the endpoint can handle historical data.

okay thank you

**Pull request merged**
