### PR TITLE
add new chain data

### PR DESCRIPTION
**Pull request by miler012**
hi,
we have more chain deployed.
and the fee data need merge

### CODE REVIEW

**Comment by llamatester** [comment]
The satori adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs satori
    
    🦙 Running SATORI adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 11 Aug 2024 00:00:00 GMT
    End Date:	Mon, 12 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    [Error: Request failed with status code 403] {
      url: 'https://base.satori.finance/api/data-center/pub/overview/integration',
      method: 'POST',
      axiosError: 'Forbidden',
      chain: 'base'
    }

**Comment by miler012** [comment]
we release the ip check for our api.
how to test again?

**Comment by llamatester** [comment]
The satori adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs satori
    
    🦙 Running SATORI adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 11 Aug 2024 00:00:00 GMT
    End Date:	Mon, 12 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    POLYGON_ZKEVM 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 8.10 B
    Daily volume: 820
    Daily fees: 0
    Daily revenue: 0
    End timestamp: 1723448372232 (+056583-11-27T02:57:12.000Z)
    
    
    ERA 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 44.08 B
    Daily volume: 158.63 M
    Daily fees: 182
    Daily revenue: 182
    End timestamp: 1723448372730 (+056583-11-27T03:05:30.000Z)
    
    
    LINEA 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 87.49 M
    Daily volume: 665.14 k
    Daily fees: 67
    Daily revenue: 67
    End timestamp: 1723448375734 (+056583-11-27T03:55:34.000Z)
    
    
    SCROLL 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 98.05 M
    Daily volume: 55.17 k
    Daily fees: 16
    Daily revenue: 16
    End timestamp: 1723448373271 (+056583-11-27T03:14:31.000Z)
    
    
    BASE 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 64.50 M
    Daily volume: 257.20 k
    Daily fees: 130
    Daily revenue: 130
    End timestamp: 1723448371328 (+056583-11-27T02:42:08.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 337.52 k
    Daily volume: 2.56 k
    Daily fees: 1
    Daily revenue: 1
    End timestamp: 1723448374676 (+056583-11-27T03:37:56.000Z)
    
    
    XLAYER 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 5.19 M
    Daily volume: 0
    Daily fees: 0
    Daily revenue: 0
    End timestamp: 1723448372820 (+056583-11-27T03:07:00.000Z)

**Comment by miler012** [comment]
thanks

**Pull request merged**
