### PR TITLE
fix: rename kizuna to kim and update subgraph url

### PR DESCRIPTION
**Pull request by agileurbanite**
fix: rename kizuna to kim and update subgraph url

### CODE REVIEW

**Comment by dtmkeng** [comment]
kizuna is for v1 you should new adapter name kim for v2

**Comment by agileurbanite** [comment]
https://defillama.com/protocol/kim-exchange

**Comment by dtmkeng** [comment]
i mean current adapter you modify is v1 and new endpoint is for v2 you should create new adapter for v2 instead modify v1
image

**Comment by agileurbanite** [comment]
I see okay will do that and close this PR

**Pull request closed without merging**
