### PR TITLE
BlueMove team added BlueMove volume adapter

### PR DESCRIPTION
**Pull request by business-bluemove**
Hi DeFiLla Team

The blueMove team just would like to send a request to merge our Volume adapter for tracking our trading volume

Thanks and Best Regards

### CODE REVIEW

**Comment by llamatester** [comment]
The blue-move-mart adapter exports: 
        
 
 _______________________________________
    Dexs for 26/12/2022
    _______________________________________
    
    APTOS 👇
    Backfill start time: 20/10/2022
    NO METHODOLOGY SPECIFIED
    Block: undefined
    Timestamp: 1672012800
    Total volume: 1485625.7300000007
    Daily volume: 3042.2700000000186
    
    
    
    
    Done in 3.78s.

**Comment by dtmkeng** [comment]
@business-bluemove  hi could you remove change on package-lock.json and yarn.lock ?

**Comment by llamatester** [comment]
The blue-move-mart adapter exports: 
        
 
 _______________________________________
    Dexs for 27/12/2022
    _______________________________________
    
    APTOS 👇
    Backfill start time: 20/10/2022
    NO METHODOLOGY SPECIFIED
    Block: undefined
    Timestamp: 1672099200
    Total volume: 1487647.1000000008
    Daily volume: 2021.3700000001118
    
    
    
    
    Done in 4.31s.

**Comment by llamatester** [comment]
The blue-move-mart adapter exports: 
        
 
 _______________________________________
    Dexs for 27/12/2022
    _______________________________________
    
    APTOS 👇
    Backfill start time: 20/10/2022
    NO METHODOLOGY SPECIFIED
    Block: undefined
    Timestamp: 1672099200
    Total volume: 1487647.1000000008
    Daily volume: 2021.3700000001118
    
    
    
    
    Done in 4.17s.

**Comment by business-bluemove** [comment]
> @business-bluemove hi could you remove change on package-lock.json and yarn.lock ?
> Done
> * and I have a question about volume, Is this volume from NFT trade?
Exactly. This is our NFT trading volume

**Comment by business-bluemove** [comment]
Hi DeFiLlama team

I just corrected something in your comments. Could you please help me review it again?

Thanks!

**Pull request merged**
