### PR TITLE
add total and daily fees for xfai dex

### PR DESCRIPTION
**Pull request by ChainlessCoder**

### CODE REVIEW

**Comment by llamatester** [comment]
The xfai adapter exports: 
        
 
 _______________________________________
    Dexs for 25/11/2023
    _______________________________________
    
    LINEA 👇
    Backfill start time: 18/8/2023
    Total fees: {
      "0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "311380",
      "0xA219439258ca9da29E9Cc4cE5596924745e12B93": "81159504",
      "0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "777388334",
      "0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "24526787632686838540",
      "0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "74676892654204830501118",
      "0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "141712012123972988",
      "0x8C56017B172226fE024dEa197748FC1eaccC82B1": "11922279838133276515066",
      "0xe322E20738386766F769b0a6083f4141083d26d0": "2542202418701693172",
      "0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "574208406395442",
      "0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "5130806321653850",
      "0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "17007654765337116",
      "0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "392960140003611846",
      "0x1578f35532FA091EcED8638730F9dB829930ce16": "1424436595951755304",
      "0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "371234218999850"
    }
    Daily fees: {
      "0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "18792",
      "0xA219439258ca9da29E9Cc4cE5596924745e12B93": "17724384",
      "0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "202826572",
      "0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "3206124132556416108",
      "0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "67067398121292253943352",
      "0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "10024117513550962",
      "0x8C56017B172226fE024dEa197748FC1eaccC82B1": "743136080815846102146",
      "0xe322E20738386766F769b0a6083f4141083d26d0": "0",
      "0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "444119928250678",
      "0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "76333319267192",
      "0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "7721538541416684",
      "0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "52470468539273900",
      "0x1578f35532FA091EcED8638730F9dB829930ce16": "415313925771352888",
      "0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "213630082178854"
    }
    
    
    
    
    Done in 4.58s.

**Comment by llamatester** [comment]
The xfai adapter exports: 
        
 
 _______________________________________
    Dexs for 25/11/2023
    _______________________________________
    
    LINEA 👇
    Backfill start time: 18/8/2023
    Total fees: {
      "0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "311380",
      "0xA219439258ca9da29E9Cc4cE5596924745e12B93": "81159504",
      "0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "777388334",
      "0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "24526787632686838540",
      "0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "74676892654204830501118",
      "0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "141712012123972988",
      "0x8C56017B172226fE024dEa197748FC1eaccC82B1": "11922279838133276515066",
      "0xe322E20738386766F769b0a6083f4141083d26d0": "2542202418701693172",
      "0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "574208406395442",
      "0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "5130806321653850",
      "0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "17007654765337116",
      "0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "392960140003611846",
      "0x1578f35532FA091EcED8638730F9dB829930ce16": "1424436595951755304",
      "0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "371234218999850"
    }
    Daily fees: {
      "0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "18792",
      "0xA219439258ca9da29E9Cc4cE5596924745e12B93": "17724384",
      "0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "202826572",
      "0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "3206124132556416108",
      "0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "67067398121292253943352",
      "0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "10024117513550962",
      "0x8C56017B172226fE024dEa197748FC1eaccC82B1": "743136080815846102146",
      "0xe322E20738386766F769b0a6083f4141083d26d0": "0",
      "0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "444119928250678",
      "0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "76333319267192",
      "0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "7721538541416684",
      "0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "52470468539273900",
      "0x1578f35532FA091EcED8638730F9dB829930ce16": "415313925771352888",
      "0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "213630082178854"
    }
    
    
    
    
    Done in 6.99s.

**Comment by ChainlessCoder** [comment]
I see that in https://github.com/DefiLlama/dimension-adapters/blob/master/adapters/types.ts#L67 you have disabled returning token balances for daily/total volume. Will you support returning token balances as calculating usdc price on-chain is very cumbersome?

**Comment by dtmkeng** [comment]
yes it can support token breakdown, value is `chain:token_address`: `value_div_by_token_decimal`

**Comment by dtmkeng** [comment]
could you fix ?

**Comment by dtmkeng** [comment]
or you can return value of usd

**Comment by llamatester** [comment]
The xfai adapter exports: 
        
 
 _______________________________________
    Dexs for 26/11/2023
    _______________________________________
    
    LINEA 👇
    Backfill start time: 18/8/2023
    Total fees: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "0",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "100.96",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "996.67",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "31.7",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "74676.89",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "0.15",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "12440.35",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "2.54",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "0",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "0.02",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "0.39",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "1.73",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "0"
    }
    Daily fees: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "0",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "19.8",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "219.28",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "7.18",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "0",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "0.01",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "518.07",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "0",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "0",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "0",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "0",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "0.31",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "0"
    }
    Total volume: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "1.61",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "50484.48",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "498337.8",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "15853.66",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "37338446.32",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "78.88",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "6220178.5",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "1271.1",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "0.3",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "2.56",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "10.48",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "196.48",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "868.57",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "0.24"
    }
    Daily volume: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "0.05",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "9904.73",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "109643.63",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "3590.27",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "0",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "8.02",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "259038.58",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "0",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "0.01",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "1.98",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "0",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "156.35",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "0.06"
    }
    
    
    
    
    Done in 4.93s.

**Comment by llamatester** [comment]
The xfai adapter exports: 
        
 
 _______________________________________
    Dexs for 26/11/2023
    _______________________________________
    
    LINEA 👇
    Backfill start time: 18/8/2023
    Total fees: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "0.333",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "11218.667",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "110741.667",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "3523.000",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "8297432.444",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "17.444",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "1382261.889",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "282.444",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "0.000",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0.556",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "2.222",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "43.556",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "193.000",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "0.000"
    }
    Daily fees: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "0.000",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "2201.000",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "24365.222",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "797.778",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "0.000",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "1.778",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "57564.111",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "0.000",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "0.000",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0.000",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "0.333",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "0.000",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "34.667",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "0.000"
    }
    Total volume: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "179.556",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "5609387.333",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "55370866.889",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "1761518.333",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "4148716258.556",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "8764.444",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "691130945.222",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "141233.444",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "33.556",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "285.000",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "1165.222",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "21831.111",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "96507.889",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "27.667"
    }
    Daily volume: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "6.556",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "1100526.000",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "12182626.111",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "398919.111",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "0.000",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "891.556",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "28782065.333",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "0.000",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "1.667",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0.000",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "220.444",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "0.000",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "17372.556",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "7.111"
    }
    
    
    
    
    Done in 4.35s.

**Comment by llamatester** [comment]
The xfai adapter exports: 
        
 
 _______________________________________
    Dexs for 26/11/2023
    _______________________________________
    
    LINEA 👇
    Backfill start time: 18/8/2023
    Total fees: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "0.333",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "11218.667",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "110741.667",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "3523.000",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "8297432.444",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "17.444",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "1382261.889",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "282.444",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "0.000",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0.556",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "2.222",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "43.556",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "193.000",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "0.000"
    }
    Daily fees: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "0.000",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "2201.000",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "24365.222",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "797.778",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "0.000",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "1.778",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "57564.111",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "0.000",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "0.000",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0.000",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "0.333",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "0.000",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "34.667",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "0.000"
    }
    Total volume: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "179.556",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "5609387.333",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "55370866.889",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "1761518.333",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "4148716258.556",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "8764.444",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "691130945.222",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "141233.444",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "33.556",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "285.000",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "1165.222",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "21831.111",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "96507.889",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "27.667"
    }
    Daily volume: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "6.556",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "1100526.000",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "12182626.111",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "398919.111",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "0.000",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "891.556",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "28782065.333",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "0.000",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "1.667",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0.000",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "220.444",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "0.000",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "17372.556",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "7.111"
    }
    
    
    
    
    Done in 4.56s.

**Comment by dtmkeng** [comment]
hmm i guess our rpc does not support get data by block number, is there way to get fees and volume from logs ?

**Comment by ChainlessCoder** [comment]
Could you provide an answer to the last question?

**Comment by llamatester** [comment]
The xfai adapter exports: 
        
 
 _______________________________________
    Dexs for 7/12/2023
    _______________________________________
    
    LINEA 👇
    Backfill start time: 18/8/2023
    Total fees: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "0.444",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "14227.556",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "161628.000",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "4525.111",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "9340954.778",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "18.556",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "1535389.778",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "282.444",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "0.000",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0.556",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "2.222",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "43.556",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "370.000",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "0.556",
      "linea:0xB5beDd42000b71FddE22D3eE8a79Bd49A568fC8F": "0.111",
      "linea:0x1E1F509963A6D33e169D9497b11c7DbFe73B7F13": "88.889",
      "linea:0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376": "97.111"
    }
    Daily fees: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "0.000",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "127.444",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "2011.111",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "61.111",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "0.000",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "0.000",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "37529.333",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "0.000",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "0.000",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0.000",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "0.000",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "0.000",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "13.000",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "0.000",
      "linea:0xB5beDd42000b71FddE22D3eE8a79Bd49A568fC8F": "0.111",
      "linea:0x1E1F509963A6D33e169D9497b11c7DbFe73B7F13": "70.778",
      "linea:0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376": "71.778"
    }
    Total volume: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "230.889",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "7113812.111",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "80814007.889",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "2262592.111",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "4670477428.111",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "9325.778",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "767694893.000",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "141233.444",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "36.222",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "285.111",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "1165.222",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "21831.111",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "185052.111",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "318.667",
      "linea:0xB5beDd42000b71FddE22D3eE8a79Bd49A568fC8F": "108.778",
      "linea:0x1E1F509963A6D33e169D9497b11c7DbFe73B7F13": "44492.778",
      "linea:0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376": "48581.556"
    }
    Daily volume: {
      "linea:0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4": "26.778",
      "linea:0xA219439258ca9da29E9Cc4cE5596924745e12B93": "63728.333",
      "linea:0x176211869cA2b568f2A7D4EE941E073a821EE1ff": "1005592.333",
      "linea:0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5": "30565.889",
      "linea:0x99AD925C1Dc14Ac7cc6ca1244eeF8043C74E99d5": "0.000",
      "linea:0xd2bc272EA0154A93bf00191c8a1DB23E67643EC5": "0.000",
      "linea:0x8C56017B172226fE024dEa197748FC1eaccC82B1": "18764692.111",
      "linea:0xe322E20738386766F769b0a6083f4141083d26d0": "0.000",
      "linea:0x2442Bd7AE83b51F6664De408A385375fe4a84F52": "0.000",
      "linea:0xe516a5CFf996cc399EFBb48355FD5Ab83438E7a9": "0.000",
      "linea:0x0A79e44c99505c7f388CA30c787ff97217E73ecC": "0.000",
      "linea:0x9D36f49D3d42B3A9BcC0f5Ac76fF8ef78fB2bC01": "0.000",
      "linea:0x1578f35532FA091EcED8638730F9dB829930ce16": "6510.000",
      "linea:0x93F4d0ab6a8B4271f4a28Db399b5E30612D21116": "37.889",
      "linea:0xB5beDd42000b71FddE22D3eE8a79Bd49A568fC8F": "57.778",
      "linea:0x1E1F509963A6D33e169D9497b11c7DbFe73B7F13": "35438.222",
      "linea:0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376": "35939.889"
    }
    
    
    
    
    Done in 6.87s.

**Comment by ChainlessCoder** [comment]
Can you reset the fees and volume data? The latest changes require a recalculation of the fees & volume as the previous ones where incorrect

**Pull request merged**
