### PR TITLE
Add Sharpe Earn in Services

### PR DESCRIPTION
**Pull request by Anirudha619**
Project Name : Sharpe Earn

Information: 
Sharpe is an AI-powered DeFi automation and execution environment designed for pro-traders and institutions. Our unified platform streamlines DeFi asset management, execution, and custody and provides traders with a comprehensive environment for earning yields, building strategies, advanced DEX trading, lending automation and so much more.

Category: Services

Website : https://www.sharpe.ai/

Twitter: https://twitter.com/SharpeLabs

Logo:
image

### CODE REVIEW

**Comment by llamatester** [comment]
The sharpe-earn adapter exports: 
        
 
 _______________________________________
    Fees for 18/3/2024
    _______________________________________
    
    Error: [base]Value: [object Object] dailyFees is NaN
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:48:49)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:59:21 {
      chain: 'base'
    }
    Done in 1029.08s.

**Comment by llamatester** [comment]
The sharpe-earn adapter exports: 
        
 
 _______________________________________
    Fees for 18/3/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 19/3/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 47
    Timestamp: 1710806399 (2024-03-18T23:59:59.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 19/3/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 142
    Timestamp: 1710806399 (2024-03-18T23:59:59.000Z)
    
    
    BASE 👇
    Backfill start time: 19/3/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 211
    Timestamp: 1710806399 (2024-03-18T23:59:59.000Z)
    
    
    
    
    Done in 13.61s.

**Comment by Define101** [comment]
Should we replace the logo? 
We have replaced the website and twitter (should be live in 1 hour)
https://defillama.com/protocol/sharpe-magnum

**Comment by Define101** [comment]
It will not be there
Since we are not tracking any TVL
Only fees

**Pull request merged**
