### PR TITLE
Feat: Fluid magnifier fees revenues + refacto

### PR DESCRIPTION
**Pull request by 0xpeluche**
**`npm run test fees fluid 1733011200` :** 

image

### CODE REVIEW

**Comment by llamatester** [comment]
The fluid adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees fluid
    
    🦙 Running FLUID adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 04 Dec 2024 06:35:08 GMT
    End Date:	Thu, 05 Dec 2024 06:35:08 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 18/2/2024
    Daily fees: 102.20 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 19.54 k
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1733380507 (2024-12-05T06:35:07.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 3/7/2024
    Daily fees: 6.24 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 624
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1733380507 (2024-12-05T06:35:07.000Z)
    
    
    BASE 👇
    Backfill start time: 12/8/2024
    Daily fees: 3.20 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 320
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1733380507 (2024-12-05T06:35:07.000Z)

**Comment by bergben** [comment]
Hi @0xpeluche referring to https://github.com/DefiLlama/dimension-adapters/pull/2166#issuecomment-2519697852

Sure thank you. I checked for various days, there is a difference for fees because of the change how fromBlock and toBlock is defined. This is fine IMO. But would be good to run a backfill and check for any spikes. Do you have some easy way to do this? This is the best way to check that the data will be correct during different configs, e.g. magnifier revenue is not always active, revenue collection / rebalances can be triggered but most days will not [...]

The [last time the code was refactored](https://github.com/DefiLlama/dimension-adapters/commit/d5bce1af08a7f549fdc5e7791ab5329cceb0ed95) it introduced a few bugs which slowly came up over time and had to be fixed :sweat_smile:

**Comment by 0xpeluche** [comment]
We are currently reworking our refill scripts, which have had some issues recently, so I don’t have a proper way to perform a clean backfill in dry_run mode at the moment to ensure there are no discrepancies or spikes compared to the old code. I tested a few dates, but there's no way to do it properly to check all the dates. I could potentially leave the PR on WIP status while we fix our scripts, and then come back to the PR to test everything afterward? This would avoid refilling the entire history and pushing errors to the end user

**Comment by bergben** [comment]
@0xpeluche any ETA on how long that would take? 
Move fast approach would be making the code live, running backfill, check data right after compared to data before, if anything seems off revert back to the old code, backfill and wait until proper testing can be done with fixed scripts. 
I feel likely it should be fine, I checked for some days where we recently had bugs and all those were fine.

**Pull request merged**
