### PR TITLE
Keller Sprinkler info updated (CL)

### PR DESCRIPTION
**Pull request by 0xArata**
Volume and fees info updated with the new Concentrated Liquidity solution from Équilibre LABS

### CODE REVIEW

**Comment by llamatester** [comment]
The keller adapter exports: 
        
 
 _______________________________________
    Dexs for 9/5/2024
    _______________________________________
    
    Version -> V2
    ---------
    SCROLL 👇
    Backfill start time: 19/3/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1715299199 (2024-05-09T23:59:59.000Z)
    Daily volume: 1.53 k
    
    
    Version -> SPRINKLER
    ---------
    SCROLL 👇
    Backfill start time: 3/4/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1715299199 (2024-05-09T23:59:59.000Z)
    Daily volume: 0

**Comment by llamatester** [comment]
The keller adapter exports: 
        
 
 _______________________________________
    Fees for 10/5/2024
    _______________________________________
    
    Version -> V2
    ---------
    SCROLL 👇
    Backfill start time: 19/3/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 2
    Daily holders revenue: 2
    Daily bribes revenue: 0
    Timestamp: 1715355894 (2024-05-10T15:44:54.000Z)
    
    
    Version -> V3
    ---------
    SCROLL 👇
    Backfill start time: 3/4/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1715355894 (2024-05-10T15:44:54.000Z)
    Daily fees: 0
    Daily user fees: 0
    Daily revenue: 0
    Daily holders revenue: 0

**Comment by dtmkeng** [comment]
could you create new file adapter for v3 ?

**Comment by llamatester** [comment]
The keller adapter exports: 
        
 
 _______________________________________
    Dexs for 30/5/2024
    _______________________________________
    
    TypeError: Cannot read properties of undefined (reading 'fromTimestamp')
        at /home/runner/work/dimension-adapters/dimension-adapters/helpers/dexVolumeLogs.ts:93:73
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:25)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'scroll'
    }

**Comment by llamatester** [comment]
The keller adapter exports: 
        
 
 _______________________________________
    Fees for 30/5/2024
    _______________________________________
    
    SCROLL 👇
    Backfill start time: 19/3/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1717092761 (2024-05-30T18:12:41.000Z)
    Daily fees: 1
    Daily bribes revenue: 1

**Comment by llamatester** [comment]
The keller-cl adapter exports: 
        
 
 _______________________________________
    Dexs for 30/5/2024
    _______________________________________
    
    TypeError: Cannot read properties of undefined (reading 'fromTimestamp')
        at /home/runner/work/dimension-adapters/dimension-adapters/helpers/dexVolumeLogs.ts:192:73
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:25)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'scroll'
    }

**Comment by llamatester** [comment]
The keller-cl adapter exports: 
        
 
 _______________________________________
    Fees for 30/5/2024
    _______________________________________
    
    SCROLL 👇
    Backfill start time: 10/4/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1717092878 (2024-05-30T18:14:38.000Z)
    Daily fees: 116
    Daily holders revenue: 116
    Daily protocol revenue: 0

**Pull request merged**
