### PR TITLE
BitFlow dexs adapter

### PR DESCRIPTION
**Pull request by rodrigoeduardo**
- Created [BitFlow](https://bitflow.finance) volume adapter.

### CODE REVIEW

**Comment by llamatester** [comment]
The bitflow adapter exports: 
        
 
 _______________________________________
    Dexs for 12/2/2024
    _______________________________________
    
    TypeError: Cannot read properties of undefined (reading 'length')
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/dexs/bitflow/index.ts:35:57)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async /home/runner/work/dimension-adapters/dimension-adapters/helpers/customBackfill.ts:14:24
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:25:42)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:48:21 {
      chain: 'stacks'
    }
    Done in 5.84s.

**Comment by dtmkeng** [comment]
@rodrigoeduardo  hi thx for pr, volume adapter is require daily swap volume seem you contain it use tvl field 
is there way to get daily swap volume ?

**Comment by rodrigoeduardo** [comment]
> @rodrigoeduardo hi thx for pr, volume adapter is require daily swap volume seem you contain it use tvl field is there way to get daily swap volume ?

Is it required for general listing or its required only if we have the adapter settings to include volume?

**Comment by rodrigoeduardo** [comment]
> > > @rodrigoeduardo hi thx for pr, volume adapter is require daily swap volume seem you contain it use tvl field is there way to get daily swap volume ?
> > 
> > 
> > Hey. Is swap volume required for general listing or its required only if we have the adapter settings to include volume?
> 
> what do you mean ?

in order to list Bitflow project, is required to provide daily swap volume information?

**Comment by llamatester** [comment]
The bitflow adapter exports: 
        
 
 _______________________________________
    Dexs for 14/2/2024
    _______________________________________
    
    TypeError: Cannot read properties of undefined (reading 'length')
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/dexs/bitflow/index.ts:36:57)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async /home/runner/work/dimension-adapters/dimension-adapters/helpers/customBackfill.ts:14:24
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:25:42)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:48:21 {
      chain: 'stacks'
    }
    Done in 4.34s.

**Comment by dtmkeng** [comment]
> > > > @rodrigoeduardo hi thx for pr, volume adapter is require daily swap volume seem you contain it use tvl field is there way to get daily swap volume ?
> > > 
> > > 
> > > Hey. Is swap volume required for general listing or its required only if we have the adapter settings to include volume?
> > 
> > 
> > what do you mean ?
> 
> in order to list Bitflow project, is required to provide daily swap volume information?

yes if you create adapter for trade dexs volume it require dailyVolume,

**Comment by rodrigoeduardo** [comment]
> > > > > @rodrigoeduardo hi thx for pr, volume adapter is require daily swap volume seem you contain it use tvl field is there way to get daily swap volume ?
> > > > 
> > > > 
> > > > Hey. Is swap volume required for general listing or its required only if we have the adapter settings to include volume?
> > > 
> > > 
> > > what do you mean ?
> > 
> > 
> > in order to list Bitflow project, is required to provide daily swap volume information?
> 
> yes if you create adapter for track dexs volume it require dailyVolume,

I see. Is there a way that we could add BitFlow to the Stacks section and only display TVL stats for now?

**Comment by dtmkeng** [comment]
> > > > > > @rodrigoeduardo hi thx for pr, volume adapter is require daily swap volume seem you contain it use tvl field is there way to get daily swap volume ?
> > > > > 
> > > > > 
> > > > > Hey. Is swap volume required for general listing or its required only if we have the adapter settings to include volume?
> > > > 
> > > > 
> > > > what do you mean ?
> > > 
> > > 
> > > in order to list Bitflow project, is required to provide daily swap volume information?
> > 
> > 
> > yes if you create adapter for track dexs volume it require dailyVolume,
> 
> I see. Is there a way that we could add BitFlow to the Stacks section and only display TVL stats for now?

this repo for tvl https://github.com/DefiLlama/DefiLlama-Adapters

**Pull request closed without merging**
