### PR TITLE
Adding dex and fee dimensions for Archly

### PR DESCRIPTION
**Pull request by tec05**

### CODE REVIEW

**Comment by llamatester** [comment]
The archly-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 24/1/2023
    _______________________________________
    
    TELOS 👇
    Backfill start time: 25/11/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1674604798
    Block: 259311768
    Total volume: 77464.21150722356
    Daily volume: 2117.845994371105839636296054062269
    
    
    
    
    Done in 23.70s.

**Comment by llamatester** [comment]
The archly-finance.ts adapter exports: 
        
 
 _______________________________________
    Fees for 24/1/2023
    _______________________________________
    
    TELOS 👇
    Backfill start time: 25/11/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1674604798
    Daily fees: 0.6353537983113317518908888162186807
    Daily protocol revenue: 0.6353537983113317518908888162186807
    Total fees: 23.239263452167068
    Total protocol revenue: 23.239263452167068
    
    
    
    
    Done in 21.40s.

**Comment by 0xtawa** [comment]
Hi, ty for the PR!

Checked the code and looks fine. I will kindly ask you to:
1. Change the code from 2 adapters to only one that includes the dimensions for DEX volume and fees (I would do it myself but I can't commit in your branch). This way it's easier to maintain and can benefit from the fees breakdown for our current/next dashboards/charts. You can copy paste the below snippet.

```typescript
import { Adapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { getStartTimestamp } from "../../helpers/getStartTimestamp";
import { getGraphDimensions } from "../../helpers/getUniSubgraph";

const endpoints = {
    [CHAIN.TELOS]: "http://api.archly.fi/subgraphs/name/archly/amm",
};

const graphFetch = getGraphDimensions({
    graphUrls: endpoints,
    totalVolume: {
        factory: "factories"
    },
    dailyVolume: {
        factory: "dayData"
    },
    feesPercent: {
        type: 'volume',
        Fees: 0.3,
        UserFees: 0.3,
        //Revenue: ,
        //SupplySideRevenue: ,
        //HoldersRevenue: ,
        //ProtocolRevenue: ,
    }
});

const adapter: Adapter = {
    adapter: {
        [CHAIN.TELOS]: {
            fetch: graphFetch(CHAIN.TELOS),
            start: getStartTimestamp({
                endpoints: endpoints,
                chain: CHAIN.TELOS,
                dailyDataField: "dayDatas"
            }),
            meta: {
                methodology: {
                    Fees: "The trading fees 0.03%, and can be adjusted for up to 0.1%.",
                    UserFees: "Currently users pay a trading fee of 0.03%",
                    // Revenue: "Protocol revenue is X% trading fees",
                    // SupplySideRevenue: "LPs earn x% trading fees",
                    // HoldersRevenue: "Holders have no revenue",
                    // ProtocolRevenue: "Treasure revenue is..."
                }
            }
        }
    }
};

export default adapter;
```

2. Please breakdown the fees and add a small description. In the object `feesPercent` from the above snippet please indicate in percentage of each attribute, if token holders or treasury earns nothing from the fees, then set a 0, if earns a part of the fees then set the number in percentage (0.03% -> `0.03`). Commented the possible values. For a description of what means each type of fee you can take a look [here](https://docs.llama.fi/list-your-project/other-dashboards/dimensions).
In the `methodology` object please add a small description of how the fee is calculated, wrote some examples

3. Ready to be listed🚀

**Comment by tec05** [comment]
Thank you for reviewing the PR. To clarify, I should delete the adapter under fees and then replace the code in the dex adapter with the code above? Doing this will have the same result as having the two adapters?

**Comment by llamatester** [comment]
The archly-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 24/1/2023
    _______________________________________
    
    TELOS 👇
    Backfill start time: 25/11/2022
    Timestamp: 1674604798
    Block: 259311867
    Total volume: 77464.21150722356
    Daily volume: 2117.845994371105839636296054062269
    Daily fees: 6.353537983113317518908888162186807
    └─ Methodology: The trading fees are 0.03%, and can be adjusted from 0.01% up to 0.1%.
    Total fees: 232.39263452167068
    └─ Methodology: The trading fees are 0.03%, and can be adjusted from 0.01% up to 0.1%.
    Daily user fees: 6.353537983113317518908888162186807
    └─ Methodology: Currently users pay a trading fee of 0.03%.
    Total user fees: 232.39263452167068
    └─ Methodology: Currently users pay a trading fee of 0.03%.
    Daily holders revenue: 6.353537983113317518908888162186807
    └─ Methodology: veArc voters receive all protocol fees.
    Total holders revenue: 232.39263452167068
    └─ Methodology: veArc voters receive all protocol fees.
    Daily revenue: 0
    └─ Methodology: The protocol does not earn any revenue from trading fees.
    Total revenue: 0
    └─ Methodology: The protocol does not earn any revenue from trading fees.
    Daily supply side revenue: 0
    └─ Methodology: LPs do not earn any revenue from trading fees.
    Total supply side revenue: 0
    └─ Methodology: LPs do not earn any revenue from trading fees.
    Daily protocol revenue: 0
    └─ Methodology: Treasury does not earn any revenue from trading fees.
    Total protocol revenue: 0
    └─ Methodology: Treasury does not earn any revenue from trading fees.
    
    
    
    
    Done in 22.25s.

**Comment by llamatester** [comment]
The archly-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 24/1/2023
    _______________________________________
    
    TELOS 👇
    Backfill start time: 25/11/2022
    Timestamp: 1674604798
    Block: 259311884
    Total volume: 77464.21150722356
    Daily volume: 2117.845994371105839636296054062269
    Daily fees: 6.353537983113317518908888162186807
    └─ Methodology: The trading fees are 0.03%, and can be adjusted from 0.01% up to 0.1%.
    Total fees: 232.39263452167068
    └─ Methodology: The trading fees are 0.03%, and can be adjusted from 0.01% up to 0.1%.
    Daily user fees: 6.353537983113317518908888162186807
    └─ Methodology: Currently users pay a trading fee of 0.03%.
    Total user fees: 232.39263452167068
    └─ Methodology: Currently users pay a trading fee of 0.03%.
    Daily holders revenue: 6.353537983113317518908888162186807
    └─ Methodology: veArc voters receive all protocol fees.
    Total holders revenue: 232.39263452167068
    └─ Methodology: veArc voters receive all protocol fees.
    Daily revenue: 6.353537983113317518908888162186807
    └─ Methodology: All trading fees are paid to veArc voters.
    Total revenue: 232.39263452167068
    └─ Methodology: All trading fees are paid to veArc voters.
    Daily supply side revenue: 0
    └─ Methodology: LPs do not earn any revenue from trading fees, only Arc emission decided by veArc voters.
    Total supply side revenue: 0
    └─ Methodology: LPs do not earn any revenue from trading fees, only Arc emission decided by veArc voters.
    Daily protocol revenue: 0
    └─ Methodology: Treasury does not earn any revenue from trading fees.
    Total protocol revenue: 0
    └─ Methodology: Treasury does not earn any revenue from trading fees.
    
    
    
    
    Done in 21.79s.

**Comment by 0xtawa** [comment]
ty🔥

**Pull request merged**
