### PR TITLE
Add Tigris - WIP 

### PR DESCRIPTION
**Pull request by henrystats**

### CODE REVIEW

**Comment by llamatester** [comment]
The tigris adapter exports: 
        
 
 _______________________________________
    Fees for 9/10/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 13/8/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Daily revenue: 0
    Daily protocol revenue: 0
    Daily holders revenue: 0
    Timestamp: 1696895998
    
    
    POLYGON 👇
    Backfill start time: 19/7/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Daily revenue: 0
    Daily protocol revenue: 0
    Daily holders revenue: 0
    Timestamp: 1696895998
    
    
    
    
    Done in 79.07s.

**Comment by llamatester** [comment]
The tigris adapter exports: 
        
 
 _______________________________________
    Fees for 9/10/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 13/8/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Daily revenue: 0
    Daily protocol revenue: 0
    Daily holders revenue: 0
    Timestamp: 1696895998
    
    
    POLYGON 👇
    Backfill start time: 19/7/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Daily revenue: 0
    Daily protocol revenue: 0
    Daily holders revenue: 0
    Timestamp: 1696895998
    
    
    
    
    Done in 36.53s.

**Comment by dtmkeng** [comment]
look good could you remove change on package yarn lock file
and check  compare date

**Comment by dtmkeng** [comment]
> hola @dtmkeng, I tried to use a similar approach to what gmx used before updating as I want to add tigris to the following dimensions:
> 
> derivatives options & fees
> 
> I was originally using a flask api to try and get the data but then saw that gmx_v2 used a dune query helper and wanted to test that, but for some reason both of these tables returned "0" as volume even though the volume isn't null and the api and query were working.
> 
> Do you know what the issue could be?

you need list this protocol https://defillama.com/protocol/tigris ?

**Pull request closed without merging**
