### PR TITLE
Add YOLO Games

### PR DESCRIPTION
**Pull request by george-lr**
**Name**

YOLO Games

**Description**

The only venue for serious degens seeking serious rewards. Built by a veteran team with a track record of delivering provably fair, fun on-chain games

**Website**

https://yologames.io/

**X (Twitter) link**

https://twitter.com/YOLO_Blast

**Discord server**

https://discord.com/invite/7SHJdtZz37

**Category**

Gaming

**Chain**

Blast

**Logo**

yolo-logo-icon-color-on-dark

### CODE REVIEW

**Comment by llamatester** [comment]
The yologames adapter exports: 
        
 
 _______________________________________
    Fees for 14/4/2024
    _______________________________________
    
    Error: INDEXA_DB not set
        at getConnection (/home/runner/work/dimension-adapters/dimension-adapters/helpers/indexer.ts:10:24)
        at queryIndexer (/home/runner/work/dimension-adapters/dimension-adapters/helpers/indexer.ts:30:22)
        at fetchVolume (/home/runner/work/dimension-adapters/dimension-adapters/fees/yologames/index.ts:7:47)
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/yologames/index.ts:110:5)
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:29:25)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:59:21 {
      chain: 'blast'
    }
    Done in 65.09s.

**Comment by dtmkeng** [comment]
index is support only eth chain

**Comment by george-lr** [comment]
> index is support only eth chain

I see. What method would you recommend to fetch transaction information that is also available on Blast?

I was able to fetch event logs with `getLogs` but also need data from the associated tx.

**Comment by dtmkeng** [comment]
> > index is support only eth chain
> 
> I see. What method would you recommend to fetch transaction information that is also available on Blast?
> 
> I was able to fetch event logs with `getLogs` but also need data from the associated tx.

yes `getLogs`

**Comment by llamatester** [comment]
The yologames adapter exports: 
        
 
 _______________________________________
    Fees for 17/4/2024
    _______________________________________
    
    BLAST 👇
    Backfill start time: 1/3/2024
    Timestamp: 1713398399 (2024-04-17T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: YOLO Games collects a 1% fee for Moon Or Doom and YOLO winnings, and a 3% fee on Poke The Bear winnings.
    Daily volume: 0
    └─ Methodology: YOLO Games derives volume data from the deposit transactions into all the games.
    
    
    
    
    Done in 65.92s.

**Comment by llamatester** [comment]
The yologames adapter exports: 
        
 
 _______________________________________
    Fees for 17/4/2024
    _______________________________________
    
    BLAST 👇
    Backfill start time: 1/3/2024
    Timestamp: 1713398399 (2024-04-17T23:59:59.000Z)
    Daily fees: 18
    └─ Methodology: YOLO Games collects a 1% fee for Moon Or Doom and YOLO winnings, and a 3% fee on Poke The Bear winnings.
    Daily volume: 1.82 k
    └─ Methodology: YOLO Games derives volume data from the deposit transactions into all the games.
    
    
    
    
    Done in 69.65s.

**Comment by llamatester** [comment]
The yologames adapter exports: 
        
 
 _______________________________________
    Fees for 17/4/2024
    _______________________________________
    
    BLAST 👇
    Backfill start time: 1/3/2024
    Timestamp: 1713398399 (2024-04-17T23:59:59.000Z)
    Daily fees: 55.04 k
    └─ Methodology: YOLO Games collects a 1% fee for Moon Or Doom and YOLO winnings, and a 3% fee on Poke The Bear winnings.
    Daily volume: 5.63 M
    └─ Methodology: YOLO Games derives volume data from the deposit transactions into all the games.
    
    
    
    
    Done in 65.47s.

**Comment by dtmkeng** [comment]
can't collect volume like that we collect only swap volume

**Comment by llamatester** [comment]
The yologames adapter exports: 
        
 
 _______________________________________
    Fees for 17/4/2024
    _______________________________________
    
    BLAST 👇
    Backfill start time: 1/3/2024
    Timestamp: 1713398399 (2024-04-17T23:59:59.000Z)
    Daily fees: 89.11 k
    └─ Methodology: YOLO Games collects a 1% fee for Moon Or Doom and YOLO winnings, and a 3% fee on Poke The Bear winnings.
    
    
    
    
    Done in 72.78s.

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Comment by george-lr** [comment]
> is there tvl adapter ?

Not yet. We plan to add it later on.

**Comment by dtmkeng** [comment]
okay wait tvl adapter

**Review by dtmkeng — APPROVED** [review]

**Comment by george-lr** [comment]
Hello.

Thanks for approving and merging the PR. We noticed a couple issues on DefiLlama's listing of YOLO Games here: https://defillama.com/protocol/yolo-games?fees=true&denomination=ETH&groupBy=weekly

- The monthly fees for March on the website are 1.01k ETH. Our API returns 920.8708 ETH for that same period, which you can verify with this query: https://stats.yologames.io/stats?from=1709251200000&to=1711929600000
- The weekly fees for April 7th are missing. You can check with our API that they should be approximately 383.7307 ETH for the March 31st - April 7th period.
- There are also discrepancies in the weeks of March 10-17th of 22.9 ETH and 17th-24th of 22.2353 ETH.

Note: regarding metodology, we're looking at 00:00 UTC timestamps for the starting and ending date of each period.

Could you share a bit more about how these weekly/monthly values are computed?

**Comment by dtmkeng** [comment]
> Hello.
> 
> Thanks for approving and merging the PR. We noticed a couple issues on DefiLlama's listing of YOLO Games here: https://defillama.com/protocol/yolo-games?fees=true&denomination=ETH&groupBy=weekly
> 
> * The monthly fees for March on the website are 1.01k ETH. Our API returns 920.8708 ETH for that same period, which you can verify with this query: https://stats.yologames.io/stats?from=1709251200000&to=1711929600000
> * The weekly fees for April 7th are missing. You can check with our API that they should be approximately 383.7307 ETH for the March 31st - April 7th period.
> * There are also discrepancies in the weeks of March 10-17th of 22.9 ETH and 17th-24th of 22.2353 ETH.
> 
> Note: regarding metodology, we're looking at 00:00 UTC timestamps for the starting and ending date of each period.
> 
> Could you share a bit more about how these weekly/monthly values are computed?

we collect daily data weekly mouthly it caluluat from historical daily

**Comment by dtmkeng** [comment]
some time it error ```
{
"error": "Failed to fetch the stats, please try again later."
}
```
then adapter it store 0

**Pull request merged**
