### PR TITLE
Add quenta 

### PR DESCRIPTION
**Pull request by quenta2024**

### CODE REVIEW

**Comment by llamatester** [comment]
The quenta adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs quenta
    
    🦙 Running QUENTA adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 31 Oct 2024 00:00:00 GMT
    End Date:	Fri, 01 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    IOTEX 👇
    Backfill start time: 10/12/1970
    NO METHODOLOGY SPECIFIED
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Total volume: 17.19 k
    Daily volume: 399

**Comment by llamatester** [comment]
The quenta adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees quenta
    
    🦙 Running QUENTA adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 31 Oct 2024 05:51:13 GMT
    End Date:	Fri, 01 Nov 2024 05:51:13 GMT
    ---------------------------------------------------
    
    IOTEX 👇
    Backfill start time: 10/12/1970
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Total fees: 11
    End timestamp: 1730440272 (2024-11-01T05:51:12.000Z)

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by llamatester** [comment]
The quenta adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs quenta
    
    🦙 Running QUENTA adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 01 Nov 2024 09:54:59 GMT
    End Date:	Sat, 02 Nov 2024 09:54:59 GMT
    ---------------------------------------------------
    
    32942620 32959885 17976.873698 17727.193258
    IOTEX 👇
    Backfill start time: 10/12/1970
    NO METHODOLOGY SPECIFIED
    Total volume: 17.98 k
    Daily volume: 250
    End timestamp: 1730541298 (2024-11-02T09:54:58.000Z)

**Comment by llamatester** [comment]
The quenta adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees quenta
    
    🦙 Running QUENTA adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 01 Nov 2024 09:55:24 GMT
    End Date:	Sat, 02 Nov 2024 09:55:24 GMT
    ---------------------------------------------------
    
    IOTEX 👇
    Backfill start time: 10/12/1970
    NO METHODOLOGY SPECIFIED
    Total volume: 11
    Daily volume: 0
    End timestamp: 1730541323 (2024-11-02T09:55:23.000Z)

**Pull request merged**
