### PR TITLE
feat: add mitte dailyVolume

### PR DESCRIPTION
**Pull request by mittedev0**
add mitte dailyVolume

Name (to be shown on DefiLlama): MITTE
Twitter Link: https://x.com/mitte_gg
List of audit links if any: X
Website Link: https://beta.mitte.gg

Logo (High resolution, will be shown with rounded borders): 
betalogo

Current TVL: X

Treasury Addresses (if the protocol has treasury)
Chain: NEAR

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):X (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

Short Description (to be shown on DefiLlama):
NFT projects can leverage traders’ abundant liquidity through MITTE’s order book-based bulk trading system, fostering attraction and active trading. This will significantly enhance the projects’ value and recognition.

MITTE (見て miːte) is an NFT trading platform fully optimized for mobile, allowing fast revenue generation.

Token address and ticker if any: X

Category (full list at https://defillama.com/categories) *Please choose only one: Dexes

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.): X

Implementation Details: Briefly describe how the oracle is integrated into your project: X

Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage: X
forkedFrom (Does your project originate from another project): X

methodology (what is being counted as tvl, how is tvl being calculated): meme trading volume + yolo lose volume + nft trading volume

### CODE REVIEW

**Comment by llamatester** [comment]
The mitte adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs mitte
    
    🦙 Running MITTE adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 23 Sep 2024 00:00:00 GMT
    End Date:	Tue, 24 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    NEAR 👇
    Backfill start time: 24/9/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1727049600 (2024-09-23T00:00:00.000Z)
    Daily volume: 2.49 k

**Comment by llamatester** [comment]
The mitte adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs mitte
    
    🦙 Running MITTE adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 23 Sep 2024 00:00:00 GMT
    End Date:	Tue, 24 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    NEAR 👇
    Backfill start time: 24/9/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1727049600 (2024-09-23T00:00:00.000Z)
    Daily volume: 2.49 k

**Comment by dtmkeng** [comment]
is there tvl adapter ? volume is from swap LP ?

**Comment by mittedev0** [comment]
> is there tvl adapter ? volume is from swap LP ?

The TVL adapter is not yet available.
The volume shown is the sum of the volume when MEME is in the bonding curve state plus the volume when MEME is listed on DEX. @dtmkeng

**Comment by dtmkeng** [comment]
> The volume shown is the sum of the volume when MEME is in the bonding curve state plus the volume when MEME is listed on DEX

is it not from your LP ?

**Comment by llamatester** [comment]
The mitte adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs mitte
    
    🦙 Running MITTE adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 08 Oct 2024 07:21:09 GMT
    End Date:	Wed, 09 Oct 2024 07:21:09 GMT
    ---------------------------------------------------
    
    NEAR 👇
    Backfill start time: 13/3/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 22.61 k
    End timestamp: 1728458468 (2024-10-09T07:21:08.000Z)

**Pull request merged**
