### PR TITLE
feat: add hiveswap pro

### PR DESCRIPTION
**Pull request by hive-wax**

### CODE REVIEW

**Comment by llamatester** [comment]
The hiveswap-pro adapter exports: 
        
 
 _______________________________________
    Dexs for 20/3/2024
    _______________________________________
    
    22776 👇
    Backfill start time: 10/3/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 4
    Daily volume: 0
    Timestamp: 1710892800 (2024-03-20T00:00:00.000Z)
    
    
    
    
    Done in 3.98s.

**Comment by dtmkeng** [comment]
@hive-wax  why use `izumi.finance` api ?

**Comment by hive-wax** [comment]
@dtmkeng  This is because the pro version is a collaboration between the hiveswap and the izumi.

**Comment by dtmkeng** [comment]
> @dtmkeng This is because the pro version is a collaboration between the hiveswap and the izumi.

can you ask `izumi` finnace if list hiveswap with chain `22776` i can't list `izumi`

**Pull request closed without merging**
