### PR TITLE
Updated fees and revenue calculation

### PR DESCRIPTION
**Pull request by bufferfinance**

### CODE REVIEW

**Comment by bufferfinance** [comment]
Let us know if anything is required to be fixed

**Comment by llamatester** [comment]
The buffer adapter exports: 
        
 
 _______________________________________
    Fees for 8/2/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 29/1/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1675900798
    Daily fees: 7561.47914
    Daily revenue: 4536.887484
    
    
    
    
    Done in 4.28s.

**Comment by bufferfinance** [comment]
Yes, 40% of the fees are distributed to the BFR(our token) staking pool and
60% of the fees are distributed to the Liquidity providers.

**Comment by dtmkeng** [comment]
in this case 40% of fees = revenue

**Comment by bufferfinance** [comment]
Okay so here is the detailed fee distribution for now

40% fee goes to the BFR staking pool
55% goes to the Liquidity providers for underwriting options (we have put
up 100k of our cash in this pool -- that's 5% of the current pool)
5% goes to a treasury contract to be distributed as rewards for trading
contests

Now what should be the revenue?

**Comment by dtmkeng** [comment]
protocolRev = 5 % of fees
userHolderRev = 40 % of fees
supplySideRev = 55 % of fees

**Pull request merged**
