### PR TITLE
Fluid: fix get latest block before timestamp

### PR DESCRIPTION
**Pull request by bergben**
This PR is somewhat related to https://github.com/DefiLlama/dimension-adapters/pull/2086 

I added `-1` on `(await getBlock(api.chain, timestamp)).number - 1`  in that PR, but it looks like getBlock() is sometimes off by quite a bit. So I implemented a method to guarantee the block timestamp is the latest block **before** the target timestamp, because otherwise we get a revert when calling `calcRevenueSimulatedTime()`. 

Also fixes a bug for collectedRevenue case between from and to timestamp.

We had another spike in wrong revenue for Fluid. Which we need to backfill. I hope this PR helps to avoid all such cases in the future in the first place
image

image

### CODE REVIEW

**Comment by llamatester** [comment]
The fluid adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees fluid
    
    🦙 Running FLUID adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 21 Nov 2024 10:29:55 GMT
    End Date:	Fri, 22 Nov 2024 10:29:55 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 18/2/2024
    Daily fees: 72.85 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1732271394 (2024-11-22T10:29:54.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 3/7/2024
    Daily fees: 4.58 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 458
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1732271394 (2024-11-22T10:29:54.000Z)
    
    
    BASE 👇
    Backfill start time: 12/8/2024
    Daily fees: 2.49 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 249
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1732271394 (2024-11-22T10:29:54.000Z)

**Comment by llamatester** [comment]
The fluid adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees fluid
    
    🦙 Running FLUID adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 21 Nov 2024 16:58:47 GMT
    End Date:	Fri, 22 Nov 2024 16:58:47 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 18/2/2024
    Daily fees: 67.81 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 7.78 k
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1732294726 (2024-11-22T16:58:46.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 3/7/2024
    Daily fees: 4.95 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 495
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1732294726 (2024-11-22T16:58:46.000Z)
    
    
    BASE 👇
    Backfill start time: 12/8/2024
    Daily fees: 3.29 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 329
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1732294726 (2024-11-22T16:58:46.000Z)

**Comment by dtmkeng** [comment]
thanks will refill

**Comment by bergben** [comment]
ty @dtmkeng can you also refill for yesterday 22nd November, I think the logic ran without this fix so collected revenue was bugged which led to revenue on mainnet being reported as 0 

And then hopefully we are done :smile: 

image

**Pull request merged**
