### PR TITLE
add project: BlazeBot (BASE) fees

### PR DESCRIPTION
**Pull request by 0xs3th**
Support for BlazeBot - **The Fastest Telegram Trading Bot on Base**
Website: [blazebot.io](https://blazebot.io)

Thank you.

### CODE REVIEW

**Comment by llamatester** [comment]
The blazebot.ts adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    fees/blazebot.ts(43,7): error TS2322: Type '{ dailyFees: any; }' is not assignable to type 'FetchResultFees'.
      Property 'timestamp' is missing in type '{ dailyFees: any; }' but required in type 'FetchResultBase'.
    fees/blazebot.ts(44,20): error TS2581: Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i --save-dev @types/jquery`.
    fees/blazebot.ts(45,9): error TS2695: Left side of comma operator is unused and has no side effects.
    fees/blazebot.ts(44,21): error TS1005: ',' expected.
    fees/blazebot.ts(44,32): error TS1128: Declaration or statement expected.
    fees/blazebot.ts(46,7): error TS1109: Expression expected.
    fees/blazebot.ts(48,1): error TS1128: Declaration or statement expected.
    
    Done in 3.61s.

**Comment by dtmkeng** [comment]
could you fix the error above?

**Comment by llamatester** [comment]
The blazebot.ts adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    fees/blazebot.ts(49,7): error TS2322: Type 'number' is not assignable to type 'string | IJSON<string> | undefined'.
    
    Done in 3.29s.

**Comment by 0xs3th** [comment]
brb will run the test on local

**Comment by llamatester** [comment]
The blazebot.ts adapter exports: 
        
 
 _______________________________________
    Fees for 13/9/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 8/9/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 0.11034935720947978
    Timestamp: 1694649598
    
    
    
    
    Done in 3.80s.

**Pull request merged**
