### PR TITLE
Aweaver89/paradex volumes stats

### PR DESCRIPTION
**Pull request by aweaver89**
### Add Paradex Derivative Volumes

**Added functions to extract 24h volume and total volume for our three instruments:**

- ETH-USD-PERP
- BTC-USD-PERP
- SOL-USD-PERP

**Overall goal**

Show Paradex at /derivatives/paradex and be listed on the boards there.

### CODE REVIEW

**Comment by llamatester** [comment]
The paradex adapter exports: 
        
 
 _______________________________________
    Dexs for 23/10/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 1/9/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698105598
    Daily volume: 59834503.00004005
    Total volume: 307558949.43935
    
    
    
    
    Done in 6.76s.

**Comment by dtmkeng** [comment]
good, we can track `dailyOpenInterest` but now not show on llama page, (will have plan to) 😎

**Comment by dtmkeng** [comment]
> @dtmkeng thanks for letting me know about this! atm I'm not 100% sure about how we're communicating the dailyOpenInterest so I didn't include that. However I can easily update this ^^
> 
> How long does it usually take this to update on the site? For the overall adapter it took about 12h would it be safe to say this will be similar?
maybe around 3-4 hour

**Comment by aweaver89** [comment]
Ok I'll keep :eyes: on this ;)

**Comment by aweaver89** [comment]
And thanks for the help!

**Pull request merged**
