### PR TITLE
add token priority

### PR DESCRIPTION
**Pull request by algtm**
Some tokens have no price on coingeko,please backfill again to fix old data

### CODE REVIEW

**Comment by llamatester** [comment]
The udex-agg adapter exports: 
        
 
 _______________________________________
    Aggregators for 6/6/2024
    _______________________________________
    
    BSC 👇
    Backfill start time: 1/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 2.66 M
    Timestamp: 1717643014 (2024-06-06T03:03:34.000Z)
    
    
    POLYGON 👇
    Backfill start time: 1/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1717643014 (2024-06-06T03:03:34.000Z)
    
    
    ETHEREUM 👇
    Backfill start time: 1/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1717643014 (2024-06-06T03:03:34.000Z)
    
    
    BASE 👇
    Backfill start time: 1/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1717643014 (2024-06-06T03:03:34.000Z)

**Comment by algtm** [comment]
What time does the script run every day?

**Comment by algtm** [comment]
please backfill and overwrite old data thx

**Comment by dtmkeng** [comment]
> What time does the script run every day?

every hour

**Pull request merged**
