### PR TITLE
v2.5 update

### PR DESCRIPTION
**Pull request by Tesla1010**

### CODE REVIEW

**Comment by llamatester** [comment]
The buffer adapter exports: 
        
 
 _______________________________________
    Fees for 4/9/2023
    _______________________________________
    
    Failed to get value on arbitrum: Error: Type `Query` has no field `defillamaFeeStat`: {"response":{"errors":[{"locations":[{"line":2,"column":9}],"message":"Type `Query` has no field `defillamaFeeStat`"}],"status":200,"headers":{}},"request":{"query":"{\n        defillamaFeeStat(id: 19604) {\n          fee\n        }\n      }"}}
    ARBITRUM 👇
    Timestamp attempted: 3/9/2023
    ClientError: Type `Query` has no field `defillamaFeeStat`: {"response":{"errors":[{"locations":[{"line":2,"column":9}],"message":"Type `Query` has no field `defillamaFeeStat`"}],"status":200,"headers":{}},"request":{"query":"{\n        defillamaFeeStat(id: 19604) {\n          fee\n        }\n      }"}}
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/src/index.ts:498:11
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:67:23)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:48:53)
        at fulfilled (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:39:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      response: {
        errors: [ [Object] ],
        status: 200,
        headers: Headers { [Symbol(map)]: [Object: null prototype] }
      },
      request: {
        query: '{\n        defillamaFeeStat(id: 19604) {\n          fee\n        }\n      }',
        variables: undefined
      }
    }
    
    
    
    
    Done in 5.08s.

**Comment by dtmkeng** [comment]
new your url does not contain function `defillamaFeeStat` plz check existing function again

**Comment by Tesla1010** [comment]
It is now added @dtmkeng

**Comment by llamatester** [comment]
The buffer adapter exports: 
        
 
 _______________________________________
    Fees for 4/9/2023
    _______________________________________
    
    Failed to get value on arbitrum: Error: Type `Query` has no field `defillamaFeeStat`: {"response":{"errors":[{"locations":[{"column":9,"line":2}],"message":"Type `Query` has no field `defillamaFeeStat`"}],"status":200,"headers":{}},"request":{"query":"{\n        defillamaFeeStat(id: 19604) {\n          fee\n        }\n      }"}}
    ARBITRUM 👇
    Timestamp attempted: 3/9/2023
    ClientError: Type `Query` has no field `defillamaFeeStat`: {"response":{"errors":[{"locations":[{"column":9,"line":2}],"message":"Type `Query` has no field `defillamaFeeStat`"}],"status":200,"headers":{}},"request":{"query":"{\n        defillamaFeeStat(id: 19604) {\n          fee\n        }\n      }"}}
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/src/index.ts:498:11
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:67:23)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:48:53)
        at fulfilled (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:39:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      response: {
        errors: [ [Object] ],
        status: 200,
        headers: Headers { [Symbol(map)]: [Object: null prototype] }
      },
      request: {
        query: '{\n        defillamaFeeStat(id: 19604) {\n          fee\n        }\n      }',
        variables: undefined
      }
    }
    
    
    
    
    Done in 4.44s.

**Comment by dtmkeng** [comment]
hmm still error 🤔

**Comment by Tesla1010** [comment]
@dtmkeng changes are live now. Sorry for the confusion

**Comment by llamatester** [comment]
The buffer adapter exports: 
        
 
 _______________________________________
    Fees for 4/9/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 29/1/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1693871998
    Daily fees: 7286.956633
    Daily revenue: 7286.956633
    
    
    
    
    Done in 3.54s.

**Pull request merged**
