### PR TITLE
add merlin on dexes dashboard

### PR DESCRIPTION
**Pull request by CryptoSnowPrince**

### CODE REVIEW

**Comment by llamatester** [comment]
The merlin adapter exports: 
        
 
 _______________________________________
    Dexs for 21/4/2023
    _______________________________________
    
    Error getting block: zksync 1682121598 Request failed with status code 400
    Failed to get total volume on zksync: Invalid value provided for argument `block`: Object({"number": Null}): {"response":{"errors":[{"locations":[{"line":0,"column":0}],"message":"Invalid value provided for argument `block`: Object({\"number\": Null})"}],"status":200,"headers":{}},"request":{"query":"query get_total_volume($block: Int) { \n  uniswapFactories(\n    block: { number: $block }\n    ) {\n      totalVolumeUSD\n    }\n     }","variables":{}}}
    ZKSYNC 👇
    Backfill start time: 11/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1682121598
    Block: undefined
    Total volume: undefined
    Daily volume: 359.9197085317380946937798669673046
    
    
    
    
    Done in 1444.89s.

**Comment by llamatester** [comment]
The merlin adapter exports: 
        
 
 _______________________________________
    Dexs for 21/4/2023
    _______________________________________
    
    Error getting block: zksync 1682121598 Request failed with status code 400
    Failed to get total volume on zksync: Invalid value provided for argument `block`: Object({"number": Null}): {"response":{"errors":[{"locations":[{"column":0,"line":0}],"message":"Invalid value provided for argument `block`: Object({\"number\": Null})"}],"status":200,"headers":{}},"request":{"query":"query get_total_volume($block: Int) { \n  uniswapFactories(\n    block: { number: $block }\n    ) {\n      totalVolumeUSD\n    }\n     }","variables":{}}}
    ZKSYNC 👇
    Backfill start time: 31/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1682121598
    Block: undefined
    Total volume: undefined
    Daily volume: 359.9197085317380946937798669673046
    
    
    
    
    Done in 1442.08s.

**Comment by llamatester** [comment]
The merlin.ts adapter exports: 
        
 
 _______________________________________
    Fees for 21/4/2023
    _______________________________________
    
    ZKSYNC 👇
    Backfill start time: 31/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1682121598
    Daily fees: 1.137083817023362554816509572534106
    Daily user fees: 1.137083817023362554816509572534106
    Daily revenue: 0.0568541908511681277408254786267053
    Daily protocol revenue: 0.0568541908511681277408254786267053
    Daily holders revenue: 0.3979793359581768941857783503869371
    Daily supply side revenue: 0.6822502902140175328899057435204636
    
    
    
    
    Done in 3.61s.

**Comment by CryptoSnowPrince** [comment]
Thank you.

**Comment by dtmkeng** [comment]
@CryptoSnowPrince  thx for pr, hmm have question, seem like merlin on tvl is chain `ZkSync Era` it on dexs and fees you add ZkSync, which chain is correct ?
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/merlin/index.js#L4
if ZkSync era is correct, could you change `CHAIN.ZKSYNC` -> `CHAIN.ERA`

**Comment by CryptoSnowPrince** [comment]
ZkSync Era is correct.
I thought ZKSYNC means ZkSync Era.
If ERA means ZkSync Era, I will update.

**Comment by llamatester** [comment]
The merlin adapter exports: 
        
 
 _______________________________________
    Dexs for 22/4/2023
    _______________________________________
    
    ERA 👇
    Backfill start time: 31/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1682207998
    Block: 2055318
    Total volume: 9731.23846063265
    Daily volume: 695.7172586727402361116361242634718
    
    
    
    
    Done in 3.67s.

**Comment by llamatester** [comment]
The merlin.ts adapter exports: 
        
 
 _______________________________________
    Fees for 22/4/2023
    _______________________________________
    
    ERA 👇
    Backfill start time: 31/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1682207998
    Daily fees: 2.061273306953521919635169980403251
    Daily user fees: 2.061273306953521919635169980403251
    Daily revenue: 0.10306366534767609598175849902016255
    Daily protocol revenue: 0.10306366534767609598175849902016255
    Daily holders revenue: 0.72144565743373267187230949314113785
    Daily supply side revenue: 1.2367639841721131517811019882419506
    
    
    
    
    Done in 3.36s.

**Comment by CryptoSnowPrince** [comment]
I updated as ERA.

**Pull request merged**
