### PR TITLE
Feat: Add Meteora adapter

### PR DESCRIPTION
**Pull request by quangkeu95**

### CODE REVIEW

**Comment by llamatester** [comment]
The meteora adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The meteora adapter exports: 
        
 
 _______________________________________
    Dexs for 2/5/2024
    _______________________________________
    
    SOLANA 👇
    Backfill start time: 30/4/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 203.81 M
    Timestamp: 1714621826 (2024-05-02T03:50:26.000Z)

**Comment by dtmkeng** [comment]
image
which breakdown you need list ?

**Comment by quangkeu95** [comment]
> image which breakdown you need list ?

Hi, TVL and last 24h volume at first for all types of pools would be great. We can update the last 24h fee in our API later.

**Comment by dtmkeng** [comment]
okay will list on meteora pool

**Pull request merged**
