### PR TITLE
using getChainVolumeWithGasToken for Fantom DEX volumes

### PR DESCRIPTION
**Pull request by ftm1337**
Partial Fix for Multichain/Anyswap affected DEXes on fantom
- Issue: https://github.com/DefiLlama/dimension-adapters/issues/664
- Referenced Implementation: https://github.com/DefiLlama/dimension-adapters/commit/5f27d694d18c6153cca66fdc3b33244cff10adf1

Sanitized Volume Data for:
- [x] SoulSwap
- [x] Solidly
- [x] Yoshi Exchange
- [x] ProtoFi
- [x] KnightSwap
- [x] Morpheus Swap
- [x] WingSwap
- [x] Spartacus Exchange

DEX that still have old/wrong numbers:
- [ ] Elk

### CODE REVIEW

**Comment by llamatester** [comment]
The knightswap-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 31/10/2023
    _______________________________________
    
    Failed to get total volume on bsc: Failed to decode `block.number` value: `subgraph QmPQfcovYgjF2vyGBE4LwXaSYj7Bgfvbny8MBpgLSBVKjB has only indexed up to block number 32476197 and data for block number 33097702 is therefore not yet available`: {"response":{"errors":[{"message":"Failed to decode `block.number` value: `subgraph QmPQfcovYgjF2vyGBE4LwXaSYj7Bgfvbny8MBpgLSBVKjB has only indexed up to block number 32476197 and data for block number 33097702 is therefore not yet available`"}],"status":200,"headers":{}},"request":{"query":"query get_total_volume($block: Int) { \n  uniswapFactories(\n    block: { number: $block }\n    ) {\n      totalVolumeUSD\n    }\n     }","variables":{"block":33097702}}}
    Failed to get daily volume via alternative query on bsc: Type `UniswapDayData` has no field `undefined`: {"response":{"errors":[{"locations":[{"column":11,"line":3}],"message":"Type `UniswapDayData` has no field `undefined`"}],"status":200,"headers":{}},"request":{"query":"{\n      uniswapDayDatas(where: {undefined: 1698710400}) {\n          undefined\n          dailyVolumeUSD\n      }\n  }"}}
    BSC 👇
    Backfill start time: 3/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796798
    Block: 33097702
    Total volume: undefined
    Daily volume: undefined
    
    
    FANTOM 👇
    Backfill start time: 26/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796798
    Block: 70029796
    Daily volume: 3825.829537681659
    
    
    
    
    Done in 6.47s.

**Comment by llamatester** [comment]
The morpheus-swap adapter exports: 
        
 
 _______________________________________
    Dexs for 31/10/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 5/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796798
    Block: 70029796
    Daily volume: 3654.402216425302
    
    
    
    
    Done in 4.88s.

**Comment by llamatester** [comment]
The protofi adapter exports: 
        
 
 _______________________________________
    Dexs for 31/10/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 19/1/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796798
    Block: 70029796
    Daily volume: 5065.966237745564
    
    
    
    
    Done in 6.28s.

**Comment by llamatester** [comment]
The soulswap adapter exports: 
        
 
 _______________________________________
    Dexs for 31/10/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 3/9/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796798
    Block: 70029796
    Daily volume: 12111.993555670888
    
    
    
    
    Done in 6.72s.

**Comment by llamatester** [comment]
The spartacus-exchange adapter exports: 
        
 
 _______________________________________
    Dexs for 31/10/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 25/4/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796798
    Block: 70029796
    Daily volume: 0
    
    
    
    
    Done in 4.18s.

**Comment by llamatester** [comment]
The wingswap adapter exports: 
        
 
 _______________________________________
    Dexs for 31/10/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 21/11/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796798
    Block: 70029796
    Daily volume: 987.3304734841694
    
    
    
    
    Done in 4.23s.

**Comment by llamatester** [comment]
The yoshi-exchange adapter exports: 
        
 
 _______________________________________
    Dexs for 31/10/2023
    _______________________________________
    
    Failed to get total volume on bsc: Failed to decode `block.number` value: `subgraph QmX8ddPyzfvvNDhJK5SkV23ixCru6N76RWtrQ3X1EgvU94 has only indexed up to block number 32476197 and data for block number 33097702 is therefore not yet available`: {"response":{"errors":[{"message":"Failed to decode `block.number` value: `subgraph QmX8ddPyzfvvNDhJK5SkV23ixCru6N76RWtrQ3X1EgvU94 has only indexed up to block number 32476197 and data for block number 33097702 is therefore not yet available`"}],"status":200,"headers":{}},"request":{"query":"query get_total_volume($block: Int) { \n  factories(\n    block: { number: $block }\n    ) {\n      volumeUSD\n    }\n     }","variables":{"block":33097702}}}
    FANTOM 👇
    Backfill start time: 23/10/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796798
    Block: 70029796
    Daily volume: 8549.128579591781
    
    
    BSC 👇
    Backfill start time: 3/12/2021
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796798
    Block: 33097702
    Daily volume: 0
    
    
    ETHEREUM 👇
    Backfill start time: 6/4/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698796798
    Block: 18473542
    Daily volume: 0
    
    
    
    
    Done in 5.16s.

**Comment by dtmkeng** [comment]
thank you

**Pull request merged**
