### PR TITLE
Add DEX dashboard for FlowX Finance

### PR DESCRIPTION
**Pull request by devflowx**
### Action
Adding  FlowX Finance to DefiLlama

### Description

FlowX Finance is the ecosystem-focused decentralized exchange built on the Sui Blockchain. 

We delivers a revolutionary DeFi user experience, surpassing other AMM DEXs with notable efficiency, speed, and agility improvements.

### Category
Dexes

### Audit: 

Website : https://flowx.finance/

Twitter: https://twitter.com/FlowX_finance
Logo: 
logo

### CODE REVIEW

**Comment by llamatester** [comment]
The flowx-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 2/7/2023
    _______________________________________
    
    SUI 👇
    Backfill start time: 13/1/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 446712.6852879666
    Daily volume: 300.9475496695
    Timestamp: 1688256000
    
    
    
    
    Done in 3.67s.

**Comment by dtmkeng** [comment]
hi, could you add adapter for tvl ?

**Comment by devflowx** [comment]
hi, @devflowxm, currently we don't have  API for TVL, so i think i'll update later

**Comment by devflowx** [comment]
Please check PR:
https://github.com/DefiLlama/DefiLlama-Adapters/pull/6709

Do we need PR for https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts ?

**Comment by devflowx** [comment]
I just modify get cumulative volume for this adapter instead of get TVL. The TVL Adapter have been merged in pr: https://github.com/DefiLlama/DefiLlama-Adapters/pull/6709

**Comment by llamatester** [comment]
The flowx-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 3/7/2023
    _______________________________________
    
    SUI 👇
    Backfill start time: 13/1/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 1175.6283676631
    Daily volume: 694.3016641443
    Timestamp: 1688342400
    
    
    
    
    Done in 3.58s.

**Pull request merged**
