### PR TITLE
feat: add sonne finance to fees dashboard

### PR DESCRIPTION
**Pull request by gathonwar**

### CODE REVIEW

**Comment by llamatester** [comment]
The sonne-finance adapter exports: 
        
 
 _______________________________________
    Fees for 14/3/2023
    _______________________________________
    
    Failed to get value on optimism: Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x3786d4419D6B4A902607cEb2BB319Bb336735Df8","data":"0xa495e5b50000000000000000000000003c8b650257cfb5f272f799f5e2b4e65093a11a0500000000000000000000000017063ad4e83b0aba4ca0f3fc3a9794e807a00ed7","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    OPTIMISM 👇
    Timestamp attempted: 13/3/2023
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x3786d4419D6B4A902607cEb2BB319Bb336735Df8","data":"0xa495e5b50000000000000000000000003c8b650257cfb5f272f799f5e2b4e65093a11a0500000000000000000000000017063ad4e83b0aba4ca0f3fc3a9794e807a00ed7","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
        at Logger.makeError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
        at Logger.throwError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:632:24
        at Array.forEach (<anonymous>)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:614:33
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:48:23)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:33:139)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at fulfilled (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:20:58) {
      reason: 'missing revert data in call exception; Transaction reverted without a reason string',
      code: 'CALL_EXCEPTION',
      transaction: {
        to: '0x3786d4419D6B4A902607cEb2BB319Bb336735Df8',
        data: '0xa495e5b50000000000000000000000003c8b650257cfb5f272f799f5e2b4e65093a11a0500000000000000000000000017063ad4e83b0aba4ca0f3fc3a9794e807a00ed7',
        accessList: null
      }
    }
    
    
    
    
    Done in 1194.82s.

**Comment by llamatester** [comment]
The sonne-finance adapter exports: 
        
 
 _______________________________________
    Fees for 14/3/2023
    _______________________________________
    
    Failed to get value on optimism: Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x3786d4419D6B4A902607cEb2BB319Bb336735Df8","data":"0xa495e5b50000000000000000000000003c8b650257cfb5f272f799f5e2b4e65093a11a0500000000000000000000000017063ad4e83b0aba4ca0f3fc3a9794e807a00ed7","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    OPTIMISM 👇
    Timestamp attempted: 13/3/2023
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x3786d4419D6B4A902607cEb2BB319Bb336735Df8","data":"0xa495e5b50000000000000000000000003c8b650257cfb5f272f799f5e2b4e65093a11a0500000000000000000000000017063ad4e83b0aba4ca0f3fc3a9794e807a00ed7","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
        at Logger.makeError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
        at Logger.throwError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:632:24
        at Array.forEach (<anonymous>)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:614:33
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:48:23)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:33:139)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at fulfilled (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:20:58) {
      reason: 'missing revert data in call exception; Transaction reverted without a reason string',
      code: 'CALL_EXCEPTION',
      transaction: {
        to: '0x3786d4419D6B4A902607cEb2BB319Bb336735Df8',
        data: '0xa495e5b50000000000000000000000003c8b650257cfb5f272f799f5e2b4e65093a11a0500000000000000000000000017063ad4e83b0aba4ca0f3fc3a9794e807a00ed7',
        accessList: null
      }
    }
    
    
    
    
    Done in 1279.30s.

**Comment by dtmkeng** [comment]
@gathonwar  seem like rpc not support filter by block if your adapter runcurrentTime I guess can remove `block` when call function `call`

**Comment by dtmkeng** [comment]
i try to removed it oke 
```
OPTIMISM 👇
Backfill start time: 1/10/2022
NO METHODOLOGY SPECIFIED
Timestamp: 1678924798
Daily fees: 16373.973856192113
Daily revenue: 2190.4701794771186
Daily holders revenue: 8564.50863399209
```
but adapter is delay

**Pull request merged**
