### PR TITLE
Update aimbot.ts to include OpenBot's daily profit paid out as royalt…

### PR DESCRIPTION
**Pull request by nobodynodrama**
Added an additional revenue stream coming from OpenBot, AimBot's personal use sniper.  It is fetched from a custom API set up by the team for this purpose. The profits are distributed every 24 hours. 

You can examine the details here: 
https://medium.com/@aimbottoken/aimbot-opening-access-to-our-new-ai-bot-b2cd1de6bdfa

40% of the ETH generated from bribes and fees will be directly sent to the reward pool. Another 10% will be send to AI funding wallet (for AIMBOT trading). The remaining 50% will go to the team.

### CODE REVIEW

**Comment by llamatester** [comment]
The aimbot.ts adapter exports: 
        
 
 _______________________________________
    Fees for 18/12/2023
    _______________________________________
    
    Error: connect ECONNREFUSED ::1:5432
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
        at cachedError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/query.js:171:23)
        at new Query (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/query.js:36:24)
        at sql (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/index.js:111:11)
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/aimbot.ts:20:35)
    Failed to get value on ethereum: Error: connect ECONNREFUSED ::1:5432
    ETHEREUM 👇
    Timestamp attempted: 17/12/2023
    Error: connect ECONNREFUSED ::1:5432
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
        at cachedError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/query.js:171:23)
        at new Query (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/query.js:36:24)
        at sql (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/postgres/cjs/src/index.js:111:11)
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/aimbot.ts:20:35)
    
    
    
    
    Done in 2.67s.

**Comment by dtmkeng** [comment]
could you check error above ?

**Comment by nobodynodrama** [comment]
> could you check error above ?

That error is w/ regards to connecting to the defillama sql server, no?

**Comment by dtmkeng** [comment]
> > could you check error above ?
> 
> That error is w/ regards to connecting to the defillama sql server, no?

i know i see you set all fees value is from your api should still use data from index ?

**Comment by nobodynodrama** [comment]
> > > could you check error above ?
> > 
> > 
> > That error is w/ regards to connecting to the defillama sql server, no?
> 
> i know i see you set all fees value is from your api should still use data from index ?

no sir, 
total amount is still an addition of the sql call plus my api call

const totalAmount = amount + openBotFundAmount;

**Pull request merged**
