### PR TITLE
add javsphere volume and fees

### PR DESCRIPTION
**Pull request by rogi-sh**
This PR adds javspheres tradex volume and fees  to the dexs adapters.
https://www.javsphere.com/ -> LandingPage
https://app.javsphere.com/ -> dApp

### CODE REVIEW

**Comment by llamatester** [comment]
The javsphere adapter exports: 
        
 
 _______________________________________
    Dexs for 23/3/2024
    _______________________________________
    
    {
      countTotal: 474,
      volumeTotal: 875534,
      feeTotal: 875,
      tradesBuy: 457,
      volumeBuy: 862320,
      volumeBuyFees: 862,
      countSell: 17,
      volumeSell: 13213,
      volumeSellFees: 13
    }
    DEFICHAIN 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Total volume: 875.53 k
    Total fees: 875
    Timestamp: 1711238399 (2024-03-23T23:59:59.000Z)
    
    
    
    
    Done in 6.26s.

**Comment by llamatester** [comment]
The javsphere adapter exports: 
        
 
 _______________________________________
    Dexs for 23/3/2024
    _______________________________________
    
    {
      countTotal: 474,
      volumeTotal: 875534,
      feeTotal: 875,
      tradesBuy: 457,
      volumeBuy: 862320,
      volumeBuyFees: 862,
      countSell: 17,
      volumeSell: 13213,
      volumeSellFees: 13
    }
    DEFICHAIN 👇
    Backfill start time not defined
    Total volume: 875.53 k
    └─ Methodology: User buys and sell RWA tokens..
    Total fees: 875
    └─ Methodology: User pays 0.1% fees on each trade.
    Timestamp: 1711238399 (2024-03-23T23:59:59.000Z)
    
    
    
    
    Done in 4.10s.

**Comment by llamatester** [comment]
The javsphere adapter exports: 
        
 
 _______________________________________
    Dexs for 23/3/2024
    _______________________________________
    
    DEFICHAIN 👇
    Backfill start time not defined
    Total volume: 875.53 k
    └─ Methodology: User buys and sell RWA tokens..
    Total fees: 875
    └─ Methodology: User pays 0.1% fees on each trade.
    Timestamp: 1711238399 (2024-03-23T23:59:59.000Z)
    
    
    
    
    Done in 6.17s.

**Comment by dtmkeng** [comment]
@rogi-sh  can you add dailyFees and dailyVolume ? we collect data every day and show historical data

**Comment by llamatester** [comment]
The javsphere adapter exports: 
        
 
 _______________________________________
    Dexs for 24/3/2024
    _______________________________________
    
    DEFICHAIN 👇
    Backfill start time not defined
    Total volume: 904.75 k
    └─ Methodology: User buys and sell RWA tokens.
    Total fees: 904
    └─ Methodology: User pays 0.1% fees on each trade.
    Daily fees: 45
    └─ Methodology: User pays 0.1% fees on each trade.
    Daily volume: 45.90 k
    └─ Methodology: User buys and sell RWA tokens.
    Timestamp: 1711324799 (2024-03-24T23:59:59.000Z)
    
    
    
    
    Done in 5.20s.

**Comment by rogi-sh** [comment]
@dtmkeng  done

**Comment by rogi-sh** [comment]
@dtmkeng pr is done ✅

**Pull request merged**
