### PR TITLE
add butternetwork dex

### PR DESCRIPTION
**Pull request by neoiss**

### CODE REVIEW

**Comment by llamatester** [comment]
The butternetwork adapter exports: 
        
 
 _______________________________________
    Dexs for 2/9/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1693752431330
    Daily volume: 16.812708
    Total volume: 2355755.779761
    
    
    POLYGON 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1693752431332
    Daily volume: 16.812708
    Total volume: 154126093.746007
    
    
    BSC 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1693752431371
    Daily volume: 178714.465386
    Total volume: 42870128.448664
    
    
    MAP 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1693752431381
    Daily volume: 178709.967457
    Total volume: 0
    
    
    
    
    Done in 4.58s.

**Comment by dtmkeng** [comment]
which value comes from? 
swap, option, derivatives, dexs aggerator

**Comment by neoiss** [comment]
> 



> which value comes from? swap, option, derivatives, dexs aggerator
dexs

**Comment by dtmkeng** [comment]
which type ?

**Comment by neoiss** [comment]
> which type ?
is it the type of butternetwork?

**Comment by dtmkeng** [comment]
> > which type ?
> > is it the type of butternetwork?

value from your API, is it value from swap ?

**Comment by dtmkeng** [comment]
if from swap do you have example txs ?

**Comment by neoiss** [comment]
> 



> > > which type ?
> > > is it the type of butternetwork?
> 
> value from your API, is it value from swap ?

from bridge

**Comment by dtmkeng** [comment]
dimension repo does not list bridge volume if you need list bridge you can you open pr on this repo https://github.com/DefiLlama/bridges-server

**Pull request closed without merging**
