### PR TITLE
add liondex fees

### PR DESCRIPTION
**Pull request by LionDEXDev**

### CODE REVIEW

**Comment by llamatester** [comment]
The liondex adapter exports: 
        
 
 _______________________________________
    Fees for 15/6/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 13/6/2023
    Timestamp: 1686873598
    Daily fees: 3190.500668234878
    └─ Methodology: Daily fees collected from user trading fees
    
    
    
    
    Done in 4.35s.

**Comment by dtmkeng** [comment]
hi, have question about LP, it can instead with some token. ?

**Comment by LionDEXDev** [comment]
Hi thereThanks for reaching out$LP is a token that used to open orders for Perpetual trading in LionDEX. Beside that, $LP can be used to stake and mine GMX’s transaction fees + LionDEX Transaction fees$LP can be minted by BTC / ETH / USDC on liondex.comOn 16 Jun 2023, at 8:10 PM, dtmkeng ***@***.***> wrote:﻿
hi, have question about LP, it can instead with some token. ?

**Comment by LionDEXDev** [comment]
The address of LP(LionDEX Liquidity Provider) token is here:
https://arbiscan.io/address/0x03229fb11e3D7E8Aca8C758DBD0EA737950d6CD0

**Comment by waynebruce0x** [comment]
Is the subgraph endpoint described in this PR still maintained? It doesnt seem to return daily fees regualrly

**Pull request merged**
