### PR TITLE
Feat/add lista dao fees

### PR DESCRIPTION
**Pull request by tyler-tsai**

### CODE REVIEW

**Comment by llamatester** [comment]
The lista-dao adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees lista-dao
    
    🦙 Running LISTA-DAO adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 29 Aug 2024 04:47:31 GMT
    End Date:	Fri, 30 Aug 2024 04:47:31 GMT
    ---------------------------------------------------
    
    BSC 👇
    Backfill start time: 30/8/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 154
    Daily revenue: 154
    End timestamp: 1724993250 (2024-08-30T04:47:30.000Z)

**Comment by llamatester** [comment]
The lista-dao adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees lista-dao
    
    🦙 Running LISTA-DAO adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 29 Aug 2024 04:49:05 GMT
    End Date:	Fri, 30 Aug 2024 04:49:05 GMT
    ---------------------------------------------------
    
    BSC 👇
    Backfill start time: 30/8/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 154
    Daily revenue: 154
    End timestamp: 1724993344 (2024-08-30T04:49:04.000Z)

**Comment by llamatester** [comment]
The lista-dao adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees lista-dao
    
    🦙 Running LISTA-DAO adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 29 Aug 2024 04:50:51 GMT
    End Date:	Fri, 30 Aug 2024 04:50:51 GMT
    ---------------------------------------------------
    
    BSC 👇
    Backfill start time: 30/8/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 154
    Daily revenue: 154
    End timestamp: 1724993450 (2024-08-30T04:50:50.000Z)

**Comment by dtmkeng** [comment]
is for slisbnb or lisusd ?

**Comment by tyler-tsai** [comment]
> is for slisbnb or lisusd ?

we have both lisUSD and slisBNB on lista dao.

**Comment by dtmkeng** [comment]
> > is for slisbnb or lisusd ?
> 
> 
> 
> we have both lisUSD and slisBNB on lista dao.

1 adpater list only 1 protolcol if you need list should split 2 adapter and split meta and address

**Comment by tyler-tsai** [comment]
> > > is for slisbnb or lisusd ?
> > 
> > 
> > we have both lisUSD and slisBNB on lista dao.
> 
> 1 adpater list only 1 protolcol if you need list should split 2 adapter and split meta and address

Lista DAO is our protocol. We have three tokens in this protocol: LISTA, lisUSD, and slisBNB.

**Comment by tyler-tsai** [comment]
> > > > is for slisbnb or lisusd ?
> > > 
> > > 
> > > we have both lisUSD and slisBNB on lista dao.
> > 
> > 
> > 1 adpater list only 1 protolcol if you need list should split 2 adapter and split meta and address
> 
> Lista DAO is our protocol. We have three tokens in this protocol: LISTA, lisUSD, and slisBNB.

Please refer to 
https://docs.bsc.lista.org/v/eglish-new

**Comment by dtmkeng** [comment]
> > > > > is for slisbnb or lisusd ?
> 
> > > > 
> 
> > > > 
> 
> > > > we have both lisUSD and slisBNB on lista dao.
> 
> > > 
> 
> > > 
> 
> > > 1 adpater list only 1 protolcol if you need list should split 2 adapter and split meta and address
> 
> > 
> 
> > Lista DAO is our protocol. We have three tokens in this protocol: LISTA, lisUSD, and slisBNB.
> 
> 
> 
> Please refer to 
> 
> https://docs.bsc.lista.org/v/eglish-new

when list we list under slisBNB or lisUSD which one that you need

**Comment by tyler-tsai** [comment]
Can't you just list under ListaDao, like pancake?

**Comment by tyler-tsai** [comment]
They won't list their fees/revenue under CAKE.

**Comment by dtmkeng** [comment]
> Can't you just list under ListaDao, like pancake?

yes it will under listaDao because is parent of slisBNB or lisUSD

**Comment by tyler-tsai** [comment]
> > Can't you just list under ListaDao, like pancake?
> 
> yes it will under listaDao because is parent of slisBNB or lisUSD

Much appreciated!

**Pull request merged**
