### PR TITLE
Add BACKED

### PR DESCRIPTION
**Pull request by 0xSullivan**
Add TVL for backed project

https://backed.ventures/

### CODE REVIEW

**Comment by llamatester** [comment]
The backed adapter exports: 
        
 
 _______________________________________
    Fees for 20/5/2024
    _______________________________________
    
    TypeError: Cannot create property 'timestamp' on string '4796628000000'
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:32:25)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 2)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'base'
    }

**Comment by dtmkeng** [comment]
this repo for list tvl https://github.com/DefiLlama/DefiLlama-Adapters

**Comment by llamatester** [comment]
The backed adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by dtmkeng** [comment]
what  you need add ? fees, tvl volume or ... ?

**Pull request closed without merging**
