### PR TITLE
Kriya-dex volume dimension adapter

### PR DESCRIPTION
**Pull request by Rajwanshi1**

### CODE REVIEW

**Comment by llamatester** [comment]
The kriya-dex adapter exports: 
        
 
 _______________________________________
    Dexs for 19/10/2023
    _______________________________________
    
    SUI 👇
    Backfill start time: 9/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 10550702.796099206
    Daily volume: 46096.67011840083
    Timestamp: 1697673600
    
    
    
    
    Done in 4.84s.

**Comment by dtmkeng** [comment]
sorry there is not record data, will backfill data

**Comment by adityadw1998** [comment]
@dtmkeng 
Seems only till June 2, 2023 backfilled. Does backfill happen in batches ? or there could be some issue with our API ?

Screenshot 2023-10-20 at 6 04 03 PM

**Comment by dtmkeng** [comment]
> Seems only till June 2, 2023 backfilled. Does backfill happen in batches ? or there could be some issue with our API ?

no, your API is 500, I will run backfill on my local

**Comment by Rajwanshi1** [comment]
Hi @dtmkeng 
Could you tell the timestamp for which the api is failing with error 500?

**Comment by dtmkeng** [comment]
sine you see data, on chart will refilled already

**Comment by Rajwanshi1** [comment]
Yes, it has completed. Thanks for the support.

**Pull request merged**
