### PR TITLE
add dpex

### PR DESCRIPTION
**Pull request by iulianivg**
Adding DPEX volume stats. 
TVL already tracked by DefiLlama: https://defillama.com/protocol/dpex

### CODE REVIEW

**Comment by llamatester** [comment]
The dpex adapter exports: 
        
 
 _______________________________________
    Dexs for 23/5/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 4/11/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1684800000
    Daily volume: undefined
    Total volume: 15992332.01177024
    
    
    
    
    Done in 3.78s.

**Comment by dtmkeng** [comment]
hi, ty for pr, could you check why daily volume is return undefined

**Comment by llamatester** [comment]
The dpex adapter exports: 
        
 
 _______________________________________
    Dexs for 23/5/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 4/11/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1684800000
    Daily volume: undefined
    Total volume: 16133176.40017446
    
    
    
    
    Done in 3.86s.

**Comment by llamatester** [comment]
The dpex adapter exports: 
        
 
 _______________________________________
    Dexs for 23/5/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 4/11/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1684800000
    Daily volume: 45771.49192234387
    Total volume: 16133176.40017446
    
    
    
    
    Done in 4.07s.

**Comment by iulianivg** [comment]
Hi, daily volume fixed. Sorry for delay. Thanks!

**Pull request merged**
