### PR TITLE
add blitz adapters

### PR DESCRIPTION
**Pull request by yruej301**

### CODE REVIEW

**Comment by llamatester** [comment]
The blitz adapter exports: 
        
 
 _______________________________________
    Dexs for 17/3/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://gateway.blast-prod.vertexprotocol.com/v1/query?type=all_products',
      method: 'GET',
      axiosError: 'Forbidden',
      chain: 'blast'
    }
    Done in 7.44s.

**Comment by llamatester** [comment]
The blitz.ts adapter exports: 
        
 
 _______________________________________
    Fees for 17/3/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://archive.blast-prod.vertexprotocol.com/v1',
      method: 'POST',
      axiosError: 'Forbidden',
      chain: 'blast'
    }
    Done in 6.32s.

**Comment by llamatester** [comment]
The blitz adapter exports: 
        
 
 _______________________________________
    Dexs for 19/3/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://gateway.blast-prod.vertexprotocol.com/v1/query?type=all_products',
      method: 'GET',
      axiosError: 'Forbidden',
      chain: 'blast'
    }
    Done in 7.91s.

**Comment by llamatester** [comment]
The blitz.ts adapter exports: 
        
 
 _______________________________________
    Fees for 19/3/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://archive.blast-prod.vertexprotocol.com/v1',
      method: 'POST',
      axiosError: 'Forbidden',
      chain: 'blast'
    }
    Done in 9.21s.

**Comment by dtmkeng** [comment]
@yruej301  could you check api seem is error 403

**Comment by yruej301** [comment]
> @yruej301 could you check api seem is error 403

hey @dtmkeng, it's just geo-blocking. if your run from a non-US server everything works.

**Comment by yruej301** [comment]
@dtmkeng see a similar case in https://github.com/DefiLlama/dimension-adapters/pull/738

**Pull request merged**
