### PR TITLE
[izumi] add fee adapter for iziswap

### PR DESCRIPTION
**Pull request by LpcAries**
add iotex config into volume adapter
add fees adapter for iziswap on iotex

### CODE REVIEW

**Comment by llamatester** [comment]
The iziswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs iziswap
    
    🦙 Running IZISWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 04 Nov 2024 00:00:00 GMT
    End Date:	Tue, 05 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BSC 👇
    Backfill start time: 6/4/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 554.86 M
    Daily volume: 12.18 k
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    ERA 👇
    Backfill start time: 6/4/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 1.58 B
    Daily volume: 53.76 k
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 4.14 M
    Daily volume: 179
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    METER 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 524.18 k
    Daily volume: 0
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    AURORA 👇
    Backfill start time: 11/10/2022
    NO METHODOLOGY SPECIFIED
    Total volume: 25.75 M
    Daily volume: 0
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    POLYGON 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 138.60 k
    Daily volume: 0
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    MANTLE 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 606.02 M
    Daily volume: 29.96 k
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    ONTOLOGY_EVM 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 161.44 k
    Daily volume: 0
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    ULTRON 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 2.15 M
    Daily volume: 0
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    LINEA 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 551.03 M
    Daily volume: 651.24 k
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    SCROLL 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 928.02 M
    Daily volume: 1.39 M
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    BASE 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 51.91 M
    Daily volume: 243.20 k
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    MANTA 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 177.47 M
    Daily volume: 51.94 k
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    ZETA 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 36.98 M
    Daily volume: 88.92 k
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    MODE 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 58.97 M
    Daily volume: 518.36 k
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)
    
    
    IOTEX 👇
    Backfill start time: 16/7/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 216.10 k
    Daily volume: 2.22 k
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)

**Comment by llamatester** [comment]
The iziswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees iziswap
    
    🦙 Running IZISWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 04 Nov 2024 00:00:00 GMT
    End Date:	Tue, 05 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    IOTEX 👇
    Backfill start time: 26/7/2024
    NO METHODOLOGY SPECIFIED
    Total fees: 648
    Daily fees: 7
    End timestamp: 1730678400 (2024-11-04T00:00:00.000Z)

**Comment by dtmkeng** [comment]
Why is there only one chain supported in the fees adapter?

**Comment by LpcAries** [comment]
> @LpcAries Why is there only one chain supported in the fees adapter?

Because currently, only the partners of this chain have a requirement to display fees, while other chains do not have this need for the time being.

**Pull request merged**
