### PR TITLE
Update to include Premia Blue (V3)

### PR DESCRIPTION
**Pull request by froggiedev**
Thanks again @0xngmi  💙💙💙

### CODE REVIEW

**Comment by llamatester** [comment]
The premia adapter exports: 
        
 
 _______________________________________
    Options for 6/9/2023
    _______________________________________
    
    Version -> V2
    ---------
    ETHEREUM 👇
    Backfill start time: 6/6/1970
    Timestamp: 1694044799
    Total notional volume: 59476550.84103109
    Daily notional volume: 0
    Total premium volume: 2641616.516262586
    Daily premium volume: 0
    
    
    ARBITRUM 👇
    Backfill start time: 8/2/1970
    Timestamp: 1694044799
    Total notional volume: 221087459.42195404
    Daily notional volume: 47877.42414289713
    Total premium volume: 7716897.041903612
    Daily premium volume: 365.0752460118383
    
    
    FANTOM 👇
    Backfill start time: 14/2/1971
    Timestamp: 1694044799
    Total notional volume: 55315577.199166715
    Daily notional volume: 0
    Total premium volume: 1809161.3416765053
    Daily premium volume: 0
    
    
    OPTIMISM 👇
    Backfill start time: 12/7/1970
    Timestamp: 1694044799
    Total notional volume: 36173153.53379367
    Daily notional volume: 1920.5731708034873
    Total premium volume: 1076719.2299592707
    Daily premium volume: 121.20161990728229
    
    
    Version -> V3
    ---------
    ARBITRUM 👇
    Backfill start time: 20/10/1973
    Timestamp: 1694044799
    Total notional volume: 380.38169992066
    Daily notional volume: 3.97941354436
    Total premium volume: 37.793894815939865
    Daily premium volume: 0.20683507641862064
    
    
    Done in 3.57s.

**Comment by llamatester** [comment]
The premia adapter exports: 
        
 
 _______________________________________
    Fees for 6/9/2023
    _______________________________________
    
    Version -> V2
    ---------
    ETHEREUM 👇
    Backfill start time: 6/6/1970
    Timestamp: 1694044799
    Daily fees: 0
    Daily user fees: 0
    └─ Methodology: Traders pay taker fees on each trade up to 3% of the option premium.
    Daily revenue: -14.98798580222558
    Daily protocol revenue: 0
    └─ Methodology: The protocol collects 20% of the taker fees.
    Daily holders revenue: 0
    └─ Methodology: vxPREMIA holders collect 80% of the taker fees.
    Daily supply side revenue: -14.98798580222558
    └─ Methodology: Liquidity providers earn revenue from market-making options.
    Total fees: 90777.06958202498
    Total user fees: 90777.06958202498
    └─ Methodology: Traders pay taker fees on each trade up to 3% of the option premium.
    Total revenue: 90777.06958202498
    Total protocol revenue: 18155.413916404996
    └─ Methodology: The protocol collects 20% of the taker fees.
    Total daily holders revenue: 72621.65566561998
    Total supply side revenue: 0
    └─ Methodology: Liquidity providers earn revenue from market-making options.
    
    
    ARBITRUM 👇
    Backfill start time: 8/2/1970
    Timestamp: 1694044799
    Daily fees: 14.664841891615652
    Daily user fees: 14.664841891615652
    └─ Methodology: Traders pay taker fees on each trade up to 3% of the option premium.
    Daily revenue: -10.274954806068365
    Daily protocol revenue: 2.9329683783231304
    └─ Methodology: The protocol collects 20% of the taker fees.
    Daily holders revenue: 11.731873513292522
    └─ Methodology: vxPREMIA holders collect 80% of the taker fees.
    Daily supply side revenue: -24.939796697684017
    └─ Methodology: Liquidity providers earn revenue from market-making options.
    Total fees: 285657.9872312952
    Total user fees: 285657.9872312952
    └─ Methodology: Traders pay taker fees on each trade up to 3% of the option premium.
    Total revenue: 285657.9872312952
    Total protocol revenue: 57131.597446259046
    └─ Methodology: The protocol collects 20% of the taker fees.
    Total daily holders revenue: 228526.38978503618
    Total supply side revenue: 0
    └─ Methodology: Liquidity providers earn revenue from market-making options.
    
    
    FANTOM 👇
    Backfill start time: 14/2/1971
    Timestamp: 1694044799
    Daily fees: 0
    Daily user fees: 0
    └─ Methodology: Traders pay taker fees on each trade up to 3% of the option premium.
    Daily revenue: -12556.550231398394
    Daily protocol revenue: 0
    └─ Methodology: The protocol collects 20% of the taker fees.
    Daily holders revenue: 0
    └─ Methodology: vxPREMIA holders collect 80% of the taker fees.
    Daily supply side revenue: -12556.550231398394
    └─ Methodology: Liquidity providers earn revenue from market-making options.
    Total fees: 60755.94490136967
    Total user fees: 60755.94490136967
    └─ Methodology: Traders pay taker fees on each trade up to 3% of the option premium.
    Total revenue: 60755.94490136967
    Total protocol revenue: 12151.188980273935
    └─ Methodology: The protocol collects 20% of the taker fees.
    Total daily holders revenue: 48604.75592109574
    Total supply side revenue: 0
    └─ Methodology: Liquidity providers earn revenue from market-making options.
    
    
    OPTIMISM 👇
    Backfill start time: 12/7/1970
    Timestamp: 1694044799
    Daily fees: 5.651501650871069
    Daily user fees: 5.651501650871069
    └─ Methodology: Traders pay taker fees on each trade up to 3% of the option premium.
    Daily revenue: 5.651501650871069
    Daily protocol revenue: 1.1303003301742138
    └─ Methodology: The protocol collects 20% of the taker fees.
    Daily holders revenue: 4.521201320696855
    └─ Methodology: vxPREMIA holders collect 80% of the taker fees.
    Daily supply side revenue: 0
    └─ Methodology: Liquidity providers earn revenue from market-making options.
    Total fees: 33253.71384378454
    Total user fees: 33253.71384378454
    └─ Methodology: Traders pay taker fees on each trade up to 3% of the option premium.
    Total revenue: 33253.71384378454
    Total protocol revenue: 6650.742768756909
    └─ Methodology: The protocol collects 20% of the taker fees.
    Total daily holders revenue: 26602.971075027635
    Total supply side revenue: 0
    └─ Methodology: Liquidity providers earn revenue from market-making options.
    
    
    Version -> V3
    ---------
    ARBITRUM 👇
    Backfill start time: 20/10/1973
    Timestamp: 1694044799
    Daily fees: 0.015895498826118404
    Daily user fees: 0.015895498826118404
    └─ Methodology: Traders pay taker fees on each trade up to 3% of the option premium.
    Daily revenue: 0.22273057524473905
    Daily protocol revenue: 0.004178819576053572
    └─ Methodology: The protocol collects 10% of the taker fees.
    Daily holders revenue: 0.01671527830421429
    └─ Methodology: vxPREMIA holders collect 40% of the taker fees.
    Daily supply side revenue: 0.2018364773644712
    └─ Methodology: Liquidity providers collect 50% of the taker fees and earn revenue from market-making options.
    Total fees: 1.2404538816575919
    Total user fees: 1.2404538816575919
    └─ Methodology: Traders pay taker fees on each trade up to 3% of the option premium.
    Total revenue: 39.03434869759746
    Total protocol revenue: 0.1791520261758926
    └─ Methodology: The protocol collects 10% of the taker fees.
    Total daily holders revenue: 0.7166081047035704
    Total supply side revenue: 38.13858856671799
    └─ Methodology: Liquidity providers collect 50% of the taker fees and earn revenue from market-making options.
    
    
    Done in 3.66s.

**Comment by dtmkeng** [comment]
are you split tvl adapter already ?

**Comment by froggiedev** [comment]
@dtmkeng can you re-generate the data? we found a bug in our subgraph leading to incorrect volume data on PUT pools.

**Comment by froggiedev** [comment]
> are you split tvl adapter already ?

missed this. what do you mean?

**Comment by dtmkeng** [comment]
> @dtmkeng can you re-generate the data? we found a bug in our subgraph leading to incorrect volume data on PUT pools.

only v3 ?

**Comment by dtmkeng** [comment]
which day you need regenerate ?

**Comment by froggiedev** [comment]
> which day you need regenerate ?

All of v3 since inception

**Comment by dtmkeng** [comment]
> > which day you need regenerate ?
> 
> All of v3 since inception

I refilled data could you check ?
https://defillama.com/fees/premia-v3

**Pull request merged**
