### PR TITLE
Fluid: minor edge case fixes

### PR DESCRIPTION
**Pull request by bergben**
Fixes a bug where calculating revenue via the resolver reverted due to fetched block timestamp being at a slightly unexpected time. This caused a missing element in an array where a value was expected for every token in sequential order. Further causing wrong token amounts being used for tokens after that position in the array. 

# **Can you also re-run the calculations backfill with this fix please.** 

The spike here in revenue on 8 Nov is wrong
image

### CODE REVIEW

**Comment by llamatester** [comment]
The fluid adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees fluid
    
    🦙 Running FLUID adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 10 Nov 2024 12:42:45 GMT
    End Date:	Mon, 11 Nov 2024 12:42:45 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 18/2/2024
    Daily fees: 57.36 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 7.05 k
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1731328964 (2024-11-11T12:42:44.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 3/7/2024
    Daily fees: 6.24 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 624
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1731328964 (2024-11-11T12:42:44.000Z)
    
    
    BASE 👇
    Backfill start time: 12/8/2024
    Daily fees: 1.41 k
    └─ Methodology: Interest paid by borrowers
    Daily revenue: 141
    └─ Methodology: Percentage of interest going to treasury
    End timestamp: 1731328964 (2024-11-11T12:42:44.000Z)

**Comment by dtmkeng** [comment]
okay thank you will refill

**Comment by bergben** [comment]
Hi @dtmkeng thanks for merging. There is still a revenue spike on Oct 26, did you backfill for there too? 

image

I am getting more realistic data locally 
image

image

**Comment by dtmkeng** [comment]
will refill

**Comment by bergben** [comment]
Hi @dtmkeng there is another spike for Nov 17. running the test locally with the most recent master branch doesnt give me such a spike. Any ideas here? See below:

image

image

image

**Comment by dtmkeng** [comment]
will refill

**Comment by bergben** [comment]
@dtmkeng can you also double check why this happened again though please? Because this PR with the merge was fixed Nov 12, but we got the wrong data spike on Nov 17

**Pull request merged**
