### PR TITLE
Lexer Markets adapter

### PR DESCRIPTION
**Pull request by vinccnt**
Name (to be shown on DefiLlama): Lexer Markets

Twitter Link: https://twitter.com/lexermarkets

List of audit links if any: https://medium.com/@hyacinthcrypto/lexer-markets-security-review-2d7795693f69

Website Link: https://www.lexer.markets/

Logo (High resolution, will be shown with rounded borders): 
LEXER_LOGO-02

Current TVL:  71,565 USD

Chain: Arbitrum 

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): https://www.coingecko.com/en/coins/lexer-markets

Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):  [(https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)](https://coinmarketcap.com/currencies/lexer/)

Short Description (to be shown on DefiLlama): Lexer is a decentralized perpetual trading platform supporting a wide range of markets with deep liquidity.

Token address and ticker if any: 0x6bB7A17AcC227fd1F6781D1EEDEAE01B42047eE0

Category (full list at https://defillama.com/categories) *Please choose only one: DEX

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): PYTH, Chainlink

forkedFrom (Does your project originate from another project): GMX

methodology (what is being counted as tvl, how is tvl being calculated): margin trading, liquidation, swap, mint, burn

Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The lexer adapter exports: 
        
 
 _______________________________________
    Dexs for 25/1/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 31/8/2021
    Methodology: api calls from grpahql
    Timestamp: 1706227198
    Total volume: 1.52 M
    
    
    
    
    Done in 3.09s.

**Comment by llamatester** [comment]
The lexer adapter exports: 
        
 
 _______________________________________
    Fees for 25/1/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 31/8/2021
    Methodology: api calls from grpahql
    Timestamp: 1706227198
    Total fees: 1.78 k
    
    
    
    
    Done in 2.83s.

**Comment by vinccnt** [comment]
Lexer logo
https://twitter.com/lexermarkets/photo

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Pull request merged**
