### PR TITLE
add garden.finance

### PR DESCRIPTION
**Pull request by Nesopie**

### CODE REVIEW

**Comment by llamatester** [comment]
The garden adapter exports: 
        
 
 _______________________________________
    Dexs for 16/1/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 31/10/2023
    Daily volume: "3626482.060550836"
    Total volume: "26029829.169172954"
    Daily user fees: "5729.109034006324"
    Total user fees: "39938.70541800378"
    
    
    BITCOIN 👇
    Backfill start time: 31/10/2023
    Daily volume: "13135479.194633706"
    Total volume: "71141365.4109933"
    Daily user fees: "20181.868161567952"
    Total user fees: "106356.17701644261"
    
    
    ARBITRUM 👇
    Backfill start time: 31/10/2023
    Daily volume: "9508086.182931213"
    Total volume: "45112519.61583265"
    Daily user fees: "13541.807975916963"
    Total user fees: "67400.84561070356"
    
    
    
    
    Done in 5.82s.

**Comment by dtmkeng** [comment]
is there example tx for calcuate fees and volume

**Comment by Nesopie** [comment]
Yes, here's an order that goes from BTC to WBTC on arbitrum: https://api.garden.finance/orders/5000.
The BTC traded is 20000000 satoshis (in order.initiatorAtomicSwap.amount, [txHash on order.initiatorAtomicSwap. initiateTxHash](https://mempool.space/tx/9b824777f258eb30ed8d54530dc54a44ad89430bce65ca9680e8cf20a418f5e1))
The received WBTC is 0.3% of the send BTC which is 0.1994 WBTC [txHash on order.followerAtomicSwap.redeemTxHash](https://arbiscan.io/tx/0x716c64998e7e03db11a9290bc793dd3cf7e4ca4dac36fd52600914cf0826fd8b)

Calculated Volume is 0.2 BTC + 0.1994 WBTC

**Comment by Nesopie** [comment]
No there is no tvl adapter

**Comment by dtmkeng** [comment]
> No there is no tvl adapter

is it aggregator ?

**Comment by Nesopie** [comment]
No, it's more of a bridge/dex

**Comment by dtmkeng** [comment]
> No, it's more of a bridge/dex

it is bridge volume it think should lit on bridge not dexs

**Comment by dtmkeng** [comment]
> Oh, sorry about that. Where exactly do I list bridges?

https://github.com/DefiLlama/bridges-server

**Comment by Nesopie** [comment]
Ah, but it does make sense to list it under dexs since we use atomic swaps to "bridge" assets

**Comment by llamatester** [comment]
The garden adapter exports: 
        
 
 _______________________________________
    Fees for 21/1/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 31/10/2023
    Daily user fees: "0"
    Total user fees: "43477.053626818386"
    
    
    BITCOIN 👇
    Backfill start time: 31/10/2023
    Daily user fees: "0"
    Total user fees: "121979.083499245"
    
    
    ARBITRUM 👇
    Backfill start time: 31/10/2023
    Daily user fees: "0"
    Total user fees: "78445.81204245744"
    
    
    
    
    Done in 4.63s.

**Comment by llamatester** [comment]
The garden adapter exports: 
        
 
 _______________________________________
    Fees for 31/1/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 31/10/2023
    Daily user fees: "3534.4069025409663"
    Total user fees: "91022.47549393613"
    
    
    BITCOIN 👇
    Backfill start time: 31/10/2023
    Daily user fees: "18976.680941431037"
    Total user fees: "291391.740353588"
    
    
    ARBITRUM 👇
    Backfill start time: 31/10/2023
    Daily user fees: "15560.47274066258"
    Total user fees: "202012.28795222924"
    
    
    
    
    Done in 5.77s.

**Pull request merged**
