### PR TITLE
feature: Impermax Fees and Revenue

### PR DESCRIPTION
**Pull request by pingu1**
This PR is adding the dimension for fees and revenue for the Impermax Finance project so that it can be displayed properly in the DefiLlama dashboard.

### CODE REVIEW

**Comment by llamatester** [comment]
The impermax.ts adapter exports: 
        
 
 _______________________________________
    Fees for 24/10/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0.00011980669710806696
    Daily revenue: 0.000011980669710806697
    
    
    POLYGON 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 2.3418111016742773
    Daily revenue: 0.23418111016742774
    
    
    ARBITRUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 6.331628835616439
    Daily revenue: 0.633162883561644
    
    
    AVAX 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0
    Daily revenue: 0
    
    
    MOONRIVER 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0
    Daily revenue: 0
    
    
    CANTO 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0
    Daily revenue: 0
    
    
    ERA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0
    Daily revenue: 0
    
    
    FANTOM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0.000020137595129375953
    Daily revenue: 0.0000020137595129375954
    
    
    
    
    Done in 4.88s.

**Comment by llamatester** [comment]
The impermax-finance.ts adapter exports: 
        
 
 _______________________________________
    Fees for 24/10/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0.00011980669710806696
    Daily revenue: 0.000011980669710806697
    
    
    POLYGON 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 2.3418111016742773
    Daily revenue: 0.23418111016742774
    
    
    ARBITRUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 6.331628835616439
    Daily revenue: 0.633162883561644
    
    
    AVAX 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0
    Daily revenue: 0
    
    
    MOONRIVER 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0
    Daily revenue: 0
    
    
    CANTO 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0
    Daily revenue: 0
    
    
    ERA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0
    Daily revenue: 0
    
    
    FANTOM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698191998
    Daily fees: 0.000020137595129375953
    Daily revenue: 0.0000020137595129375954
    
    
    
    
    Done in 5.30s.

**Comment by dtmkeng** [comment]
look good, could you add `meta` like this https://github.com/DefiLlama/dimension-adapters/blob/master/fees/gmx.ts#L65 for explain ppl about meta your protocol fees/rev

**Comment by dtmkeng** [comment]
thank you

**Pull request merged**
