### PR TITLE
feat: lista multi protocols

### PR DESCRIPTION
**Pull request by tyler-tsai**

### CODE REVIEW

**Comment by llamatester** [comment]
The lista-slisbnb adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees lista-slisbnb
    
    🦙 Running LISTA-SLISBNB adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 01 Sep 2024 05:50:33 GMT
    End Date:	Mon, 02 Sep 2024 05:50:33 GMT
    ---------------------------------------------------
    
    BSC 👇
    Backfill start time: 30/8/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 132
    Daily revenue: 132
    End timestamp: 1725256232 (2024-09-02T05:50:32.000Z)

**Comment by llamatester** [comment]
The lista adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees lista
    
    🦙 Running LISTA adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 01 Sep 2024 05:50:45 GMT
    End Date:	Mon, 02 Sep 2024 05:50:45 GMT
    ---------------------------------------------------
    
    BSC 👇
    Backfill start time: 30/8/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Daily revenue: 0
    End timestamp: 1725256244 (2024-09-02T05:50:44.000Z)

**Comment by dtmkeng** [comment]
could you move lista to lista-slisbnb or lista-slisusd because now lista-dao just two breakdown

**Comment by dtmkeng** [comment]
> > could you move lista to lista-slisbnb or lista-slisusd because now lista-dao just two breakdown
> 
> Can you please help add a new protocol "LISTA"? it's different from other ones.
> 
> https://lista.org/lock

is there tvl ?

**Comment by tyler-tsai** [comment]
> > > could you move lista to lista-slisbnb or lista-slisusd because now lista-dao just two breakdown
> > 
> > 
> > Can you please help add a new protocol "LISTA"? it's different from other ones.
> > https://lista.org/lock
> 
> is there tvl ?

https://bscscan.com/token/0xfceb31a79f71ac9cbdcf853519c1b12d379edc46?a=0xd0C380D31DB43CD291E2bbE2Da2fD6dc877b87b3#readContract

The balance is locked amount.
TVL will be the lock amount multiply the LISTA price.

**Comment by dtmkeng** [comment]
> > > > could you move lista to lista-slisbnb or lista-slisusd because now lista-dao just two breakdown
> > > 
> > > 
> > > Can you please help add a new protocol "LISTA"? it's different from other ones.
> > > https://lista.org/lock
> > 
> > 
> > is there tvl ?
> 
> https://bscscan.com/token/0xfceb31a79f71ac9cbdcf853519c1b12d379edc46?a=0xd0C380D31DB43CD291E2bbE2Da2fD6dc877b87b3#readContract
> 
> The balance is locked amount. TVL will be the lock amount multiply the LISTA price.

could you create tvl adapter ?

**Comment by dtmkeng** [comment]
or move  lista-slisbnb or lista-slisusd

**Comment by tyler-tsai** [comment]
I am not sure how to create a TVL adapter, will ask for help tmrw.

**Comment by tyler-tsai** [comment]
@dtmkeng 
here's the adaptor of LISTA protocol
https://github.com/DefiLlama/DefiLlama-Adapters/pull/11504

**Comment by llamatester** [comment]
The lista-slisbnb adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees lista-slisbnb
    
    🦙 Running LISTA-SLISBNB adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 02 Sep 2024 10:53:40 GMT
    End Date:	Tue, 03 Sep 2024 10:53:40 GMT
    ---------------------------------------------------
    
    BSC 👇
    Backfill start time: 30/8/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 146
    Daily revenue: 146
    End timestamp: 1725360819 (2024-09-03T10:53:39.000Z)

**Comment by tyler-tsai** [comment]
@dtmkeng I remove the "lista" one, and keep lisUSD and slisBNB. please help review.

**Pull request merged**
