### PR TITLE
Grizzly Trade Volume and Fees adapter

### PR DESCRIPTION
**Pull request by rogsta-dev**
Adapter for the grizzly-trade platform (fork of GMX) providing volume and fees

### CODE REVIEW

**Comment by llamatester** [comment]
The grizzly-trade adapter exports: 
        
 
 _______________________________________
    Dexs for 26/7/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    BSC 👇
    Backfill start time: 21/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690329600
    Daily volume: 2316.0977205320864
    Total volume: 558006.1215683001
    
    
    Version -> DERIVATIVES
    ---------
    BSC 👇
    Backfill start time: 21/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690329600
    Daily volume: 219736.7596140586
    Total volume: 824380.3641482869
    
    
    Version -> GLL
    ---------
    BSC 👇
    Backfill start time: 21/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690329600
    Daily volume: 9776.120565044945
    Total volume: 1421724.2814579506
    
    
    Done in 4.16s.

**Comment by llamatester** [comment]
The grizzly-trade.ts adapter exports: 
        
 
 _______________________________________
    Fees for 26/7/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 21/7/2023
    Timestamp: 1690415998
    Daily fees: 276.37871492479434
    └─ Methodology: Fees from open/close position (0.1%), swap (0.2% to 0.8%), mint and burn (based on tokens balance in the pool) and borrow fee ((assets borrowed)/(total assets in pool)*0.01%)
    Daily user fees: 269.9896069342602
    └─ Methodology: Fees from open/close position (0.1%), swap (0.2% to 0.8%) and borrow fee ((assets borrowed)/(total assets in pool)*0.01%)
    Daily revenue: 138.18935746239717
    └─ Methodology: 15% Protocol revenue, 10% goes to MVX stakers and 25% are buyback and burn of GHNY
    Daily protocol revenue: 41.45680723871915
    └─ Methodology: 10% of all collected fees goes to Grizzly.fi treasury and 5% goes to marketing
    Daily holders revenue: 96.73255022367802
    └─ Methodology: 10% goes to MVX stakers and 25% are buyback and burn of GHNY
    Daily supply side revenue: 138.18935746239717
    └─ Methodology: 50% of all collected fees goes to GLL holders
    
    
    
    
    Done in 3.88s.

**Comment by llamatester** [comment]
The grizzly-trade adapter exports: 
        
 
 _______________________________________
    Dexs for 30/7/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    BSC 👇
    Backfill start time: 21/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690675200
    Daily volume: 32654.625993283425
    Total volume: 596989.0977172239
    
    
    Version -> DERIVATIVES
    ---------
    BSC 👇
    Backfill start time: 21/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690675200
    Daily volume: 52410.46041608588
    Total volume: 1015113.8373083516
    
    
    Done in 4.23s.

**Comment by llamatester** [comment]
The grizzly-trade.ts adapter exports: 
        
 
 _______________________________________
    Fees for 30/7/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 21/7/2023
    Timestamp: 1690761598
    Daily fees: 162.98744430533148
    └─ Methodology: Fees from open/close position (0.1%), swap (0.2% to 0.8%), mint and burn (based on tokens balance in the pool) and borrow fee ((assets borrowed)/(total assets in pool)*0.01%)
    Daily user fees: 161.92046149098468
    └─ Methodology: Fees from open/close position (0.1%), swap (0.2% to 0.8%) and borrow fee ((assets borrowed)/(total assets in pool)*0.01%)
    Daily revenue: 81.49372215266574
    └─ Methodology: 15% Protocol revenue, 10% goes to MVX stakers and 25% are buyback and burn of GHNY
    Daily protocol revenue: 24.448116645799722
    └─ Methodology: 10% of all collected fees goes to Grizzly.fi treasury and 5% goes to marketing
    Daily holders revenue: 57.04560550686602
    └─ Methodology: 10% goes to MVX stakers and 25% are buyback and burn of GHNY
    Daily supply side revenue: 81.49372215266574
    └─ Methodology: 50% of all collected fees goes to GLL holders
    
    
    
    
    Done in 3.53s.

**Comment by rogsta-dev** [comment]
Thanks for the comment! Should be removed now

**Comment by dtmkeng** [comment]
okay thx

**Pull request merged**
