### PR TITLE
Add Perpie Volume & Fees

### PR DESCRIPTION
**Pull request by perpie-papa**

### CODE REVIEW

**Comment by dtmkeng** [comment]
could you make query can query by timestamp   seem current query id it get all data, it consume more dune credit,

**Comment by perpie-papa** [comment]
> could you make query can query by timestamp seem current query id it get all data, it consume more dune credit,

hi mate, i don't think it matters though because we are returning `totalVolume` in the adapter, so we need to have all the data there regardless of the timestamp being passed for `dailyVolume`

**Comment by dtmkeng** [comment]
we pay dune credit if you query it consume more i can't list it could you make query fast and cheap 
or  could you make api ?

**Comment by perpie-papa** [comment]
> we pay dune credit if you query it consume more i can't list it could you make query fast and cheap or could you make api ?

is this affected by computation it consumes or by rows returned?

i.e if i wrap it in a query that just returns volume_total, volume_24hr - would that be fine?

**Comment by dtmkeng** [comment]
yes just 24h it good

**Comment by perpie-papa** [comment]
> yes just 24h it good

what about total? is it not needed at all? if so why is it an option?

**Comment by dtmkeng** [comment]
yes options if you need show on page

**Comment by perpie-papa** [comment]
@dtmkeng let me know if okay

**Comment by dtmkeng** [comment]
```
[Error: Request failed with status code 400] {
  url: 'https://api.dune.com/api/v1/query/3855069/execute',
  method: 'POST',
  axiosError: "invalid query parameters: the following keys in the query do not have matching parameters: 'timestamp'",
  chain: 'arbitrum'
}
```

**Comment by dtmkeng** [comment]
it error could you check ?

**Comment by perpie-papa** [comment]
> it error could you check ?

fixed it

**Comment by dtmkeng** [comment]
i run test at my local it 2m but does not finish could you check why query it take long time 
you can try at your local with ` npm run test aggregator-derivatives perpie`

**Comment by perpie-papa** [comment]
> i run test at my local it 2m but does not finish could you check why query it take long time you can try at your local with ` npm run test aggregator-derivatives perpie`

hi mate, i run it and it take few minutes then finish. The only async call is dune mate so dune may take few mins to make whole query (take me 250s first time and 90s second time)

ARBITRUM 👇
Backfill start time: 11/10/2023
NO METHODOLOGY SPECIFIED
Daily volume: 0
Total volume: 21.97 M
Daily revenue: 0
Total revenue: 11.46 k
End timestamp: 1719370416 (2024-06-26T02:53:36.000Z)


✨  Done in 94.78s.

**Pull request merged**
