### PR TITLE
pendle volumes

### PR DESCRIPTION
**Pull request by waynebruce0x**

### CODE REVIEW

**Comment by llamatester** [comment]
The pendle.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees pendle.ts
    
    🦙 Running PENDLE.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 18 Aug 2024 12:55:01 GMT
    End Date:	Mon, 19 Aug 2024 12:55:01 GMT
    ---------------------------------------------------
    
    [Error: Promise pool failed! 
     PromisePoolError: Failed to call: function tryAggregate(bool requireSuccess, tuple(address target, bytes callData)[] calls) payable returns (tuple(bool success, bytes returnData)[] returnData) target: 0xca11bde05977b3631167028862be2a173976ca11 params: false, 0xed0dc8c074255c277bc704d6b096167d7a6e4311,0xc4f59f9b,0x2066a650af4b6895f72e618587aad5e8120b7790,0xc4f59f9b,0x07c3de6f0c21a52538a15d00... on chain: [arbitrum] rpc: https://arb1.arbitrum.io/rpc, https://arbitrum.llamarpc.com, https://rpc.ankr.com/arbitrum, https://1rpc.io/arb, https://arb-pokt.nodies.app, https://arbitrum.blockpi.network/v1/rpc/public, https://arbitrum-one.public.blastapi.io, https://endpoints.omniatech.io/v1/arbitrum/one/public, https://arbitrum-one-rpc.publicnode.com, https://arbitrum.meowrpc.com, https://arbitrum.drpc.org, https://arbitrum.rpc.subquery.network/public, https://arbitrum-one.publicnode.com  call reverted, reason: invalid BytesLike value (argument="value", value=null, code=INVALID_ARGUMENT, version=6.10.0)   ] {
      _isCustomError: true,
      chain: 'arbitrum'
    }

**Comment by waynebruce0x** [comment]
works on local

**Comment by waynebruce0x** [comment]
Screenshot

**Comment by dtmkeng** [comment]
it is swap volume ? could you create new one under /dexs/  because it good for refill

**Comment by llamatester** [comment]
The pendle.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees pendle.ts
    
    🦙 Running PENDLE.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 18 Aug 2024 00:00:00 GMT
    End Date:	Mon, 19 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 9/6/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 7.56 k
    Daily revenue: 7.13 k
    Daily holders revenue: 7.13 k
    Daily supply side revenue: 428
    End timestamp: 1724025599 (2024-08-18T23:59:59.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 9/6/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 532
    Daily revenue: 474
    Daily holders revenue: 474
    Daily supply side revenue: 58
    End timestamp: 1724025599 (2024-08-18T23:59:59.000Z)
    
    
    BSC 👇
    Backfill start time: 9/6/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Daily revenue: 0
    Daily holders revenue: 0
    Daily supply side revenue: 0
    End timestamp: 1724025599 (2024-08-18T23:59:59.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 11/8/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Daily revenue: 0
    Daily holders revenue: 0
    Daily supply side revenue: 0
    End timestamp: 1724025599 (2024-08-18T23:59:59.000Z)
    
    
    MANTLE 👇
    Backfill start time: 27/3/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 180
    Daily revenue: 153
    Daily holders revenue: 153
    Daily supply side revenue: 27
    End timestamp: 1724025599 (2024-08-18T23:59:59.000Z)

**Pull request merged**
