### PR TITLE
Add Umoja to Options & Fees dashboards.

### PR DESCRIPTION
**Pull request by DarkRoku12**
Main site: https://umoja.xyz
dApp: https://protocol.umoja.xyz
Twitter (X): https://twitter.com/UmojaProtocol
Telegram: https://t.me/+t1uTUpaoafM4MTZh
Discord: https://discord.gg/UgKd3jYZkW
Guild.xyz: https://guild.xyz/umojaxyz

### CODE REVIEW

**Comment by llamatester** [comment]
The umoja adapter exports: 
        
 
 _______________________________________
    Fees for 23/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 24/4/2024
    Timestamp: 1713916799 (2024-04-23T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: All fees comes from synthetic option activation, which are about 1% of the notional value of option.
    
    
    
    
    Done in 11.81s.

**Comment by llamatester** [comment]
The umoja adapter exports: 
        
 
 _______________________________________
    Options for 23/4/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 24/4/2024
    Timestamp: 1713916799 (2024-04-23T23:59:59.000Z)
    Daily premium volume: 0
    Daily notional volume: 124.28 k
    
    
    
    
    Done in 8.89s.

**Comment by DarkRoku12** [comment]
> is there tvl adapter ?

No, not yet, perhaps in the future but not for a while.

**Comment by dtmkeng** [comment]
not sure can't ppl will complaint our list if you adapter does not have tvl but there is volume

**Comment by DarkRoku12** [comment]
> not sure can't ppl will complaint our list if you adapter does not have tvl but there is volume

At this moment, TVL is not a core metric of our protocol. **Notional** volume _is_, since we're only offering synthetic options.
Would this be a blocker for us to merge?

**Comment by dtmkeng** [comment]
not sure all options adapter have tvl

**Comment by DarkRoku12** [comment]
We're going to eventually have TVL once we implement the stacking part of our protocol.
We just want to showcase our synthetic options notional volume + fees, since this is what we have at the moment.
Here you can find our [audits](https://umoja.gitbook.io/umoja-protocol/resources/audits).

**Comment by DarkRoku12** [comment]
@dtmkeng our TVL has been merged already merge:
https://github.com/DefiLlama/DefiLlama-Adapters/pull/11075

Can we merge this options+fees dashboard.

**Pull request merged**
