### PR TITLE
Create covo-v2.ts

### PR DESCRIPTION
**Pull request by covofin**

### CODE REVIEW

**Comment by llamatester** [comment]
The covo-v2.ts adapter exports: 
        
 
 _______________________________________
    Fees for 9/4/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 29/3/2023
    Timestamp: 1681084798
    Daily fees: 33.097078
    └─ Methodology: Fees collected from open/close position, liquidations, and borrow fee
    Daily user fees: 33.097078
    └─ Methodology: Fees from open/close position, borrow fee, liquidation fees)
    Daily revenue: 13.238831200000002
    └─ Methodology: Revenue is 40% of all collected fees, which goes to COVO stakers
    Daily protocol revenue: 3.3097078000000004
    └─ Methodology: Treasury receives 10% of revenue
    Total protocol revenue: 3.3097078000000004
    └─ Methodology: Treasury receives 10% of revenue
    Daily holders revenue: 13.238831200000002
    └─ Methodology: 40% of all collected fees goes to COVO stakers
    Daily supply side revenue: 16.548539
    └─ Methodology: 50% of all collected fees goes to USDC Pool Liquidity providers holders
    
    
    
    
    Done in 3.86s.

**Comment by llamatester** [comment]
The covo-v2.ts adapter exports: 
        
 
 _______________________________________
    Fees for 10/4/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 29/3/2023
    Timestamp: 1681171198
    Daily fees: 0.1015
    └─ Methodology: Fees collected from open/close position, liquidations, and borrow fee
    Daily user fees: 0.1015
    └─ Methodology: Fees from open/close position, borrow fee, liquidation fees)
    Daily revenue: 0.040600000000000004
    └─ Methodology: Revenue is 40% of all collected fees, which goes to COVO stakers
    Daily protocol revenue: 0.010150000000000001
    └─ Methodology: Treasury receives 10% of revenue
    Total protocol revenue: 0.010150000000000001
    └─ Methodology: Treasury receives 10% of revenue
    Daily holders revenue: 0.040600000000000004
    └─ Methodology: 40% of all collected fees goes to COVO stakers
    Daily supply side revenue: 0.05075
    └─ Methodology: 50% of all collected fees goes to USDC Pool Liquidity providers holders
    
    
    
    
    Done in 4.77s.

**Comment by llamatester** [comment]
The Covo-v2 adapter exports: 
        
 
 _______________________________________
    Dexs for 10/4/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    POLYGON 👇
    Backfill start time: 15/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1681084800
    Daily volume: 0
    Total volume: 0
    
    
    Version -> DERIVATIVES
    ---------
    POLYGON 👇
    Backfill start time: 15/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1681084800
    Daily volume: 31140.09
    Total volume: 850785.489995
    
    
    Done in 3.90s.

**Comment by llamatester** [comment]
The covo-v2.ts adapter exports: 
        
 
 _______________________________________
    Fees for 10/4/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 29/3/2023
    Timestamp: 1681171198
    Daily fees: 0.1015
    └─ Methodology: Fees collected from open/close position, liquidations, and borrow fee
    Daily user fees: 0.1015
    └─ Methodology: Fees from open/close position, borrow fee, liquidation fees)
    Daily revenue: 0.040600000000000004
    └─ Methodology: Revenue is 40% of all collected fees, which goes to COVO stakers
    Daily protocol revenue: 0.010150000000000001
    └─ Methodology: Treasury receives 10% of revenue
    Total protocol revenue: 0.010150000000000001
    └─ Methodology: Treasury receives 10% of revenue
    Daily holders revenue: 0.040600000000000004
    └─ Methodology: 40% of all collected fees goes to COVO stakers
    Daily supply side revenue: 0.05075
    └─ Methodology: 50% of all collected fees goes to USDC Pool Liquidity providers holders
    
    
    
    
    Done in 3.46s.

**Comment by llamatester** [comment]
The covo-v2 adapter exports: 
        
 
 _______________________________________
    Dexs for 10/4/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    POLYGON 👇
    Backfill start time: 15/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1681084800
    Daily volume: 0
    Total volume: 0
    
    
    Version -> DERIVATIVES
    ---------
    POLYGON 👇
    Backfill start time: 15/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1681084800
    Daily volume: 31140.09
    Total volume: 850785.489995
    
    
    Done in 4.14s.

**Comment by llamatester** [comment]
The covo-v2.ts adapter exports: 
        
 
 _______________________________________
    Fees for 10/4/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 29/3/2023
    Timestamp: 1681171198
    Daily fees: 0.1015
    └─ Methodology: Fees collected from open/close position, liquidations, and borrow fee
    Daily user fees: 0.1015
    └─ Methodology: Fees from open/close position, borrow fee, liquidation fees)
    Daily revenue: 0.040600000000000004
    └─ Methodology: Revenue is 40% of all collected fees, which goes to COVO stakers
    Daily protocol revenue: 0.010150000000000001
    └─ Methodology: Treasury receives 10% of revenue
    Total protocol revenue: 0.010150000000000001
    └─ Methodology: Treasury receives 10% of revenue
    Daily holders revenue: 0.040600000000000004
    └─ Methodology: 40% of all collected fees goes to COVO stakers
    Daily supply side revenue: 0.05075
    └─ Methodology: 50% of all collected fees goes to USDC Pool Liquidity providers holders
    
    
    
    
    Done in 3.47s.

**Comment by dtmkeng** [comment]
seem like `volumeStats` funtion query all list volume is zero

**Comment by covofin** [comment]
Only Swaps Volume is zero, as 100% of volume is in DERIVATIVES. Covo V2 doesn't have swap feature.

Version -> SWAP
---------
POLYGON 👇
Backfill start time: 15/3/2023
NO METHODOLOGY SPECIFIED
Timestamp: 1681084800
Daily volume: 0
Total volume: 0


Version -> DERIVATIVES
---------
POLYGON 👇
Backfill start time: 15/3/2023
NO METHODOLOGY SPECIFIED
Timestamp: 1681084800
Daily volume: 31140.09
Total volume: 850785.489995

**Comment by dtmkeng** [comment]
ok I can list your DERIVATIVES volume, are you need to list fees also?

**Comment by covofin** [comment]
yes, I have also submitted Fees adaptor for V2.

**Comment by llamatester** [comment]
The covo-v2 adapter exports: 
        
 
 _______________________________________
    Dexs for 11/4/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    POLYGON 👇
    Backfill start time: 15/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1681171200
    Daily volume: 0
    Total volume: 0
    
    
    Version -> DERIVATIVES
    ---------
    POLYGON 👇
    Backfill start time: 15/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1681171200
    Daily volume: 65707.459999
    Total volume: 931611.059993
    
    
    Done in 4.95s.

**Comment by llamatester** [comment]
The covo-v2.ts adapter exports: 
        
 
 _______________________________________
    Fees for 11/4/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 29/3/2023
    Timestamp: 1681257598
    Daily fees: 0.0133346
    └─ Methodology: Fees collected from open/close position, liquidations, and borrow fee
    Daily user fees: 0.0133346
    └─ Methodology: Fees from open/close position, borrow fee, liquidation fees)
    Daily revenue: 0.00533384
    └─ Methodology: Revenue is 40% of all collected fees, which goes to COVO stakers
    Daily protocol revenue: 0.00133346
    └─ Methodology: Treasury receives 10% of revenue
    Total protocol revenue: 0.00133346
    └─ Methodology: Treasury receives 10% of revenue
    Daily holders revenue: 0.00533384
    └─ Methodology: 40% of all collected fees goes to COVO stakers
    Daily supply side revenue: 0.0066673
    └─ Methodology: 50% of all collected fees goes to USDC Pool Liquidity providers holders
    
    
    
    
    Done in 4.99s.

**Comment by dtmkeng** [comment]
I can't list the fees adapter because the volume is less

**Comment by dtmkeng** [comment]
oh sorry for my rely above on, I'll try to list 🙏

**Pull request merged**
