### PR TITLE
update ramses-v1

### PR DESCRIPTION
**Pull request by 0xShad0w**
Hi! Updating Ramses Exchange V1 pools and adding bribes. Ty!

### CODE REVIEW

**Comment by llamatester** [comment]
The ramses-exchange adapter exports: 
        
 
 _______________________________________
    Fees for 12/3/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 15/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1710287998 (2024-03-12T23:59:58.000Z)
    Daily fees: 1.04 B
    Daily revenue: 1.04 B
    Daily holders revenue: 1.04 B
    
    
    
    
    Done in 46.71s.

**Comment by dtmkeng** [comment]
thank for pr seem our fees helper have spike value will fix

**Comment by llamatester** [comment]
The ramses-exchange adapter exports: 
        
 
 _______________________________________
    Fees for 25/3/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 15/3/2023
    Daily bribes revenue: 6
    Timestamp: 1711381225 (2024-03-25T15:40:25.000Z)
    
    
    
    
    Done in 8.58s.

**Comment by llamatester** [comment]
The ramses-exchange adapter exports: 
        
 
 _______________________________________
    Fees for 25/3/2024
    _______________________________________
    
    [Error: Llama RPC error! methos: undefined 
    - host: https://arb1.arbitrum.io/rpc error: missing trie node ef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c (path ) state 0xef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c is not available, not found
    - host: https://arbitrum-one-rpc.publicnode.com error: missing trie node ef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c (path ) state 0xef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c is not available, not found
    - host: https://arbitrum.meowrpc.com error: missing trie node ef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c (path ) state 0xef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c is not available, not found
    - host: https://public.stackup.sh/api/v1/node/arbitrum-one error: missing trie node ef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c (path ) state 0xef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c is not available, not found
    - host: https://arb-pokt.nodies.app error: missing trie node ef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c (path ) state 0xef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c is not available, not found
    - host: https://arbitrum.llamarpc.com error: missing trie node ef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c (path ) state 0xef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c is not available, not found
    - host: https://1rpc.io/arb error: missing trie node ef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c (path ) state 0xef151a2d5c75f2b0dad3942604561292df736d34a3f6522d4973d5534c30bb5c is not available, not found] {
      _underlyingError: '[object Object]',
      _isCustomError: true,
      chain: 'arbitrum'
    }
    Done in 6.95s.

**Comment by llamatester** [comment]
The ramses-exchange adapter exports: 
        
 
 _______________________________________
    Fees for 25/3/2024
    _______________________________________
    
    {
      llamaRPCError: true,
      errors: [
        { host: 'https://arb1.arbitrum.io/rpc', error: [AxiosError] },
        { host: 'https://rpc.ankr.com/arbitrum', error: [AxiosError] },
        {
          host: 'https://arbitrum-one.public.blastapi.io',
          error: [AxiosError]
        }
      ],
      chain: 'arbitrum'
    }
    Done in 88.80s.

**Pull request merged**
