### PR TITLE
add El-Dorado-Exchange fees adapter

### PR DESCRIPTION
**Pull request by ede-frank**
add El-Dorado-Exchange fees adapter

### CODE REVIEW

**Comment by llamatester** [comment]
The El-Dorado-Exchange.ts adapter exports: 
        
 
 _______________________________________
    Fees for 9/1/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 10/12/2022
    Methodology: All mint, burn, marginAndLiquidation and swap fees are collected and the daily fee amount is determined. Daily revenue is calculated as 30% of the total fee.
    Timestamp: 1673308798
    Daily fees: 5233.454655166151
    Daily revenue: 1570.0363965498452
    
    
    
    
    Done in 6.21s.

**Comment by 0xtawa** [comment]
Hi @ede-frank, pr looks good. Could you rename the name to be all lowercase and breakdown the fees in the different categories if posible?
dailyUserFees, those I assume are the same as daily fees
dailyProtocolRevenue, if any of that revenue goes to treasury
dialyHoldersRevenue, if any of that revenue is distributed among holders, stakers or is used to buyback and burn
dailySupplySideRevenue, how much of that revenue goes to LPs

aslo please breakdown the methodology by categories
see an example here: https://github.com/DefiLlama/dimension-adapters/blob/master/fees/lido.ts

This way your protocol will have a fees breakdown and will be able to rank in other dashboards/charts we are building

ty

**Comment by llamatester** [comment]
The ei-dorado-exchange.ts adapter exports: 
        
 
 _______________________________________
    Fees for 11/1/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 10/12/2022
    Methodology: All mint, burn, marginAndLiquidation and swap fees are collected and the daily fee amount is determined. Daily revenue is calculated as 30% of the total fee.
    Timestamp: 1673481598
    Daily user fees: 3321.8777105784307
    Daily revenue: 996.5633131735292
    
    
    
    
    Done in 4.52s.

**Comment by ekmanss** [comment]
thx, :) .has been changed to all lowercase. revenue is calculated as 30%, No more breakdown

**Comment by 0xtawa** [comment]
ty!

**Comment by 0xtawa** [comment]
Hi, ty for the updates, will be closing this PR and opening a new one to add some commits before merging since:
- there is a typo in the filename ei-dorado-exchange->el-dorado-exchange
- `dailyUserFees` will be considered only the sum of swap fees and margin and liquidation fees since mint and burn fees I believe are paid by LPs, please correct me if I'm wrong
- Add back `dailyFees`

Here you can take a look at the PR -> https://github.com/DefiLlama/dimension-adapters/pull/182

**Pull request closed without merging**
