### PR TITLE
Add Cauldron DEX volume

### PR DESCRIPTION
**Pull request by dagurval**
Same approach as for the TVL adapter: https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/cauldron/index.js

### CODE REVIEW

**Comment by llamatester** [comment]
The cauldron adapter exports: 
        
 
 _______________________________________
    Dexs for 20/3/2024
    _______________________________________
    
    BITCOINCASH 👇
    Backfill start time: 1/7/2023
    Timestamp: 1710979199 (2024-03-20T23:59:59.000Z)
    Daily volume: 26
    Total volume: 2.11 k
    
    
    
    
    Done in 5.03s.

**Comment by llamatester** [comment]
The cauldron adapter exports: 
        
 
 _______________________________________
    Dexs for 20/3/2024
    _______________________________________
    
    BITCOINCASH 👇
    Backfill start time: 1/7/2023
    Timestamp: 1710979199 (2024-03-20T23:59:59.000Z)
    Daily volume: 11.15 k
    └─ Methodology: Scrape the blockchain and filter for spent transaction outputs that match the cauldron contract's redeem script. Check if the transaction has an output with a locking script that matches the redeem script in the input. A match on locking script means the funds are still locked in the DEX contract. Aggregate the difference of funds in contract utxos as trade volume.
    Total volume: 905.04 k
    └─ Methodology: Scrape the blockchain and filter for spent transaction outputs that match the cauldron contract's redeem script. Check if the transaction has an output with a locking script that matches the redeem script in the input. A match on locking script means the funds are still locked in the DEX contract. Aggregate the difference of funds in contract utxos as trade volume.
    
    
    
    
    Done in 5.57s.

**Comment by llamatester** [comment]
The cauldron adapter exports: 
        
 
 _______________________________________
    Dexs for 20/3/2024
    _______________________________________
    
    BITCOINCASH 👇
    Backfill start time: 1/7/2023
    Timestamp: 1710979199 (2024-03-20T23:59:59.000Z)
    Daily volume: 10.97 k
    └─ Methodology: Scrape the blockchain and filter for spent transaction outputs that match the cauldron contract's redeem script. Check if the transaction has an output with a locking script that matches the redeem script in the input. A match on locking script means the funds are still locked in the DEX contract. Aggregate the difference of funds in contract utxos as trade volume.
    Total volume: 890.19 k
    └─ Methodology: Scrape the blockchain and filter for spent transaction outputs that match the cauldron contract's redeem script. Check if the transaction has an output with a locking script that matches the redeem script in the input. A match on locking script means the funds are still locked in the DEX contract. Aggregate the difference of funds in contract utxos as trade volume.
    
    
    
    
    Done in 8.55s.

**Comment by dtmkeng** [comment]
hi why i got error when run at my local

**Comment by dtmkeng** [comment]
`https://indexer.cauldron.quest/cauldron/contract/volume?end=1710892800`

**Comment by dagurval** [comment]
> hi why i got error when run at my local `Error: connect ECONNREFUSED`

Is this one-time occurrence? It may be that the indexer restarted due to some issue, in which case it would be offline for ~10 seconds.

**Pull request merged**
