### PR TITLE
Fixing error MagpieFi Adapter.ts

### PR DESCRIPTION
**Pull request by Dongminh1997**

### CODE REVIEW

**Comment by dtmkeng** [comment]
yes i use dune only because your api it not retrurn data

**Comment by Dongminh1997** [comment]
@dtmkeng They all should work now. I checked from my local and it ran properly

**Comment by llamatester** [comment]
The magpie adapter exports: 
        
 
 _______________________________________
    Aggregators for 24/4/2024
    _______________________________________
    
    Method 2
    Method 2
    Method 2
    Method 2
    Method 2
    Method 2
    Method 2
    ETHEREUM 👇
    Backfill start time: 8/9/2022
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1713916800 (2024-04-24T00:00:00.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 8/9/2022
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1713916800 (2024-04-24T00:00:00.000Z)
    
    
    POLYGON 👇
    Backfill start time: 8/9/2022
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1713916800 (2024-04-24T00:00:00.000Z)
    
    
    AVAX 👇
    Backfill start time: 8/9/2022
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1713916800 (2024-04-24T00:00:00.000Z)
    
    
    BSC 👇
    Backfill start time: 8/9/2022
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1713916800 (2024-04-24T00:00:00.000Z)
    
    
    OPTIMISM 👇
    Backfill start time: 8/9/2022
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1713916800 (2024-04-24T00:00:00.000Z)
    
    
    BASE 👇
    Backfill start time: 8/9/2022
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1713916800 (2024-04-24T00:00:00.000Z)

**Comment by dtmkeng** [comment]
i resolve conflit, result above is it okay seem it 0 every chain

**Comment by Dongminh1997** [comment]
@dtmkeng hi, sorry for late response. Our app was attacked  few days ago so we had to shut down it so we did not have data several days so 0 is correct. Thank you for support

**Comment by Dongminh1997** [comment]
@dtmkeng Can it pull the historical data and overwrite the old data too?

**Pull request merged**
