### PR TITLE
Add zns dimensions

### PR DESCRIPTION
**Pull request by h0lme3**

### CODE REVIEW

**Comment by llamatester** [comment]
The zns adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees zns
    
    🦙 Running ZNS adapter 🦙
    ---------------------------------------------------
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The zns adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees zns
    
    🦙 Running ZNS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 23 Jul 2024 00:00:35 GMT
    End Date:	Wed, 24 Jul 2024 00:00:35 GMT
    ---------------------------------------------------
    
    Error: execution reverted (unknown custom error) (action="call", data="0x947d5a84", reason=null, transaction={ "data": "0x3115c06b000000000000000000000000000000000000000000000000000000000000001c", "to": "0x8ccD9c0A9C084412416A85Fd748c7f1E9b86442D" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.10.0)
        at makeError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ethers/src.ts/utils/errors.ts:694:21)
        at getBuiltinCallException (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ethers/src.ts/abi/abi-coder.ts:118:21)
        at Function.getBuiltinCallException (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ethers/src.ts/abi/abi-coder.ts:235:16)
        at Interface.makeError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ethers/src.ts/abi/interface.ts:925:32)
        at staticCallResult (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ethers/src.ts/contract/contract.ts:340:42)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async staticCall (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ethers/src.ts/contract/contract.ts:303:24)
        at async Proxy.priceToRegister (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ethers/src.ts/contract/contract.ts:351:41)
        at async fetchLogsAndCalculateFees (/home/runner/work/dimension-adapters/dimension-adapters/fees/zns/index.ts:73:25)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:46:18) {
      code: 'CALL_EXCEPTION',
      action: 'call',
      data: '0x947d5a84',
      reason: null,
      transaction: {
        to: '0x8ccD9c0A9C084412416A85Fd748c7f1E9b86442D',
        data: '0x3115c06b000000000000000000000000000000000000000000000000000000000000001c'
      },
      invocation: {
        method: 'priceToRegister',
        signature: 'priceToRegister(uint16)',
        args: Result(1) [ 28n ]
      },
      revert: null,
      shortMessage: 'execution reverted (unknown custom error)',
      chain: 'polygon'
    }

**Comment by llamatester** [comment]
The zns adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees zns
    
    🦙 Running ZNS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 23 Jul 2024 00:58:38 GMT
    End Date:	Wed, 24 Jul 2024 00:58:38 GMT
    ---------------------------------------------------
    
    BSC 👇
    Backfill start time: 30/4/2024
    Daily fees: 419
    └─ Methodology: registration and renew cost
    Daily revenue: 419
    └─ Methodology: registration and renew cost
    End timestamp: 1721782717 (2024-07-24T00:58:37.000Z)
    
    
    SCROLL 👇
    Backfill start time: 3/5/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721782717 (2024-07-24T00:58:37.000Z)
    
    
    BLAST 👇
    Backfill start time: 31/5/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721782717 (2024-07-24T00:58:37.000Z)
    
    
    POLYGON 👇
    Backfill start time: 31/5/2024
    Daily fees: 12
    └─ Methodology: registration and renew cost
    Daily revenue: 12
    └─ Methodology: registration and renew cost
    End timestamp: 1721782717 (2024-07-24T00:58:37.000Z)
    
    
    TAIKO 👇
    Backfill start time: 30/5/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721782717 (2024-07-24T00:58:37.000Z)
    
    
    XLAYER 👇
    Backfill start time: 17/4/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721782717 (2024-07-24T00:58:37.000Z)
    
    
    ZORA 👇
    Backfill start time: 24/6/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721782717 (2024-07-24T00:58:37.000Z)
    
    
    BOBA 👇
    Backfill start time: 29/6/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721782717 (2024-07-24T00:58:37.000Z)

**Comment by llamatester** [comment]
The zns adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees zns
    
    🦙 Running ZNS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 23 Jul 2024 11:39:22 GMT
    End Date:	Wed, 24 Jul 2024 11:39:22 GMT
    ---------------------------------------------------
    
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    BSC 👇
    Backfill start time: 30/4/2024
    Daily fees: 537
    └─ Methodology: registration and renew cost
    Daily revenue: 537
    └─ Methodology: registration and renew cost
    End timestamp: 1721821161 (2024-07-24T11:39:21.000Z)
    
    
    SCROLL 👇
    Backfill start time: 3/5/2024
    Daily fees: 19.78 k
    └─ Methodology: registration and renew cost
    Daily revenue: 19.78 k
    └─ Methodology: registration and renew cost
    End timestamp: 1721821161 (2024-07-24T11:39:21.000Z)
    
    
    BLAST 👇
    Backfill start time: 31/5/2024
    Daily fees: 57
    └─ Methodology: registration and renew cost
    Daily revenue: 57
    └─ Methodology: registration and renew cost
    End timestamp: 1721821161 (2024-07-24T11:39:21.000Z)
    
    
    POLYGON 👇
    Backfill start time: 31/5/2024
    Daily fees: 43
    └─ Methodology: registration and renew cost
    Daily revenue: 43
    └─ Methodology: registration and renew cost
    End timestamp: 1721821161 (2024-07-24T11:39:21.000Z)
    
    
    TAIKO 👇
    Backfill start time: 30/5/2024
    Daily fees: 11.14 k
    └─ Methodology: registration and renew cost
    Daily revenue: 11.14 k
    └─ Methodology: registration and renew cost
    End timestamp: 1721821161 (2024-07-24T11:39:21.000Z)
    
    
    XLAYER 👇
    Backfill start time: 17/4/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721821161 (2024-07-24T11:39:21.000Z)
    
    
    ZORA 👇
    Backfill start time: 24/6/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721821161 (2024-07-24T11:39:21.000Z)
    
    
    BOBA 👇
    Backfill start time: 29/6/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721821161 (2024-07-24T11:39:21.000Z)

**Comment by llamatester** [comment]
The zns adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees zns
    
    🦙 Running ZNS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 23 Jul 2024 13:50:26 GMT
    End Date:	Wed, 24 Jul 2024 13:50:26 GMT
    ---------------------------------------------------
    
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
    BSC 👇
    Backfill start time: 30/4/2024
    Daily fees: 415
    └─ Methodology: registration and renew cost
    Daily revenue: 415
    └─ Methodology: registration and renew cost
    End timestamp: 1721829025 (2024-07-24T13:50:25.000Z)
    
    
    SCROLL 👇
    Backfill start time: 3/5/2024
    Daily fees: 19.44 k
    └─ Methodology: registration and renew cost
    Daily revenue: 19.44 k
    └─ Methodology: registration and renew cost
    End timestamp: 1721829025 (2024-07-24T13:50:25.000Z)
    
    
    BLAST 👇
    Backfill start time: 31/5/2024
    Daily fees: 57
    └─ Methodology: registration and renew cost
    Daily revenue: 57
    └─ Methodology: registration and renew cost
    End timestamp: 1721829025 (2024-07-24T13:50:25.000Z)
    
    
    POLYGON 👇
    Backfill start time: 31/5/2024
    Daily fees: 43
    └─ Methodology: registration and renew cost
    Daily revenue: 43
    └─ Methodology: registration and renew cost
    End timestamp: 1721829025 (2024-07-24T13:50:25.000Z)
    
    
    TAIKO 👇
    Backfill start time: 30/5/2024
    Daily fees: 10.36 k
    └─ Methodology: registration and renew cost
    Daily revenue: 10.36 k
    └─ Methodology: registration and renew cost
    End timestamp: 1721829025 (2024-07-24T13:50:25.000Z)
    
    
    XLAYER 👇
    Backfill start time: 17/4/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721829025 (2024-07-24T13:50:25.000Z)
    
    
    ZORA 👇
    Backfill start time: 24/6/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721829025 (2024-07-24T13:50:25.000Z)
    
    
    BOBA 👇
    Backfill start time: 29/6/2024
    Daily fees: 0
    └─ Methodology: registration and renew cost
    Daily revenue: 0
    └─ Methodology: registration and renew cost
    End timestamp: 1721829025 (2024-07-24T13:50:25.000Z)

**Comment by dtmkeng** [comment]
i can't find `zns` at Tvl do you hava infomation ?

**Comment by h0lme3** [comment]
> i can't find `zns` at Tvl do you hava infomation ?

@dtmkeng  We've tried to list our project, ZNS with 0 TVL but rejected and closed the PR.
Here is refer [PR](https://github.com/DefiLlama/DefiLlama-Adapters/pull/11080) for information

**Comment by dtmkeng** [comment]
i see

**Comment by bond-zns** [comment]
Gm Gm   
Can we also add please zkLink ?

https://explorer.zklink.io/address/0xe0971a2B6E34bd060866081aE879630e83C4A0BD

**Comment by bond-zns** [comment]
Gm Team. How are you today?
Can is ask you to add 3 new chains, please?

1.  Sonic : https://sonicscan.org/token/0xFb2Cd41a8aeC89EFBb19575C6c48d872cE97A0A5
2. Soneium: https://soneium.blockscout.com/address/0xf180136DdC9e4F8c9b5A9FE59e2b1f07265C5D4D
3. Base: https://basescan.org/token/0x55b867a955e4384bcac03ef7f2e492f68016c152


And delete please : 

Boba and ZK link

**Pull request merged**
