### PR TITLE
add typus finance adapter

### PR DESCRIPTION
**Pull request by WayneAl**

### CODE REVIEW

**Comment by llamatester** [comment]
The typus adapter exports: 
        
 
 _______________________________________
    Options for 1/8/2023
    _______________________________________
    
    [
      { timestamp: '1683331200', value: 13.15839970588684 },
      { timestamp: '1683417600', value: 22234.116117432117 },
      { timestamp: '1683504000', value: 4506.399803161621 },
      { timestamp: '1683590400', value: 3134.6199867725372 },
      { timestamp: '1683676800', value: 7867.091265493941 },
      { timestamp: '1683763200', value: 13161.359621286392 },
      { timestamp: '1683849600', value: 23027.999711036682 },
      { timestamp: '1683936000', value: 23121.999979019165 },
      { timestamp: '1684022400', value: 19764.00089263916 },
      { timestamp: '1684108800', value: 17771.40004634857 },
      { timestamp: '1684195200', value: 1254.600019454956 },
      { timestamp: '1684281600', value: 0 },
      { timestamp: '1684368000', value: 2299.999952316284 },
      { timestamp: '1684454400', value: 14657.95934844017 },
      { timestamp: '1684540800', value: 14723.899937868118 },
      { timestamp: '1684627200', value: 112.99999952316284 },
      { timestamp: '1684713600', value: 0 },
      { timestamp: '1684800000', value: 14620.644082754707 },
      { timestamp: '1684886400', value: 21.480000019073486 },
      { timestamp: '1684972800', value: 5159.076333045959 },
      { timestamp: '1685059200', value: 2232.469895458222 },
      { timestamp: '1685145600', value: 53075.173949956894 },
      { timestamp: '1685232000', value: 0 },
      { timestamp: '1685318400', value: 0 },
      { timestamp: '1685404800', value: 2320.9998846054077 },
      { timestamp: '1685491200', value: 4.079999923706055 },
      { timestamp: '1685577600', value: 6.088378431797028 },
      { timestamp: '1685664000', value: 7587.379929065704 },
      { timestamp: '1685750400', value: 37514.02661936283 },
      { timestamp: '1685836800', value: 0 },
      { timestamp: '1685923200', value: 13.428645968437195 },
      { timestamp: '1686009600', value: 3679.3436691761017 },
      { timestamp: '1686096000', value: 2046.7910857200623 },
      { timestamp: '1686182400', value: 578.5760229825975 },
      { timestamp: '1686268800', value: 8267.32282637651 },
      { timestamp: '1686355200', value: 93044.89836966344 },
      { timestamp: '1686441600', value: 3595.103859901428 },
      { timestamp: '1686528000', value: 610.9489798545837 },
      { timestamp: '1686614400', value: 2467.855930328369 },
      { timestamp: '1686700800', value: 0 },
      { timestamp: '1686787200', value: 0 },
      { timestamp: '1686873600', value: 1265.0120258331299 },
      { timestamp: '1686960000', value: 26246.478075084822 },
      { timestamp: '1687046400', value: 7541.6600704193115 },
      { timestamp: '1687132800', value: 0 },
      { timestamp: '1687219200', value: 7553.970217704774 },
      { timestamp: '1687305600', value: 9270.584640264511 },
      { timestamp: '1687392000', value: 10989.60992884636 },
      { timestamp: '1687478400', value: 6678.455829620361 },
      { timestamp: '1687564800', value: 5437.221923343837 },
      { timestamp: '1687651200', value: 0 },
      { timestamp: '1687737600', value: 77.39199995994568 },
      { timestamp: '1687824000', value: 2992.9840564727783 },
      { timestamp: '1687910400', value: 0 },
      { timestamp: '1687996800', value: 0 },
      { timestamp: '1688083200', value: 2.6625280380249023 },
      { timestamp: '1688169600', value: 4606.311692751944 },
      { timestamp: '1688256000', value: 0 },
      { timestamp: '1688342400', value: 0 },
      { timestamp: '1688428800', value: 2778.048038482666 },
      { timestamp: '1688515200', value: 102.43569946289062 },
      { timestamp: '1688601600', value: 5276.717692613602 },
      { timestamp: '1688688000', value: 66.96010231971741 },
      { timestamp: '1688774400', value: 2334.3732833862305 },
      { timestamp: '1688860800', value: 0 },
      { timestamp: '1688947200', value: 0 },
      { timestamp: '1689033600', value: 6928.718837618828 },
      { timestamp: '1689120000', value: 66.46170020103455 },
      { timestamp: '1689206400', value: 2518.53443980217 },
      { timestamp: '1689292800', value: 267.78346252441406 },
      { timestamp: '1689379200', value: 5493.669266290963 },
      { timestamp: '1689465600', value: 4.10812783241272 },
      { timestamp: '1689552000', value: 0 },
      { timestamp: '1689638400', value: 2992.2274820804596 },
      { timestamp: '1689724800', value: 1607.573208808899 },
      { timestamp: '1689811200', value: 1847.073086977005 },
      { timestamp: '1689897600', value: 299.8213584423065 },
      { timestamp: '1689984000', value: 5789.6302490234375 },
      { timestamp: '1690070400', value: 4176.1143716573715 }
    ]
    [
      { timestamp: '1683331200', value: 0.3660243476587181 },
      { timestamp: '1683417600', value: 90.27642571022524 },
      { timestamp: '1683504000', value: 8.049971237179337 },
      { timestamp: '1683590400', value: 6.427723225456307 },
      { timestamp: '1683676800', value: 15.912573152547374 },
      { timestamp: '1683763200', value: 27.116349227736354 },
      { timestamp: '1683849600', value: 40.646077505958935 },
      { timestamp: '1683936000', value: 86.62354604139804 },
      { timestamp: '1684022400', value: 34.884884583572386 },
      { timestamp: '1684108800', value: 31.367800622608566 },
      { timestamp: '1684195200', value: 5.018400077819824 },
      { timestamp: '1684281600', value: 0 },
      { timestamp: '1684368000', value: 26.265999455451965 },
      { timestamp: '1684454400', value: 123.71317690083504 },
      { timestamp: '1684540800', value: 292.7117624302955 },
      { timestamp: '1684627200', value: 0.4349654741645336 },
      { timestamp: '1684713600', value: 0 },
      { timestamp: '1684800000', value: 51.12552671072391 },
      { timestamp: '1684886400', value: 0.07131360006332398 },
      { timestamp: '1684972800', value: 17.128133425712587 },
      { timestamp: '1685059200', value: 7.411800052921295 },
      { timestamp: '1685145600', value: 968.5339112637923 },
      { timestamp: '1685232000', value: 0 },
      { timestamp: '1685318400', value: 0 },
      { timestamp: '1685404800', value: 5.988848150248718 },
      { timestamp: '1685491200', value: 0.010527574843139648 },
      { timestamp: '1685577600', value: 0.015709769186553 },
      { timestamp: '1685664000', value: 19.57762538240909 },
      { timestamp: '1685750400', value: 706.5268787573581 },
      { timestamp: '1685836800', value: 0 },
      { timestamp: '1685923200', value: 0.03153052787712038 },
      { timestamp: '1686009600', value: 8.639117331943833 },
      { timestamp: '1686096000', value: 6.9593823825734695 },
      { timestamp: '1686182400', value: 1.790421434090537 },
      { timestamp: '1686268800', value: 24.117599495348678 },
      { timestamp: '1686355200', value: 2156.7717436612356 },
      { timestamp: '1686441600', value: 6.961228364758015 },
      { timestamp: '1686528000', value: 1.1829853972842694 },
      { timestamp: '1686614400', value: 8.666986634516716 },
      { timestamp: '1686700800', value: 0 },
      { timestamp: '1686787200', value: 0 },
      { timestamp: '1686873600', value: 4.009002741572857 },
      { timestamp: '1686960000', value: 356.591598860606 },
      { timestamp: '1687046400', value: 31.51553406021237 },
      { timestamp: '1687132800', value: 0 },
      { timestamp: '1687219200', value: 19.889082359271644 },
      { timestamp: '1687305600', value: 24.408809687476282 },
      { timestamp: '1687392000', value: 28.934884659567373 },
      { timestamp: '1687478400', value: 17.583913385938168 },
      { timestamp: '1687564800', value: 63.973428285227016 },
      { timestamp: '1687651200', value: 0 },
      { timestamp: '1687737600', value: 0.2038277746465087 },
      { timestamp: '1687824000', value: 7.882640067436695 },
      { timestamp: '1687910400', value: 0 },
      { timestamp: '1687996800', value: 0 },
      { timestamp: '1688083200', value: 0.0061931733428478245 },
      { timestamp: '1688169600', value: 22.269109473222244 },
      { timestamp: '1688256000', value: 0 },
      { timestamp: '1688342400', value: 0 },
      { timestamp: '1688428800', value: 7.3180924917092325 },
      { timestamp: '1688515200', value: 0.7627858880286483 },
      { timestamp: '1688601600', value: 15.66671169506818 },
      { timestamp: '1688688000', value: 0.420808862388134 },
      { timestamp: '1688774400', value: 12.056606084007788 },
      { timestamp: '1688860800', value: 0 },
      { timestamp: '1688947200', value: 0 },
      { timestamp: '1689033600', value: 18.76239251731647 },
      { timestamp: '1689120000', value: 0.3364055989757657 },
      { timestamp: '1689206400', value: 7.790485389962029 },
      { timestamp: '1689292800', value: 1.1401503789955523 },
      { timestamp: '1689379200', value: 40.04596217700602 },
      { timestamp: '1689465600', value: 0.029577306718690872 },
      { timestamp: '1689552000', value: 0 },
      { timestamp: '1689638400', value: 13.162687655564298 },
      { timestamp: '1689724800', value: 15.559189332659496 },
      { timestamp: '1689811200', value: 21.512341021714068 },
      { timestamp: '1689897600', value: 2.457695474827576 },
      { timestamp: '1689984000', value: 63.75583051955441 },
      { timestamp: '1690070400', value: 5.888841563117566 }
    ]
    SUI 👇
    Backfill start time: 4/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690848000
    Total notional volume: 529709.8869389589
    Daily notional volume: 0
    Total premium volume: 5585.26153839593
    Daily premium volume: 0
    
    
    
    
    Done in 4.08s.

**Comment by llamatester** [comment]
The typus adapter exports: 
        
 
 _______________________________________
    Options for 1/8/2023
    _______________________________________
    
    SUI 👇
    Backfill start time: 4/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690848000
    Total notional volume: 529709.8869389589
    Daily notional volume: 0
    Total premium volume: 5585.26153839593
    Daily premium volume: 0
    
    
    
    
    Done in 3.25s.

**Comment by WayneAl** [comment]
@dtmkeng  can you help me check this, thanks!

**Comment by WayneAl** [comment]
```
🦙 Running TYPUS adapter 🦙
_______________________________________
Options for 2/8/2023
_______________________________________

SUI 👇
Backfill start time: 4/3/2023
NO METHODOLOGY SPECIFIED
Timestamp: 1690934400
Total notional volume: 599861.5288663595
Daily notional volume: 6595.064620653153
Total premium volume: 5847.810651542555
Daily premium volume: 33.64075370109369




✨  Done in 6.04s.
```

**Comment by dtmkeng** [comment]
i run on local but got error 
`message: 'anonymous user without id'`

**Pull request merged**
