### PR TITLE
thegraph urls updated

### PR DESCRIPTION
**Pull request by cowboybebop-r**

### CODE REVIEW

**Comment by llamatester** [comment]
The azuro adapter exports: 
        
 
 _______________________________________
    Fees for 14/6/2023
    _______________________________________
    
    POLYGON 👇
    Backfill start time: 14/7/2022
    Timestamp: 1686787198
    Daily fees: 1114.731070961085
    └─ Methodology: Total pools profits (equals total bets amount minus total won bets amount)
    Daily revenue: 1114.731070961085
    └─ Methodology: Total pools profits (equals total bets amount minus total won bets amount)
    
    
    XDAI 👇
    Backfill start time: 14/7/2022
    Timestamp: 1686787198
    Daily fees: 40.48870558147314
    └─ Methodology: Total pools profits (equals total bets amount minus total won bets amount)
    Daily revenue: 40.48870558147314
    └─ Methodology: Total pools profits (equals total bets amount minus total won bets amount)
    
    
    ARBITRUM 👇
    Backfill start time: 14/7/2022
    Timestamp: 1686787198
    Daily fees: 0
    └─ Methodology: Total pools profits (equals total bets amount minus total won bets amount)
    Daily revenue: 0
    └─ Methodology: Total pools profits (equals total bets amount minus total won bets amount)
    
    
    
    
    Done in 4.01s.

**Comment by dtmkeng** [comment]
there is pr already but waiting team verify query https://github.com/DefiLlama/dimension-adapters/pull/550/files

**Comment by cowboybebop-r** [comment]
hi, @dtmkeng ! what do u mean by switching for query date range? any updates for https://github.com/DefiLlama/dimension-adapters/pull/550/files ?

**Comment by dtmkeng** [comment]
> 

fix url and change query `resolvedBlockTimestamp` intead `createdBlockTimestamp`

**Pull request closed without merging**
