### PR TITLE
add adapters of fwx-dex and update helper functions

### PR DESCRIPTION
**Pull request by idea2409**
i updated the helper functions to be able to get data from subgraph by using date id (instead of block only).

### CODE REVIEW

**Comment by llamatester** [comment]
The fwx-dex adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs fwx-dex
    
    🦙 Running FWX-DEX adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 04 Sep 2024 09:57:43 GMT
    End Date:	Thu, 05 Sep 2024 09:57:43 GMT
    ---------------------------------------------------
    
    AVAX 👇
    Backfill start time: 6/6/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1725530262 (2024-09-05T09:57:42.000Z)
    Block: 50.15 M
    Total volume: 2.38 M
    Daily volume: 36
    
    
    BASE 👇
    Backfill start time: 4/9/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1725530262 (2024-09-05T09:57:42.000Z)
    Block: 19.37 M
    Total volume: 2
    Daily volume: 1

**Comment by llamatester** [comment]
The fwx-dex adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees fwx-dex
    
    🦙 Running FWX-DEX adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 04 Sep 2024 09:57:48 GMT
    End Date:	Thu, 05 Sep 2024 09:57:48 GMT
    ---------------------------------------------------
    
    AVAX 👇
    Backfill start time: 6/6/2024
    End timestamp: 1725530267 (2024-09-05T09:57:47.000Z)
    Block: 50.15 M
    Total volume: 2.38 M
    Daily volume: 36
    Daily fees: 0
    └─ Methodology: A 0.1% of each swap is collected as trading fees
    Total fees: 2.38 k
    └─ Methodology: A 0.1% of each swap is collected as trading fees
    Daily user fees: 0
    └─ Methodology: User pays 0.1% fees on each swap
    Total user fees: 2.38 k
    └─ Methodology: User pays 0.1% fees on each swap
    Daily supply side revenue: 0
    └─ Methodology: A 0.075% from each swap is distributed to liquidity providers
    Total supply side revenue: 1.78 k
    └─ Methodology: A 0.075% from each swap is distributed to liquidity providers
    Daily protocol revenue: 0
    └─ Methodology: A 0.025% fees goes to FWX treasury
    Total protocol revenue: 594
    └─ Methodology: A 0.025% fees goes to FWX treasury
    Daily revenue: 0
    └─ Methodology: Governance revenue is 0.025% trading fees
    Total revenue: 594
    └─ Methodology: Governance revenue is 0.025% trading fees
    
    
    BASE 👇
    Backfill start time: 4/9/2024
    End timestamp: 1725530267 (2024-09-05T09:57:47.000Z)
    Block: 19.37 M
    Total volume: 2
    Daily volume: 1
    Daily fees: 0
    └─ Methodology: A 0.25% of each swap is collected as trading fees
    Total fees: 0
    └─ Methodology: A 0.25% of each swap is collected as trading fees
    Daily user fees: 0
    └─ Methodology: User pays 0.25% fees on each swap
    Total user fees: 0
    └─ Methodology: User pays 0.25% fees on each swap
    Daily supply side revenue: 0
    └─ Methodology: A 0.20833% from each swap is distributed to liquidity providers
    Total supply side revenue: 0
    └─ Methodology: A 0.20833% from each swap is distributed to liquidity providers
    Daily protocol revenue: 0
    └─ Methodology: A 0.04167% fees goes to FWX treasury
    Total protocol revenue: 0
    └─ Methodology: A 0.04167% fees goes to FWX treasury
    Daily revenue: 0
    └─ Methodology: Governance revenue is 0.04167% trading fees
    Total revenue: 0
    └─ Methodology: Governance revenue is 0.04167% trading fees

**Comment by dtmkeng** [comment]
could you revert change `helper` our working on it for fix issue ?

**Comment by idea2409** [comment]
> could you revert change `helper` our working on it for fix issue ?

u mean only remain the adapters changes, right ?

**Comment by dtmkeng** [comment]
why you the graph should use `totalVolumeFilterParams` ?

**Comment by idea2409** [comment]
the subgraph i use does not support query by block number. (i saw some of other adapters also facing the issue tho)
however we still can get the data from date id. so, i think adding **totalVolumeFilterParams** would help.

**Pull request merged**
