### PR TITLE
[emojicoin] Add fees, volume and revenue

### PR DESCRIPTION
**Pull request by CRBl69**
# Emojicoin

This PR adds the following metrics for the emojicoin.fun Aptos package:

- daily fees
- total fees
- daily volume
- total volume
- daily revenue
- total revenue

This PR supersedes #2140, which can now be closed.

### CODE REVIEW

**Comment by llamatester** [comment]
The emojicoin.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees emojicoin.ts
    
    🦙 Running EMOJICOIN.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 10:44:38 GMT
    End Date:	Wed, 11 Dec 2024 10:44:38 GMT
    ---------------------------------------------------
    
    APTOS 👇
    Backfill start time: 20/11/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 369
    Total fees: 325.52 k
    Daily revenue: 369
    Total revenue: 325.52 k
    Daily volume: 38.99 k
    Total volume: 29.94 M
    End timestamp: 1733913877 (2024-12-11T10:44:37.000Z)

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
code is good, expect why 100% fees = revenue question is still unanswered: https://github.com/DefiLlama/dimension-adapters/pull/2140#discussion_r1862153187

**Comment by alnoki** [comment]
@g1nt0ki thank you for flagging, after reviewing the DeFi Llama revenue/fee docs, we will update accordingly so that revenue is considered 0, because there is no mechanism to accrue fees to a protocol treasury or to token holders

All user fees are paid to "integrators", who are essentially rewarded via payment for order flow

@CRBl69 will update and report back

**Comment by llamabutler** [comment]
The emojicoin.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees emojicoin.ts
    
    🦙 Running EMOJICOIN.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 15 Dec 2024 09:14:01 GMT
    End Date:	Mon, 16 Dec 2024 09:14:01 GMT
    ---------------------------------------------------
    
    APTOS 👇
    Backfill start time: 20/11/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 388
    Total fees: 363.81 k
    Daily volume: 40.92 k
    Total volume: 33.51 M
    End timestamp: 1734340440 (2024-12-16T09:14:00.000Z)

**Pull request merged**
