### PR TITLE
feat: added `dailyVolume` dimension for Aftermath's smart-order router

### PR DESCRIPTION
**Pull request by admin-aftermath**
Happy holidays!

### CODE REVIEW

**Comment by dtmkeng** [comment]
is there web site, x and details for list ?

**Comment by admin-aftermath** [comment]
> is there web site, x and details for list ?

Yeah, we have two of our domains already listed on DefiLlama here: https://defillama.com/protocol/aftermath-finance

All info can remain the same as currently listed there

**Comment by dtmkeng** [comment]
@admin-aftermath  Can you help check the volume API? It seems to be returning an error:
https://aftermath.finance/api/router/volume-24hrs

**Comment by admin-aftermath** [comment]
@dtmkeng will check and get back to you once the endpoint is back online

**Pull request merged**
