### PR TITLE
feat: apollox daily volume

### PR DESCRIPTION
**Pull request by bryansniyve**

### CODE REVIEW

**Comment by llamatester** [comment]
The apollox adapter exports: 
        
 
 _______________________________________
    Dexs for 9/10/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 21/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 46626263.8896481900688
    Timestamp: 1696895998
    
    
    ARBITRUM 👇
    Backfill start time: 21/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 2247523.4332246419
    Timestamp: 1696895998
    
    
    
    
    Done in 5.24s.

**Comment by dtmkeng** [comment]
volume is from broker id ?
because bsc pancake use 2 and arb use 1,2

**Comment by bryansniyve** [comment]
> volume is from broker id ? because bsc pancake use 2 and arb use 1,2

Brokers are different front ends, but all broker vol belong to the Apollox protocol

**Comment by dtmkeng** [comment]
i

> > volume is from broker id ? because bsc pancake use 2 and arb use 1,2
> 
> Brokers are different front ends, but all broker vol belong to the Apollox protocol

i mean volume from if merge value is dupplication if can calculate value same broker id because panacake list perp value already use filter broker 2 bsc and arb use 1,2

**Comment by dtmkeng** [comment]
if data from your api calculate value from all broker value is duplicate with pancake perp

**Comment by dtmkeng** [comment]
so i use dune query filter just broker id 1 bsc

**Comment by bryansniyve** [comment]
> so i use dune query filter just broker id 1 bsc

Indeed, it make sense. Our PM gonna discuss with pancake, so wait me some while. I 'll reply to you once I get response from them.

**Comment by DrunkCzz** [comment]
Hi dtmkeng, I'm PM of Apollox

I think Defillama should be showing aggregate volumes for apollox

For example **Orderly** Network powering **Woofi** and others is able to show aggregated TVL and volumes on Defillama

Would you mind double-check? Thx

> so i use dune query filter just broker id 1 bsc

**Comment by dtmkeng** [comment]
> Hi dtmkeng, I'm PM of Apollox
> 
> I think Defillama should be showing aggregate volumes for apollox
> 
> For example **Orderly** Network powering **Woofi** and others is able to show aggregated TVL and volumes on Defillama
> 
> Would you mind double-check? Thx
> 
> > so i use dune query filter just broker id 1 bsc

you mean should show all value from all broker ?

**Comment by DrunkCzz** [comment]
> > Hi dtmkeng, I'm PM of Apollox
> > I think Defillama should be showing aggregate volumes for apollox
> > For example **Orderly** Network powering **Woofi** and others is able to show aggregated TVL and volumes on Defillama
> > Would you mind double-check? Thx
> > > so i use dune query filter just broker id 1 bsc
> 
> you mean should show all value from all broker ?

yes ,because their trades are done through apollox.

> > Hi dtmkeng, I'm PM of Apollox
> > I think Defillama should be showing aggregate volumes for apollox
> > For example **Orderly** Network powering **Woofi** and others is able to show aggregated TVL and volumes on Defillama
> > Would you mind double-check? Thx
> > > so i use dune query filter just broker id 1 bsc
> 
> you mean should show all value from all broker ?

Yes，because their trades are done through apollox.

**Comment by dtmkeng** [comment]
> es ,because their trades are done through apollox.

i can't list because is double count because pacakeswap list already (some broker)
if you need list all broker volume  you should ask Pancakeswap for delist pancakeswap perp, and list only Apollox

**Comment by apollox-docs** [comment]
Hi, we are doing rebranding recently, can you help us to update the project information?

- Update name: APX
- Protocol Information: APX Finance (APX) is the foremost decentralized exchange (DEX) for crypto derivatives on BNB Chain. Offering both order book and on-chain perpetuals, APX offers trading with up to 1001x leverage, zero to minimal slippage and competitive fees. It also offers attractive LP yield for a LP pool made of majority stablecoins. 
- Update Twitter link:
https://twitter.com/APX_Finance

**Comment by Define101** [comment]
> Hi, we are doing rebranding recently, can you help us to update the project information?
> 
> * Update name: APX
> * Protocol Information: APX Finance (APX) is the foremost decentralized exchange (DEX) for crypto derivatives on BNB Chain. Offering both order book and on-chain perpetuals, APX offers trading with up to 1001x leverage, zero to minimal slippage and competitive fees. It also offers attractive LP yield for a LP pool made of majority stablecoins.
> * Update Twitter link:
>   https://twitter.com/APX_Finance

Hello, is there any announcement regarding the rebrand?

**Comment by Define101** [comment]
This should be live within 1 hour

**Pull request closed without merging**
