### PR TITLE
Update index.ts

### PR DESCRIPTION
**Pull request by geckocoding**

### CODE REVIEW

**Comment by llamatester** [comment]
The DerpDEX adapter exports: 
        
 
 _______________________________________
    Dexs for 29/10/2023
    _______________________________________
    
    ERA 👇
    Backfill start time: 5/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698623998
    Block: 17649382
    Total volume: 10199144.511195894
    Daily volume: 24422.74521498971043385226363831683
    Daily fees: 32.67108403796414220988565689014818
    Total fees: 5571.614180829631
    Daily protocol revenue: 0
    Total protocol revenue: 0
    Daily holders revenue: 0
    Total holders revenue: 0
    Daily user fees: 0
    Total user fees: 0
    Daily supply side revenue: 32.67108403796414220988565689014818
    Total supply side revenue: 5571.614180829631
    Daily revenue: 0
    Total revenue: 0
    
    
    BASE 👇
    Backfill start time: 17/8/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698623998
    Block: 5917325
    Total volume: 155787.97377343502
    Daily volume: 1260.481038855401478820995897437086
    Daily fees: 3.055785010145586541698625092452139
    Total fees: 436.08040843605016
    Daily protocol revenue: 0
    Total protocol revenue: 0
    Daily holders revenue: 0
    Total holders revenue: 0
    Daily user fees: 0
    Total user fees: 0
    Daily supply side revenue: 3.055785010145586541698625092452139
    Total supply side revenue: 436.08040843605016
    Daily revenue: 0
    Total revenue: 0
    
    
    OP_BNB 👇
    Backfill start time: 21/9/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698623998
    Block: 6870274
    Total volume: 1468778.2913479125
    Daily volume: 2659.578917223426041571394028441071
    Daily fees: 4.551325689890428397465428435039215
    Total fees: 441.11719598310646
    Daily protocol revenue: 0
    Total protocol revenue: 0
    Daily holders revenue: 0
    Total holders revenue: 0
    Daily user fees: 0
    Total user fees: 0
    Daily supply side revenue: 4.551325689890428397465428435039215
    Total supply side revenue: 441.11719598310646
    Daily revenue: 0
    Total revenue: 0
    
    
    
    
    Done in 7.15s.

**Comment by dtmkeng** [comment]
why set user fees 0 ?
user fees is fees money from user paid for tx (not gas)

**Comment by geckocoding** [comment]
> why set user fees 0 ? user fees is fees money from user paid for tx (not gas)

If we have 4 different tiers of the fees, how we can write it as an array instead of number type?

**Comment by llamatester** [comment]
The DerpDEX adapter exports: 
        
 
 _______________________________________
    Dexs for 30/10/2023
    _______________________________________
    
    ERA 👇
    Backfill start time: 5/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698710398
    Block: 17733419
    Total volume: 10264368.532114686
    Daily volume: 65224.02091879170612674763631711488
    Daily fees: 156.8961451124529113684123681434647
    Total fees: 5586.897625086347
    Daily protocol revenue: 0
    Total protocol revenue: 0
    Daily holders revenue: 0
    Total holders revenue: 0
    Daily user fees: 156.8961451124529113684123681434647
    Total user fees: 5586.897625086347
    Daily supply side revenue: 156.8961451124529113684123681434647
    Total supply side revenue: 5586.897625086347
    Daily revenue: 0
    Total revenue: 0
    
    
    BASE 👇
    Backfill start time: 17/8/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698710398
    Block: 5960525
    Total volume: 160507.19342176244
    Daily volume: 4719.219648327405798183110233602538
    Daily fees: 12.15510812607507484410776563463629
    Total fees: 448.369501618306
    Daily protocol revenue: 0
    Total protocol revenue: 0
    Daily holders revenue: 0
    Total holders revenue: 0
    Daily user fees: 12.15510812607507484410776563463629
    Total user fees: 448.369501618306
    Daily supply side revenue: 12.15510812607507484410776563463629
    Total supply side revenue: 448.369501618306
    Daily revenue: 0
    Total revenue: 0
    
    
    OP_BNB 👇
    Backfill start time: 21/9/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1698710398
    Block: 6956674
    Total volume: 1547553.050420094
    Daily volume: 78774.75907218161504542605112701502
    Daily fees: 21.37831789816986817457018126898211
    Total fees: 460.7889976212575
    Daily protocol revenue: 0
    Total protocol revenue: 0
    Daily holders revenue: 0
    Total holders revenue: 0
    Daily user fees: 21.37831789816986817457018126898211
    Total user fees: 460.7889976212575
    Daily supply side revenue: 21.37831789816986817457018126898211
    Total supply side revenue: 460.7889976212575
    Daily revenue: 0
    Total revenue: 0
    
    
    
    
    Done in 5.41s.

**Comment by geckocoding** [comment]
Resolved the issues. Thanks

**Pull request merged**
