### PR TITLE
Add bsx volume data

### PR DESCRIPTION
**Pull request by bsx-engineering**
Add volume data for BSX exchange

https://bsx.exchange/

Can cross check the data with this Dune query: https://dune.com/queries/3634369/6121582/

### CODE REVIEW

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 30/4/2024
    _______________________________________
    
    timestamp {
      createBalances: [Function: createBalances],
      getBlock: [AsyncFunction: getBlock],
      toTimestamp: 1714446124,
      fromTimestamp: 1714359724,
      getFromBlock: [AsyncFunction: getFromBlock],
      getToBlock: [AsyncFunction: getToBlock],
      getLogs: [AsyncFunction: getLogs],
      chain: 'base',
      fromApi: <ref *1> ChainApi {
        block: 13785188,
        chain: 'base',
        timestamp: 1714359724,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: 1714359724, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *1]
      },
      toApi: <ref *2> ChainApi {
        block: 13828388,
        chain: 'base',
        timestamp: undefined,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: undefined, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *2]
      },
      api: <ref *2> ChainApi {
        block: 13828388,
        chain: 'base',
        timestamp: undefined,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: undefined, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *2]
      },
      startOfDay: 1714435200,
      startTimestamp: 1714359724,
      endTimestamp: 1714446125,
      getStartBlock: [AsyncFunction: getFromBlock],
      getEndBlock: [AsyncFunction: getToBlock]
    }
    [Error: Request failed with status code 403] {
      url: 'https://api.bsx.exchange/defillama-stats?end_time=NaN',
      method: 'GET',
      axiosError: 'Forbidden',
      chain: 'base'
    }

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 30/4/2024
    _______________________________________
    
    timestamp {
      createBalances: [Function: createBalances],
      getBlock: [AsyncFunction: getBlock],
      toTimestamp: 1714446481,
      fromTimestamp: 1714360081,
      getFromBlock: [AsyncFunction: getFromBlock],
      getToBlock: [AsyncFunction: getToBlock],
      getLogs: [AsyncFunction: getLogs],
      chain: 'base',
      fromApi: <ref *1> ChainApi {
        block: 13785367,
        chain: 'base',
        timestamp: 1714360081,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: 1714360081, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *1]
      },
      toApi: <ref *2> ChainApi {
        block: 13828567,
        chain: 'base',
        timestamp: undefined,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: undefined, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *2]
      },
      api: <ref *2> ChainApi {
        block: 13828567,
        chain: 'base',
        timestamp: undefined,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: undefined, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *2]
      },
      startOfDay: 1714435200,
      startTimestamp: 1714360081,
      endTimestamp: 1714446482,
      getStartBlock: [AsyncFunction: getFromBlock],
      getEndBlock: [AsyncFunction: getToBlock]
    }
    [Error: Request failed with status code 403] {
      url: 'https://api.bsx.exchange/defillama-stats?end_time=NaN',
      method: 'GET',
      axiosError: 'Forbidden',
      chain: 'base'
    }

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 30/4/2024
    _______________________________________
    
    timestamp {
      createBalances: [Function: createBalances],
      getBlock: [AsyncFunction: getBlock],
      toTimestamp: 1714446508,
      fromTimestamp: 1714360108,
      getFromBlock: [AsyncFunction: getFromBlock],
      getToBlock: [AsyncFunction: getToBlock],
      getLogs: [AsyncFunction: getLogs],
      chain: 'base',
      fromApi: <ref *1> ChainApi {
        block: 13785380,
        chain: 'base',
        timestamp: 1714360108,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: 1714360108, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *1]
      },
      toApi: <ref *2> ChainApi {
        block: 13828580,
        chain: 'base',
        timestamp: undefined,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: undefined, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *2]
      },
      api: <ref *2> ChainApi {
        block: 13828580,
        chain: 'base',
        timestamp: undefined,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: undefined, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *2]
      },
      startOfDay: 1714435200,
      startTimestamp: 1714360108,
      endTimestamp: 1714446509,
      getStartBlock: [AsyncFunction: getFromBlock],
      getEndBlock: [AsyncFunction: getToBlock]
    }
    [Error: Request failed with status code 403] {
      url: 'https://api.bsx.exchange/defillama-stats?end_time=NaN',
      method: 'GET',
      axiosError: 'Forbidden',
      chain: 'base'
    }

**Comment by dtmkeng** [comment]
could you fix error seem ci return result 403 from API

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 1/5/2024
    _______________________________________
    
    timestamp {
      createBalances: [Function: createBalances],
      getBlock: [AsyncFunction: getBlock],
      toTimestamp: 1714545087,
      fromTimestamp: 1714458687,
      getFromBlock: [AsyncFunction: getFromBlock],
      getToBlock: [AsyncFunction: getToBlock],
      getLogs: [AsyncFunction: getLogs],
      chain: 'base',
      fromApi: <ref *1> ChainApi {
        block: 13834670,
        chain: 'base',
        timestamp: 1714458687,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: 1714458687, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *1]
      },
      toApi: <ref *2> ChainApi {
        block: 13877870,
        chain: 'base',
        timestamp: undefined,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: undefined, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *2]
      },
      api: <ref *2> ChainApi {
        block: 13877870,
        chain: 'base',
        timestamp: undefined,
        provider: LlamaProvider {
          quorum: 1,
          eventQuorum: 1,
          eventWorkers: 1,
          isCustomLlamaProvider: true,
          rpcs: [Array],
          archivalRPCs: [],
          chainName: 'base',
          chainId: 8453,
          _isReady: [Promise]
        },
        _balances: Balances { chain: 'base', timestamp: undefined, _balances: {} },
        chainId: 8453,
        storedKey: undefined,
        api: [Circular *2]
      },
      startOfDay: 1714521600,
      startTimestamp: 1714458687,
      endTimestamp: 1714545088,
      getStartBlock: [AsyncFunction: getFromBlock],
      getEndBlock: [AsyncFunction: getToBlock]
    }
    [Error: Request failed with status code 400] {
      url: 'https://api.bsx.exchange/defillama-stats?end_time=NaN',
      method: 'GET',
      axiosError: 'parsing field "end_time": strconv.ParseInt: parsing "NaN": invalid syntax',
      chain: 'base'
    }

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 1/5/2024
    _______________________________________
    
    Error: [base]Value: NaN dailyVolume is NaN
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:48:49)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:82:24 {
      chain: 'base'
    }

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 1/5/2024
    _______________________________________
    
    Error: [base]Value: NaN dailyVolume is NaN
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:48:49)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:82:24 {
      chain: 'base'
    }

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 1/5/2024
    _______________________________________
    
    Error: [base]Value: NaN dailyVolume is NaN
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:48:49)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:82:24 {
      chain: 'base'
    }

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 1/5/2024
    _______________________________________
    
    Error: [base]Value: NaN dailyVolume is NaN
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:48:49)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:82:24 {
      chain: 'base'
    }

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 1/5/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1714549074 (2024-05-01T07:37:54.000Z)
    Daily volume: 71.67 M
    Total volume: 704.89 M

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 1/5/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1714549091 (2024-05-01T07:38:11.000Z)
    Daily volume: 71.66 M
    Total volume: 704.90 M

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 1/5/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1714549103 (2024-05-01T07:38:23.000Z)
    Daily volume: 71.66 M
    Total volume: 704.90 M

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 1/5/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1714549319 (2024-05-01T07:41:59.000Z)
    Daily volume: 71.60 M
    Total volume: 704.95 M

**Comment by llamatester** [comment]
The bsx adapter exports: 
        
 
 _______________________________________
    Dexs for 1/5/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1714549318 (2024-05-01T07:41:58.000Z)
    Daily volume: 71.60 M
    Total volume: 704.95 M

**Pull request merged**
