### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by pullstacker**
add fee and revenue infos for Monocerus

### CODE REVIEW

**Comment by llamatester** [comment]
The monocerus adapter exports: 
        
 
 _______________________________________
    Dexs for 2/1/2024
    _______________________________________
    
    Attempting with alternative query...
    Failed to get alternative daily volume on manta with graph https://api.goldsky.com/api/public/project_clpm9wvhralny01szb1oa4pue/subgraphs/monocerus/1.2.0/gn: Type `Query` has no field `uniswapDayDatass`: {"response":{"errors":[{"locations":[{"line":3,"column":5}],"message":"Type `Query` has no field `uniswapDayDatass`"}],"status":200,"headers":{}},"request":{"query":"\n  query daily_volume_alternative ($timestamp: Int) {\n    uniswapDayDatass (where: {date: $timestamp}) {\n      date\n      volumeUSD\n    }\n  }","variables":{"timestamp":1704153600}}}
    Failed to get daily volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Attempting with alternative query...
    Failed to get alternative daily volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Failed to get total volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Unable to get daily fees on avax from graph.
    Unable to get total fees on avax from graph.
    AVAX 👇
    Backfill start time: 31/12/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704239998
    Block: 39.86 M
    Total volume: NaN
    Daily volume: NaN
    Daily fees: NaN
    Total fees: NaN
    
    
    MANTA 👇
    Backfill start time: 9/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704239998
    Block: 1.00 M
    Total volume: 0
    Daily volume: NaN
    Daily fees: NaN
    Total fees: 0
    
    
    
    
    Done in 5.93s.

**Comment by llamatester** [comment]
The monocerus adapter exports: 
        
 
 _______________________________________
    Dexs for 2/1/2024
    _______________________________________
    
    MANTA 👇
    Backfill start time: 9/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704239998
    Block: 1.00 M
    Total volume: 0
    Daily volume: 0
    Daily fees: 0
    Total fees: 0
    Daily protocol revenue: 0
    Daily holders revenue: 0
    Daily user fees: 0
    Daily supply side revenue: 0
    Daily revenue: 0
    
    
    
    
    Done in 4.09s.

**Comment by pullstacker** [comment]
is it ok to be merged now ser?

**Comment by dtmkeng** [comment]
when is data is not 0 ?

**Comment by pullstacker** [comment]
after launching, mid Jan 2024... but now the tvl is already deployed

**Comment by dtmkeng** [comment]
i will wait your tvl is ok

**Comment by llamatester** [comment]
The monocerus adapter exports: 
        
 
 _______________________________________
    Dexs for 10/1/2024
    _______________________________________
    
    MANTA 👇
    Backfill start time: 9/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704931198
    Block: 1.07 M
    Total volume: 0
    Daily volume: 0
    Daily fees: 0
    Total fees: 0
    Daily protocol revenue: 0
    Daily holders revenue: 0
    Daily user fees: 0
    Daily supply side revenue: 0
    Daily revenue: 0
    
    
    
    
    Done in 4.22s.

**Pull request closed without merging**
