### PR TITLE
update adapter for mu-exchange

### PR DESCRIPTION
**Pull request by sword-mu**

### CODE REVIEW

**Comment by llamatester** [comment]
The mu-exchange adapter exports: 
        
 
 _______________________________________
    Dexs for 15/11/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    XDAI 👇
    Backfill start time: 9/11/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1700006400
    Daily volume: 208644
    Total volume: 764023
    
    
    Version -> DERIVATIVES
    ---------
    XDAI 👇
    Backfill start time: 9/11/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1700006400
    Daily volume: 208644
    Total volume: 764023
    
    
    Done in 8.84s.

**Comment by dtmkeng** [comment]
why split swap with same value ?

**Comment by sword-mu** [comment]
Hi @dtmkeng , I want to make this page https://defillama.com/chain/Gnosis show Mu Exchange's TVL and volume info. But currently only TVL is displayed. What should I do to make it happen?

**Comment by dtmkeng** [comment]
now support only swap volume `DERIVATIVES`

**Comment by sword-mu** [comment]
OK. I got it. Thanks.

**Pull request closed without merging**
