### PR TITLE
Add Valorem Fees + Options Adapters

### PR DESCRIPTION
**Pull request by nickadamson**
### Options Adapter: 
```
🦙 Running VALOREM adapter 🦙
_______________________________________
Options for 25/10/2023
_______________________________________

ARBITRUM 👇
Backfill start time: 31/8/2023
Timestamp: 1698278398
Daily notional volume: {
  "wrapped-ether:0x82af49447d8a07e3bd95bd0d56f35241523fbab1": "10.29",
  "usd-coin:0xff970a61a04b1ca14834a43f5de4533ebddb5cc8": "57329.60075"
}
└─ Methodology: Notional Volume is calculated with the market value of the Underlying + Exercise assets of a position at the time of Write/Exercise/Redeem/Transfer.
Daily premium volume: undefined
Total notional volume: 885848.5794287254
└─ Methodology: Notional Volume is calculated with the market value of the Underlying + Exercise assets of a position at the time of Write/Exercise/Redeem/Transfer.
Total premium volume: undefined
```

### Fee adapter: 
```
🦙 Running VALOREM adapter 🦙
_______________________________________
Fees for 25/10/2023
_______________________________________

ARBITRUM 👇
Backfill start time: 31/8/2023
Timestamp: 1698278398
Daily fees: 48.52761061394469830675843515540924
└─ Methodology: All fees come from users of Valorem Protocol.
Daily user fees: 48.52761061394469830675843515540924
└─ Methodology: Valorem collects fees when users write and exercise options.
Daily revenue: 48.52761061394469830675843515540924
└─ Methodology: All revenue generated comes from user fees.
Daily protocol revenue: 48.52761061394469830675843515540924
└─ Methodology: Valorem collects fees when users write and exercise options.
Total fees: 424.5295006463806
└─ Methodology: All fees come from users of Valorem Protocol.
Total user fees: 424.5295006463806
└─ Methodology: Valorem collects fees when users write and exercise options.
Total revenue: 424.5295006463806
└─ Methodology: All revenue generated comes from user fees.
Total protocol revenue: 424.5295006463806
└─ Methodology: Valorem collects fees when users write and exercise options.
```

### CODE REVIEW

**Comment by llamatester** [comment]
The valorem adapter exports: 
        
 
 _______________________________________
    Fees for 25/10/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 31/8/2023
    Timestamp: 1698278398
    Daily fees: 48.52761061394469830675843515540924
    └─ Methodology: All fees come from users of Valorem Protocol.
    Daily user fees: 48.52761061394469830675843515540924
    └─ Methodology: Valorem collects fees when users write and exercise options.
    Daily revenue: 48.52761061394469830675843515540924
    └─ Methodology: All revenue generated comes from user fees.
    Daily protocol revenue: 48.52761061394469830675843515540924
    └─ Methodology: Valorem collects fees when users write and exercise options.
    Total fees: 424.5295006463806
    └─ Methodology: All fees come from users of Valorem Protocol.
    Total user fees: 424.5295006463806
    └─ Methodology: Valorem collects fees when users write and exercise options.
    Total revenue: 424.5295006463806
    └─ Methodology: All revenue generated comes from user fees.
    Total protocol revenue: 424.5295006463806
    └─ Methodology: Valorem collects fees when users write and exercise options.
    
    
    
    
    Done in 4.62s.

**Comment by llamatester** [comment]
The valorem adapter exports: 
        
 
 _______________________________________
    Options for 25/10/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 31/8/2023
    Timestamp: 1698278398
    Daily notional volume: {
      "wrapped-ether:0x82af49447d8a07e3bd95bd0d56f35241523fbab1": "10.29",
      "usd-coin:0xff970a61a04b1ca14834a43f5de4533ebddb5cc8": "57329.60075"
    }
    └─ Methodology: Notional Volume is calculated with the market value of the Underlying + Exercise assets of a position at the time of Write/Exercise/Redeem/Transfer.
    Daily premium volume: undefined
    Total notional volume: 885848.5794287254
    └─ Methodology: Notional Volume is calculated with the market value of the Underlying + Exercise assets of a position at the time of Write/Exercise/Redeem/Transfer.
    Total premium volume: undefined
    
    
    
    
    Done in 4.96s.

**Comment by dtmkeng** [comment]
hi @nickadamson thank you for pr
if you return dailyVolume type object 
`key` is `chain` + `:` + `token_address` 
example: `arbitrum:0x000`: '0.01', or you can `Daily notional volume` is unit of USD

**Comment by llamatester** [comment]
The valorem adapter exports: 
        
 
 _______________________________________
    Fees for 25/10/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 31/8/2023
    Timestamp: 1698278398
    Daily fees: 48.52761061394469830675843515540924
    └─ Methodology: All fees come from users of Valorem Protocol.
    Daily user fees: 48.52761061394469830675843515540924
    └─ Methodology: Valorem collects fees when users write and exercise options.
    Daily revenue: 48.52761061394469830675843515540924
    └─ Methodology: All revenue generated comes from user fees.
    Daily protocol revenue: 48.52761061394469830675843515540924
    └─ Methodology: Valorem collects fees when users write and exercise options.
    Total fees: 424.5295006463806
    └─ Methodology: All fees come from users of Valorem Protocol.
    Total user fees: 424.5295006463806
    └─ Methodology: Valorem collects fees when users write and exercise options.
    Total revenue: 424.5295006463806
    └─ Methodology: All revenue generated comes from user fees.
    Total protocol revenue: 424.5295006463806
    └─ Methodology: Valorem collects fees when users write and exercise options.
    
    
    
    
    Done in 3.74s.

**Comment by llamatester** [comment]
The valorem adapter exports: 
        
 
 _______________________________________
    Options for 25/10/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 31/8/2023
    Timestamp: 1698278398
    Daily notional volume: {
      "arbitrum:0x82af49447d8a07e3bd95bd0d56f35241523fbab1": "10.29",
      "arbitrum:0xff970a61a04b1ca14834a43f5de4533ebddb5cc8": "57329.60075"
    }
    └─ Methodology: Notional Volume is calculated with the market value of the Underlying + Exercise assets of a position at the time of Write/Exercise/Redeem/Transfer.
    Daily premium volume: undefined
    Total notional volume: 885848.5794287254
    └─ Methodology: Notional Volume is calculated with the market value of the Underlying + Exercise assets of a position at the time of Write/Exercise/Redeem/Transfer.
    Total premium volume: undefined
    
    
    
    
    Done in 3.83s.

**Comment by nickadamson** [comment]
> hi @nickadamson thank you for pr if you return dailyVolume type object `key` is `chain` + `:` + `token_address` example: `arbitrum:0x000`: '0.01', or you can `Daily notional volume` is unit of USD

@dtmkeng thank you! I misunderstood the docs.
I have pushed a fix for the dailyVolume token key 👍

**Comment by llamatester** [comment]
The valorem adapter exports: 
        
 
 _______________________________________
    Fees for 26/10/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 31/8/2023
    Timestamp: 1698364798
    Daily fees: 60.31843531048163255135635834372958
    └─ Methodology: All fees come from users of Valorem Protocol.
    Daily user fees: 60.31843531048163255135635834372958
    └─ Methodology: Valorem collects fees when users write and exercise options.
    Daily revenue: 60.31843531048163255135635834372958
    └─ Methodology: All revenue generated comes from user fees.
    Daily protocol revenue: 60.31843531048163255135635834372958
    └─ Methodology: Valorem collects fees when users write and exercise options.
    Total fees: 484.8479359568622
    └─ Methodology: All fees come from users of Valorem Protocol.
    Total user fees: 484.8479359568622
    └─ Methodology: Valorem collects fees when users write and exercise options.
    Total revenue: 484.8479359568622
    └─ Methodology: All revenue generated comes from user fees.
    Total protocol revenue: 484.8479359568622
    └─ Methodology: Valorem collects fees when users write and exercise options.
    
    
    
    
    Done in 3.55s.

**Comment by llamatester** [comment]
The valorem adapter exports: 
        
 
 _______________________________________
    Options for 26/10/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 31/8/2023
    Timestamp: 1698364798
    Daily notional volume: {
      "arbitrum:0x82af49447d8a07e3bd95bd0d56f35241523fbab1": "32.1",
      "arbitrum:0xff970a61a04b1ca14834a43f5de4533ebddb5cc8": "33037.7015"
    }
    └─ Methodology: Notional Volume is calculated with the market value of the Underlying + Exercise assets of a position at the time of Write/Exercise/Redeem/Transfer.
    Daily premium volume: undefined
    Total notional volume: 976860.1101720886
    └─ Methodology: Notional Volume is calculated with the market value of the Underlying + Exercise assets of a position at the time of Write/Exercise/Redeem/Transfer.
    Total premium volume: undefined
    
    
    
    
    Done in 3.88s.

**Pull request merged**
