### PR TITLE
Add lumia adapter

### PR DESCRIPTION
**Pull request by OlyaKanishcheva**

### CODE REVIEW

**Comment by llamatester** [comment]
The lumia adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators lumia
    
    🦙 Running LUMIA adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 26 Aug 2024 11:59:03 GMT
    End Date:	Tue, 27 Aug 2024 11:59:03 GMT
    ---------------------------------------------------
    
    ETHEREUM 👇
    Backfill start time: 1/1/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 113.06 k
    Total volume: 74.49 M
    End timestamp: 1724759942 (2024-08-27T11:59:02.000Z)
    
    
    BSC 👇
    Backfill start time: 1/1/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 266.72 k
    Total volume: 338.10 M
    End timestamp: 1724759942 (2024-08-27T11:59:02.000Z)
    
    
    POLYGON 👇
    Backfill start time: 1/1/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 182.58 k
    Total volume: 39.77 M
    End timestamp: 1724759942 (2024-08-27T11:59:02.000Z)
    
    
    ARBITRUM 👇
    Backfill start time: 1/1/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 43.07 k
    Total volume: 23.40 M
    End timestamp: 1724759942 (2024-08-27T11:59:02.000Z)
    
    
    OP_BNB 👇
    Backfill start time: 1/1/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Total volume: 11.08 M
    End timestamp: 1724759942 (2024-08-27T11:59:02.000Z)
    
    
    LINEA 👇
    Backfill start time: 1/1/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Total volume: 21.19 M
    End timestamp: 1724759942 (2024-08-27T11:59:02.000Z)

**Comment by dtmkeng** [comment]
is there details protocol for list ?

**Comment by OlyaKanishcheva** [comment]
> is there details protocol for list ?

Is there some specific list of details? I will provide

**Comment by dtmkeng** [comment]
> > is there details protocol for list ?
> 
> Is there some specific list of details? I will provide

web site x description

**Comment by OlyaKanishcheva** [comment]
> > > is there details protocol for list ?
> > 
> > 
> > Is there some specific list of details? I will provide
> 
> web site x description

Thanks for the answer!

https://lumia.stream/
Lumia Stream is a highly capital efficient liquidity infrastracture integrated across major EVM blockchains and the Lumia L2, enabling decentralized access to centralized exchange liquidity. Through its Delta Neutral Liquidity Provision (DNLP), Lumia Stream maximizes capital efficiency for Liquidity Providers.

**Comment by dtmkeng** [comment]
why api is `https://orion.xyz/` but web is `https://lumia.stream/` ??

**Comment by OlyaKanishcheva** [comment]
> why api is `https://orion.xyz/` but web is `https://lumia.stream/` ??

we are performing a rebranding from Orion to Lumia, which will be supported by Binance

**Comment by Define101** [comment]
@OlyaKanishcheva  any public announcement?

**Comment by OlyaKanishcheva** [comment]
> @OlyaKanishcheva any public announcement?

What do you mean? From our side?

**Comment by Define101** [comment]
@OlyaKanishcheva any public announcement talking about the rebrand

**Comment by OlyaKanishcheva** [comment]
> @OlyaKanishcheva any public announcement talking about the rebrand

Yes - 
https://medium.com/@TradeOnOrion/orion-dao-votes-yes-orn-to-lumia-b7bafcbdf10c
https://x.com/BuildOnLumia/status/1762135413295075709
https://coinmarketcap.com/community/articles/65f193f47ee8977ea2bf3352/

**Comment by Define101** [comment]
image
How should we display their new names?

**Pull request merged**
