### PR TITLE
Add AutoLayer

### PR DESCRIPTION
**Pull request by AlexS-Glue**
##### Name (to be shown on DefiLlama):

AutoLayer

##### Twitter Link:

https://x.com/AutoLayer

##### Website Link:

https://autolayer.io/

##### Logo (High resolution, will be shown with rounded borders):
logo_1920

##### Current TVL:

This project does not custody user funds. All operations are conducted through our contracts, but the funds are returned directly to the users. This allows us to calculate the transaction volume but there is no Total Value Locked (TVL).

##### Chain:

Arbitrum

##### Short Description (to be shown on DefiLlama):

The premier LRTfi app on Arbitrum

##### Category (full list at https://defillama.com/categories) *Please choose only one:

Services

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):

Chainlink

##### Implementation Details: Briefly describe how the oracle is integrated into your project:

Chainlink price feeds is used to calculate the USD value of the LST and LRT assets which are obtained by the users through Autolayer Dapp. This USD value is necessary to calculate the amount of AutolayerPoints users earn because 1 USD is equivalent to 1 AutolayerPoints

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

This contract uses Chainlink oracle https://arbiscan.io/address/0x752853f01379D019771d7F1050ABF158e2031024#code

##### forkedFrom (Does your project originate from another project):

No

##### Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The autolayer adapter exports: 
        
 
 _______________________________________
    Dexs for 5/6/2024
    _______________________________________
    
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/3800672/execute',
      method: 'POST',
      axiosError: 'invalid API Key',
      chain: 'arbitrum'
    }

**Comment by dtmkeng** [comment]
could you change to use getLogs instead dune API ?

**Comment by AlexS-Glue** [comment]
> could you change to use getLogs instead dune API ?

Unfortunately, with `getLogs`, it is quite complicated to capture the entire volume, as the only event we manage to follow this way only covers certain types of operations (the ones that give points), and not the rest. It would be great to be able to proceed with Dune, as we could capture all the calls there, regardless of whether they generate the event or not.

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Comment by g1nt0ki** [comment]
hmm, I looked at the dune query, it is quite easy to convert it to on chain adapter: 
image
 but the query looks wrong? one of it is EOA and can see none of the contracts with 0x235c18fe54960bc2b1072d9a404e225ef54b523b788af3cb8510696cd28d1621 event

**Comment by g1nt0ki** [comment]
am I looking at the right query? https://dune.com/queries/3800672/6390081

**Comment by g1nt0ki** [comment]
hmm, we can simplify it into all tokens sent as input to autolayerForwarder contract, so the adapter would be something like:


    import { FetchOptions, SimpleAdapter } from "../adapters/types";
    import { addTokensReceived } from "../helpers/token";


    async function fetch(options: FetchOptions) {
      const dailyVolume = await addTokensReceived({ targets: config[options.chain], options })
      return { dailyVolume }
    }


    const config: any = {
      ethereum: ['0x9566D8998a47D53C948803744864e63456177353'],
      arbitrum: ['0x9566D8998a47D53C948803744864e63456177353'],
    }

    export default {
      adapter:
        Object.keys(config).reduce((acc, chain) => ({
          ...acc,
          [chain]: {
            fetch,
            start: 1683893231
          }
        }), {})
      ,
      version: 2
    } as SimpleAdapter;

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
.

**Pull request closed without merging**
