### PR TITLE
add Sanctum volume calculation

### PR DESCRIPTION
**Pull request by Johnnycus**

### CODE REVIEW

**Comment by dtmkeng** [comment]
if you need get value from dune api could you use helper function like this https://github.com/DefiLlama/dimension-adapters/blob/master/fees/fantom.ts#L11 ?

**Comment by dtmkeng** [comment]
Sanctum is yield with volume did you need list ? dexs it support swap volume or `derivatives` 
if you need list fees/rev plz create under folder `fees`

**Comment by Johnnycus** [comment]
> if you need get value from dune api could you use helper function like this https://github.com/DefiLlama/dimension-adapters/blob/master/fees/fantom.ts#L11 ?

dune query takes about 20 minutes to complete and is set to run daily. can we avoid re-running it and just fetch the result?

**Comment by Johnnycus** [comment]
> Sanctum is yield with volume did you need list ? dexs it support swap volume or `derivatives` if you need list fees/rev plz create under folder `fees`

we want to change Sanctum category from Yield to Dexes

**Comment by dtmkeng** [comment]
> > if you need get value from dune api could you use helper function like this https://github.com/DefiLlama/dimension-adapters/blob/master/fees/fantom.ts#L11 ?
> 
> dune query takes about 20 minutes to complete and is set to run daily. can we avoid re-running it and just fetch the result?

yeah  just query daily for fast get result if query take time when collect data it will be timeout

**Comment by llamatester** [comment]
The sanctum adapter exports: 
        
 
 _______________________________________
    Dexs for 11/12/2023
    _______________________________________
    
    make query dune [AxiosError: Request failed with status code 401] {
      code: 'ERR_BAD_REQUEST',
      config: {
        transitional: {
          silentJSONParsing: true,
          forcedJSONParsing: true,
          clarifyTimeoutError: false
        },
        adapter: [Function: httpAdapter],
        transformRequest: [ [Function: transformRequest] ],
        transformResponse: [ [Function: transformResponse] ],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        env: { FormData: [Function] },
        validateStatus: [Function: validateStatus],
        headers: {
          Accept: 'application/json, text/plain, */*',
          'Content-Type': 'application/json',
          'x-dune-api-key': 'L0URsn5vwgyrWbBpQo9yS1E3C1DBJpZh',
          'User-Agent': 'axios/0.27.2',
          'Content-Length': 43
        },
        method: 'post',
        url: 'https://api.dune.com/api/v1/query/3276095/execute',
        data: '{"query_parameters":{"endTime":1702339198}}'
      },
      request: <ref *1> ClientRequest {
        _events: [Object: null prototype] {
          abort: [Function (anonymous)],
          aborted: [Function (anonymous)],
          connect: [Function (anonymous)],
          error: [Function (anonymous)],
          socket: [Function (anonymous)],
          timeout: [Function (anonymous)],
          finish: [Function: requestOnFinish]
        },
        _eventsCount: 7,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        destroyed: false,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        maxRequestsOnConnectionReached: false,
        _defaultKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        strictContentLength: false,
        _contentLength: 43,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        _closed: false,
        socket: TLSSocket {
          _tlsOptions: [Object],
          _secureEstablished: true,
          _securePending: false,
          _newSessionPending: false,
          _controlReleased: true,
          secureConnecting: false,
          _SNICallback: null,
          servername: 'api.dune.com',
          alpnProtocol: false,
          authorized: true,
          authorizationError: null,
          encrypted: true,
          _events: [Object: null prototype],
          _eventsCount: 10,
          connecting: false,
          _hadError: false,
          _parent: null,
          _host: 'api.dune.com',
          _closeAfterHandlingError: false,
          _readableState: [ReadableState],
          _maxListeners: undefined,
          _writableState: [WritableState],
          allowHalfOpen: false,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: undefined,
          _server: null,
          ssl: [TLSWrap],
          _requestCert: true,
          _rejectUnauthorized: true,
          parser: null,
          _httpMessage: [Circular *1],
          [Symbol(alpncallback)]: null,
          [Symbol(res)]: [TLSWrap],
          [Symbol(verified)]: true,
          [Symbol(pendingSession)]: null,
          [Symbol(async_id_symbol)]: 8,
          [Symbol(kHandle)]: [TLSWrap],
          [Symbol(lastWriteQueueSize)]: 0,
          [Symbol(timeout)]: null,
          [Symbol(kBuffer)]: null,
          [Symbol(kBufferCb)]: null,
          [Symbol(kBufferGen)]: null,
          [Symbol(kCapture)]: false,
          [Symbol(kSetNoDelay)]: false,
          [Symbol(kSetKeepAlive)]: true,
          [Symbol(kSetKeepAliveInitialDelay)]: 60,
          [Symbol(kBytesRead)]: 0,
          [Symbol(kBytesWritten)]: 0,
          [Symbol(connect-options)]: [Object]
        },
        _header: 'POST /api/v1/query/3276095/execute HTTP/1.1\r\n' +
          'Accept: application/json, text/plain, */*\r\n' +
          'Content-Type: application/json\r\n' +
          'x-dune-api-key: L0URsn5vwgyrWbBpQo9yS1E3C1DBJpZh\r\n' +
          'User-Agent: axios/0.27.2\r\n' +
          'Content-Length: 43\r\n' +
          'Host: api.dune.com\r\n' +
          'Connection: close\r\n' +
          '\r\n',
        _keepAliveTimeout: 0,
        _onPendingData: [Function: nop],
        agent: Agent {
          _events: [Object: null prototype],
          _eventsCount: 2,
          _maxListeners: undefined,
          defaultPort: 443,
          protocol: 'https:',
          options: [Object: null prototype],
          requests: [Object: null prototype] {},
          sockets: [Object: null prototype],
          freeSockets: [Object: null prototype] {},
          keepAliveMsecs: 1000,
          keepAlive: false,
          maxSockets: Infinity,
          maxFreeSockets: 256,
          scheduling: 'lifo',
          maxTotalSockets: Infinity,
          totalSocketCount: 1,
          maxCachedSessions: 100,
          _sessionCache: [Object],
          [Symbol(kCapture)]: false
        },
        socketPath: undefined,
        method: 'POST',
        maxHeaderSize: undefined,
        insecureHTTPParser: undefined,
        joinDuplicateHeaders: undefined,
        path: '/api/v1/query/3276095/execute',
        _ended: true,
        res: IncomingMessage {
          _readableState: [ReadableState],
          _events: [Object: null prototype],
          _eventsCount: 4,
          _maxListeners: undefined,
          socket: [TLSSocket],
          httpVersionMajor: 1,
          httpVersionMinor: 1,
          httpVersion: '1.1',
          complete: true,
          rawHeaders: [Array],
          rawTrailers: [],
          joinDuplicateHeaders: undefined,
          aborted: false,
          upgrade: false,
          url: '',
          method: null,
          statusCode: 401,
          statusMessage: 'Unauthorized',
          client: [TLSSocket],
          _consuming: false,
          _dumped: false,
          req: [Circular *1],
          responseUrl: 'https://api.dune.com/api/v1/query/3276095/execute',
          redirects: [],
          [Symbol(kCapture)]: false,
          [Symbol(kHeaders)]: [Object],
          [Symbol(kHeadersCount)]: 18,
          [Symbol(kTrailers)]: null,
          [Symbol(kTrailersCount)]: 0
        },
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        reusedSocket: false,
        host: 'api.dune.com',
        protocol: 'https:',
        _redirectable: Writable {
          _writableState: [WritableState],
          _events: [Object: null prototype],
          _eventsCount: 3,
          _maxListeners: undefined,
          _options: [Object],
          _ended: true,
          _ending: true,
          _redirectCount: 0,
          _redirects: [],
          _requestBodyLength: 43,
          _requestBodyBuffers: [],
          _onNativeResponse: [Function (anonymous)],
          _currentRequest: [Circular *1],
          _currentUrl: 'https://api.dune.com/api/v1/query/3276095/execute',
          [Symbol(kCapture)]: false
        },
        [Symbol(kCapture)]: false,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(kNeedDrain)]: false,
        [Symbol(corked)]: 0,
        [Symbol(kOutHeaders)]: [Object: null prototype] {
          accept: [Array],
          'content-type': [Array],
          'x-dune-api-key': [Array],
          'user-agent': [Array],
          'content-length': [Array],
          host: [Array]
        },
        [Symbol(errored)]: null,
        [Symbol(kHighWaterMark)]: 16384,
        [Symbol(kRejectNonStandardBodyWrites)]: false,
        [Symbol(kUniqueHeaders)]: null
      },
      response: {
        status: 401,
        statusText: 'Unauthorized',
        headers: {
          date: 'Tue, 12 Dec 2023 08:20:22 GMT',
          'content-type': 'application/json; charset=utf-8',
          'content-length': '27',
          connection: 'close',
          'access-control-allow-credentials': 'true',
          'access-control-allow-headers': 'Content-Type, Content-Length, Accept-Encoding, Accept, Origin, X-Dune-Api-Key',
          'access-control-allow-methods': 'OPTIONS, GET, POST',
          'access-control-allow-origin': '*',
          'strict-transport-security': 'max-age=15724800; includeSubDomains'
        },
        config: {
          transitional: [Object],
          adapter: [Function: httpAdapter],
          transformRequest: [Array],
          transformResponse: [Array],
          timeout: 0,
          xsrfCookieName: 'XSRF-TOKEN',
          xsrfHeaderName: 'X-XSRF-TOKEN',
          maxContentLength: -1,
          maxBodyLength: -1,
          env: [Object],
          validateStatus: [Function: validateStatus],
          headers: [Object],
          method: 'post',
          url: 'https://api.dune.com/api/v1/query/3276095/execute',
          data: '{"query_parameters":{"endTime":1702339198}}'
        },
        request: <ref *1> ClientRequest {
          _events: [Object: null prototype],
          _eventsCount: 7,
          _maxListeners: undefined,
          outputData: [],
          outputSize: 0,
          writable: true,
          destroyed: false,
          _last: true,
          chunkedEncoding: false,
          shouldKeepAlive: false,
          maxRequestsOnConnectionReached: false,
          _defaultKeepAlive: true,
          useChunkedEncodingByDefault: true,
          sendDate: false,
          _removedConnection: false,
          _removedContLen: false,
          _removedTE: false,
          strictContentLength: false,
          _contentLength: 43,
          _hasBody: true,
          _trailer: '',
          finished: true,
          _headerSent: true,
          _closed: false,
          socket: [TLSSocket],
          _header: 'POST /api/v1/query/3276095/execute HTTP/1.1\r\n' +
            'Accept: application/json, text/plain, */*\r\n' +
            'Content-Type: application/json\r\n' +
            'x-dune-api-key: L0URsn5vwgyrWbBpQo9yS1E3C1DBJpZh\r\n' +
            'User-Agent: axios/0.27.2\r\n' +
            'Content-Length: 43\r\n' +
            'Host: api.dune.com\r\n' +
            'Connection: close\r\n' +
            '\r\n',
          _keepAliveTimeout: 0,
          _onPendingData: [Function: nop],
          agent: [Agent],
          socketPath: undefined,
          method: 'POST',
          maxHeaderSize: undefined,
          insecureHTTPParser: undefined,
          joinDuplicateHeaders: undefined,
          path: '/api/v1/query/3276095/execute',
          _ended: true,
          res: [IncomingMessage],
          aborted: false,
          timeoutCb: null,
          upgradeOrConnect: false,
          parser: null,
          maxHeadersCount: null,
          reusedSocket: false,
          host: 'api.dune.com',
          protocol: 'https:',
          _redirectable: [Writable],
          [Symbol(kCapture)]: false,
          [Symbol(kBytesWritten)]: 0,
          [Symbol(kNeedDrain)]: false,
          [Symbol(corked)]: 0,
          [Symbol(kOutHeaders)]: [Object: null prototype],
          [Symbol(errored)]: null,
          [Symbol(kHighWaterMark)]: 16384,
          [Symbol(kRejectNonStandardBodyWrites)]: false,
          [Symbol(kUniqueHeaders)]: null
        },
        data: { error: 'invalid API Key' }
      }
    }
    TypeError: Cannot read properties of undefined (reading 'bail')
        at onError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/async-retry/lib/index.js:26:15)
        at catchIt (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/async-retry/lib/index.js:51:11)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
    Done in 3.18s.

**Comment by dtmkeng** [comment]
`sol_dispensed` is swap volume ?

**Comment by Johnnycus** [comment]
> `sol_dispensed` is swap volume ?

yes

**Comment by dtmkeng** [comment]
im not sure about swap txs on solana
 seem query is like stake and unstake ?

**Comment by dtmkeng** [comment]
checked is there swap event on txs dune query
https://solscan.io/tx/PnaDEFvyocy2Ysd8RWVszBUGRY5Qmu9tWgEzQuE1RTor9UF4iVyCWZ5qnWA7tYirH1wb4qExaguhcnrM1wQy25H
if i misunderstand so sorry

**Comment by dtmkeng** [comment]
> > im not sure about swap txs on solana seem query is like stake and unstake ?
> 
> swap volume count solana stake accounts unstakes, xsol to xsol, xsol to sol and sol to xsol swaps (mSol -> bSol; mSol -> Sol; Sol -> mSol)

is it not user action swap ?

**Comment by Johnnycus** [comment]
> > > im not sure about swap txs on solana seem query is like stake and unstake ?
> > 
> > 
> > swap volume count solana stake accounts unstakes, xsol to xsol, xsol to sol and sol to xsol swaps (mSol -> bSol; mSol -> Sol; Sol -> mSol)
> 
> is it not user action swap ?

it is a user action swap. can be done on [unstake.it](https://unstake.sanctum.so/en/) and we're also integrated with [jup.ag](https://jup.ag/)

**Comment by Johnnycus** [comment]
> > > im not sure about swap txs on solana seem query is like stake and unstake ?
> > 
> > 
> > swap volume count solana stake accounts unstakes, xsol to xsol, xsol to sol and sol to xsol swaps (mSol -> bSol; mSol -> Sol; Sol -> mSol)
> 
> is it not user action swap ?

hi, any update on this?

**Comment by dtmkeng** [comment]
sorry it count swap volume don't like other protocol i can't list

**Comment by f8122dac91** [comment]
Essentially what we're trying to track on Defillama is similar to what jup.ag is displaying on their stats page at https://station.jup.ag/stats:

sanctum

**Comment by dtmkeng** [comment]
> > sorry it count swap volume don't like other protocol i can't list
> 
> @dtmkeng You are correct that the sanctum is fundamentally different from other "LP" based swap protocols. In the sanctum's case we translate the underlying value of the stake accounts (Solana's native on-chain representation of staked sol) and use that to perform swaps which is a far more superior mechanism to perform swaps for liquid staking tokens and stake accounts alike.
> 
> The calculated volume comes from the users:
> 
> 1. Swapping from LST -> SOL
> 2. Swapping from LST -> LST
> 3. Swapping from SOL -> LST
> 
> Which gives more meaningful data on the protocol's usefulness in my opinion. Could you point out why you cannot list the volume data on defillama?

is there example txs swap is direct to your pool ?

**Comment by f8122dac91** [comment]
> > > sorry it count swap volume don't like other protocol i can't list
> > 
> > 
> > @dtmkeng You are correct that the sanctum is fundamentally different from other "LP" based swap protocols. In the sanctum's case we translate the underlying value of the stake accounts (Solana's native on-chain representation of staked sol) and use that to perform swaps which is a far more superior mechanism to perform swaps for liquid staking tokens and stake accounts alike.
> > The calculated volume comes from the users:
> > 
> > 1. Swapping from LST -> SOL
> > 2. Swapping from LST -> LST
> > 3. Swapping from SOL -> LST
> > 
> > Which gives more meaningful data on the protocol's usefulness in my opinion. Could you point out why you cannot list the volume data on defillama?
> 
> is there example txs swap is direct to your pool ?

Here's the program address for sanctum unstake program: `unpXTU2Ndrc7WWNyEhQWe4udTzSibLPi25SXv2xbCHQ`. You can view it on:
 - solana fm: https://solana.fm/address/unpXTU2Ndrc7WWNyEhQWe4udTzSibLPi25SXv2xbCHQ?cluster=mainnet-alpha
 - solscan: https://solscan.io/account/unpXTU2Ndrc7WWNyEhQWe4udTzSibLPi25SXv2xbCHQ

Here's the sanctum's reserve sol pool:
 - solana fm: https://solana.fm/address/3rBnnH9TTgd3xwu48rnzGsaQkSr1hR64nY71DrDt6VrQ?cluster=mainnet-alpha
 - solscan: https://solscan.io/account/3rBnnH9TTgd3xwu48rnzGsaQkSr1hR64nY71DrDt6VrQ

If you're expecting swap txs to be looking anything like other AMMs/LPs then they will look very different. In normal LP's case you will see two liquidity pools e.g. bSOL and SOL. But if you think about it, swapping these two assets using LPs isn't very efficient since bSOL's underlying asset is indeed SOL. What we do is to calculate the bSOL's due amount using stake account and swap them accordingly using stake account as the intermediary value layer.

**Comment by f8122dac91** [comment]
Here's the link to our documentation if you want to dive deeper into how sanctum works under the hood: https://blog.sanctum.so/docs/behind-the-hood

**Pull request merged**
