### PR TITLE
JustBet Game Volume

### PR DESCRIPTION
**Pull request by allinJB**
Hello,

This PR is for total volume of games played in https://app.just.bet.

I would like to ask a question: 
 * Endpoint returns each games name, count and volume. Do you support showing each games with name and volume

### CODE REVIEW

**Comment by dtmkeng** [comment]
hi, it is swap volume ?

**Comment by allinJB** [comment]
No, It is volume of played games.

**Comment by dtmkeng** [comment]
> No, It is volume of played games.

we can't list volume from games but can list fees/rev about protocol

**Comment by WINRLabs** [comment]
Hey, sorry for long wait. Total Volume is returned. Is it enough ? Thank you !

**Comment by dtmkeng** [comment]
sorry sir i can't list game volume

**Pull request closed without merging**
