### PR TITLE
added drift-protocol daily volume

### PR DESCRIPTION
**Pull request by lukecaan**

### CODE REVIEW

**Comment by llamatester** [comment]
The drift-protocol adapter exports: 
        
 
 _______________________________________
    Dexs for 16/7/2023
    _______________________________________
    
    SOLANA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 2713911
    Timestamp: 1689585186.279
    
    
    
    
    Done in 3.58s.

**Comment by dtmkeng** [comment]
it is volume from `swap` or `derivatives` ?

**Comment by lukecaan** [comment]
> it is volume from `swap` or `derivatives` ?

Hi, 

Not sure if our terminology matches or not but we have 3 kinds of trades that can go through Drift:

- PERP => Drift's derivatives
- SPOT => Spot Trades using the Drift program which get filled against Drift, Serum or Phoenix orderbooks
- SWAP => Instant spot swaps, mostly done through Jupiter

The volume returned in this PR will be PERP + SPOT ... SWAP is not included

Is that ok?

**Comment by dtmkeng** [comment]
> > it is volume from `swap` or `derivatives` ?
> 
> Hi,
> 
> Not sure if our terminology matches or not but we have 3 kinds of trades that can go through Drift:
> 
> * PERP => Drift's derivatives
> * SPOT => Spot Trades using the Drift program which get filled against Drift, Serum or Phoenix orderbooks
> * SWAP => Instant spot swaps, mostly done through Jupiter
> 
> The volume returned in this PR will be PERP + SPOT ... SWAP is not included
> 
> Is that ok?

hmm you can split volume PERP and  (SPOT SWAP) ?

**Comment by lukecaan** [comment]
> hmm you can split volume PERP and (SPOT SWAP) ?

Yes, but I'm not sure in which format you want it. I can't see it in the docs or in any examples in the repo.

Like this? Otherwise can you show me what format?
```
{
    dailyVolume: {
        perp: {number},
        spot: {number},
    },
    timestamp: Date.now() / 1e3,
}
```

**Comment by dtmkeng** [comment]
> > hmm you can split volume PERP and (SPOT SWAP) ?
> 
> Yes, but I'm not sure in which format you want it. I can't see it in the docs or in any examples in the repo.
> 
> Like this? Otherwise can you show me what format?
> 
> ```
> {
>     dailyVolume: {
>         perp: {number},
>         spot: {number},
>     },
>     timestamp: number,
> }
> ```

could you follow this 
https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/gmx/index.ts#L73

**Comment by llamatester** [comment]
The drift-protocol adapter exports: 
        
 
 _______________________________________
    Dexs for 26/7/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    SOLANA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 1380616
    Timestamp: 1690461180.624
    
    
    Version -> DERIVATIVES
    ---------
    SOLANA 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 2807306
    Timestamp: 1690461180.626
    
    
    Done in 3.98s.

**Comment by lukecaan** [comment]
> > > hmm you can split volume PERP and (SPOT SWAP) ?
> > 
> > 
> > Yes, but I'm not sure in which format you want it. I can't see it in the docs or in any examples in the repo.
> > Like this? Otherwise can you show me what format?
> > ```
> > {
> >     dailyVolume: {
> >         perp: {number},
> >         spot: {number},
> >     },
> >     timestamp: number,
> > }
> > ```
> 
> could you follow this https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/gmx/index.ts#L73

Thanks for that .. should be done now 🤞

**Comment by dtmkeng** [comment]
LG thx

**Pull request merged**
