### PR TITLE
update adapter of hive swap

### PR DESCRIPTION
**Pull request by neoiss**

### CODE REVIEW

**Comment by llamatester** [comment]
The hiveswap adapter exports: 
        
 
 _______________________________________
    Dexs for 7/2/2024
    _______________________________________
    
    Failed to get total volume on map: Invalid value provided for argument `block`: Object({"number": Null}): {"response":{"errors":[{"locations":[{"line":0,"column":0}],"message":"Invalid value provided for argument `block`: Object({\"number\": Null})"}],"status":200,"headers":{}},"request":{"query":"query get_total_volume($block: Int) { \n  factories(\n    block: { number: $block }\n    ) {\n      totalVolumeUSD\n    }\n     }","variables":{"block":null}}}
    MAP 👇
    Backfill start time: 16/7/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1707350398
    Block: NaN
    Total volume: NaN
    Daily volume: 95.12 k
    
    
    
    
    Done in 4.54s.

**Comment by llamatester** [comment]
The hiveswap adapter exports: 
        
 
 _______________________________________
    Dexs for 7/2/2024
    _______________________________________
    
    Failed to get total volume on map: Invalid value provided for argument `block`: Object({"number": Null}): {"response":{"errors":[{"locations":[{"line":0,"column":0}],"message":"Invalid value provided for argument `block`: Object({\"number\": Null})"}],"status":200,"headers":{}},"request":{"query":"query get_total_volume($block: Int) { \n  factories(\n    block: { number: $block }\n    ) {\n      totalVolumeUSD\n    }\n     }","variables":{"block":null}}}
    MAP 👇
    Backfill start time: 16/7/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1707350398
    Block: NaN
    Total volume: NaN
    Daily volume: 95.12 k
    
    
    
    
    Done in 4.84s.

**Comment by dtmkeng** [comment]
should create new adapter for v3

**Comment by llamatester** [comment]
The hiveswap adapter exports: 
        
 
 _______________________________________
    Dexs for 7/2/2024
    _______________________________________
    
    MAP 👇
    Backfill start time: 16/7/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1707350398 (2024-02-07T23:59:58.000Z)
    Block: 10.09 M
    Total volume: 318.37 k
    Daily volume: 95.12 k
    
    
    
    
    Done in 6.93s.

**Comment by neoiss** [comment]
> should create new adapter for v3

ok

**Pull request closed without merging**
