### PR TITLE
Double the volume of IntentX

### PR DESCRIPTION
**Pull request by lemonpac**
The volume in our platform needs to be accounted by 2, as for every $1 traded on-chain, our solvers hedge another $1 off-chain
As part of the protocol, it's being made the volume on-chain + the volume off-chain, just as other orderbook dexes take into account
The fees are not modified with this, but it's important to modify the volume for correctness as users can also interact with solver parts

### CODE REVIEW

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 17 Jul 2024 00:00:00 GMT
    End Date:	Thu, 18 Jul 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1721174400 (2024-07-17T00:00:00.000Z)
    Daily volume: 1.87 M
    Total volume: 3.41 B
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1721174400 (2024-07-17T00:00:00.000Z)
    Daily volume: 90.99 k
    Total volume: 500.52 M
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1721174400 (2024-07-17T00:00:00.000Z)
    Daily volume: 71.00 M
    Total volume: 4.07 B

**Comment by 0xngmi** [comment]
- if its not onchain we cant verify it
- offchain volume is not done by users
- im sure many other solves for intent markets or for cowswap also hedge on CEXs, but we dont track that volume as protocol volume

so no

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 17 Jul 2024 00:00:00 GMT
    End Date:	Thu, 18 Jul 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1721174400 (2024-07-17T00:00:00.000Z)
    Daily volume: 1.87 M
    Total volume: 3.41 B
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1721174400 (2024-07-17T00:00:00.000Z)
    Daily volume: 90.99 k
    Total volume: 500.55 M
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1721174400 (2024-07-17T00:00:00.000Z)
    Daily volume: 71.00 M
    Total volume: 4.08 B

**Comment by lemonpac** [comment]
Correction here:
The volume off-chain depends on the market maker risk management strategies.
Forgetting about it, there's still 2 on-chain volumes. For every $ the user longs, there's a $ that the solver shorts and it's not being taken into account in the subgraph.
This volume is needed for our protocol metrics, as people can provide liquidity to the solver side and the solver fees is accounted from this solver volume
Orderbook dexes is doing this same stuff. Their volume is not accounting only the user one but rather both, user one and the one that the orderbook backed.
Not having this metric also gives us this disadvantage. 

One side (trader) takes long, the other side (solver) takes short
That is recorded in the bilateral trade agreement on-chain

Thanks!

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 31 Jul 2024 00:00:00 GMT
    End Date:	Thu, 01 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722384000 (2024-07-31T00:00:00.000Z)
    Daily volume: 1692370306506584.00 B
    Total volume: 3435673162602157056.00 B
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722384000 (2024-07-31T00:00:00.000Z)
    Daily volume: 191479555552000.00 B
    Total volume: 503803936238378624.00 B
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722384000 (2024-07-31T00:00:00.000Z)
    Daily volume: 10672667717065878.00 B
    Total volume: 4433700985517030400.00 B

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 31 Jul 2024 00:00:00 GMT
    End Date:	Thu, 01 Aug 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722384000 (2024-07-31T00:00:00.000Z)
    Daily volume: 1692370306506584.00 B
    Total volume: 3435673162602157056.00 B
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722384000 (2024-07-31T00:00:00.000Z)
    Daily volume: 191479555552000.00 B
    Total volume: 503803936238378624.00 B
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1722384000 (2024-07-31T00:00:00.000Z)
    Daily volume: 10672667717065878.00 B
    Total volume: 4433700985517030400.00 B

**Pull request closed without merging**
