### PR TITLE
13oct patches

### PR DESCRIPTION
**Pull request by waynebruce0x**

### CODE REVIEW

**Comment by llamatester** [comment]
The swapbased adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs swapbased
    
    🦙 Running SWAPBASED adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 13 Oct 2024 00:00:00 GMT
    End Date:	Mon, 14 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ClientError: GraphQL Error (Code: 410): {"response":{"message":"This endpoint has been removed. If you are the owner of this subgraph you can upgrade it by going here: https://thegraph.com/hosted-service. If you have any questions, reach out to support@thegraph.zendesk.com. Learn more about why this happening here: https://thegraph.com/docs/en/sunrise/#upgrading-subgraphs-to-the-graph-network","status":410,"headers":{}},"request":{"query":"\n  query get_volume($period: String!, $id: String!) {\n    volumeStats(where: { period: $period, id: $id }) {\n      liquidation\n      margin\n    }\n  }\n","variables":{"id":"1728777600:daily","period":"daily"}}}
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/src/index.ts:498:11
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:67:23)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:48:53)
        at fulfilled (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:39:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      response: {
        message: 'This endpoint has been removed. If you are the owner of this subgraph you can upgrade it by going here: https://thegraph.com/hosted-service. If you have any questions, reach out to support@thegraph.zendesk.com. Learn more about why this happening here: https://thegraph.com/docs/en/sunrise/#upgrading-subgraphs-to-the-graph-network',
        status: 410,
        headers: Headers { [Symbol(map)]: [Object: null prototype] }
      },
      request: {
        query: '\n' +
          '  query get_volume($period: String!, $id: String!) {\n' +
          '    volumeStats(where: { period: $period, id: $id }) {\n' +
          '      liquidation\n' +
          '      margin\n' +
          '    }\n' +
          '  }\n',
        variables: { id: '1728777600:daily', period: 'daily' }
      },
      chain: 'base'
    }

**Comment by llamatester** [comment]
The tangleswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs tangleswap
    
    🦙 Running TANGLESWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 13 Oct 2024 14:23:55 GMT
    End Date:	Mon, 14 Oct 2024 14:23:55 GMT
    ---------------------------------------------------
    
    Error: No pairs found, is there TVL adapter for this already?
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/helpers/uniswap.ts:108:30)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:51:18)
        at async Promise.all (index 0)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:27:20)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'shimmer_evm'
    }

**Comment by llamatester** [comment]
The vapordex adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs vapordex
    
    🦙 Running VAPORDEX adapter 🦙
    ---------------------------------------------------
    GRAPH_API_KEY env variable is not set, using the default api key
    Start Date:	Sun, 13 Oct 2024 14:24:04 GMT
    End Date:	Mon, 14 Oct 2024 14:24:04 GMT
    ---------------------------------------------------
    
    Failed to get total volume on avax https://gateway-arbitrum.network.thegraph.com/api/5a1340b49fa9efe0021452daa260564e/subgraphs/id/B6Tur5gXGCcswG8rEtmwfjBqeyDXCDUQSwM9wUXHoui5: auth error: payment required for subsequent requests for this API key
    Failed to get total volume on avax https://gateway-arbitrum.network.thegraph.com/api/5a1340b49fa9efe0021452daa260564e/subgraphs/id/B6Tur5gXGCcswG8rEtmwfjBqeyDXCDUQSwM9wUXHoui5: auth error: payment required for subsequent requests for this API key
    Error: [avax]Value: NaN dailyVolume is NaN
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:68:49)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:27:20)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:82:24 {
      chain: 'avax'
    }

**Comment by llamatester** [comment]
The biswap.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees biswap.ts
    
    🦙 Running BISWAP.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 13 Oct 2024 14:24:12 GMT
    End Date:	Mon, 14 Oct 2024 14:24:12 GMT
    ---------------------------------------------------
    
    [Error: Promise pool failed! 
     PromisePoolError: Llama RPC error! methos: undefined 
    - host: https://bsc-dataseed.binance.org error: missing trie node
    - host: https://bsc-dataseed1.defibit.io error: missing trie node
    - host: https://bsc-dataseed2.ninicoin.io error: missing trie node
    - host: https://bsc-dataseed1.ninicoin.io error: missing trie node
    - host: https://bsc-dataseed2.defibit.io error: missing trie node
    - host: https://bsc-dataseed4.bnbchain.org error: missing trie node
    - host: https://bsc-dataseed3.ninicoin.io error: missing trie node
    PromisePoolError: Llama RPC error! methos: undefined 
    - host: https://bsc-dataseed.binance.org error: missing trie node
    - host: https://bsc.blockpi.network/v1/rpc/public error: state is not available
    - host: https://bsc-dataseed4.defibit.io error: missing trie node
    - host: https://rpc-bsc.48.club error: state is not available
    - host: https://bsc-dataseed4.bnbchain.org error: missing trie node
    - host: https://binance.nodereal.io error: missing trie node
    - host: https://bsc-dataseed2.ninicoin.io error: missing trie node
    PromisePoolError: Llama RPC error! methos: undefined 
    - host: https://bsc-dataseed.binance.org error: missing trie node
    - host: https://bsc-rpc.publicnode.com error: missing trie node 484f3e3b0d02e387d84a6feba9b9c5e32534ee256b8bdac69f8f8b0abe0518b6 (path ) state 0x484f3e3b0d02e387d84a6feba9b9c5e32534ee256b8bdac69f8f8b0abe0518b6 is not available
    - host: https://bsc-dataseed.bnbchain.org error: missing trie node
    - host: https://bsc-dataseed1.defibit.io error: missing trie node
    - host: https://bsc-dataseed3.defibit.io error: missing trie node
    - host: https://bsc-dataseed4.defibit.io error: missing trie node
    - host: https://binance.nodereal.io error: missing trie node
    PromisePoolError: Llama RPC error! methos: undefined 
    - host: https://bsc-dataseed.binance.org error: missing trie node
    - host: https://bsc-dataseed4.defibit.io error: missing trie node
    - host: https://binance.nodereal.io error: missing trie node
    - host: https://bsc-mainnet.public.blastapi.io error: missing trie node 484f3e3b0d02e387d84a6feba9b9c5e32534ee256b8bdac69f8f8b0abe0518b6 (path ) state 0x484f3e3b0d02e387d84a6feba9b9c5e32534ee256b8bdac69f8f8b0abe0518b6 is not available
    - host: https://1rpc.io/bnb error: missing trie node 484f3e3b0d02e387d84a6feba9b9c5e32534ee256b8bdac69f8f8b0abe0518b6 (path ) state 0x484f3e3b0d02e387d84a6feba9b9c5e32534ee256b8bdac69f8f8b0abe0518b6 is not available
    - host: https://bsc-rpc.publicnode.com error: missing trie node 484f3e3b0d02e387d84a6feba9b9c5e32534ee256b8bdac69f8f8b0abe0518b6 (path ) state 0x484f3e3b0d02e387d84a6feba9b9c5e32534ee256b8bdac69f8f8b0abe0518b6 is not available
    - host: https://bsc-dataseed3.defibit.io error: missing trie node] {
      _isCustomError: true,
      chain: 'bsc'
    }

**Comment by llamatester** [comment]
The forge.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees forge.ts
    
    🦙 Running FORGE.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 13 Oct 2024 14:24:28 GMT
    End Date:	Mon, 14 Oct 2024 14:24:28 GMT
    ---------------------------------------------------
    
    [Error: Promise pool failed! 
     PromisePoolError: Llama RPC error! methos: undefined 
    - host: https://evmos-evm.publicnode.com error: rpc error: code = Unknown desc = codespace sdk code 18: invalid request: failed to load state at height 24152935; version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height (latest height: 24155257)
    - host: https://evmos-mainnet.public.blastapi.io error: rpc error: code = Internal desc = out of gas
    - host: https://evmos-json-rpc.stakely.io error: rpc error: code = Internal desc = out of gas
    - host: https://evmos.lava.build error: rpc error: code = Internal desc = out of gas
    - host: https://evmos-evm-rpc.publicnode.com error: rpc error: code = Unknown desc = codespace sdk code 18: invalid request: failed to load state at height 24152935; version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height (latest height: 24155257)
    - host: https://evmos-pokt.nodies.app error: Request failed with status code 403
    - host: https://evm-rpc.evmos.silentvalidator.com error: rpc error: code = Internal desc = out of gas] {
      _isCustomError: true,
      chain: 'evmos'
    }

**Comment by waynebruce0x** [comment]
tangle and forge are still wip but they were broken anyway so

**Pull request merged**
