### PR TITLE
update jojo volume

### PR DESCRIPTION
**Pull request by JoscelynFarr**

### CODE REVIEW

**Comment by llamatester** [comment]
The jojo adapter exports: 
        
 
 _______________________________________
    Dexs for 21/4/2024
    _______________________________________
    
    7834595.164991921
    BASE 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 24.83 M
    Daily volume: 7.83 M
    Timestamp: 1713657600 (2024-04-21T00:00:00.000Z)
    
    
    
    
    Done in 4.19s.

**Comment by dtmkeng** [comment]
could you explain why remove arb ?

**Comment by llamatester** [comment]
The jojo adapter exports: 
        
 
 _______________________________________
    Dexs for 29/4/2024
    _______________________________________
    
    40108265.45822937
    BASE 👇
    Backfill start time: 1/4/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 210.85 M
    Daily volume: 40.11 M
    Timestamp: 1714348800 (2024-04-29T00:00:00.000Z)

**Comment by JoscelynFarr** [comment]
we do not support arb chain

**Pull request merged**
