### PR TITLE
Orca Volume and Fees Update

### PR DESCRIPTION
**Pull request by mcastrogg**
Hello, updated the dimensions adapter to include fees and protocol fees and volume all from Orca's new endpoint.

### CODE REVIEW

**Comment by dtmkeng** [comment]
could you resolve conflicts ?

**Comment by llamatester** [comment]
The orca adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs orca
    
    🦙 Running ORCA adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 12 Nov 2024 00:00:00 GMT
    End Date:	Wed, 13 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    SOLANA 👇
    Backfill start time: 14/9/2022
    NO METHODOLOGY SPECIFIED
    Daily volume: 1.11 B
    Daily fees: 1.16 M
    Daily revenue: 97.25 k
    End timestamp: 1731455999 (2024-11-12T23:59:59.000Z)

**Comment by mcastrogg** [comment]
Fixed the conflict. Just one wanted to bring one thing to your attention regarding the DailyFees. I have the dailyFees value being LP fees generated + protocol fees generated. Was unsure if it should be only LP fees or both. There is an extra function in their I can remove, but I was not sure which value to use. Let me know so I can fix

**Comment by mcastrogg** [comment]
> The orca adapter exports:
> 
> ```
> > adapters@1.0.0 test
> > ts-node --transpile-only cli/testAdapter.ts dexs orca
> 
> 🦙 Running ORCA adapter 🦙
> ---------------------------------------------------
> Start Date:	Tue, 12 Nov 2024 00:00:00 GMT
> End Date:	Wed, 13 Nov 2024 00:00:00 GMT
> ---------------------------------------------------
> 
> SOLANA 👇
> Backfill start time: 14/9/2022
> NO METHODOLOGY SPECIFIED
> Daily volume: 1.11 B
> Daily fees: 1.16 M
> Daily revenue: 97.25 k
> End timestamp: 1731455999 (2024-11-12T23:59:59.000Z)
> ```

Yes, this looks about right. 

Here is a dune query: 
https://dune.com/queries/4280823/7194473

In the last 24hr rolling window seems possible as we've done 918k yesterday, and 511k today so far

**Comment by llamatester** [comment]
The orca adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs orca
    
    🦙 Running ORCA adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 12 Nov 2024 00:00:00 GMT
    End Date:	Wed, 13 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    SOLANA 👇
    Backfill start time: 14/9/2022
    NO METHODOLOGY SPECIFIED
    Daily volume: 1.14 B
    Daily fees: 1.16 M
    Daily revenue: 95.70 k
    End timestamp: 1731455999 (2024-11-12T23:59:59.000Z)
    
    
    ECLIPSE 👇
    Backfill start time: 14/9/2022
    NO METHODOLOGY SPECIFIED
    Daily volume: 894.33 k
    Daily fees: 1.65 k
    Daily revenue: 123
    End timestamp: 1731455999 (2024-11-12T23:59:59.000Z)

**Comment by mcastrogg** [comment]
Side note, I also added the eclipse network, as we just launched on there and I had forgot to add it

**Pull request merged**
