### PR TITLE
add fee and revenue infos for Avax and Manta

### PR DESCRIPTION
**Pull request by pullstacker**
add fee and revenue infos for Avax and Manta

### CODE REVIEW

**Comment by llamatester** [comment]
The monocerus adapter exports: 
        
 
 _______________________________________
    Dexs for 10/1/2024
    _______________________________________
    
    MANTA 👇
    Backfill start time: 9/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704931198
    Block: 1.07 M
    Total volume: 0
    Daily volume: 0
    Daily fees: 0
    Total fees: 0
    Daily protocol revenue: 0
    Daily holders revenue: 0
    Daily user fees: 0
    Daily supply side revenue: 0
    Daily revenue: 0
    
    
    
    
    Done in 3.42s.

**Comment by pullstacker** [comment]
hi do you support goldsky? because we use this https://api.goldsky.com/api/public/project_clpm9wvhralny01szb1oa4pue/subgraphs/monocerus/1.2.0/gn for manta, but the export still 0

**Comment by llamatester** [comment]
The monocerus adapter exports: 
        
 
 _______________________________________
    Dexs for 10/1/2024
    _______________________________________
    
    Failed to get daily volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Attempting with alternative query...
    Failed to get alternative daily volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Failed to get total volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Unable to get daily fees on avax from graph.
    Unable to get total fees on avax from graph.
    AVAX 👇
    Backfill start time: 31/12/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704931198
    Block: 40.20 M
    Total volume: NaN
    Daily volume: NaN
    Daily fees: NaN
    Total fees: NaN
    
    
    MANTA 👇
    Backfill start time: 9/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704931198
    Block: 1.07 M
    Total volume: 0
    Daily volume: 0
    Daily fees: 0
    Total fees: 0
    Daily protocol revenue: 0
    Daily holders revenue: 0
    Daily user fees: 0
    Daily supply side revenue: 0
    Daily revenue: 0
    
    
    
    
    Done in 5.20s.

**Comment by llamatester** [comment]
The monocerus adapter exports: 
        
 
 _______________________________________
    Dexs for 10/1/2024
    _______________________________________
    
    Failed to get daily volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Attempting with alternative query...
    Failed to get alternative daily volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Failed to get total volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Unable to get daily fees on avax from graph.
    Unable to get total fees on avax from graph.
    AVAX 👇
    Backfill start time: 31/12/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704931198
    Block: 40.20 M
    Total volume: NaN
    Daily volume: NaN
    Daily fees: NaN
    Total fees: NaN
    
    
    MANTA 👇
    Backfill start time: 9/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704931198
    Block: 1.07 M
    Total volume: 0
    Daily volume: 0
    Daily fees: 0
    Total fees: 0
    Daily protocol revenue: 0
    Daily holders revenue: 0
    Daily user fees: 0
    Daily supply side revenue: 0
    Daily revenue: 0
    
    
    
    
    Done in 4.82s.

**Comment by llamatester** [comment]
The monocerus adapter exports: 
        
 
 _______________________________________
    Dexs for 10/1/2024
    _______________________________________
    
    Failed to get daily volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Attempting with alternative query...
    Failed to get alternative daily volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Failed to get total volume on avax with graph https://thegraph.com/hosted-service/subgraph/monocerusworld/v3-avax: Unexpected token < in JSON at position 0
    Unable to get daily fees on avax from graph.
    Unable to get total fees on avax from graph.
    AVAX 👇
    Backfill start time: 31/12/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704931198
    Block: 40.20 M
    Total volume: NaN
    Daily volume: NaN
    Daily fees: NaN
    Total fees: NaN
    
    
    MANTA 👇
    Backfill start time: 9/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704931198
    Block: 1.07 M
    Total volume: 0.003212636070204903
    Daily volume: 0.0004748716496693521
    Daily fees: 0.000001385040803000677
    Total fees: 0.000010663376610546398
    Daily protocol revenue: 0
    Total protocol revenue: 0
    Daily holders revenue: 0
    Total holders revenue: 0
    Daily user fees: 0.000001385040803000677
    Total user fees: 0.000010663376610546398
    Daily supply side revenue: 0.000001385040803000677
    Total supply side revenue: 0.000010663376610546398
    Daily revenue: 0
    Total revenue: 0
    
    
    
    
    Done in 5.34s.

**Comment by llamatester** [comment]
The monocerus adapter exports: 
        
 
 _______________________________________
    Dexs for 10/1/2024
    _______________________________________
    
    MANTA 👇
    Backfill start time: 9/1/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1704931198
    Block: 1.07 M
    Total volume: 0.003212636070204903
    Daily volume: 0.0004748716496693521
    Daily fees: 0.000001385040803000677
    Total fees: 0.000010663376610546398
    Daily protocol revenue: 0
    Total protocol revenue: 0
    Daily holders revenue: 0
    Total holders revenue: 0
    Daily user fees: 0.000001385040803000677
    Total user fees: 0.000010663376610546398
    Daily supply side revenue: 0.000001385040803000677
    Total supply side revenue: 0.000010663376610546398
    Daily revenue: 0
    Total revenue: 0
    
    
    
    
    Done in 3.62s.

**Comment by pullstacker** [comment]
hi there, the numbers are shown now, kindly help to merge, thanks

**Pull request merged**
