### PR TITLE
add jojo volume

### PR DESCRIPTION
**Pull request by KittyFu307**
NOTE

Name (to be shown on DefiLlama):
JOJO

Twitter Link:
https://twitter.com/jojo_exchange

List of audit links if any:
https://github.com/JOJOexchange/smart-contract-EVM/tree/main/audits

Website Link:
https://app.jojo.exchange/trade

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
logo01

Current 24 Volume:
2170.29588

Chain:
BSC

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
have not issue the token

Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
have not issue the token

Short Description (to be shown on DefiLlama):
JOJO is a decentralized perpetual contract exchange based on an off-chain matching system.

Token address and ticker if any:
Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
Chainlink

forkedFrom (Does your project originate from another project):
no

methodology (what is being counted as tvl, how is tvl being calculated):
24 volume

### CODE REVIEW

**Comment by 0xtawa** [comment]
Hi, looks like you copied the helper function from `getUniSubgraphVolume.ts` to your adapter, any reason behind it?

**Comment by KittyFu307** [comment]
> Hi, looks like you copied the helper function from `getUniSubgraphVolume.ts` to your adapter instead of just importing it, any reason behind it?

Sure, because the totalVolume query sql have a little different, this is our project's query totalVolume sql
截屏2022-12-01 下午10 52 43
and this one is from the helper function:
截屏2022-12-01 下午10 55 32
in the help function I need to parse an param

**Comment by llamatester** [comment]
The jojo adapter exports: 
        
 
 _______________________________________
    Dexs for 30/11/2022
    _______________________________________
    
    Unable to get daily fees on bsc from graph.
    Unable to get total fees on bsc from graph.
    BSC 👇
    Backfill start time: 13/9/1970
    NO METHODOLOGY SPECIFIED
    Timestamp: 1669852798
    Block: 23516085
    Total volume: 498331.536372424
    Daily volume: 38267.884892
    Daily fees: undefined
    Total fees: undefined
    
    
    
    
    Done in 4.37s.

**Comment by 0xtawa** [comment]
Hi, simplified a bit the adapter for better future maintenance, please check if the output is correct and if so please:
1. Check the current start timestamp, the current one looks too far away in time. Should be specified in seconds.
2. Set fees and methodology parameters so it can be also included in the fees&revenue dashboard. To specify the fees please take a look at this [readme](https://github.com/DefiLlama/dimension-adapters/blob/master/README.md) and the examples in this [folder](https://github.com/DefiLlama/dimension-adapters/tree/master/protocols).

For testing please run `yarn` to install the updated dependencies and run with `yarn test dexs jojo`

Feel free to ping me here or on Discord if you have any question-

**Comment by KittyFu307** [comment]
> Backfill start time

Sure, I have already changed the current start timestamp and I will push it asap. 
But for the second one of the fee. I am afraid of I can not use the subgraph to monitor the event. Because there are no related fee events in our current contract.  Users can only find the fee by called contract's view function.

**Comment by dtmkeng** [comment]
@KittyFu307 could you delete file .bak ?

**Comment by KittyFu307** [comment]
> @KittyFu307 could you delete file .bak ?

截屏2022-12-05 下午11 33 16
I did not delete it. it is still in the branches

**Comment by 0xsalah** [comment]
@dtmkeng I kept the bak there and commited it by mistake, will merge and delete myself. ty

**Comment by llamatester** [comment]
The jojo adapter exports: 
        
 
 _______________________________________
    Dexs for 4/12/2022
    _______________________________________
    
    Attempting with alternative query...
    Unable to get daily fees on bsc from graph.
    Unable to get total fees on bsc from graph.
    BSC 👇
    Backfill start time: 1/11/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1670198398
    Block: 23628825
    Total volume: 500172.1317558855
    Daily volume: 0
    Daily fees: undefined
    Total fees: undefined
    
    
    
    
    Done in 4.47s.

**Comment by 0xtawa** [comment]
@dtmkeng Commited it by mistake will delete it

**Comment by llamatester** [comment]
The jojo adapter exports: 
        
 
 _______________________________________
    Dexs for 4/12/2022
    _______________________________________
    
    Attempting with alternative query...
    Unable to get daily fees on bsc from graph.
    Unable to get total fees on bsc from graph.
    BSC 👇
    Backfill start time: 1/11/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1670198398
    Block: 23628825
    Total volume: 500172.1317558855
    Daily volume: 0
    Daily fees: undefined
    Total fees: undefined
    
    
    
    
    Done in 5.54s.

**Comment by KittyFu307** [comment]
hi @0xtawa want to know after the pull request merged, When can the volume be found in the dashboard

**Pull request merged**
