### PR TITLE
Add demented-games to fees dashboard

### PR DESCRIPTION
**Pull request by dementedgames**
**NOTE**

#### Please enable "Allow edits by maintainers" while putting up the PR.

- If you would like to add a `volume` adapter please submit the PR [here](https://github.com/DefiLlama/adapters).
- If you would like to add a `liquidations` adapter, please refer to [this readme document](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/liquidations) for details.

1.  Once your adapter has been merged, it takes time to show on the UI. If more than 24 hours have passed, please let us know in Discord.
2.  Sorry, We no longer accept fetch adapter for new projects, we prefer the tvl to computed from blockchain data, if you have trouble with creating a the adapter, please hop onto our discord, we are happy to assist you.
3.  Please fill the form below **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
4.  **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can edit it there and put up a PR
5.  Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
6.  No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---

##### Name (to be shown on DefiLlama):

Demented Games

##### Twitter Link:

https://twitter.com/Playdemented

##### Website Link:

https://demented.games/

##### Logo (High resolution, will be shown with rounded borders):

logo (1)

##### Chain:

Fuse

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):

https://api.coingecko.com/api/v3/coins/list

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):

https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000

##### Short Description (to be shown on DefiLlama):

Demented games is the first easy to play and degen focused community game on Fuse network.

Join the craziest game of all times were a strike of luck can change your life!

Demented team has vast experience at building complex infrastructure and well known protocols focused on DeFi, but now its time to level up and bring the crypto community a fun to play game.

##### Category (full list at https://defillama.com/categories) \*Please choose only one:

[Gaming](https://defillama.com/protocols/Gaming)

### CODE REVIEW

**Comment by llamatester** [comment]
The demented-games adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees demented-games
    
    🦙 Running DEMENTED-GAMES adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 12 Aug 2024 15:02:49 GMT
    End Date:	Tue, 13 Aug 2024 15:02:49 GMT
    ---------------------------------------------------
    
    FUSE 👇
    Backfill start time: 8/7/2024
    Total fees: 120
    └─ Methodology: Sum of all fees from each game on the Demented Games platform.
    End timestamp: 1723561368 (2024-08-13T15:02:48.000Z)

**Comment by dtmkeng** [comment]
could you add `dailyFees` ?

**Comment by dementedgames** [comment]
We don't have that functionality yet; could we add it later?

**Comment by dtmkeng** [comment]
adapter require daily value show at chart

**Comment by llamatester** [comment]
The demented-games adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees demented-games
    
    🦙 Running DEMENTED-GAMES adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 13 Aug 2024 17:27:55 GMT
    End Date:	Wed, 14 Aug 2024 17:27:55 GMT
    ---------------------------------------------------
    
    FUSE 👇
    Backfill start time: 8/7/2024
    Total fees: 120
    └─ Methodology: Sum of all fees from each game on the Demented Games platform.
    Daily fees: 6
    └─ Methodology: Sum of all fees from each game on the Demented Games platform.
    End timestamp: 1723656474 (2024-08-14T17:27:54.000Z)

**Pull request merged**
