### PR TITLE
add fees predy

### PR DESCRIPTION
**Pull request by wshino**

### CODE REVIEW

**Comment by llamatester** [comment]
The predy adapter exports: 
        
 
 _______________________________________
    Fees for 15/1/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 15/12/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1673827198
    Daily fees: 192.34294573707664955402
    Daily revenue: 0
    
    
    
    
    Done in 5.75s.

**Comment by wshino** [comment]
The output In my local is

```
% yarn test fees predy
yarn run v1.22.19
$ yarn run update-submodules && ts-node cli/testAdapter.ts fees predy
$ git submodule update --init --recursive --remote --merge
🦙 Running PREDY adapter 🦙
_______________________________________
Fees for 15/1/2023
_______________________________________

ARBITRUM 👇
Backfill start time: 15/12/2022
NO METHODOLOGY SPECIFIED
Timestamp: 1673827198
Daily fees: 86.86013513668433498071
Daily revenue: 1.32711433095011694861
```

What is the difference between this and above comment?
I would like to display my local output on your site.

**Comment by llamatester** [comment]
The predy adapter exports: 
        
 
 _______________________________________
    Fees for 15/1/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 15/12/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1673827198
    Daily fees: 192.34294573707664955402
    Daily revenue: 3.74505671376854949516
    
    
    
    
    Done in 5.30s.

**Comment by wshino** [comment]
I see it's related to a local time issue. understood.

**Pull request merged**
