### PR TITLE
Add JasperVault Options Fee Adapter

### PR DESCRIPTION
**Pull request by gaawai-l**
This PR updates the JasperVault Options Fee Adapter to calculate NotionalVolume and PremiumVolume using order data from our Subgraph. Tests have been successfully run with `yarn test options jaspervault`. 

Feedback and reviews are greatly appreciated.

### CODE REVIEW

**Comment by llamatester** [comment]
The jaspervault adapter exports: 
        
 
 _______________________________________
    Options for 17/5/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 8/5/2024
    NO METHODOLOGY SPECIFIED
    Daily notional volume: 1.13 M
    Daily premium volume: 3.03 k
    Total notional volume: 14.77 M
    Total premium volume: 67.22 k
    Timestamp: 1715934884 (2024-05-17T08:34:44.000Z)

**Comment by gaawai-l** [comment]
Name (to be shown on DefiLlama):Jasper Vault
Twitter Link:https://x.com/jaspervault
List of audit links if any:https://docs.jaspervault.io/security/audit-reports
Website Link:https://www.jaspervault.io
Logo (High resolution, will be shown with rounded borders):
https://www.jaspervault.io/images/logo_400x400.png
Current TVL:
Treasury Addresses (if the protocol has treasury)
Chain:Arbitrum 
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):  
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):  
Short Description (to be shown on DefiLlama):

Jasper Vault is a peer-to-peer interoperable options protocol. Jasper Vault’s mission is to revolutionize the decentralised finance (DeFi) options space by making it simpler, safer, and more efficient than ever before.

With the protocol’s innovative application of Account Abstraction (AA) technology on Ethereum and Solana, and Hash Time-Lock Contract (HTLC) on the Bitcoin network, the protocol truly enables peer-to-peer trading and interoperability between wallets on different chains. This groundbreaking solution not only eliminates the problem of counterparty risk but also improves liquidity and accessibility across multiple blockchain networks like never before.

Jasper Vault’s current product suite includes the buying of American call options on major pairs such as USDT-ETH and USDC-WBTC, with options for physical delivery or net settlement—giving traders unprecedented flexibility.

Token address and ticker if any:
Category (full list at https://defillama.com/categories) Dexes
Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):Pyth
Implementation Details: Briefly describe how the oracle is integrated into your project:

In our project, the integration of the oracle, specifically Pyth, happens at the exercise stage. Users match premium prices amongst themselves. When it comes to exercising the options, we use Pyth's price data. Pyth, as a powerful oracle, provides high-fidelity, real-time market data that ensures the options are exercised at a fair and accurate market price. This integration not only increases the reliability and trustworthiness of our project but also enhances the overall user experience by ensuring fair transactions.

Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://arbiscan.io/tx/0x4a0b701420efffde5e3ec8a1cb9c1da567cb7b00e710767636981c4d900a4b34

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Comment by gaawai-l** [comment]
We are currently focusing on peer-to-peer options trading. As we don't have a pool yet, the concept of TVL doesn't exist for us at the moment. We anticipate integrating pear-to- pool trading next month, at which point we'll have TVL.

**Comment by dtmkeng** [comment]
can't list option volume without tvl

**Comment by gaawai-l** [comment]
Currently, we are the sellers in our options trading. In the future, there will be a pool acting as the option seller. Can we consider this seller vault for selling options as a target for TVL ?

**Comment by gaawai-l** [comment]
Hi,

I've already added a TVL adapter.

https://github.com/DefiLlama/DefiLlama-Adapters/pull/10270

**Comment by g1nt0ki** [comment]
@gaawai-l thanks for the PR, but pyth dependency is not really needed, I have refactored that part here: https://github.com/DefiLlama/dimension-adapters/pull/1494

I still think the code can be tweaked a bit more, maybe we can skip the total prem/notional volume field code? because it is too many calls to the graph and only increases over time?

Also, can you share the log event for all these? this way if the graph is unreachable, we will be able to compute volume using that

**Comment by gaawai-l** [comment]
Thank you for your feedback on the PR. In regard to your suggestion of possibly skipping the total prem/notional volume field code, I have a question: Is DefiLlama calculating the total prem/notional on a daily basis? If so, I agree that we can skip it. Initially, I initially thought that computing and submitting the total prem/notional was necessary.

**Comment by gaawai-l** [comment]
for sharing the log event, I am unsure about the best way to do this.  I have uploaded the subgraph code to our repo https://github.com/jaspervault/subgraphs.   

AddCallOrder & AddPutOrder are used to calculate the notional volume.
name: Diamond
    network: arbitrum-one
    source:
      address: "0x5FfDD96bD604f915520d66C9edDd46dFc1434d71"
      abi: Diamond
      startBlock: 200200000
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - CallOrder
        - PutOrder
      abis:
        - name: Diamond
          file: ./abis/DiamondABI.json
      eventHandlers:
        - event: AddCallOrder(uint64,(address,uint8,address,uint8,address,address,address,uint256,uint256,uint256,uint256),address,address)
          handler: handleAddCallOrder
        - event: AddPutOrder(uint64,(address,uint8,address,uint8,address,address,address,uint256,uint256,uint256,uint256),address,address)
          handler: handleAddPutOrder  


The OptionPremium event is used to calculate the premium volume:

name: OptionModule
    network: arbitrum-one
    source:
      address: "0x835d6Fe77fa1437f951F6F95b2B7524Aa0B8c2e6"
      abi: OptionModule
      startBlock: 208965858
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - CallOrder
      abis:
        - name: OptionModule
          file: ./abis/OptionModule.json 
      eventHandlers:
        - event: OptionPremiun(uint8,uint64,address,address,address,uint256)
          handler: handleOptionPremiun

**Comment by g1nt0ki** [comment]
thanks

**Pull request merged**
