### PR TITLE
SynFutures V3 Fees

### PR DESCRIPTION
**Pull request by fan3cn**
Fee = LiquidityFee + ProtocolFee
LiquidityFee = MakerRebates + FeesToLP

```typescript
const methodology = {
  TotalFees: "total fees paid by takers on the protocol by using market orders, these fees paid goes to limit order makers, AMM LP and protocol fees",
  TotalMakerRebates: "total fees rebated received by limit order makers on the protocol, these fees are paid by takers",
  TotalFeesToLp: "total fees received by AMM LPs on the protocol, these fees are paid by takers",
  TotalProcotolFees: "total fees received by the protocol from takers, these fees are paid by takers"
}
```

### CODE REVIEW

**Comment by llamatester** [comment]
The synfutures-v3 adapter exports: 
        
 
 _______________________________________
    Fees for 23/4/2024
    _______________________________________
    
    BLAST 👇
    Backfill start time: 27/2/2024
    Daily fees: 299.39 k
    Daily maker rebates: 84.17 k
    Daily fees to lp: 18.97 k
    Daily procotol fees: 196.25 k
    Total fees: 9.52 M
    Total maker rebates: 2.39 M
    Total fees to lp: 1.09 M
    Total procotol fees: 6.04 M
    Timestamp: 1713835943 (2024-04-23T01:32:23.000Z)
    
    
    
    
    Done in 10.93s.

**Comment by llamatester** [comment]
The synfutures-v3 adapter exports: 
        
 
 _______________________________________
    Fees for 23/4/2024
    _______________________________________
    
    BLAST 👇
    Backfill start time: 27/2/2024
    Daily fees: 300.01 k
    └─ Methodology: fees paid by takers on the protocol by using market orders, these fees paid goes to limit order makers, AMM LP and protocol fees
    Daily maker rebates: 84.36 k
    └─ Methodology: fees rebated received by limit order makers on the protocol, these fees are paid by takers
    Daily fees to lp: 18.98 k
    └─ Methodology: fees received by AMM LPs on the protocol, these fees are paid by takers
    Daily procotol fees: 196.67 k
    └─ Methodology: fees received by the protocol from takers, these fees are paid by takers
    Total fees: 9.54 M
    └─ Methodology: fees paid by takers on the protocol by using market orders, these fees paid goes to limit order makers, AMM LP and protocol fees
    Total maker rebates: 2.39 M
    └─ Methodology: fees rebated received by limit order makers on the protocol, these fees are paid by takers
    Total fees to lp: 1.09 M
    └─ Methodology: fees received by AMM LPs on the protocol, these fees are paid by takers
    Total procotol fees: 6.06 M
    └─ Methodology: fees received by the protocol from takers, these fees are paid by takers
    Timestamp: 1713836739 (2024-04-23T01:45:39.000Z)
    
    
    
    
    Done in 5.91s.

**Comment by dtmkeng** [comment]
do you example on chain txs for cal ` ProtocolFee, MakerRebates , FeesToLP` ?

**Comment by fan3cn** [comment]
> do you example on chain txs for cal ` ProtocolFee, MakerRebates , FeesToLP` ?

Hi, in our contract, there is an event designed to record market trades made by users:

```
event Trade(
    uint32 indexed expiry, address indexed trader, int size, uint amount, int takenSize, uint takenValue,
    uint entryNotional, uint16 feeRatio, uint160 sqrtPX96, uint mark);
```

In this event: `entryNotional` represents the total volume; `takenSize` represents the volume contributed by limit orders; `feeRatio` indicates the fee rate of this trade (note: in our system the fee rate for trades is not fixed). Therefore, `entryNotional * feeRatio` is the fee allocated to the limit order and LP.
Additionally, there is a `protocolFee`, which is not reflected in this event. This is because `protocolFeeRatio` is fixed for each trading pair, so it does not need to be included in this event to avoid redundancy.

To summarize:

`MakerRebates = takenValue * feeRatio`
`FeesToLP = (entryNotional - takenValue) * feeRatio`
`ProtocolFee = entryNotional * protocolFeeRatio`

Here are a few transaction links for reference. You can use the above event to parse them and verify:
https://blastscan.io/tx/0x6a847591475ce1d2ece3368d553f65b57d5542ef8766ecdd0b9ef42d5b3e8e19
https://blastscan.io/tx/0x05cad1ee054df11361189200c206c62b126657946420e0d1b8860679bddf5378

Below are the codes for parsing tx 0x05cad1ee054df11361189200c206c62b126657946420e0d1b8860679bddf5378:

```typescript
import { ethers } from 'ethers';

async function parseEvent(): Promise<void> {
    const provider = new ethers.providers.JsonRpcProvider('https://rpc.ankr.com/blast');
    const receipt = await provider.getTransactionReceipt(
        '0x05cad1ee054df11361189200c206c62b126657946420e0d1b8860679bddf5378',
    );
    const iface = new ethers.utils.Interface([
        `event Trade(
          uint32 indexed expiry, address indexed trader, int size, uint amount, int takenSize, uint takenValue,
          uint entryNotional, uint16 feeRatio, uint160 sqrtPX96, uint mark)`,
    ]);
    for (const log of receipt.logs) {
        try {
            const event = iface.parseLog(log);
            console.info(event.name);
            console.info('instrument:', log.address);
            console.info('trader:', event.args.trader);
            console.info('size:', ethers.utils.formatEther(event.args.size));
            console.info('takenValue:', ethers.utils.formatEther(event.args.takenValue));
            console.info('entryNotional:', ethers.utils.formatEther(event.args.entryNotional));
            console.info('feeRatio:', Number(event.args.feeRatio) / 1e4);
        } catch (e) {
            // no matching event, do nothing
        }
    }
}
parseEvent().catch(console.error);
```
The result is:  

```
Trade
instrument: 0xeb9e8822142Fc10C38FaAB7bB6c635D22eb20Ff8
trader: 0x53fA150E5974E1D9700a610E348D001eCF6f01eA
size: 3716.204103995768162849
takenValue: 0.0
entryNotional: 1.093549978781389437
feeRatio: 0.0001
```
 instrument 0xeb9e8822142Fc10C38FaAB7bB6c635D22eb20Ff8 is USDB-WETH-PYTH, its `protocolFeeRatio` is 0.0002.
Therefore, the fee calculation for this trade is：

`MakerRebates = 0 * 0.0001`
`FeesToLP = (1.093549978781389437 - 0) * 0.0001 =  0.00010935499787813895 (WETH)`
`ProtocolFee = 1.093549978781389437 * 0.0002 = 0.0002187099957562779 (WETH)`

Hope this explanation addresses your concerns. Thanks.

**Pull request merged**
