### PR TITLE
add nftearth fees

### PR DESCRIPTION
**Pull request by westonnelson**
Adding NFTEarth NFT Marketplace to DeFiLlama Fees dashboard!

NFTEarth protocol information:

[Website](https://nftearth.exchange) 
[Twitter](https://twitter.com/NFTEarth_L2)
[Discord](https://discord.gg/nftearth)
[GitHub](https://github.com/NFTEarth)

### CODE REVIEW

**Comment by llamatester** [comment]
The nftearth.ts adapter exports: 
        
 
 _______________________________________
    Fees for 15/2/2023
    _______________________________________
    
    OPTIMISM 👇
    Backfill start time: 3/2/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 2.9893020820640425e+34
    Daily revenue: 1.881676913974009e-9
    Timestamp: 1676505598
    
    
    ARBITRUM 👇
    Backfill start time: 3/2/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 2.4425719130989125e+33
    Daily revenue: 2.847723587672241e-12
    Timestamp: 1676505598
    
    
    
    
    Done in 15.89s.

**Comment by 0xngmi** [comment]
> Daily fees: 2.9893020820640425e+34

this is clearly wrong

**Comment by westonnelson** [comment]
@0xngmi agreed... but used the exact code from Llama for it? 

Here is NFTScan data - this appears accurate to me.

image


What else could I do to help?

**Comment by dtmkeng** [comment]
thank  you for this pr,  iI have update something https://github.com/DefiLlama/dimension-adapters/pull/255

**Pull request merged**
