### PR TITLE
added vela fees and volume

### PR DESCRIPTION
**Pull request by zodiacasti**

### CODE REVIEW

**Comment by llamatester** [comment]
The vela adapter exports: 
        
 
 _______________________________________
    Fees for 29/3/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 1/9/2021
    Timestamp: 1680134398
    Daily fees: 29508.787473752
    └─ Methodology: Fees collected from user trading fees
    Trade volume: 62381215.879337125
    Trade counts: 10309
    
    
    
    
    Done in 4.44s.

**Comment by zodiacasti** [comment]
> The vela adapter exports:
> 
> ```
> Fees for 29/3/2023
> _______________________________________
> 
> ARBITRUM 👇
> Backfill start time: 1/9/2021
> Timestamp: 1680134398
> Daily fees: 29508.787473752
> └─ Methodology: Fees collected from user trading fees
> Trade volume: 62381215.879337125
> Trade counts: 10309
> 
> 
> 
> 
> Done in 4.44s.
> ```

Does this mean everything is okay, or I need to change something?

**Comment by dtmkeng** [comment]
hi, if you want to add fees/ trade volume, you should split two files for fees under folder `fees`
and trade volume under `dexs` folder metric 
interface for fees
```
  timestamp: number;
  totalFees?: string | IJSON<string>;
  dailyFees?: string | IJSON<string>;
  dailyUserFees?: string | IJSON<string>;
  totalRevenue?: string | IJSON<string>;
  dailyRevenue?: string | IJSON<string>;
  dailyProtocolRevenue?: string | IJSON<string>;
  dailyHoldersRevenue?: string | IJSON<string>;
  dailySupplySideRevenue?: string | IJSON<string>;
  totalProtocolRevenue?: string | IJSON<string>;
  totalSupplySideRevenue?: string | IJSON<string>;
  totalUserFees?: string | IJSON<string>;
```
dexs adapter interface 
```
  timestamp: number;
  dailyVolume?: string // | IJSON<string>;
  totalVolume?: string // | IJSON<string>;
```

**Comment by llamatester** [comment]
The vela adapter exports: 
        
 
 _______________________________________
    Fees for 30/3/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 1/9/2021
    Timestamp: 1680220798
    Daily fees: 42598.73566604867
    └─ Methodology: Daily fees collected from user trading fees
    
    
    
    
    Done in 4.13s.

**Comment by zodiacasti** [comment]
> hi, if you want to add fees/ trade volume, you should split two files for fees under folder `fees` and trade volume under `dexs` folder metric interface for fees
> 
> ```
>   timestamp: number;
>   totalFees?: string | IJSON<string>;
>   dailyFees?: string | IJSON<string>;
>   dailyUserFees?: string | IJSON<string>;
>   totalRevenue?: string | IJSON<string>;
>   dailyRevenue?: string | IJSON<string>;
>   dailyProtocolRevenue?: string | IJSON<string>;
>   dailyHoldersRevenue?: string | IJSON<string>;
>   dailySupplySideRevenue?: string | IJSON<string>;
>   totalProtocolRevenue?: string | IJSON<string>;
>   totalSupplySideRevenue?: string | IJSON<string>;
>   totalUserFees?: string | IJSON<string>;
> ```
> 
> dexs adapter interface
> 
> ```
>   timestamp: number;
>   dailyVolume?: string // | IJSON<string>;
>   totalVolume?: string // | IJSON<string>;
> ```

Hello, I just pushed another commit, just for fees. Can you approve please?

**Pull request merged**
