### PR TITLE
feat: Raindex vol adapter

### PR DESCRIPTION
**Pull request by rouzwelt**
Raindex dailyVolume

### CODE REVIEW

**Comment by llamatester** [comment]
The raindex adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs raindex
    
    🦙 Running RAINDEX adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 08 Oct 2024 12:43:22 GMT
    End Date:	Wed, 09 Oct 2024 12:43:22 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 23/9/2024
    Daily volume: 92
    └─ Methodology: Volume of trades
    End timestamp: 1728477801 (2024-10-09T12:43:21.000Z)
    
    
    BASE 👇
    Backfill start time: 28/8/2024
    Daily volume: 659
    └─ Methodology: Volume of trades
    End timestamp: 1728477801 (2024-10-09T12:43:21.000Z)
    
    
    BSC 👇
    Backfill start time: 23/9/2024
    Daily volume: 350
    └─ Methodology: Volume of trades
    End timestamp: 1728477801 (2024-10-09T12:43:21.000Z)
    
    
    FLARE 👇
    Backfill start time: 4/9/2024
    Daily volume: 159
    └─ Methodology: Volume of trades
    End timestamp: 1728477801 (2024-10-09T12:43:21.000Z)
    
    
    LINEA 👇
    Backfill start time: 30/9/2024
    Daily volume: 304
    └─ Methodology: Volume of trades
    End timestamp: 1728477801 (2024-10-09T12:43:21.000Z)
    
    
    POLYGON 👇
    Backfill start time: 20/9/2024
    Daily volume: 0
    └─ Methodology: Volume of trades
    End timestamp: 1728477801 (2024-10-09T12:43:21.000Z)

**Comment by g1nt0ki** [comment]
@rouzwelt thanks for the PR, I refactored it a bit here. you were counting both sides of the swap when we count only one side.

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/dimension-adapters/pull/1979

**Comment by rouzwelt** [comment]
> @rouzwelt thanks for the PR, I refactored it a bit here. you were counting both sides of the swap when we count only one side. 

these are 2 sep tokens though, how is that not counted?

**Comment by rouzwelt** [comment]
if anything, you should include output side and not input side, raindex is not similar to other dexes

**Pull request closed without merging**
