### PR TITLE
Add VinuSwap volume

### PR DESCRIPTION
**Pull request by samuelemarro**
Already part of Defillama's TVL adapters. [PR here](https://github.com/DefiLlama/DefiLlama-Adapters/pull/12692).

### CODE REVIEW

**Comment by llamabutler** [comment]
The vinuswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs vinuswap
    
    🦙 Running VINUSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 12 Dec 2024 00:00:00 GMT
    End Date:	Fri, 13 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    VINU 👇
    Backfill start time: 1/6/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: -2276
    End timestamp: 1734047999 (2024-12-12T23:59:59.000Z)

**Comment by dtmkeng** [comment]
@samuelemarro could you take a look why value is negative ?

**Comment by samuelemarro** [comment]
It's subtracting outgoing money from the incoming one. What's the policy on measuring volume? If Alice swaps 100 USD worth of TokenA for 300 USD of TokenB, is the volume:
* tokenIn - tokenOut = -200 USD,
* abs(tokenIn - tokenOut) = 200 USD, or
* tokenIn + tokenOut = 400 USD

?

**Comment by dtmkeng** [comment]
> It's subtracting outgoing money from the incoming one. What's the policy on measuring volume? If Alice swaps 100 USD worth of TokenA for 300 USD of TokenB, is the volume:
> 
> * tokenIn - tokenOut = -200 USD,
> * abs(tokenIn - tokenOut) = 200 USD, or
> * tokenIn + tokenOut = 400 USD
> 
> ?

volume should track 1 side could you fix use tokenIn or tokenOut

**Comment by llamabutler** [comment]
The vinuswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs vinuswap
    
    🦙 Running VINUSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 18 Dec 2024 00:00:00 GMT
    End Date:	Thu, 19 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    VINU 👇
    Backfill start time: 1/6/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: -1423
    End timestamp: 1734566399 (2024-12-18T23:59:59.000Z)

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by llamabutler** [comment]
The vinuswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs vinuswap
    
    🦙 Running VINUSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 18 Dec 2024 12:23:30 GMT
    End Date:	Thu, 19 Dec 2024 12:23:30 GMT
    ---------------------------------------------------
    
    VINU 👇
    Backfill start time: 1/6/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 1.23 k
    End timestamp: 1734611009 (2024-12-19T12:23:29.000Z)

**Comment by g1nt0ki** [comment]
> It's subtracting outgoing money from the incoming one. What's the policy on measuring volume? If Alice swaps 100 USD worth of TokenA for 300 USD of TokenB, is the volume:
> 
>     * tokenIn - tokenOut = -200 USD,
> 
>     * abs(tokenIn - tokenOut) = 200 USD, or
> 
>     * tokenIn + tokenOut = 400 USD
> 
> 
> ?

umm, wouldnt alice swap 100$ worth of tokenA to 100$ worth of tokenB ?
how could they 3x the input?

**Comment by samuelemarro** [comment]
Yeah, I was making an example with a large discrepancy for simplicity's sake. In practice, due to price discrepancies, a more realistic situation would be swapping 100 USD for 101 USD or 99 USD.

**Comment by g1nt0ki** [comment]
hmm, we try to count the volume of major token in the pair (usually gas token of a chain or a stablecoin), this way, less chance of fluctuation. you can find the list for each chain here: https://github.com/DefiLlama/dimension-adapters/blob/master/helpers/coreAssets.json#L2

**Pull request merged**
