### PR TITLE
feat: add bifrost fees adapter

### PR DESCRIPTION
**Pull request by killbond007**
add bifrost dailyFees, dailyRevenue, totalRevenue, totalFees

### CODE REVIEW

**Comment by llamatester** [comment]
The bifrost-liquid-staking adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees bifrost-liquid-staking
    
    🦙 Running BIFROST-LIQUID-STAKING adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 25 Sep 2024 16:57:59 GMT
    End Date:	Thu, 26 Sep 2024 16:57:59 GMT
    ---------------------------------------------------
    
    BIFROST 👇
    Backfill start time: 1/1/2022
    NO METHODOLOGY SPECIFIED
    Daily fees: 26.73 k
    Daily revenue: 3.00 k
    Total revenue: 1.52 M
    Total fees: 6.25 M
    End timestamp: 1727369878 (2024-09-26T16:57:58.000Z)

**Comment by dtmkeng** [comment]
@killbond007 could you check api seem data is not up to date

**Comment by killbond007** [comment]
> @killbond007 could you check api seem data is not up to date
Hello, dtmkeng. Thank you for the reminder. A bug occurred during the mainnet upgrade service, but the service has now been restored.

**Comment by dtmkeng** [comment]
okay thank you

**Comment by dtmkeng** [comment]
@killbond007  could you take a look api seem data stop since 28/11 ?

**Comment by killbond007** [comment]
> @killbond007 could you take a look api seem data stop since 28/11 ?

Hello dtmkeng, the bug has been fixed

**Comment by killbond007** [comment]
> @killbond007 could you take a look api seem data stop since 28/11 ?

Hello dtmkeng, the bug has been fixed

**Comment by dtmkeng** [comment]
thx will refill

**Pull request merged**
