### PR TITLE
Added Chain Expansions

### PR DESCRIPTION
**Pull request by phpwufeng**
Chain Expansion:
Polygon chain added to the DeFi and DEX sections of MetaTdex project

### CODE REVIEW

**Comment by llamatester** [comment]
The metatdex adapter exports: 
        
 
 _______________________________________
    Dexs for 30/1/2023
    _______________________________________
    
    ------ ERROR ------
    [AxiosError: Request failed with status code 500] {
      code: 'ERR_BAD_RESPONSE',
      config: {
        transitional: {
          silentJSONParsing: true,
          forcedJSONParsing: true,
          clarifyTimeoutError: false
        },
        adapter: [Function: httpAdapter],
        transformRequest: [ [Function: transformRequest] ],
        transformResponse: [ [Function: transformResponse] ],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        env: { FormData: [Function] },
        validateStatus: [Function: validateStatus],
        headers: {
          Accept: 'application/json, text/plain, */*',
          'User-Agent': 'axios/0.27.2'
        },
        method: 'get',
        url: 'http://public.tdex.cz/get_volumes_list?chain_id=128',
        data: undefined
      },
      request: <ref *1> ClientRequest {
        _events: [Object: null prototype] {
          abort: [Function (anonymous)],
          aborted: [Function (anonymous)],
          connect: [Function (anonymous)],
          error: [Function (anonymous)],
          socket: [Function (anonymous)],
          timeout: [Function (anonymous)],
          finish: [Function: requestOnFinish]
        },
        _eventsCount: 7,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        destroyed: false,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        maxRequestsOnConnectionReached: false,
        _defaultKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        strictContentLength: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        _closed: false,
        socket: Socket {
          connecting: false,
          _hadError: false,
          _parent: null,
          _host: 'public.tdex.cz',
          _closeAfterHandlingError: false,
          _readableState: [ReadableState],
          _events: [Object: null prototype],
          _eventsCount: 7,
          _maxListeners: undefined,
          _writableState: [WritableState],
          allowHalfOpen: false,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: null,
          _server: null,
          parser: null,
          _httpMessage: [Circular *1],
          [Symbol(async_id_symbol)]: 527,
          [Symbol(kHandle)]: [TCP],
          [Symbol(lastWriteQueueSize)]: 0,
          [Symbol(timeout)]: null,
          [Symbol(kBuffer)]: null,
          [Symbol(kBufferCb)]: null,
          [Symbol(kBufferGen)]: null,
          [Symbol(kCapture)]: false,
          [Symbol(kSetNoDelay)]: false,
          [Symbol(kSetKeepAlive)]: true,
          [Symbol(kSetKeepAliveInitialDelay)]: 60,
          [Symbol(kBytesRead)]: 0,
          [Symbol(kBytesWritten)]: 0,
          [Symbol(RequestTimeout)]: undefined
        },
        _header: 'GET /get_volumes_list?chain_id=128 HTTP/1.1\r\n' +
          'Accept: application/json, text/plain, */*\r\n' +
          'User-Agent: axios/0.27.2\r\n' +
          'Host: public.tdex.cz\r\n' +
          'Connection: close\r\n' +
          '\r\n',
        _keepAliveTimeout: 0,
        _onPendingData: [Function: nop],
        agent: Agent {
          _events: [Object: null prototype],
          _eventsCount: 2,
          _maxListeners: undefined,
          defaultPort: 80,
          protocol: 'http:',
          options: [Object: null prototype],
          requests: [Object: null prototype] {},
          sockets: [Object: null prototype],
          freeSockets: [Object: null prototype] {},
          keepAliveMsecs: 1000,
          keepAlive: false,
          maxSockets: Infinity,
          maxFreeSockets: 256,
          scheduling: 'lifo',
          maxTotalSockets: Infinity,
          totalSocketCount: 1,
          [Symbol(kCapture)]: false
        },
        socketPath: undefined,
        method: 'GET',
        maxHeaderSize: undefined,
        insecureHTTPParser: undefined,
        path: '/get_volumes_list?chain_id=128',
        _ended: true,
        res: IncomingMessage {
          _readableState: [ReadableState],
          _events: [Object: null prototype],
          _eventsCount: 4,
          _maxListeners: undefined,
          socket: [Socket],
          httpVersionMajor: 1,
          httpVersionMinor: 1,
          httpVersion: '1.1',
          complete: true,
          rawHeaders: [Array],
          rawTrailers: [],
          aborted: false,
          upgrade: false,
          url: '',
          method: null,
          statusCode: 500,
          statusMessage: 'Internal Server Error',
          client: [Socket],
          _consuming: true,
          _dumped: false,
          req: [Circular *1],
          responseUrl: 'http://public.tdex.cz/get_volumes_list?chain_id=128',
          redirects: [],
          [Symbol(kCapture)]: false,
          [Symbol(kHeaders)]: [Object],
          [Symbol(kHeadersCount)]: 18,
          [Symbol(kTrailers)]: null,
          [Symbol(kTrailersCount)]: 0,
          [Symbol(RequestTimeout)]: undefined
        },
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        reusedSocket: false,
        host: 'public.tdex.cz',
        protocol: 'http:',
        _redirectable: Writable {
          _writableState: [WritableState],
          _events: [Object: null prototype],
          _eventsCount: 3,
          _maxListeners: undefined,
          _options: [Object],
          _ended: true,
          _ending: true,
          _redirectCount: 0,
          _redirects: [],
          _requestBodyLength: 0,
          _requestBodyBuffers: [],
          _onNativeResponse: [Function (anonymous)],
          _currentRequest: [Circular *1],
          _currentUrl: 'http://public.tdex.cz/get_volumes_list?chain_id=128',
          [Symbol(kCapture)]: false
        },
        [Symbol(kCapture)]: false,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(kEndCalled)]: true,
        [Symbol(kNeedDrain)]: false,
        [Symbol(corked)]: 0,
        [Symbol(kOutHeaders)]: [Object: null prototype] {
          accept: [Array],
          'user-agent': [Array],
          host: [Array]
        },
        [Symbol(kUniqueHeaders)]: null
      },
      response: {
        status: 500,
        statusText: 'Internal Server Error',
        headers: {
          server: 'nginx',
          date: 'Tue, 31 Jan 2023 02:20:03 GMT',
          'content-type': 'text/html; charset=utf-8',
          'transfer-encoding': 'chunked',
          connection: 'close',
          'x-powered-by': 'PHP/7.2.34',
          'access-control-allow-origin': '*',
          'access-control-allow-methods': '*',
          'access-control-allow-headers': 'x-requested-with,content-type'
        },
        config: {
          transitional: [Object],
          adapter: [Function: httpAdapter],
          transformRequest: [Array],
          transformResponse: [Array],
          timeout: 0,
          xsrfCookieName: 'XSRF-TOKEN',
          xsrfHeaderName: 'X-XSRF-TOKEN',
          maxContentLength: -1,
          maxBodyLength: -1,
          env: [Object],
          validateStatus: [Function: validateStatus],
          headers: [Object],
          method: 'get',
          url: 'http://public.tdex.cz/get_volumes_list?chain_id=128',
          data: undefined
        },
        request: <ref *1> ClientRequest {
          _events: [Object: null prototype],
          _eventsCount: 7,
          _maxListeners: undefined,
          outputData: [],
          outputSize: 0,
          writable: true,
          destroyed: false,
          _last: true,
          chunkedEncoding: false,
          shouldKeepAlive: false,
          maxRequestsOnConnectionReached: false,
          _defaultKeepAlive: true,
          useChunkedEncodingByDefault: false,
          sendDate: false,
          _removedConnection: false,
          _removedContLen: false,
          _removedTE: false,
          strictContentLength: false,
          _contentLength: 0,
          _hasBody: true,
          _trailer: '',
          finished: true,
          _headerSent: true,
          _closed: false,
          socket: [Socket],
          _header: 'GET /get_volumes_list?chain_id=128 HTTP/1.1\r\n' +
            'Accept: application/json, text/plain, */*\r\n' +
            'User-Agent: axios/0.27.2\r\n' +
            'Host: public.tdex.cz\r\n' +
            'Connection: close\r\n' +
            '\r\n',
          _keepAliveTimeout: 0,
          _onPendingData: [Function: nop],
          agent: [Agent],
          socketPath: undefined,
          method: 'GET',
          maxHeaderSize: undefined,
          insecureHTTPParser: undefined,
          path: '/get_volumes_list?chain_id=128',
          _ended: true,
          res: [IncomingMessage],
          aborted: false,
          timeoutCb: null,
          upgradeOrConnect: false,
          parser: null,
          maxHeadersCount: null,
          reusedSocket: false,
          host: 'public.tdex.cz',
          protocol: 'http:',
          _redirectable: [Writable],
          [Symbol(kCapture)]: false,
          [Symbol(kBytesWritten)]: 0,
          [Symbol(kEndCalled)]: true,
          [Symbol(kNeedDrain)]: false,
          [Symbol(corked)]: 0,
          [Symbol(kOutHeaders)]: [Object: null prototype],
          [Symbol(kUniqueHeaders)]: null
        },
        data: '<!DOCTYPE html>\n' +
          '<html>\n' +
          '<head>\n' +
          '    <meta charset="UTF-8">\n' +
          '    <title>System Error</title>\n' +
          '    <meta name="robots" content="noindex,nofollow" />\n' +
          '    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">\n' +
          '    <style>\n' +
          '        /* Base */\n' +
          '        body {\n' +
          '            color: #333;\n' +
          `            font: 14px Verdana, "Helvetica Neue", helvetica, Arial, 'Microsoft YaHei', sans-serif;\n` +
          '            margin: 0;\n' +
          '            padding: 0 20px 20px;\n' +
          '            word-break: break-word;\n' +
          '        }\n' +
          '        h1{\n' +
          '            margin: 10px 0 0;\n' +
          '            font-size: 28px;\n' +
          '            font-weight: 500;\n' +
          '            line-height: 32px;\n' +
          '        }\n' +
          '        h2{\n' +
          '            color: #4288ce;\n' +
          '            font-weight: 400;\n' +
          '            padding: 6px 0;\n' +
          '            margin: 6px 0 0;\n' +
          '            font-size: 18px;\n' +
          '            border-bottom: 1px solid #eee;\n' +
          '        }\n' +
          '        h3.subheading {\n' +
          '            color: #4288ce;\n' +
          '            margin: 6px 0 0;\n' +
          '            font-weight: 400;\n' +
          '        }\n' +
          '        h3{\n' +
          '            margin: 12px;\n' +
          '            font-size: 16px;\n' +
          '            font-weight: bold;\n' +
          '        }\n' +
          '        abbr{\n' +
          '            cursor: help;\n' +
          '            text-decoration: underline;\n' +
          '            text-decoration-style: dotted;\n' +
          '        }\n' +
          '        a{\n' +
          '            color: #868686;\n' +
          '            cursor: pointer;\n' +
          '        }\n' +
          '        a:hover{\n' +
          '            text-decoration: underline;\n' +
          '        }\n' +
          '        .line-error{\n' +
          '            background: #f8cbcb;\n' +
          '        }\n' +
          '\n' +
          '        .echo table {\n' +
          '            width: 100%;\n' +
          '        }\n' +
          '\n' +
          '        .echo pre {\n' +
          '            padding: 16px;\n' +
          '            overflow: auto;\n' +
          '            font-size: 85%;\n' +
          '            line-height: 1.45;\n' +
          '            background-color: #f7f7f7;\n' +
          '            border: 0;\n' +
          '            border-radius: 3px;\n' +
          '            font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;\n' +
          '        }\n' +
          '\n' +
          '        .echo pre > pre {\n' +
          '            padding: 0;\n' +
          '            margin: 0;\n' +
          '        }\n' +
          '        /* Layout */\n' +
          '        .col-md-3 {\n' +
          '            width: 25%;\n' +
          '        }\n' +
          '        .col-md-9 {\n' +
          '            width: 75%;\n' +
          '        }\n' +
          '        [class^="col-md-"] {\n' +
          '            float: left;\n' +
          '        }\n' +
          '        .clearfix {\n' +
          '            clear:both;\n' +
          '        }\n' +
          '        @media only screen \n' +
          '        and (min-device-width : 375px) \n' +
          '        and (max-device-width : 667px) { \n' +
          '            .col-md-3,\n' +
          '            .col-md-9 {\n' +
          '                width: 100%;\n' +
          '            }\n' +
          '        }\n' +
          '        /* Exception Info */\n' +
          '        .exception {\n' +
          '            margin-top: 20px;\n' +
          '        }\n' +
          '        .exception .message{\n' +
          '            padding: 12px;\n' +
          '            border: 1px solid #ddd;\n' +
          '            border-bottom: 0 none;\n' +
          '            line-height: 18px;\n' +
          '            font-size:16px;\n' +
          '            border-top-left-radius: 4px;\n' +
          '            border-top-right-radius: 4px;\n' +
          '            font-family: Consolas,"Liberation Mono",Courier,Verdana,"微软雅黑";\n' +
          '        }\n' +
          '\n' +
          '        .exception .code{\n' +
          '            float: left;\n' +
          '            text-align: center;\n' +
          '            color: #fff;\n' +
          '            margin-right: 12px;\n' +
          '            padding: 16px;\n' +
          '            border-radius: 4px;\n' +
          '            background: #999;\n' +
          '        }\n' +
          '        .exception .source-code{\n' +
          '            padding: 6px;\n' +
          '            border: 1px solid #ddd;\n' +
          '\n' +
          '            background: #f9f9f9;\n' +
          '            overflow-x: auto;\n' +
          '\n' +
          '        }\n' +
          '        .exception .source-code pre{\n' +
          '            margin: 0;\n' +
          '        }\n' +
          '        .exception .source-code pre ol{\n' +
          '            margin: 0;\n' +
          '            color: #4288ce;\n' +
          '            display: inline-block;\n' +
          '            min-width: 100%;\n' +
          '            box-sizing: border-box;\n' +
          '        font-size:14px;\n' +
          '            font-family: "Century Gothic",Consolas,"Liberation Mono",Courier,Verdana;\n' +
          '            padding-left: 56px;\n' +
          '        }\n' +
          '        .exception .source-code pre li{\n' +
          '            border-left: 1px solid #ddd;\n' +
          '            height: 18px;\n' +
          '            line-height: 18px;\n' +
          '        }\n' +
          '        .exception .source-code pre code{\n' +
          '            color: #333;\n' +
          '            height: 100%;\n' +
          '            display: inline-block;\n' +
          '            border-left: 1px solid #fff;\n' +
          '        font-size:14px;\n' +
          '            font-family: Consolas,"Liberation Mono",Courier,Verdana,"微软雅黑";\n' +
          '        }\n' +
          '        .exception .trace{\n' +
          '            padding: 6px;\n' +
          '            border: 1px solid #ddd;\n' +
          '            border-top: 0 none;\n' +
          '            line-height: 16px;\n' +
          '        font-size:14px;\n' +
          '            font-family: Consolas,"Liberation Mono",Courier,Verdana,"微软雅黑";\n' +
          '        }\n' +
          '        .exception .trace ol{\n' +
          '            margin: 12px;\n' +
          '        }\n' +
          '        .exception .trace ol li{\n' +
          '            padding: 2px 4px;\n' +
          '        }\n' +
          '        .exception div:last-child{\n' +
          '            border-bottom-left-radius: 4px;\n' +
          '            border-bottom-right-radius: 4px;\n' +
          '        }\n' +
          '\n' +
          '        /* Exception Variables */\n' +
          '        .exception-var table{\n' +
          '            width: 100%;\n' +
          '            margin: 12px 0;\n' +
          '            box-sizing: border-box;\n' +
          '            table-layout:fixed;\n' +
          '            word-wrap:break-word;            \n' +
          '        }\n' +
          '        .exception-var table caption{\n' +
          '            text-align: left;\n' +
          '            font-size: 16px;\n' +
          '            font-weight: bold;\n' +
          '            padding: 6px 0;\n' +
          '        }\n' +
          '        .exception-var table caption small{\n' +
          '            font-weight: 300;\n' +
          '            display: inline-block;\n' +
          '            margin-left: 10px;\n' +
          '            color: #ccc;\n' +
          '        }\n' +
          '        .exception-var table tbody{\n' +
          '            font-size: 13px;\n' +
          '            font-family: Consolas,"Liberation Mono",Courier,"微软雅黑";\n' +
          '        }\n' +
          '        .exception-var table td{\n' +
          '            padding: 0 6px;\n' +
          '            vertical-align: top;\n' +
          '            word-break: break-all;\n' +
          '        }\n' +
          '        .exception-var table td:first-child{\n' +
          '            width: 28%;\n' +
          '            font-weight: bold;\n' +
          '            white-space: nowrap;\n' +
          '        }\n' +
          '        .exception-var table td pre{\n' +
          '            margin: 0;\n' +
          '        }\n' +
          '\n' +
          '        /* Copyright Info */\n' +
          '        .copyright{\n' +
          '            margin-top: 24px;\n' +
          '            padding: 12px 0;\n' +
          '            border-top: 1px solid #eee;\n' +
          '        }\n' +
          '\n' +
          '        /* SPAN elements with the classes below are added by prettyprint. */\n' +
          '        pre.prettyprint .pln { color: #000 }  /* plain text */\n' +
          '        pre.prettyprint .str { color: #080 }  /* string content */\n' +
          '        pre.prettyprint .kwd { color: #008 }  /* a keyword */\n' +
          '        pre.prettyprint .com { color: #800 }  /* a comment */\n' +
          '        pre.prettyprint .typ { color: #606 }  /* a type name */\n' +
          '        pre.prettyprint .lit { color: #066 }  /* a literal value */\n' +
          '        /* punctuation, lisp open bracket, lisp close bracket */\n' +
          '        pre.prettyprint .pun, pre.prettyprint .opn, pre.prettyprint .clo { color: #660 }\n' +
          '        pre.prettyprint .tag { color: #008 }  /* a markup tag name */\n' +
          '        pre.prettyprint .atn { color: #606 }  /* a markup attribute name */\n' +
          '        pre.prettyprint .atv { color: #080 }  /* a markup attribute value */\n' +
          '        pre.prettyprint .dec, pre.prettyprint .var { color: #606 }  /* a declaration; a variable name */\n' +
          '        pre.prettyprint .fun { color: red }  /* a function name */\n' +
          '    </style>\n' +
          '</head>\n' +
          '<body>\n' +
          '    <div class="echo">\n' +
          '            </div>\n' +
          '        <div class="exception">\n' +
          '    <div class="message">\n' +
          '        \n' +
          '            <div class="info">\n' +
          '                <div>\n' +
          '                    <h2>[2005]&nbsp;<abbr title="PDOException">PDOException</abbr> in <a class="toggle" title="/data/web/public.tdex/thinkphp/library/think/db/Connection.php line 295">Connection.php line 295</a></h2>\n' +
          '                </div>\n' +
          "                <div><h1>SQLSTATE[HY000] [2005] Unknown MySQL server host 'onlyread2.cm7yhcwtnme9.ap-southeast-1.rds.amazonaws.com' (2)</h1></div>\n" +
          '            </div>\n' +
          '        \n' +
          '    </div>\n' +
          '\t        <div class="source-code">\n' +
          `            <pre class="prettyprint lang-php"><ol start="286"><li class="line-286"><code>                $this-&gt;fetchType = $config['result_type'];\n` +
          '</code></li><li class="line-287"><code>            }\n' +
          '</code></li><li class="line-288"><code>            try {\n' +
          `</code></li><li class="line-289"><code>                if (empty($config['dsn'])) {\n` +
          `</code></li><li class="line-290"><code>                    $config['dsn'] = $this-&gt;parseDsn($config);\n` +
          '</code></li><li class="line-291"><code>                }\n' +
          `</code></li><li class="line-292"><code>                if ($config['debug']) {\n` +
          '</code></li><li class="line-293"><code>                    $startTime = microtime(true);\n' +
          '</code></li><li class="line-294"><code>                }\n' +
          `</code></li><li class="line-295"><code>                $this-&gt;links[$linkNum] = new PDO($config['dsn'], $config['username'], $config['password'], $params);\n` +
          `</code></li><li class="line-296"><code>                if ($config['debug']) {\n` +
          '</code></li><li class="line-297"><code>                    // 记录数据库连接信息\n' +
          `</code></li><li class="line-298"><code>                    Log::record('[ DB ] CONNECT:[ UseTime:' . number_format(microtime(true) - $startTime, 6) . 's ] ' . $config['dsn'], 'sql');\n` +
          '</code></li><li class="line-299"><code>                }\n' +
          '</code></li><li class="line-300"><code>            } catch (\\PDOException $e) {\n' +
          '</code></li><li class="line-301"><code>                if ($autoConnection) {\n' +
          `</code></li><li class="line-302"><code>                    Log::record($e-&gt;getMessage(), 'error');\n` +
          '</code></li><li class="line-303"><code>                    return $this-&gt;connect($autoConnection, $linkNum);\n' +
          '</code></li><li class="line-304"><code>                } else {\n' +
          '</code></li></ol></pre>\n' +
          '        </div>\n' +
          '\t        <div class="trace">\n' +
          '            <h2>Call Stack</h2>\n' +
          '            <ol>\n' +
          '                <li>in <a class="toggle" title="/data/web/public.tdex/thinkphp/library/think/db/Connection.php line 295">Connection.php line 295</a></li>\n' +
          '                                <li>\n' +
          `                at <abbr title="PDO">PDO</abbr>->__construct('<a class="toggle" title="mysql:host=onlyread2.cm7yhcwtnme9.ap-southeast-1.rds.amazonaws.com;port=3307;dbname=tdex6;charset=utf8mb4">mysql:host=onlyread2...</a>', 'admin_turbine', '<a class="toggle" title="TTwljh.tt.AA.zz.VVV.2021">TTwljh.tt.AA.zz.VVV....</a>', [0, 2, 0, ...]) in <a class="toggle" title="/data/web/public.tdex/thinkphp/library/think/db/Connection.php line 295">Connection.php line 295</a>                </li>\n` +
          '      '... 63869 more characters
      }
    }
    Done in 20.68s.

**Comment by llamatester** [comment]
The metatdex adapter exports: 
        
 
 _______________________________________
    Dexs for 30/1/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 23/8/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1675036800
    Block: undefined
    Daily volume: 260922.9428575499
    Total volume: 661365216.6782076
    
    
    HECO 👇
    Backfill start time: 20/5/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1675036800
    Block: undefined
    Daily volume: 28694728.43240787
    Total volume: 4494823657.900605
    
    
    POLYGON 👇
    Backfill start time: 9/12/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1675036800
    Block: undefined
    Daily volume: 4482885.557649
    Total volume: 92673370.03912202
    
    
    
    
    Done in 20.21s.

**Comment by phpwufeng** [comment]
@0xtawa hello，When will Polygon information be displayed ？

**Comment by phpwufeng** [comment]
Hi, Dear DefiLlama platform

We found that DefiLlama's statistics about metatdex trading volume only count USDT trading volume, not coin-based trading volume, is this accurate? The API interface is as follows: http://public.tdex.cz/get_volumes_list?chain_id=137

**Pull request merged**
