### PR TITLE
adapter for Erinaceus VRF

### PR DESCRIPTION
**Pull request by erinaceus-labs**
Add adapter for Erinaceus VRF, add Bahamut network in chains list

### CODE REVIEW

**Comment by llamatester** [comment]
The erinaceus adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees erinaceus
    
    🦙 Running ERINACEUS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 22 Sep 2024 13:03:46 GMT
    End Date:	Mon, 23 Sep 2024 13:03:46 GMT
    ---------------------------------------------------
    
    FTN 👇
    Backfill start time: 22/5/2024
    Methodology: All Fees generated from activity on Erinaceus VRF Coordinator contract.
    Daily fees: 0
    Daily revenue: 0
    End timestamp: 1727096625 (2024-09-23T13:03:45.000Z)

**Comment by dtmkeng** [comment]
is there details for list website x and some details ?

**Comment by erinaceus-labs** [comment]
Hi, sure
"Erinaceus VRF Oracle is a product of an Erinaceus decentralized oracle
platform, providing verifiable random functions (VRF) for secure and
tamper-proof randomness. It's crucial for applications like gaming,
lotteries, NFT generation and other use cases where fair randomness is
essential. By integrating Erinaceus, developers can ensure transparent,
unbiased outcomes in their smart contracts. Simply connect your project to
the oracle for seamless and reliable random number generation."
https://x.com/ErinaceusOracle
https://www.linkedin.com/company/erinaceus/

**Comment by dtmkeng** [comment]
@erinaceus-labs could you check why adapter is return 0 ?

**Comment by erinaceus-labs** [comment]
> @erinaceus-labs could you check why adapter is return 0 ?

It's returning 0 because there are only a few transactions, and the fee is too low. Given the small transaction volume, it's okay if the adapter returns 0.

**Pull request merged**
