### PR TITLE
Add Equity - Fees & Volume adapters

### PR DESCRIPTION
**Pull request by ftm1337**

### CODE REVIEW

**Comment by llamatester** [comment]
The equity-spot adapter exports: 
        
 
 _______________________________________
    Dexs for 26/6/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 30/5/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1687737600
    Daily volume: 35.00000000000001
    Total volume: 3291.1477376307066
    
    
    
    
    Done in 4.09s.

**Comment by llamatester** [comment]
The equity-spot adapter exports: 
        
 
 _______________________________________
    Dexs for 26/6/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 30/5/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1687737600
    Daily volume: 35.00000000000001
    Total volume: 3291.157737630707
    
    
    
    
    Done in 4.28s.

**Comment by llamatester** [comment]
The equity adapter exports: 
        
 
 _______________________________________
    Fees for 26/6/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 30/5/2023
    Methodology: 100.00% of All & Any Fees generated from All activity on Any Equity Platform Product goes solely to veEQUAL voters.
    Timestamp: 1687823998
    Daily fees: 1.957710752531161
    Daily revenue: 1.957710752531161
    
    
    
    
    Done in 4.04s.

**Comment by llamatester** [comment]
The equity-spot adapter exports: 
        
 
 _______________________________________
    Dexs for 27/6/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 30/5/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1687824000
    Daily volume: 0.01
    Total volume: 4011.611768630707
    
    
    
    
    Done in 3.68s.

**Comment by dtmkeng** [comment]
@ftm1337  data is ok ?

**Comment by ftm1337** [comment]
@dtmkeng yes, the numbers from the llamatester look correct when compared to the official numbers (here: https://equity-stats.equalizer.exchange/)
for 2023-06-26, fees is $1.6
image
for 2023-06-26, volume is $0.01
image

i had a small request, can we rename "`Equalizer0x`" to "`Equalizer`" .. i think it got mislabelled earlier by @realdealshaman while making a parent protocol entry (here : https://github.com/DefiLlama/defillama-server/commit/da9872c59911edc52dbf41e2e9fbfc39f6ac9394 ) 
image
the 0x thing is the twitter handle, initially created by the community, not the actual project name :sweat_smile:

**Review by alokeutpal — APPROVED** [review]

**Pull request merged**
