### PR TITLE
Add hercules dex

### PR DESCRIPTION
**Pull request by waliair**
re-open with id

For tracking: prev #1439

### CODE REVIEW

**Comment by llamatester** [comment]
The hercules-v3 adapter exports: 
        
 
 _______________________________________
    Dexs for 25/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 3/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1714031381 (2024-04-25T07:49:41.000Z)
    Block: 16.79 M
    Total volume: 67.45 M
    Daily volume: 1.61 M
    
    
    
    
    Done in 7.13s.

**Comment by llamatester** [comment]
The hercules adapter exports: 
        
 
 _______________________________________
    Dexs for 25/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 23/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1714031389 (2024-04-25T07:49:49.000Z)
    Block: 16.79 M
    Total volume: 405.01 k
    Daily volume: 5.27 k
    
    
    
    
    Done in 5.90s.

**Comment by llamatester** [comment]
The hercules-v2.ts adapter exports: 
        
 
 _______________________________________
    fatal: Not a valid object name master
    Error: Command failed: git ls-tree --name-only -r master
    fatal: Not a valid object name master
    
        at checkExecSyncError (node:child_process:890:11)
        at execSync (node:child_process:962:15)
        at checkIfFileExistsInMasterBranch (/home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:12:23)
        at /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:53:5
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      status: 128,
      signal: null,
      output: [
        null,
        <Buffer >,
        <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 76 61 6c 69 64 20 6f 62 6a 65 63 74 20 6e 61 6d 65 20 6d 61 73 74 65 72 0a>
      ],
      pid: 1973,
      stdout: <Buffer >,
      stderr: <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 76 61 6c 69 64 20 6f 62 6a 65 63 74 20 6e 61 6d 65 20 6d 61 73 74 65 72 0a>
    }
    Done in 1.30s.

**Comment by llamatester** [comment]
The hercules-v3.ts adapter exports: 
        
 
 _______________________________________
    fatal: Not a valid object name master
    Error: Command failed: git ls-tree --name-only -r master
    fatal: Not a valid object name master
    
        at checkExecSyncError (node:child_process:890:11)
        at execSync (node:child_process:962:15)
        at checkIfFileExistsInMasterBranch (/home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:12:23)
        at /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:53:5
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      status: 128,
      signal: null,
      output: [
        null,
        <Buffer >,
        <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 76 61 6c 69 64 20 6f 62 6a 65 63 74 20 6e 61 6d 65 20 6d 61 73 74 65 72 0a>
      ],
      pid: 2049,
      stdout: <Buffer >,
      stderr: <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 76 61 6c 69 64 20 6f 62 6a 65 63 74 20 6e 61 6d 65 20 6d 61 73 74 65 72 0a>
    }
    Done in 1.31s.

**Comment by llamatester** [comment]
The hercules-v3 adapter exports: 
        
 
 _______________________________________
    Dexs for 25/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 3/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1714031649 (2024-04-25T07:54:09.000Z)
    Block: 16.79 M
    Total volume: 67.45 M
    Daily volume: 1.61 M
    
    
    
    
    Done in 13.08s.

**Comment by llamatester** [comment]
The hercules adapter exports: 
        
 
 _______________________________________
    Dexs for 25/4/2024
    _______________________________________
    
    METIS 👇
    Backfill start time: 23/10/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1714031663 (2024-04-25T07:54:23.000Z)
    Block: 16.79 M
    Total volume: 405.01 k
    Daily volume: 5.25 k
    
    
    
    
    Done in 5.70s.

**Comment by llamatester** [comment]
The hercules-v2.ts adapter exports: 
        
 
 _______________________________________
    fatal: Not a valid object name master
    Error: Command failed: git ls-tree --name-only -r master
    fatal: Not a valid object name master
    
        at checkExecSyncError (node:child_process:890:11)
        at execSync (node:child_process:962:15)
        at checkIfFileExistsInMasterBranch (/home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:12:23)
        at /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:53:5
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      status: 128,
      signal: null,
      output: [
        null,
        <Buffer >,
        <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 76 61 6c 69 64 20 6f 62 6a 65 63 74 20 6e 61 6d 65 20 6d 61 73 74 65 72 0a>
      ],
      pid: 2055,
      stdout: <Buffer >,
      stderr: <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 76 61 6c 69 64 20 6f 62 6a 65 63 74 20 6e 61 6d 65 20 6d 61 73 74 65 72 0a>
    }
    Done in 1.30s.

**Comment by llamatester** [comment]
The hercules-v3.ts adapter exports: 
        
 
 _______________________________________
    fatal: Not a valid object name master
    Error: Command failed: git ls-tree --name-only -r master
    fatal: Not a valid object name master
    
        at checkExecSyncError (node:child_process:890:11)
        at execSync (node:child_process:962:15)
        at checkIfFileExistsInMasterBranch (/home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:12:23)
        at /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:53:5
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      status: 128,
      signal: null,
      output: [
        null,
        <Buffer >,
        <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 76 61 6c 69 64 20 6f 62 6a 65 63 74 20 6e 61 6d 65 20 6d 61 73 74 65 72 0a>
      ],
      pid: 2132,
      stdout: <Buffer >,
      stderr: <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 76 61 6c 69 64 20 6f 62 6a 65 63 74 20 6e 61 6d 65 20 6d 61 73 74 65 72 0a>
    }
    Done in 1.27s.

**Comment by waliair** [comment]
@g1nt0ki after your commit ts-check test giving typeError, can u help?

**Comment by g1nt0ki** [comment]
@waliair let me check

**Comment by g1nt0ki** [comment]
@waliair thanks for the PR, issue was you were using v1 adapter format, I have updated it to use v2 here: https://github.com/DefiLlama/dimension-adapters/pull/1445

**Comment by waliair** [comment]
@g1nt0ki thank u so much.

**Pull request closed without merging**
