### PR TITLE
Add SNSY token option

### PR DESCRIPTION
**Pull request by apostgit**

### CODE REVIEW

**Comment by llamatester** [comment]
The snsy adapter exports: 
        
 
 _______________________________________
    Options for 22/5/2024
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily notional volume: 25.41 k
    Daily premium volume: 25.41 k
    Total notional volume: 25.41 k
    Total premium volume: 25.41 k
    Timestamp: 1716378116 (2024-05-22T11:41:56.000Z)
    
    
    BASE 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily notional volume: 677
    Daily premium volume: 677
    Total notional volume: 677
    Total premium volume: 677
    Timestamp: 1716378116 (2024-05-22T11:41:56.000Z)
    
    
    ARBITRUM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily notional volume: 1.05 k
    Daily premium volume: 1.05 k
    Total notional volume: 1.05 k
    Total premium volume: 1.05 k
    Timestamp: 1716378116 (2024-05-22T11:41:56.000Z)

**Comment by dtmkeng** [comment]
hnm seem wrong could you check premium and notional volume 
and is there tvl ?

**Comment by bettiolo** [comment]
> https://github.com/DefiLlama/DefiLlama-Adapters this repo for list tvl and could you check Daily notional volume and Daily premium volume seem incorrect

Can you tell us what is the difference?

**Comment by dtmkeng** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters this it for tvl 
and thus repo it for volume and fees

**Comment by apostgit** [comment]
I'm sorry but did you mean to send a different URL? These all link to the original repo. We are trying to set up a graph so that we can fetch the data from it. Should we query the graph directly on the `option/snsy/index.ts` or we can do it on our own endpoint and fetch the endpoint on the option?

**Comment by dtmkeng** [comment]
your option data is incorrect premium it not equal notional volume

**Pull request closed without merging**
