### PR TITLE
Ape.Store dex adapter on base

### PR DESCRIPTION
**Pull request by mrben1**
Added Ape.Store dex adapter on base

### CODE REVIEW

**Comment by llamatester** [comment]
The apestore adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The apestore adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

**Comment by llamatester** [comment]
The apestore adapter exports: 
        
 
 _______________________________________
    Dexs for 10/5/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 4/4/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 5.39 M
    Daily volume: 141.41 k
    Timestamp: 1715308540 (2024-05-10T02:35:40.000Z)

**Comment by llamatester** [comment]
The apestore adapter exports: 
        
 
 _______________________________________
    Dexs for 10/5/2024
    _______________________________________
    
    BASE 👇
    Backfill start time: 4/4/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 5.39 M
    Daily volume: 142.29 k
    Timestamp: 1715308604 (2024-05-10T02:36:44.000Z)

**Comment by dtmkeng** [comment]
is there tvl adapter ?

**Comment by mrben1** [comment]
> is there tvl adapter ?

No, just a dex volume dashboard

**Comment by dtmkeng** [comment]
could you add ?

**Comment by mrben1** [comment]
> could you add ?

Can you point me in the direction of a code sample to copy? your docs seem to be quite out of date.

**Comment by mrben1** [comment]
> could you add ?

Added https://github.com/DefiLlama/DefiLlama-Adapters/pull/10172

**Comment by dtmkeng** [comment]
@mrben1  is it swap volume  ?

**Comment by mrben1** [comment]
> @mrben1 is it swap volume ?

correct

**Pull request merged**
