### PR TITLE
new chain data

### PR DESCRIPTION
**Pull request by miler012**
we deploy the dapp at the linea and scroll mainnet, the fee and 24volume will add them.pls thanks

### CODE REVIEW

**Comment by llamatester** [comment]
The satori adapter exports: 
        
 
 _______________________________________
    Dexs for 2/11/2023
    _______________________________________
    
    POLYGON_ZKEVM 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 3250349647.52284
    Daily volume: 28682799.783178
    Daily fees: 258.086769000000000000
    Daily revenue: 258.086769000000000000
    Timestamp: 1698980582827
    
    
    ERA 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 3250349647.52284
    Daily volume: 28682799.783178
    Daily fees: 258.086769000000000000
    Daily revenue: 258.086769000000000000
    Timestamp: 1698980583023
    
    
    LINEA 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 29643.17752
    Daily volume: 8815.986727
    Daily fees: 14.728425000000000000
    Daily revenue: 14.728425000000000000
    Timestamp: 1698980583020
    
    
    SCROLL 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 115811.358575
    Daily volume: 38079.62928
    Daily fees: 72.606369000000000000
    Daily revenue: 72.606369000000000000
    Timestamp: 1698980583053
    
    
    
    
    Done in 5.95s.

**Comment by llamatester** [comment]
The satori adapter exports: 
        
 
 _______________________________________
    Dexs for 2/11/2023
    _______________________________________
    
    POLYGON_ZKEVM 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 3440622428.481942
    Daily volume: 106905.982683
    Daily fees: 92.401508000000000000
    Daily revenue: 92.401508000000000000
    Timestamp: 1698999997057
    
    
    ERA 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 3255791773.809275
    Daily volume: 28847461.285073
    Daily fees: 194.599744000000000000
    Daily revenue: 194.599744000000000000
    Timestamp: 1698999997058
    
    
    LINEA 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 41658.28593
    Daily volume: 19521.925867
    Daily fees: 36.877290000000000000
    Daily revenue: 36.877290000000000000
    Timestamp: 1698999997072
    
    
    SCROLL 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 122012.551267
    Daily volume: 41201.308452
    Daily fees: 76.016769000000000000
    Daily revenue: 76.016769000000000000
    Timestamp: 1698999997079
    
    
    
    
    Done in 3.38s.

**Comment by dtmkeng** [comment]
could you remove .`idea`

**Comment by llamatester** [comment]
The satori adapter exports: 
        
 
 _______________________________________
    Dexs for 5/11/2023
    _______________________________________
    
    POLYGON_ZKEVM 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 3440649958.855342
    Daily volume: 6118.38462
    Daily fees: 12.585960000000000000
    Daily revenue: 12.585960000000000000
    Timestamp: 1699272069169
    
    
    ERA 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 3333179236.623223
    Daily volume: 27122121.720877
    Daily fees: 182.795168000000000000
    Daily revenue: 182.795168000000000000
    Timestamp: 1699272069128
    
    
    LINEA 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 84702.217202
    Daily volume: 19430.430772
    Daily fees: 27.914737000000000000
    Daily revenue: 27.914737000000000000
    Timestamp: 1699272069165
    
    
    SCROLL 👇
    Backfill start time: 13/5/2023
    NO METHODOLOGY SPECIFIED
    Total volume: 219707.511725
    Daily volume: 24492.459177
    Daily fees: 47.333391000000000000
    Daily revenue: 47.333391000000000000
    Timestamp: 1699272069167
    
    
    
    
    Done in 3.46s.

**Pull request merged**
