### PR TITLE
Add cellana vomlume & fees

### PR DESCRIPTION
**Pull request by Centure2222**

### CODE REVIEW

**Comment by llamatester** [comment]
The cellana-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 6/3/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://api.cellana.finance/api/v1/tool/trading-volume-chart?timeframe=VOLUME_1H&endTimestamp=1709769598',
      method: 'GET',
      axiosError: 'Forbidden',
      chain: 'aptos'
    }
    Done in 3.79s.

**Comment by dtmkeng** [comment]
could you check error 403 ?

**Comment by Centure2222** [comment]
> could you check error 403 ?

it's ok now, please check this, sir

**Comment by llamatester** [comment]
The cellana-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 10/3/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://api.cellana.finance/api/v1/tool/trading-volume-chart?timeframe=VOLUME_1H&endTimestamp=1710115198',
      method: 'GET',
      axiosError: 'Forbidden',
      chain: 'aptos'
    }
    Done in 2.65s.

**Comment by dtmkeng** [comment]
it error when run on server ? could you check ?

**Comment by Centure2222** [comment]
> it error when run on server ? could you check ?

where your sever, sir?

**Comment by llamatester** [comment]
The cellana-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 11/3/2024
    _______________________________________
    
    [Error: Request failed with status code 403] {
      url: 'https://api.cellana.finance/api/v1/tool/trading-volume-chart?timeframe=VOLUME_1H&endTimestamp=1710201598',
      method: 'GET',
      axiosError: 'Forbidden',
      chain: 'aptos'
    }
    Done in 5.65s.

**Comment by oliver112024** [comment]
@dtmkeng please help to re-check again, thank you

**Comment by Centure2222** [comment]
> @dtmkeng please help to re-check again, thank you

i fixed in cloudflare , could u restart job? thank sir. sorry about that!

**Comment by llamatester** [comment]
The cellana-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 11/3/2024
    _______________________________________
    
    APTOS 👇
    Backfill start time: 28/2/2024
    NO METHODOLOGY SPECIFIED
    Total volume: 3.76 M
    Daily volume: 356.94 k
    Total fees: 3.20 k
    Daily fees: 276
    Total protocol revenue: 0
    Daily protocol revenue: 0
    Timestamp: 1710201598 (2024-03-11T23:59:58.000Z)
    
    
    
    
    Done in 5.52s.

**Pull request merged**
