### PR TITLE
add blum

### PR DESCRIPTION
**Pull request by sk-blum**

### CODE REVIEW

**Comment by llamatester** [comment]
The blum adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs blum
    
    🦙 Running BLUM adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 02 Dec 2024 12:45:22 GMT
    End Date:	Tue, 03 Dec 2024 12:45:22 GMT
    ---------------------------------------------------
    
    TON 👇
    Backfill start time: 24/10/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 501.47 k
    End timestamp: 1733229921 (2024-12-03T12:45:21.000Z)

**Comment by dtmkeng** [comment]
why volume is so high ?, are you count one side ?, example count only volume out or in

**Comment by sk-blum** [comment]
Bots are trading actively plus a volume of 0.5M isn’t particularly high, especially considering we have over 100K active traders with relatively small transaction sizes.

**Comment by 0xSeymour** [comment]
> why volume is so high ?, are you count one side ?, example count only volume out or in

it is in $ so it is not so high for such big app

**Pull request merged**
