### PR TITLE
Mantis Volume

### PR DESCRIPTION
**Pull request by godilov**
We currently interested only in posting daily/total volumes, so there is no Mantis adapter in DefiLlama-Adapters repository. Should we add some dummy adapter to properly list Mantis and only then add Volume, or can we add it right here?

### CODE REVIEW

**Comment by llamabutler** [comment]
The mantis adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs mantis
    
    🦙 Running MANTIS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 15 Dec 2024 00:00:00 GMT
    End Date:	Mon, 16 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    SOLANA 👇
    Backfill start time: 30/11/2024
    Methodology: Sum of all executed intents with Solana as input or output
    Daily volume: 522.78 k
    Total volume: 2.51 M
    End timestamp: 1734307199 (2024-12-15T23:59:59.000Z)
    
    
    ETHEREUM 👇
    Backfill start time: 30/11/2024
    Methodology: Sum of all executed intents with Ethereum as input or output
    Daily volume: 0
    Total volume: 80
    End timestamp: 1734307199 (2024-12-15T23:59:59.000Z)

**Comment by llamabutler** [comment]
The mantis adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs mantis
    
    🦙 Running MANTIS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 15 Dec 2024 00:00:00 GMT
    End Date:	Mon, 16 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Removing key solana:0x0000…0000
    Removing key solana:0xdac1…1ec7
    Removing key solana:0xc02a…6cc2
    Removing key solana:0x0000…0000
    SOLANA 👇
    Backfill start time: 30/11/2024
    Methodology: Sum of all executed intents with Solana as input or output
    Daily volume: 546.45 k
    Total volume: 2.53 M
    End timestamp: 1734307199 (2024-12-15T23:59:59.000Z)
    
    
    ETHEREUM 👇
    Backfill start time: 30/11/2024
    Methodology: Sum of all executed intents with Ethereum as input or output
    Daily volume: 0
    Total volume: 79
    End timestamp: 1734307199 (2024-12-15T23:59:59.000Z)

**Comment by g1nt0ki** [comment]
@godilov thanks for the PR, just volume adapter is enough. I have removed invalid keys in the data 
image
For some reason truncated eth addresses were found in sol data

**Comment by g1nt0ki** [comment]
can you fill in this form: 

##### Name (to be shown on DefiLlama):


##### Twitter Link:


##### List of audit links if any:


##### Website Link:


##### Logo (High resolution, will be shown with rounded borders):


##### Current TVL:


##### Treasury Addresses (if the protocol has treasury)


##### Chain:


##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)


##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)


##### Short Description (to be shown on DefiLlama):


##### Token address and ticker if any:


##### Category (full list at https://defillama.com/categories) *Please choose only one:


##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

##### forkedFrom (Does your project originate from another project):


##### methodology (what is being counted as tvl, how is tvl being calculated):


##### Github org/user (Optional, if your code is open source, we can track activity):

**Comment by godilov** [comment]
Yeah, sure

##### Name (to be shown on DefiLlama):
Mantis

##### Twitter Link:
https://x.com/mantis

##### List of audit links if any:
https://github.com/ComposableFi/composable/tree/main/audits/mantis-contracts

##### Website Link:
https://www.mantis.app

##### Logo (High resolution, will be shown with rounded borders):
mantis-logo


##### Current TVL:
—

##### Treasury Addresses (if the protocol has treasury)
—

##### Chain:
Solana/Ethereum

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
—

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
—

##### Short Description (to be shown on DefiLlama):
Unified intent-based trading app on Solana and Ethereum

##### Token address and ticker if any:
—

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
##### Implementation Details: Briefly describe how the oracle is integrated into your project:
##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:

##### forkedFrom (Does your project originate from another project):
Solana

##### methodology (what is being counted as tvl, how is tvl being calculated):
—

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/ComposableFi

**Comment by dtmkeng** [comment]
hi seem your volume it slow down could you check your API ? 
image

**Comment by godilov** [comment]
It seems like there is some issue in data on graph. Total volume of mantis swaps over its existence and functioning is about 2.9 million USD and recent daily volume is correct. But volume for the first 12-14 days seems too high.
Can we correct it somehow? For the last 3 days data is correct

**Comment by godilov** [comment]
@dtmkeng, can you help please?

**Comment by dtmkeng** [comment]
> seems like there is some issue in data on graph. Total volume of mantis swaps over its existence and functioning is about 2.9 million USD and recent daily volume is correct. But volume for the first 12-14 days seems too high.
> Can we correct it somehow? For the last 3 days data is correct

your api it return data correct ?

**Comment by g1nt0ki** [comment]
hi @godilov if you fix the subgraph on your end, we can re-run the adapters and fix the chart on your end.

**Comment by godilov** [comment]
Sorry for the delay. It is fixed and completely deployed. @g1nt0ki, we are good to re-run now

**Comment by dtmkeng** [comment]
@godilov  will backfill data

**Pull request merged**
