### PR TITLE
Add Grafun fee and revenue adapter for BSC

### PR DESCRIPTION
**Pull request by 0xsaymon**

### CODE REVIEW

**Comment by llamatester** [comment]
The grafun.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees grafun.ts
    
    🦙 Running GRAFUN.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 13 Oct 2024 11:02:30 GMT
    End Date:	Mon, 14 Oct 2024 11:02:30 GMT
    ---------------------------------------------------
    
    BSC 👇
    Backfill start time: 27/9/2024
    End timestamp: 1728903749 (2024-10-14T11:02:29.000Z)
    Daily fees: 796
    └─ Methodology: Sum of all fees from Token Sale Factory smart contract.
    Daily revenue: 771
    └─ Methodology: Sum of all revenue from Token Sale Factory smart contract.
    Daily volume: 24.89 k

**Comment by llamatester** [comment]
The grafun.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees grafun.ts
    
    🦙 Running GRAFUN.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 13 Oct 2024 11:23:29 GMT
    End Date:	Mon, 14 Oct 2024 11:23:29 GMT
    ---------------------------------------------------
    
    BSC 👇
    Backfill start time: 27/9/2024
    End timestamp: 1728905008 (2024-10-14T11:23:28.000Z)
    Daily fees: 800
    └─ Methodology: Sum of all fees from Token Sale Factory smart contract.
    Daily revenue: 775
    └─ Methodology: Sum of all revenue from Token Sale Factory smart contract.
    Daily volume: 25.02 k

**Comment by g1nt0ki** [comment]
thanks for the PR, I have refactored it a bit merged it here: https://github.com/DefiLlama/dimension-adapters/pull/2000

**Comment by 0xsaymon** [comment]
> thanks for the PR, I have refactored it a bit merged it here: https://github.com/DefiLlama/dimension-adapters/pull/2000

Thanks!

**Pull request closed without merging**
