### PR TITLE
EⅢ : Fees Adapter

### PR DESCRIPTION
**Pull request by ftm1337**

### CODE REVIEW

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 5/5/2023
    _______________________________________
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x8597dB3ba8dE6BAAdEDa8cBa4dAC653E24a0e57B","data":"0x574f2ba3","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
        at Logger.makeError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
        at Logger.throwError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:632:24
        at Array.forEach (<anonymous>)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:614:33
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:48:23)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:33:139)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at fulfilled (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:20:58) {
      reason: 'missing revert data in call exception; Transaction reverted without a reason string',
      code: 'CALL_EXCEPTION',
      transaction: {
        to: '0x8597dB3ba8dE6BAAdEDa8cBa4dAC653E24a0e57B',
        data: '0x574f2ba3',
        accessList: null
      }
    }
    Failed to get value on fantom: Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x8597dB3ba8dE6BAAdEDa8cBa4dAC653E24a0e57B","data":"0x574f2ba3","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    FANTOM 👇
    Timestamp attempted: 4/5/2023
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x8597dB3ba8dE6BAAdEDa8cBa4dAC653E24a0e57B","data":"0x574f2ba3","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
        at Logger.makeError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
        at Logger.throwError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:632:24
        at Array.forEach (<anonymous>)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:614:33
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:48:23)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:33:139)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at fulfilled (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:20:58) {
      reason: 'missing revert data in call exception; Transaction reverted without a reason string',
      code: 'CALL_EXCEPTION',
      transaction: {
        to: '0x8597dB3ba8dE6BAAdEDa8cBa4dAC653E24a0e57B',
        data: '0x574f2ba3',
        accessList: null
      }
    }
    
    
    
    
    Done in 4.70s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 5/5/2023
    _______________________________________
    
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x8597dB3ba8dE6BAAdEDa8cBa4dAC653E24a0e57B","data":"0x574f2ba3","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
        at Logger.makeError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
        at Logger.throwError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:632:24
        at Array.forEach (<anonymous>)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:614:33
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:48:23)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:33:139)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at fulfilled (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:20:58) {
      reason: 'missing revert data in call exception; Transaction reverted without a reason string',
      code: 'CALL_EXCEPTION',
      transaction: {
        to: '0x8597dB3ba8dE6BAAdEDa8cBa4dAC653E24a0e57B',
        data: '0x574f2ba3',
        accessList: null
      }
    }
    Failed to get value on fantom: Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x8597dB3ba8dE6BAAdEDa8cBa4dAC653E24a0e57B","data":"0x574f2ba3","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    FANTOM 👇
    Timestamp attempted: 4/5/2023
    Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x8597dB3ba8dE6BAAdEDa8cBa4dAC653E24a0e57B","data":"0x574f2ba3","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
        at Logger.makeError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
        at Logger.throwError (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:632:24
        at Array.forEach (<anonymous>)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:614:33
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:48:23)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:33:139)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
        at fulfilled (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@ethersproject/providers/lib/fallback-provider.js:20:58) {
      reason: 'missing revert data in call exception; Transaction reverted without a reason string',
      code: 'CALL_EXCEPTION',
      transaction: {
        to: '0x8597dB3ba8dE6BAAdEDa8cBa4dAC653E24a0e57B',
        data: '0x574f2ba3',
        accessList: null
      }
    }
    
    
    
    
    Done in 4.22s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 5/5/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 142738368141561.6
    Daily revenue: 142738368141561.6
    Daily holders revenue: 142738368141561.6
    Timestamp: 1683331198
    
    
    
    
    Done in 12.22s.

**Comment by ftm1337** [comment]
hmm
but my [dune](https://dune.com/queries/2395015/3929206) thinks fee is $103 
image

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 6/5/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 17.054951226
    Daily revenue: 17.054951226
    Daily holders revenue: 17.054951226
    Timestamp: 1683417598
    
    
    
    
    Done in 14.34s.

**Comment by ftm1337** [comment]
:thinking: reversing doesnt help.. i think the original numbers are correct, but have somehow have 12 extra digits (usdc has 6 decimals, wftm has 18, could be that?)
as of now, E3 has 2 pools, USDC-fUSDT & WFTM-USDC.. maybe it has to do with ordering tokens by address? uniswap orders token0 to be the one which has a lower address (dictionary sort).. but in E3 the token0 ("tokenX") can be anything.. here wftm is 0x21be while usdc is 0x0406
meanwhile, our [Dune Numbers](https://dune.com/queries/2402516/3942906) are:
5th may : $139.00
6th may : $103.63
the result above has $142 for 5th may, which would be very close to the expected $139.. probably based on daily price used by defillama instead of per-minute price use by our dune query..
i'll revert the last commit.. but still need to figure if its the decimal problem or something else

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 6/5/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 195793881909046.2
    Daily revenue: 195793881909046.2
    Daily holders revenue: 195793881909046.2
    Timestamp: 1683417598
    
    
    
    
    Done in 12.87s.

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    dexs/e3/index.ts(73,7): error TS2451: Cannot redeclare block-scoped variable 'graph'.
    dexs/e3/index.ts(171,14): error TS2451: Cannot redeclare block-scoped variable 'graph'.
    dexs/e3/index.ts(170,6): error TS2322: Type 'import("/home/runner/work/dimension-adapters/dimension-adapters/helpers/chains").CHAIN' is not assignable to type '{ start: IStartTimestamp; fetch: Fetch; runAtCurrTime?: boolean | undefined; customBackfill?: Fetch | undefined; meta?: { methodology?: string | IJSON<string> | undefined; hallmarks?: [...][] | undefined; } | undefined; }'.
    dexs/e3/index.ts(171,14): error TS7031: Binding element 'graph' implicitly has an 'any' type.
    dexs/e3/index.ts(172,7): error TS2304: Cannot find name 'start'.
    dexs/e3/index.ts(172,14): error TS2695: Left side of comma operator is unused and has no side effects.
    dexs/e3/index.ts(170,19): error TS1005: ',' expected.
    dexs/e3/index.ts(170,21): error TS1136: Property assignment expected.
    dexs/e3/index.ts(171,19): error TS1005: ',' expected.
    dexs/e3/index.ts(172,12): error TS1005: ';' expected.
    dexs/e3/index.ts(173,5): error TS1109: Expression expected.
    dexs/e3/index.ts(173,6): error TS1128: Declaration or statement expected.
    dexs/e3/index.ts(174,3): error TS1128: Declaration or statement expected.
    dexs/e3/index.ts(175,1): error TS1128: Declaration or statement expected.
    
    Done in 3.02s.

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    Dexs for 6/5/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 8145930949714065
    Timestamp: 1683417598
    
    
    
    
    Done in 10.77s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 6/5/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 195793881909046.2
    Daily revenue: 195793881909046.2
    Daily holders revenue: 195793881909046.2
    Timestamp: 1683417598
    
    
    
    
    Done in 9.66s.

**Comment by ftm1337** [comment]
nope, the numbers are wrong :(

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    Dexs for 6/5/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 47265.56405332122
    Timestamp: 1683417598
    
    
    
    
    Done in 10.72s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 6/5/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 195793881909046.2
    Daily revenue: 195793881909046.2
    Daily holders revenue: 195793881909046.2
    Timestamp: 1683417598
    
    
    
    
    Done in 10.10s.

**Comment by ftm1337** [comment]
Volume numbers look better but Dune says 58K :disappointed: 
image

**Comment by dtmkeng** [comment]
> Volume numbers look better but Dune says 58K 😞 image _https://dune.com/e3/fees_

hi, could you try like this, sorry about code base, 🙏

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    Dexs for 7/5/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 7802.144699252375
    Timestamp: 1683503998
    
    
    
    
    Done in 11.29s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 7/5/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 26657524936504.29
    Daily revenue: 26657524936504.29
    Daily holders revenue: 26657524936504.29
    Timestamp: 1683503998
    
    
    
    
    Done in 10.06s.

**Comment by ftm1337** [comment]
you are awesome @dtmkeng !
Dune Volume : $7861.35
Defillama Volume: $7802.14 
99.25% accuracy! :smile: 
i'll try the fees adapter now

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 7/5/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 13.933884896038018
    Timestamp: 1683503998
    
    
    
    
    Done in 11.58s.

**Comment by ftm1337** [comment]
:ok_hand: perfect!
Defillama: $13.93388
Dune: $14.065393
~99.064% accurate, 1% error margin.. sounds good!
Ready for a merge :heavy_check_mark:

**Pull request merged**
