### PR TITLE
Added an additional revenue stream from OpenBot funding which is distributed every 24 hours to the profit wallet.

### PR DESCRIPTION
**Pull request by nobodynodrama**

### CODE REVIEW

**Comment by dtmkeng** [comment]
value is from bot trade ? not token trake ?

**Comment by llamatester** [comment]
The aimbot.ts adapter exports: 
        
 
 _______________________________________
    ------ ERROR ------
    Error: Cannot find module 'request-promise'
    Require stack:
    - /home/runner/work/dimension-adapters/dimension-adapters/fees/aimbot.ts
    - /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
        at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
        at Function.Module._load (node:internal/modules/cjs/loader:975:27)
        at Module.require (node:internal/modules/cjs/loader:1225:19)
        at require (node:internal/modules/helpers:177:18)
        at Object.<anonymous> (/home/runner/work/dimension-adapters/dimension-adapters/fees/aimbot.ts:6:17)
        at Module._compile (node:internal/modules/cjs/loader:1356:14)
        at Module.m._compile (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1618:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
        at Object.require.extensions.<computed> [as .ts] (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/ts-node/src/index.ts:1621:12) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/home/runner/work/dimension-adapters/dimension-adapters/fees/aimbot.ts',
        '/home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts'
      ]
    }
    Done in 2.77s.

**Comment by dtmkeng** [comment]
if you need get api just use axios

**Comment by nobodynodrama** [comment]
>if you need get api just use axios

will change it, thanks

> value is from bot trade ?is it not included in token (fees from trade tokem) trade?

This is another revenue stream. 

AimBot launched OpenBot which is a user-instanced version of Aimbot which people feed their own funds into it with different strategies/risk levels available

Value is 40% of generated bananabot bribes + openbot usage fee, sent to reward pool every 24 hours.

You can verify this in the article written by AimBot team near the end of the article.
https://medium.com/@aimbottoken/aimbot-opening-access-to-our-new-ai-bot-b2cd1de6bdfa

"How does this benefit the AIMBOT project?
40% of the ETH generated from bribes and fees will be directly sent to the reward pool. Another 10% will be send to AI funding wallet (for AIMBOT trading). The remaining 50% will go to the team."

**Comment by nobodynodrama** [comment]
I messed up my fork and couldnt correctly merge my changes. I decided to delete it and make a new fork which uses axios as you mentioned. Look for it!

**Pull request closed without merging**
