### PR TITLE
Add TON Hedge

### PR DESCRIPTION
**Pull request by Kotevode**

### CODE REVIEW

**Comment by llamatester** [comment]
The ton-hedge adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts options ton-hedge
    
    🦙 Running TON-HEDGE adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 02 Sep 2024 00:00:00 GMT
    End Date:	Tue, 03 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    TON 👇
    Backfill start time: 1/7/2024
    NO METHODOLOGY SPECIFIED
    Daily notional volume: 0
    Daily premium volume: 0
    Total notional volume: 82.27 k
    Total premium volume: 4.51 k

**Comment by dtmkeng** [comment]
which timestamp is use for your api ex UTC 0 ?

**Comment by llamatester** [comment]
The ton-hedge.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts protocols ton-hedge.ts
    
    🦙 Running TON-HEDGE.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 03 Sep 2024 00:00:00 GMT
    End Date:	Wed, 04 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    TON 👇
    Backfill start time: 1/7/2024
    Daily notional volume: 4.84 k
    Daily premium volume: 102
    Total notional volume: 89.33 k
    Total premium volume: 4.58 k
    Total volume: 8.84 k
    └─ Methodology: Total costs + payouts
    Daily volume: 108
    └─ Methodology: Total costs + payouts
    End timestamp: 1725407999 (2024-09-03T23:59:59.000Z)

**Comment by Kotevode** [comment]
> which timestamp is use for your api ex UTC 0 ?

right now used the same as passed to fetch function

**Comment by dtmkeng** [comment]
is it options volume ?

**Pull request merged**
