### PR TITLE
Add Cellula adapter

### PR DESCRIPTION
**Pull request by cellulalifegame**
Name (to be shown on DefiLlama): Cellula

**Twitter Link**: https://twitter.com/cellulalifegame

**List of audit links if any**: https://factory.cellula.life/pdf

**Website Link**: https://factory.cellula.life/

**Logo** (High resolution, will be shown with rounded borders): [Cellula_Logo_Profile_Pic.png](https://drive.google.com/file/d/1FMoGc96ej36Plw4NlVtMX25jO1RsuC5T/view?usp=sharing)

Current TVL:

Treasury Addresses (if the protocol has treasury)

Chain: BSC

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):

Short Description (to be shown on DefiLlama): Cellula, a fully on-chain AI game that offers users the ability to create, compose and evolve their digital life. Its unique Virtual Proof of Work (vPOW) asset distribution method provides an innovative incentive layer for games within the Cellula ecosystem.

Token address and ticker if any:
Category (full list at https://defillama.com/categories) *Please choose only one: 37 [Gaming](https://defillama.com/protocols/Gaming)

Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Implementation Details: Briefly describe how the oracle is integrated into your project:
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
forkedFrom (Does your project originate from another project):
methodology (what is being counted as tvl, how is tvl being calculated):
Github org/user (Optional, if your code is open source, we can track activity):

### CODE REVIEW

**Comment by llamatester** [comment]
The cellula adapter exports: 
        
 
 _______________________________________
    Fees for 25/5/2024
    _______________________________________
    
    BSC 👇
    Backfill start time: 14/4/2024
    Total fees: 23
    └─ Methodology: The cost of renting a Cell.
    Daily fees: 23
    └─ Methodology: The cost of renting a Cell.
    Daily user fees: 23
    Daily revenue: 6.17 k
    └─ Methodology: The sum of life charging fees and life mint fees.
    Daily protocol revenue: 6.03 k
    Daily holders revenue: 23
    Daily supply side revenue: 115
    Timestamp: 1716631490 (2024-05-25T10:04:50.000Z)

**Comment by dtmkeng** [comment]
mint fees and charging fees and life mint fees go to team and holder ?

**Comment by cellulalifegame** [comment]
@dtmkeng 
**Team**:  100% charging fees + 95% life mint fess ( 70% for protocol, 25% for future liquidity).
**Cell Holders**: 5% life mint fess.

**Comment by dtmkeng** [comment]
i think fees =rev 
and holder rev from 5% of mint fees and protocol is 70% of mint fees

**Comment by cellulalifegame** [comment]
Yes, you are right. @dtmkeng 
So, do I need to change to 0% fees and 100% revenue in adapter?

**Comment by dtmkeng** [comment]
> Yes, you are right. @dtmkeng So, do I need to change to 0% fees and 100% revenue in adapter?

no i think your fees it equal mint and charge fees and rev you can calculate from % above

**Comment by llamatester** [comment]
The cellula adapter exports: 
        
 
 _______________________________________
    Fees for 26/5/2024
    _______________________________________
    
    {
      llamaRPCError: true,
      errors: [
        { host: 'https://bsc-dataseed.binance.org', error: [Object] },
        { host: 'https://bsc-dataseed.bnbchain.org', error: [Object] },
        { host: 'https://bsc-dataseed2.defibit.io', error: [Object] }
      ],
      chain: 'bsc'
    }

**Comment by cellulalifegame** [comment]
> The cellula adapter exports:
> 
> ```
> Fees for 26/5/2024
> _______________________________________
> 
> {
>   llamaRPCError: true,
>   errors: [
>     { host: 'https://bsc-dataseed.binance.org', error: [Object] },
>     { host: 'https://bsc-dataseed.bnbchain.org', error: [Object] },
>     { host: 'https://bsc-dataseed2.defibit.io', error: [Object] }
>   ],
>   chain: 'bsc'
> }
> ```
Got rpc error, Recreate exports.

**Comment by llamatester** [comment]
The cellula adapter exports: 
        
 
 _______________________________________
    Fees for 27/5/2024
    _______________________________________
    
    BSC 👇
    Backfill start time: 14/4/2024
    Daily fees: 34.57 k
    └─ Methodology: The cost of renting a Cell.
    Daily revenue: 34.57 k
    └─ Methodology: The sum of life charging fees and life mint fees.
    Daily protocol revenue: 34.45 k
    Daily holders revenue: 19
    Daily supply side revenue: 95
    Timestamp: 1716778988 (2024-05-27T03:03:08.000Z)

**Comment by cellulalifegame** [comment]
Can this PR be merged? @dtmkeng

**Comment by dtmkeng** [comment]
@cellulalifegame  hi seem adapter is can map workTime for 300 do you know value for 300

**Pull request merged**
