### PR TITLE
Refactor velodrome/aerodrome

### PR DESCRIPTION
**Pull request by g1nt0ki**

### CODE REVIEW

**Comment by llamatester** [comment]
The aerodrome-slipstream adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs aerodrome-slipstream
    
    🦙 Running AERODROME-SLIPSTREAM adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 18 Sep 2024 12:06:22 GMT
    End Date:	Thu, 19 Sep 2024 12:06:22 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 3/5/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 476.82 M
    Daily fees: 284.71 k
    Daily revenue: 284.71 k
    Daily holders revenue: 284.71 k
    End timestamp: 1726747581 (2024-09-19T12:06:21.000Z)

**Comment by llamatester** [comment]
The aerodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs aerodrome
    
    🦙 Running AERODROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 18 Sep 2024 12:07:53 GMT
    End Date:	Thu, 19 Sep 2024 12:07:53 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 30.81 M
    Daily fees: 80.12 k
    End timestamp: 1726747672 (2024-09-19T12:07:52.000Z)

**Comment by llamatester** [comment]
The Omnidrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees Omnidrome
    
    🦙 Running OMNIDROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 18 Sep 2024 00:00:00 GMT
    End Date:	Thu, 19 Sep 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ZETA 👇
    Backfill start time: 6/2/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1726703999 (2024-09-18T23:59:59.000Z)
    Daily fees: 0

**Comment by llamatester** [comment]
The aerodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees aerodrome
    
    🦙 Running AERODROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 18 Sep 2024 12:09:38 GMT
    End Date:	Thu, 19 Sep 2024 12:09:38 GMT
    ---------------------------------------------------
    
    [Error: Promise pool failed! 
     PromisePoolError: Failed to call: function tryAggregate(bool requireSuccess, tuple(address target, bytes callData)[] calls) payable returns (tuple(bool success, bytes returnData)[] returnData) target: 0xca11bde05977b3631167028862be2a173976ca11 params: false, 0x16613524e02ad97eDfeF371bC883F2F5d6C480A50,0xb9a09fd50000000000000000000000006cdcb1c4a4d1c3c6d054b27ac5b77e89eafb971d,0x16613524e02ad... on chain: [base] rpc:   call reverted, reason: invalid address (argument="address", value="0x16613524e02ad97eDfeF371bC883F2F5d6C480A50", code=INVALID_ARGUMENT, version=6.13.2) (argument="target", value="0x16613524e02ad97eDfeF371bC883F2F5d6C480A50", code=INVALID_ARGUMENT, version=6.13.2)   ] {
      _isCustomError: true,
      chain: 'base'
    }

**Comment by llamatester** [comment]
The keller-cl adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees keller-cl
    
    🦙 Running KELLER-CL adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 18 Sep 2024 12:10:58 GMT
    End Date:	Thu, 19 Sep 2024 12:10:58 GMT
    ---------------------------------------------------
    
    SCROLL 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Daily protocol revenue: 0
    End timestamp: 1726747857 (2024-09-19T12:10:57.000Z)

**Comment by llamatester** [comment]
The keller adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees keller
    
    🦙 Running KELLER adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 18 Sep 2024 12:11:06 GMT
    End Date:	Thu, 19 Sep 2024 12:11:06 GMT
    ---------------------------------------------------
    
    SCROLL 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Daily fees: 0
    Daily revenue: 0
    Daily holders revenue: 0
    Daily bribes revenue: 0
    End timestamp: 1726747865 (2024-09-19T12:11:05.000Z)

**Comment by llamatester** [comment]
The velodrome-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees velodrome-v2
    
    🦙 Running VELODROME-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 18 Sep 2024 12:11:15 GMT
    End Date:	Thu, 19 Sep 2024 12:11:15 GMT
    ---------------------------------------------------
    
    Error: token is required
        at Balances.add (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/Balances.js:32:19)
        at /home/runner/work/dimension-adapters/dimension-adapters/fees/velodrome-v2/index.ts:30:24
        at Array.forEach (<anonymous>)
        at customLogic (/home/runner/work/dimension-adapters/dimension-adapters/fees/velodrome-v2/index.ts:29:8)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:51:18)
        at async Promise.all (index 2)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:27:20)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'bob'
    }

**Comment by llamatester** [comment]
The velodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees velodrome
    
    🦙 Running VELODROME adapter 🦙
    ---------------------------------------------------
    GRAPH_API_KEY env variable is not set, using the default api key
    Start Date:	Wed, 18 Sep 2024 12:12:28 GMT
    End Date:	Thu, 19 Sep 2024 12:12:28 GMT
    ---------------------------------------------------
    
    ClientError: auth error: payment required for subsequent requests for this API key: {"response":{"errors":[{"message":"auth error: payment required for subsequent requests for this API key"}],"status":200,"headers":{}},"request":{"query":"\n      query fees {\n        yesterday: pairs(block: {number: 125531348}, where: {volumeUSD_gt: \"0\"}, first: 1000) {\n          id\n          isStable\n          volumeUSD\n        }\n        today: pairs(block: {number: 125574548}, where: {volumeUSD_gt: \"0\"}, first: 1000) {\n          id\n          isStable\n          volumeUSD\n        }\n      }\n    "}}
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/src/index.ts:498:11
        at step (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:67:23)
        at Object.next (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:48:53)
        at fulfilled (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/graphql-request/dist/index.js:39:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      response: {
        errors: [ [Object] ],
        status: 200,
        headers: Headers { [Symbol(map)]: [Object: null prototype] }
      },
      request: {
        query: '\n' +
          '      query fees {\n' +
          '        yesterday: pairs(block: {number: 125531348}, where: {volumeUSD_gt: "0"}, first: 1000) {\n' +
          '          id\n' +
          '          isStable\n' +
          '          volumeUSD\n' +
          '        }\n' +
          '        today: pairs(block: {number: 125574548}, where: {volumeUSD_gt: "0"}, first: 1000) {\n' +
          '          id\n' +
          '          isStable\n' +
          '          volumeUSD\n' +
          '        }\n' +
          '      }\n' +
          '    ',
        variables: undefined
      },
      chain: 'optimism'
    }

**Review by dtmkeng — APPROVED** [review]

**Pull request merged**
