### PR TITLE
Add Jellyverse adapter for SEI chain

### PR DESCRIPTION
**Pull request by pho-phoenix**
- Create new directory for Jellyverse
- Implement index.ts with adapter for tracking daily volume and fees
- Configure endpoint for SEI chain subgraph
- Implement volume and fees calculation based on poolSnapshots
- Set up adapter with v2 breakdown for SEI chain

### CODE REVIEW

**Comment by llamatester** [comment]
The jellyverse adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs jellyverse
    
    🦙 Running JELLYVERSE adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 19 Aug 2024 13:30:03 GMT
    End Date:	Tue, 20 Aug 2024 13:30:03 GMT
    ---------------------------------------------------
    
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 80711999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 80711999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    Version -> V2
    ---------
    SEI 👇
    Backfill start time: 20/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 105.20 k
    Daily fees: 264
    End timestamp: 1724160602 (2024-08-20T13:30:02.000Z)

**Comment by llamatester** [comment]
The jellyverse adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs jellyverse
    
    🦙 Running JELLYVERSE adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 19 Aug 2024 15:21:23 GMT
    End Date:	Tue, 20 Aug 2024 15:21:23 GMT
    ---------------------------------------------------
    
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 80711999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 80711999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    Version -> V2
    ---------
    SEI 👇
    Backfill start time: 20/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 133.78 k
    Daily fees: 350
    End timestamp: 1724167282 (2024-08-20T15:21:22.000Z)

**Comment by llamatester** [comment]
The jellyverse adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs jellyverse
    
    🦙 Running JELLYVERSE adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 19 Aug 2024 15:27:46 GMT
    End Date:	Tue, 20 Aug 2024 15:27:46 GMT
    ---------------------------------------------------
    
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 95079999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 95079999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    Version -> V2
    ---------
    SEI 👇
    Backfill start time: 20/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 134.56 k
    Daily fees: 352
    End timestamp: 1724167665 (2024-08-20T15:27:45.000Z)

**Comment by llamatester** [comment]
The jellyverse adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs jellyverse
    
    🦙 Running JELLYVERSE adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 19 Aug 2024 15:30:00 GMT
    End Date:	Tue, 20 Aug 2024 15:30:00 GMT
    ---------------------------------------------------
    
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 82529999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 82529999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    Version -> V2
    ---------
    SEI 👇
    Backfill start time: 20/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 134.56 k
    Daily fees: 352
    End timestamp: 1724167799 (2024-08-20T15:29:59.000Z)

**Comment by dtmkeng** [comment]
could you revert change ..github/workflows ?

**Comment by llamatester** [comment]
The jellyverse adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs jellyverse
    
    🦙 Running JELLYVERSE adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 19 Aug 2024 17:28:16 GMT
    End Date:	Tue, 20 Aug 2024 17:28:16 GMT
    ---------------------------------------------------
    
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 80711999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    error fetching block [Error: Llama RPC error! methos: undefined 
    - host: https://evm-rpc.sei-apis.com error: height is not available (requested height: 78353999, base height: 80711999)] {
      _underlyingError: '[object Object]',
      _isCustomError: true
    }
    Version -> V2
    ---------
    SEI 👇
    Backfill start time: 20/8/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 143.51 k
    Daily fees: 378
    End timestamp: 1724174895 (2024-08-20T17:28:15.000Z)

**Pull request merged**
