### PR TITLE
update volume arbitrum

### PR DESCRIPTION
**Pull request by algebraDefi**

### CODE REVIEW

**Comment by llamatester** [comment]
The level-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 4/7/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 10/12/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1688428800
    Daily volume: 6616680.045667646
    Total volume: 19618271641.89773
    
    
    ARBITRUM 👇
    Backfill start time: 9/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1688428800
    Daily volume: 15907756.857011471
    Total volume: 353465769.47955155
    
    
    
    
    Done in 4.36s.

**Comment by dtmkeng** [comment]
seem total is include derivatives volume
if you need to update derivatives, plz use this 
https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/level-finance-derivative/index.ts

**Comment by llamatester** [comment]
The level-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 5/7/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 10/12/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1688515200
    Daily volume: 13806580.88474298
    Total volume: 4146147120.807221
    
    
    ARBITRUM 👇
    Backfill start time: 9/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1688515200
    Daily volume: 2764094.7709477535
    Total volume: 121181127.85836639
    
    
    
    
    Done in 3.94s.

**Comment by llamatester** [comment]
The level-finance-derivative adapter exports: 
        
 
 _______________________________________
    Dexs for 5/7/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 10/12/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1688515200
    Daily volume: 9111323.92054992
    Total volume: 15536526023.584599
    
    
    ARBITRUM 👇
    Backfill start time: 9/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1688515200
    Daily volume: 11138877.53799421
    Total volume: 243104375.2808695
    
    
    
    
    Done in 4.60s.

**Comment by llamatester** [comment]
The level-finance adapter exports: 
        
 
 _______________________________________
    Dexs for 5/7/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 10/12/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1688515200
    Daily volume: 13806580.88474298
    Total volume: 4147667965.2273016
    
    
    ARBITRUM 👇
    Backfill start time: 9/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1688515200
    Daily volume: 2764094.7709477535
    Total volume: 121482821.58114691
    
    
    
    
    Done in 4.33s.

**Comment by dtmkeng** [comment]
LG ty

**Pull request merged**
