### PR TITLE
E3 - Fees & Volume : Fee/Rev/PF/TF/UF/SSR & Using Factory to get all pools.

### PR DESCRIPTION
**Pull request by ftm1337**

### CODE REVIEW

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    Dexs for 14/7/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1689379198
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 2704.1901908049026
    Timestamp: 1689379198
    
    
    
    
    Done in 11.34s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 14/7/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    Daily fees: 0
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 0
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 0
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 0
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 0
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1689379198
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    Daily fees: 4.706813026060255
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 4.706813026060255
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 4.706303755006411
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 4.706303755006411
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 4.706303755006411
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.000509271053843463
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1689379198
    
    
    
    
    Done in 11.18s.

**Comment by ftm1337** [comment]
Shouldnt we be using the factory for Joe-v2.1's fee & volume adapters too?

**Comment by dtmkeng** [comment]
> Shouldnt we be using the factory for Joe-v2.1's fee & volume adapters too?

not sure for joe2.1 just filter volume some pool, for exclude scam token

**Comment by ftm1337** [comment]
hmm true... those could skew its results.. guess its okay the way it is (for now at least) :upside_down_face:

**Comment by dtmkeng** [comment]
> hmm true... those could skew its results.. guess its okay the way it is (for now at least) 🙃

yeah, will  fix to switch to use factory, thank you for advice

**Comment by dtmkeng** [comment]
ohhm could remove change for yarn and package log

**Comment by dtmkeng** [comment]
sorry

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    Dexs for 14/7/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1689379198
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 2704.1901908049026
    Timestamp: 1689379198
    
    
    
    
    Done in 10.64s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 14/7/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    Daily fees: 0
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 0
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 0
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 0
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 0
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1689379198
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    Daily fees: 4.706813026060255
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 4.706813026060255
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 4.706303755006411
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 4.706303755006411
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 4.706303755006411
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0.000509271053843463
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1689379198
    
    
    
    
    Done in 10.24s.

**Comment by dtmkeng** [comment]
code it oke will merge after you remove change from yarn and package lock

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    Dexs for 17/7/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1689638398
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 184613.594153583
    Timestamp: 1689638398
    
    
    
    
    Done in 12.27s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 17/7/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    Daily fees: 0
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 0
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 0
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 0
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 0
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1689638398
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    Daily fees: 78.54534303661778
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 78.54534303661778
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 17.558843959936983
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 17.558843959936983
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 17.558843959936983
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 60.9864990766808
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1689638398
    
    
    
    
    Done in 11.64s.

**Comment by llamatester** [comment]
The e3 adapter exports: 
        
 
 _______________________________________
    Dexs for 17/7/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1689638398
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 184613.594153583
    Timestamp: 1689638398
    
    
    
    
    Done in 10.61s.

**Comment by llamatester** [comment]
The e3.ts adapter exports: 
        
 
 _______________________________________
    Fees for 17/7/2023
    _______________________________________
    
    FANTOM 👇
    Backfill start time: 10/4/2023
    Daily fees: 0
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 0
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 0
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 0
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 0
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 0
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1689638398
    
    
    ARBITRUM 👇
    Backfill start time: 11/6/2023
    Daily fees: 78.54534303661778
    └─ Methodology: Net Trading fees paid is the Sum of fees sent to LP & Protocol Fees
    Daily user fees: 78.54534303661778
    └─ Methodology: EⅢ users pay a Trading fee on each swap. Includes Flash Loan Fees.
    Daily protocol revenue: 17.558843959936983
    └─ Methodology: 100% of Revenue is collected by Protocol Treasury.
    Daily revenue: 17.558843959936983
    └─ Methodology: A variable % of the trading fee is collected as Protocol Fees.
    Daily holders revenue: 17.558843959936983
    └─ Methodology: 100% of Revenue is used to buyback ELITE.
    Daily supply side revenue: 60.9864990766808
    └─ Methodology: The portion of trading fees paid to liquidity providers.
    Timestamp: 1689638398
    
    
    
    
    Done in 10.11s.

**Pull request merged**
