### PR TITLE
Update thena perp and fees

### PR DESCRIPTION
**Pull request by 0xSullivan**

### CODE REVIEW

**Comment by llamatester** [comment]
The symmio adapter exports: 
        
 
 _______________________________________
    Dexs for 20/9/2023
    _______________________________________
    
    Version -> FEES
    ---------
    BSC 👇
    Backfill start time: 27/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1695168000
    Daily volume: "1715225.8950291"
    Total volume: "39762942.430614286498484234"
    
    
    Version -> DERIVATIVES
    ---------
    BSC 👇
    Backfill start time: 27/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1695168000
    Daily fees: "504.77185563846"
    Total fees: "16383.06370360782"
    Daily user fees: "504.77185563846"
    Daily revenue: "504.77185563846"
    Daily protocol revenue: 0
    Daily holders revenue: "504.77185563846"
    Daily supply side revenue: 0
    Total user fees: "16383.06370360782"
    Total revenue: "16383.06370360782"
    Total protocol revenue: 0
    Total supply side revenue: 0
    Total daily holders revenue: "16383.06370360782"
    
    
    Done in 3.67s.

**Comment by 0xSullivan** [comment]
I want to list symmio in both Derivatives & Fees dashboards as mentioned here:
https://docs.llama.fi/list-your-project/other-dashboards/listing-your-project

**Comment by dtmkeng** [comment]
hmm not sure this `https://github.com/DefiLlama/dimension-adapters/blob/master/dexs/thena-perp/index.ts` seem thena team listing not sure relate this

**Comment by llamatester** [comment]
The symmio adapter exports: 
        
 
 _______________________________________
    Dexs for 20/9/2023
    _______________________________________
    
    Version -> FEES
    ---------
    BSC 👇
    Backfill start time: 27/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1695168000
    Daily volume: "1715225.8950291"
    Total volume: "40363373.959414286498484234"
    
    
    Version -> DERIVATIVES
    ---------
    BSC 👇
    Backfill start time: 27/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1695168000
    Daily fees: "504.77185563846"
    Total fees: "16389.64022566782"
    Daily user fees: "504.77185563846"
    Daily revenue: "504.77185563846"
    Daily protocol revenue: 0
    Daily holders revenue: "504.77185563846"
    Daily supply side revenue: 0
    Total user fees: "16389.64022566782"
    Total revenue: "16389.64022566782"
    Total protocol revenue: 0
    Total supply side revenue: 0
    Total daily holders revenue: "16389.64022566782"
    
    
    Done in 4.06s.

**Comment by llamatester** [comment]
The thena-perp adapter exports: 
        
 
 _______________________________________
    Dexs for 20/9/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 27/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1695168000
    Daily volume: 1702254.4950291
    Total volume: 18811240.15959253762
    
    
    
    
    Done in 3.61s.

**Comment by llamatester** [comment]
The thena-perp adapter exports: 
        
 
 _______________________________________
    Dexs for 20/9/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 27/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1695168000
    Daily volume: 1702254.4950291
    Total volume: 18811240.15959253762
    
    
    
    
    Done in 3.63s.

**Comment by llamatester** [comment]
The thena-perp.ts adapter exports: 
        
 
 _______________________________________
    Fees for 20/9/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 27/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1695168000
    Daily fees: 504.77185563846
    Total fees: 5752.99585881
    Daily user fees: 504.77185563846
    Daily revenue: 504.77185563846
    Daily protocol revenue: 0
    Daily holders revenue: 504.77185563846
    Daily supply side revenue: 0
    Total user fees: 5752.99585881
    Total revenue: 5752.99585881
    Total protocol revenue: 0
    Total supply side revenue: 0
    
    
    
    
    Done in 3.75s.

**Pull request merged**
