### PR TITLE
intentx: Updated subgraph endpoint

### PR DESCRIPTION
**Pull request by lemonpac**
We were using a hosted service subgraph that have been deprecated.
Also we have multiplied the volume by 2 to match the solver analytics.
New data has to be backfilled.

### CODE REVIEW

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 09 Jul 2024 00:00:00 GMT
    End Date:	Wed, 10 Jul 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1720483200 (2024-07-09T00:00:00.000Z)
    Daily volume: 660.03 k
    Total volume: 1.70 B
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1720483200 (2024-07-09T00:00:00.000Z)
    Daily volume: 664.97 k
    Total volume: 499.30 M
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1720483200 (2024-07-09T00:00:00.000Z)
    Daily volume: 35.25 M
    Total volume: 1.76 B

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 09 Jul 2024 13:26:08 GMT
    End Date:	Wed, 10 Jul 2024 13:26:08 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 46
    Total fees: 469.57 k
    Daily user fees: 46
    Daily revenue: 46
    Daily protocol revenue: 0
    Daily holders revenue: 46
    Daily supply side revenue: 0
    Total user fees: 469.57 k
    Total revenue: 469.57 k
    Total protocol revenue: 0
    Total supply side revenue: 0
    End timestamp: 1720617967 (2024-07-10T13:26:07.000Z)
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 12
    Total fees: 74.17 k
    Daily user fees: 12
    Daily revenue: 12
    Daily protocol revenue: 0
    Daily holders revenue: 12
    Daily supply side revenue: 0
    Total user fees: 74.17 k
    Total revenue: 74.17 k
    Total protocol revenue: 0
    Total supply side revenue: 0
    End timestamp: 1720617967 (2024-07-10T13:26:07.000Z)
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 3.34 k
    Total fees: 340.20 k
    Daily user fees: 3.34 k
    Daily revenue: 3.34 k
    Daily protocol revenue: 0
    Daily holders revenue: 3.34 k
    Daily supply side revenue: 0
    Total user fees: 340.20 k
    Total revenue: 340.20 k
    Total protocol revenue: 0
    Total supply side revenue: 0
    End timestamp: 1720617967 (2024-07-10T13:26:07.000Z)

**Comment by dtmkeng** [comment]
could you revert change yarn lock ?

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 09 Jul 2024 00:00:00 GMT
    End Date:	Wed, 10 Jul 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1720483200 (2024-07-09T00:00:00.000Z)
    Daily volume: 660.03 k
    Total volume: 1.70 B
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1720483200 (2024-07-09T00:00:00.000Z)
    Daily volume: 664.97 k
    Total volume: 499.85 M
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1720483200 (2024-07-09T00:00:00.000Z)
    Daily volume: 35.25 M
    Total volume: 1.77 B

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 09 Jul 2024 21:24:58 GMT
    End Date:	Wed, 10 Jul 2024 21:24:58 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 92
    Total fees: 469.62 k
    Daily user fees: 92
    Daily revenue: 92
    Daily protocol revenue: 0
    Daily holders revenue: 92
    Daily supply side revenue: 0
    Total user fees: 469.62 k
    Total revenue: 469.62 k
    Total protocol revenue: 0
    Total supply side revenue: 0
    End timestamp: 1720646697 (2024-07-10T21:24:57.000Z)
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 80
    Total fees: 74.23 k
    Daily user fees: 80
    Daily revenue: 80
    Daily protocol revenue: 0
    Daily holders revenue: 80
    Daily supply side revenue: 0
    Total user fees: 74.23 k
    Total revenue: 74.23 k
    Total protocol revenue: 0
    Total supply side revenue: 0
    End timestamp: 1720646697 (2024-07-10T21:24:57.000Z)
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 4.20 k
    Total fees: 341.06 k
    Daily user fees: 4.20 k
    Daily revenue: 4.20 k
    Daily protocol revenue: 0
    Daily holders revenue: 4.20 k
    Daily supply side revenue: 0
    Total user fees: 341.06 k
    Total revenue: 341.06 k
    Total protocol revenue: 0
    Total supply side revenue: 0
    End timestamp: 1720646697 (2024-07-10T21:24:57.000Z)

**Comment by lemonpac** [comment]
Addressed

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 09 Jul 2024 00:00:00 GMT
    End Date:	Wed, 10 Jul 2024 00:00:00 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1720483200 (2024-07-09T00:00:00.000Z)
    Daily volume: 660.03 k
    Total volume: 1.70 B
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1720483200 (2024-07-09T00:00:00.000Z)
    Daily volume: 664.97 k
    Total volume: 499.85 M
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1720483200 (2024-07-09T00:00:00.000Z)
    Daily volume: 35.25 M
    Total volume: 1.77 B

**Comment by llamatester** [comment]
The intent-x adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees intent-x
    
    🦙 Running INTENT-X adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 09 Jul 2024 21:25:28 GMT
    End Date:	Wed, 10 Jul 2024 21:25:28 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 92
    Total fees: 469.62 k
    Daily user fees: 92
    Daily revenue: 92
    Daily protocol revenue: 0
    Daily holders revenue: 92
    Daily supply side revenue: 0
    Total user fees: 469.62 k
    Total revenue: 469.62 k
    Total protocol revenue: 0
    Total supply side revenue: 0
    End timestamp: 1720646727 (2024-07-10T21:25:27.000Z)
    
    
    BLAST 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 80
    Total fees: 74.23 k
    Daily user fees: 80
    Daily revenue: 80
    Daily protocol revenue: 0
    Daily holders revenue: 80
    Daily supply side revenue: 0
    Total user fees: 74.23 k
    Total revenue: 74.23 k
    Total protocol revenue: 0
    Total supply side revenue: 0
    End timestamp: 1720646727 (2024-07-10T21:25:27.000Z)
    
    
    MANTLE 👇
    Backfill start time: 1/11/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 4.20 k
    Total fees: 341.06 k
    Daily user fees: 4.20 k
    Daily revenue: 4.20 k
    Daily protocol revenue: 0
    Daily holders revenue: 4.20 k
    Daily supply side revenue: 0
    Total user fees: 341.06 k
    Total revenue: 341.06 k
    Total protocol revenue: 0
    Total supply side revenue: 0
    End timestamp: 1720646727 (2024-07-10T21:25:27.000Z)

**Pull request merged**
