### PR TITLE
aerodrome volume / fees / bribes

### PR DESCRIPTION
**Pull request by ethzoomer**

### CODE REVIEW

**Comment by llamatester** [comment]
The aerodrome-slipstream adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs aerodrome-slipstream
    
    🦙 Running AERODROME-SLIPSTREAM adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 09 Dec 2024 23:01:27 GMT
    End Date:	Tue, 10 Dec 2024 23:01:27 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 3/5/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 1.46 B
    Daily fees: 1.02 M
    Daily revenue: 1.02 M
    Daily holders revenue: 1.02 M
    End timestamp: 1733871686 (2024-12-10T23:01:26.000Z)

**Comment by llamatester** [comment]
The aerodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs aerodrome
    
    🦙 Running AERODROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 09 Dec 2024 23:06:44 GMT
    End Date:	Tue, 10 Dec 2024 23:06:44 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 28/8/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Daily fees: 0
    Daily revenue: 0
    Daily holders revenue: 0
    End timestamp: 1733872003 (2024-12-10T23:06:43.000Z)

**Comment by llamatester** [comment]
The aerodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees aerodrome
    
    🦙 Running AERODROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 02:47:13 GMT
    End Date:	Wed, 11 Dec 2024 02:47:13 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 28/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bribes revenue: 639.74 k
    End timestamp: 1733885232 (2024-12-11T02:47:12.000Z)

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
sorry, cant approve this PR. I am bit confused what this PR is trying to achieve.

I think llamas have already tried reaching out to aerodrome team, good that you have put up this PR, current implementation is not scalable (even with our indexer), there are just too many events


Does your team maintain a graph or aggregator endpoint for pulling volume, fees & bribes data?

**Comment by g1nt0ki** [comment]
hi @ethzoomer the reason we are filtering out those pools is, with that many pools, the adapter just times out :(

**Comment by g1nt0ki** [comment]
ah, misread the comment, yes.

**Comment by g1nt0ki** [comment]
but do you think 1k or 10k makes much of a difference? volume wise

**Comment by g1nt0ki** [comment]
> The existing `master` branch code only works because the `helpers/uniswap.filterPools` is setting `maxPairSize` very low, aka only looking at a tiny number of pools, but this results in 40+% of the volume and fees missing
> 
> If I filter with `minUSDValue: 10000` and `maxPairSize: 500`, then the adapter takes 1700s to run instead of 9000+s. But I assume 1700s is still too much time? Is there a way for me to isolate it so that it only tries to run within the last 24hours of logs?

it already only pulls logs in last 24 hours, let me give it a try, it is bit faster for us as we pull logs from our own indexer

**Comment by llamatester** [comment]
The aerodrome-slipstream adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs aerodrome-slipstream
    
    🦙 Running AERODROME-SLIPSTREAM adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 19:10:02 GMT
    End Date:	Wed, 11 Dec 2024 19:10:02 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 3/5/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 536.65 M
    Daily fees: 609.40 k
    Daily revenue: 609.40 k
    Daily holders revenue: 609.40 k
    End timestamp: 1733944201 (2024-12-11T19:10:01.000Z)

**Comment by llamatester** [comment]
The aerodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs aerodrome
    
    🦙 Running AERODROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 19:15:33 GMT
    End Date:	Wed, 11 Dec 2024 19:15:33 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 28/8/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Daily fees: 0
    Daily revenue: 0
    Daily holders revenue: 0
    End timestamp: 1733944532 (2024-12-11T19:15:32.000Z)

**Comment by llamatester** [comment]
The aerodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees aerodrome
    
    🦙 Running AERODROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 19:39:55 GMT
    End Date:	Wed, 11 Dec 2024 19:39:55 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 28/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bribes revenue: 1.11 M
    End timestamp: 1733945994 (2024-12-11T19:39:54.000Z)

**Comment by llamatester** [comment]
The aerodrome-slipstream adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs aerodrome-slipstream
    
    🦙 Running AERODROME-SLIPSTREAM adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 22:12:22 GMT
    End Date:	Wed, 11 Dec 2024 22:12:22 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 3/5/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 553.90 M
    Daily fees: 587.16 k
    Daily revenue: 587.16 k
    Daily holders revenue: 587.16 k
    End timestamp: 1733955141 (2024-12-11T22:12:21.000Z)

**Comment by llamatester** [comment]
The aerodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs aerodrome
    
    🦙 Running AERODROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 22:17:22 GMT
    End Date:	Wed, 11 Dec 2024 22:17:22 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 28/8/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 44.88 M
    Daily fees: 173.06 k
    Daily revenue: 173.06 k
    Daily holders revenue: 173.06 k
    End timestamp: 1733955441 (2024-12-11T22:17:21.000Z)

**Comment by llamatester** [comment]
The aerodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees aerodrome
    
    🦙 Running AERODROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 22:42:33 GMT
    End Date:	Wed, 11 Dec 2024 22:42:33 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 28/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bribes revenue: 940.50 k
    End timestamp: 1733956952 (2024-12-11T22:42:32.000Z)

**Comment by llamabutler** [comment]
The aerodrome-slipstream adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs aerodrome-slipstream
    
    🦙 Running AERODROME-SLIPSTREAM adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 12 Dec 2024 12:36:46 GMT
    End Date:	Fri, 13 Dec 2024 12:36:46 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 3/5/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 600.93 M
    Daily fees: 650.73 k
    Daily revenue: 650.73 k
    Daily holders revenue: 650.73 k
    End timestamp: 1734093405 (2024-12-13T12:36:45.000Z)

**Comment by llamabutler** [comment]
The aerodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees aerodrome
    
    🦙 Running AERODROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 12 Dec 2024 13:01:38 GMT
    End Date:	Fri, 13 Dec 2024 13:01:38 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 28/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bribes revenue: 53.65 k
    End timestamp: 1734094897 (2024-12-13T13:01:37.000Z)

**Comment by llamabutler** [comment]
The aerodrome-slipstream adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs aerodrome-slipstream
    
    🦙 Running AERODROME-SLIPSTREAM adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 12 Dec 2024 17:15:05 GMT
    End Date:	Fri, 13 Dec 2024 17:15:05 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 3/5/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 1.15 B
    Daily fees: 797.45 k
    Daily revenue: 797.45 k
    Daily holders revenue: 797.45 k
    End timestamp: 1734110104 (2024-12-13T17:15:04.000Z)

**Comment by llamabutler** [comment]
The aerodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs aerodrome
    
    🦙 Running AERODROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 12 Dec 2024 17:18:18 GMT
    End Date:	Fri, 13 Dec 2024 17:18:18 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 28/8/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 54.29 M
    Daily fees: 210.82 k
    Daily revenue: 210.82 k
    Daily holders revenue: 210.82 k
    End timestamp: 1734110297 (2024-12-13T17:18:17.000Z)

**Comment by llamabutler** [comment]
The aerodrome adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees aerodrome
    
    🦙 Running AERODROME adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 12 Dec 2024 17:37:07 GMT
    End Date:	Fri, 13 Dec 2024 17:37:07 GMT
    ---------------------------------------------------
    
    BASE 👇
    Backfill start time: 28/8/2023
    NO METHODOLOGY SPECIFIED
    Daily bribes revenue: 245.13 k
    End timestamp: 1734111426 (2024-12-13T17:37:06.000Z)

**Comment by llamabutler** [comment]
The velodrome-v2 adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees velodrome-v2
    
    🦙 Running VELODROME-V2 adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 12 Dec 2024 17:41:56 GMT
    End Date:	Fri, 13 Dec 2024 17:41:56 GMT
    ---------------------------------------------------
    
    OPTIMISM 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily bribes revenue: 21.32 k
    End timestamp: 1734111715 (2024-12-13T17:41:55.000Z)
    
    
    MODE 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Daily revenue: 0
    Daily holders revenue: 0
    Daily bribes revenue: 0
    End timestamp: 1734111715 (2024-12-13T17:41:55.000Z)
    
    
    BOB 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    Daily fees: 41
    Daily revenue: 41
    Daily holders revenue: 41
    Daily bribes revenue: 0
    End timestamp: 1734111715 (2024-12-13T17:41:55.000Z)

**Pull request merged**
