### PR TITLE
Beamswap updated fees

### PR DESCRIPTION
**Pull request by flisko**
- Added graph dimensions
- Added methodologies
- Added V3 and Beamex to Volume
- Added Beamex to Fees

### CODE REVIEW

**Comment by llamatester** [comment]
The beamswap adapter exports: 
        
 
 _______________________________________
    Dexs for 30/12/2023
    _______________________________________
    
    Attempting with alternative query...
    Attempting with alternative query...
    Version -> CLASSIC
    ---------
    MOONBEAM 👇
    Backfill start time: 18/1/2022
    Timestamp: 1703980799
    Block: 5.20 M
    Total volume: 449.02 M
    Daily volume: 14.27 k
    Daily fees: 42.80052402290328
    └─ Methodology: A 0.30% of each swap is collected as trading fees
    Total fees: 1.35 M
    └─ Methodology: A 0.30% of each swap is collected as trading fees
    Daily user fees: 42.80052402290328
    └─ Methodology: User pays 0.30% fees on each swap.
    Total user fees: 1.35 M
    └─ Methodology: User pays 0.30% fees on each swap.
    Daily protocol revenue: 18.54689374325809
    └─ Methodology: Protocol receives 0.13% on each swap.
    Total protocol revenue: 583.72 k
    └─ Methodology: Protocol receives 0.13% on each swap.
    Daily supply side revenue: 24.253630279645193
    └─ Methodology: All user fees are distributed among LPs.
    Total supply side revenue: 763.33 k
    └─ Methodology: All user fees are distributed among LPs.
    Daily holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Total holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Daily revenue: 18.54689374325809
    └─ Methodology: Protocol receives 0.13% on each swap.
    Total revenue: 583.72 k
    └─ Methodology: Protocol receives 0.13% on each swap.
    
    
    Version -> STABLE-AMM
    ---------
    MOONBEAM 👇
    Backfill start time: 4/7/2022
    Timestamp: 1703980799
    Block: 5.20 M
    Total volume: 2.36 M
    Daily volume: 83.83 k
    Daily fees: 33.531728730853395
    └─ Methodology: A 0.04% of each swap is collected as trading fees
    Total fees: 943.2680398129534
    └─ Methodology: A 0.04% of each swap is collected as trading fees
    Daily user fees: 33.531728730853395
    └─ Methodology: User pays a 0.04% fee on each swap.
    Total user fees: 943.2680398129534
    └─ Methodology: User pays a 0.04% fee on each swap.
    Daily protocol revenue: 16.765864365426697
    └─ Methodology: Protocol receives 0.02% of the swap fee
    Total protocol revenue: 471.6340199064767
    └─ Methodology: Protocol receives 0.02% of the swap fee
    Daily supply side revenue: 16.765864365426697
    └─ Methodology: 0.02% of the swap fee is distributed to LPs
    Total supply side revenue: 471.6340199064767
    └─ Methodology: 0.02% of the swap fee is distributed to LPs
    Daily holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Total holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Daily revenue: 16.765864365426697
    └─ Methodology: Protocol receives 0.02% of the swap fee
    Total revenue: 471.6340199064767
    └─ Methodology: Protocol receives 0.02% of the swap fee
    
    
    Version -> V3
    ---------
    MOONBEAM 👇
    Backfill start time: 18/5/2023
    Timestamp: 1703980799
    Block: 5.20 M
    Total volume: 36.02 M
    Daily volume: 285.94 k
    Daily fees: 857.817348667103
    Total fees: 108.34 k
    Daily protocol revenue: 137.25077578673648
    └─ Methodology: Protocol receives 16% of fees.
    Total protocol revenue: 17.33 k
    └─ Methodology: Protocol receives 16% of fees.
    Daily holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Total holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Daily user fees: 857.817348667103
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Total user fees: 108.34 k
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Daily supply side revenue: 720.5665728803666
    └─ Methodology: 84% of user fees are distributed among LPs.
    Total supply side revenue: 91.01 k
    └─ Methodology: 84% of user fees are distributed among LPs.
    Daily revenue: 0
    Total revenue: 0
    
    
    Version -> BEAMEX-SWAP
    ---------
    MOONBEAM 👇
    Backfill start time: 22/6/2023
    Timestamp: 1703894400
    Daily volume: 103.11 k
    Total volume: 20.70 M
    
    
    Version -> BEAMEX-PERPS
    ---------
    MOONBEAM 👇
    Backfill start time: 22/6/2023
    Timestamp: 1703894400
    Daily volume: 0
    Total volume: 11.99 M
    
    
    Done in 4.08s.

**Comment by llamatester** [comment]
The beamex.ts adapter exports: 
        
 
 _______________________________________
    Fees for 30/12/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 22/6/2023
    Timestamp: 1703980798
    Daily fees: 283.7407340878256
    └─ Methodology: Fees from open/close position (0.1%), liquidations, swap (0.1% to 0.4%), mint and burn (based on tokens balance in the pool) and borrow fee ((assets borrowed)/(total assets in pool)*0.02%)
    Daily user fees: 283.56015876201394
    └─ Methodology: Fees from open/close position (0.1%), swap (0.1% to 0.4%) and borrow fee ((assets borrowed)/(total assets in pool)*0.04%)
    Daily revenue: 198.6185138614779
    └─ Methodology: 70% of all collected fees are distributed to the treasury
    Daily protocol revenue: 198.6185138614779
    └─ Methodology: 70% of all collected fees are distributed to the treasury
    Daily holders revenue: 85.12222022634768
    └─ Methodology: 30% of all collected fees are distributed to $stGLINT stakers
    Daily supply side revenue: 85.12222022634768
    └─ Methodology: 70% of all collected fees will be distributed to BLP stakers. Currently they are distributed to treasury
    
    
    
    
    Done in 2.58s.

**Comment by dtmkeng** [comment]
could you create new file v3 volume and BEAMEX volume ?

**Comment by llamatester** [comment]
The beamswap adapter exports: 
        
 
 _______________________________________
    Dexs for 31/12/2023
    _______________________________________
    
    Attempting with alternative query...
    Attempting with alternative query...
    Version -> CLASSIC
    ---------
    MOONBEAM 👇
    Backfill start time: 18/1/2022
    Timestamp: 1704067199
    Block: 5.20 M
    Total volume: 449.02 M
    Daily volume: 3.87 k
    Daily fees: 11.595955234212767
    └─ Methodology: A 0.30% of each swap is collected as trading fees
    Total fees: 1.35 M
    └─ Methodology: A 0.30% of each swap is collected as trading fees
    Daily user fees: 11.595955234212767
    └─ Methodology: User pays 0.30% fees on each swap.
    Total user fees: 1.35 M
    └─ Methodology: User pays 0.30% fees on each swap.
    Daily protocol revenue: 5.024913934825532
    └─ Methodology: Protocol receives 0.13% on each swap.
    Total protocol revenue: 583.72 k
    └─ Methodology: Protocol receives 0.13% on each swap.
    Daily supply side revenue: 6.571041299387234
    └─ Methodology: All user fees are distributed among LPs.
    Total supply side revenue: 763.33 k
    └─ Methodology: All user fees are distributed among LPs.
    Daily holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Total holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Daily revenue: 5.024913934825532
    └─ Methodology: Protocol receives 0.13% on each swap.
    Total revenue: 583.72 k
    └─ Methodology: Protocol receives 0.13% on each swap.
    
    
    Version -> STABLE-AMM
    ---------
    MOONBEAM 👇
    Backfill start time: 4/7/2022
    Timestamp: 1704067199
    Block: 5.20 M
    Total volume: 2.36 M
    Daily volume: 47.13 k
    Daily fees: 18.8523486270253
    └─ Methodology: A 0.04% of each swap is collected as trading fees
    Total fees: 943.2680398129534
    └─ Methodology: A 0.04% of each swap is collected as trading fees
    Daily user fees: 18.8523486270253
    └─ Methodology: User pays a 0.04% fee on each swap.
    Total user fees: 943.2680398129534
    └─ Methodology: User pays a 0.04% fee on each swap.
    Daily protocol revenue: 9.42617431351265
    └─ Methodology: Protocol receives 0.02% of the swap fee
    Total protocol revenue: 471.6340199064767
    └─ Methodology: Protocol receives 0.02% of the swap fee
    Daily supply side revenue: 9.42617431351265
    └─ Methodology: 0.02% of the swap fee is distributed to LPs
    Total supply side revenue: 471.6340199064767
    └─ Methodology: 0.02% of the swap fee is distributed to LPs
    Daily holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Total holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Daily revenue: 9.42617431351265
    └─ Methodology: Protocol receives 0.02% of the swap fee
    Total revenue: 471.6340199064767
    └─ Methodology: Protocol receives 0.02% of the swap fee
    
    
    Version -> V3
    ---------
    MOONBEAM 👇
    Backfill start time: 18/5/2023
    Timestamp: 1704067199
    Block: 5.20 M
    Total volume: 36.36 M
    Daily volume: 340.12 k
    Daily fees: 1.02 k
    Total fees: 109.44 k
    Daily protocol revenue: 163.2577827980622
    └─ Methodology: Protocol receives 16% of fees.
    Total protocol revenue: 17.51 k
    └─ Methodology: Protocol receives 16% of fees.
    Daily holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Total holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Daily user fees: 1.02 k
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Total user fees: 109.44 k
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Daily supply side revenue: 857.1033596898266
    └─ Methodology: 84% of user fees are distributed among LPs.
    Total supply side revenue: 91.93 k
    └─ Methodology: 84% of user fees are distributed among LPs.
    Daily revenue: 0
    Total revenue: 0
    
    
    Version -> BEAMEX-SWAP
    ---------
    MOONBEAM 👇
    Backfill start time: 22/6/2023
    Timestamp: 1703980800
    Daily volume: 221.49 k
    Total volume: 20.90 M
    
    
    Version -> BEAMEX-PERPS
    ---------
    MOONBEAM 👇
    Backfill start time: 22/6/2023
    Timestamp: 1703980800
    Daily volume: 14.66 k
    Total volume: 12.01 M
    
    
    Done in 5.18s.

**Comment by llamatester** [comment]
The beamex.ts adapter exports: 
        
 
 _______________________________________
    Fees for 31/12/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 22/6/2023
    Timestamp: 1704067198
    Daily fees: 669.3442439128162
    └─ Methodology: Fees from open/close position (0.1%), liquidations, swap (0.1% to 0.4%), mint and burn (based on tokens balance in the pool) and borrow fee ((assets borrowed)/(total assets in pool)*0.02%)
    Daily user fees: 664.7064937235481
    └─ Methodology: Fees from open/close position (0.1%), swap (0.1% to 0.4%) and borrow fee ((assets borrowed)/(total assets in pool)*0.04%)
    Daily revenue: 468.5409707389713
    └─ Methodology: 70% of all collected fees are distributed to the treasury
    Daily protocol revenue: 468.5409707389713
    └─ Methodology: 70% of all collected fees are distributed to the treasury
    Daily holders revenue: 200.80327317384484
    └─ Methodology: 30% of all collected fees are distributed to $stGLINT stakers
    Daily supply side revenue: 200.80327317384484
    └─ Methodology: 70% of all collected fees will be distributed to BLP stakers. Currently they are distributed to treasury
    
    
    
    
    Done in 2.59s.

**Comment by llamatester** [comment]
The beamswap adapter exports: 
        
 
 _______________________________________
    Dexs for 31/12/2023
    _______________________________________
    
    Attempting with alternative query...
    Attempting with alternative query...
    Version -> CLASSIC
    ---------
    MOONBEAM 👇
    Backfill start time: 18/1/2022
    Timestamp: 1704067199
    Block: 5.20 M
    Total volume: 449.02 M
    Daily volume: 3.87 k
    Daily fees: 11.595955234212767
    └─ Methodology: A 0.30% of each swap is collected as trading fees
    Total fees: 1.35 M
    └─ Methodology: A 0.30% of each swap is collected as trading fees
    Daily user fees: 11.595955234212767
    └─ Methodology: User pays 0.30% fees on each swap.
    Total user fees: 1.35 M
    └─ Methodology: User pays 0.30% fees on each swap.
    Daily protocol revenue: 5.024913934825532
    └─ Methodology: Protocol receives 0.13% on each swap.
    Total protocol revenue: 583.72 k
    └─ Methodology: Protocol receives 0.13% on each swap.
    Daily supply side revenue: 6.571041299387234
    └─ Methodology: All user fees are distributed among LPs.
    Total supply side revenue: 763.33 k
    └─ Methodology: All user fees are distributed among LPs.
    Daily holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Total holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Daily revenue: 5.024913934825532
    └─ Methodology: Protocol receives 0.13% on each swap.
    Total revenue: 583.72 k
    └─ Methodology: Protocol receives 0.13% on each swap.
    
    
    Version -> STABLE-AMM
    ---------
    MOONBEAM 👇
    Backfill start time: 4/7/2022
    Timestamp: 1704067199
    Block: 5.20 M
    Total volume: 2.36 M
    Daily volume: 47.13 k
    Daily fees: 18.8523486270253
    └─ Methodology: A 0.04% of each swap is collected as trading fees
    Total fees: 943.2680398129534
    └─ Methodology: A 0.04% of each swap is collected as trading fees
    Daily user fees: 18.8523486270253
    └─ Methodology: User pays a 0.04% fee on each swap.
    Total user fees: 943.2680398129534
    └─ Methodology: User pays a 0.04% fee on each swap.
    Daily protocol revenue: 9.42617431351265
    └─ Methodology: Protocol receives 0.02% of the swap fee
    Total protocol revenue: 471.6340199064767
    └─ Methodology: Protocol receives 0.02% of the swap fee
    Daily supply side revenue: 9.42617431351265
    └─ Methodology: 0.02% of the swap fee is distributed to LPs
    Total supply side revenue: 471.6340199064767
    └─ Methodology: 0.02% of the swap fee is distributed to LPs
    Daily holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Total holders revenue: 0
    └─ Methodology: Stakers received $GLINT in staking rewards.
    Daily revenue: 9.42617431351265
    └─ Methodology: Protocol receives 0.02% of the swap fee
    Total revenue: 471.6340199064767
    └─ Methodology: Protocol receives 0.02% of the swap fee
    
    
    Done in 4.51s.

**Comment by llamatester** [comment]
The beamex adapter exports: 
        
 
 _______________________________________
    Dexs for 31/12/2023
    _______________________________________
    
    Version -> BEAMEX-SWAP
    ---------
    MOONBEAM 👇
    Backfill start time: 22/6/2023
    Timestamp: 1703980800
    Daily volume: 221.49 k
    Total volume: 20.90 M
    
    
    Version -> BEAMEX-PERPS
    ---------
    MOONBEAM 👇
    Backfill start time: 22/6/2023
    Timestamp: 1703980800
    Daily volume: 14.66 k
    Total volume: 12.01 M
    
    
    Done in 2.73s.

**Comment by llamatester** [comment]
The beamswap-v3 adapter exports: 
        
 
 _______________________________________
    Dexs for 31/12/2023
    _______________________________________
    
    Version -> V3
    ---------
    MOONBEAM 👇
    Backfill start time: 18/5/2023
    Timestamp: 1704067199
    Block: 5.20 M
    Total volume: 36.36 M
    Daily volume: 340.12 k
    Daily fees: 1.02 k
    Total fees: 109.44 k
    Daily protocol revenue: 163.2577827980622
    └─ Methodology: Protocol receives 16% of fees.
    Total protocol revenue: 17.51 k
    └─ Methodology: Protocol receives 16% of fees.
    Daily holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Total holders revenue: 0
    └─ Methodology: Holders have no revenue.
    Daily user fees: 1.02 k
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Total user fees: 109.44 k
    └─ Methodology: User pays 0.01%, 0.05%, 0.3%, or 1% on each swap.
    Daily supply side revenue: 857.1033596898266
    └─ Methodology: 84% of user fees are distributed among LPs.
    Total supply side revenue: 91.93 k
    └─ Methodology: 84% of user fees are distributed among LPs.
    Daily revenue: 0
    Total revenue: 0
    
    
    Done in 4.02s.

**Comment by llamatester** [comment]
The beamex.ts adapter exports: 
        
 
 _______________________________________
    Fees for 31/12/2023
    _______________________________________
    
    BASE 👇
    Backfill start time: 22/6/2023
    Timestamp: 1704067198
    Daily fees: 669.3442439128162
    └─ Methodology: Fees from open/close position (0.1%), liquidations, swap (0.1% to 0.4%), mint and burn (based on tokens balance in the pool) and borrow fee ((assets borrowed)/(total assets in pool)*0.02%)
    Daily user fees: 664.7064937235481
    └─ Methodology: Fees from open/close position (0.1%), swap (0.1% to 0.4%) and borrow fee ((assets borrowed)/(total assets in pool)*0.04%)
    Daily revenue: 468.5409707389713
    └─ Methodology: 70% of all collected fees are distributed to the treasury
    Daily protocol revenue: 468.5409707389713
    └─ Methodology: 70% of all collected fees are distributed to the treasury
    Daily holders revenue: 200.80327317384484
    └─ Methodology: 30% of all collected fees are distributed to $stGLINT stakers
    Daily supply side revenue: 200.80327317384484
    └─ Methodology: 70% of all collected fees will be distributed to BLP stakers. Currently they are distributed to treasury
    
    
    
    
    Done in 2.71s.

**Comment by flisko** [comment]
@dtmkeng done

**Comment by dtmkeng** [comment]
thank you

**Pull request merged**
