### PR TITLE
Added new subgraphs for arbitrum mainnet

### PR DESCRIPTION
**Pull request by Tesla1010**

### CODE REVIEW

**Comment by llamatester** [comment]
The buffer adapter exports: 
        
 
 _______________________________________
    Fees for 22/6/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 1/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1687478398
    Daily fees: 930554708966662.745535
    Daily revenue: 930554708966662.745535
    
    
    
    
    Done in 4.11s.

**Comment by llamatester** [comment]
The buffer adapter exports: 
        
 
 _______________________________________
    Fees for 22/6/2023
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 1/6/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1687478398
    Daily fees: 6872.670252
    Daily revenue: 6872.670252
    
    
    
    
    Done in 4.82s.

**Comment by dtmkeng** [comment]
polygon is  deprecated?

**Comment by Tesla1010** [comment]
No it is not, data is inconsistent. Will add it in a couple of days

**Comment by dtmkeng** [comment]
> 

should i wait polygon or merge this pr first ?

**Comment by Tesla1010** [comment]
Merge this, will make another PR next week for polygon

**Pull request merged**
