### PR TITLE
feat: add solana chain for delta-trade

### PR DESCRIPTION
**Pull request by deep-path**

### CODE REVIEW

**Comment by llamatester** [comment]
The delta-trade adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs delta-trade
    
    🦙 Running DELTA-TRADE adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 23 Oct 2024 00:00:00 GMT
    End Date:	Thu, 24 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    NEAR 👇
    Backfill start time not defined
    NO METHODOLOGY SPECIFIED
    End timestamp: 1729728000 (2024-10-24T00:00:00.000Z)
    Daily volume: 22.84 k
    Total volume: 3.38 M
    
    
    SOLANA 👇
    Backfill start time: 24/10/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1729728000 (2024-10-24T00:00:00.000Z)
    Daily volume: 22.84 k
    Total volume: 3.38 M

**Comment by deep-path** [comment]
add solana chain

**Review by g1nt0ki — CHANGES_REQUESTED** [review]
this doesnt look right, value is duplicated

**Comment by g1nt0ki** [comment]
closing this as there was no response.

**Pull request closed without merging**
