### PR TITLE
add plunderswap volume

### PR DESCRIPTION
**Pull request by darthgus**
add plunderswap volume, similar to zilswap exchange.

### CODE REVIEW

**Comment by llamatester** [comment]
The plunderswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs plunderswap
    
    🦙 Running PLUNDERSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 07 Dec 2024 00:00:00 GMT
    End Date:	Sun, 08 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ZILLIQA 👇
    Backfill start time: 7/12/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 7.76 k
    End timestamp: 1733529600 (2024-12-07T00:00:00.000Z)

**Comment by darthgus** [comment]
Just a slight issue with the Zilliqa API from some restore of data, just awaiting that to be up, before I request this PR again.

**Comment by llamatester** [comment]
The plunderswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs plunderswap
    
    🦙 Running PLUNDERSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 09 Dec 2024 00:00:00 GMT
    End Date:	Tue, 10 Dec 2024 00:00:00 GMT
    ---------------------------------------------------

**Comment by llamatester** [comment]
The plunderswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs plunderswap
    
    🦙 Running PLUNDERSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 00:00:00 GMT
    End Date:	Wed, 11 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ZILLIQA 👇
    Backfill start time: 10/12/2024
    Daily volume: 8.32 k
    └─ Methodology: Volume of trades on Plunderswap at the start of the day (12:00:00 UTC) for the previous day
    End timestamp: 1733788800 (2024-12-10T00:00:00.000Z)

**Comment by llamatester** [comment]
The plunderswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs plunderswap
    
    🦙 Running PLUNDERSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 00:00:00 GMT
    End Date:	Wed, 11 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ZILLIQA 👇
    Backfill start time: 10/12/2024
    Daily volume: 8.32 k
    └─ Methodology: Volume of trades on Plunderswap at the start of the day (12:00:00 UTC) for the previous day
    End timestamp: 1733788800 (2024-12-10T00:00:00.000Z)

**Comment by llamatester** [comment]
The plunderswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs plunderswap
    
    🦙 Running PLUNDERSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 00:00:00 GMT
    End Date:	Wed, 11 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ZILLIQA 👇
    Backfill start time: 10/12/2024
    Daily volume: 8.32 k
    └─ Methodology: Volume of trades on Plunderswap at the start of the day (12:00:00 UTC) for the previous day
    End timestamp: 1733788800 (2024-12-10T00:00:00.000Z)

**Comment by darthgus** [comment]
hi [g1nt0ki](https://github.com/g1nt0ki) should be ready for review - thanks.

**Comment by dtmkeng** [comment]
@darthgus  why you delete .gitigonre file ?

**Comment by darthgus** [comment]
@dtmkeng i apologize, I thought I had added it into my commit

**Comment by dtmkeng** [comment]
yes create new one

**Pull request closed without merging**
