### PR TITLE
update elp2

### PR DESCRIPTION
**Pull request by ede-frank**
update elp2

### CODE REVIEW

**Comment by llamatester** [comment]
The ei-dorado-exchange.ts adapter exports: 
        
 
 _______________________________________
    Fees for 12/2/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 10/12/2022
    Methodology: All mint, burn, marginAndLiquidation and swap fees are collected and the daily fee amount is determined. Daily revenue is calculated as 30% of the total fee.
    Timestamp: 1676246398
    Daily user fees: 7227.58891977486
    Daily revenue: 2168.276675932458
    
    
    
    
    Done in 4.26s.

**Comment by dtmkeng** [comment]
hi, not sure file name should like this https://github.com/DefiLlama/dimension-adapters/blob/master/fees/el-dorado-exchange.ts
`el-dorado-exchange.ts` ?

**Comment by ede-frank** [comment]
> hi, not sure file name should like this https://github.com/DefiLlama/dimension-adapters/blob/master/fees/el-dorado-exchange.ts `el-dorado-exchange.ts` ?

Yes, the correct file name is `el-dorado-exchange.ts`

**Comment by llamatester** [comment]
The el-dorado-exchange.ts adapter exports: 
        
 
 _______________________________________
    Fees for 13/2/2023
    _______________________________________
    
    BSC 👇
    Backfill start time: 10/12/2022
    Timestamp: 1676332798
    Daily fees: 20057.208321978535
    └─ Methodology: All mint, burn, margin and liquidation and swap fees are collected
    Daily user fees: 19517.92637912508
    └─ Methodology: Users pay swap fees and margin and liquidation fees
    Daily revenue: 6017.16249659356
    └─ Methodology: Revenue is calculated as 30% of the total fee.
    
    
    
    
    Done in 4.54s.

**Comment by dtmkeng** [comment]
LG ty

**Pull request merged**
