### PR TITLE
add udex-agg

### PR DESCRIPTION
**Pull request by algtm**
##### Name (to be shown on DefiLlama):
UDEX

##### Twitter Link:
https://x.com/uDEX_one

##### Website Link:
https://app.udex.one/

##### Logo (High resolution, will be shown with rounded borders):
uDEX Logo

##### Chain:
ETH BSC POLYGON BASE

##### Short Description (to be shown on DefiLlama):
uDEX is a comprehensive decentralized perpetuals trading platform, offering high user convenience and a diverse range of trading options. It provides web-based trading services, along with unique trading capabilities through the [uDEX Telegram bot](https://t.me/u_dex_bot/udex) within the Telegram app. Users can start trading directly in their browser or on Telegram without needing to install any additional software.

uDEX supports peer-to-peer decentralized transactions, ensuring fairness and transparency in the market, and giving users complete control over their funds. The platform integrates price charts from centralized exchanges for real-time monitoring. In addition to supporting spot, limit, and margin trading, uDEX also offers a feature for sniping upcoming launches. It supports multiple chains, such as Ethereum, BNB, Polygon, and more.
##### Category (full list at https://defillama.com/categories) *Please choose only one:
Dexes

### CODE REVIEW

**Comment by llamatester** [comment]
The udex-agg adapter exports: 
        
 
 _______________________________________
    Aggregators for 31/5/2024
    _______________________________________
    
    Dune: Failed to fetch url https://api.dune.com/api/v1/query/3781797/results?api_key=
    Error: Dune: All API keys failed
        at retries (/home/runner/work/dimension-adapters/dimension-adapters/helpers/duneRequest.ts:36:16)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async _fetchURLWithRetry (/home/runner/work/dimension-adapters/dimension-adapters/helpers/duneRequest.ts:23:10)
        at async /home/runner/work/dimension-adapters/dimension-adapters/aggregators/udex-agg/index.ts:32:20
        at async /home/runner/work/dimension-adapters/dimension-adapters/helpers/customBackfill.ts:24:22
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:18)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'bsc'
    }
    Dune: Failed to fetch url https://api.dune.com/api/v1/query/3781797/results?api_key=
    Dune: Failed to fetch url https://api.dune.com/api/v1/query/3781797/results?api_key=
    Dune: Failed to fetch url https://api.dune.com/api/v1/query/3781797/results?api_key=

**Comment by algtm** [comment]
should i add api key in url?

**Comment by dtmkeng** [comment]
is there query id that faster ? seem current id it get all it consume more our dune credit ?

**Comment by dtmkeng** [comment]
seem you can use getLogs for calculate fees instead use dune

**Comment by llamatester** [comment]
The udex-agg adapter exports: 
        
 
 _______________________________________
    Aggregators for 2/6/2024
    _______________________________________
    
    BSC 👇
    Backfill start time: 24/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 34.55 k
    Timestamp: 1717337942 (2024-06-02T14:19:02.000Z)
    
    
    POLYGON 👇
    Backfill start time: 24/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 1
    Timestamp: 1717337942 (2024-06-02T14:19:02.000Z)
    
    
    ETHEREUM 👇
    Backfill start time: 24/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1717337942 (2024-06-02T14:19:02.000Z)
    
    
    BASE 👇
    Backfill start time: 24/12/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    Timestamp: 1717337942 (2024-06-02T14:19:02.000Z)

**Comment by algtm** [comment]
> seem you can use getLogs for calculate fees instead use dune

change to getlogs

**Pull request merged**
