### PR TITLE
Feat: Add `Base` (Coinbase) Network to `Sobal` for Fees & Dexs

### PR DESCRIPTION
**Pull request by joehquak**
Adding the `Base` network to `Sobal` DEX.

### CODE REVIEW

**Comment by llamatester** [comment]
The sobal adapter exports: 
        
 
 _______________________________________
    Dexs for 31/7/2023
    _______________________________________
    
    NEON_EVM 👇
    Backfill start time: 17/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690847998
    Block: 208702895
    Total volume: 10376.072837921529
    Daily volume: 1891.345595894114
    
    
    
    
    Done in 6.92s.

**Comment by llamatester** [comment]
The sobal.ts adapter exports: 
        
 
 _______________________________________
    Fees for 31/7/2023
    _______________________________________
    
    NEON_EVM 👇
    Backfill start time: 17/7/2023
    Timestamp: 1690847998
    Total user fees: 31.12821851376458442785917146410162
    └─ Methodology: Trading fees paid by users, ranging from 0.0001% to 10%
    Daily user fees: 5.67403678768234264667349025682789
    └─ Methodology: Trading fees paid by users, ranging from 0.0001% to 10%
    Total fees: 31.12821851376458442785917146410162
    └─ Methodology: All trading fees collected (doesn't include withdrawal and flash loan fees)
    Daily fees: 5.67403678768234264667349025682789
    └─ Methodology: All trading fees collected (doesn't include withdrawal and flash loan fees)
    Total revenue: 15.56410925688229221392958573205081
    └─ Methodology: Protocol revenue from all fees collected
    Daily revenue: 2.837018393841171323336745128413945
    └─ Methodology: Protocol revenue from all fees collected
    Total protocol revenue: 15.56410925688229221392958573205081
    └─ Methodology: Currently no protocol swap fee in place
    Daily protocol revenue: 2.837018393841171323336745128413945
    └─ Methodology: Currently no protocol swap fee in place
    Total supply side revenue: 15.56410925688229221392958573205081
    └─ Methodology: A small percentage of the trade paid by traders to pool LPs, set by the pool creator or managed by protocol.
    Daily supply side revenue: 2.837018393841171323336745128413945
    └─ Methodology: A small percentage of the trade paid by traders to pool LPs, set by the pool creator or managed by protocol.
    
    
    
    
    Done in 5.06s.

**Comment by joehquak** [comment]
Info missing while subgraph is building data, this is expected

**Comment by dtmkeng** [comment]
> Info missing while subgraph is building data, this is expected

start is 1 aug could you set start time 29/07 it can run get info

**Comment by joehquak** [comment]
@dtmkeng I tried but it fails because the data doesn't exist for the range it's trying to get data from

```Cannot read property 'totalSwapFee' of null```

I'll just wait until the data is within a timeframe that can be tested

**Comment by dtmkeng** [comment]
> @dtmkeng I tried but it fails because the data doesn't exist for the range it's trying to get data from
> 
> `Cannot read property 'totalSwapFee' of null`
> 
> I'll just wait until the data is within a timeframe that can be tested

seem base the graph out of sync block could you check sync % of the graph

**Comment by joehquak** [comment]
I set the subgraph to start from `2029566` because that's when we deployed the `Vault` contract

**Comment by dtmkeng** [comment]
> I set the subgraph to start from `2029566` because that's when we deployed the `Vault` contract
> 
> The TX is only maybe 13 hours old
> 
> https://basescan.org/block/2029566

yeah adapter run get data yesterday 31/07 then it error block range

**Comment by llamatester** [comment]
The sobal adapter exports: 
        
 
 _______________________________________
    Dexs for 1/8/2023
    _______________________________________
    
    NEON_EVM 👇
    Backfill start time: 17/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690934398
    Block: 208899162
    Total volume: 11445.303671633874
    Daily volume: 1069.230833712345
    
    
    
    
    Done in 5.33s.

**Comment by llamatester** [comment]
The sobal.ts adapter exports: 
        
 
 _______________________________________
    Fees for 1/8/2023
    _______________________________________
    
    NEON_EVM 👇
    Backfill start time: 17/7/2023
    Timestamp: 1690934398
    Total user fees: 34.3359110149016222196600761508332
    └─ Methodology: Trading fees paid by users, ranging from 0.0001% to 10%
    Daily user fees: 3.20769250113703779180090468673158
    └─ Methodology: Trading fees paid by users, ranging from 0.0001% to 10%
    Total fees: 34.3359110149016222196600761508332
    └─ Methodology: All trading fees collected (doesn't include withdrawal and flash loan fees)
    Daily fees: 3.20769250113703779180090468673158
    └─ Methodology: All trading fees collected (doesn't include withdrawal and flash loan fees)
    Total revenue: 17.1679555074508111098300380754166
    └─ Methodology: Protocol revenue from all fees collected
    Daily revenue: 1.60384625056851889590045234336579
    └─ Methodology: Protocol revenue from all fees collected
    Total protocol revenue: 17.1679555074508111098300380754166
    └─ Methodology: Currently no protocol swap fee in place
    Daily protocol revenue: 1.60384625056851889590045234336579
    └─ Methodology: Currently no protocol swap fee in place
    Total supply side revenue: 17.1679555074508111098300380754166
    └─ Methodology: A small percentage of the trade paid by traders to pool LPs, set by the pool creator or managed by protocol.
    Daily supply side revenue: 1.60384625056851889590045234336579
    └─ Methodology: A small percentage of the trade paid by traders to pool LPs, set by the pool creator or managed by protocol.
    
    
    
    
    Done in 3.51s.

**Comment by llamatester** [comment]
The sobal adapter exports: 
        
 
 _______________________________________
    Dexs for 1/8/2023
    _______________________________________
    
    NEON_EVM 👇
    Backfill start time: 17/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1690934398
    Block: 208899162
    Total volume: 11445.303671633874
    Daily volume: 1069.230833712345
    
    
    
    
    Done in 5.11s.

**Comment by llamatester** [comment]
The sobal.ts adapter exports: 
        
 
 _______________________________________
    Fees for 1/8/2023
    _______________________________________
    
    NEON_EVM 👇
    Backfill start time: 17/7/2023
    Timestamp: 1690934398
    Total user fees: 34.3359110149016222196600761508332
    └─ Methodology: Trading fees paid by users, ranging from 0.0001% to 10%
    Daily user fees: 3.20769250113703779180090468673158
    └─ Methodology: Trading fees paid by users, ranging from 0.0001% to 10%
    Total fees: 34.3359110149016222196600761508332
    └─ Methodology: All trading fees collected (doesn't include withdrawal and flash loan fees)
    Daily fees: 3.20769250113703779180090468673158
    └─ Methodology: All trading fees collected (doesn't include withdrawal and flash loan fees)
    Total revenue: 17.1679555074508111098300380754166
    └─ Methodology: Protocol revenue from all fees collected
    Daily revenue: 1.60384625056851889590045234336579
    └─ Methodology: Protocol revenue from all fees collected
    Total protocol revenue: 17.1679555074508111098300380754166
    └─ Methodology: Currently no protocol swap fee in place
    Daily protocol revenue: 1.60384625056851889590045234336579
    └─ Methodology: Currently no protocol swap fee in place
    Total supply side revenue: 17.1679555074508111098300380754166
    └─ Methodology: A small percentage of the trade paid by traders to pool LPs, set by the pool creator or managed by protocol.
    Daily supply side revenue: 1.60384625056851889590045234336579
    └─ Methodology: A small percentage of the trade paid by traders to pool LPs, set by the pool creator or managed by protocol.
    
    
    
    
    Done in 3.75s.

**Comment by llamatester** [comment]
The sobal.ts adapter exports: 
        
 
 _______________________________________
    Fees for 2/8/2023
    _______________________________________
    
    NEON_EVM 👇
    Backfill start time: 17/7/2023
    Timestamp: 1691020798
    Total user fees: 36.41772415831726632485962200938867
    └─ Methodology: Trading fees paid by users, ranging from 0.0001% to 10%
    Daily user fees: 2.08181314341564410519954585855547
    └─ Methodology: Trading fees paid by users, ranging from 0.0001% to 10%
    Total fees: 36.41772415831726632485962200938867
    └─ Methodology: All trading fees collected (doesn't include withdrawal and flash loan fees)
    Daily fees: 2.08181314341564410519954585855547
    └─ Methodology: All trading fees collected (doesn't include withdrawal and flash loan fees)
    Total revenue: 18.208862079158633162429811004694335
    └─ Methodology: Protocol revenue from all fees collected
    Daily revenue: 1.040906571707822052599772929277735
    └─ Methodology: Protocol revenue from all fees collected
    Total protocol revenue: 18.208862079158633162429811004694335
    └─ Methodology: Currently no protocol swap fee in place
    Daily protocol revenue: 1.040906571707822052599772929277735
    └─ Methodology: Currently no protocol swap fee in place
    Total supply side revenue: 18.208862079158633162429811004694335
    └─ Methodology: A small percentage of the trade paid by traders to pool LPs, set by the pool creator or managed by protocol.
    Daily supply side revenue: 1.040906571707822052599772929277735
    └─ Methodology: A small percentage of the trade paid by traders to pool LPs, set by the pool creator or managed by protocol.
    
    
    BASE 👇
    Backfill start time: 1/8/2023
    Timestamp: 1691020798
    Total user fees: 0
    └─ Methodology: Trading fees paid by users, ranging from 0.0001% to 10%
    Daily user fees: 0
    └─ Methodology: Trading fees paid by users, ranging from 0.0001% to 10%
    Total fees: 0
    └─ Methodology: All trading fees collected (doesn't include withdrawal and flash loan fees)
    Daily fees: 0
    └─ Methodology: All trading fees collected (doesn't include withdrawal and flash loan fees)
    Total revenue: 0
    └─ Methodology: Protocol revenue from all fees collected
    Daily revenue: 0
    └─ Methodology: Protocol revenue from all fees collected
    Total protocol revenue: 0
    └─ Methodology: Currently no protocol swap fee in place
    Daily protocol revenue: 0
    └─ Methodology: Currently no protocol swap fee in place
    Total supply side revenue: 0
    └─ Methodology: A small percentage of the trade paid by traders to pool LPs, set by the pool creator or managed by protocol.
    Daily supply side revenue: 0
    └─ Methodology: A small percentage of the trade paid by traders to pool LPs, set by the pool creator or managed by protocol.
    
    
    
    
    Done in 4.11s.

**Comment by joehquak** [comment]
All ready @dtmkeng 👍

**Comment by mrkts16** [comment]
Joeh ***@***.***>, 1 Ağu 2023 Sal, 05:38 tarihinde şunu yazdı:

**Pull request merged**
