### PR TITLE
Added liquidity hub volume in QuickSwap's stats

### PR DESCRIPTION
**Pull request by sameepsi**

### CODE REVIEW

**Comment by llamatester** [comment]
The quickswap adapter exports: 
        
 
 _______________________________________
    Dexs for 6/11/2023
    _______________________________________
    
    Version -> V2
    ---------
    POLYGON 👇
    Backfill start time: 8/10/2020
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699315199
    Block: 49632123
    Total volume: 49515148282.59302
    Daily volume: 3170736.5158688748545586871687735
    
    
    Version -> V3
    ---------
    POLYGON 👇
    Backfill start time: 6/9/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699315199
    Block: 49632123
    Total volume: 8808565222.922821
    Daily volume: 33958686.16514146661108949744724077
    
    
    POLYGON_ZKEVM 👇
    Backfill start time: 27/3/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1699315199
    Block: 7130618
    Total volume: 147567891.24899378
    Daily volume: 816085.0778164584255806057155090609
    
    
    Version -> LIQUIDITYHUB
    ---------
    POLYGON 👇
    Backfill start time: 18/9/2023
    NO METHODOLOGY SPECIFIED
    Daily volume: 8846.816495784242
    Total volume: 4656516.786348076
    Timestamp: 1699228800
    
    
    Done in 5.08s.

**Comment by dtmkeng** [comment]
`LIQUIDITYHUB` it is spot volume or perp volume ?

**Comment by sameepsi** [comment]
> `LIQUIDITYHUB` it is spot volume or perp volume ?

Its a spot volume

**Comment by dtmkeng** [comment]
> > `LIQUIDITYHUB` it is spot volume or perp volume ?
> 
> Its a spot volume

is there tvl adapter already ?

**Comment by sameepsi** [comment]
> > > `LIQUIDITYHUB` it is spot volume or perp volume ?
> > 
> > 
> > Its a spot volume
> 
> is there tvl adapter already ?

Yes, here is the github link
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/quickswap-v3/index.js

**Comment by dtmkeng** [comment]
> > > > `LIQUIDITYHUB` it is spot volume or perp volume ?
> > > 
> > > 
> > > Its a spot volume
> > 
> > 
> > is there tvl adapter already ?
> 
> Yes, here is the github link https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/quickswap-v3/index.js

oh sorry i mean this volume `LIQUIDITYHUB` should list under which product ?
image

**Comment by sameepsi** [comment]
> > > > > `LIQUIDITYHUB` it is spot volume or perp volume ?
> > > > 
> > > > 
> > > > Its a spot volume
> > > 
> > > 
> > > is there tvl adapter already ?
> > 
> > 
> > Yes, here is the github link https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/quickswap-v3/index.js
> 
> oh sorry i mean this volume `LIQUIDITYHUB` should list under which product ? image

It has to be put under QuickSwap DEX on Polygon. It is more like a CLOB/RFQ based system.

**Comment by dtmkeng** [comment]
hmm i can not list same chain more breakdown if you need list volume under `QuickSwap DEX` you should sum volume with v2 on polygon instead new breakdown

**Comment by sameepsi** [comment]
> hmm i can not list same chain more breakdown if you need list volume under `QuickSwap DEX` you should sum volume with v2 on polygon instead new breakdown

Ahh now I get your question. It has to be new tab like QuickSwap V3. There is no TVL like section for liquidity hub because its like CLOB/RFQ system. Does that make sense now?

**Comment by dtmkeng** [comment]
okay

**Comment by sameepsi** [comment]
Thanks for merging it

**Pull request merged**
