### PR TITLE
Updated Rubicon Volume Adapter

### PR DESCRIPTION
**Pull request by bghughes**
Hey dev/admin - **I need a bit of help. How can I marry my two adapters? We have the old one, which was working, but cuts off around January 2 of this year, then I would like to transition our volume to the new one while keeping all the data from the old one in one continuous stream. Can you please provide guidance?**

This is incomplete in my mind and I wanted to ask to see if you had guidance on how to do this. Sorry if I am missing something and thank you in advance 🙏

### CODE REVIEW

**Comment by dtmkeng** [comment]
are you change tvl adapter ? if you and new chain it run collect with old adapter name

**Comment by bghughes** [comment]
> are you change tvl adapter ? if you and new chain it run collect with old adapter name

No this is only for volume - please see my diff. Volume I want is already there from inception -> January 1, now I want it to transition at that date to the new adapter I have in this file as `adapterNew` 😄

**Comment by dtmkeng** [comment]
you need to refill data with new the graph ?

**Comment by bghughes** [comment]
> you need to refill data with new the graph ?

I'm asking how I can combine them.

This snippet has the data until January 1st of this year: https://github.com/DefiLlama/dimension-adapters/blob/519802f89241152d1bf83c8d41072f37098705df/dexs/rubicon/index.ts#L6

This snippet has the data FROM January 1st to present and into the future: https://github.com/DefiLlama/dimension-adapters/blob/519802f89241152d1bf83c8d41072f37098705df/dexs/rubicon/index.ts#L21

**How do I combine them into one adapter?** 😄

**Comment by dtmkeng** [comment]
> > you need to refill data with new the graph ?
> 
> I'm asking how I can combine them.
> 
> This snippet has the data until January 1st of this year:
> 
> https://github.com/DefiLlama/dimension-adapters/blob/519802f89241152d1bf83c8d41072f37098705df/dexs/rubicon/index.ts#L6
> 
> This snippet has the data FROM January 1st to present and into the future:
> 
> https://github.com/DefiLlama/dimension-adapters/blob/519802f89241152d1bf83c8d41072f37098705df/dexs/rubicon/index.ts#L21
> 
> **How do I combine them into one adapter?** 😄

you should modify code set check if data have two souse will sum two source,

**Comment by bghughes** [comment]
> > > you need to refill data with new the graph ?
> > 
> > 
> > I'm asking how I can combine them.
> > This snippet has the data until January 1st of this year:
> > https://github.com/DefiLlama/dimension-adapters/blob/519802f89241152d1bf83c8d41072f37098705df/dexs/rubicon/index.ts#L6
> > 
> > This snippet has the data FROM January 1st to present and into the future:
> > https://github.com/DefiLlama/dimension-adapters/blob/519802f89241152d1bf83c8d41072f37098705df/dexs/rubicon/index.ts#L21
> > 
> > **How do I combine them into one adapter?** 😄
> 
> you should modify code set check if data have two souse will sum two source,

Thank you - have figured it out. Just need to get our data straight now that the Graph has deprecated the Hosted Service. **I will ping when we are ready, thank you for your help** ❤️

**Comment by bghughes** [comment]
Hey @dtmkeng this is ready to go! Please review and let me know what we can do to help. Thank you 🙏

**Comment by bghughes** [comment]
Hey @dtmkeng - noticing something weird in production where only a small amount of the new data is coming through in production despite it working locally... does it take a while for the production data to sync or is something wrong? 😄

**Comment by dtmkeng** [comment]
which date ?

**Comment by dtmkeng** [comment]
image
image

**Comment by dtmkeng** [comment]
adapter it return 5k on arb

**Comment by bghughes** [comment]
> image image

Thank you. I believe the issue is the historical data. **We've done $40mm+ in volume on Optimism from January 1 of this year to present and that is not showing up in the chart. So it's the historical stuff from this year that I believe is the issue** 😄

**Comment by bghughes** [comment]
Maybe I need to do something with `backfill`?

**Comment by bghughes** [comment]
Trying to fix this with #1631

**Pull request merged**
