### PR TITLE
feat/teleswap-volume

### PR DESCRIPTION
**Pull request by MahyarDaneshpajooh**
teleswap defillama tvl: https://defillama.com/protocol/teleswap

### CODE REVIEW

**Comment by llamatester** [comment]
The teleswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts protocols teleswap
    
    🦙 Running TELESWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 25 Nov 2024 00:00:00 GMT
    End Date:	Tue, 26 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Balances { chain: 'bob', timestamp: undefined, _balances: {} }
    Balances {
      chain: 'polygon',
      timestamp: undefined,
      _balances: {
        'coingecko:dog-go-to-the-moon-rune': 832286.4251700001,
        'coingecko:bitcoin': 0.00021289
      }
    }
    Balances { chain: 'bsquared', timestamp: undefined, _balances: {} }
    Balances { chain: 'bsc', timestamp: undefined, _balances: {} }
    POLYGON 👇
    Backfill start time: 26/11/2023
    End timestamp: 1732579199 (2024-11-25T23:59:59.000Z)
    Daily volume: 5.79 k
    
    
    BSC 👇
    Backfill start time: 3/12/2023
    End timestamp: 1732579199 (2024-11-25T23:59:59.000Z)
    Daily volume: 0
    
    
    BOB 👇
    Backfill start time: 23/7/2024
    End timestamp: 1732579199 (2024-11-25T23:59:59.000Z)
    Daily volume: 0
    
    
    BSQUARED 👇
    Backfill start time: 3/7/2024
    End timestamp: 1732579199 (2024-11-25T23:59:59.000Z)
    Daily volume: 0

**Comment by dtmkeng** [comment]
is it bridge volume ?

**Comment by MahyarDaneshpajooh** [comment]
yes, bridge volume (wrap&unwrap volume of btc, brc-20 tokens, rune tokens) @dtmkeng

**Comment by dtmkeng** [comment]
> yes, bridge volume (wrap&unwrap volume of btc, brc-20 tokens, rune tokens) @dtmkeng

i think should list at https://github.com/DefiLlama/bridges-server

**Comment by g1nt0ki** [comment]
@vrtnd

**Comment by g1nt0ki** [comment]
@MahyarDaneshpajooh sorry, @dtmkeng is correct, closing this PR

**Pull request closed without merging**
