### PR TITLE
feat: add core and taiko chains on eisen

### PR DESCRIPTION
**Pull request by climberNeedEquipment**

### CODE REVIEW

**Comment by llamatester** [comment]
The eisen adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators eisen
    
    🦙 Running EISEN adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 07 Oct 2024 03:23:58 GMT
    End Date:	Tue, 08 Oct 2024 03:23:58 GMT
    ---------------------------------------------------
    
    error fetching block TypeError: Cannot read properties of null (reading 'getBlock')
        at _getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:84:59)
        at getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:76:22)
        at _lookupBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:204:44)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:155:26
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:31
        at run (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:43)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:45:20
        at runNextTicks (node:internal/process/task_queues:60:5)
        at listOnTimeout (node:internal/timers:538:9)
        at processTimers (node:internal/timers:512:7)
    error fetching blockbitlayer Error getting block: bitlayer 1728271437 Request failed with status code 400
    error fetching block TypeError: Cannot read properties of null (reading 'getBlock')
        at _getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:84:59)
        at getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:76:22)
        at _lookupBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:204:44)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:155:26
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:31
        at run (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:43)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:45:20
        at runNextTicks (node:internal/process/task_queues:60:5)
        at listOnTimeout (node:internal/timers:538:9)
        at processTimers (node:internal/timers:512:7)
    error fetching blockbitlayer Error getting block: bitlayer 1728357837 Request failed with status code 400
    Error: fromBlock or fromTimestamp is required
        at getLogs (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/logs.js:35:15)
        at getLogs (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:107:26)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async fetch (/home/runner/work/dimension-adapters/dimension-adapters/aggregators/eisen/index.ts:40:16)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:51:18)
        at async Promise.all (index 4)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:27:20)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'bitlayer'
    }

**Comment by llamatester** [comment]
The eisen adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators eisen
    
    🦙 Running EISEN adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 07 Oct 2024 03:50:46 GMT
    End Date:	Tue, 08 Oct 2024 03:50:46 GMT
    ---------------------------------------------------
    
    error fetching block TypeError: Cannot read properties of null (reading 'getBlock')
        at _getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:84:59)
        at getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:76:22)
        at _lookupBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:204:44)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:155:26
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:31
        at run (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:43)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:45:20
        at runNextTicks (node:internal/process/task_queues:60:5)
        at listOnTimeout (node:internal/timers:538:9)
        at processTimers (node:internal/timers:512:7)
    error fetching blockbitlayer Error getting block: bitlayer 1728273045 Request failed with status code 400
    error fetching block TypeError: Cannot read properties of null (reading 'getBlock')
        at _getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:84:59)
        at getCurrentChainBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:76:22)
        at _lookupBlock (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:204:44)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/blocks.js:155:26
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:31
        at run (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:23:43)
        at /home/runner/work/dimension-adapters/dimension-adapters/node_modules/p-limit/index.js:45:20
        at runNextTicks (node:internal/process/task_queues:60:5)
        at listOnTimeout (node:internal/timers:538:9)
        at processTimers (node:internal/timers:512:7)
    error fetching blockbitlayer Error getting block: bitlayer 1728359445 Request failed with status code 400
    Error: fromBlock or fromTimestamp is required
        at getLogs (/home/runner/work/dimension-adapters/dimension-adapters/node_modules/@defillama/sdk/build/util/logs.js:35:15)
        at getLogs (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:107:26)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async fetch (/home/runner/work/dimension-adapters/dimension-adapters/aggregators/eisen/index.ts:42:16)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:51:18)
        at async Promise.all (index 4)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:27:20)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'bitlayer'
    }

**Comment by g1nt0ki** [comment]
thanks for the PR

**Comment by llamatester** [comment]
The eisen adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators eisen
    
    🦙 Running EISEN adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 07 Oct 2024 10:35:36 GMT
    End Date:	Tue, 08 Oct 2024 10:35:36 GMT
    ---------------------------------------------------
    
    MODE 👇
    Backfill start time: 1/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1728383735 (2024-10-08T10:35:35.000Z)
    
    
    SCROLL 👇
    Backfill start time: 1/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 641.33 k
    End timestamp: 1728383735 (2024-10-08T10:35:35.000Z)
    
    
    MANTLE 👇
    Backfill start time: 1/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 711
    End timestamp: 1728383735 (2024-10-08T10:35:35.000Z)
    
    
    BLAST 👇
    Backfill start time: 1/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1728383735 (2024-10-08T10:35:35.000Z)
    
    
    LINEA 👇
    Backfill start time: 1/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 1.32 k
    End timestamp: 1728383735 (2024-10-08T10:35:35.000Z)
    
    
    CRONOS 👇
    Backfill start time: 1/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1728383735 (2024-10-08T10:35:35.000Z)
    
    
    CORE 👇
    Backfill start time: 1/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 1
    End timestamp: 1728383735 (2024-10-08T10:35:35.000Z)
    
    
    TAIKO 👇
    Backfill start time: 1/1/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 0
    End timestamp: 1728383735 (2024-10-08T10:35:35.000Z)

**Pull request merged**
