### PR TITLE
Add chains

### PR DESCRIPTION
**Pull request by Plexus-Olivia**
Checked https://defillama.com/fees/plexus .
Add more chains and upload them.

Thank you.

### CODE REVIEW

**Comment by llamatester** [comment]
The plexus.ts adapter exports: 
        
 
 _______________________________________
    Fees for 30/3/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 1/2/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1680220798
    Daily fees: 0
    
    
    BSC 👇
    Backfill start time: 1/2/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1680220798
    Daily fees: 1.1087679460009237
    
    
    POLYGON 👇
    Backfill start time: 1/2/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1680220798
    Daily fees: 100.2067499395451
    
    
    FANTOM 👇
    Backfill start time: 1/2/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1680220798
    Daily fees: 0.9424747958554365
    
    
    KAVA 👇
    Backfill start time: 1/2/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1680220798
    Daily fees: 0
    
    
    ARBITRUM 👇
    Backfill start time: 1/2/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1680220798
    Daily fees: 0
    
    
    AVAX 👇
    Backfill start time: 1/2/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1680220798
    Daily fees: 0
    
    
    OPTIMISM 👇
    Backfill start time: 1/2/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1680220798
    Daily fees: 0
    
    
    KLAYTN 👇
    Backfill start time: 1/2/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1680220798
    Daily fees: 0
    
    
    AURORA 👇
    Backfill start time: 1/2/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1680220798
    Daily fees: 0
    
    
    
    
    Done in 5.09s.

**Comment by Plexus-Olivia** [comment]
Can you put our project(plexus) in every  chain(ethereum, bsc, polygon … )  on https://defillama.com/chain TVL Ranking?

**Comment by dtmkeng** [comment]
> Can you put our project(plexus) in every chain(ethereum, bsc, polygon … ) on https://defillama.com/chain TVL Ranking? Thank you :)

do you have a contract address for locking your user money?

**Comment by Plexus-Olivia** [comment]
There is also a project that is Tvl 0, can you add us to the category?

**Comment by Define101** [comment]
Hello Plexus-Olivia
That would not be possible.
In order to show under the TVL adapter you need to have TVL.
So there are a few protocols with 0 TVL, however when they launch they had TVL.
After taking a look at Plexus seem to be a Cross Chain protocol. If you guys can make a TVL adapter would be great
https://defillama.com/protocols/Cross%20Chain
https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects

**Comment by Plexus-Olivia** [comment]
Okay. Thank you for your reply.

**Comment by HIprotocoltony** [comment]
Hello DefiLlama Dev team! My name is Tony, the PLEXUS founder. We aggregate DEX and Bridge with our cross-chain aggregator service. Usually, if there is a DEX aggregator in the chain, it is processed by integrating the aggregator, but in the case of Kava, there is no DEX aggregator, so we developed the DEX aggregator part. So we can see it as a project that is heavily attributed to Kava. DefiLlama's TVL sector serves to show the TVL of projects in the chain, but on the other hand, it is also a space that shows which projects in the chain exist. As we were developing Kava this time, there was a request for the condition that Kava supports Grant to be shown as a project belonging to Kava through listing in the sector. 1inch is an aggregator, but as we see it as a project owned by Etherum, please consider putting it in the Kava TVL sector as a Kava owned project.

**Comment by HIprotocoltony** [comment]
image
We are a cross-chain aggregator service like Rubic
!

**Comment by g1nt0ki** [comment]
> Hello DefiLlama Dev team! My name is Tony, the PLEXUS founder. We aggregate DEX and Bridge with our cross-chain aggregator service. Usually, if there is a DEX aggregator in the chain, it is processed by integrating the aggregator, but in the case of Kava, there is no DEX aggregator, so we developed the DEX aggregator part. So we can see it as a project that is heavily attributed to Kava. DefiLlama's TVL sector serves to show the TVL of projects in the chain, but on the other hand, it is also a space that shows which projects in the chain exist. As we were developing Kava this time, there was a request for the condition that Kava supports Grant to be shown as a project belonging to Kava through listing in the sector. 1inch is an aggregator, but as we see it as a project owned by Etherum, please consider putting it in the Kava TVL sector as a Kava owned project.

Hi Tony, 1inch has their own contracts with tokens locked in ethereum and bsc, rubic used to be the same, now they have moved to a different model (https://defillama.com/protocol/rubic), but if you enable staking filter, rubic would show tvl value.


You are making a strong case for the grant, my two cents is kava should be more flexible in this case, clearly you are providing a valuable service on their chain.

**Comment by HIprotocoltony** [comment]
Hello. Greetings after a long time. We have deployed a DEX aggregator on Kava. Can you include our project in that sector as well? https://defillama.com/dexs/chains/kava thank you

**Comment by HIprotocoltony** [comment]
@Define101 @llamatester @dtmkeng

**Comment by dtmkeng** [comment]
@HIprotocoltony do you have, url or sugraph for get volume data ?

**Pull request merged**
