### PR TITLE
Remove fee data for VEAX and Concordex

### PR DESCRIPTION
**Pull request by vladjito**
Hi, our team wants to remove fee data because we are the only projects on chain who shows it

### CODE REVIEW

**Comment by llamatester** [comment]
The concordex-io adapter exports: 
        
 
 _______________________________________
    Dexs for 18/10/2023
    _______________________________________
    
    CONCORDIUM 👇
    Backfill start time: 1/7/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1697673598
    Daily volume: 5994.49
    Total volume: 660915.22
    
    
    
    
    Done in 3.91s.

**Comment by llamatester** [comment]
The veax adapter exports: 
        
 
 _______________________________________
    Dexs for 18/10/2023
    _______________________________________
    
    NEAR 👇
    Backfill start time: 27/4/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1697673598
    Daily volume: 338148.42
    Total volume: 11396924.91
    
    
    
    
    Done in 3.85s.

**Comment by dtmkeng** [comment]
fees data is incorrect?

**Comment by vladjito** [comment]
We want to remove it, we had back and forth discussion in discord about it. We don't think that we want to share the fee data on DeFillama when another DeFi projects on our chains don't.

**Comment by dtmkeng** [comment]
okay will disable 
there is two protocol `concordex-io ` and `veax ` ?

**Comment by vladjito** [comment]
Yep, they are both DEXs we have build on different chains

**Pull request merged**
