### PR TITLE
add equation-v3 volume and fees

### PR DESCRIPTION
**Pull request by RickGrimes2**

### CODE REVIEW

**Comment by llamatester** [comment]
The equation-v3 adapter exports: 
        
 
 _______________________________________
    Dexs for 14/5/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 13/5/2024
    Timestamp: 1715650017 (2024-05-14T01:26:57.000Z)
    Daily volume: 992.97 k
    Total volume: 4.76 M

**Comment by llamatester** [comment]
The equation-v3 adapter exports: 
        
 
 _______________________________________
    Fees for 14/5/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 13/5/2024
    Timestamp: 1715650031 (2024-05-14T01:27:11.000Z)
    Daily fees: 0
    └─ Methodology: Fees from open/close position and placed limit order (0.05%),  with invitation code (0.045%)
    Daily protocol revenue: 0
    └─ Methodology: Revenue is 50% of all collected fees

**Comment by dtmkeng** [comment]
why fees it show 0 ? seem the graph is return 0
```
{
  "data": {
    "protocolStatistics": [
      {
        "id": "Daily:1715558400",
        "stakeFee": "0",
        "architectFee": "0",
        "protocolFee": "0"
      },
      {
        "id": "Daily:1715644800",
        "stakeFee": "0",
        "architectFee": "0",
        "protocolFee": "0"
      },
      {
        "id": "Daily:1715731200",
        "stakeFee": "0",
        "architectFee": "0",
        "protocolFee": "0"
      }
    ]
  }
}
```
is it correct ?

**Comment by llamatester** [comment]
The equation-v3 adapter exports: 
        
 
 _______________________________________
    Dexs for 23/5/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 13/5/2024
    Timestamp: 1716450045 (2024-05-23T07:40:45.000Z)
    Daily volume: 1.68 M
    Total volume: 210.40 M

**Comment by llamatester** [comment]
The equation-v3 adapter exports: 
        
 
 _______________________________________
    Fees for 23/5/2024
    _______________________________________
    
    ARBITRUM 👇
    Backfill start time: 13/5/2024
    Timestamp: 1716450060 (2024-05-23T07:41:00.000Z)
    Daily fees: 122
    └─ Methodology: Fees from open/close position and placed limit order (0.05%),  with invitation code (0.045%)
    Daily protocol revenue: 81
    └─ Methodology: Revenue is 50% of all collected fees

**Pull request merged**
