### PR TITLE
Feat: Add a blacklist and simplify logic for `impermax-finance`

### PR DESCRIPTION
**Pull request by swan-of-bodom**
Adding our official blacklist to the fees adapter.

On another note if possible, could we please backfill the 29th? For some reason it is skipping that day. Could it be due to failed api calls our adapter is making or is there an error showing for that day?

image

Thank you!

### CODE REVIEW

**Comment by llamatester** [comment]
The impermax-finance adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees impermax-finance
    
    🦙 Running IMPERMAX-FINANCE adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 31 Oct 2024 00:00:00 GMT
    End Date:	Fri, 01 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Getting 4 tokens from gecko on scroll
    Getting 4 tokens from gecko on base
    Getting 2 tokens from gecko on optimism
    Getting 4 tokens from gecko on fantom
    Getting 12 tokens from gecko on arbitrum
    No price found on Gecko for token: 0x951a9094a2b8f3cbfac08364565c014a29d7a179
    Getting 5 tokens from gecko on avax
    Getting 9 tokens from gecko on ethereum
    No price found on Gecko for token: 0xa16001dd47f505b7b7c5639c710a52209e4e8904
    No price found on Gecko for token: 0x35f67c1d929e106fdff8d1a55226afe15c34dbe2
    No price found on Gecko for token: 0xa00d47b4b304792eb07b09233467b690db847c91
    Getting 6 tokens from gecko on polygon
    No price found on Gecko for token: 0xd30dc92b8ec0fa8de625768d208f51a93c10aff2
    ETHEREUM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    POLYGON 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 3
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 1
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    ARBITRUM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    FANTOM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 2
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    BASE 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 8.15 k
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 1.63 k
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    SCROLL 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 101
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 10
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    OPTIMISM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 89
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 9
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    REAL 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 315
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 32
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    AVAX 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.

**Comment by llamatester** [comment]
The impermax-finance adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees impermax-finance
    
    🦙 Running IMPERMAX-FINANCE adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 31 Oct 2024 00:00:00 GMT
    End Date:	Fri, 01 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Getting 4 tokens from gecko on base
    Getting 2 tokens from gecko on optimism
    Getting 4 tokens from gecko on fantom
    Getting 4 tokens from gecko on scroll
    Getting 5 tokens from gecko on avax
    Getting 12 tokens from gecko on arbitrum
    No price found on Gecko for token: 0x951a9094a2b8f3cbfac08364565c014a29d7a179
    Getting 6 tokens from gecko on polygon
    No price found on Gecko for token: 0xd30dc92b8ec0fa8de625768d208f51a93c10aff2
    Getting 9 tokens from gecko on ethereum
    No price found on Gecko for token: 0xa16001dd47f505b7b7c5639c710a52209e4e8904
    No price found on Gecko for token: 0x35f67c1d929e106fdff8d1a55226afe15c34dbe2
    No price found on Gecko for token: 0xa00d47b4b304792eb07b09233467b690db847c91
    ETHEREUM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    POLYGON 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 3
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 1
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    ARBITRUM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    FANTOM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 2
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    BASE 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 8.16 k
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 1.63 k
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    SCROLL 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 101
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 10
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    OPTIMISM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 89
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 9
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    REAL 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 315
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 32
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    AVAX 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.

**Comment by llamatester** [comment]
The impermax-finance adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees impermax-finance
    
    🦙 Running IMPERMAX-FINANCE adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 31 Oct 2024 00:00:00 GMT
    End Date:	Fri, 01 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Getting 4 tokens from gecko on base
    Getting 2 tokens from gecko on optimism
    Getting 4 tokens from gecko on fantom
    Getting 12 tokens from gecko on arbitrum
    No price found on Gecko for token: 0x951a9094a2b8f3cbfac08364565c014a29d7a179
    Getting 3 tokens from gecko on scroll
    Getting 5 tokens from gecko on avax
    Getting 9 tokens from gecko on ethereum
    No price found on Gecko for token: 0xa16001dd47f505b7b7c5639c710a52209e4e8904
    No price found on Gecko for token: 0x35f67c1d929e106fdff8d1a55226afe15c34dbe2
    No price found on Gecko for token: 0xa00d47b4b304792eb07b09233467b690db847c91
    Getting 6 tokens from gecko on polygon
    No price found on Gecko for token: 0xd30dc92b8ec0fa8de625768d208f51a93c10aff2
    ETHEREUM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    POLYGON 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 3
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 1
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    ARBITRUM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    FANTOM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 2
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    BASE 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 8.14 k
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 1.63 k
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    SCROLL 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 2
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    OPTIMISM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 89
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 9
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    REAL 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 315
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 32
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    AVAX 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.

**Comment by llamatester** [comment]
The impermax-finance adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees impermax-finance
    
    🦙 Running IMPERMAX-FINANCE adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 31 Oct 2024 00:00:00 GMT
    End Date:	Fri, 01 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Getting 4 tokens from gecko on base
    Getting 4 tokens from gecko on fantom
    Getting 5 tokens from gecko on avax
    Getting 3 tokens from gecko on scroll
    Getting 2 tokens from gecko on optimism
    Getting 12 tokens from gecko on arbitrum
    No price found on Gecko for token: 0x951a9094a2b8f3cbfac08364565c014a29d7a179
    Getting 9 tokens from gecko on ethereum
    No price found on Gecko for token: 0xa16001dd47f505b7b7c5639c710a52209e4e8904
    No price found on Gecko for token: 0x35f67c1d929e106fdff8d1a55226afe15c34dbe2
    No price found on Gecko for token: 0xa00d47b4b304792eb07b09233467b690db847c91
    Getting 6 tokens from gecko on polygon
    No price found on Gecko for token: 0xd30dc92b8ec0fa8de625768d208f51a93c10aff2
    ETHEREUM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    POLYGON 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 3
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 1
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    ARBITRUM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    FANTOM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 2
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    BASE 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 8.03 k
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 1.60 k
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    SCROLL 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 2
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    OPTIMISM 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 89
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 9
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    REAL 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 315
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 32
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.
    
    
    AVAX 👇
    Backfill start time: 23/10/2023
    End timestamp: 1730419199 (2024-10-31T23:59:59.000Z)
    Daily fees: 0
    └─ Methodology: Fees is the interest rate paid by borrowers
    Daily revenue: 0
    └─ Methodology: Percentage of interest going to treasury, based on each lending pool's reserve factor.

**Comment by dtmkeng** [comment]
will refill

**Pull request merged**
