### PR TITLE
Meowl fees adapter

### PR DESCRIPTION
**Pull request by 0xpeche**

### CODE REVIEW

**Comment by llamatester** [comment]
The meowl adapter exports: 
        
 
 _______________________________________
    Fees for 17/8/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 29/5/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1692316798
    Daily fees: 538.8257998431216
    Daily revenue: 538.8257998431216
    
    
    
    
    Done in 10.78s.

**Comment by dtmkeng** [comment]
hi, do you details about your protocol ? 
website or x

**Comment by 0xpeche** [comment]
> hi, do you details about your protocol ? website or x

henlo! Yeah I was wondering if I needed to open another pr somewhere else for that or use the same form as for the adapters template so there u go:

Name (to be shown on DefiLlama): Meowl
Twitter Link: https://twitter.com/meowlxyz
Website Link: https://meowl.xyz
Logo (High resolution, will be shown with rounded borders): https://i.imgur.com/mUEC1T2.png
Treasury Addresses (if the protocol has treasury): 0x842618c3f6E3E12edc5F02CC17561293e10CEb7d
Chain: Ethereum
Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): meowl
Short Description (to be shown on DefiLlama): Meowl is a Discord Bot that can be integrated into any server, enabling members to trade, share coins, set alerts, and monitor crypto positions directly within Discord. 
Token address and ticker if any: 0x1f1f26c966f483997728bed0f9814938b2b5e294 (MEOWL)
Category: Services
Github org/user: [meowlxyz](https://github.com/meowlxyz/)

❤️

**Comment by llamatester** [comment]
The meowl adapter exports: 
        
 
 _______________________________________
    Fees for 19/8/2023
    _______________________________________
    
    ETHEREUM 👇
    Backfill start time: 29/5/2023
    NO METHODOLOGY SPECIFIED
    Timestamp: 1692489598
    Daily fees: 168.3111774805777
    Daily revenue: 168.3111774805777
    
    
    
    
    Done in 7.07s.

**Pull request merged**
