### PR TITLE
Add MevX fee trackers

### PR DESCRIPTION
**Pull request by dev-mevx**
MEVX’s Social: 
Channel: https://t.me/MevX_TG
Chat Portal: https://t.me/MevX_Community
X: https://x.com/MevX_Official
Website: https://mevx.io
Discord: https://discord.gg/mevx

### CODE REVIEW

**Comment by llamatester** [comment]
The mevx.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees mevx.ts
    
    🦙 Running MEVX.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 01 Aug 2024 04:25:27 GMT
    End Date:	Fri, 02 Aug 2024 04:25:27 GMT
    ---------------------------------------------------
    
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/3958680/execute',
      method: 'POST',
      axiosError: 'invalid API Key',
      chain: 'solana'
    }

**Comment by dev-mevx** [comment]
@dtmkeng Could you please take a look on this PR. Thanks

**Comment by dev-mevx** [comment]
@dtmkeng dear sir it seems have some miss understanding
For https://defillama.com/fees/mevxs-social
Our Protocol is **MevX** not **Mevxs Social** please update for us.

**Comment by Define101** [comment]
@dev-mevx  will be good within 2 hours

**Pull request merged**
