### PR TITLE
add unidexv2

### PR DESCRIPTION
**Pull request by supakawaiidesu**

### CODE REVIEW

**Comment by llamatester** [comment]
The unidexv2.ts adapter exports: 
        
 
 _______________________________________
    Fees for 10/7/2023
    _______________________________________
    
    OPTIMISM 👇
    Backfill start time: 22/6/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 3733.023183
    Daily holders revenue: 1306.5581140499999
    Daily protocol revenue: 1306.5581140499999
    Daily revenue: 1306.5581140499999
    Daily supply side revenue: 1119.9069548999998
    Timestamp: 1689033598
    
    
    ERA 👇
    Backfill start time: 22/6/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 773.46325
    Daily holders revenue: 270.7121375
    Daily protocol revenue: 270.7121375
    Daily revenue: 270.7121375
    Daily supply side revenue: 232.038975
    Timestamp: 1689033598
    
    
    FANTOM 👇
    Backfill start time: 22/6/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 713.7830844
    Daily holders revenue: 249.82407953999999
    Daily protocol revenue: 249.82407953999999
    Daily revenue: 249.82407953999999
    Daily supply side revenue: 214.13492532
    Timestamp: 1689033598
    
    
    METIS 👇
    Backfill start time: 27/6/2023
    NO METHODOLOGY SPECIFIED
    Daily fees: 0
    Daily holders revenue: 0
    Daily protocol revenue: 0
    Daily revenue: 0
    Daily supply side revenue: 0
    Timestamp: 1689033598
    
    
    
    
    Done in 3.47s.

**Comment by supakawaiidesu** [comment]
heads up that metis should in fact be returning 0 as there is currently no active traders on metis for v2

**Comment by dtmkeng** [comment]
is there v2 on tvl ?

**Comment by supakawaiidesu** [comment]
> is there v2 on tvl ?

It uses the same pool's as before

**Comment by dtmkeng** [comment]
can i sum with v1 ?

**Comment by supakawaiidesu** [comment]
> can i sum with v1 ?

Yeah this would be better

**Comment by dtmkeng** [comment]
> > can i sum with v1 ?
> 
> Yeah this would be better

okay thank you

**Pull request merged**
